### ISSUE TITLE
The build on Windows is failing

### ISSUE THREAD

**Issue by adamyellen** [Haivision/srt#1]

**Comment by BobbleNablet** [comment]
I get this error, using VS2013 : fatal error C1083: Cannot open include file: 'sys/syslog.h': No such file or directory

**Comment by jordancrittenden** [comment]
I also get an error looking for <arpa/inet.h>

**Comment by ethouris** [comment]
Whoever can, please confirm that it can be compiled on VS. The fix I provided makes it compile and work correctly on VS, just need some second pair of eyes to confirm that there are no more problems.
