### ISSUE TITLE
stransmit does not support multicast input on windows

### ISSUE THREAD

**Issue by lewk2** [Haivision/srt#101]
When running with master or v1.2, stransmit reports 'bind: no error' if specifying a multicast source for a UDP input.

For example:

./stransmit -r:1000 udp://@239.186.31.73:1234 -c:1328 srt://10.186.4.41:9000

My test server does have multiple NICs installed, and I have attempted to 'steer' the choice of multicast adapter with such a URL (trying both target adapter inside host in URL, and adapter of 'source' of multicast):

./stransmit -r:1000 udp://10.184.3.73@239.186.31.73:1236 srt://10.186.6.104:9000

However, I have no luck.

As a receiver, I can confirm that stransmit will output to multicast (although I'm not having a lot of luck passing arguments to bind the output to a chosen adapter...)

**Comment by ethouris** [comment]
Well, you've run into experimenting with URI, but note that there's no intelligent robot sitting behind this :). The @ character is only allowed before the HOST part and it's simply turned into the `multicast=true` attribute. If you want to specify the adapter for UDP, use `adapter` attribute - so your URI should sound like:

`udp://@239.186.31.73:1236?adapter=10.184.3.73'

Currently the `adapter` attribute is used exclusively with multicast (so, you should use @ also for the output, if you have such a situation).

**Comment by lewk2** [comment]
I tried all sort of combinations - never any luck.

Here, I think you can see below what I have entered - is this looking correct?

![image](https://user-images.githubusercontent.com/1837744/30913556-8db1a4ca-a388-11e7-9799-61817d7bc53c.png)

**Comment by ethouris** [comment]
If stransmit can't read under this condition, then - unless some completely unknown disaster has happened with strasmit - there's some problem that makes it impossible to read UDP packet this way on that machine.

Stransmit can also work without SRT, and it should be also possible, for example, to read from UDP to file. If stransmit wouldn't read anything, then you can check this using any other software tool that can read UDP to file the same way (netcat?), to see if this is stransmit's problem.

**Comment by lewk2** [comment]
I'm running on one of our test boxes used heavily for multicast. The windows firewall is totally off.

I have a tool we made which does UDP packet reading - it can pick up the same stream perfectly fine:

![image](https://user-images.githubusercontent.com/1837744/30924641-43262c68-a3a7-11e7-9759-102e950aa3ea.png)

The command that launched this tool was:

 .\TsAnalyser.exe stream -m 239.186.31.73 -g 1234 -a 10.186.3.71

The error kicks back instantly with 'bind: No error' - it is unlike a fault when packets cannot arrive; it is just like something is going wrong with the socket setup.

**Comment by ethouris** [comment]
Alright, have you tried:

`.\stransmit.exe udp://@239.186.31.73:1236?adapter=10.184.3.71 output.ts -v`

Please try, tell me if you can see anything and what is in the resulting `output.ts` file. If nothing happens, this is some serious problem that should be taken care of.

(Please note that -v causes that every single UDP packet is reported in a single text line in stdout, and this thing is usually a dire performance killer on Windows, so it's completely ok if you have the TS output file scrapped in this case)

**Comment by lewk2** [comment]
This also triggers a 'bind: No error' fault.

![image](https://user-images.githubusercontent.com/1837744/30925539-1582a810-a3aa-11e7-987a-099a686c563d.png)

(Please note, I made a typo earlier that propagates this thread where I accidentally marked the multicast adapter inside this box as '10.184.3.71' instead of the actual '10.186.3.71' - this was just a fault in my write up, the correct adapter was used when testing.

I've now completed an auto-build of the SRT binaries through extension of the appveyor.yml - you can grab my binaries here:

https://ci.appveyor.com/project/cinegy/srt

I'm just finishing my trimmed back managed wrapper and C# receiver client - this code is now visible on our GitHub:

https://github.com/Cinegy/Cinegy.SRT

I am just connecting up AppVeyor to build these too - the other project binaries all get wrapped up now so I can keep this development environment clear from the core SRT (to more clearly understand where we screw up versus the library having problems).

Because I never like to trust a single point failure, I'm going to test these binaries on a few other Windows machines to get some more data with stransmit.

**Comment by ethouris** [comment]
Ok, now I'm not sure if the multicast reading is properly coded. Looxlike it makes the `bind` called with the multicast address, this probably is wrong. I'll take a closer look at that tomorrow.

**Comment by ethouris** [comment]
Alright, I've submitted the pull request that fixes this problem, but it's submitted to the `dev` branch. I'd be grateful if you can check and confirm it with this branch, and backport it to `master` if possible. Changes in `CMakeLists.txt` and `appcommon.hpp` are straightforward, just the changes done in `transmitmedia.cpp` should be applied here to `stransmit.cpp`.

**Comment by lewk2** [comment]
OK- I hand-ported the relevant change for multicast (had to skip all the error changes, too much difference between 'dev' and 'master'.

I can confirm that this now works - although the 'adapter' argument must be specified (at least in my tests) or the bind still fails.

I can now source from multicast (making it much easier to run sources on more test machines). 

I submitted this highly specific change as a pull request, so I don't know if this issue now stays open until that is merged, or we close it now.

Pull request is 
Master patch mcast stransmit win #105

**Comment by lewk2** [comment]
Please note, this might need some further refinement, since it seems to attempt an exclusive lock on the UDP port on the PC (regardless of multicast group). I had a few emitters on port 1234 (differing by multicast group address) and stransmit would not work unless I first stopped this.

I might have a play later to see if I can see what socket options need to be kicked to remove any exclusive locking.

However, while the whole EXE remains unstable, further refinement to this stage is not a priority.

**Comment by ethouris** [comment]
The `SO_REUSEADDR` flag should fix the above mentioned problem.

**Comment by lewk2** [comment]
Sorry, got sidetracked with other tasks (including my main test server motherboard breaking with a power problem).

Will try and set this flag now that I have new machines to test with, and report results.

**Comment by lewk2** [comment]
Added to PR 105, waiting for merge or more comments

**Comment by lewk2** [comment]
Closing as fixed by PR105
