### ISSUE TITLE
[FR] How to set SRT StreamID by VLC?

### ISSUE THREAD

**Issue by amjy** [Haivision/srt#1015]
How to set SRT StreamID by VLC?

**Comment by maxsharabayko** [comment]
As of now, VLC does not support this.
This FR should better be submitted to VLC.

**Comment by tomasz-lasko** [comment]
I saw that someone mentioned this case on VLC's forum:

https://forum.videolan.org/viewtopic.php?f=7&p=506009

**Comment by justinjoy** [comment]
FYI, StreamID patch[1] for VLC has landed into the master already. 
I think it should be able to be set when VLC nightly build[2] is used.

[1] https://code.videolan.org/videolan/vlc/-/commit/a55c95a9ccb051066b73f103f1a1e25586a97773
[2] https://nightlies.videolan.org/

**Comment by tomasz-lasko** [comment]
Thank you! So master is 4.0 nightly build, not 3.0 nightly - is that right?
