### ISSUE TITLE
[BUG] Bandwidth Estimation with SRT 1.4.1 is always 0

### ISSUE THREAD

**Issue by lukasmahr** [Haivision/srt#1021]
**Describe the bug**
I tried to transfer a video stream via gstreamer's srtsink and srtsrc and recognized that the stats property "bandwidth-mbps" is always 0.
Using SRT Version 1.4.0 the bandwidth estimation works properly.

**To Reproduce**
1. Create a gstreamer pipeline like: `videotestsrc ! x264enc ! mpegtsmux ! srtsink uri=srt://:8888`
2. Run the gstreamer pipeline and print the [stats](https://gstreamer.freedesktop.org/documentation/srt/srtsink.html?gi-language=c#srtsink:stats) property
3. Connect a client to get stats: `gst-launch-1.0 srtsrc uri=srt://127.0.0.1:8888 ! tsparse ! tsdemux ! h264parse ! avdec_h264 ! videoconvert ! autovideosink`
4. The field "bandwidth-mbps" is always 0

**Expected behavior**
The stats-property "bandwidth-mbps" should display a realistic estimation of the available bandwidth (like SRT version 1.4.0 does)

**Desktop (please provide the following information):**
 - OS: Arch Linux
 - SRT Version: 1.4.1

**Additional context**
I used GStreamer version 1.16.2

**Comment by maxsharabayko** [comment]
This can be a mismatch in ABI. v1.4.1 has some changes in the order of the stats structure elements, to be more compliant to v1.3.4. 
Can you confirm you have performed a clean rebuilt with SRT v1.4.1?

**Comment by lukasmahr** [comment]
Thank you for your response!

I created a fresh example here: https://github.com/lukasmahr/srt-example
It contains 2 docker containers.

One container (port 8887) running the code with SRT 1.4.0 that successfully logs the bandwidth estimation.
The other container (port 8888) is running with SRT 1.4.1 and always logs 0 as bandwidth estimation.

**Comment by justinjoy** [comment]
> One container (port 8887) running the code with SRT 1.4.0 that successfully logs the bandwidth estimation.
> The other container (port 8888) is running with SRT 1.4.1 and always logs 0 as bandwidth estimation.

This is because your pre-built gstreamer was built with srt 1.4.0.
SRT package of archlinux doesn't have information of SRT ABI break between two versions so the pre-built gstreamer isn't built again even though srt package is updated.

I guess quick solution is to build `gst-plugins-bad` from source when you create docker image.

**Comment by justinjoy** [comment]
And, I think this issue isn't  a BUG of SRT. Rather, it's just that ABI break information has been delivered to package maintainers, or users.
