### ISSUE TITLE
1.3 release?

### ISSUE THREAD

**Issue by tbekiares** [Haivision/srt#103]
Hi, 

this press release (https://www.haivision.com/about/press-releases/srt-open-source-video-transport-project-adds-fast-file-transfer-stream-multiplexing/) from 9/15/17 indicates that v1.3 of SRT is now available, yet I don't see it as a release or tag in this repository. When will 1.3 be released?

thanks!

**Comment by heidabyr** [comment]
Hi,

you're right, it's not yet tagged. We are working on reviewing and testing the latest code changes and hope to be able to tag the release soon.

- Marc

**Comment by adamyellen** [comment]
1.3 is in a branch named 'dev'. Please help us test this important release!

**Comment by rmsoto** [comment]
Hello! I get this error after compiling dev branch:

> srt-dev$ ./srt-file-transmit file:///home/ovencoder/Blackmagic_Desktop_Video_Linux_10.9.3.tar srt://:9001            
> ./srt-file-transmit: error while loading shared libraries: libsrt.so.1: cannot open shared object file: No such file or directory

If I use the master one everything is ok.

Any clue?

Thanks!

**Comment by ethouris** [comment]
No clue, I can't repro this. But let's try to analyze it. Please check the following:
* After building, do you have the `libsrt.so.1.3.0` file with `libsrt.so.1` and `libsrt.so` links in the build directory?
* What is shown in the `libsrt` position in the output of `ldd ./srt-file-transmit`?

(Note: You can compile SRT as static using `--disable-shared` in configure or `ENABLE_SHARED=0` in cmake; just note that this should be done only for testing)

**Comment by rmsoto** [comment]
Hello,

 links in the build directory seems to be ok

> lrwxrwxrwx  1 ovencoder ovencoder      11 Dec 13 06:25 libsrt.so -> libsrt.so.1
> lrwxrwxrwx  1 ovencoder ovencoder      15 Dec 13 06:25 libsrt.so.1 -> libsrt.so.1.3.0

after doing lld I get:

> /srt-dev$ ldd ./srt-file-transmit
>         linux-vdso.so.1 (0x00007ffcb21fb000)
>         libsrt.so.1 => not found
>         libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f7420979000)
>         librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f7420771000)
>         libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f742056d000)
>         libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f7420262000)
>         libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f741ff61000)
>         libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f741fd4b000)
>         libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f741f9a0000)
>         /lib64/ld-linux-x86-64.so.2 (0x00007f7420b96000)

Maybe is the not found one...let´s try to put it there,,,

**Comment by rmsoto** [comment]
Yessss...cping the library to /lib/x86_64-linux-gnu/ solves the problem....

This happened to me in 2 different machines running debian jessie.

Now the output of ldd is:

> ldd ./srt-file-transmit                                                              ldd:
> ldd: ./ldd: No such file or directory
> ./srt-file-transmit:
>         linux-vdso.so.1 (0x00007ffe5ab75000)
>         libsrt.so.1 => /lib/x86_64-linux-gnu/libsrt.so.1 (0x00007fe628985000)
>         libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fe628768000)
>         librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007fe628560000)
>         libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fe62835c000)
>         libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fe628051000)
>         libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fe627d50000)
>         libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fe627b3a000)
>         libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fe62778f000)
>         libssl.so.1.0.0 => /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007fe62752e000)
>         libcrypto.so.1.0.0 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007fe627132000)
>         /lib64/ld-linux-x86-64.so.2 (0x00007fe628c50000)

**Comment by ethouris** [comment]
AFAIR there's something like that the "assumed path to a shared library" being the location directory of the executable not always works.

I have seen that there's `RUNPATH` entry in the result of `objdump -x`, which is `../lib`. This was intended to make it work when `srt-file-transmit` is in `bin` directory, and the library in `lib` directory.

I have discovered a weird behavior of `LD_LIBRARY_PATH` and probably that was why I thought it will work: When you have an **empty entry** in the value of this variable and at least two entries, then the libraries from the current directory matter. This doesn't work when it contains nothing or a single space, but it does work, when it contains a single colon. In this case I have:

`        libsrt.so.1 (0x00007fc9170a9000)`

If I set a single **dot** in this variable then I have:

`        libsrt.so.1 => ./libsrt.so.1 (0x00007f91ee125000)`

But if I **unset** `LD_LIBRARY_PATH` (or set it to empty string), then it says that libsrt.so.1 is not found.

I think we need to change this forced rpath to the following (not sure if this is the right solution):

`-Wl,-rpath,../lib,../lib64,.`

**Comment by rmsoto** [comment]
Ohhh...nice, so we can set several inputs for one output and vice versa... great feature! Tomorrow I will test it.

Thanks!

**Comment by mks75** [comment]
Hi,
While trying to use ./stransmit, getting the following error.
./stransmit: error while loading shared libraries: libsrt.so.1: cannot open shared object file: No such file or directory

How to fix this? Please elaborate on the required commands.
Thanks

**Comment by ethouris** [comment]
Yeah, I think I know where the problem is, but we need to agree upon the fix.

I found a workaround: This will work if you set `LD_LIBRARY_PATH` (environment variable) to either a single `.`, or if you have something in this variable, add an empty entry (a `:` that is exactly at the beginning or end of the contents). With emtpy or white string or nonexistent variable, you'll have this error.

**Comment by maxlovic** [comment]
Check together with #499.

**Comment by snowgames95** [comment]
Hello, I am getting the following error message. I have no idea where to look. I am also still looking for how to include SRT in ffmpeg for Raspberry Pi OS. Does anyone have any idea?
pi@raspi41:~ $ ffmpeg -version
ffmpeg: error while loading shared libraries: libsrt.so.1.4: cannot open shared object file: No such file or directory
pi@raspi41:~ $ pkg-config --modversion srt
1.4.2
