### ISSUE TITLE
play publish command

### ISSUE THREAD

**Issue by HuyaJohn** [Haivision/srt#1038]
Hi, Is there any option to determine client is play or publish?
Caller or listener mode is no enough, how a SRT server know a new client is want to play stream or publisher stream, like rtmp command Play/Publish.
Thanks.

**Comment by maxsharabayko** [comment]
The mode is supposed to be determined via [SRT Access Control](https://github.com/Haivision/srt/blob/master/docs/AccessControl.md) technique, using the StreamID field of the handshake.
