### ISSUE TITLE
[BUG] ffmpeg4.0 use newest srt code 

### ISSUE THREAD

**Issue by Luosh** [Haivision/srt#1050]
I compile ffmpeg 4.0 with enable-libsrt option, and the libsrt is newest  1.4.x

compile  completed, then I try this commands to test srt protocol , but connection is disconnect  after  5 seconds. The caller mode side print error message  "Operation not supported: Invalid socket ID" .  Some files like 720p.mp4   occur  error are 100%,  but some other files run ok.

libsrt version 1.3.x run ok  by same command . 

caller :
```shell
ffmpeg -re -i  ./720p.mp4 -vcodec copy -acodec copy -f mpegts -pkt_size 1316 "srt://127.0.0.1:8080?mode=caller&pkt_size=1316"
```

listener:
```shell
ffplay  "srt://:8080?mode=listener"
```

something different between 1.3.x and 1.4.x?

Forgive me for bad english

**Comment by ethouris** [comment]
I think I saw that before, exactly in ffmpeg. Please refer to #427, might be something similar.

**Comment by Luosh** [comment]
@ethouris 
Thank you for your answer, the problem seems different

**Comment by ethouris** [comment]
Still, if you try to retest using the method described in this issue, and it works, it simply means that it's a problem inside ffmepg, so it should be probably reported there.

This still might be the case that either it's some bug in SRT that has just popped up in an unusual implementation in ffmpeg, or it's the problem in the ffmpeg implementation. Hard to say because I don't know how it's implemented in ffmpeg. Still, reporting this problem to ffmpeg, with referring to THIS issue, would be needed to find out where the problem is. If you did this already, please paste the link.

**Comment by Luosh** [comment]
Sorry, I could't find link to report this issue in `https://github.com/FFmpeg/FFmpeg`. 
I recompiled libsrt with --enable-heavy-logging --enable-logging .  
Log print some important information [srt.log](https://github.com/Haivision/srt/files/4025435/srt.log)


It seems that for some reason the socket is judged to be timeout.
Is the bitrate of the stream  greater than 4Mbps or some other parameters not set

```shell

[srt @ 0x33a8c80]  (checkExpTimer)[9206]: EXP TIMER: count=16/16 elapsed=5277681/5000000us
[srt @ 0x33a8c80]  (updateCC)[6530]: updateCC: EVENT:checktimer
[srt @ 0x33a8c80]  (updateCC)[6603]: udpateCC: emitting signal for EVENT:checktimer
[srt @ 0x33a8c80]  (updateCC)[6621]: updateCC: updated values from congctl: interval=9 us (9.856us) cgwindow=8.19e+03
[srt @ 0x33a8c80]  (updateCC)[6625]: udpateCC: finished handling for EVENT:checktimer
[srt @ 0x33a8c80]  (checkExpTimer)[9186]: CONNECTION EXPIRED after 5293ms
[srt @ 0x33a8c80]  (pop)[318]: SND:pop: requesting packet from @235521846 STATUS: -Listening -Connecting +Connected +Closing -Shutdown +Broken +PeerHealth +Opened 
[srt @ 0x33a8c80]  (worker)[1200]: @235521846: SOCKET broken, REMOVING FROM RCV QUEUE/MAP.


--------

[srt @ 0x33a8c80]  (checkBrokenSockets)[1529]: moving socket to CLOSED: 235521846
m_Sockets.erase()
[srt @ 0x33a8c80]  (garbageCollect)[1892]: GC: sleep 1 s
[srt @ 0x33a8c80]  (wait)[630]: CEPoll::wait: EVENT WAITING: CHECKPOINT
[srt @ 0x33a8c80]  (wait)[519]: CEPoll::wait: REPORTED 0/0
[srt @ 0x33a8c80]  (wait)[617]: CEPoll::wait: Total of 0 READY SOCKETS
[srt @ 0x33a8c80]  (wait)[624]: ... not waiting longer - timeout
m_Sockets.end(1)
m_Sockets.end(1)
[srt @ 0x33a8c80] libsrt_network_wait_fd:174 Operation not supported: Invalid socket ID
av_interleaved_write_frame(): Unknown error occurred
Error writing trailer of srt://127.0.0.1:8080?mode=caller&pkt_size=1316: Unknown error occurred
```

**Comment by ethouris** [comment]
When this happens:
```
[srt @ 0x33a8c80]  (checkExpTimer)[9186]: CONNECTION EXPIRED after 5293ms
```
it means that the other side didn't respond in time. It would be interesting to see the logs from both sides, as well as the pcap file on the side that has reported the above.

Not sure also what the parameters were. Please try to reproduce the test first with replacing the SRT medium in ffmpeg with pipes and `srt-live-transmit`, according to the instruction provided in the referred issue. This is important to rule out some functional areas from causing the trouble.

**Comment by Luosh** [comment]
1. caller  attach log file [srt-caller.log](https://github.com/Haivision/srt/files/4025795/srt-caller.log)

```shell
ffmpeg -re -i ~/work/svnd/mcu/res/1080p/摩天大楼.mp4 -vcodec copy -acodec copy -bsf:v h264_mp4toannexb -f mpegts pipe:1 | ./srt-live-transmit file://con srt://127.0.0.1:8080 -v -ll 7
```
2. listener  attach log file [srt-listener.log](https://github.com/Haivision/srt/files/4025797/srt-listener.log)

```shell 
 ./srt-live-transmit srt://:8080 file://con -v -ll 7 | ffplay -
```
In this way ,  listener side  is auto reconnected every few seconds. 
log print 
```
SRT source disconnected   4 aq=   13KB vq=  234KB sq=    0B f=0/1   
SrtCommon: DESTROYING CONNECTION, closing sockets (rt%594505166 ls%-1)...
SrtCommon: ... done.
Opening SRT source listener on :8080
Binding a server on :8080 ...
 listen...
 accept... 
 connected.
Accepted SRT source connection

```

How can I upload pcap file?   I think this sreenshot shows something
![srt-pcap](https://user-images.githubusercontent.com/3368806/71815181-98de2600-30b9-11ea-8019-93cd30c390af.png)

**Comment by ethouris** [comment]
Ok, I analyzed the log a bit, it looks like there is a problem there. We need to investigate it deeper. I'm not sure I can reproduce it myself, but could you please do one more test for me?

The same as you did here, just replace the listener and caller configurations. That is, make the sending party open SRT in listener mode and the receiver in caller mode.

As I traced the logs there's some very weird "CONNECTION EXPIRED" message on the caller side, which should not happen as it does receive ACK messages, although the difference between reported time and the time of the event points the moment of connection. Looxlike the connection timeout watchdog somehow wasn't updated since the connecting time. By inverting the connection sides I could at least know whether it was really the sending side (regardless of the connection side) getting this connection expired event.

**Comment by Luosh** [comment]
Ok, I replace the listener and caller configurations like this 
```shell
ffmpeg -re -i ~/work/svnd/mcu/res/1080p/摩天大楼.mp4 -vcodec copy -acodec copy -bsf:v h264_mp4toannexb -f mpegts pipe:1 | ./srt-live-transmit file://con srt://:8080 -v -ll 7
```
```shell
./srt-live-transmit srt://127.0.0.1:8080 file://con -v  | ffplay -
```
this is the log file [srt-send-listener.log](https://github.com/Haivision/srt/files/4028567/srt-send-listener.log)  and pcap picture 
![srt-pcap](https://user-images.githubusercontent.com/3368806/71861705-3a08c300-3132-11ea-9c11-0bd51c7df092.png)

**Comment by Luosh** [comment]
I try modify like this  can fix this bug, but the video is not smooth looked

```c++
--- a/srtcore/core.cpp
+++ b/srtcore/core.cpp
@@ -7262,7 +7262,8 @@ void CUDT::processCtrlAck(const CPacket &ctrlpkt, const steady_clock::time_point
 void CUDT::processCtrl(CPacket &ctrlpkt)
 {
     // Just heard from the peer, reset the expiration count.
-    m_iEXPCount = 1;
+   m_iEXPCount = 1;
+   m_tsLastRspTime = steady_clock::now();
     const steady_clock::time_point currtime = steady_clock::now();
     bool using_rexmit_flag = m_bPeerRexmitFlag;

```

**Comment by Luosh** [comment]
> I try modify like this can fix this bug, but the video is not smooth looked
> 
> ```c++
> --- a/srtcore/core.cpp
> +++ b/srtcore/core.cpp
> @@ -7262,7 +7262,8 @@ void CUDT::processCtrlAck(const CPacket &ctrlpkt, const steady_clock::time_point
>  void CUDT::processCtrl(CPacket &ctrlpkt)
>  {
>      // Just heard from the peer, reset the expiration count.
> -    m_iEXPCount = 1;
> +   m_iEXPCount = 1;
> +   m_tsLastRspTime = steady_clock::now();
>      const steady_clock::time_point currtime = steady_clock::now();
>      bool using_rexmit_flag = m_bPeerRexmitFlag;
> ```
@ethouris I think i fixed this issue, thank you! 
 By srt-live-transmit video is smoonth .

**Comment by ethouris** [comment]
Wow, I just wanted you to make an extra test, I didn't know you'll come through for me, thanks a lot!

I checked also previous versions, and yes, it contained the update of the last response time also in `processCtrl` function, someone has made a mistake and removed it. So, yes, that's the correct fix.
