### ISSUE TITLE
Proposed binary installer for libsrt on Windows

### ISSUE THREAD

**Issue by lelegard** [Haivision/srt#1068]
Hi,

#### The problem
While libsrt is now available in the repos of the main Linux distros and macOS, building an application using SRT on Windows is, at best, challenging.

There is no precise build instructions for libsrt on Windows, only guidelines. It is currently impossible to automate (from scratch) the build of a Windows application using SRT. This is however required when you do continuous integration and build on bare Windows machines (see "GitHub Actions" for instance).

#### Proposed solution
Since I need it, I wrote a bunch of scripts to automate the build of a binary installer for libsrt. When you install it, you get pre-compiled static libraries for libsrt, header files and a Visual Studio property file to reference libsrt.

The scripts are here: https://github.com/tsduck/srt-win-installer

The project contains only scripts, no copy of libsrt source code or any other dependent code. When building an installer, the scripts start with cloning the required repositories from GitHub.

The first release, for libsrt 1.4.1, is here: https://github.com/tsduck/srt-win-installer/releases

I did this because I needed it for the [TSDuck](https://github.com/tsduck/tsduck) project. However, if the libsrt team is interested in taking over those scripts so that a proper binary installer can be built as part of the libsrt project, I am ready the release the ownership.

Let me know.
-Thierry Lelégard, author of [TSDuck](https://tsduck.io)

**Comment by maxsharabayko** [comment]
Hi @lelegard 
Thank you very much for your contribution, and for sharing this with us!

Building SRT for windows is indeed harder compared to building for Linux or MacOS. This is something we are looking forward to improve.
Now SRT can be built using **vcpkg** packet manager ([link](https://maxsharabayko.github.io/srtcookbook/getting-started/vcpkg-library-manager/)). But this is not yet documented.

I think we can include the scripts in the upcoming v1.5.0 SRT release.
This was also requested in #586 

Please let us know once support for SRT is added to TSDuck. This would be great news for the comunity!

It would be cool to see you in our `#development` channel on Slack: [link to join](https://slackin-srtalliance.azurewebsites.net/).

**Comment by maxsharabayko** [comment]
Checked out the new version of TSDuck. It already supports SRT. This is awesome! :)

**Comment by lelegard** [comment]
> It would be cool to see you in our #development channel on Slack: link to join.

I am the author and maintainer of TSDuck but the SRT plugin is not mine. This is a code contribution from @spnngl. He knows SRT while I don't.

As the maintainer of TSDuck, I needed to automate the integration of libsrt inside the project. This is required for continuous integration and for users who want to build TSDuck on Windows without caring much about the details of third-party libraries. This is why I developed those scripts.

On Windows, package managers such as vcpkg are fine as long as you already use them. But this is far from a standard. There are other similar systems such as Chocolatey (used in some CI systems). But they are not standard, even conflicting with each other. These are nice technical attempts but hopeless as widely accepted standards for everyone.

This is different in Linux where, depending on distros, everybody use rpm or dpkg. Even on macOS, while not Apple-provided, Homebrew is a de-facto standard for all open-source software. Libsrt is already available on all of them (rpm, dpkg, homebrew).

On Windows, the "standard" is either standalone .exe installers or MSI packages (and even sometimes MSI package inside an .exe installer!) By using this method, any developer can automate the installation of the libsrt binaries without having to install a specific package manager. In my project, there is a simple PowerShell script named `install-libsrt.ps1` which automatically downloads and installs the latest version of the libsrt binaries. Very useful for automation.

**Comment by lelegard** [comment]
By the way, basic tests with TSDuck exhibit a problem with SRT reception on Windows. Details are here: https://github.com/tsduck/tsduck/issues/506

The problem is specific to Windows (not seen on Linux or macOS). The author of the SRT plugin for TSDuck uses only Linux and has no way to troubleshoot this.

I do not know if this is an SRT issue, an integration issue, a Windows-specific build issue. Are these symptoms familiar to you?

**Comment by maxsharabayko** [comment]
Some notes on the Windows installer.
SRT v1.5.0 can be built without pthreads, and it is preferred to use C++11 on Windows.
Not sure yet how to integrate the proposed installer into SRT repo. Probably it should be a separate repo.
Maybe [WIX Toolset](https://wixtoolset.org/documentation/manual/v3/howtos/) can be used. 🤔 
Enabling CI-CD and Generating MSI Installations: [link](https://dzone.com/articles/azure-devops-pipeline-enabling-ci-cd-and-generatin).

**Comment by lelegard** [comment]
Hi @maxsharabayko 

> SRT v1.5.0 can be built without pthreads, and it is preferred to use C++11 on Windows.

Definitely better to remove the dependency on pthread, especially on Windows.

Currently, the version in the repo identifies itself as "1.4.1-315-931aae0". Can it be compiled without pthread?

> Not sure yet how to integrate the proposed installer into SRT repo. Probably it should be a separate repo.

Not really. I would recommend a dedicated sub-directory containing all files to build the Windows installer. This is what I do in project [TSDuck](https://github.com/tsduck/tsduck).

Additionally, you can publish the binary installed as assets of a GitHub release. This is easier for users to find the right installer. Users don't really care how to build SRT in Windows, they just want to use it. So, when they look into [SRT](https://github.com/Haivision/srt) project, they expect to find binary installers in the release section.

> Maybe [WIX Toolset](https://wixtoolset.org/documentation/manual/v3/howtos/) can be used. 🤔

I use NSIS but other installer systems are fine, I suppose.

**Comment by maxsharabayko** [comment]
Hi @lelegard 

Thank you for your comments.

> Currently, the version in the repo identifies itself as "1.4.1-315-931aae0". Can it be compiled without pthread?

Yes, 931aae0 is the latest master. It already supports C++11 threads. cmake option `-DENABLE_STDCXX_SYNC=ON` can be used to enable C++11 threads.
For example, see the CI pipeline for windows with C++11: [link](https://github.com/Haivision/srt/blob/master/.github/workflows/cxx11-win.yaml).

**Comment by lelegard** [comment]
Hi @maxsharabayko 

Thanks. I have just updated the project [srt-win-installer](https://github.com/tsduck/srt-win-installer). I have removed any reference to pthread. The installer is built correctly, installed correctly and TSDuck is build correctly with this new version.

**Comment by lelegard** [comment]
Rebuilt 1.4.3, see https://github.com/tsduck/srt-win-installer/releases

SRT team, wouldn't you like to take over binary windows installers? It would make more sense to have binaries for your product published by you rather than from a project using libsrt (here TSDuck).

If you integrate the [srt-win-installer](https://github.com/tsduck/srt-win-installer) project (it only contains a few scripts) as a subdirectory of your build directory, publishing binaries for a new version is straightforward. For instance, to produce the binaries for 1.4.3, I just typed `.\build-all.ps1 -Tag v1.4.3` from a PowerShell window. And I collected `libsrt-1.4.3.exe` a few minutes later. I can propose a pull request for that. Just tell me if you are ready to integrate the feature.

**Comment by maxsharabayko** [comment]
Hi @lelegard 
Thank you, I have added the installer to v1.4.3 release artifacts.

If you could prepare a PR, that would be extremely helpful! Please place related scripts in [/srtipts/win-installer](https://github.com/Haivision/srt/tree/master/scripts) folder.

**Comment by lelegard** [comment]
Hi @maxsharabayko 

> If you could prepare a PR, that would be extremely helpful! Please place related scripts in /srtipts/win-installer folder.

The PR was submitted as #1995.
