### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by oviano** [Haivision/srt#1069]
I am currently using a slightly modified version of 1.4.0 in my video stream project (emustream.tv).

I recall some discussion about being able to compile on Windows without needing pthreads (using std::thread etc).

It got me wondering if there is a roadmap of development for SRT?

**Comment by maxsharabayko** [comment]
Hi @oviano 
Yes, the work is in progress. See PR #800 and related PRs. Planned for v1.5.0 release.

Meanwhile, some additional build instructions can be found [here](https://maxsharabayko.github.io/srtcookbook/getting-started/vcpkg-library-manager/).

**Comment by maxsharabayko** [comment]
Roadmap for C++11 feature: #1103

**Comment by maxsharabayko** [comment]
Closing this as resolved by #1103.
