### ISSUE TITLE
Rename CSndLossList::remove()

### ISSUE THREAD

**Issue by maxsharabayko** [Haivision/srt#1093]
The function `CSndLossList::remove(int32_t seqno)` removes all sequence numbers (elements) that are not greater than the argument.
The name "remove" adds confusion, that the function will remove only the element in the argument.
Therefore, it is suggested to rename the function to one of the following:
* `removeUpTo(seqno)`
* `removeLessEqual(seqno)`
* `removeLE(seqno)`

At the moment this will introduce unwanted conflicts with the ongoing merging of the network bonding feature.

**Comment by ethouris** [comment]
I think `removeUpTo` would be most appropriate. Note that these are circular numbers and the terms of "less/greater" do not apply to it. Better are "earlier/later". This function will remove elements whose sequence numbers are not **later** than the argument.
