### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [Haivision/srt#1101]
I would like to point out that identifiers like “[`INC__SRT_UTILITIES_H`](https://github.com/Haivision/srt/blob/a080a3f6393cfc9216f9514ba5b2d4db7aa000df/srtcore/utilities.h#L16 "Update candidate")” and “[`__UDT_H__`](https://github.com/Haivision/srt/blob/eef66e533a632ced339a740d0eeb389fba6d1d66/srtcore/udt.h#L67 "Another update candidate")” [do eventually not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by maxsharabayko** [comment]
Hi @elfring Thanks for pointing out.

**Comment by elfring** [comment]
Would you like to [rename any more identifiers](https://github.com/Haivision/srt/blob/7315e924834b064b3d7207de713ffd6fc63eea80/srtcore/utilities.h#L592 "Update candidate: typename _Tp1")?

**Comment by maxsharabayko** [comment]
Hi @elfring. Could you recommend a static check tool that can list all those remaining identifiers, so that we confirm all are renamed? Looks like SonarCloud we use does not show this type of issues. 🤔

**Comment by elfring** [comment]
* I noticed [such questionable implementation details](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?") just by looking at source code displays (from GitHub for example).
* How do you think about to take another look at [linked information sources](https://wiki.sei.cmu.edu/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-AutomatedDetection "Advanced source code analysis")?

**Comment by ethouris** [comment]
Please be precise about what exactly violation is to be fixed. I found some violations for an identifier beginning with _ and uppercase letter. Anything else?

**Comment by ethouris** [comment]
I found some violations for an identifier beginning with _ and uppercase letter. Anything else?

**Comment by ethouris** [comment]
I added #1328 to track these changes. Feel free to propose more fixes in this topic.

**Comment by maxsharabayko** [comment]
> How do you think about to take another look at linked information sources?

[SonarCloud](https://sonarcloud.io/dashboard?id=srt) seems to have this [rule](https://rules.sonarsource.com/cpp/RSPEC-978), but somehow it does not show these errors in the current master.
