### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [Haivision/srt#1104]
Would you like to add more error handling for return values from functions like the following?
- [pthread_cond_init](https://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_cond_init.html "Initialize a condition variable.") ⇒ [CUDTSocket::construct()](https://github.com/Haivision/srt/blob/eee6628078b2367a80f0019518858d51125b1bf7/srtcore/api.cpp#L84)
- [pthread_mutex_init](https://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_init.html "Initialize a mutex.") ⇒ [srt::sync::Mutex constructor](https://github.com/Haivision/srt/blob/a080a3f6393cfc9216f9514ba5b2d4db7aa000df/srtcore/sync.cpp#L320)

**Comment by ethouris** [comment]
Pending works added in #1379, but the exact fix for this is dependent and this should be split.
