### ISSUE TITLE
Remove an unnecessary null pointer check

### ISSUE THREAD

**Issue by elfring** [Haivision/srt#1105]
[An extra null pointer check is not needed](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") in [the destructor for the class “EventSlot”](https://github.com/Haivision/srt/blob/2689d9af143ca7a3cc4e2a8971f1f160c97db2ac/srtcore/common.h#L534 "Update candidate").

**Comment by maxsharabayko** [comment]
Hi @elfring 
Thanks for reporting. PR #1110 fixes this.

We also have some useful feedback from SonarCloud: [link](https://sonarcloud.io/dashboard?id=srt). It might be interesting to you.

Please also feel free to submit a PR with fixes, if you would like to. Your contribution is highly appreciated!

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/Haivision/srt/commit/55940c657acbb5573fdb927e953687ed852b542d "Removed an unnecessary null pointer check").

**Comment by maxsharabayko** [comment]
😊
