### ISSUE TITLE
User data per connection when using epoll

### ISSUE THREAD

**Issue by pbeyeler** [Haivision/srt#1126]
I followed the recvlive.cpp example to learn how libsrt can be used with epoll. But I'm struggling to understand how I can set user data per connection.

When using epoll system calls directly, it is possible to set a user data pointer in the epoll_event struct (see http://man7.org/linux/man-pages/man2/epoll_ctl.2.html) that gets returned by epoll_wait.

The SRT C API does not allow to set the epoll_event struct manually. How am I supposed to do this?

**Comment by ethouris** [comment]
The SRT epoll system is only loosely inspired by Linux epoll. Although there are many similarities, some of the features are not the same.

AFAIR the only reason for this `epoll_data_t` to exist is to map user data associated with particular `fd`. In SRT you only have a possibility to get information about which `fd` report readiness, so you have to associate it somehow with user data by yourself.

**Comment by pbeyeler** [comment]
Thanks for the speedy reply! I'll implement it by myself.
