### ISSUE TITLE
[BUG] stransmit on Windows uses too much CPU time

### ISSUE THREAD

**Issue by karlbrowns** [Haivision/srt#1142]
**Describe the bug**
I am running a single instance of stransmit receiving a SRT stream at around 6Mbps and retransmitting it locally as UDP.  This process seems to be using 60% CPU time and occasionally (if left running for >24 hours typically) will runaway and use 100% CPU time stopping the PC from performing.

**To Reproduce**
stransmit srt://a.b.c.d:e udp://127.0.0.1:9034

**Expected behavior**
I would expect it to take less than 10% CPU time.  For example, FFmpeg which is retransmitting the UDP stream as RTP is using <1% CPU time.

**Desktop (please provide the following information):**
Windows

**Comment by maxsharabayko** [comment]
@karlbrowns Please define SRT version.

**Comment by karlbrowns** [comment]
Can you please tell me how to find the SRT version?  It isn't shown when I run the command-line.

**Comment by manueldev** [comment]
srt-live-transmit -version

**Comment by maxsharabayko** [comment]
> Can you please tell me how to find the SRT version?  It isn't shown when I run the command-line.

Did you build it yourself or installed e.g. with `apt get`?

**Comment by karlbrowns** [comment]
I build it myself on Windows (so apt get isn't an option).  And srt-live-transmit -version gives this (I did try that!):
C:\Users\simon\Documents\Visual Studio 2013\Projects\srt-master\srt-master\build\Release>srt-live-transmit.exe -version
Usage: srt-live-transmit.exe [options] <input-uri> <output-uri>
        -t:<timeout=0> - exit timer in seconds
        -c:<chunk=1316> - max size of data read in one step
        -b:<bandwidth> - set SRT bandwidth
        -r:<report-frequency=0> - bandwidth report frequency
        -s:<stats-report-freq=0> - frequency of status report
        -pf:<format> - printformat (json or default)
        -f - full counters in stats-report (prints total statistics)
        -q - quiet mode (default no)
        -v - verbose mode (default no)
        -a - auto-reconnect mode, default yes, -a:no to disable

I've tried building the latest version but it's complaining about pthread not available.  I can't remember how I persuaded it last time.

**Comment by maxsharabayko** [comment]
Yes, `--version` is added only in PR 1024, which is not merged yet.
There should be `version.h` file in your source folder with SRT.
```
#define SRT_VERSION_MAJOR 1
#define SRT_VERSION_MINOR 4
#define SRT_VERSION_PATCH 0
```
`git log` could also tell the commit ID if you used git to clone the repo. Was it the latest master?

**Comment by karlbrowns** [comment]
No, I haven't managed to get latest master to build on Windows.  version.h shows 1.3.1

**Comment by maxsharabayko** [comment]
>  version.h shows 1.3.1

Should work in v1.4.1 then.
See #669, #893

**Comment by wakabayashik** [comment]
it seems that the v1.4.1 have not been applied the fix.
the bug can be reproduce quickly by adjusting the system clock on windows.

https://github.com/Haivision/srt/blob/v1.4.1/srtcore/common.cpp#L314
https://github.com/Haivision/srt/blob/v1.4.1/common/win_time.cpp#L30

could you release a fixed version or should I use the head of the master?

**Comment by maxsharabayko** [comment]
I see what you mean now. This is planned to be fixed by moving to C++11 timers.
Refer to #1103.

**Comment by wakabayashik** [comment]
i see the fix is planned for v1.5.0.
i'll try the v1.4.1 with @oviano's workaround until next release.

best regards,

**Comment by maxsharabayko** [comment]
oviano's workaround is in the latest master.

**Comment by wakabayashik** [comment]
but I prefer the official release (with minimal patches)
