### ISSUE TITLE
[FR] Ability to demultiplex and send only certain PIDs and service discovery

### ISSUE THREAD

**Issue by stoyanovgeorge** [Haivision/srt#1144]
**Is your feature request related to a problem? Please describe.**
Sometimes instead of `SPTS`, we have `MPTS` input multicast and in order to send only one channel out of the `MPTS`, we need first to demultiplex it and then to send the demultiplexed stream. 

**Describe the solution you'd like**
Ability to send only the selected service using the `Program ID`

**Describe alternatives you've considered**
I can demultiplex the stream with `ffmpeg` and then use the built-in support for SRT to send the demultiplexed stream, but usually `ffmpeg` is cutting all the stuffing bits which could potentially create a problem with the `PCR` and the audio/video synchronization. I believe `TSDuck` has also similar functionality, but this is all increasing the complexity and would be perfect if it is supported natively.

**Additional context**
Another interesting feature will be if you can send only selected streams. For example, if a channel has 3 audio PIDs and 2 subtitles PIDs to include only 1 audio and 1 subtitle PID to the receiving end. 
I think multicast discovery functionality will be also good to have, currently, I need to use `ffmpeg`/`ffprobe` to check the multicast streams or make a recording and analyze it with `mediainfo`. 

My request seems to be related to FR #830 but the status is still open, so if you want you can merge both `FR`

**Comment by ethouris** [comment]
SRT is only a transport library and it's content-agnostic. Interpretation of the incoming data and undertaking any actions basing on it is beyond the scope of this project.

The #830 PR is about extracting the parts of the current applications into a separate library so that applications creators may take some advantage of it.

**Comment by maxsharabayko** [comment]
Closing as "Won't Implement".
MPEG-TS Demux -> SRT Transport is the best approach for the desired functionality.
