### ISSUE TITLE
[BUG] Stutter when fed RTMP frames

### ISSUE THREAD

**Issue by Llorx** [Haivision/srt#1162]
**Describe the bug**
When I use a libsrt-enabled version of ffmpeg, if I get an RTMP stream and output it to SRT, it stutters. Is like the SRT stream is sending the frames at the same speed is receiving it, but we all know that RTMP is unstable, so surely is sending frames with no time-consistency.

**To Reproduce**
Just create a live stream with any software (vMix in my case) and use a srt-enabled ffmpeg binary with this command:
```
ffmpeg -i rtmp://localhost/live/test1 -c copy -f mpegts "srt://0.0.0.0:1231?latency=1000&mode=listener"
```

Example (Right is the RTMP output to `rtmp://localhost/live/test1`. Left is the SRT input where you can see the stutter): https://streamable.com/mbtdf

This is easily fixed with the `-re` flag, which forces ffmpeg to read/process frames at native fps. This demonstrates that when srt is fed with frames at a constant speed, they are sent at this consistent speed. This has a problem: `-re` is never meant to be used with live streams. As ffmpeg documentation states: 

> Should not be used with actual grab devices or live input streams (where it can cause packet loss)

I guess that you should process frames pts (if possible, and if this is the problem actually). Otherwise, I don't know how to make ffmpeg send frames steadily to srt without the `-re` flag.

**Desktop (please provide the following information):**
 - OS: Windows 10
 - SRT Version / commit ID: 1.4.1

**Comment by AlexandreLicinio** [comment]
do you notice same issue with an UDP output instead of SRT ?
what is the involved decoder, VLC ?

**Comment by maxsharabayko** [comment]
SRT tries to preserve the timing of the input (sender) on the receiving side. That is the design of SRT.

> Is like the SRT stream is sending the frames at the same speed is receiving it, but we all know that RTMP is unstable, so surely is sending frames with no time-consistency.

**Comment by Llorx** [comment]
The decoder is another vMix instance. Version 23 has SRT support with version 1.4.1 implemented.

With UDP is not happening (VLC wrapper). Here a side-to-side input SRT and UDP. You can see how SRT stutters: https://streamable.com/gdrif

**Comment by maxsharabayko** [comment]
Could you share the trace messages from VLC?
Menu Tools -> Messages with verbosity set to 2 (debug).

**Comment by Llorx** [comment]
Hm, is weird as I can play the video inside the VLC wrapper in vMix but cannot play it on my computer installation of VLC. By the way, here's the log: [log.log](https://github.com/Haivision/srt/files/4292870/log.log)

**Comment by Llorx** [comment]
Ok, just changed RTMP server to Wowza, still not able to receive UDP in my computer installation of VLC, so I tried again with vMix side-to-side inputs, and noticed that UDP is also stuttering, along with SRT. Yes, both stutter.

**Comment by Llorx** [comment]
Ok, I've noticed that adding "Decoder delay" it fixes the problem. I'm not sure what is happening actually.
![image](https://user-images.githubusercontent.com/702490/92012730-18a5b880-ed4d-11ea-9b60-f9975ad3616a.png)

**Comment by J-Rogmann** [comment]
Ahoi Llorx,
where in your chain you added the "Decoder delay"? On the SRT receiving end or on the RTMP input side?

**Comment by J-Rogmann** [comment]
Hi @Llorx 

Do you have any more info on the fixing the problem? Or shall we just close this ticket.

I'm still not sure, where you added the decoder delay... was this in vMix?

Best regards,
Justus

**Comment by Llorx** [comment]
Yes, vMix. Right now I'm not sure but seems a vMix fault actually, but
their support is a bit awful :-/

Close this and I'll open again if I find that is not a vMix problem.
