### ISSUE TITLE
ffmpeg build with --enable-libsrt, but still get the error 'srt://*** protocol not found'

### ISSUE THREAD

**Issue by chenjinli** [Haivision/srt#1176]
my configuration:
ffmpeg version 4.2.1 Copyright (c) 2000-2019 the FFmpeg developers
  built with Apple clang version 11.0.0 (clang-1100.0.33.17)
  configuration: --prefix=/usr/local/ffmpeg --enable-gpl --enable-nonfree --enable-libfdk-aac --enable-libx264 --enable-libx265 --enable-filter=delogo --enable-debug --disable-optimizations --enable-librtmp --enable-libspeex --enable-videotoolbox --enable-shared --enable-pthreads --enable-version3 --enable-hardcoded-tables --cc=clang --host-cflags= --host-ldflags= --disable-x86asm --enable-libsrt

Supported file protocols:
Input:
  async
  cache
  concat
  crypto
  data
  file
  ftp
  gopher
  hls
  http
  httpproxy
  https
  mmsh
  mmst
  pipe
  rtp
  srtp
  subfile
  tcp
  tls
  udp
  udplite
  unix
  rtmp
  rtmpe
  rtmps
  rtmpt
  rtmpte
Output:
  crypto
  file
  ftp
  gopher
  http
  httpproxy
  https
  icecast
  md5
  pipe
  prompeg
  rtp
  srtp
  tee
  tcp
  tls
  udp
  udplite
  unix
  rtmp
  rtmpe
  rtmps
  rtmpt
  rtmpte

**Comment by maxsharabayko** [comment]
Just a not regarding this useful guide: [link](https://srtlab.github.io/srt-cookbook/apps/ffmpeg/).
And I think "strp" is not SRT, but a different protocol ([FFmpeg guide](http://www.ffmpeg.org/ffmpeg-protocols.html#srtp)). So please check your build.

**Comment by chenjinli** [comment]
> Just a note regarding this useful guide: [link](https://srtlab.github.io/srt-cookbook/apps/ffmpeg/).
> And I think "strp" is not SRT, but a different protocol ([FFmpeg guide](http://www.ffmpeg.org/ffmpeg-protocols.html#srtp)). So please check your build.

thanks @maxsharabayko . i have found the reason. we can not build ffmpeg both with --enable-libsrt and --enable-shared. once i delete the --enable-shared option, it runs ok

**Comment by maxsharabayko** [comment]
Thanks @chenjinli. Made a note in the SRT cookbook.

**Comment by himslm01** [comment]
I'd just like to point out that although @chenjinli may not be able to build FFmpeg with libsrt as shared libraries, it is perfectly possible to do so.

I build FFmpeg as both shared and static every day. I would not like people to be put off from using SRT because an answer to an issue says it cannot be used in a shared library context.

**Comment by robynjayqueerie** [comment]
I just cannot get past this ffmpeg ./configure error
ERROR: srt >= 1.3.0 not found using pkg-config
even though pkg-config --modversion srt returns 1.4.2
Does anyone have an idea where to start? I have spent about a week on it so far, it should be simple I know

**Comment by maxsharabayko** [comment]
Hi @robynjayqueerie 
Your issue is probably related to your environment somehow.
Could you try to get help in the `#development` channel on [Slack](https://srtalliance.slack.com)?
[Join SRT Slack](https://slackin-srtalliance.azurewebsites.net/)
