### ISSUE TITLE
when release the bonding version ?

### ISSUE THREAD

**Issue by yyantony** [Haivision/srt#1180]
Hi
I saw there are a lot of commit about bonding ,but i make the version still 1.4.1,so when to release the version?

**Comment by maxsharabayko** [comment]
The current target is mid of April.
Check the roadmap here to track progress: #1120 .
You are also welcome to join "network-bonding" slack channel to keep track of updates: [link](https://slackin-srtalliance.azurewebsites.net/).

**Comment by awadh-bajpai** [comment]
Hi, 
Could you confirm when the connection bonding is expected to release ?.
And I assume srt-live-transmit app would support this at the same time ?.

**Comment by mbakholdina** [comment]
Hi @awadh-bajpai,

Connection Bonding feature is planned to be released in v1.5.0. We've just released [v1.4.2](https://github.com/Haivision/srt/releases/tag/v1.4.2) so I can't tell you any exact dates at this point. 

>> And I assume srt-live-transmit app would support this at the same time ?
This questions remains open for now.

**Comment by maxsharabayko** [comment]
The bonding API is no longer experimental in the upcoming v1.5.0, see #2316.
