### ISSUE TITLE
[BUG?]srt_epoll_uwait(), trigger same srt fd??

### ISSUE THREAD

**Issue by kyolong** [Haivision/srt#1189]
code
```c++
void Worker::event_loop()
{
    int       rc, i,
              srt_read_num, srt_write_num, 
              sys_read_num, sys_write_num;
    SRTSOCKET srt_read_sock[MAX_SOCKET_NUM], 
              srt_write_sock[MAX_SOCKET_NUM]; 
    SYSSOCKET sys_read_sock[MAX_SOCKET_NUM],
              sys_write_sock[MAX_SOCKET_NUM];    
    while(true) {
        srt_read_num = MAX_SOCKET_NUM;
        srt_write_num = MAX_SOCKET_NUM;
        sys_read_num = MAX_SOCKET_NUM;
        sys_write_num = MAX_SOCKET_NUM;
        rc = srt_epoll_wait(m_epoll_id, srt_read_sock, &srt_read_num,
                            srt_write_sock, &srt_write_num, BVC_POLLING_TIME,
                            sys_read_sock, &sys_read_num,
                            sys_write_sock, &sys_write_num);
        if (rc <= 0) {
            //TODO: add event
            continue;
        }
    // .........
}
```

gdb  info

`
#8  0x000000000044a8ce in Worker::event_loop (this=this@entry=0x377a9f0)
    at core/worker.cpp:229
229				ev->ReadHandler();
(gdb) info locals
it = <optimized out>
ev = <optimized out>
rc = <optimized out>
i = 0
srt_read_num = 1
srt_write_num = 0
sys_read_num = 2
sys_write_num = 0
srt_read_sock = {271057931, 271057931, 271057919, 271057925, 271057929, 271057931,
  271057933, 271057935, 271057953, 271057957, 271057971, 271065068, 271057927,
  271057929, 271057931, 271057933, 271057935, 271057941, 271057943, 271057953,
  271057957, 271057959, 271057971, 271057973, 271057977, 271057979, 271057983,
  271065068, 271057985, 271065068, 271074771, 271057969, 271057971, 271057981,
  271057985, 271057987, 271057989, 271074771, 271057973, 271057977, 271057979,
  271057981, 271057983, 271057985, 271057987, 271057989, 271065068, 271074771,
  271058507, 271065068, 271058419, 271058423, 271058429, 271058453, 271058469,
  271058483, 271058493, 271058507, 271058519, 271058529, 271065068, 271058419,
  271058453, 271058469, 271058483, 271058493, 271058507, 271058519, 271058529,
  271065068, 271058385, 271058389, 271058393, 271058395, 271058399, 271058405,
  271058409, 271058423, 271058529, 271058533, 271065068, 271058405, 271058407,
  271058409, 271058417, 271058419, 271058423, 271058425, 271058429, 271058433,
  271058469, 271058483, 271058493, 271058507, 271058515, 271058519, 271065068,
  271058361, 271058363, 271058365, 271058367, 271058371, 271058375, 271058379,
  271058385, 271058387, 271058389, 271058391, 271058393, 271058395, 271058405,
  271058407, 271058409, 271058417, 271058423, 271058425, 271058429, 271058433,
  271058453, 271058455, 271058469, 271058483, 271058493, 271058495, 271058507,
  271058515, 271058519, 271058529, 271058533, 271058537, 271058543, 271065068,
  271058507, 271058515, 271058519, 271058529, 271058533, 271058537, 271058543,
  271065068, 271058541, 271058543, 271058453, 271058455, 271058461, 271058467,
  271058469, 271058471, 271058477, 271058481, 271058483, 271058487, 271058493,
  271058495, 271058507, 271058515, 271058519, 271058521, 271058529, 271058533,
  271058537, 271058541, 271058543, 271058483, 271058487, 271058493, 271058495,
  271058507, 271058515, 271058519, 271058521, 271058529, 271058533, 271058537,
  271058541, 271058543, 271065068, 271058515, 271058519, 271058521, 271058529,
  271058533, 271058537, 271058541, 271058543, 271065068, 271058423, 271058425,
  271058429, 271058431, 271058433, 271058435, 271058437, 271058445, 271058449,
  271058453, 271058455, 271058461, 271058467, 271058469...}
srt_write_sock = {271057965, 271058139, 271058379, 271059069, 271059117, 271060403,
---Type <return> to continue, or q <return> to quit---q
`

271065068  duplication 13 times???

**Comment by maxsharabayko** [comment]
The behaviour of [srt_epoll_uwait(..)](https://github.com/Haivision/srt/blob/master/docs/API-functions.md#srt_epoll_uwait) depends on the mode it is used in: level- or edge triggered.There is not hint on this in your sample code.
Please refer to the following docs section: [srt_epoll_add_usock](https://github.com/Haivision/srt/blob/master/docs/API-functions.md#srt_epoll_add_usock-srt_epoll_add_ssock-srt_epoll_update_usock-srt_epoll_update_ssock)

**Comment by kyolong** [comment]
sorry my mistake`  I did not see  srt_read_num is just 1.

But, srt_epoll_wait(..)  trigger my  srt_read even. bug my srt_recv()  is block?
`
#2  0x00000000007a8494 in CUDT::receiveMessage (this=0x7f9230ce5d70,
    data=0x7f91f0522990 "", len=1456, r_mctrl=...)
    at /data/app/bvc-srt-server/bvc_network_srt/srtcore/core.cpp:6154
6154	                if (CTimer::condTimedWaitUS(&m_RecvDataCond, &m_RecvLock, recvtmo * 1000) == ETIMEDOUT)
(gdb) info locals
mctrl = @0x7f9691cf8710: {flags = 0, msgttl = -1, inorder = 0, boundary = 0,
  srctime = 0, pktseq = 0, msgno = 0}
recvguard = {m_Mutex = @0x7f9230ceaca0, m_iLocked = 0}
__FUNCTION__ = "receiveMessage"
res = 0
timeout = false
recvtmo = 1000
(gdb) p this.m_bClosing
$7 = false
(gdb) p this.m_bBroken
$8 = false
(gdb) p this.m_bConnected
$9 = true
(gdb) p timeout
$10 = false
(gdb) call m_pRcvBuffer->isRcvDataReady()
$11 = false
(gdb)
`
epoll trigger  read even,why  ,isRcvDataReady() is not ready?

**Comment by ethouris** [comment]
Thinks can quickly change when you debug with gdb, be sure that you have set `SRTO_CONNTIMEO` option to a really high value so that the connection isn't broken as you type commands in the debugger.

Note also the case of `SRT_EPOLL_ET` flag. Normally you should get exit from the waiting function when at least subscribed socket is currently ready. The `SRT_EPOLL_ET` flag clears readiness on a socket that was subscribed this way upon exit from the waiting function. Please also note that `srt_epoll_wait` reports the ERR state by adding the socket as ready to both IN and OUT arrays simultaneously.

**Comment by kyolong** [comment]
Hi, i did not set SRT_EPOLL_ET (by default).
after srt_connect()  ,I add the srt fd to srt_epoll .
after srt_epoll_wait(),  I get a read even at fd(271065068),  then  I call srt_recv() with this fd.
then srt_recv() is block ,i can't get any data.    So  no data why trigger srt read even ?

**Comment by ethouris** [comment]
Wait. How do you subscribe sockets to epoll?

And note that for a case of proper fallback in case of error, you should turn of blocking mode in particular direction (`SRTO_SNDSYN` and `SRTO_RCVSYN`) - this way the receiving function will return `SRT_EASYNC*` (*SND or *RCV) instead od blocking.
