### ISSUE TITLE
Check the value of pw_addrlen in CUDTUnited::accept(..)

### ISSUE THREAD

**Issue by Avetri** [Haivision/srt#1191]
https://github.com/Haivision/srt/blob/6598a135fba8bc2967e0dd8ae398a66bf763d7cb/srtcore/api.cpp#L999

Hi!

'if (pw_addr && !pw_addrlen)' statement may return a wrong result. 'if (addr != NULL && addrlen == NULL)' will work in a bit more strict way (I suppose).

**Comment by maxsharabayko** [comment]
Hi @Avetri 
Both `pw_addr` and `pw_addrlen` are pointers, so `if (pw_addr && !pw_addrlen)` looks good.

However, I have noticed the value of `pw_addrlen` is not checked, which should be fixed. 

- [ ] Check the value of `pw_addrlen` in `CUDTUnited::accept(..)`

**Comment by maxsharabayko** [comment]
Closing this issue.
The value of pw_addrlen is checked (see above), so my comment was also wrong.
