### ISSUE TITLE
[BUG] URI Parser issues with rendezvous mode

### ISSUE THREAD

**Issue by maxsharabayko** [Haivision/srt#1195]
The following URI request fails to set the correct connection mode:
```
"srt://192.168.1.91:4200?adapter=192.168.1.237&port=4200&mode=rendezvous"
```
Does not work with the latest master 7fda3652919da9ba8ff64b9f8d8cebe74ed7c0f1
Works with SRT v1.4.1.

**srt-test-live logs**
```
./srt-test-live "srt://192.168.1.91:4200?adapter=192.168.1.237&port=4200&mode=rendezvous" udp://192.168.1.237:5200 -v
SRT parameters specified:
	adapter = '192.168.1.237'
	mode = 'rendezvous'
	port = '4200'
Opening SRT source rendezvous(blocking, backlog=1) on 192.168.1.91:4200
WARNING: failed to set options: 
mode, 

ERROR (app): ConfigurePre
Open FAILED - closing SRT sockets
MEDIA CREATION FAILED: ConfigurePre - exitting.
```

**Comment by ethouris** [comment]
Why do you use `port` parameter? It's intended for the use exclusively with caller mode. In rendezvous the same port is used on both sides.

**Comment by maxsharabayko** [comment]
> Why do you use `port` parameter? It's intended for the use exclusively with caller mode. In rendezvous the same port is used on both sides.

Because I wanted to have a different port to bind a socket to.
