### ISSUE TITLE
[srt-live-transmit] Add absolute timestamp when collecting SRT statistics

### ISSUE THREAD

**Issue by mbakholdina** [Haivision/srt#1218]
Add absolute timestamp when collecting SRT statistics in `srt-live-transmit` application. Timestamp type: ISO 8601, yyyy-mm-dd hh:mm:ss.

An example of `.csv` statistics generated by `srt-xtransmit`:

```
Timepoint,Time,SocketID,pktFlowWindow,pktCongestionWindow,pktFlightSize,msRTT,mbpsBandwidth,mbpsMaxBW,pktSent,pktSndLoss,pktSndDrop,pktRetrans,byteSent,byteAvailSndBuf,byteSndDrop,mbpsSendRate,usPktSndPeriod,pktRecv,pktRcvLoss,pktRcvDrop,pktRcvRetrans,pktRcvBelated,byteRecv,byteAvailRcvBuf,byteRcvLoss,byteRcvDrop,mbpsRecvRate,msRcvTsbPdDelay,msRcvTsbPdDelay
10.02.2020 17:34:29.952211 +0000,1,855406566,25600,25600,0,100,12,1000,0,0,0,0,0,1019020500,0,0,10,0,0,0,0,0,0,38398500,0,0,0,120,0
10.02.2020 17:34:29.962457 +0000,12,855406566,25600,25600,0,100,12,1000,0,0,0,0,0,1019020500,0,0,10,0,0,0,0,0,0,38398500,0,0,0,120,0
10.02.2020 17:34:29.972632 +0000,22,855406566,25600,25600,0,100,12,1000,0,0,0,0,0,1019020500,0,0,10,0,0,0,0,0,0,38398500,0,0,0,120,0
10.02.2020 17:34:29.982806 +0000,32,855406566,25600,25600,0,100,12,1000,0,0,0,0,0,1019020500,0,0,10,0,0,0,0,0,0,38398500,0,0,0,120,0
10.02.2020 17:34:29.992977 +0000,42,855406566,25600,25600,0,100,12,1000,0,0,0,0,0,1019020500,0,0,10,0,0,0,0,0,0,38398500,0,0,0,120,0
10.02.2020 17:34:30.003159 +0000,52,855406566,25600,25600,0,100,12,1000,0,0,0,0,0,1019020500,0,0,10,0,0,0,0,0,0,38398500,0,0,0,120,0
10.02.2020 17:34:30.013346 +0000,62,855406566,25600,25600,0,100,12,1000,0,0,0,0,0,1019020500,0,0,10,0,0,0,0,0,0,38398500,0,0,0,120,0
10.02.2020 17:34:30.023655 +0000,73,855406566,25600,25600,0,100,12,1000,0,0,0,0,0,1019020500,0,0,10,0,0,0,0,0,0,38398500,0,0,0,120,0
```

I would also think about proper and the same naming for both test applications:
- Timepoint -> timestamp
- Time -> time

**Comment by alatteri** [comment]
I add my voice to this.  Quite necessary for proper logging into a Time Series Database like Influx and visualizations with Grafana.

**Comment by chenzhigang-cn** [comment]
Add absolute timestamp when  srt-live-transmit  -pf json log
{
    "sid":5743516,
    "starttime":2264,
     "timestamp":1611746322000,
    "window":{
        "flow":8132,
        "congestion":8192,
        "flight":3
    },
    "link":{
        "rtt":0.392,
        "bandwidth":77.856,
        "maxBandwidth":1000
    },
    "send":{
        "packets":996,
        "packetsUnique":994,
        "packetsLost":2,
        "packetsDropped":0,
        "packetsRetransmitted":2,
        "packetsFilterExtra":0,
        "bytes":1354560,
        "bytesUnique":1351840,
        "bytesDropped":0,
        "mbitRate":4.78471
    },
    "recv":{
        "packets":0,
        "packetsUnique":0,
        "packetsLost":0,
        "packetsDropped":0,
        "packetsRetransmitted":0,
        "packetsBelated":0,
        "packetsFilterExtra":0,
        "packetsFilterSupply":0,
        "packetsFilterLoss":0,
        "bytes":0,
        "bytesUnique":0,
        "bytesLost":0,
        "bytesDropped":0,
        "mbitRate":0
    }
}

**Comment by mbakholdina** [comment]
@ethouris Could you please add an absolute timestamp to the `json` `srt-live-transmit` log in the same way it has been implemented by @maxsharabayko for `csv` log?

**Comment by mbakholdina** [comment]
Hi @chenzhigang-cn, PR #1780 is in progress.
