### ISSUE TITLE
should I set SRTO_PACKETFILTER for sender, receiver or both ?

### ISSUE THREAD

**Issue by alexpokotilo** [Haivision/srt#1229]
Hi,
if I want to use "embedded" FEC filter should I set SRTO_PACKETFILTER only for sender or for receiver too?
I've checked API-functions.md, packet-filtering-and-fec.md, srt.h and was not able to get it.

**Comment by alexpokotilo** [comment]
according to this comment https://github.com/Haivision/srt/issues/894#issuecomment-555428369 we should set fec with params on sender and set fec without params on receiver.
This is all I was able to find so far

**Comment by ethouris** [comment]
`packetfilter=fec` must be set on both sides and at least one side should define a configuration for it.

**Comment by alexpokotilo** [comment]
@mbakholdina, don't you think we need to have comment from @ethouris added to docs about 
SRTO_PACKETFILTER ? I can submit necessary changes if you don't mind
