### ISSUE TITLE
Haivision Play Pro does not support the streamid parameter.

### ISSUE THREAD

**Issue by Edward-Wu** [Haivision/srt#1233]
hi, 
The Haivision Play Pro is good tool for playing the srt url.
There is a little bug. I input the streamid to the url input box, when the  cursor left the input box, the streamid disappear.
So if using the streamid to distinguish streams  Play Pro will not work normally.

**Comment by fallenhaivision** [comment]
Hi Edward,
I will create a ticket for Play Pro to look into this issue.

**Comment by maxsharabayko** [comment]
Hi @Edward-Wu 
Please check the latest release v.3.0.6 of Haivision Play Pro for iOS. It adds StreamID text field for SRT streams when Caller is selected.
