### ISSUE TITLE
How to keep the statsout log only the last one

### ISSUE THREAD

**Issue by macsun1990** [Haivision/srt#1235]
Hi,
   I'm try to make the statsout log only last one line,but it did not succeed. I want know how to do it.

**Comment by ethouris** [comment]
The CSV format can be close to what you need, although it prints first the headers, then the probe data in one line, separated by comma, once per probe time.

**Comment by macsun1990** [comment]
Sorry, I may not describe clearly,I want to keep only the last data in the log file.Because the log file will grow larger and larger, I want it to keep only the last one, I can save it to the database, and then call it through grafana.

**Comment by ethouris** [comment]
That's beyond the scope of the SRT project. There are lots of tools available in the free software world that can do it for you.

**Comment by maxsharabayko** [comment]
@macsun1990 
Sorry, still not clear which logs do you need. srt-live-transmit currently provides CSV, JSON and default statistics output.
You can make the required modifications yourself. Like @ethouris noted, adding the requested functionality to our codebase is unlikely, although possible if you could come up with a convenient way of handling both cases. 

Take a look at the `SrtSource::Read(..)` function: [code](https://github.com/Haivision/srt/blob/master/apps/transmitmedia.cpp#L534). Replacing the first stats line from
```c++
out_stats << transmit_stats_writer->WriteStats(m_sock, perf) << std::flush;
```
to
```c++
out_stats < transmit_stats_writer->WriteStats(m_sock, perf) << std::flush;
```
should do the trick.
The same should be done for `SrtTarget::Write(..)`.

**Comment by macsun1990** [comment]
@maxsharabayko 
Hi, my friend, I tried to modify that part of the code, but it was unsuccessful, so I deleted that part of the code, 

`out_stats << transmit_stats_writer->WriteStats(m_sock, perf) << std::flush;`

but there are still log writes, so it may not be the writes affected by that part of the code.

**Comment by ethouris** [comment]
Example:
```
#!/bin/bash
rm -f stats.fifo
mkfifo stats.fifo
while read <stats.fifo; do
    echo $REPLY >stats.out
done
```

Start this script, and then run the command with using redirection `>> stats.fifo` while allowing the stats to be written to stdout.

**Comment by macsun1990** [comment]
@ethouris 
That's good idea and easly. Thank you.
