### ISSUE TITLE
[FR]do we have a plan to add the output traffic shaping feature?

### ISSUE THREAD

**Issue by yyantony** [Haivision/srt#1237]
the output stream have a  large bitrate jitter when receiving in a big packet loss network,is not smooth to the decoder.

**Comment by mbakholdina** [comment]
Hi @yyantony ! 
Could you please provide more details regarding your test setup? 
What application do you use for SRT streaming?
How big is the level of packet loss?

**Comment by yyantony** [comment]
command:
./srt-live-transmit udp://0.0.0.0:6000 srt://192.168.0.181:8888
./srt-live-transmit srt://@:8888?latency=1000ms udp://192.168.0.148:7000
on 100ms RTT 20% loss network, the UDP output stream bitrate 
![100ms 20%](https://user-images.githubusercontent.com/59468869/79339750-e4775a00-7f5b-11ea-8c2d-a3a6bd277256.png)

on 100ms RTT 30% loss network

![100ms 30%](https://user-images.githubusercontent.com/59468869/79339759-e80ae100-7f5b-11ea-954c-5812b442cd0c.png)

and when add udp rcvbuff 
command:
./srt-live-transmit udp://0.0.0.0:?rcvbuf=67108864 srt://192.168.0.181:8888
./srt-live-transmit srt://@:8888?latency=1000ms udp://192.168.0.148:7000?rcvbuf=67108864

on 100ms RTT 20% loss network,
![100ms 20% rcvbuf](https://user-images.githubusercontent.com/59468869/79339558-a5e19f80-7f5b-11ea-9f7f-8285698ebf52.png)

on 100ms RTT 30% loss network
![100ms 30% rcvbuf](https://user-images.githubusercontent.com/59468869/79339593-b1cd6180-7f5b-11ea-865f-a07b8ae9c134.png)

my sender side and receiver side both increase system maximum buffer size as below
net.core.rmem_default = 4048576
net.core.rmem_max = 4048576
net.core.wmem_max = 4048576
net.core.wmem_default = 4048576

**Comment by ethouris** [comment]
What's the `@` sign in the SRT URI?

**Comment by ethouris** [comment]
BTW. How many packet drops do you have in the stats? Because the only way of having different times at the reception side is the following:
* the application performance at the receiver side is poor and it reads packets with a delay
* dropped packets are simply not delivered
* a largely changing RTT, which fools the drift tracer (a rare case, theoretically possible, but unlikely in the real-world stable network)

Please mind also that with 30% packet loss you'll get an overhead of 30% plus the exponental value of repeated retransmission, which can cause pushback on the actual network bandwidth limit and cause more packet losses if the overhead exceeds it. The size of retransmission statistics grabbed at the sender side compared with the transfer size and retransmission stats at the receiver side can give some insight into it.

**Comment by yyantony** [comment]
sorry,it usually use in VLC.
I repeat the test with new  command:
./srt-live-transmit udp://0.0.0.0:6000?rcvbuf=67108864 srt://192.168.0.181:8888
./srt-live-transmit srt://:8888?latency=1000ms udp://192.168.0.148:7000?rcvbuf=67108864

![30% new rcvbuf](https://user-images.githubusercontent.com/59468869/79341837-f8708b00-7f5e-11ea-8831-317845155e71.png)

 and there is no packet loss  when i analysis the UDP outstream.
I mean we use the  rec buff to do traffic sharping,

**Comment by ethouris** [comment]
Yeah, but I meant grabbing statistics from SRT. There are options for this for `srt-live-transmit` command:

```
        -s, -stats, -stats-report-frequency:<every_n_packets=0> - frequency of status report
        -statsout:<filename>    - output stats to file
        -pf, -statspf:<format=default>  - stats printing format [json|csv|default]
        -f, -fullstats  - full counters in stats-report (prints total statistics)
```

Note that stats interval is in "number of packets" unit, so with high bitrate the interval (`-s`) value should be quite large.

**Comment by yyantony** [comment]
this is the output with other protocol in the same network and the same stream.
![other](https://user-images.githubusercontent.com/59468869/79342706-0b378f80-7f60-11ea-86fe-eec66e5e9e3c.png)

**Comment by yyantony** [comment]
I use -s 2000 and run the test 5 min ,the packet lose on both side  still looks stable。

sender side:
======= SRT STATS: sid=527076856
PACKETS     SENT:        3794  RECEIVED:             0
LOST PKT    SENT:        1785  RECEIVED:             0
REXMIT      SENT:        1785  RECEIVED:             0
DROP PKT    SENT:           0  RECEIVED:             0
FILTER EXTRA  TX:           0        RX:             0
FILTER RX  SUPPL:           0  RX  LOSS:             0
RATE     SENDING:     20.0595  RECEIVING:            0
BELATED RECEIVED:           0  AVG TIME:             0
REORDER DISTANCE:           0
WINDOW      FLOW:        7308  CONGESTION:        8192  FLIGHT:         319
LINK         RTT:   100.864ms  BANDWIDTH:  3376.82Mb/s 
BUFFERLEFT:  SND:    11808000  RCV:           12286500
======= SRT STATS: sid=527076856
PACKETS     SENT:        3685  RECEIVED:             0
LOST PKT    SENT:        1717  RECEIVED:             0
REXMIT      SENT:        1717  RECEIVED:             0
DROP PKT    SENT:           0  RECEIVED:             0
FILTER EXTRA  TX:           0        RX:             0
FILTER RX  SUPPL:           0  RX  LOSS:             0
RATE     SENDING:     19.8181  RECEIVING:            0
BELATED RECEIVED:           0  AVG TIME:             0
REORDER DISTANCE:           0
WINDOW      FLOW:        7351  CONGESTION:        8192  FLIGHT:         388
LINK         RTT:   100.893ms  BANDWIDTH:  3648.24Mb/s 
BUFFERLEFT:  SND:    11704500  RCV:           12286500
======= SRT STATS: sid=527076856
PACKETS     SENT:        3672  RECEIVED:             0
LOST PKT    SENT:        1663  RECEIVED:             0
REXMIT      SENT:        1663  RECEIVED:             0
DROP PKT    SENT:           0  RECEIVED:             0
FILTER EXTRA  TX:           0        RX:             0
FILTER RX  SUPPL:           0  RX  LOSS:             0
RATE     SENDING:     19.3785  RECEIVING:            0
BELATED RECEIVED:           0  AVG TIME:             0
REORDER DISTANCE:           0
WINDOW      FLOW:        7416  CONGESTION:        8192  FLIGHT:         373
LINK         RTT:   100.827ms  BANDWIDTH:  3518.62Mb/s 
BUFFERLEFT:  SND:    11727000  RCV:           12286500
======= SRT STATS: sid=527076856
PACKETS     SENT:        3723  RECEIVED:             0
LOST PKT    SENT:        1714  RECEIVED:             0
REXMIT      SENT:        1714  RECEIVED:             0
DROP PKT    SENT:           0  RECEIVED:             0
FILTER EXTRA  TX:           0        RX:             0
FILTER RX  SUPPL:           0  RX  LOSS:             0
RATE     SENDING:      19.641  RECEIVING:            0
BELATED RECEIVED:           0  AVG TIME:             0
REORDER DISTANCE:           0
WINDOW      FLOW:        7352  CONGESTION:        8192  FLIGHT:         267
LINK         RTT:    100.87ms  BANDWIDTH:  4042.67Mb/s 
BUFFERLEFT:  SND:    11886000  RCV:           12286500
======= SRT STATS: sid=527076856
PACKETS     SENT:        3600  RECEIVED:             0
LOST PKT    SENT:        1591  RECEIVED:             0
REXMIT      SENT:        1591  RECEIVED:             0
DROP PKT    SENT:           0  RECEIVED:             0
FILTER EXTRA  TX:           0        RX:             0
FILTER RX  SUPPL:           0  RX  LOSS:             0
RATE     SENDING:     19.0254  RECEIVING:            0
BELATED RECEIVED:           0  AVG TIME:             0
REORDER DISTANCE:           0
WINDOW      FLOW:        7248  CONGESTION:        8192  FLIGHT:         273
LINK         RTT:   100.846ms  BANDWIDTH:  4469.06Mb/s 
BUFFERLEFT:  SND:    11878500  RCV:           12286500


Rec side:
======= SRT STATS: sid=46518514
PACKETS     SENT:           0  RECEIVED:          2650
LOST PKT    SENT:           0  RECEIVED:           615
REXMIT      SENT:           0  RECEIVED:          1255
DROP PKT    SENT:           0  RECEIVED:             0
FILTER EXTRA  TX:           0        RX:             0
FILTER RX  SUPPL:           0  RX  LOSS:             0
RATE     SENDING:           0  RECEIVING:      13.9945
BELATED RECEIVED:          89  AVG TIME:   -4.69734e+06
REORDER DISTANCE:           0
WINDOW      FLOW:        8192  CONGESTION:        8192  FLIGHT:           0
LINK         RTT:   100.831ms  BANDWIDTH:  3641.39Mb/s 
BUFFERLEFT:  SND:    12288000  RCV:           11130000
======= SRT STATS: sid=46518514
PACKETS     SENT:           0  RECEIVED:          2554
LOST PKT    SENT:           0  RECEIVED:           597
REXMIT      SENT:           0  RECEIVED:          1142
DROP PKT    SENT:           0  RECEIVED:             0
FILTER EXTRA  TX:           0        RX:             0
FILTER RX  SUPPL:           0  RX  LOSS:             0
RATE     SENDING:           0  RECEIVING:      13.7416
BELATED RECEIVED:         113  AVG TIME:    -1.685e+11
REORDER DISTANCE:           0
WINDOW      FLOW:        8192  CONGESTION:        8192  FLIGHT:           0
LINK         RTT:   100.839ms  BANDWIDTH:  3493.68Mb/s 
BUFFERLEFT:  SND:    12288000  RCV:           11265000
======= SRT STATS: sid=46518514
PACKETS     SENT:           0  RECEIVED:          2724
LOST PKT    SENT:           0  RECEIVED:           608
REXMIT      SENT:           0  RECEIVED:          1266
DROP PKT    SENT:           0  RECEIVED:             0
FILTER EXTRA  TX:           0        RX:             0
FILTER RX  SUPPL:           0  RX  LOSS:             0
RATE     SENDING:           0  RECEIVING:      13.8398
BELATED RECEIVED:          88  AVG TIME:      -761.053
REORDER DISTANCE:           0
WINDOW      FLOW:        8192  CONGESTION:        8192  FLIGHT:           0
LINK         RTT:   100.823ms  BANDWIDTH:  3836.08Mb/s 
BUFFERLEFT:  SND:    12288000  RCV:           10990500
======= SRT STATS: sid=46518514
PACKETS     SENT:           0  RECEIVED:          2502
LOST PKT    SENT:           0  RECEIVED:           570
REXMIT      SENT:           0  RECEIVED:          1120
DROP PKT    SENT:           0  RECEIVED:             0
FILTER EXTRA  TX:           0        RX:             0
FILTER RX  SUPPL:           0  RX  LOSS:             0
RATE     SENDING:           0  RECEIVING:      13.7232
BELATED RECEIVED:         100  AVG TIME:   -1.66875e+08
REORDER DISTANCE:           0
WINDOW      FLOW:        8192  CONGESTION:        8192  FLIGHT:           0
LINK         RTT:   100.911ms  BANDWIDTH:  4474.58Mb/s 
BUFFERLEFT:  SND:    12288000  RCV:           11146500
======= SRT STATS: sid=46518514
PACKETS     SENT:           0  RECEIVED:          2556
LOST PKT    SENT:           0  RECEIVED:           566
REXMIT      SENT:           0  RECEIVED:          1113
DROP PKT    SENT:           0  RECEIVED:             0
FILTER EXTRA  TX:           0        RX:             0
FILTER RX  SUPPL:           0  RX  LOSS:             0
RATE     SENDING:           0  RECEIVING:      13.5191
BELATED RECEIVED:          85  AVG TIME:   -3.86856e+15
REORDER DISTANCE:           0
WINDOW      FLOW:        8192  CONGESTION:        8192  FLIGHT:           0
LINK         RTT:   100.951ms  BANDWIDTH:   4141.6Mb/s 
BUFFERLEFT:  SND:    12288000  RCV:           11107500

**Comment by ethouris** [comment]
The stats show the loss rate in this session around 45%, which seems to be higher than your declared 30%.

> 1785*100.0/3794
47.047970479704794
> 1717*100.0/3685
46.594301221166894
> 1591*100.0/3600
44.19444444444444

Might be that some losses are caused by the real network conditions (retransmission overhead exceeds the available bandwidth). There could be also double losses because the number of losses at the sender (represented by the number of losses reported by the receiver) is 2-3x higher than the losses reported by the receiver (which reports every missing packet only once).

There are however 0 dropped packets on either side. This means that your stream at the output exactly is the stream that you send in the beginning. The stream itself then isn't damaged.

The TSBPD mechanism should also replay the original times at the receiver, that is, time distance between two consecutive packets when receiving should represent the time distance between two the same packets at the source side. If you are observing a jitter at the receiver, it may come from two sources:

* an extra delay on a single packet is introduced when reading - the packet isn't reported to the application (and therefore passed to UDP link) exactly at the moment when it is declared ready to play. This might result from the possible performance or thread scheduling, as well as non-blocking mode that this application is using
* an extra delay on UDP packet when reading (a delay in readiness report), which leads to the unexpectedly belated times assigned to particular packet at the sender side and so replayed at the receiver side

You can try to repeat the test using `srt-test-live` application instead. It's a developer-only application and requires to `--enable-testing` to compile. It is however simpler in architecture and works in blocking mode, so any delay in reading from UDP or from SRT can only be caused by the thread scheduling (unlikely by blocked sending to the output medium).

Another - at least theoretical - reason of the unstable delays introduced at the packets could be at the UDP medium. You might try to introduce some interceptor that will be receiving UDP packets directly and then pass them through the pipe to the SRT transmitting application. Similarly on the output. To use the pipe to the program (stdin/stdout), use `file://con` as the medium URI.

**Comment by mbakholdina** [comment]
@yyantony When doing the additional checks @ethouris has suggested, please collect the statistics in `.csv` format from both sender and receiver so that it's easier to analyze.

Please also feel free to use the script [srt-stats-plotting](https://github.com/mbakholdina/srt-stats-plotting) for the statistics visualization and analysis.

**Comment by yyantony** [comment]
Source：
10Mbps ts file
ffmpeg command: 
ffmpeg.exe -re -i D:\Desktop\10Mbps.ts -vcodec copy  -an -f mpegts udp://192.168.1.50:6000?pkt_size=1316

Emulator:
tc qdisc add dev eth0 root handle 1:0 prio bands 3
tc qdisc add dev eth0  parent 1:3 handle 30: netem delay 100ms loss 30% limit 1000
tc filter add dev eth0 protocol ip parent 1:0 prio 3 u32 match ip dst 192.168.0.60 flowid 1:3

use srt-test-live ,the output issue same as srt-live-transmit
here is the log.
[stats-csv.zip](https://github.com/Haivision/srt/files/4523595/stats-csv.zip)


i think it same as the issue #735 
i also made a video for this.
https://youtu.be/dqIl3t6LVzg

**Comment by ethouris** [comment]
I've taken a look at both things. For me there are two things important:

1. You don't observe any packet drops - all packets as received by the SRT transmitting application have been delivered to the output.

2. The default settings with TSBPDMODE=on and TLPKTDROP=on ensure that the time of packet delivery relatively to the previous packet should be preserved as the same that has been recorded at the sending time. The only skew you might have by this process - of which we know so far - can only result from the performance or thread layout on the receiver machine.

Please describe in details your configuration, machines involved, their OS, IP address you used for each of them. We'll try to repro this in our lab.

It would be also nice if you can collect the pcap record from both sides - sending and receiving, and as you have the receiving side retransmitting the packets over UDP, that UDP output, too, just separately. This should at least allow us to match UDP payloads with SRT payloads and their sending time.

Please also note that if you are trying to research what happens inside SRT, then SRT connection should be the only case of involving network.

**Comment by mbakholdina** [comment]
Hi @yyantony, do you have any updates on your side?

Here is the useful article [Using TShark & Wireshark to analyse SRT traffic](https://srtlab.github.io/srt-cookbook/how-to-articles/how-to-setup-wireshark-for-srt-traffic-analysis/) which will give you some tips on collecting Wireshark dump.

**Comment by yyantony** [comment]
Busy with other projects recently.sorry for late.
Here is the pcap. 
https://drive.google.com/file/d/15YCv5ETTSlig8BUdtQ2DSy927Us0dvr7/view?usp=sharing

and the OS and network as below:
1. UDP sender and UDP recevier
    win7 Ultimate 64bit sp1 
    ip1: 192.168.0.148
    ip2:192.168.1.148
2. UDP receiver and SRT transmit
    5.5.7-100.fc30.x86_64  
    ip:192.168.1.163 
    gw:192.168.1.200
3.Network emulator
    ip1:192.168.0.80
    ip2:192.168.1.200
    iptabless- t nat -A POSTROUTING -s 192.168.1.0/24 -j SNAT --to 192.168.0.80
4. SRT recevier and UDP output
    5.5.7-100.fc30.x86_64  
    ip:192.168.0.181

1 is my PC,and 2,3,4 is virtualbox on the PC,and share a wireless card for network.bridge the same card for 3.
TC command & SRT had post before. anything else can i do ?

**Comment by mbakholdina** [comment]
Hi @yyantony, thank you for sharing the dumps and additional information with us! I'll take some time to reproduce the test case and see whether the problem appears on my side. Currently busy with the other tasks as well, will ping you in case any additional help is required.

**Comment by mbakholdina** [comment]
Hi @yyantony, I've spent some time to reproduce the problem you have and unfortunately were not able to do so. I run my tests on two CentOS 7 test machines generating UDP source streaming with the help of a special application on local host.

I used the same parameters and network settings as you did: RTT=100ms, packet loss 30% (generated on a sender side), sending rate 10Mbps, latency=400ms (not 1000ms, but 4*RTT latency is enough).

The results are the following:

1. RTT=100ms, packet loss 30% (sender side), sending rate 10Mbps, latency=400ms, srt-live-transmit buffering=10 (by default)
```
_build/srt-live-transmit "udp://:4200?adapter=127.0.0.1&port=4200" srt://192.168.3.2:4200 -v 
_build/srt-live-transmit "srt://:4200?adapter=192.168.3.2&port=4200&latency=400" udp://127.0.0.1:4200 -v
```
<img width="957" alt="rcv_rtt100ms_loss30A_sendrate10Mbps_latency400ms_buf10" src="https://user-images.githubusercontent.com/41019697/89298930-46bcad80-d666-11ea-8286-7c1f5757cb37.png">

The legend is the following
<img width="1086" alt="legend" src="https://user-images.githubusercontent.com/41019697/89299150-900cfd00-d666-11ea-9fd5-f2b681a63a38.png">

2. RTT=100ms, packet loss 30% (sender side), sending rate 10Mbps, latency=400ms, srt-live-transmit buffering=10 (by default), rcvbuf=26214400
```
_build/srt-live-transmit "udp://:4200?adapter=127.0.0.1&port=4200&rcvbuf=26214400" srt://192.168.3.2:4200 -v
_build/srt-live-transmit "srt://:4200?adapter=192.168.3.2&port=4200&latency=400" udp://127.0.0.1:4200 -v
```
<img width="956" alt="rcv_rtt100ms_loss30A_sendrate10Mbps_latency400ms_buf10_rcvbuf" src="https://user-images.githubusercontent.com/41019697/89299532-132e5300-d667-11ea-9d48-eca98efc6485.png">

In both cases, the UDP trajectory (the blue one) at the receiver side looks pretty smooth and the number of missing (dropped by SRT) packets is very low (~0.06%).

Recommendations:
- `rcvbuf` URI option is meant to help with higher bitrates and may lead additional unnecessary buffering. For 10Mbps, you do not need it. In case you continue using it or for any other use cases, please make sure you change the default system rcv buffer size first as described [here](https://github.com/Haivision/srt/blob/master/docs/srt-live-transmit.md#udp-performance) and apply it only at a sender side while receiving UDP (see the commands I've listed above, test case 2).
- The latest `srt-live-transmit` from master has `-srctime:true` command-line option to reduce jitter in SRT output with SRT/UDP/STDIN input. See this [doc](https://github.com/Haivision/srt/blob/master/docs/srt-live-transmit.md#command-line-options).
- There is one more option `-buffering:1` which can be used to reduce the buffering in `srt-live-transmit` application and as a result the jitter. The default value is 10 packets.

Please apply these recommendations and let me know the result. Other than that, it could be related to the OS or VMs specifics.

**Comment by mbakholdina** [comment]
Hi @yyantony,
Do you have any updates on the ticket?

**Comment by mbakholdina** [comment]
Closing the ticket as "Can't Reproduce". The recommendations were given in the [following comment](https://github.com/Haivision/srt/issues/1237#issuecomment-668604072), however there was no further feedback provided. Please feel free to reopen in case of further questions.
