### ISSUE TITLE
srt-live-transmit one to many [no multicast]

### ISSUE THREAD

**Issue by AlexandreLicinio** [Haivision/srt#1250]
Hi, 

Is there a way to share a single input (either SRT or UDP) to many outputs (either UDP or SRT) with srt-app-transmit ? 

imagine for srt to many udp:
```
srt-live-transmit srt://:5000 udp://127.0.0.1:6001 udp://127.0.0.1:6002 udp://127.0.0.1:6003
```
and imagine for udp to many srt:
```
srt-live-transmit udp://:7000 srt://:6001 srt://:6002 srt://:6003
```
i did play with `file://con` and `tee` but no success. Also i tried `?reuse` like in ffmpeg but no success too.

Thanks

**Comment by ethouris** [comment]
This application supports only one stream transport between two media. It's the limitation of the application.

**Comment by AlexandreLicinio** [comment]
ok thanks @ethouris

**Comment by Bond246** [comment]
Hi,
i would like to open this discussion again.

What has to be done to have a one to many configuration? Some brands tell this feature "srt on request" in their products. Does this depents on individual software implementations or are there any tools within the open source srt-toolkit to get this function?

**Comment by maxsharabayko** [comment]
From the code perspective, it needs several targets [here](https://github.com/Haivision/srt/blob/master/apps/srt-live-transmit.cpp#L804). And some logic to connect/reconnect targets in a separate thread, not affecting the main loop.

We do not consider adding this functionality to srt-live-transmit any time soon.
[TSDuck](https://tsduck.io/) had recently added support for SRT. Please check if there is some processing plugin that can do it.

As some very hacky alternative maybe something can be built using the `tee` command and `file://con` input and output of `srt-live-transmit`. Create a pipe for the output of `srt-live-transmit`. Copy its contents to several different pipes. Then use standalone `srt-live-transmit` with `file://con` as an input for each target.
