### ISSUE TITLE
Status of Application-Supplied Timestamps

### ISSUE THREAD

**Issue by BananaHemic** [Haivision/srt#126]
Hey everyone,

I've been using SRT for about two weeks and I've been loving the protocol.
I'd like to add to the stream timestamps generated by my application, so that I can synchronize some out-of-band data to the stream on the receiver. 

The code for application supplied timestamps seems to be in place but the warning in srt.h:

>  the functionality of application-supplied timestamps
> also doesn't work properly. Left for future until the problems are solved.

Is a bit alarming to me. How severely will adding application-supplied timestamps affect the stream? Will it just interfere with some drift calculations, or should I expect the stream to be completely broken?

**Comment by ethouris** [comment]
As I remember, what is lacking here is the correct time base. It's not even important what this time exactly is, important is that the time distance between subsequent packets are "identical with original". Currently the "time to play" at the reception side is calculated basing on the time base as received in the beginning, and this (plus the latency) is used to convert the timestamp received in the packet into the local "time to play".

Not sure if this is going to work, but I think it should work if you have some "originally" received timestamps from somewhere else and recalculate these timestamps into the local timestamps at the machine that is a sender. As long as these timestamps are from the same "time domain" as timestamps that would be taken automatically, it should work as expected. There's nothing else done than when you don't supply your own timestamp, the timestamp will be filled in from the current time, that is, it will be the time at the moment when your packet is scheduled for sending.

Passing the timestamps directly from some other "time domain" would require that the time base for that time domain be passed somehow to the other side, and this is currently not implemented.
