### ISSUE TITLE
Haivision gateway is accepting our stream yet reporting it's not receiving anything

### ISSUE THREAD

**Issue by karlbrowns** [Haivision/srt#1264]
I have been using stransmit from github for as long as it's been available, and it works a treat running on an embedded Linux system.  I updated to a later version of stransmit about 2 years ago.

Twice in the last 12 hours we've had a situation where the stream is being sent to a Haivision cloud gateway.  The gateway claims it is connected to our SRT transmitter, and using iftop I can see our system is sending 6Mbps of data to the gateway.  However the gateway says 0bps are being received.

As I understand SRT, and from previous testing, if no SRT connection is established no data would be sent.  So given that data is being sent why does the gateway think it is not receiving anything?  Is this a bug or a change in the gateway?

Cheers,
Simon

**Comment by ethouris** [comment]
Depends on what other premises state about as to whether data are transmitted over the connection or not. Such as:
 - you can see any data transmitted through the gateway (on the output)
 - the sender stats report any sent packets

**Comment by karlbrowns** [comment]
The gateway claimed it wasn't receiving any data (but was connected), and we couldn't receive the stream on the output of the gateway.
The sender - I can't get the stransmit stats directly but I could use iftop to see that 6Mbps were being sent to the gateway.  I know that if it doesn't have a connection then I get bursts of perhaps 50kbps and then nothing to the gateway.  So stransmit clearly thought it had a connection and was merrily sending the data.  The gateway clearly thought it had a connection and was merrily discarding any data that came its way.

I'm going to run some more tests locally now and see if I can find where it breaks, but is there incompatibility between stransmit from 2 years ago and a recently updated gateway?

**Comment by Svyatk0** [comment]
hey @karlbrowns out of interest, what are the versions of stransmit and Gateway ?

**Comment by ethouris** [comment]
From your description it is unclear to me as to whether the UDP packets carrying the SRT traffic (or only data) really are sent or not. Maybe grabbing a pcap at both sides would shed some light there. The problem is that the number of received packets includes all packets - regardless if they turn into packets delivered to the application or not.

**Comment by karlbrowns** [comment]
@Svyatk0 The Haivision gateway is version 3.3.0. build 127.  Stransmit is 1.3.1

@ethouris If the gateway is saying the state of the connection is "Connected" rather than "Connecting" I have to assume that the stransmit is making the connection with SRT.  At that point I'm surprised the data could go outside of stransmit.

**Comment by ethouris** [comment]
Right. Therefore the connection should be established. But the data not necessarily come out of stransmit.

**Comment by karlbrowns** [comment]
Thanks for your input - I think I have found the issue in the way stransmit is called from my end.
