### ISSUE TITLE
[BUG] Cookie contest behavior does not match documentation

### ISSUE THREAD

**Issue by russelltg** [Haivision/srt#1267]
**Describe the bug**
The documentation states (in handshake.md):

> When one party's cookie value is greater than its peer's, it wins the cookie contest and becomes Initiator (the other party becomes the Responder).

However, the cookie contest subtracts the peer's cookie from the host's cookie, then compares with zero. This works in many cases, but cookies can have large absolute value, as they are hashes so each bit (in theory) has equal entropy. This can cause integer underflow, and have a negative cookie win against a positive cookie. 

Adding a few print statements to `CUDT::cookieContest`, it's typical to get 

```
cookieContest: agent=-1852209696 peer=1950268229
cookie contest won, initator
```

**To Reproduce**
1. Add the print statements
2. Run SRT in rendezvous modes a few times

**Expected behavior**
Documentation matches. This probably means updating docs with the real cookie contest algorithm, as it likely shouldn't change

**Desktop (please provide the following information):**
 - OS: [e.g. Windows, Linux, macOS,...] linux, but doesn't matter
 - SRT Version / commit ID: db097fad533938aa49f5beaf318160947c408499

**Additional context**
I'm writing an alternative implementation of SRT, and found it surprising.

**Comment by ethouris** [comment]
I understand that the description does not precisely describe how the cookie contest is made, but it doesn't change anything in the functionality. It actually doesn't matter, which will turn out to be winner or loser. What matters is that this operation is done on both independent sides of the connection and they come to identical results, by applying loser on itself and winner on the peer, or vice versa.

I'd add here only that the signed overflow is not taken into account in this comparison, but it doesn't master for the overall process - that's of course fair to be added.

**Comment by jeandube** [comment]
@ethouris is right, documentation may be wrong but the mechanism works. Changing it would  introduce interoperability problems unless complexity is added to fallback on old method when peering with older implementation.

**Comment by maxsharabayko** [comment]
### TODO
- [ ] Fix cookie contest in the docs (handshake.md)
- [ ] Fix cookie contest in the RFC draft ([GitHub](https://github.com/Haivision/srt-rfc))

**Comment by maxsharabayko** [comment]
The described behavior is unfortunatelly since the introduction of the HSv5 cookie contest in v1.3.0. Preserving it for now.
Updated documentation and provided an algorithm not relying on integer overflow in PR #1517.
