### ISSUE TITLE
“../common/appcommon.hpp”: No such file or directory

### ISSUE THREAD

**Issue by changtj** [Haivision/srt#1277]
os:windows 
tool: cmake ui

i new a project with vs 2017,  inlude examples files, build , then output this error.

**Comment by changtj** [comment]
in suflip.cpp

#include "../common/appcommon.hpp"
#include "../common/uriparser.hpp"

**Comment by mbakholdina** [comment]
Hi @changtj, thank you for reporting the issue. The issue is fixed within the PR #1280. In case the problem is still there on your side, please let us know and do not hesitate to reopen the issue.
