### ISSUE TITLE
SRT LOST PACKET STATS

### ISSUE THREAD

**Issue by dduquesne** [Haivision/srt#1287]
Hello,

We are trying to use the SRT stats.
The idea behind is to assess if we have "definitely lost" packets during a transmission.
We collect all the SRT metrics.
But we don't realy understand how tu use them.
There is apparently no obvious value saying how many packet are "definitely lost".

https://github.com/Haivision/srt/blob/master/docs/statistics.md

From what we undeerstand ( !!! Statement below are my understanding and maybe totaly wrong !!! ):

- 1 : pktRcvLoss = the number of pkt declared "lost" at receiver side. But this is before any retransmission. Those pkt are maybe not "definetly lost" and if SRT do the job, they should be retransmited.

- 2 : pktSndLoss = the number of pkt declared "lost" at sender side. The sender compile it's own assessment (tlpktdrop) with receiver report. It should be pktRcvLoss + X .

- 3 : pktRetrans = number of retransmitted packets sent by the SRT sender. Available for sender. This number tel us how many packet are retransmited. But we assume this number is not easy to corelate with pktSndLoss as 1 lost packet could be retransmited X time.

-4 : pktRcvRetrans = number of retransmitted packets registered at the receiver side. Available for receiver. Again this is not easy to corelate with pktRcvLoss because :
      1 : lost packet could be retransmited X time.
      2 : pktSndLoss  != pktRcvLoss

Then Lost Retrans pkt at receiver are not part of pktRcvLoss.
Retrans pkt are distinguished.
Lost Retrans pkt can be calculated with  pktRetrans - pktRcvRetrans after compilation of sender and receiver stats ( Not always possible when one peer is a third party ).
But again, as a pkt can be retransmited many times, it does not tell us how many packet are "definetly lost".
We can use a TS analyser at the end and see how many packet are definetly lost.
But it's not always possible.
We would expect SRT stats to give us this number ( Which is maybe the most important value ).
In addition, that prevent us showing those stats to our customers/management.
Because at first look and without any deep analysis, one can look at the pktRcvLoss curve and say "Oh ! it does not work " while the protocol is indeed doint the recovery job.

Is there any way to compute a "definetly lost" metric ?
Any plan to introduce this metric in a future release ?

Many thanks for your help,

**Comment by ethouris** [comment]
Ok, we are using specific definitions for that mechanism - maybe this deserves a separate description.

It works this way:

1. When the receiver receives a packet, it notifies its sequence number and places it in the receiver buffer. When the sequence number is not contiguous (not previous + 1), it notifies a loss and:
   * pktRcvLoss is increased (by the number of lacking packets before this one)
   * the buffer has a hole at this position (or positions)
   * loss report is sent immediately

2. When the sender receives the loss report, it updates the loss record and:
   * pktSndLoss is increased with every newly found loss
   * the packets are scheduled for sending, this time with R flag
   * note that if a packet was once lost, retransmitted, then loss-reported again (through the periodic NAKreport mechanism), it will be notified in pktSndLoss again

3. When the packet is received with R flag set
   * it increases pktRcvRetrans
   * it's placed in the receiver buffer at its position, possibly sealing a hole
   * might be that this is an excessive retransmission (that is, the packet is already there)

4. With TSBPD turned on (default), packets are delivered to the application when the time comes, and until then they remain in the receiver buffer. The time of delivery is calculated, simplifying, basing on the packet's timestamp and latency. When after delivering particular packet the next position in the buffer is empty, but there are some packets after the hole, this packet's delivery time is also taken into account. If the hole isn't sealed until the play time comes for this packet, those lost packets are now forgotten forever - that is DROPPED. This increases the pktRcvDrop stat.

**Comment by mbakholdina** [comment]
Hi @dduquesne, thank you for reporting the issue! There is a plan to improve the calculation of `pktRcvLossTotal` statistic in the upcoming release, see issue #1212. Currently, this statistic contains not lost but presently missing packets (either reordered or lost). Plus it additionally 
counts packets that failed to be decrypted (since v.1.4.0) which is not correct as well. We have a separate statistic pktRcvUndecryptTotal for this. Please follow the issue #1212 to be updated on the improvements.

**Comment by dduquesne** [comment]
Hello @ethouris & @mbakholdina  
Many thanks for this detailled answer.
So from you explainations, I think pktRcvDrop is what we are looking for.

**Comment by mbakholdina** [comment]
@dduquesne You are welcome! Closing the issue, please feel free to reopen in case of further questions.

**Comment by glowfishDE** [comment]
hi guys. Is this still in planning ?

**Comment by maxsharabayko** [comment]
@glowfishDE If you mean #1212, it is in the backlog. Not assigned to any release yet. Contributions are welcome.
