### ISSUE TITLE
README for CentOS 6

### ISSUE THREAD

**Issue by blakewenzel** [Haivision/srt#13]
There are several encoding appliances still on CentOS 6, having instructions to make it work would be useful.

Compiling and running on CentOS 6 using the README for CentOS 7 results in the following runtime errors:

```
stransmit: /usr/lib64/libstdc++.so.6: version 'GLIBCXX_3.4.20' not found (required by stransmit)
stransmit: /usr/lib64/libstdc++.so.6: version 'GLIBCXX_3.4.19' not found (required by stransmit)
stransmit: /usr/lib64/libstdc++.so.6: version 'GLIBCXX_3.4.15' not found (required by stransmit)
```

**Comment by blakewenzel** [comment]
Being worked on the pull request #12

**Comment by rndi** [comment]
#12 has been merged, README updated for CentOS 6 instructions, closing this issue.

Thanks @blakewenzel !
