### ISSUE TITLE
[BUG] Cannot connect using IPv6 address on v1.4.1

### ISSUE THREAD

**Issue by jeandube** [Haivision/srt#1308]
srt_connect() fails when using an IPv6 address with SRT v1.4.1. it used to work with earlier versions but with the obsolescence of srt_socket(int af, int type, int protocol), the address family of the socket is no longer provided and assume IPv4 by default. Looks like a work in progress toward AF independence. The code at the head of master branch is different but I cannot find the commit fixing this issue. I don't want to grab all the added features of 1.5.0.

**Comment by ethouris** [comment]
The only thing that was changed here for that purpose was that the creation of the real UDP socket was delayed up to the moment when the family is known, either through `srt_bind` or `srt_connect`. There's no IPv4 assuming at all. The family is exactly the one that you specify in `srt_bind` or `srt_connect` - where you specify the "sockaddr" argument and must set the IP version correctly anyway.

**Comment by jeandube** [comment]
Problem was in the app wrongly adapted to use srt_create_socket() instead of srt_socket() if version >=1.4.1. Fix was implemented while testing with master head which is 1.4.1++ but srt_socket was not yet deprecated in 1.4.1. adaptation should be for versions > 1.4.1.
