### ISSUE TITLE
How we can use (.so) libraries in our android project

### ISSUE THREAD

**Issue by shailendrapokhriyal96** [Haivision/srt#1310]
When asking a question please also include where you looked for an answer (so we can update the documentation if needed).

You are encouraged to ask general questions regarding SRT in the [SRT Alliance Slack channel](https://slackin-srtalliance.azurewebsites.net/).

**Comment by maxsharabayko** [comment]
There is the following guide for Android contributed by the community [Android Compilation Guide](https://github.com/Haivision/srt/blob/master/docs/Android/Compiling.md)
Hope that helps.
