### ISSUE TITLE
How could i fix this "this_thread" problem?

### ISSUE THREAD

**Issue by kaka2436** [Haivision/srt#1311]
when i build a .a for Android, i had get some error like this:

> /srt/docs/Android/srt/srtcore/api.cpp:2669:7: error: reference to 'this_thread' is ambiguous
      this_thread::sleep_for(milliseconds_from(1));
      ^
/opt/ndk/android-ndk-r21/toolchains/llvm/prebuilt/linux-x86_64/bin/../sysroot/usr/include/c++/v1/__threading_support:472:11: note: candidate found by name lookup is 'std::__ndk1::this_thread'
namespace this_thread
          ^
/home/parallels/work/srt/docs/Android/srt/srtcore/sync.h:781:11: note: candidate found by name lookup is 'srt::sync::this_thread'
namespace this_thread

i edit and run the script that in "srt/docs/Android/mkall",and how could i fix this problem?
my environment: 
system: ubuntu 18.04
NDK: android-ndk-21
cmake: 3.10.2

thanks very much!

**Comment by kaka2436** [comment]
Unittests fixed for the case ENABLE_STDCXX_SYNC=ON

**Comment by dkozinski** [comment]
I am about to compile SRT library and got the same issue.
How did you resolve it?

my environment:
system: WSL (WIndows subsystem for Linux) - ubuntu 18.04
NDK: android-ndk-21
cmake: version 3.17.3
srt branch: master
release: 1.4.1

**Comment by ethouris** [comment]
Where exactly do you get this error? This might be some kinda intermediate problem when you include both `<thread>` and the `"sync.h"` header in POSIX wrapper version. May happen when a file contains both `using namespace srt::sync` and `using namespace std`.

**Comment by ethouris** [comment]
Would you be able to track down as to how it happened that `api.cpp` has effectively included `<thread>` header?

Probably replacing `using namespace srt::sync` with `using srt::sync::this_thread` might fix this. Likely no other parts from the namespace are used here.

**Comment by kaka2436** [comment]
> I'm trying to compile SRT library and got the same issue.
> How did you resolve it?
> 
> my environment:
> system: WSL (WIndows subsystem for Linux) - ubuntu 18.04
> NDK: android-ndk-21
> cmake: version 3.17.3
> srt branch: master
> release: 1.4.1

change here from OFF to ON：
file：srt/CMakeLists.txt
 
line 118: option(ENABLE_STDCXX_SYNC "Use C++11 chrono and threads for timing instead of pthreads" ON)

**Comment by dkozinski** [comment]
> Probably replacing `using namespace srt::sync` with `using srt::sync::this_thread` might fix this. Likely no other parts from the namespace are used here.

Guys thank you for your help.
Unfortunately, a single replacement `using namespace srt::sync` with `using srt::sync::this_thread` was not enough to fix the issue. The change caused the need for further changes (error: use of the undeclared identifier "steady_clock ...") and so on etc. (Name of unknown type "CGuard" ...). Too many changes were needed and I had to give up (at least for today).

Switching 'ENABLE_STDCXX_SYNC' CMake cache variable from OFF to ON made me able to build SRT for Android.

**Comment by ethouris** [comment]
Unfortunately, Android support has been provided entirely by the community. Probably it would be needed that the standard scripts to build on Android use `-DENABLE_STDCXX_SYNC=ON` flag by default.
