### ISSUE TITLE
Exception when closing active connection in test application

### ISSUE THREAD

**Issue by EladHarmonic** [Haivision/srt#132]
When creating a test application which has a blocking listener SRT socket and a blocking Caller SRT socket, both active on different threads, communication is established correctly, data is exchanged correctly but application crashes when one of sockets is closed using srt_close() api.

**Comment by ethouris** [comment]
Would you be able to:
- reproduce this problem after compiling SRT in debug mode
- run the application with all logs turned on (from the SRT API: `srt_setloglevel(LOG_DEBUG)`)
- paste the stack trace here
?

The expected reaction on reading from a socket that has been closed, including closed while simultaneously reading or writing in another thread, is to return error when trying to read or write with this socket. If you have handled the returned value from these functions correctly, I would very keenly like to know where it could crash.

**Comment by EladHarmonic** [comment]
I don't get a meaningful stack trace, all I get is the following (after call to srt_close())
     [exec] unknown file: Failure
     [exec] C++ exception with description "No associated state" thrown in the test body.

I don't get much prints from the library itself, is the part before the crash (added logger callback for debug messages)
     [exec] 2017-10-25 08:49:26,595 INFO  core.ip.srt.itransceiver.csrttransceiver - CSrtTransceiver::Connect[SrtSocket]: Connected!
     [exec] 2017-10-25 08:49:26,595 INFO  core.ip.srt.ut - Listener: Sending Buffer to transmitter [This is message from listener to transmitter] total bytes sent [45]
     [exec] 2017-10-25 08:49:26,595 DEBUG core.ip.srt.library - 08:49:26.595716/ut D: SRT.t: recvmsg: DATA COND: KICKED.
     [exec] 
     [exec] 2017-10-25 08:49:26,595 INFO  core.ip.srt.ut - Caller: Received Buffer [This is message from listener to transmitter] total bytes received [45]
     [exec] 2017-10-25 08:49:26,595 INFO  core.ip.srt.ut - Caller: Sending Buffer from caller [This is message from caller to listener] total bytes sent [40]
     [exec] 2017-10-25 08:49:26,596 DEBUG core.ip.srt.library - 08:49:26.596115/SRT:RcvQ:worker D: SRT.c: Spawning TSBPD thread
     [exec] 
     [exec] 2017-10-25 08:49:26,697 DEBUG core.ip.srt.library - 08:49:26.697592/ut D: SRT.t: recvmsg: DATA COND: KICKED.
     [exec] 
     [exec] 2017-10-25 08:49:26,697 DEBUG core.ip.srt.library - 08:49:26.697653/ut D: SRT.t: recvmsg: KICK tsbpd() (buffer empty)
     [exec] 
     [exec] 2017-10-25 08:49:26,697 INFO  core.ip.srt.ut - Listener: Received Buffer [This is message from caller to listener] total bytes received [40]
     [exec] 2017-10-25 08:49:26,697 INFO  core.ip.srt.ut - Asking Caller to Disconnect
     [exec] 2017-10-25 08:49:26,697 INFO  core.ip.srt.ut - Caller: Disconnecting
     [exec] 2017-10-25 08:49:26,697 INFO  core.ip.srt.itransceiver.csrttransceiver - CSrtTransceiver::Disconnect: Release connected socket [430865053]
     [exec] 2017-10-25 08:49:26,697 INFO  core.ip.srt.itransceiver.csrttransceiver - CSrtTransceiver::Disconnect: Disconnected socket
     [exec] unknown file: Failure
     [exec] C++ exception with description "No associated state" thrown in the test body.

**Comment by EladHarmonic** [comment]
Hi,
found the issue, not related to SRT, but to using std::future in different contexts. 
Thanks
