### ISSUE TITLE
Listener side stats (no stats for SRT output)

### ISSUE THREAD

**Issue by kmudide** [Haivision/srt#135]
Hi,

    I am using -s option for the listener to print stats. I was expecting the listener to print
    sender's stats as well. As you can see below, sent packets is zero and this is probably 
    because listener is not sending any TS packets other than control messages. 

    I want listener to print sender side stats as well. Is this information available in listener? 
    I know both caller and listener use same code (CUDT, UDT, Source, Target, etc).  
    I am thinking that CUDT member variable have sender's stats.

    If so, can anyone share some info on this?

======= SRT STATS: sid=934219591
PACKETS SENT: 0 RECEIVED: 619022
LOST PKT SENT: 0 RECEIVED: 0
REXMIT SENT: 0 RECEIVED: 3346
RATE SENDING: 0 RECEIVING: 1.90861
BELATED RECEIVED: 0 AVG TIME: 0
REORDER DISTANCE: 0
WINDOW: FLOW: 8192 CONGESTION: 8192 FLIGHT: 0
RTT: 10.599ms  BANDWIDTH: 9.492Mb/s
BUFFERLEFT: SND: 12288000 RCV: 12252000

**Comment by jeandube** [comment]
Your listener is definitively a receiver from the stats. For the receiver to display the sender stats the sender would need to send them to the receiver. This is not something SRT does. Some stats, usefull to flow control such as the measured RTT, receiver buffer usage, are sent from the receiver to the sender but not the packet counters.

**Comment by ethouris** [comment]
Well, ok, I've reviewed the sources and seems like the statistics reading and displaying is supported only for receiving in `stransmit` - the call is only in `SrtSource::Read`, but there's no such call in `SrtTarget::Write`. It's not that the statistics can't be read in the other direction, it's that this call is missing and wasn't previously predicted.

This can be easily changed; I suspect a more troublesome issue here would be to have an appropriate option to turn on statistics only for input or output or both. I thing we should rather deprecate the `-s` option and turn it into a parameter in the SRT URI. Anyone has idea for the name for such a parameter?

This would still be a parameter managed only in the application support library. What we need is:
* the name should suggest "stats report"; probably similar thing would be needed for "bandwidth report"
* the assigned value is an integer that counts the number of single buffers (say, single UDP packets) to pass between two consecutive reports

Something like `statsrep=10` (and `bwrep=10`) would be acceptable?

**Comment by kmudide** [comment]
In stats report, what are the units of rate sending and receiving values?  Also, what is bufferleft: SND <> RCV <>? In my stats, I see SND value does not change but RCV changes constantly.

It's better to add stats's description to README file.

Thanks for your time.

**Comment by kmudide** [comment]
In the stats, pasted below, I see bandwidth in Gbps. I know that I am not sending video at this rate. Is this indicating that available bandwidth between caller and listener?

======= SRT STATS: sid=146037650
PACKETS SENT: 0 RECEIVED: 2102
LOST PKT SENT: 0 RECEIVED: 0
REXMIT SENT: 0 RECEIVED: 62568
RATE SENDING: 0 RECEIVING: 1.35041
BELATED RECEIVED: 0 AVG TIME: 0
REORDER DISTANCE: 0
WINDOW: FLOW: 8192 CONGESTION: 8192 FLIGHT: 0
RTT: 0.235ms  BANDWIDTH: 2252.57Mb/s
BUFFERLEFT: SND: 12288000 RCV: 12138000
======= SRT STATS: sid=146037650
PACKETS SENT: 0 RECEIVED: 3046
LOST PKT SENT: 0 RECEIVED: 0
REXMIT SENT: 0 RECEIVED: 62569
RATE SENDING: 0 RECEIVING: 1.46354
BELATED RECEIVED: 0 AVG TIME: 0
REORDER DISTANCE: 0
WINDOW: FLOW: 8192 CONGESTION: 8192 FLIGHT: 0
RTT: 0.183ms  BANDWIDTH: 3821.23Mb/s
BUFFERLEFT: SND: 12288000 RCV: 12216000

**Comment by ethouris** [comment]
Please paste it to a separate issue ticket. Looks like a bug, at least in the unit used in the application, but I'd have to make more research to be sure.

**Comment by maxlovic** [comment]
**Closing.**
Listener side stats (no stats for SRT output) fixed. 
Created #599 for the estimated bandwidth issue.

**Comment by maxlovic** [comment]
Actually there was #141
