### ISSUE TITLE
Save stats in useable form

### ISSUE THREAD

**Issue by karlbrowns** [Haivision/srt#1368]
Using srt-live-transmit I can get stats printed out to the terminal every 10 seconds or whatever, using the -s :10 option.  Is it possible to collect these stats in a more useable format, eg into a database or csv file for historical analysis?  Has anyone done this?  Is it obvious where in the code I would need to add something?

Cheers,
Simon

**Comment by maxsharabayko** [comment]
Hi.
`-s` option of srt-live-transmit defines the stats period **in packets**, not in milliseconds.

By dividing your sending rate on 1500 bytes you could roughly estimate the number of packets per second and use this value.

**Comment by karlbrowns** [comment]
Thank you, but I don't really want the data output to the terminal.  Where is the code that produces the -s output so that I can add in a few lines of my own to output the data in the format I want to a file and/or database?

But thank you for explaining that -s defines the period in packets, because that isn't clear in any of the documentation I've seen.  It would explain why whenever I've used it I've set the number quite high.

**Comment by maxsharabayko** [comment]
Please take a look at [srt-live-transmit.md](https://github.com/Haivision/srt/blob/master/docs/srt-live-transmit.md#command-line-options) document.

There is `-statsout` command line option to output stats to file.
Also `-pf` sets the print format (JSON, CSV).

**Comment by karlbrowns** [comment]
Thank you.
