### ISSUE TITLE
[BUG] repeated log on stable stream: epoll/update: IPE: update struck EID 1 which is NOT SUBSCRIBED

### ISSUE THREAD

**Issue by jeandube** [Haivision/srt#1370]
repeated error log on an otherwise stable rx-only stream. Stream is the accepted socket from a listening socket. Attaching a heavy log trace to issue. build 92abcd6 (Jun 19) with a pull request in progress (new get/set option not touching epoll). I had to truncate the file to upload it here with 2 occurrences of error log. Full file available offline upon request.
[EID1-truncated.log](https://github.com/Haivision/srt/files/4820119/EID1-truncated.log)

**Comment by ethouris** [comment]
Looxlike `CUDTUnited::epoll_remove_entity` needs some locking, or possibly the order should be altered. The current code leaves a risk that the `update_event` function is called between two removals.
