### ISSUE TITLE
IPv6 seems not working on srt-live-transmit

### ISSUE THREAD

**Issue by Litrona** [Haivision/srt#1371]
Downloaded the latest main trunk and compiled, been testing IPv6 on srt-live-transmit, but seems not working.

Cmdlines used in the same machine:
srt-live-transmit udp://238.0.0.1:1234 srt://:5000 -s:500
srt-live-transmit srt://[::1]:5000 udp://127.0.0.1:5000 -s:500

But nothing happens, no connection at all.
However, if I did it on IPv4 works:
srt-live-transmit udp://238.0.0.1:1234 srt://:5000 -s:500
srt-live-transmit srt://127.0.0.1:5000 udp://127.0.0.1:5000 -s:500
 
Am I missing anything ?
Thanks

**Comment by ethouris** [comment]
Empty host defines IPv4 `INADDR_ANY`. In order to make the IPv6 "any" you have to specify the listener address as `[::]` (note that in this case `mode=listener` must be added explicitly). Whether it accepts also IPv4 connections, it depends on the `ipv6only` flag, which's value is default for the system (see `ipv6(7)`, `IPV6_V6ONLY`).

**Comment by Litrona** [comment]
I also tested it:

srt-live-transmit udp://238.0.0.1:1234 srt://[::]:5000?mode=listener -s:500

**Comment by Litrona** [comment]
I also tested it:
srt-live-transmit udp://238.0.0.1:1234 srt://[::]:5000?mode=listener -s:500
srt-live-transmit srt://[::1]:5000 udp://127.0.0.1:5000 -s:500

But the 1st cmdline, when second is executed, responses:
edia path: 'udp://238.0.0.1:1234' --> 'srt://[::]:5000?mode=listener'
ERROR: error: srt_accept: Operation not supported: Bad parameters

Can you tell me what are the parameters I'm supposed to use in this sense ?
Thanks.

**Comment by ethouris** [comment]
You're right. The `srt-live-transmit` application wasn't added a proper fix when IPv6 support was added. The same thing works when you run `srt-test-live` for the listener part. I'll use your issue as a bug report.
