### ISSUE TITLE
Rendezvous mode and IPv4 <=> IPv6

### ISSUE THREAD

**Issue by Litrona** [Haivision/srt#1376]
Is it possible to connect IPv4 and IPv6 addresses using rendezvous mode ? Or both ends have to use the same version of IP protocol ?.
Thanks.

**Comment by ethouris** [comment]
The general rule for rendezvous is that the socket is expecting a connection from the exact other party that it is trying to connect. As long as you can connect an IPv6 listener from both IPv4 and IPv6 callers, there's no way how you could connect IPv6 caller to IPv4 listener, even if this IPv6 caller is using IPv4-mapped-on-IPv6 address.
