### ISSUE TITLE
[BUG] srt-live-transmit mode rendezvous not working on IPv6 [apps]

### ISSUE THREAD

**Issue by Litrona** [Haivision/srt#1377]
Latest commit on main trunk tested on Linux Debian 10 64 bits:

Sender End (IPv6 addr: 2001:41d0:YYY:YYY::YYY):
srt-live-transmit udp://127.0.0.1:1234 srt://[2607:5300:XXX:XXX::XXX]:5000?mode=rendezvous -s:500

Receiver End (IPv6 addr: 2607:5300:XXX:XXX::XXX):
srt-live-transmit srt://[2001:41d0:YYY:YYY::YYY]:5000?mode=rendezvous udp://127.0.0.1:9000 -s:500

No connection at all between them on IPv6.
Changed to IPv4, just changing address:
- Target connected on source side inmediately
- Source connected on targe side when UDP packets start to be sent to Sender side.

Anybody tested this ?.
Thanks.

**Comment by ethouris** [comment]
You need to add an extra option: `adapter`, if you want to use IPv6, at least as `::`. Otherwise the socket will be bound as IPv4.

**Comment by ethouris** [comment]
BUT: please do not close this Issue. At least the documentation should be fixed.

**Comment by ethouris** [comment]
UPDATE: The documentation should be updated, but a fix can be provided, too. In case of Rendezvous, if you specify an IPv6 destination address, then it may enforce using IPv6 'any' binding address, too, without the need of specifying it explicitly.

**Comment by Litrona** [comment]
Yes, only rendezvous IPv6 needs to specify the adapter. 
I was unable to conect 2 rendezvous between IPv4 <=> IPv6, I guess is not possible, no need to specify the adapter.

**Comment by ethouris** [comment]
Listener requires, too. And this better stays as is.
