### ISSUE TITLE
Bandwidth report in stats

### ISSUE THREAD

**Issue by kmudide** [Haivision/srt#141]
In the stats, pasted below, I see bandwidth in Gbps. I know that I am not sending video at this rate. Is this indicating that available bandwidth between caller and listener?

======= SRT STATS: sid=146037650
PACKETS SENT: 0 RECEIVED: 2102
LOST PKT SENT: 0 RECEIVED: 0
REXMIT SENT: 0 RECEIVED: 62568
RATE SENDING: 0 RECEIVING: 1.35041
BELATED RECEIVED: 0 AVG TIME: 0
REORDER DISTANCE: 0
WINDOW: FLOW: 8192 CONGESTION: 8192 FLIGHT: 0
RTT: 0.235ms BANDWIDTH: 2252.57Mb/s
BUFFERLEFT: SND: 12288000 RCV: 12138000
======= SRT STATS: sid=146037650
PACKETS SENT: 0 RECEIVED: 3046
LOST PKT SENT: 0 RECEIVED: 0
REXMIT SENT: 0 RECEIVED: 62569
RATE SENDING: 0 RECEIVING: 1.46354
BELATED RECEIVED: 0 AVG TIME: 0
REORDER DISTANCE: 0
WINDOW: FLOW: 8192 CONGESTION: 8192 FLIGHT: 0
RTT: 0.183ms BANDWIDTH: 3821.23Mb/s
BUFFERLEFT: SND: 12288000 RCV: 12216000

**Comment by maxlovic** [comment]
@kmudide 
> In the stats, pasted below, I see bandwidth in Gbps. I know that I am not sending video at this rate. Is this indicating that available bandwidth between caller and listener?

The bandwidth estimation is based on the time difference between consecutive probing packets sent almost immediately one after another in certain probing periods. This is more a guess of the potential bandwidth of the channel, or the potential maximum possible sending bitrate between sender and receiver.
What was the network setup in that experiment? E.g. local 1 Gbps switch, some pubic network or else?

**Comment by maxlovic** [comment]
Closing, as the question was:
> Is this indicating that available bandwidth between caller and listener?

The answer is yes, it is an estimation of the available bandwidth.
