### ISSUE TITLE
How can I a encryption stream with srt and ffmpeg 

### ISSUE THREAD

**Issue by David-E91** [Haivision/srt#1411]
Hy Guys 

I'm new with streaming over SRT. 
My stream with the following command works fine:
 
Caller:
ffmpeg -v "trace" -re -i test.mkv -f mpegts "srt://127.0.0.1:1234?pkt_size=1316&mode=caller"

Listener:
ffmpeg -v "trace" -re -i "srt://127.0.0.1:20000?pkt_sizr=1316&mode=listener" -f mpegts test.mp4

how can I encrypt this stream?

**Comment by ethouris** [comment]
Just set the `passphrase` option. Optionally you can set `pbkeylen` to define the key length (default is 16, that is, AES-128).

Note that I'm talking about the SRT socket option, I don't know how it maps to ffmpeg URI syntax.

**Comment by maxsharabayko** [comment]
> Just set the `passphrase` option. Optionally you can set `pbkeylen` to define the key length (default is 16, that is, AES-128).
> 
> Note that I'm talking about the SRT socket option, I don't know how it maps to ffmpeg URI syntax.

The same in FFMpeg: [link](https://www.ffmpeg.org/ffmpeg-protocols.html#srt).
Please also note [this guide](https://srtlab.github.io/srt-cookbook/apps/ffmpeg/).

**Comment by maxsharabayko** [comment]
Closed as resolved.
