### ISSUE TITLE
"make: *** [ffbuild / common.mak: 59: libavformat / libsrt.o] Error 1"

### ISSUE THREAD

**Issue by OscarParzon** [Haivision/srt#1413]
any ideas to get out of this error?
any help will be welcome !!

I try to compile ffmpeg with srt.

git clone --depth 1 https://github.com/Haivision/srt.git
cmake -DENABLE_C_DEPS=ON -DENABLE_SHARED=ON -DENABLE_STATIC=OFF -fPIC
make
make install
- without errors -

ffmpeg-4.3.1

./configure --enable-libsrt --enable-libx264 --enable-libx265 --enable-gpl
make
error:
-----------------------------------
libavformat / libsrt.c: In function ‘libsrt_set_options_pre’:
libavformat / libsrt.c: 317: 66: error: ‘SRTO_STRICTENC’ undeclared (first use in this function); did you mean ‘SRTO_STATE’?
  317 | (s-> enforced_encryption> = 0 && libsrt_setsockopt (h, fd, SRTO_STRICTENC, "SRTO_STRICTENC", & s-> enforced_encryption, sizeof (s-> enforced_encryption)) <0) ||
      | ^ ~~~~~~~~~~~~~
      | SRTO_STATE
libavformat / libsrt.c: 317: 66: note: each undeclared identifier is reported only once for each function it appears in
libavformat / libsrt.c: 336: 50: error: ‘SRTO_SMOOTHER’ undeclared (first use in this function); did you mean ‘SRTO_SENDER’?
  336 | (s-> smoother && libsrt_setsockopt (h, fd, SRTO_SMOOTHER, "SRTO_SMOOTHER", s-> smoother, strlen (s-> smoother)) <0) ||
      | ^ ~~~~~~~~~~~~
      | SRTO_SENDER
libavformat / libsrt.c: In function ‘libsrt_setup’:
libavformat / libsrt.c: 409: 5: warning: ‘srt_socket’ is deprecated [-Wdeprecated-declarations]
  409 | fd = srt_socket (cur_ai-> ai_family, cur_ai-> ai_socktype, 0);
      | ^ ~
In file included from libavformat / libsrt.c: 24:
/usr/local/include/srt/srt.h:723:41: note: declared here
  723 | SRT_ATR_DEPRECATED_PX SRT_API SRTSOCKET srt_socket (int, int, int) SRT_ATR_DEPRECATED;
      | ^ ~~~~~~~~~
make: *** [ffbuild / common.mak: 67: libavformat / libsrt.o] Error 1

-------------------------------------------------- -----------------

**Comment by ethouris** [comment]
The version you are trying to compile hasn't been updated after some symbols have been deprecated. Now these deprecated symbols have been removed. AFAIR there was a ticket about that raised against ffmpeg. You should use the fixed version of ffmpeg (if available), or use SRT release 1.4.1 (v1.4.1 git label).

**Comment by OscarParzon** [comment]
Thank you so much !!

**Comment by OscarParzon** [comment]
> The version you are trying to compile hasn't been updated after some symbols have been deprecated. Now these deprecated symbols have been removed. AFAIR there was a ticket about that raised against ffmpeg. You should use the fixed version of ffmpeg (if available), or use SRT release 1.4.1 (v1.4.1 git label).

**Comment by OscarParzon** [comment]
> The version you are trying to compile hasn't been updated after some symbols have been deprecated. Now these deprecated symbols have been removed. AFAIR there was a ticket about that raised against ffmpeg. You should use the fixed version of ffmpeg (if available), or use SRT release 1.4.1 (v1.4.1 git label).

thanks for your help.
I think I did not understand something.
ffmpeg versions tested:

ffmpeg-4.3.1
ffmpeg-4.2.4
ffmpeg-4.2.3

same mistake.

SRT version in use: v1.41.1

so ?. I did not understand something. maybe it's my worst english!

**Comment by OscarParzon** [comment]
even without solution. the same error in all versions.

**Comment by ethouris** [comment]
What do you mean by "same mistake"?

Your report concerns errors reported for nonexistent symbols: SRTO_STRICTENC and SRTO_SMOOTHER. I checked the srt.h file in the version from v1.4.1 label and it does contain these symbols. How can then compiler report it?

**Comment by OscarParzon** [comment]
Mr.
I apologize for my ignorance. I can't find a solution.
I just want to compile FFmpeg with SRT.
It seemed very simple to me:
Download SRT version and Compile.
Download version of FFmpeg and Compile with SRT.
But I find the error described in my first post.

I am looking for information about my mistake and cannot find it. So I must think that the error only happens to me. I make a mistake and I don't know where.

You, in your first response, tell me:
"You should use the fixed version of ffmpeg (if available), or use SRT release 1.4.1"
Okay, but I change the versions of FFmpeg and confirm that I am using SRT 1.4.1 and the error continues.

In your last comment you send me to check srt.h, and look for "SRTO_STRICTENC", Ok, it is on line 280, and the comment doesn't help me (SRTO_SMOOTHER is not there). I keep checking, but I am thinking that my bad English does not allow me to understand it.

I am thinking that maybe I have an error in my commands to compile FFmpeg with SRT and I add another question to my doubts:
If another interested person wants to compile FFmpeg with SRT, will she have the same problem that I have?

I very much appreciate any help to get out of my error when trying to compile FFmpeg with SRT, something I thought was very simple.

**Comment by OscarParzon** [comment]
Hello !.

Regarding the compilation error:
It seems that there is a change in the last SRT code that does not let make compile the last FFmpeg code.

While FFmpeg and / or SRT fix it:
In a clean install of "Ubuntu 20.04.1 LTS" (basic install).
Download and Compile SRT 1.4.0
Download FFmpeg 4.2.2 and run the following command:
----------------
PATH="$HOME/bin:$PATH" PKG_CONFIG_PATH="$HOME/ffmpeg_build/lib/pkgconfig" ./configure --prefix=/usr \
            --enable-gpl         \
            --enable-version3    \
            --enable-nonfree     \
            --disable-static     \
            --enable-shared      \
            --disable-debug      \
            --enable-avresample  \
            --enable-libfdk-aac  \
            --enable-libfreetype \
            --enable-libx264     \
            --enable-libx265     \
            --enable-protocol=libsrt \
            --enable-libsrt
----------------
... and compile without errors.

In my case it allows me to do some Tx SRT testing with FFmpeg.

It was not very difficult to explain it this way.

I guess my solution will be heavily criticized by people who really know. They may even say that it is not a solution and perhaps you are right. But for me it works.

Thank you very much for the help.

**Comment by ethouris** [comment]
Solution: not a problem. Closing.

**Comment by OscarParzon** [comment]
and here I am again, today November 5 of the year of the pandemic and my error in the make of ffmpeg with srt, everything remains the same ...

The truth is, I feel very bad, obviously my ignorance makes me commit the same sacrilege: I download and compile srt 1.4.0 and ffmpeg 4.2.2

I am left thinking that maybe I do not belong to the "group", I am not "part of the brotherhood". No !, the truth must be that "The old wolverines are still intolerant."

Many ... but Many, many thanks for the help ...
