### ISSUE TITLE
[core][BUG] Group connection errors are reported misleadingly

### ISSUE THREAD

**Issue by ethouris** [Haivision/srt#1415]
The group connections, regardless if made through `srt_connect_group` or `srt_connect`, do not report properly connection errors for individual sockets, this way making the connection errors impossible to properly report.

The problem is that all of the calls resolve to `CUDTUnited::groupConnect` that potentially can make multiple connections at once, each one being potentially able to fail by different reason.

There is also the matter of the stage of errors: some errors appear at the preparation stage, in which case for a single socket they are reported immediately, and the runtime stage, in case when the preparation succeeded and the process continues in background, where it may only be reported through the error event on epoll.

A method of recording the socket connection failure should be provided somehow with a possibility to report it through an array, and it is also desired that the error for one socket failure is available somehow, including rejection reason.

**Comment by ethouris** [comment]
The #1456 fixes the problem of transferring the error information into the call when `srt_connect` is used to just make a single in-group connection. This concerns however only the part when the initial errors are reported for an asynchronous mode. Although this also makes it possible to report also late errors if you use synchronous mode, this gives the application using synchronous mode only a possibility to get the full error information at a cost of possibly waiting up to timeout with one of the group connection before attempting to make another one, which isn't too comfortable.

Another proposal to fix the problem of asynchronous failures - including the case when you use synchronous call of `srt_connect_group` and you have a "partial success" - is in #1464.

**Comment by maxsharabayko** [comment]
Resolved in #1456
