### ISSUE TITLE
Documentation error in bonding-intro code example

### ISSUE THREAD

**Issue by jeandube** [Haivision/srt#1462]
Minor documentation error in docs/bonding-intro.md:

```
srt_sendmsg2(conngrp, packetdata.data(), packetdata.size(), &mc);
for (int i = 0; i < 3; ++i)
    if (mc.grpdata[i].status == SRTS_BROKEN)
        ReestablishConnection(mc.grpdata[i].id);
```

`.status` above shall be `.sockstate`

I am stashing my workspace an report it now.

**Comment by ethouris** [comment]
Right. The field was renamed together with introduction of `memberstate` field.
