### ISSUE TITLE
[FR] Add a callback function for connection resolution readiness

### ISSUE THREAD

**Issue by ethouris** [Haivision/srt#1464]
Idea: add a function that would register a callback to be called at the moment when the connection process is resolved.

This registered function will be called at the moment when an asynchronous connection becomes either established or certainly failed. Note that this function shall not be called in case when you use synchronous connection because the process result is then obtained exactly at the moment when the connecting function exits - but only if this is called for a single socket. When you use a synchronous call for a group using `srt_connect_group` - which returns upon the first successful connection and continues the others in background - should still call this callback for every member socket.

This should help in the following situations:

1. When a group member connection fails. There's currently no way at all to determine that an asynchronous connection has failed - it may at best lead to a broken group connection, or it will simply turn out that not all member connections that the application has requested are in the list of the member connections. This callback would be then the only way for an application to determine as to why particular member connection could have failed.

2. When a connection is established, including for a single socket. Even though this thing can be as well determined by the epoll flag or socket state by polling, it might be more comfortable in certain situations. For example, if you want to connect the socket to read from it later, beside setting `SRTO_RCVSYN` you have to subscribe it to epoll with only +[WE] and after you determine [W] readiness on it, you have to resubscribe it with -[W] and +[R]. By using this callback you can simply avoid subscribing this socket in epoll at all and rely on readiness reported by this callback, and only then subscribe it to +[RE], which may simplify the design of the applications using fibre-based socket switching.

How it should work: the callback function should be called:

1. When the async connection is established and the socket becomes ready for transmission. The socket and the value stating that it succeeded should be passed - likely `SRT_SUCCESS`.

2. When the async connection has failed and the socket may only be available to extract information at this last time. In case when this is a single socket, it will be still available outside the callback-called function, but if it is a member of a managed group, this is the last moment when a user may retrieve any error information from it. In this case the error code should be passed as argument, but the user might want to get extra information, such as for example the reject reason, or the extended reject reason from the StreamID field (see #1170 proposal).

**Comment by maxsharabayko** [comment]
**Motivation:** There is no way of getting notification of a failed call in non-blocking mode.
