### ISSUE TITLE
[FR]absolute unix timestamp in CSV

### ISSUE THREAD

**Issue by alatteri** [Haivision/srt#1488]
**Is your feature request related to a problem? Please describe.**
Trying to use srt-transmit-live CSV data for Grafana logging.  But the timestamp is relative to the start of the app.  This doesn't work.  Need an absolute unix timestamp.
**Describe the solution you'd like**
flag to enable absolute unix timestamp instead of relative time.
**Describe alternatives you've considered**
Not sure any other way to correlate srt-live-transmit csv with absolute time other than native timestamp.
**Additional context**

**Comment by maxsharabayko** [comment]
Duplicates #1218. Please post your comments and subscribe to updates there.
