### ISSUE TITLE
[BUG]CUDTUnited::updateListenerMux returns ipv6 CMultiplexer for ipv4 connection

### ISSUE THREAD

**Issue by rexvl** [Haivision/srt#1499]
1)bind ipv4 listening srt socket to 127.0.0.1 port 9999;
2)bind ipv6 listening srt socket to ::1 port 9999;
3)connect over ipv4 to 127.0.0.1 port 9999;
4)on accept connection, CUDTUnited::updateListenerMux retuns ipv6 CMultiplexer for ipv4 connection.

CUDTUnited::newConnection allocates ns->m_pSelfAddr for ipv4 as followng:
ns->m_pSelfAddr = (sockaddr*)(new sockaddr_in);
but CUDTUnited::updateListenerMux binds it to ipv6 send queue and channel.
Then getSockAddr treats m_pSelfAddr as ipv6 sockaddr_in6 buffer and writes out of allocated buffer:
ns->m_pUDT->m_pSndQueue->m_pChannel->getSockAddr(ns->m_pSelfAddr);
It caused undefined beahvior.

1)add attache test_muxer.cpp from [test_muxer.zip](https://github.com/Haivision/srt/files/5127139/test_muxer.zip) to srt/test folder;
2)add test_muxer.cpp file into filelist.maf;
3)configure --enable-unittests --enable-debug
4)make
5)./test-srt --gtest_filter=Muxer.*

CUDTUnited::updateListenerMux only checks the port on CMultiplexer finding.  Will be better to check ip version too.

**Comment by ethouris** [comment]
There's no such phrase as `m_pSelfAddr` in the current latest master branch. Please check it again in the latest version.

**Comment by rexvl** [comment]
The issue have been reproduced on latest rev 3ad4518b54792a72e0ecf1d70184e9428d849b8a

test@ibase-linux2:~/srt$ ./test-srt --gtest_filter=Muxer.*
Running main() from /home/test/srt/googletest/googletest-src/googletest/src/gtest_main.cc
Note: Google Test filter = Muxer.*
[==========] Running 2 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 2 tests from Muxer
[ RUN      ] Muxer.ipv4_only
[       OK ] Muxer.ipv4_only (143 ms)
[ RUN      ] Muxer.ipv4_with_ipv6
18:51:51.629937/test-srt*E:SRT.mg: HS VERSION=5 but no handshake extension found!
/home/test/srt/test/test_muxer.cpp:32: Failure
Expected: (srt_connect(m_client_sock, psa, sizeof sa)) != (SRT_ERROR), actual: -1 vs -1
/home/test/srt/test/test_muxer.cpp:269: Failure
Expected equality of these values:
  srt_recvmsg(m_sock, buffer, sizeof buffer)
    Which is: -1
  1316
terminate called without an active exception
Aborted (core dumped)

**Comment by ethouris** [comment]
Wow. Could you please share this test? You can do it also through a PR - it will be worth having it.

**Comment by rexvl** [comment]
it is available from this url:
https://github.com/Haivision/srt/files/5127139/test_muxer.zip

**Comment by ethouris** [comment]
Oh sorry, missed that. Thanks a lot!

**Comment by maxsharabayko** [comment]
Hi @rexvl 
Thank you for your contribution!
Could you share your public GitHub e-mail to put you as a co-author of the related fixes?
You can find it in [Setting -> Emails](https://github.com/settings/emails) under "Keep my email addresses private". The format is `*@users.noreply.github.com`. Or you actual email if you are fine disclosing it.

**Comment by rexvl** [comment]
Hi @maxsharabayko 
I've added my email anton.korovin@gmail.com as public.
