### ISSUE TITLE
TL Packet Drop detection

### ISSUE THREAD

**Issue by kavyarav** [Haivision/srt#1502]
Hi,
Is there a way to detect the SRT socket is dropping packets when the TLPKTDROP is set to true and the packet has exceeded 
SRTO_SNDDROPDELAY time? I am trying to record situations when this happens during video transmissions.
Thanks!

**Comment by ethouris** [comment]
There is a method to do that. If you call `srt_recvmsg2` function to receive the packet. This function requires `SRT_MSGCTRL` argument and it fills it with some extra data. One of the fields is `pktseq`, which is the packet's sequence number. You can simply remember the previous value from the previous call and check if the next value is the previous + 1. Just mind that these are circular numbers, so if you get 0 value from this field, then the previous value should be the value of `CSeqNo::m_iMaxSeqNo`, that is, 0x7FFFFFFF.

**Comment by maxsharabayko** [comment]
The `srt_recvmsg2` is a way to see if the receiver has dropped too late packets.
On the sending side, the  [pktSndDropTotal](https://github.com/Haivision/srt/blob/master/docs/statistics.md#pktSndDropTotal) statistics of the SRT socket can be used.

**Comment by kavyarav** [comment]
thanks that helps.
