### ISSUE TITLE
[BUG]reuse addr issue

### ISSUE THREAD

**Issue by rexvl** [Haivision/srt#1503]
Libsrt doesn't check socket address on socket reuse. It only checks if ports are equals.

1)bind listening srt socket to 127.0.0.1:5000;
2)connect to 127.0.0.1:5000, it is ok;
3)close listening socket;
4)bind new listening srt socket to 127.0.0.2:5000;
5)connect to 127.0.0.2:5000 - it is failed due to addr reuse issue;
6)connect to 127.0.0.1:5000 - it is still available;

New listening socket should binded to 127.0.0.2, not to 127.0.0.1.

I attached unit test that reproduced the issue:
https://github.com/Haivision/srt/files/5140196/test_reuseaddr.zip

It might be have the same cause as reported in https://github.com/Haivision/srt/issues/1499

**Comment by ethouris** [comment]
#1588 Should fix that.
BLOCKED DUE TO: Solving the problem of failing IPv6 tests on platforms where it's not supported.
