### ISSUE TITLE
How to generate SYN cookie?

### ISSUE THREAD

**Issue by nikesaw** [Haivision/srt#1511]
Hello. I'm working on SRT server in Erlang. And I have a problem with cookies - there is no clear information in the Technical overview: "SYN Cookie: a cookie that is crafted based on host, port and current time with 1 minute accuracy". How to combine host,port and time for scrambling by MD5? And also, md5 is a 128bit checksum, but the cookie position is only 32-bits. 
I tested a random-generated cookie with Larix app srt client - it ignores my handshake replies..
Thanks in advance!

**Comment by maxsharabayko** [comment]
Hi @nikesaw 
The cookie is baked [here](https://github.com/Haivision/srt/blob/master/srtcore/core.cpp#L10162).
There is indeed no clear description of the procedure in the Technical Overview. There is ongoing work in [SRT-RFC](https://github.com/Haivision/srt-rfc) on that topic as well.

**Comment by nikesaw** [comment]
@maxsharabayko Thank you so much, I reproduced the algorithm. Maybe it'll be useful for somebody not good at C++:

**Comment by nikesaw** [comment]
@maxsharabayko Thank you so much, I reproduced the algorithm - it's just first big-endian 4 bytes of md5("ClientIP:ClientPort:MinutesFromStart"). As the session with Larix is still does not work, therefore an additional question about Destination Socket ID (in the main UDT header) - is it generated randomly or not?

**Comment by ethouris** [comment]
The **initial** value for the socket ID in the application is generated randomly, then the next socket gets this value decreased by 1. See `CUDTUnited::generateSocketID` (in api.cpp) for details. Mind also that now that the groups are introduced, the socket ID rolls over, but the bit designated as `SRTGROUP_MASK` is excluded from this operation. This bit is set only if the ID designates a group and clear if it designates a socket.

**Comment by nikesaw** [comment]
Thank you @ethouris . Now I create Destination SocketID randomly with cleared (1 << 30) bit to initialize a socket session.
But my srt session handshakes are still ignored... 

I use Larix client app iOS + WMS Panel. It works and I try to reproduce a session with my server. The cookie-baking algorithm is the same.

I share a Wireshark dump:
1) A message from Larix app:
```
Frame 108: 106 bytes on wire (848 bits), 106 bytes captured (848 bits) on interface 0
Ethernet II, Src: Apple_b5:9e:39 (c4:98:80:b5:9e:39), Dst: IntelCor_58:d6:62 (48:a4:72:58:d6:62)
Internet Protocol Version 4, Src: 192.168.0.102, Dst: 192.168.0.152
User Datagram Protocol, Src Port: 60093, Dst Port: 14125
UDT Protocol
    1... .... .... .... .... .... .... .... = Type: CONTROL (1)
    .000 0000 0000 0000 .... .... .... .... = Type: handshake (0x0000)
    Additional Info: 0
    Timestamp: 261
    ID: 0x00000000
    Version: 4
    Type: DGRAM (2)
    Initial Sequence Number: 604197535 
    MTU: 1500
    Flow Window: 8192
    Requested Type: 1
    ID: 600338941
    SYN Cookie: 0x00000000
    Peer IP Address: 9800a8c0000000000000000000000000
```
2) My Reply (I "suggest" to use HSv5):
```
Frame 109: 106 bytes on wire (848 bits), 106 bytes captured (848 bits) on interface 0
Ethernet II, Src: IntelCor_58:d6:62 (48:a4:72:58:d6:62), Dst: Apple_b5:9e:39 (c4:98:80:b5:9e:39)
Internet Protocol Version 4, Src: 192.168.0.152, Dst: 192.168.0.102
User Datagram Protocol, Src Port: 14125, Dst Port: 60093
UDT Protocol
    1... .... .... .... .... .... .... .... = Type: CONTROL (1)
    .000 0000 0000 0000 .... .... .... .... = Type: handshake (0x0000)
    Additional Info: 0
    Timestamp: 40000000 // 40 seconds from start => 0 minutes
    ID: 0x23c873ff // random generated with (1 << 30) bit == 0
    Version: 5
    Type: Unknown (18967) // unknown for Wireshark, but SRT MAGIC VALUE for HSv5 0x00004a17
    Initial Sequence Number: 604197535
    MTU: 1500
    Flow Window: 8192
    Requested Type: 1
    ID: 600338941
    SYN Cookie: 0xdb9e8d4d // md5("192.168.0.102:60093:0") = 0x4d8d9edb23b218400c639e1e7c457135 => cookie = 0xdb9e8d4d
    Peer IP Address: 9800a8c0000000000000000000000000

```

3) Larix ignores and tries to connect again...
```
Frame 134: 106 bytes on wire (848 bits), 106 bytes captured (848 bits) on interface 0
Ethernet II, Src: Apple_b5:9e:39 (c4:98:80:b5:9e:39), Dst: IntelCor_58:d6:62 (48:a4:72:58:d6:62)
Internet Protocol Version 4, Src: 192.168.0.102, Dst: 192.168.0.152
User Datagram Protocol, Src Port: 60093, Dst Port: 14125
UDT Protocol
    1... .... .... .... .... .... .... .... = Type: CONTROL (1)
    .000 0000 0000 0000 .... .... .... .... = Type: handshake (0x0000)
    Additional Info: 0
    Timestamp: 1005372
    ID: 0x00000000
    Version: 4
    Type: DGRAM (2)
    Initial Sequence Number: 604197535
    MTU: 1500
    Flow Window: 8192
    Requested Type: 1
    ID: 600338941
    SYN Cookie: 0x00000000
    Peer IP Address: 9800a8c0000000000000000000000000
```

What's wrong? Please help me to find out my misunderstanding...

**Comment by maxsharabayko** [comment]
You should not generate the destination socket ID. You should only generate the source socket ID. The destination socket ID should be taken from the source socket ID of the incoming handshake. The listener generates its source socket ID only on the conclusion phase of the handshake.
The corresponding RFC section is in WIP.

**Comment by ethouris** [comment]
Oh, so that's worse. If you specify the target socket ID in the caller's first handshake, it won't treat it as the connection request.

**Comment by nikesaw** [comment]
@maxsharabayko @ethouris Now it works! Thank you!!!
