### ISSUE TITLE
Tr101 290 error occurred at 3 am

### ISSUE THREAD

**Issue by Morgan0328** [Haivision/srt#1512]
Hi , I meet a problem when i use srt-live-transmit.exe. 

My cmd : 
srt-live-transmit.exe srt://:5201?adapter=192.168.0.171 udp://227.7.7.7:9999?adapter=192.168.0.171 

The Tr 101 290 error occurred at 3 am every day , i try to change the srt source and computer , but it still happen.

How can i solve my problem? Thanks!!

![1](https://user-images.githubusercontent.com/68948580/91790357-2242f980-ec43-11ea-9827-736f7c47f3c0.PNG)

**Comment by maxsharabayko** [comment]
Hi @Morgan0328 
Try the steady clock build of SRT.
I see you have Windows. Build SRT with `-DENABLE_STDCXX_SYNC=ON` CMake build option.

**Comment by Morgan0328** [comment]
> Hi @Morgan0328
> Try the steady clock build of SRT.
> I see you have Windows. Build SRT with `-DENABLE_STDCXX_SYNC=ON` CMake build option.
> 
> You can also disable Drift Tracer in this case, with URI option `drifttracer=off`, e.g. `srt://:4202?drifttracer=off&otheroption=1&...`.

 It seems to be my network problem, i change the network and the problem problem has been solved  , thank you

**Comment by maxsharabayko** [comment]
> It seems to be my network problem, i change the network and the problem has been solved , thank you

Ok, thanks for reporting back!
