### ISSUE TITLE
Bandwidth vs receiving rate

### ISSUE THREAD

**Issue by kmudide** [Haivision/srt#154]
In stats, what is bandwidth, which is next to RTT, and Receiving rate. I see receiving rate is around 8Mbps and bandwidth is around 10Mbps.

Thanks,

**Comment by ethouris** [comment]
They refer to more-less the same source of data, just calculated differently. Mind that the bandwidth measurement is used also internally by SRT for bandwidth limitation.

To understand the bandwidth calculation in detail, the best way is to get the version 1.3.0 currently in the `dev` branch, and open the `srtcore/window.h` file. The `probe2Arrival()` function shows how the value is being picked up and stored into the statistical table. Then `getBandwidth_in` (in `window.cpp`) can show you how the value is finally calculated.

The value for receiving and sending rate is calculated simple way on the fly - for every packet there's taken a time that it took to send or receive it, divided by the number of bytes send by the packet, converted to mbps unit. Note that this is calculating how many bytes of the given payload have been transferred in time, whereas bandwidth calculates the speed based on whole MTU, as this is exactly what maps to system measurements of the bandwidth.

**Comment by kmudide** [comment]
Thanks again.

**Comment by kmudide** [comment]
We are sending around 8 mbps movie stream (pay load), but I see that SRT is using up to little less than 20 mbps and moreover there are no lost packets transmitted. I am printing stats for every 1000 packets

My RTT is 70ms and latency is 300ms, which little over 4 * RTT as recommended by the 
SRT_Alliance_Deployement doc.

Does SRT need this much overhead?

======= SRT STATS: sid=1036214041
PACKETS SENT: 0 RECEIVED: 973294
LOST PKT SENT: 0 RECEIVED: 0
REXMIT SENT: 0 RECEIVED: 71863
**RATE SENDING: 0 RECEIVING: 7.92921**
BELATED RECEIVED: 0 AVG TIME: 0
REORDER DISTANCE: 0
WINDOW: FLOW: 8192 CONGESTION: 8192 FLIGHT: 0
**RTT: 70.163ms  BANDWIDTH: 10.908Mb/s**
BUFFERLEFT: SND: 12288000 RCV: 11860500
======= SRT STATS: sid=1036214041
PACKETS SENT: 0 RECEIVED: 974213
LOST PKT SENT: 0 RECEIVED: 0
REXMIT SENT: 0 RECEIVED: 71863
**RATE SENDING: 0 RECEIVING: 7.92905**
BELATED RECEIVED: 0 AVG TIME: 0
REORDER DISTANCE: 0
WINDOW: FLOW: 8192 CONGESTION: 8192 FLIGHT: 0
**RTT: 70.177ms  BANDWIDTH: 9.324Mb/s**
BUFFERLEFT: SND: 12288000 RCV: 11977500
======= SRT STATS: sid=1036214041
PACKETS SENT: 0 RECEIVED: 975250
LOST PKT SENT: 0 RECEIVED: 0
REXMIT SENT: 0 RECEIVED: 71863
**RATE SENDING: 0 RECEIVING: 7.929**
BELATED RECEIVED: 0 AVG TIME: 0
REORDER DISTANCE: 0
WINDOW: FLOW: 8192 CONGESTION: 8192 FLIGHT: 0
**RTT: 70.173ms  BANDWIDTH: 12.66Mb/s**
BUFFERLEFT: SND: 12288000 RCV: 11910000
======= SRT STATS: sid=1036214041
PACKETS SENT: 0 RECEIVED: 976237
LOST PKT SENT: 0 RECEIVED: 0
REXMIT SENT: 0 RECEIVED: 71864
**RATE SENDING: 0 RECEIVING: 7.92969**
BELATED RECEIVED: 0 AVG TIME: 0
REORDER DISTANCE: 0
WINDOW: FLOW: 8192 CONGESTION: 8192 FLIGHT: 0
**RTT: 70.197ms  BANDWIDTH: 19.872Mb/s**
BUFFERLEFT: SND: 12288000 RCV: 11932500
======= SRT STATS: sid=1036214041
PACKETS SENT: 0 RECEIVED: 977220
LOST PKT SENT: 0 RECEIVED: 0
REXMIT SENT: 0 RECEIVED: 71864
**RATE SENDING: 0 RECEIVING: 7.92993**
BELATED RECEIVED: 0 AVG TIME: 0
REORDER DISTANCE: 0
WINDOW: FLOW: 8192 CONGESTION: 8192 FLIGHT: 0
**RTT: 70.189ms  BANDWIDTH: 19.38Mb/s**
BUFFERLEFT: SND: 12288000 RCV: 11967000
======= SRT STATS: sid=1036214041
PACKETS SENT: 0 RECEIVED: 978235
LOST PKT SENT: 0 RECEIVED: 0
REXMIT SENT: 0 RECEIVED: 71864
**RATE SENDING: 0 RECEIVING: 7.93013**
BELATED RECEIVED: 0 AVG TIME: 0
REORDER DISTANCE: 0
WINDOW: FLOW: 8192 CONGESTION: 8192 FLIGHT: 0
**RTT: 70.197ms  BANDWIDTH: 9.636Mb/s**
BUFFERLEFT: SND: 12288000 RCV: 11940000
======= SRT STATS: sid=1036214041
PACKETS SENT: 0 RECEIVED: 979235
LOST PKT SENT: 0 RECEIVED: 0
REXMIT SENT: 0 RECEIVED: 71865
**RATE SENDING: 0 RECEIVING: 7.9303**
BELATED RECEIVED: 0 AVG TIME: 0
REORDER DISTANCE: 0
WINDOW: FLOW: 8192 CONGESTION: 8192 FLIGHT: 0
**RTT: 70.189ms  BANDWIDTH: 10.596Mb/s**
BUFFERLEFT: SND: 12288000 RCV: 11937000
======= SRT STATS: sid=1036214041
PACKETS SENT: 0 RECEIVED: 980233
LOST PKT SENT: 0 RECEIVED: 0
REXMIT SENT: 0 RECEIVED: 71865
**RATE SENDING: 0 RECEIVING: 7.93065**
BELATED RECEIVED: 0 AVG TIME: 0
REORDER DISTANCE: 0
WINDOW: FLOW: 8192 CONGESTION: 8192 FLIGHT: 0
**RTT: 70.183ms  BANDWIDTH: 13.992Mb/s**
BUFFERLEFT: SND: 12288000 RCV: 11947500
======= SRT STATS: sid=1036214041
PACKETS SENT: 0 RECEIVED: 981189
LOST PKT SENT: 0 RECEIVED: 0
REXMIT SENT: 0 RECEIVED: 71865
**RATE SENDING: 0 RECEIVING: 7.93074**
BELATED RECEIVED: 0 AVG TIME: 0
REORDER DISTANCE: 0
WINDOW: FLOW: 8192 CONGESTION: 8192 FLIGHT: 0
**RTT: 70.189ms  BANDWIDTH: 11.832Mb/s**
BUFFERLEFT: SND: 12288000 RCV: 12015000
======= SRT STATS: sid=1036214041
PACKETS SENT: 0 RECEIVED: 982241
LOST PKT SENT: 0 RECEIVED: 0
REXMIT SENT: 0 RECEIVED: 71866
**RATE SENDING: 0 RECEIVING: 7.93124**
BELATED RECEIVED: 0 AVG TIME: 0
REORDER DISTANCE: 0
WINDOW: FLOW: 8192 CONGESTION: 8192 FLIGHT: 0
**RTT: 70.192ms  BANDWIDTH: 13.416Mb/s**
BUFFERLEFT: SND: 12288000 RCV: 11935500

**Comment by ethouris** [comment]
We have researched it a little bit and it looks like there's something very unusual here.

Would you be able to perform a short session with `-loglevel:debug` on both sides? Just remember to redirect stderr to a file, otherwise the logs may highly influence the timing.

(The best option would be to compile in release mode, but with logging - use `ENABLE_LOGGING=1` only).

**Comment by kmudide** [comment]
I will probably by Monday. Thanks.
