### ISSUE TITLE
FFMPEG streamid usage

### ISSUE THREAD

**Issue by NickolayGerasimenko** [Haivision/srt#1540]
Hi I'm trying to set/get streamId using ffmpeg like so:

Caller:
`./ffmpeg -re -i /dev/video0 -c:v libx264 -streamid "--------------- bla bla" -f mpegts srt://127.0.0.1:1234?pkt_size=1316`

Listener:
`./ffmpeg -re -i srt://127.0.0.1:1234?mode=listener -map 0:v -vcodec copy out.h264`

I faced two issues:
1. SRT Option name 'streamid' interferes with another FFMPEG option streamid = 'k:v', which has totally different input range.
To handle this I renamed SRT streamid option like 'srt_streamid', now command looks like(name of the variable which hold actually value of this option I did't touch):

`./ffmpeg -re -i /dev/video0 -c:v libx264 -crt_streamid "--------------- bla bla" -f mpegts srt://127.0.0.1:1234?pkt_size=1316`

2. How I can print value of SRT streamid on listener side? default FFMPEG output doesn't print this field.

Thanks!

**Comment by Llorx** [comment]
The SRTO_STREAMID parameter you set on one side with setSockOpt, you can read it on the other side with getSockOpt. It is "copied" during the handshake.

**Comment by ethouris** [comment]
In particular, you can set this parameter at the caller side and retrieve it at the listener side.

**Comment by NickolayGerasimenko** [comment]
> The SRTO_STREAMID parameter you set on one side with setSockOpt, you can read it on the other side with getSockOpt. It is "copied" during the handshake.

Am I rightly understood that there is no way to set it via CLI of FFMPEG? As I mentioned in my question.

**Comment by NickolayGerasimenko** [comment]
> In particular, you can set this parameter at the caller side and retrieve it at the listener side.

How? Can you show example usage?

**Comment by ethouris** [comment]
I don't know how to do it in ffmpeg, I don't know the details of the implementation. I'm talking about the SRT socket option designated as `SRTO_STREAMID`.

**Comment by maxsharabayko** [comment]
FFMpeg Patch "[Support new SRT streamid specification](https://patchwork.ffmpeg.org/project/ffmpeg/patch/CAK8GPyDFV1oyggGaNtvA3zCDExeWKYEh-Tnva16EW71Hr1+OiA@mail.gmail.com/)" adds `user_passphrase_list` SRT URI option to provide a list of per-user passphrases.
```
user_passphrase_list=usrr1=pass1,usr2=pass2,...
```
The patch also adds a listener callback to parse the StreamID in the YAML format described in the [Access Control Guidelines](https://github.com/Haivision/srt/blob/master/docs/AccessControl.md). Only the comma-separated keys without nesting (`#!::`).

**Comment by mbakholdina** [comment]
Hi @J-Rogmann,
Could you please extend the [CookBook FFMpeg article](https://srtlab.github.io/srt-cookbook/apps/ffmpeg/) with StreamID use case? 

@NickolayGerasimenko, or maybe you have time for this? We would appreciate a PR a lot. Please let us know.

The project is located [here](https://github.com/SRTLab/srt-cookbook). The file to update is [here](https://github.com/SRTLab/srt-cookbook/blob/master/docs/apps/ffmpeg.md).

**Comment by mbakholdina** [comment]
Closing the ticket due to inactivity. Feel free to reopen in case of further questions.
