### ISSUE TITLE
Data Races Reported by the Clang Thread Sanitizer

### ISSUE THREAD

**Issue by jlsantiago0** [Haivision/srt#1547]
[test002.log](https://github.com/Haivision/srt/files/5219593/test002.log)
[test-tsan-20201014-01.log](https://github.com/Haivision/srt/files/5379920/test-tsan-20201014-01.log)

**Describe the bug**

Large number of data races are reported by the Clang Thread Sanitizer.

**To Reproduce**
Build with Clang and/or GCC with tsan.

**Expected behavior**
There should be no data races reported by the sanitizer.

**Screenshots**
None

**Desktop (please provide the following information):**
 - OS: Linux x86_64
 - SRT v1.4.1

**Additional context**
None

**Comment by jlsantiago0** [comment]
Log from the sanitizer.

[test002.log](https://github.com/Haivision/srt/files/5219597/test002.log)

**Comment by jlsantiago0** [comment]
I added an update TSAN log from the latest master branch as of 20201014.

**Comment by ethouris** [comment]
SRT went large changes since then, including fixes for data races, so the report is largely outdated. @jlsantiago0 would you be able to repeat it with the latest version?

**Comment by jlsantiago0** [comment]
Races curently reported by the sanitizers.

[test-tsan-20210209-01.log](https://github.com/Haivision/srt/files/5953207/test-tsan-20210209-01.log)
[test-tsan-20210209-02.log](https://github.com/Haivision/srt/files/5953209/test-tsan-20210209-02.log)

**Comment by ethouris** [comment]
The work on fixing the sanitizer reported issues continues under #1813.
