### ISSUE TITLE
Initial value of received retransmission packet statistic is wrong

### ISSUE THREAD

**Issue by ethouris** [Haivision/srt#156]
This value should be 0 in the beginning and increase with every packet received as retransmitted. Happens that it carries a >0 value while no packets were retransmitted.

**Comment by ethouris** [comment]
Added a fix in #158

**Comment by lars18th** [comment]
Hi @ethouris ,

This problem persists. Even in the "dev" branch at 2018-01-24:

```
REXMIT SENT: 0 RECEIVED: 32604
```

The value it's initialized to a non-zero value; and it **never** increases. So it's impossible to know which packets are retransmitted.

Please, can you fix it?
Thank you!
