### ISSUE TITLE
No room to store.. & RCV-DROPPED

### ISSUE THREAD

**Issue by PierreIntel** [Haivision/srt#1570]
Hi,

I am trying to encode a flow with ffmpeg and to stream it with the hls protocol. This flow arrive in a srt canal and I need to stream it at 50 fps. With the encoder only, I encode the video at 55 fps so I can stream it in real time.
But at a moment there is the message "No room to store incoming packet..." and sometimes I have the message "RCV-DROPPED packet".

I tried to adjust the sizes of different fifos but this message is always, sometimes directly or after 2h of streaming.

This message is displayed because the target doesn't read the packets fast enough but my encoder is running more than 50 fps.

here is my command line :
 ./ffmpeg -i "srt://:5900&pkt_size=1316&rcvbuf=5000000" -max_muxing_queue_size 1024 -c:a aac -b:a 128000 -c:v libsvtav1 -rc 1 -preset 7 -g 50 -r 50 -b:v 2000000 -hls_list_size 20 -hls_time 1 -hls_flags delete_segments -hls_segment_type fmp4 /usr/share/nginx/html/hls/hls.m3u8

Do you have any ideas of what is causing this ?

Thanks.

**Comment by maxsharabayko** [comment]
Hi @PierreIntel 
What is an approximate bitrate of your streaming?
I see you are setting `rcvbuf=5000000`, which is ~40 Mbits. The default value is ~96Mbits. Please consider increasing it.

You don't set the latency, so the default 120 ms will be used. It means the receiver buffer has to store at least latency * bitrate. Please also note the latency in FFMpeg is configured in microseconds. See [this FFMeg guideline](https://srtlab.github.io/srt-cookbook/apps/ffmpeg/) and [Calculating receiver buffer size](https://github.com/Haivision/srt/issues/703#issuecomment-495570496).

**Comment by PierreIntel** [comment]
Hi, thanks for your answer, the bitrate of my streaming is 2 Mbits.
Ok, so if I decrease the latency, my encoder will begin to encode sooner and it can avoid to excess the receiver buffer ?

**Comment by ethouris** [comment]
Just note that not "for free". The less the latency, the less time given to equalize the network jitter and retransmit possibly lost packets.

This message in general is a result of overflowing the receiver buffer. Whether it's because the buffer is too small to compensate the size of the stream for given bitrate and latency, or because the application doesn't read packets even though it should have read them a long time ago already, is another matter.

**Comment by PierreIntel** [comment]
Ok. Is there a way to detect what is the cause of this ? To see the size of the receiver buffer in real time ?
Thanks.

**Comment by ethouris** [comment]
Currently the only possibility is when you enable heavy logging at compile time. There's a log that shows these values:
```
    LOGC(brlog.Debug,
         log << CONID() << "readMsg: DELIVERED seq=" << seq << " T=" << FormatTime(srctime) << " in " << timediff_ms
             << "ms - TIME-PREVIOUS: PKT: " << srctimediff_ms << " LOCAL: " << nowdiff_ms << " !"
             << BufferStamp(pkt.data(), pkt.size()) << " NEXT pkt T=" << next_playtime);
```

To see it, use `-lf ~all buf-recv -ll debug` in the application (or: loglevel debug and turn on `SRT_LOGFA_BUF_RECV` as the only enabled FA (note that all FA are enabled by default).

**Comment by PierreIntel** [comment]
I have this : 
readMsg: DELIVERED seq=1716555018 T=18530D 11:03:48.483048 [STD] in 0ms - TIME-PREVIOUS: PKT: 0 LOCAL: 0 !2BA7C563 NEXT pkt T=18530D 11:03:48.483051 [STD]'

It append just before the message "No room ...".

How is the size of the rcvbuffer is affected by the options rcvbuf and recv_buffer_size ?
Because the number of packet that I see is always 8192.

Is there a way to drop packets until the application has read a certain number of packet ?

Thanks.

**Comment by ethouris** [comment]
You skipped the time in the log header, while it is important. The time as specified in `T=` is the time when the packet SHOULD be delivered and this time should be confronted with the time from this log header. Still, if there's `in 0ms`, it means that the time of expected delivery is the equal to the current time.

The size of the receiver buffer is specified in bytes, but internally it's expressed in the number of packets of the size of the single packet payload (1456, by the default MSS value 1500). Might be it is too small for your current stream parameters; the receiver buffer in live mode is also used to compensate the latency, that is, packets are given up to the application (the thing reported by the above log) not when it's in the buffer and contiguous, but also when the time to play comes - and that's this time in `T=`. The required size of the buffer that would compensate the latency should be calculated basing on the stream bitrate and latency - it should give you the number of bytes your receiver buffer should keep constantly as a latency buffer. The real buffer size should be safest set as twice that value, just for a case.

**Comment by PierreIntel** [comment]
When the message "No room..." appears the encoder stop receiving data, does that means the buffer is full and there are no packets that can be played ?

**Comment by ethouris** [comment]
Ok, let me explain this mechanism in short.

The receiver buffer should keep packets at positions determined by their sequence number. Loss will result in empty positions. An initial contiguous range of packets should be ready for retrieval.

But in TSBPD mode packets are only allowed retrieval when their play time (relative time in the timestamp + start time + latency) is in the past. If the next packet's play time is in the future, the reading function is blocked up to this time. That is, "future" packets stay in the buffer.

Rest of this mechanism depends on the cooperation with the application - the application should read ready-to-play packets immediately. If it doesn't, the receiver buffer swells, up to overflow in the end.

When the application then reads the packets too slowly, then beside the full receiver buffer, there also grows the sequence distance between the last remaining packet and the incoming packet's sequence. If this distance grows above the size of the receiver buffer, this situation is no longer recoverable and the connection must be emergency-closed.

**Comment by maxsharabayko** [comment]
Hi @PierreIntel 
There is a similar issue #1246.
Log messages were extended in #1282 to help identify the reason for the receiver buffer not having enough space. May be related to #1255.
Please include all log messages you will have starting with "No room to store incoming packet: offset..." in full together with surrounding messages.

Please use #1246 for any further updates on this issue.
