### ISSUE TITLE
SRTO_MINVERSION without effect on group socket

### ISSUE THREAD

**Issue by jeandube** [Haivision/srt#1577]
non-blocking mode caller/sender set `SRTO_MINVERSION` to 0x0001045b (libsrt.so.1.4.91, a previously patched pre-1.5.0 libsrt).
socket was obtained from experimental `srt_create_group()`.
Listening/receiver peer announces version 1.4.2 and connexion succeeds.
Both peers are on libsrt commit  2641221, ( 2 commits behind v1.4.2)

**Comment by ethouris** [comment]
Just checked how it works with a single socket connection. I set `minversion=1.5.5` on the caller and it still succeeds. Looxlike this option has stopped working completely.
