### ISSUE TITLE
Gstreamer: Failed to load plug in 'srt': srt.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by BlueWaterCrystal** [Haivision/srt#1590]
Error:
`GStreamer-WARNING **: 11:53:11.787: Failed to load plugin 'srt': srt.so: cannot open shared object file: No such file or directory
Could not load plugin file: Opening module failed: srt.so: cannot open shared object file: No such file or directory
`

Versions we have tried:

> Gstreamer: 1.15.2 to 1.19.2
> SRT: 1.3.2 to 1.4.2

Everything complies without any errors.
Everything works except SRT.

 libsrt shows up in /usr/local/lib

> Hardware: ARM 64bit
> OS: Ubuntu 18

srt-live-transmit command works fine:

SRT sample application to transmit live streaming.
Built with SRT Library version: 1.4.2
SRT Library version: 1.4.2

        -t, -timeout, -to:<timeout=0>   - exit timer in seconds
        -timeout-mode, -tm:<mode=0>     - timeout mode (0 - since app start; 1 - like 0, but cancel on connect
        -a, -auto, -autoreconnect:<enabled=yes> - auto-reconnect mode {yes, no}
        -c, -chunk:<chunk=1456> - max size of data read in one step, that can fit one SRT packet
        -bandwidth-report, -bitrate-report, -bwreport, -r, -report:<every_n_packets=0>  - bandwidth report frequency
        -sourcetime, -srctime, -st:<enabled=yes>        - Pass packet time from source to SRT output {yes, no}
        -buffering:<packets=n>  - Buffer up to n incoming packets
        -s, -stats, -stats-report-frequency:<every_n_packets=0> - frequency of status report
        -statsout:<filename>    - output stats to file
        -pf, -statspf:<format=default>  - stats printing format {json, csv, default}
        -f, -fullstats  - full counters in stats-report (prints total statistics)
        -ll, -loglevel:<level=error>    - log level {fatal,error,info,note,warning}
        -logfa:<fas>    - log functional area (see '-h logging' for more info)
        -logfile:<filename=>    - write logs to file
        -q, -quiet      - quiet mode (default off)
        -v, -verbose    - verbose mode (default off)

        -h,-help - show this help (use '-h logging' for logging system)
        -version - print SRT library version

        <input-uri>  - URI specifying a medium to read from
        <output-uri> - URI specifying a medium to write to

**Comment by robynjayqueerie** [comment]
I am battling trying to get this to work on a Pi, suspect your issue is that you need to compile gstreamer with the srt option enabled, don't think the basic version has that.
Where did you get your gstreamer from? I have used a compile .sh from https://github.com/PietroAvolio/Building-Gstreamer-Raspberry-Pi-With-SRT-Support but it does not seem to fully work even though it recognises srt to some extent.
I think we have to go back to compiling gstreamer and work out how you do that and enable srt
Regards

**Comment by maxsharabayko** [comment]
Hi. It looks more like an issue building GStreamer with SRT.
I don't think SRT is built or linked by default in GStreamer. Did you manage to resolve this issue?

The following documents might be helpful:
- [Using SRT with GStreamer](https://github.com/Haivision/srt/blob/master/docs/gstreamer.md)
- [GStreamer Bad Plugins](https://gitlab.freedesktop.org/gstreamer/gst-plugins-bad)

**Comment by robynjayqueerie** [comment]
No, not yet. I decided to try linking SRT to ffmpeg instead but it seems there are issues there as well. I have gone farther into it with ffmpeg so that may throw some light on the issue if I resolve it.
It all seems so simple, just recompile the package using the SRT library, but no. 
I have not seen that last link you sent so I will look at that and see what I make of it.
Thanks

**Comment by BlueWaterCrystal** [comment]
I downloaded gstreamer source code from their website and complied with make and meson and still had same result.

I compile SRT and install it and then compile and install gstreamer, I have also tried installing it using `apt-get install` but still no luck

Its worked before but not sure whats changed.

**Comment by maxsharabayko** [comment]
@robynjayqueerie 

> No, not yet. I decided to try linking SRT to ffmpeg instead but it seems there are issues there as well. I have gone farther into it with ffmpeg so that may throw some light on the issue if I resolve it.

Please also note this [FFMpeg guide](https://srtlab.github.io/srt-cookbook/apps/ffmpeg/) then.

@justinjoy Maybe you could help here?

**Comment by justinjoy** [comment]
I don't think there's something special trick to build GStreamer with SRT.
Unless the relevant log is shared, it's hard to find the root cause.

One quick checkpoint is `ldd`.
What result is shown by `ldd  /path/libgstsrt.so`? It will show what dependencies are missing.

@maxsharabayko FYI, GStreamer's build aggregator solves library dependencies by the concept of `subproject` when running configure. However, this issue summons #795 again.

**Comment by BlueWaterCrystal** [comment]
> I don't think there's something special trick to build GStreamer with SRT.
> Unless the relevant log is shared, it's hard to find the root cause.
> 
> One quick checkpoint is `ldd`.
> What result is shown by `ldd /path/libgstsrt.so`? It will show what dependencies are missing.
> 
> @maxsharabayko FYI, GStreamer's build aggregator solves library dependencies by the concept of `subproject` when running configure. However, this issue summons #795 again.

I did the ldd command and it returned this:
`
ubuntu@localhost:~/gst-1.15.2/lib/aarch64-linux-gnu$ ldd libsrt.so
        linux-vdso.so.1 (0x0000007faada2000)
        libcrypto.so.1.1 => /usr/lib/aarch64-linux-gnu/libcrypto.so.1.1 (0x0000007faaa68000)
        libpthread.so.0 => /lib/aarch64-linux-gnu/libpthread.so.0 (0x0000007faaa3c000)
        libstdc++.so.6 => /usr/lib/aarch64-linux-gnu/libstdc++.so.6 (0x0000007faa8a8000)
        libm.so.6 => /lib/aarch64-linux-gnu/libm.so.6 (0x0000007faa7ef000)
        libgcc_s.so.1 => /lib/aarch64-linux-gnu/libgcc_s.so.1 (0x0000007faa7cb000)
        libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000007faa672000)
        /lib/ld-linux-aarch64.so.1 (0x0000007faad76000)
        libdl.so.2 => /lib/aarch64-linux-gnu/libdl.so.2 (0x0000007faa65d000)
`

**Comment by justinjoy** [comment]
> ubuntu@localhost:~/gst-1.15.2/lib/aarch64-linux-gnu$ ldd libsrt.so

unfortunately, the target file is wrong. 
In my previous comment, the filename was `libgstsrt.so` which is a gstreamer SRT plugin that is built by your way.

**Comment by BlueWaterCrystal** [comment]
> libgstsrt

I don't see any file called  `libgstsrt.so`

**Comment by justinjoy** [comment]
> I don't see any file called `libgstsrt.so`

That's the gstreamer plugin. If you install with a prefix, `/usr/local`, you should be able to see the file in `/usr/local/lib/gstreamer-1.0` directory. If not, there might be a mishap when you built gstreamer.

**Comment by BlueWaterCrystal** [comment]
> > ubuntu@localhost:~/gst-1.15.2/lib/aarch64-linux-gnu$ ldd libsrt.so
> 
> unfortunately, the target file is wrong.
> In my previous comment, the filename was `libgstsrt.so` which is a gstreamer SRT plugin that is built by your way.

Is this the correct target file?

`ldd /home/ubuntu/gst-1.15.2/lib/aarch64-linux-gnu/gstreamer-1.0/libgstsrt.so`

```
 /home/ubuntu/gst-1.15.2/lib/aarch64-linux-gnu/gstreamer-1linux-vdso.so.1 (0x0000007f78a98000)
        libgstreamer-1.0.so.0 => /home/ubuntu/gst-1.15.2/lib/aarch64-linux-gnu/libgstreamer-1.0.so.0 (0x0000007f7891b000)
        libgio-2.0.so.0 => /usr/lib/aarch64-linux-gnu/libgio-2.0.so.0 (0x0000007f78779000)
        libgobject-2.0.so.0 => /usr/lib/aarch64-linux-gnu/libgobject-2.0.so.0 (0x0000007f7871b000)
        libglib-2.0.so.0 => /usr/lib/aarch64-linux-gnu/libglib-2.0.so.0 (0x0000007f7860c000)
        libgstbase-1.0.so.0 => /home/ubuntu/gst-1.15.2/lib/aarch64-linux-gnu/libgstbase-1.0.so.0 (0x0000007f78590000)
        libsrt.so.1 => /home/ubuntu/gst-1.15.2/lib/aarch64-linux-gnu/libsrt.so.1 (0x0000007f784e7000)
        libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000007f7838e000)
        /lib/ld-linux-aarch64.so.1 (0x0000007f78a6c000)
        libgmodule-2.0.so.0 => /usr/lib/aarch64-linux-gnu/libgmodule-2.0.so.0 (0x0000007f7837a000)
        libm.so.6 => /lib/aarch64-linux-gnu/libm.so.6 (0x0000007f782c1000)
        libdl.so.2 => /lib/aarch64-linux-gnu/libdl.so.2 (0x0000007f782ac000)
        libpthread.so.0 => /lib/aarch64-linux-gnu/libpthread.so.0 (0x0000007f78280000)
        libz.so.1 => /lib/aarch64-linux-gnu/libz.so.1 (0x0000007f78253000)
        libselinux.so.1 => /lib/aarch64-linux-gnu/libselinux.so.1 (0x0000007f78220000)
        libresolv.so.2 => /lib/aarch64-linux-gnu/libresolv.so.2 (0x0000007f781fb000)
        libmount.so.1 => /lib/aarch64-linux-gnu/libmount.so.1 (0x0000007f7819e000)
        libffi.so.6 => /usr/lib/aarch64-linux-gnu/libffi.so.6 (0x0000007f78186000)
        libpcre.so.3 => /lib/aarch64-linux-gnu/libpcre.so.3 (0x0000007f78114000)
        libcrypto.so.1.1 => /usr/lib/aarch64-linux-gnu/libcrypto.so.1.1 (0x0000007f77ed3000)
        libstdc++.so.6 => /usr/lib/aarch64-linux-gnu/libstdc++.so.6 (0x0000007f77d3f000)
        libgcc_s.so.1 => /lib/aarch64-linux-gnu/libgcc_s.so.1 (0x0000007f77d1b000)
        libblkid.so.1 => /lib/aarch64-linux-gnu/libblkid.so.1 (0x0000007f77cc5000)
        libuuid.so.1 => /lib/aarch64-linux-gnu/libuuid.so.1 (0x0000007f77cae000)
```

**Comment by justinjoy** [comment]
>         libsrt.so.1 => /home/ubuntu/gst-1.15.2/lib/aarch64-linux-gnu/libsrt.so.1 (0x0000007f784e7000)

Your GStreamer plugin linked correctly.
I guess you used `gst-launch-1.0` of your ubuntu package instead of using your built one.

Can you check again the absolute path of the command above?
If you are sure that you used your built executable, more gstreamer log is required to see what happens when loading plugins.

```
GST_REGISTRY=/tmp GST_DEBUG=4 GST_DEBUG_FILE=gstreamer.log /<<your build path>>/gst-inspect-1.0  <<your build path>>/libgstsrt.so
```
The above command will generate `gstreamer.log` file. we can check the details from the log.

**Comment by BlueWaterCrystal** [comment]
> > ```
> >     libsrt.so.1 => /home/ubuntu/gst-1.15.2/lib/aarch64-linux-gnu/libsrt.so.1 (0x0000007f784e7000)
> > ```
> 
> Your GStreamer plugin linked correctly.
> I guess you used `gst-launch-1.0` of your ubuntu package instead of using your built one.
> 
> Can you check again the absolute path of the command above (gst-launch-1.0)?
> If you are sure that you used your built executable, more gstreamer log is required to see what happens when loading plugins.
> 
> ```
> GST_REGISTRY=/tmp GST_DEBUG=4 GST_DEBUG_FILE=gstreamer.log /<<your build path>>/gst-inspect-1.0  <<your build path>>/libgstsrt.so
> ```
> 
> The above command will generate `gstreamer.log` file. we can check the details from the log.

Hey

I found the commands in /usr/bin

environment variables were added during the install.
```
export LD_LIBRARY_PATH=/home/ubuntu/gst-1.15.2/lib/aarch64-linux-gnu
export PATH=/home/ubuntu/gst-1.15.2/bin:$PATH
```



Here's the output:
```
linux-gnu/gstreamer-1.0/libgstsrt.soct-1.0  /home/ubuntu/gst-1.15.2/lib/aarch64-l

(gst-plugin-scanner:8002): GLib-GObject-WARNING **: 12:28:19.845: cannot register existing type 'GstVideoAggregator'

(gst-plugin-scanner:8002): GLib-GObject-CRITICAL **: 12:28:19.846: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed

(gst-plugin-scanner:8002): GLib-CRITICAL **: 12:28:19.846: g_once_init_leave: assertion 'result != 0' failed

(gst-plugin-scanner:8002): GLib-GObject-CRITICAL **: 12:28:19.846: g_type_register_static: assertion 'parent_type > 0' failed

(gst-plugin-scanner:8002): GLib-CRITICAL **: 12:28:19.846: g_once_init_leave: assertion 'result != 0' failed

(gst-plugin-scanner:8002): GStreamer-CRITICAL **: 12:28:19.846: gst_element_register: assertion 'g_type_is_a (type, GST_TYPE_ELEMENT)' failed
Plugin Details:
  Name                     srt
  Description              transfer data via SRT
  Filename                 /home/ubuntu/gst-1.15.2/lib/aarch64-linux-gnu/gstreamer-1.0/libgstsrt.so
  Version                  1.15.2
  License                  LGPL
  Source module            gst-plugins-bad
  Source release date      2019-02-26
  Binary package           GStreamer Bad Plug-ins source release
  Origin URL               Unknown package origin

  srtserversink: SRT sink
  srtclientsink: SRT sink
  srtserversrc: SRT source
  srtclientsrc: SRT source
  srtsink: SRT sink
  srtsrc: SRT source

  6 features:
  +-- 6 elements

```

**Comment by BlueWaterCrystal** [comment]
It is definitely the gstreamer within the ubuntu causing the issues
woudl you know 


```
ubuntu@localhost:~$ /home/ubuntu/gst-1.15.2/bin/gst-inspect-1.0 srt
Plugin Details:
  Name                     srt
  Description              transfer data via SRT
  Filename                 /home/ubuntu/gst-1.15.2/lib/aarch64-linux-gnu/gstreamer-1.0/libgstsrt.so
  Version                  1.15.2
  License                  LGPL
  Source module            gst-plugins-bad
  Source release date      2019-02-26
  Binary package           GStreamer Bad Plug-ins source release
  Origin URL               Unknown package origin

  srtsrc: SRT source
  srtsink: SRT sink
  srtclientsrc: SRT source
  srtserversrc: SRT source
  srtclientsink: SRT sink
  srtserversink: SRT sink

  6 features:
  +-- 6 elements
```







```
ubuntu@localhost:~$ which gst-inspect-1.0
/usr/bin/gst-inspect-1.0
```

```
ubuntu@localhost:~$ gst-inspect-1.0 srt

(gst-inspect-1.0:11125): GStreamer-WARNING **: 21:01:42.671: Failed to load plugin 'srt': srt.so: cannot open shared object file: No such file or directory
Could not load plugin file: Opening module failed: srt.so: cannot open shared object file: No such file or directory
```

**Comment by maxsharabayko** [comment]
Thanks, @BlueWaterCrystal, @justinjoy!
@robynjayqueerie I hope you have also succeeded.
