### ISSUE TITLE
Shared library soname should change iff ABI incompatible

### ISSUE THREAD

**Issue by heftig** [Haivision/srt#1592]
The soname is currently `libsrt.so.1` and has been through several ABI-incompatible releases. E.g. 1.4.2 broke ABI by adding some fields to the `CBytePerfMon` structure. To avoid trouble when a shared libsrt is upgraded, the soname of the library should be bumped to reflect the incompatibility.

I would suggest making the next release 1.5.0 and using the soname `libsrt.so.1.5`, then avoiding breaking ABI in patch releases. If ABI is broken, the minor (or major) version is increased.

**Comment by FedericoCeratto** [comment]
@maxsharabayko ABI breaking changes without soname changes are impact Linux distributions e.g. [1] making srt difficult to ship. Would it be possible to have a 1.5 release as soon as possible? Thanks!

[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=971754

**Comment by maxsharabayko** [comment]
@FedericoCeratto The next planned SRT release is v1.4.3.
If the shared library has `libsrt.so.1.4` or even `libsrt.so.1.4.3`, would that resolve the shipment issue?

**Comment by sdroege** [comment]
You have to increase that 1 there whenever the ABI is changing in incompatible ways. If you're lazy you could simply increase it with every release.

**Comment by heftig** [comment]
If you're willing to take care to avoid ABI changes in patch releases (1.4.4, 1.4.5, etc) I would suggest `.so.1.4` instead of `.so.1.4.3`.

**Comment by maxsharabayko** [comment]
Going forward with `.so.1.4`, `.so.1.5` etc and preserving ABI compatibility in patch versions.
