### ISSUE TITLE
Build SRT for Android on Mac OS

### ISSUE THREAD

**Issue by tobisweb** [Haivision/srt#1595]
Hi SRT-Specialists,

I am trying to build SRT for Android in order to use it in a Flutter-Project. Therefore I used the compilation guide for android *https://github.com/Haivision/srt/tree/master/docs/Android* as a basis and created my own script. I am expecting a *.so file as a result of this build. Unfortunately I receive a weird error message when I run the srt-compile script.

*Has somebody experienced the same issue or knows how to handle this one?*

After successfully running openssl build script I **run this script**: 
`#!/bin/bash
BASE_DIR=/Users/tobisweb/development/my_flutter
ANDROID_API=21
OPENSSL_DIR=BASE_DIR/srt/openssl-$openssl_ver
TOOLCHAIN_DIR=/Users/tobisweb/development/android-ndk-r21d/toolchains/llvm/prebuilt/darwin-x86_64
CMAKE_TOOLCHAIN_FILE=/Users/tobisweb/development/android-ndk-r21d/build/cmake/android.toolchain.cmake
TARGET_HOST=armv7a-linux-androideabi
TARGET_HOST_API=$TOOLCHAIN_DIR/bin/armv7a-linux-androideabi$ANDROID_API

export OPENSSL_ROOT_DIR=/usr/local/Cellar/openssl@1.1
export OPENSSL_ROOT_DIR=/Users/tobisweb/development/srt/openssl-1.1.1c
export PATH=$PATH:$TOOLCHAIN_DIR/bin
export AR=$TARGET_HOST-ar
export AS=$TARGET_HOST-as
export LD=$TARGET_HOST-ld
export STRIP=$TARGET_HOST-strip
export CC=$TARGET_HOST_API-clang
export CXX=$TARGET_HOST_API-clang++
export CFLAGS="-fPIE -fPIC"
export LDFLAGS="-pie"

cd BASE_DIR/srt

./configure --use-openssl-pc=OFF --CMAKE_PREFIX_PATH=$TOOLCHAIN_DIR --CMAKE_INSTALL_PREFIX=$TOOLCHAIN_DIR
#--CMAKE_PREFIX_PATH=$TOOLCHAIN_DIR --CMAKE_INSTALL_PREFIX=$TOOLCHAIN_DIR --ANDROID_PLATFORM=21  --CMAKE_TOOLCHAIN_FILE=$CMAKE_TOOLCHAIN_FILE --CMAKE_SYSTEM_NAME="ANDROID"
make
make install`

and the following **output**:

./build-srt-android.sh                                                
Running: cmake . -DUSE_OPENSSL_PC=OFF -DCMAKE_PREFIX_PATH=/Users/tobisweb/development/android-ndk-r21d/toolchains/llvm/prebuilt/darwin-x86_64 -DCMAKE_INSTALL_PREFIX=/Users/tobisweb/development/android-ndk-r21d/toolchains/llvm/prebuilt/darwin-x86_64 -DOPENSSL_INCLUDE_DIR=/usr/local/opt/openssl/include -DOPENSSL_LIBRARIES=/usr/local/opt/openssl/lib/libcrypto.a
-- The C compiler identification is Clang 9.0.8
-- The CXX compiler identification is Clang 9.0.8
-- Check for working C compiler: /Users/tobisweb/development/android-ndk-r21d/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi21-clang
-- Check for working C compiler: /Users/tobisweb/development/android-ndk-r21d/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi21-clang - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Users/tobisweb/development/android-ndk-r21d/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi21-clang++
-- Check for working CXX compiler: /Users/tobisweb/development/android-ndk-r21d/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi21-clang++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.2") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- BUILD TYPE: Release
-- LOGGING: ENABLED
-- USE_BUSY_WAITING: OFF (default)
-- No WITH_COMPILER_PREFIX - using C++ compiler /Users/tobisweb/development/android-ndk-r21d/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi21-clang++
-- Looking for inet_pton
-- Looking for inet_pton - found
-- Found OpenSSL: /usr/lib/libcrypto.dylib (found version "1.1.1g")  
-- SSL via find_package(OpenSSL): -I /usr/local/opt/openssl/include -l;/usr/lib/libssl.dylib;/usr/lib/libcrypto.dylib
-- ENCRYPTION: ENABLED, using: openssl libcrypto
-- SSL libraries: /usr/lib/libssl.dylib;/usr/lib/libcrypto.dylib
-- COMPILER: Clang (/Users/tobisweb/development/android-ndk-r21d/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi21-clang++) - GNU compat
-- NOTE: CLANG 9.0.8 detected, unsure if >=C++11 is default, forcing C++11 on applications
-- STDCXX_SYNC: OFF
-- C++ STD: Forcing C++11 on applications
-- DETECTED SYSTEM: DARWIN;  OSX=1
-- SRT Sources: /Users/tobisweb/development/my_flutter/srt/srtcore/api.cpp;/Users/tobisweb/development/my_flutter/srt/srtcore/buffer.cpp;/Users/tobisweb/development/my_flutter/srt/srtcore/cache.cpp;/Users/tobisweb/development/my_flutter/srt/srtcore/channel.cpp;/Users/tobisweb/development/my_flutter/srt/srtcore/common.cpp;/Users/tobisweb/development/my_flutter/srt/srtcore/core.cpp;/Users/tobisweb/development/my_flutter/srt/srtcore/crypto.cpp;/Users/tobisweb/development/my_flutter/srt/srtcore/epoll.cpp;/Users/tobisweb/development/my_flutter/srt/srtcore/fec.cpp;/Users/tobisweb/development/my_flutter/srt/srtcore/handshake.cpp;/Users/tobisweb/development/my_flutter/srt/srtcore/list.cpp;/Users/tobisweb/development/my_flutter/srt/srtcore/logger_default.cpp;/Users/tobisweb/development/my_flutter/srt/srtcore/logger_defs.cpp;/Users/tobisweb/development/my_flutter/srt/srtcore/md5.cpp;/Users/tobisweb/development/my_flutter/srt/srtcore/packet.cpp;/Users/tobisweb/development/my_flutter/srt/srtcore/packetfilter.cpp;/Users/tobisweb/development/my_flutter/srt/srtcore/queue.cpp;/Users/tobisweb/development/my_flutter/srt/srtcore/congctl.cpp;/Users/tobisweb/development/my_flutter/srt/srtcore/srt_c_api.cpp;/Users/tobisweb/development/my_flutter/srt/srtcore/window.cpp;/Users/tobisweb/development/my_flutter/srt/srtcore/srt_compat.c;/Users/tobisweb/development/my_flutter/srt/srtcore/sync.cpp;/Users/tobisweb/development/my_flutter/srt/srtcore/sync_posix.cpp
-- APP: srt_virtual: using default C++ standard
-- ADDING TRANSITIVE LINK DEP to:srt_shared : -pthread 
-- ADDING TRANSITIVE LINK DEP to:srt_static : -pthread 
-- INSTALL DIRS: bin=bin lib=lib shlib=lib include=include
-- APPS: ENABLED, std=11
-- DEVEL APPS (testing): DISABLED
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/tobisweb/development/my_flutter/srt
Scanning dependencies of target srtsupport_virtual
[ 14%] Built target srtsupport_virtual
Scanning dependencies of target srt_virtual
[ 16%] Building CXX object CMakeFiles/srt_virtual.dir/srtcore/epoll.cpp.o
/Users/tobisweb/development/my_flutter/srt/srtcore/epoll.cpp:120:14: error: use of undeclared identifier 'kqueue'
   localid = kqueue();
             ^
/Users/tobisweb/development/my_flutter/srt/srtcore/epoll.cpp:220:18: error: variable has incomplete type 'struct kevent'
   struct kevent ke[2];
                 ^
/Users/tobisweb/development/my_flutter/srt/srtcore/epoll.cpp:220:11: note: forward declaration of 'kevent'
   struct kevent ke[2];
          ^
/Users/tobisweb/development/my_flutter/srt/srtcore/epoll.cpp:225:29: error: use of undeclared identifier 'EVFILT_READ'
      EV_SET(&ke[num++], s, EVFILT_READ, EV_ADD, 0, 0, NULL);
                            ^
/Users/tobisweb/development/my_flutter/srt/srtcore/epoll.cpp:225:42: error: use of undeclared identifier 'EV_ADD'
      EV_SET(&ke[num++], s, EVFILT_READ, EV_ADD, 0, 0, NULL);
                                         ^
/Users/tobisweb/development/my_flutter/srt/srtcore/epoll.cpp:226:29: error: use of undeclared identifier 'EVFILT_WRITE'
      EV_SET(&ke[num++], s, EVFILT_WRITE, EV_ADD, 0, 0, NULL);
                            ^

**Comment by maxsharabayko** [comment]
Hi @tobisweb 
If you are targeting ANDROID, you should let CMake know about it. See [this line](https://github.com/Haivision/srt/blob/master/CMakeLists.txt#L566) in SRT's CMakeLists.txt and [this CMake guide](https://cmake.org/cmake/help/v3.7/manual/cmake-toolchains.7.html#cross-compiling-for-android).

From your log, the build targets MacOS:

```
-- DETECTED SYSTEM: DARWIN; OSX=1
```

Sadly, the Android compillation guide is not maintained and is provided as is. It would be extremely helpfull if you could improve it once you succeed with your build.

**Comment by maxsharabayko** [comment]
See also #1597

**Comment by tobisweb** [comment]
@maxsharabayko Thanks for your hint! 
I changed the target to ANDROID and it seems to work so far. The build succeeded and I got a libsrt.so file.

**Comment by aixil123** [comment]
> @maxsharabayko感谢您的提示！
> 我将目标更改为ANDROID，到目前为止，它似乎仍然有效。构建成功，我得到了libsrt.so文件。

Which is change the target to android, please a command, or a compiler configuration bother sending, thank you, my dear.

**Comment by aixil123** [comment]
> @maxsharabayko Thanks for your hint!
> I changed the target to ANDROID and it seems to work so far. The build succeeded and I got a libsrt.so file.

Which is change the target to android, please a command, or a compiler configuration bother sending, thank you, my dear.

**Comment by muhammedakyuzlu** [comment]
Hello @tburchardt 
Is your Flutter project open source? If so, could you provide access to it? I'm interested in using SRT with my Flutter project as well.

Thanks
