### ISSUE TITLE
[BUG]pthread_cancel error stops Android build. 

### ISSUE THREAD

**Issue by techmaticsnz** [Haivision/srt#1597]
**Describe the bug**
I am trying to build android .so files on a debian 10 computer.  Build fails with the following error:
```
/home/nathan/repositories/srt/docs/Android/srt/srtcore/sync_posix.cpp:371:9: error: use of undeclared identifier 'pthread_cancel'
        pthread_cancel(m_thread);
        ^
1 error generated.
make[2]: *** [CMakeFiles/srt_virtual.dir/build.make:349: CMakeFiles/srt_virtual.dir/srtcore/sync_posix.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:223: CMakeFiles/srt_virtual.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
[ 14%] Built target srtsupport_virtual
[ 16%] Building CXX object CMakeFiles/srt_virtual.dir/srtcore/sync_posix.cpp.o
/home/nathan/repositories/srt/docs/Android/srt/srtcore/sync_posix.cpp:371:9: error: use of undeclared identifier 'pthread_cancel'
        pthread_cancel(m_thread);
        ^
1 error generated.

```

**To Reproduce**
1. Run /bin/bash mkall from srt/docs/Android
2. See errors

**Expected behavior**
Should be able to get .so files for Android

**Desktop (please provide the following information):**
 - OS: Debian 10
 - SRT Version / commit ID: 1.4.2/49f19fe

We're on a tight schedule to get the program working so i'd appreciate if we can get this fixed right away.

**Comment by maxsharabayko** [comment]
_Moving [my reply](https://github.com/Haivision/srt/pull/1484#issuecomment-707002522) and further discussion here._

The building issue is because there is no `pthread_cancel()` on Android. SRT uses `pthread_cancel()` mostly as a fallback plan in case there was some unexpected error around some thread's state.
SRT does not rely on it and is not even expected to use if. So we can assume it is safe not to use it if the platform does not support it.

This PR wrapped the `pthread_cancel()` around `#ifndef ANDROID`. Looks like `ANDROID` is not defined in your build.
It is defined by CMake [here](https://github.com/Haivision/srt/blob/master/CMakeLists.txt#L566).
Could you please check if you have this definition?

**Comment by techmaticsnz** [comment]
My CMakeLists file does have Android.

**Comment by techmaticsnz** [comment]
Just chiming in to issue. Appears to build for ndk requires r19 so i'll be getting that ndk and running it and reporting to see what the errors are.

**Comment by techmaticsnz** [comment]
Okay, it appears if you do not have the CMAKE_SYSTEM_NAME it will not compile for Android (to be expected) I've tried following cross compiling using NDK, which failed. now I'm trying standalone toolchain method. Basic failure for ndk was 
like this error:
`/home/nathan/srt/android-ndk-r19c/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /home/nathan/srt/Android/x86_64/lib/libcrypto.a(aes_misc.o): incompatible target
`

**Comment by techmaticsnz** [comment]
Okay. I've stumbled on the issue looking in logs.
I've been able to compile the .so files for Android.
Here's what i needed to do.
download android-ndk-r19c onto computer. point mkall NDK to this folder
download latest version of cmake. i had to do sudo apt-get purge cmake on my debian 10 computer. then install from source. I followed the following guide https://linux4one.com/how-to-install-cmake-on-debian-10
however to tailor it i changed the version number. On my computer in order to get it in path i had to edit my .bashrc to include /usr/local/bin

Then I had to modify the configure command in mksrt to the following:
`./configure --use-openssl-pc=OFF --CMAKE_PREFIX_PATH=$install_dir --CMAKE_INSTALL_PREFIX=$install_dir --CMAKE_SYSTEM_NAME=Android --CMAKE_SYSTEM_VERSION=21  --CMAKE_ANDROID_NDK=/home/nathan/srt/android-ndk-r19c --CMAKE_ANDROID_ARCH_ABI=$arch_abi`
however to do this last bit had to modify prepare_build case statement to the following:
```while getopts t:h:a:s:i:b: option
do
 case "${option}"
 in
 t) toolchain_dir=${OPTARG};;
 h) target_host=${OPTARG};;
 a) target_host_api=${OPTARG};;
 s) src_dir=${OPTARG};;
 i) install_dir=$OPTARG;;
 b) arch_abi=${OPTARG};;
 esac
done
```
this arch_abi is added to the end of mkall file
```

for arch in arm arm64 x86 x86_64; do
 rm -rf $BASE_DIR/openssl-$openssl_ver
 tar xf $BASE_DIR/openssl-$openssl_ver.tar.gz
 $BASE_DIR/mkssl -t $toolchain -h ${target_hosts[$arch]} -a ${target_api[$arch]} -s $BASE_DIR/openssl-$openssl_ver -i ${sysroots[$arch]}

 git -C $BASE_DIR/srt clean -fd
 $BASE_DIR/mksrt -t $toolchain -h ${target_hosts[$arch]} -a ${target_api[$arch]} -s $BASE_DIR/srt -i ${sysroots[$arch]} -b ${archabi[$arch]}
done
```

**Comment by maxsharabayko** [comment]
Hi @techmaticsnz 
Thank you for reporting back on your progress! You are now able to build SRT on Android, right?

It would be very appreciated if you could update the [Android Building Guide](https://github.com/Haivision/srt/blob/master/docs/Android/Compiling.md) based on your build process.

**Comment by techmaticsnz** [comment]
Yes, I have it building now. This is the first time i'll be contributing to another repo. What is the process for making a change and requesting a pull?

**Comment by maxsharabayko** [comment]
> Yes, I have it building now. This is the first time i'll be contributing to another repo. What is the process for making a change and requesting a pull?

Right, the procedure is described in the Developer's Guide, Section [Submitting a Pull Request](https://github.com/Haivision/srt/blob/master/docs/DevelopersGuide.md#submitting-a-pull-request).

> I've got it building but just read developer guide and it says it needs openssl1.1.1.

It is better to use a more recent version 1.1.1 of the OpenSSL library, as there might be, e.g., important security fixes.

**Comment by techmaticsnz** [comment]
> It is better to use a more recent version 1.1.1 of the OpenSSL library, as there might be, e.g., important security fixes.

Yeah all good, i have 1.1.1h currently.

**Comment by techmaticsnz** [comment]
Do i generally make a feature branch with the changes and then pull request from that branch into master? i know that there are procedures usually, (ie, in our case, features go into development and then development goes into master). Also how do you link a commit to this issue?

**Comment by techmaticsnz** [comment]
I have the libsrt building with latest openssl. I've added an armeabi target using armv5te-linux-androideabi16. Use with discretion as it hasn't been tested but i took the required compile info from the openssl1.1.1 script that i found. I've replaced the mkssl script with the updated one and changed the scripts

**Comment by techmaticsnz** [comment]
Im getting onto updating this now. will make a pull request shortly.
