### ISSUE TITLE
[BUG] API change: SRT_MSGCTRL.srctime changed from wallclock time to monotonic clock between 1.4.1 and 1.4.2

### ISSUE THREAD

**Issue by sdroege** [Haivision/srt#1598]
**Describe the bug**

In version 1.4.1 and before, SRT_MSGCTRL.srctime was given in wallclock time in microseconds since the UNIX epoch. The update to 1.4.2 changed this to a monotonic clock (as returned from `srt_time_now()`).

While this change is in principle the right thing, this breaks existing applications and is an API change. This should've at least caused the soname to be increased from libsrt.so.1 to libsrt.so.2 to prevent uncontrolled breakage.

**Comment by maxsharabayko** [comment]
PR #1741 changes the `so` naming. It will now also include the minor version, i.e. `libsrt.1.4.so`.
Certain API changes are allowed in minor releases if required, e.g. v1.4.3 -> v1.5.0. A further goal is to also make API tolerant to extensions.

The existing change (SRT_MSGCTRL.srctime changed from wallclock time to monotonic clock between 1.4.1 and 1.4.2) can't be withdrawn. This change is now mentioned in [v1.4.2 release notes](https://github.com/Haivision/srt/releases/tag/v1.4.2).

**Comment by ethouris** [comment]
As a further note to that I'd like to mention also that the time passthrough feature wasn't working correctly before 1.4.2. The wallclock used there was one of the reason why it wasn't working correctly. This was actually an experimental feature that has been created in the early version of SRT (before 1.2.0), but it wasn't working correctly; problems were both in the correct setting of the start time and effective translation between the internal time and the wall clock, but it might also go haywire in case when the wallclock in the computer is changed during transmission.
