### ISSUE TITLE
stransmit exits, once connection to listener drops.

### ISSUE THREAD

**Issue by nitrat7** [Haivision/srt#16]
hello,

I test following setup:

**sender**
transmitting udp-stream to relay 40.74.114.99
`./stransmit udp://127.0.0.1:10000 srt://40.74.114.99:4000?mode=caller -r:10 -s:10  -t:10`

**relay**
relaying srt-stream port 4000 incoming as listener to srt-stream port 4002 as listener
`./stransmit srt://:4000/?mode=listener srt://:4002?mode=listener -r:10 -s:10 -v -t:10`

**receiver**
receiving stream from relay over srt-port 4002
`./stransmit srt://40.74.114.99:4002/?mode=client file://con | ffplay -`

**issue/question**
receiver drops connection to relay. 
Then relay-stransmit-process exits and so also sender-stransmit-process. 
Is this correct behavior? 
I would expect, stransmit-relay-processs remains listening/running.

> ======= SRT STATS: sid=858452265
> PACKETS SENT: 0 RECEIVED: 0
> LOST PKT SENT: 0 RECEIVED: 0
> REXMIT SENT: 0 RECEIVED: 0
> RATE SENDING: 0 RECEIVING: 0
> BELATED RECEIVED: 58 AVG TIME: 1.844478248e+16
> REORDER DISTANCE: 0
> WINDOW: FLOW: 8192 CONGESTION: 8192 FLIGHT: 0
> RTT: 255.174ms  BANDWIDTH: 0.011648Mb/s
> BUFFERLEFT: SND: 12288000 RCV: 11884500
>  << 1128  ->   sent
> +++/+++SRT TRANSFER: 6776084B DURATION: 20512ms SPEED: 322.609kB/s
>  << 564  ->   sent
>  << 376  ->   sent
>  << 752  ->   sent
>  << 564  ->   sent
>  << 564  ->   sent
>  << 376  ->   sent
>  << 376  ->   sent
>  << 376  ->  FAILURE
> srt_sendmsg: [2001] Connection was broken.
> SrtCommon: DESTROYING CONNECTION, closing sockets
> SrtCommon: DESTROYING CONNECTION, closing sockets

**Comment by ReubenM** [comment]
stransmit is not persistant (see #24)

Once connection is made, Either side of the connection will exit if it's corresponding process exits.

You could get around the problem by using 2 stransmit processes in the relay connected by a pipe, with the receiving side in listening mode and the transmitting side in caller mode. The first process will block the second from starting until it receives a connection.

**Comment by nitrat7** [comment]
Thanks @ReubenM 
Just thought, that stransmit in listener behaves same as for Haivision Mediagateway or any other Haivision product running SRT in listener mode.
On disconnect of any Client to a pull connection, running listener process does NOT terminate and stays active and allows reconnection - but here stransmit listener process terminates.

**Comment by ethouris** [comment]
Ok, tell you what. Creation of `stransmit` tool was kinda necessary for having at least some tool for testing the SRT library. Then it has evolved into something more useful, also as a flipper between UDP and SRT. Although it's a little bit tough to define a medium that is simultaneously universally either source or target and either caller or listener simultaneously, so some "halfway" must have been made. So, the same as when the caller breaks when the listener is killed, so is the other way around.

If we wanted to have some tool that is a universal listener that does "empty reading" when none connected, and resends the data to whoever is currently connected, then definitely it can't be some universal simple "transmit source to destination" tool, as `stransmit` is. This would have to be some other tool that has various possible media as source and ALWAYS SRT LISTENER as target. But it would have to be designed a little bit differently and it's rather little possibility (or at least it makes little sense) to add this functionality to stransmit.
