### ISSUE TITLE
Is there an open-source low latency srt player?

### ISSUE THREAD

**Issue by lovelypp777** [Haivision/srt#1600]
I need a utility  to  test srt. I find there is a srt player pro in Haivision, but it is not open source.

**Comment by ynerant** [comment]
ffplay (included with ffmpeg in most distributions) is able to connect to a SRT stream. A pull request has been made to the MPV player to support the SRT protocol: https://github.com/mpv-player/mpv/pull/8139
VLC Media Player also support this protocol, but unfortunately does not support SRT options (like streamid: https://trac.videolan.org/vlc/ticket/25168), so if you don't use options, you may also use VLC.

**Comment by maxsharabayko** [comment]
See also [this list](https://srtlab.github.io/srt-cookbook/apps/) of applications with SRT support.

**Comment by mbakholdina** [comment]
Hi @lovelypp777, we've updated the [CookBook page](https://srtlab.github.io/srt-cookbook/apps/) and added the list of free of charge players with SRT support. I am closing the ticket, please feel free to reopen in case of remaining questions.

**Comment by jlsantiago0** [comment]
NOTE: FFPlay from the FFMPEG project also supports SRT if built with SRT support.

**Comment by maxsharabayko** [comment]
Added FFPlay.
