### ISSUE TITLE
Initiate shutdown from the server

### ISSUE THREAD

**Issue by nikesaw** [Haivision/srt#1601]
Hello.
I'm writing an Erlang framework for SRT protocol. 
Is there any way to tell "shutdown" to a client from the server side? I've made a timeout mechanism - if I have no data during several seconds - I reset a listener for UDP peer pair (socket / host / port). But sometimes, Larix srt client continues to send data to my side after some time - therefore I get data packets without a handshake. How to reply from the server side something like "I want to initiate a new session" or to send a shutdown signal? I didnt find anything in the RFC draft - is there no such methods?

Thanks in advance!

**Comment by maxsharabayko** [comment]
Hi @nikesaw 
There is a SHUTDOWN control packet. See [this section](https://tools.ietf.org/html/draft-sharabayko-mops-srt-01#section-3.2.6) of RFC.
