### ISSUE TITLE
Request new release version for VLC contrib

### ISSUE THREAD

**Issue by justinjoy** [Haivision/srt#162]
As a nettle crypto backend[0] is landed, I'd like to use an official SRT version which includes that commit. This is very important for VLC contrib.

To enable SRT module in VLC nightly build, VLC should fetch SRT while running build process.
Due to license conflict between VLC and OpenSSL, it was postponed until SRT supports GPL-compatible crypto backend.

Now, SRT has nettle backend in master and it solves license problem.
Can I ask an official version of SRT?

[0] 6c3fa957e07a314142b59868f7ffc26be61034aa

**Comment by ethouris** [comment]
Right. I think we can officially make it a 1.2.1 version. What do you think?

**Comment by justinjoy** [comment]
Sounds good to me.
