### ISSUE TITLE
SRT fails when sending from Comcast US

### ISSUE THREAD

**Issue by karlbrowns** [Haivision/srt#163]
We're trying to use stransmit to send an SRT stream through Comcast ISP in the US to us in the UK.  It breaks down as soon as we go above 2Mbps.  Retransmission goes through the roof, packet loss goes up, stream dies.

If I send using the same software and hardware platform back from the UK to the same endpoint in the US at 7Mbps it's fine.

If we use a Haivision Makito X encoder with SRT enabled, it's happy sending from the US at 7Mbps.  What does the Haivision encoder do differently when dealing with potential data throttling or other issues that is different to stransmit?  

If we turn SRT off and stream through the Comcast ISP to the UK it works at 7Mbps but we get some packet loss (not unexpected with UDP which is why we want SRT), but the bandwidth is definitely there.

Any thoughts gratefully received.

**Comment by adamyellen** [comment]
Can you please include the command line you're using on both sides?

**Comment by karlbrowns** [comment]
stransmit -v -t:5 udp://:65222 srt://ipaddr:port?latency=175

when we're sending from our unit.  The receiver is a Haivision gateway or Makito X decoder so I can't give you a command line for that, but latency on the receiver is set to 600ms (btw, the latency=175 does NOT work - if the decoder is set to 125 then it will use 125 - it ignores the 175, but that's a different issue).

I don't know what the Makito encoder is using either, but latency was set to 600ms on the receiver for that one as well.

For your information, although I'm using the -v option, I've disabled outputting stats for each packet.

**Comment by adamyellen** [comment]
What is the average RTT you are seeing between US and UK?

**Comment by karlbrowns** [comment]
Sorry, latency was set to 700ms on the receiver.
When the Haivision encoder was sending, the RTT was steady at around 120ms.
When our transmitter was sending, the RTT was more like 4500ms.  But it's the same internet connection so why would RTT go up?

**Comment by heidabyr** [comment]
Can you please remove the -v option? It will still be active, even though the stats are disabled.

**Comment by karlbrowns** [comment]
I've now done that (removed -v) - I've not got a direct connection to the gateway, but it doesn't look like it's working any better, as we are restreaming from the gateway to an rtmp stream which I'm looking at.

**Comment by karlbrowns** [comment]
Yes, confirmed now, it has occasionally looked better, but RTT still goes up to 4500ms and the stream breaks up when streaming >2Mbps.  Is there a retransmit limit on stransmit?  Is there a way of setting it?  That might help, though I don't think that's the only issue.

**Comment by ethouris** [comment]
RTT=4.5s? That's kinda extreme.

There's no general limit for retransmission, but there's a bandwidth limit option - see `maxbw` option, for example, which limits the bandwidth usage for transporting both normal and retransmitted packets effectively. With TLPKTDROP turned on (default) the receiver will wait for retransmission of the lost packet only up to the moment when the next already received packet is ready to play. When it happens, the lost packet is no longer tried to be recovered. The `latency` option controls the time between the moment when the packet should be received according to the initially measured packet delivery time, and the moment when it's turned in to the application, so setting it to a higher value increases the probability that the packet will be recovered.

Additionally, the packet can be dropped already by the sender (not sent at al), if the sender knows in advance that the packet will arrive at the receiver too late anyway.

**Comment by adamyellen** [comment]
If RTT is steady at 120ms and then jumps to 4500ms when stransmit is running that would seem to indicate that stransmit is causing some heavy congestion on the link. Do you know what kind of bandwidth the link can sustain? What's the source feeding stransmit?

**Comment by karlbrowns** [comment]
The actual link is >100Mbps upload, we can stream at 8Mbps over UDP without SRT without difficulty, just the normal dropped packet problem with UDP.  I agree that 4500ms is extreme.  Why or how would stransmit cause such congestion?  The source feeding stransmit is a custom encoder being fed out by an FPGA.  And as mentioned earlier, I can use stransmit using the same hardware in the reverse direction from the UK to the US and it causes no such jumps in RTT and it works ok.

**Comment by karlbrowns** [comment]
More testing today.  Some changes, in that it has been streaming fairly well at 7Mbps for a long time, but occasional drop outs.  At one point I ramped the data rate to 10Mbps and it worked for a few minutes but then dropped out and didn't recover until I brought the data rate back to 2Mbps. 
![2017-11-17 11 19 23](https://user-images.githubusercontent.com/29904023/32951707-d57800aa-cba2-11e7-95ea-72cec77fb8d0.jpg)
The first picture is when it was running at 10Mbps and failed.  The next picture is when it was running at 7Mbps and failed, but then recovered again.
![2017-11-17 14 01 00](https://user-images.githubusercontent.com/29904023/32951743-f76687cc-cba2-11e7-801e-cc5f70b3dbf8.jpg)
Final comment is that it has just dropped out again as I type, and isn't recovering at 7Mbps.  RTT is steady at around 6s.
I am curious as to what could possibly cause the RTT to skyrocket like that, from a steady 100ms to jump to >5s just seems ridiculous. If I know what could cause such a spike then I might be able to do something about it.
