### ISSUE TITLE
[FR] Comprehensive changelog for APIs, programmatic way to test

### ISSUE THREAD

**Issue by toots** [Haivision/srt#1632]
I am maintaining the binding over at https://github.com/savonet/ocaml-srt.

After upgrading my local `libsrt`, I see that `srt_socket` is not deprecated but I cannot find any info re: which version introduced the other function, `srt_create_socket` nor any easy way to detect that at the C pre-processor level.

Likewise, it looks like the `struct SRT_EPOLL_EVENT_` was renamed to `struct SRT_EPOLL_EVENT_STR` but I have no info on when and how to detect it.

As the library progress in adoption, it would be nice to provide such tools for people building software using it. Thanks!

**Comment by maxsharabayko** [comment]
Hi @toots 

Thanks for reporting.
Not sure if some scripting tools could be provided here. But the documentation definitely needs to be improved.

### TODO:

- The [API-functions.md](https://github.com/Haivision/srt/blob/master/docs/API-functions.md#srt_create_socket) needs to be reworked a bit, to have a summary table similar to the one [SocketOptions.md](https://github.com/Haivision/srt/blob/master/docs/APISocketOptions.md#list-of-options), with some information on when a certain API function was added.

- Deprecation information and removal of deprecated functions, API renamings, and any API changes should go to Release Notes.

**Comment by mbakholdina** [comment]
@toots 
The SRT [API-functions.md](https://github.com/Haivision/srt/blob/master/docs/API-functions.md#SRT-API-Functions) has been improved. It now has the summary of API functions with a short description. All the functions are splitted into categories. [srt_socket](https://github.com/Haivision/srt/blob/master/docs/API-functions.md#srt_socket) is marked Deprecated.

**Comment by toots** [comment]
Looks great thanks for doing it!

**Comment by maxsharabayko** [comment]
The remaining TODO item "Deprecation information and removal of deprecated functions, API renamings, and any API changes should go to Release Notes" has a separate issue #1602.
This one can be closed.
