### ISSUE TITLE
SRT compilation for android configuration options - with - target - path problem

### ISSUE THREAD

**Issue by ghost** [Haivision/srt#1655]
Linux should be how to compile for android, thank you, please help solve
look:
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_LIBRARIES
  OPENSSL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindOpenSSL.cmake:313 (find_package_handle_standard_args)
  CMakeLists.txt:324 (find_package)
In fact I have installed openssl, and can be found through the command openssl

Try to eventually cmake tips are as follows:
fatal error: 'openssl/evp.h' file not found

**Comment by aixil123** [comment]
export OPENSSL_INCLUDE_DIR=/openssls/include
export  OPENSSL_LIBRARIES=/openssls/lib

**Comment by maxsharabayko** [comment]
Related issues: #1595, #1597

@aixil123 If you are building for Android, you likely need OpenSSL available in that toolchain.

**Comment by maxsharabayko** [comment]
Closing due to the lack of activity.
