### ISSUE TITLE
How to install srt-live-transmit on a clean Ubuntu 20.4 ?

### ISSUE THREAD

**Issue by gaamaaresosa** [Haivision/srt#1697]
Option 1:
These lines seems not working for me (https://github.com/Haivision/srt)
I get below error while running 
-bash: ./configure: No such file or directory (./configure)
First of from which path we have to run these lines ?
Should we create any new directory at some path?
Now proper documentation on the net.

I tried:

sudo apt-get update
sudo apt-get upgrade
sudo apt-get install tclsh pkg-config cmake libssl-dev build-essential
./configure
make

Option 2:
apt install srt-tools -y
The above line install older version (srt-live-transmit) only (SRT Library version: 1.4.0)

Usually Linux experts never consider Windows guys who doesn't know much about Linux.
If linux experts give few more lines that would be a great help.

Some one please let me know step by step how to successfully install srt-live-transmit on Ubuntu 20.4
I try on DigitalOcean droplet.

**Comment by maxsharabayko** [comment]
Hi @gaamaaresosa 
The `configure` file is located in the root directory of the project [here](https://github.com/Haivision/srt/blob/master/configure).
Note that it has nothing to do with Autotools, it just calls Cmake. So it is possible to use CMake directly as well.

**Comment by gaamaaresosa** [comment]
> 
> 
> Hi @gaamaaresosa
> The `configure` file is located in the root directory of the project [here](https://github.com/Haivision/srt/blob/master/configure).
> Note that it has nothing to do with Autotools, it just calls Cmake. So it is possible to use CMake directly as well.

**Comment by gaamaaresosa** [comment]
Hi @maxsharabayko
Thank you so much. I have figured out few days before with little struggle.
