### ISSUE TITLE
FFMPEG with SRT

### ISSUE THREAD

**Issue by DigitalTVDev** [Haivision/srt#1706]
I'm trying to build ffmpeg with srt but appeard error during compile,
configuration: PATH="$HOME/bin:$PATH" PKG_CONFIG_PATH="$HOME/ffmpeg_build/lib/pkgconfig" ./configure --prefix=/root/ffmpeg_build --pkg-config-flags=--static --extra-cflags=-I/usr/local/cuda/include --extra-ldflags=-L/usr/local/cuda/lib64 --extra-cflags=-I/root/ffmpeg_build/include  --extra-ldflags=-L/root/ffmpeg_build/lib --extra-cflags=-I/root/Video_Codec_SDK_9.0.20/include --extra-ldflags=-L/root/Video_Codec_SDK_9.0.20/Lib/linux/stubs/x86_64 --extra-libs=-lpthread --extra-libs=-lm --bindir=/root/bin --enable-gpl --enable-libfreetype --enable-libmp3lame --enable-libopus --enable-libvpx --enable-libx264 --enable-libx265 --enable-nonfree --enable-cuda --enable-cuvid --enable-nvenc  --enable-libnpp --enable-libsrt --extra-cflags=-I/usr/local/openssl/include --extra-ldflags=-L/usr/local/openssl/lib --enable-openssl --disable-shared --enable-static
![image](https://user-images.githubusercontent.com/70523824/101954169-11782b80-3c15-11eb-8682-d529e2c71923.png)

**Comment by ethouris** [comment]
FYI there has been created a ticket against it in ffmpeg https://trac.ffmpeg.org/ticket/8760

As mentioned in #1382

**Comment by maxsharabayko** [comment]
@DigitalTVDev Could you please tell which version of FFMpeg are you using,
This is the commit in FFMpeg with a fix of #1382: [link](https://github.com/FFmpeg/FFmpeg/commit/7c59e1b0f285cd7c7b35fcd71f49c5fd52cf9315).
committed on Jul 28 
lavf/srt: fix build fail when used the libsrt 1.4.1

**Comment by DigitalTVDev** [comment]
@maxsharabayko 
@ethouris 
I am using FFmpeg 4.3.1 "4:3" , but when I download latest version of ffmpeg from github (ffmpeg version N-100397-gd764693 Copyright (c) 2000-2020 the FFmpeg developers) It was compiled and now working fine with srt
