### ISSUE TITLE
how do I use the srt-file-transmit mode to transmit multiple files at a time

### ISSUE THREAD

**Issue by douguixiao** [Haivision/srt#1725]
this is an example of a single file transfer:
srt-file-transmit.exe -v ./test.m4s srt://:5555
srt-file-transmit.exe -v srt://127.0.0.1:5555 ./test.m4s

**Comment by maxsharabayko** [comment]
`srt-file-transmit` is a **sample** application to transfer only one file over an SRT connection.
A solution might be:
- use several instances of `srt-file-transmit` per file;
- modify `srt-file-transmit` to work with multiple files.

There is also a **testing** application [`srt-xtransmit`](https://github.com/maxsharabayko/srt-xtransmit), which allows to send/receive multiple files and folders using SRT. See `file send` and `file receive` subcommands.
