### ISSUE TITLE
Undesirable behaviour when feeding SRT with a static video?

### ISSUE THREAD

**Issue by oviano** [Haivision/srt#1726]
Video encoded using NVENC, key frame every second, latency 200ms, so the pattern when encoding a static video is that I submit a ton of packets to SRT when it encodes a key frame, and then minimal packets in=between because the image is not actually changing so there is little encoded data.

What I am finding is that the player gets into some sort of oscillating state where (I think) it reads all the small packets before a keyframe and this empties the receive buffer (stats msRcvBuf is now 1ms), so my decoder starves for a very short time, and then it seems like a very short time later all the keyframe packets come through and as these come through the "stats msRcvBuf" value rises back up to 200ms again. I do not lose any frames of data, just that periodically (and it seems like every second) the receive buffer becomes empty.

I can mitigate by increasing the latency or increasing the decoder's own small buffer, but that is not ideal just for the special case of a static video so I wonder if I can stop this happening? Am I suppose to space-out the packets for a keyframe or something? However, conceptually the packets for a keyframe belong to a single timestamp so I'd expect the player to read them all out at the same time?

Thing is, if I feed a normal, moving video, I don't get this issue, the SRT receive buffer stays fairly constantly full. This is across a LAN, so it's nothing about bandwidth constrains, latency or jitter, it seems to be something about the pattern of submitting data from a video that consists mostly of key frames and little data between.

I suppose some logs might help?

**Comment by jeandube** [comment]
@oviano I think this issue is related to the output pace rate. Have a look at the documentation in [PR#1383](https://github.com/Haivision/srt/pull/1383).

**Comment by oviano** [comment]
Thank you for that, it looks interesting.

At the moment I have it set to automatic, and in most cases I am encoding using VBR so this does seem relevant.

Although...in the case I am testing right now NVENC is actually configured to use CBR for encoding but it appears that the bitrate still drops to about 40% of the configured bitrate when the video is static. I don’t know if that is to be expected or not.

**Comment by oviano** [comment]
So further to this, I seemed to have solved my issue just by specifying the SRTO_INPUTBW. Previously I was relying on the automatic calculation, but I now understand this is flawed with VBR (or inaccurate CBR) and it's better to put in the bandwidth since I know it. This stopped the wild fluctuations in the receiver buffer timespan.

I do have a Q though, I'm curious as what is the effect of let's say setting the input BW to 8mbit/s, but then the actual supplied bandwidth being less? This seems to happen with my CBR encode. I specify 8mbit/s but when the video is static, it actually only produces about 3mbit/s for some reason using NVENC. Is that a problem?

**Comment by mbakholdina** [comment]
> I do have a Q though, I'm curious as what is the effect of let's say setting the input BW to 8mbit/s, but then the actual supplied bandwidth being less? This seems to happen with my CBR encode. I specify 8mbit/s but when the video is static, it actually only produces about 3mbit/s for some reason using NVENC. Is that a problem?

Hi @oviano,

I recommend you to take a look at [the following section](https://haivision.github.io/srt-rfc/draft-sharabayko-mops-srt.html#name-srt-packet-pacing-and-live-) of future RFC version which describes in details different modes of setting SRT bandwidth (so called MAX_BW). You can use either MAXBW_SET, or INPUTBW_SET mode for you task.

The formula is the following:
```
MAX_BW = INPUT_BW * (1 + OVERHEAD /100)
```
where INPUT_BW corresponds to the encoder output bitrate and the OVERHEAD is the overhead required for retransmitting packets in case of loss and possible bitrate variations (25% by default).

MAX_BW limits SRT output pacing rate so that MAX_BW is the maximum possible value. In your case, everything is fine. MAXBW of 8mbit/s is more than enough for 3mbit/s stream.

**Comment by oviano** [comment]
Great, thanks so much for the feedback.
