### ISSUE TITLE
How to transmit multiple channels?

### ISSUE THREAD

**Issue by Budkhuu976** [Haivision/srt#1727]
Hi I'm trying to 52 udp H265 tv channels transmitting.

udp(h265)->srt->internet-srt->udp(h265)->udp(h264)->ip MUX scrambler

sender  : srt-live-transmit udp://224.1.1.1:20001 srt://:90001 ...-...  srt-live-transmit udp://224.1.1.1:20052 srt://:90052
receiver : srt://x.x.x.x:90001 udp://224.1.1.1:10001 ...--... srt://x.x.x.x:90052 udp://224.1.1.1:10052
udp h265 -> udp H264 : ffmpeg -re -i udp://224.1.1.1:10001 -threads 0 -codec copy -bsf:v h264_mp4toannexb -acodec aac -b:a 128k -ac 2 -ar 44100 -f mpegts udp://224.0.0.1:10001?pkt_size=1316  ...  ffmpeg -re -i udp://224.1.1.1:10052 ... mpegts udp://224.0.0.52:10052?pkt_size=1316 

How to do it easily?
Is it possible to transmit multiple channels in this way?
nginx rtmp-module not support h265.

**Comment by ethouris** [comment]
It is possible, just not with `srt-live-transmit` application. This app is intended for simple and straightforward uses only. This is possible in SRT in general.

There's another application that was later downgraded to "developer/tester application" (so it doesn't features reconnection and is not exactly user friendly) called `srt-test-multiplex` (you need to `--enable-testing` to make it compiled). At least you can use it for testing if it works. Your call of sender and receiver would be then:

sender: srt-test-multiplex srt://:90000 -i udp://224.1.1.1:20001?id=1 udp://224.1.1.1:20002?id=2 ... udp://224.1.1.1:20052?id=52
receiver: srt-test-multiplex srt://x.x.x.x:90000 -o  udp://224.1.1.1:10001?id=1 etc...

**Comment by ethouris** [comment]
@Budkhuu976 if everything is fine, please close the ticket.

**Comment by mbakholdina** [comment]
Closing the ticket. Please feel free to reopen in case of further questions.
