### ISSUE TITLE
Could not play srt in VLC

### ISSUE THREAD

**Issue by gogsbread** [Haivision/srt#1749]
Just playing around with `srt-live-transmit`. I can use `ffmpeg` to stream and `ffplay srt://192.168.86.27:4201`(or even `localhost`) to play. However, I cannot play with VLC and I see the following logs
```
main debug: `srt://192.168.86.27:4201' gives access `srt' demux `any' path `192.168.86.27:4201' 
main debug: creating demux: access='srt' demux='any' location='192.168.86.27:4201' file='(null)' 
main debug: looking for access_demux module matching "srt": 17 candidates 
main debug: no access_demux modules matched 
main debug: creating access: srt://192.168.86.27:4201 
main debug: looking for access module matching "srt": 28 candidates 
main debug: no access modules matched 
main debug: dead input 
```

` vlc --list | grep srt` gives

```
VLC media player 3.0.9.2 Vetinari (revision 3.0.9.2-0-gd4c1aefe4d)
access_output_srt      SRT stream output
```
I am running this in Ubuntu 20.04.

**Comment by ethouris** [comment]
Have you reported that also against VLC? AFAIK @justinjoy was working on it.

**Comment by justinjoy** [comment]
thx for letting me know.
I am not an active contributor to VLC currently, but I might give a hint for this question.

The vlc plugin name that is involved in playback is `access_srt`, not _access_output_srt_.
If VLC 3.0.9.2 doesn't have access plugin, it might be a mistake of VLC.

This is the result of mine. Perhaps, using the latest stable version will be helpful for you. If not, as mentioned above, the issue should be reported to VLC community.

```
$ vlc --list | grep srt
VLC media player 3.0.10 Vetinari (revision 3.0.10-0-g7f145afa84)
  access_output_srt      SRT stream output
  access_srt             SRT input
```

**Comment by gogsbread** [comment]
So looks like VLC moved to using snap based installs and hence they probably wouldn't update the apt based installer. But yes, the snap based installer has the latest build and it works.
Thanks for the help!!
