### ISSUE TITLE
[BUG] Main/backup: The group drops packets at the very beginning of the transmission

### ISSUE THREAD

**Issue by mbakholdina** [Haivision/srt#1755]
## Describe the bug

During testing Connection Bonding (main/backup algorithm) I've encountered the following problem: 

The group drops packets at the very beginning of the transmission.
The connection over backup link happens first as it's the faster link and transmission starts over backup link.
Then main link is connected in a while and the transmission continues over main link.
There are no dropped packets on both main and backup link, however there are **2 dropped packets** at the group level.
This happens in the moment of switch.

Another problem is that there is no log from the library in `srt-xtransmit` (receiver side) when the drop happens at the group level. There is only a message from individual sockets (main link when it becomes up after 2 s shutdown).

## To Reproduce

Test procedure with the detailed description of the test setup, test cases, and `srt-xtransmit` commands for reproduction can be found [here](https://stash.haivision.com/projects/SAS/repos/srt-devbook/browse/srt-protocol/connection-bonding/test-reports/release-v1.5.0/dynamic-link-stability-timeout-4th-iteration/test-procedure.md). Briefly:

Test Setup is the combination of small Flip&Flop (CentOS 7) and big LanForge with the following links connected:

```
FLIP                 ---- LanForge  ----                 FLOP

enp7s0 (192.168.4.1) ---- eth2-eth3 ---- (192.168.4.2) enp7s0    (Main link)
enp8s0 (192.168.3.1) ---- eth4-eth5 ---- (192.168.3.2) enp8s0    (Backup link)
```

**SRT version:**
- [PR 13](https://github.com/maxsharabayko/srt/pull/13), `develop/main-backup` branch:
   commit 6cd05372ae8f1b35d2fe48435db90c8bd3dfaf31 (HEAD -> develop/main-backup, origin/develop/main-backup)
   Author: Maxim Sharabayko
   Date:   Thu Jan 21 15:02:38 2021 +0100
   [core] Added socket ID to RCV-DROP log message
   
- `srt-xtransmit` with Connection Bonding support (`develop/bonding` branch):
   commit 5055a22b6a2ff4f5f59591f73d7a0a1c1ea2ef62 (HEAD -> develop/bonding, origin/develop/bonding)
   Author: Maxim Sharabayko
   Date:   Thu Jan 21 18:07:19 2021 +0100
   Printing SRC and DST URIs

**srt-xtransmit commands:**
```
# Sender
_build_bonding_main_backup/bin/srt-xtransmit generate "srt://192.168.4.2:4200?latency=800&grouptype=backup&weight=75" srt://192.168.3.2:4201?weight=25 --sendrate 1Mbps --duration 120s --enable-metrics --statsfile group-snd-stats.csv --statsfreq 1s -v
```

```
# Receiver
_build_bonding_main_backup/bin/srt-xtransmit receive srt://:4200?latency=800 srt://:4201 --enable-metrics --metricsfile group-rcv-metrics.csv --metricsfreq 1s --statsfile group-rcv-stats.csv --statsfreq 1s -v
```

**Failed test case:**

Test Case 1. Main link shutdown for 2 seconds (less than `SRTO_PEERIDLETIMEOUT` = 5 s)

| Main Link (enp7s0)                              | Backup Link (enp8s0)                       | Bitrate, Mbps  | SRT Options  | 
| ------------------------------------ | ----------------------------------- | -------------- | ------------- | 
| RTT1 = 200 ms (slow link)                  | RTT2 = 100 ms                                   | 1                       | latency=800  | 

1 out of 5 test runs - failed

To emulate link shutdown use the following command:
```
sleep 60 && echo ifdown $(date +"%F %T,%3N") && sudo ifdown enp7s0 && sleep 2 && echo ifup $(date +"%F %T,%3N") && sudo ifup enp7s0
```

Statistics and screenshots are attached.
[srt #1755.zip](https://github.com/Haivision/srt/files/5850026/srt.1755.zip)

**Comment by maxsharabayko** [comment]
There are two situations when this drop in the beginning while switching to the main link happens.
The first situation happens when the newly connected link signals the read-readiness of the packet ahead of packets in another link. Although it is not yet clear exactly why this happens,. as the new link receives previous packets as well, but somehow signs off some older packets.

```
12:19:50.357000/T8736!W:SRT.gr: group/recv: @530726722 EXTRACTED data with %1458317107 #3: D53A7CCB
12:19:50.358000/T8736!W:SRT.gr: group/recv: @530726722 %1458317107 #3 DELIVERING
12:19:50.542000/T8736!W:SRT.gr: group/recv: EPOLL: @530726720 %1458317200 NEW SOCKET INSERTED
12:19:50.543000/T8736!W:SRT.gr: group/recv: @530726720 EXTRACTED data with %1458317125 #21: D53D61B9
12:19:50.543000/T8736!W:SRT.gr: @530726720 %1458317125 #21 AHEAD base=%1458317107
12:19:50.544000/T8736!W:SRT.br: @530726720 seqno %1458317125 base seqno %1458317107 (seqdiff 18)
12:19:50.545000/T8736!W:SRT.br: @530726722 seqno %1458317107 base seqno %1458317107 (seqdiff 0)
12:19:50.545000/T8736!W:SRT.br: @1604468545 GROUP RCV-DROPPED 17 packet(s): seqno %1458317108 to 1458317125
12:19:50.553000/T8736!W:SRT.gr: group/recv: @530726720 EXTRACTED data with %1458317126 #22: D53D8BE2
12:19:50.554000/T8736!W:SRT.gr: group/recv: @530726720 %1458317126 #22 DELIVERING
12:19:50.554000/T8736!W:SRT.gr: group/recv: @530726722 %1458317108 #4 BEHIND base=%1458317125 - discarding
12:19:50.555000/T8736!W:SRT.gr: group/recv: @530726722 %1458317109 #5 BEHIND base=%1458317125 - discarding
```

[group-drop-at-start-01.zip](https://github.com/Haivision/srt/files/5873648/group-drop-at-start-01.zip)

The second situation is under investigation.
