### ISSUE TITLE
[BUG] Main/backup: The group drops packets when switches back to main link after 10 s shutdown

### ISSUE THREAD

**Issue by mbakholdina** [Haivision/srt#1757]
## Describe the bug

During testing Connection Bonding (main/backup algorithm) I've encountered the following problems: 

1) The group drops packets when switches back to main link after 10 s shutdown.
The connection over backup link happens first as it's the faster link and transmission starts over backup link.
Then main link is connected in a while and the transmission continues over main link.
Approximately after 60 s of transmission, the main link is shut sown for 10 s.
The transmission continues over backup link.
Once main link is up again, the group reconnects to it and transmission continues over main link. At this moment group drops **68 packets** (scenario 5). However, there are no drops on individual sockets.
This problem is similar to #1755. 

2) Once the transmission is started over backup link, in statistics (receiver side, scenario 5) `pktRcvLoss = 6740` what's really high value and seems to be not correct. See the attached screenshots for details. It can be related to the fact that at the very beginning the transmission starts over backup link (faster link) and this statistics isn't 0 to the moment of main link going down.
I've seen the same problem on the other network impairments scenarios and test case 1 as well.

## To Reproduce

See issue #1755 for the reproduction steps.

**Failed test case:**

Test Case 2. Main link shutdown for 10 seconds (higher than `SRTO_PEERIDLETIMEOUT` = 5 s)

Scenario | Main Link (enp7s0)                              | Backup Link (enp8s0)                       | Bitrate, Mbps  | SRT Options  | 
| --------| ------------------------------------ | ----------------------------------- | -------------- | ------------- | 
| 5           | RTT1 = 200 ms (slow link)                   | RTT2 = 100 ms                                  | 1                       | latency=800  | 
| 6           | RTT1 = 100 ms                                     | RTT2 = 200 ms (slow link)                | 1                       | latency=800  |    

1 out of 5 test runs - failed for scenario 5 (68 dropped packets)
the very first test run failed for scenario 6 and I've stopped the tests (51 dropped packets)

**Statistics and screenshots:**
[srt #1757-scen5.zip](https://github.com/Haivision/srt/files/5855515/srt.1757-scen5.zip)
[srt #1757-scen6.zip](https://github.com/Haivision/srt/files/5855520/srt.1757-scen6.zip)

**Comment by J-Rogmann** [comment]
I ran 5 tests with the latest master and found no lost and no reordered packets 
```
2021-02-17T16:42:18.780852+0100,850468,851237,850702,167,11315,0,0,0
2021-02-17T16:44:48.882083+0100,850166,850918,850549,217,11315,0,0,0
2021-02-17T16:47:09.166855+0100,850567,851036,850748,115,11314,0,0,0
2021-02-17T16:49:45.850715+0100,850244,850647,850415,129,11315,0,0,0
2021-02-17T16:52:29.769215+0100,850158,850610,850336,119,11315,0,0,0
```
