### ISSUE TITLE
receiving multi srt streaming with srt-live-transmit

### ISSUE THREAD

**Issue by aniltonf** [Haivision/srt#1758]
Hi there.

I'm really new on this, but facing a major challenge of receiving multiples SRT straming and output them to a specific IP:port

Can srt-live-transmit do this. I already have it configured, and it's working with one streaming, but having issues adding more streaming on INPUT, but specially on OUTPUT.

Help please...

System: Ubuntu-server 20:04

Thanks

**Comment by ethouris** [comment]
The `srt-live-transmit` application can only serve one stream at a time.

What you want is generally possible in SRT, just not with this application. Among testing applications (you need to `--enable-testing` to allow this to be compiled - not sure if this is distributed by default) there's `srt-test-multiplex`, which can be used to demonstrate the solution for sending multiple streams over one UDP link (not exactly over one SRT connection, but from the system perspective it will be seen like utilizing one link for all streams).

**Comment by aniltonf** [comment]
Great... thanks

So, in my case, I'm only using SRT for streaming INPUT, and do OUTPUT with UDP... The issue here is that I don't really know how to receive multiple streaming with SRT...

This is my SRT link config for INPUT...

srt://ip:port?rcvlatency=3000&sndlatency=3000&peeridletimeo=10000&oheadbw=100&nakreport=1 udp://ip:port?sndbuf=67108864 -logfile:/var/log/srt-live-transmit.log -statsout:/var/log/srt-live-transmit-SRT.log -f -ll:debug -lfa:all -pf:csv -s:1000


Can you help more?

Regards

**Comment by ethouris** [comment]
What do you mean by "multiple streaming"?

**Comment by aniltonf** [comment]
![SRT_receiving_diagram](https://user-images.githubusercontent.com/5655952/105494591-8a55b300-5caa-11eb-9d42-9093efc0c78e.png)

Please, check this diagram... each streaming with own IP and PORT

**Comment by ethouris** [comment]
So, the source passes to some intermediate application each one with its distinct SRT connection. That's ok. Then some processing happens there and it results with a one stream to be sent next over UDP (only one, as I understand, although some unusual processing should happen as through a bare UDP connection you can send only one stream).

So, yes, this is possible - in the SRT library in general - if you set up a listener in this application on the intermediate device. Then connect every source separately to it. Of course in result this application would need to accept every connection separately and separately read the data from each one.

We don't have anything among the applications that could do that. You'd have to write your own. All of our applications can process only one stream at a time.

**Comment by aniltonf** [comment]
that server in the middle is the srt-live-transmit....

**Comment by ethouris** [comment]
If you want to connect every stream to a different listener port on this intermediate device, simply run multiple instances of srt-live-transmit, each one with SRT source in listener mode, just with different port. They will just work independently.

**Comment by aniltonf** [comment]
That's the question... how can I do that. My srt INPUT and OUTPUT is on srt-live-transmit.config... should I put in the same file, multiples srt like this...? 

str://ip1:port1 udp://ip11:port11
str://ip2:port2 udp://ip22:port22

If so, it must be in different ports?

Thanks

**Comment by ethouris** [comment]
Exactly. One port can be shared (by various ways) within one application, but there's no way to share the port between application instances. Still, there's no problem in running srt-live-transmit in multiple instances.

**Comment by J-Rogmann** [comment]
Hi @aniltonf 

just to clarify: this is a limitation by `srt-live-transmit`. This executable is meant for demo purposes to help beginners to familiarize with the SRT protocol and the implementation of SRT into their own application. It is not really optimized for production purposes, although it runs stable.
`srt-live-transmit` can only handle one input & output at a time. To realize multiple SRT streams, you would need to run `srt-live-transmit` multiple times in parallel or build your own application. 

Please let me know, if that solved your problem or if you have more questions.

best regards,
Justus

**Comment by mbakholdina** [comment]
Closing the ticket due to inactivity. Please feel free to reopen in case of further questions.

**Comment by johnnyreina** [comment]
Hi @aniltonf
I need to ask you some questions about SRT
please send me your email to contact you

**Comment by kyanzad** [comment]
Hi.
How can I change this code to reach that goal?
I mean servicing more than one SRT destination with one stream.
Thanks.
