### ISSUE TITLE
udp transfer connection not persistent

### ISSUE THREAD

**Issue by mks75** [Haivision/srt#176]
Hi,
The transport connection successfully works for few hours but then stops by itself. Not sure what is causing this and what I can do to make it persistent.
Following are the set of commands I am using on my Linux machines.
 
server-1 at Location-A
./stransmit -v udp://238.1.1.1:1234 srt://server1-ip:38000?mode=server

server-2 at Location-B
./stransmit -v srt://server1-ip:38000?mode=client udp://238.2.2.2:5678

Please advise. Thanks.

**Comment by ethouris** [comment]
Note that stransmit has a default timeout of 30s for any transmission to happen (it only doesn't work on Windows). When nothing is sent from source to target for that time, stransmit exits. You can change it with `-t` option (`-t:-1` turns it off completely).

You can compile with logs enabled (`ENABLE_LOGGING=1` in cmake, or compile in debug mode) and increase log level to see what happened (default is "error").

**Comment by mks75** [comment]
Could you please share the detailed compile commands to enable logs, as you have mentioned.

Also, I have now added -t:120 to both the source and target commands.
server-1 at Location-A
./stransmit -v -t:120 udp://238.1.1.1:1234 srt://server1-ip:38000?mode=server

server-2 at Location-B
./stransmit -v -t:120 srt://server1-ip:38000?mode=client udp://238.2.2.2:5678

Will share my observations soon.
Thanks-

**Comment by ethouris** [comment]
When you run `cmake`, add `ENABLE_LOGGING=1` as argument. Then, `stransmit` has a `-loglevel` option, default is `error`. With `-loglevel:debug` it's extremely verbose, recommended is logging to a file and expect them to be extremely big.

**Comment by mks75** [comment]
I don't know much about cmake, but this is what I tried.
./configure --ENABLE_LOGGING=1
./make
not sure if this correct. I am seeing the following options for stransmit. Please advise.
Usage: ./stransmit [options] <input-uri> <output-uri>
        -t:<timeout=0> - connection timeout
        -c:<chunk=1316> - max size of data read in one step
        -b:<bandwidth> - set SRT bandwidth
        -r:<report-frequency=0> - bandwidth report frequency
        -s:<stats-report-freq=0> - frequency of status report
        -k - crash on error (aka developer mode)
        -v - verbose mode (prints also size of every data packet passed)

**Comment by ethouris** [comment]
Well, the equivalents for cmake variables used from `configure` script is: lowercase made uppercase, dash turned to underscore, and + to X. So, `--enable-logging` turns into `-DENABLE_LOGGING=1` as cmake parameter.

The `-loglevel` and `-logfa` parameters are undocumented - see [stransmit documentation](../tree/master/docs/stransmit.md) for details. For `-logfa` there are also no details, see [source file](../tree/master/apps/stransmit.cpp#L175).

**Comment by maxlovic** [comment]
Closing. Do not hesitate to reopen if the problem persists.
