### ISSUE TITLE
[FR] Connection Bonding: Add TSBPD RCV-DROPPED log for the group

### ISSUE THREAD

**Issue by mbakholdina** [Haivision/srt#1760]
During testing main/backup algorithm (Connection Bonding), I've noticed that in case group is dropping packets there is no TSBPD RCV-DROPPED log generated by the group. I see only logs from individual sockets if any.

It would be useful to add such a log.

**Comment by ethouris** [comment]
That sounds reasonable; the group receiver doesn't report this. This might be due to the problem of too big latency - the socket when broken gets closed immediately even if it has still some data in the buffer that it can deliver.
