### ISSUE TITLE
[BUG] RTTVar estimate on the sender side updates earlier than expected

### ISSUE THREAD

**Issue by mbakholdina** [Haivision/srt#1769]
## Describe the bug

See issue #1768 for the screenshots, detailed instructions, steps to reproduce, and log files.

At the beginning of the transmission, RTTVar estimate on the sender side on the main link updates earlier than expected. It actually starts changing in 1 RTT since the transmission, however it's too early for the ACK with measured RTT estimate to come at the sender side back from receiver. RTTVar gradually decreases down to 0 and then changes again in 2 RTT when the ACK (this time with measured RTT estimate) comes.

**Comment by maxsharabayko** [comment]
### TODO

- [ ] Initial RTTVar value when RTT is restored from cache

When RTT is restored from the cache, RTTVar remains the default one, which is 50. Consider setting it to `RTT / 2`.

```c++
CInfoBlock ib;
ib.m_iIPversion = peer.family();
CInfoBlock::convert(peer, ib.m_piIP);
if (m_pCache->lookup(&ib) >= 0)
{
    m_iRTT       = ib.m_iRTT;
    m_iBandwidth = ib.m_iBandwidth;
}
```

**Comment by maxsharabayko** [comment]
- [ ] Sender ignores RTTVar reported by the receiver in ACK control packet.

Sender applies EWMA on the current RTTVar value and the difference between the current RTT value and the RTT value received in ACK:

```c++
m_iRTTVar = avg_iir<4>(m_iRTTVar, abs(rtt - m_iRTT));
m_iRTT    = avg_iir<8>(m_iRTT, rtt);
```

It means that even if the receiver reports some high RTTVar value, the sender ignores it and calculates its own.

**Comment by maxsharabayko** [comment]
On the issue, SRT receiver is sending `{ RTT = 100; RTTVar = 50 }` in the beginning until it measures the first actual value from the very first ACKACK received from the sender. Only then it can send some actual, although smoothened, value.

The sender, on the other hand, receives `{ RTT = 100; RTTVar = 50 }` and already considers it a measured value, and updates RTT and RTTVar according to the code in [the above comment](https://github.com/Haivision/srt/issues/1769#issuecomment-778059415).

**Comment by mbakholdina** [comment]
**TODO**
- [ ] Write about RTT and RTTVar values stored in cache in RFC.
