### ISSUE TITLE
build failure stransmit with MinGW

### ISSUE THREAD

**Issue by justinjoy** [Haivision/srt#177]
This might not be a problem of SRT, but MinGW seems not to provide `std::this_thread`.
However, it should be fixed or changed to use alternative to support MinGW (W32 cross compilation on Linux)

```
[ 85%] Building CXX object CMakeFiles/stransmit.dir/apps/stransmit.cpp.obj
/home/jaykim/ssd/git/vlc/contrib/win32/srt/apps/stransmit.cpp: In member function ‘void BandwidthGuard::Checkpoint(size_t, size_t)’:
/home/jaykim/ssd/git/vlc/contrib/win32/srt/apps/stransmit.cpp:366:14: error: ‘std::this_thread’ has not been declared
         std::this_thread::sleep_for(expdur-dur);
              ^
/home/jaykim/ssd/git/vlc/contrib/win32/srt/apps/stransmit.cpp: In member function ‘virtual bytevector SrtSource::Read(size_t)’:
/home/jaykim/ssd/git/vlc/contrib/win32/srt/apps/stransmit.cpp:1094:17: error: ‘this_thread’ has not been declared
                 this_thread::sleep_for(chrono::milliseconds(10));
                 ^
CMakeFiles/stransmit.dir/build.make:63: recipe for target 'CMakeFiles/stransmit.dir/apps/stransmit.cpp.obj' failed
make[2]: *** [CMakeFiles/stransmit.dir/apps/stransmit.cpp.obj] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/stransmit.dir/all' failed
make[1]: *** [CMakeFiles/stransmit.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by ethouris** [comment]
Compiler vendor and version?

**Comment by justinjoy** [comment]
> Compiler vendor and version?

Ubuntu (16.06 LTS): mingw 5.3.1-8ubuntu3+17
Archlinux: mingw-w64-gcc 7.2.0-1

**Comment by ethouris** [comment]
Looxlike there's a solution here. Haven't looked too thoro' yet.

If this works, we might add some information in the docs.

https://stackoverflow.com/questions/37358856/does-mingw-w64-support-stdthread-out-of-the-box-when-using-the-win32-threading

**Comment by justinjoy** [comment]
Shouldn't we use `Sleep` for Windows, or `nanosleep` for Linux/Mac OS? 

Using 3rd party `std::thread` can be a good option, but introducing another library makes a burden for someone who wants to use `stransmit` on Windows. Above all, if SRT requires the 3rd party library, we must provide it to VLC contrib for VLC nightly build. This will raise maintaining cost a lot.

**Comment by ethouris** [comment]
I'm really surprised how a C++11 supporting gcc compiler in MinGW flavor doesn't contain proper header files for all C++11 things. But OTOH this `sleep_for` is the only part of C++11 thread library, so we can focus on this. Could you please, If possible (that is, if MinGW isn't lacking more of C++11 headers, like `std::chrono`), create a support function - say `SleepFor` - with the same type of argument, then the call will resolve to `Sleep` call on MinGW only, and to `this_thread::sleep_for` otherwise.

The `../common/appcommon.hpp` file is predicted for this purpose.

**Comment by maxlovic** [comment]
@justinjoy Is this still relevant or can close?
Now only `srt-file-transmit` uses `this_thread::sleep_for()`. `srt-live-transmit` does not.

**Comment by justinjoy** [comment]
> @justinjoy Is this still relevant or can close?
> Now only `srt-file-transmit` uses `this_thread::sleep_for()`. `srt-live-transmit` does not.

If you don't use, you can close. But to be sure, someone else should try to bump up srt version for vlc again.
