### ISSUE TITLE
[FR] Main/backup: Add advanced logging for main/backup algorithm 

### ISSUE THREAD

**Issue by mbakholdina** [Haivision/srt#1782]
For Connection Bonding, main/backup algorithm, add advanced logging directly from the SRT library:
- log the time when main link is considered unstable and backup link is activated,
- log the time when main link is considered stable again or becomes broken,
- log the time when the switch from backup to main link happens, etc.

The idea is to log all the changes in links' states and the moments of switching from one link to another.

This log should be available to the upstream application so that it knows about the reason of switching from one link to another. Any additional statistics available should be printed within the log: Socket ID, RTT, RTTVar, the value of last response time and dynamic link stability timeout, link state, etc.

**Comment by maxsharabayko** [comment]
Addressed in #1857. Closing.
