### ISSUE TITLE
[BUG]srt-file-transmit mode.packets of some file are not download

### ISSUE THREAD

**Issue by douguixiao** [Haivision/srt#1788]
when multiple files are transferred,each file has a srt-file-transmit instance.because the server does not know when the client downloads the files.the server adds a send file success control packet to notify the client that the files are uploaded.after the client downloads the files,check whether a file sending success control packet is received.if yes,the client sends a file receiving success packet to the server,and the server sends the next file.however,after control packets are added,during file download,the last packet packet of the file is not download or the srt_epoll_wait value less than 0.as a result,the dodownload function can not exit.

log:
upload: 1456 --> 1456
upload: 1456 --> 1456
upload: 158 --> 158
file sent
send file success  control packet

download: --> 1456
download: --> 1456
download: --> 158
srt_epoll_wait
srt_epoll_wait
srt_epoll_wait
…
srt_epoll_wait

**Comment by ethouris** [comment]
Excuse me, but I don't understand what application you are talking about. I'm pretty sure `srt-file-transmit` isn't capable of receiving multiple files and doesn't use any sending success control packet. Can you tell me more about what commands and solutions you are using?

**Comment by douguixiao** [comment]
the command on the server are as follows:
srt-file-transmit.exe -v file:///./1.m4s srt://:5555 -ll error -logfile a.log
srt-file-transmit.exe -v file:///./2.m4s srt://:5555 -ll error -logfile a.log
…
srt-file-transmit.exe -v file:///./40.m4s srt://:5555 -ll error -logfile a.log

the command on the client is as follows:
srt-file-transmit.exe -v srt://127.0.0.1:5555 file:///./1.m4s -ll error -logfile b.log
srt-file-transmit.exe -v srt://127.0.0.1:5555 file:///./2.m4s -ll error -logfile b.log
…
srt-file-transmit.exe -v srt://127.0.0.1:5555 file:///./40.m4s -ll error -logfile b.log

the code is modified as follow:
in the DoUpload function:
if(ifile.eof())
{
      ﹉
     //send file upload success message
}

in the DoDownLoad function:
if(n == 0)
{
      …
      //check whether the send file upload success message is received
    //if yes,send a upload file success message
}

**Comment by ethouris** [comment]
I still don't understand. How exactly do you "send the upload success message"?

In file mode SRT it's usually that you stop transmission and close the connection. The `srt_epoll_wait` function returns -1 also in case of timeout. You can try also the `srt-test-file` application that works merely the same way, just uses blocking mode (or, more precisely, allows to select blocking variant, while blocking is default).
