### ISSUE TITLE
CPU Problem

### ISSUE THREAD

**Issue by ruppen** [Haivision/srt#1809]
Hy, I have a problem. I use ubuntu Server with Kernel 5.4.0-65-generic.

Whenever I am using srt-live-transmit udp://localhost:5000 srt://dest:5001
to forward a udp Stream to my software I get a 100% CPU usage on my Linux machine. 
I have seen that there is a similar issue. The stream is  h264 4MB/s 1080p 

I am on the latest version 1.4.2

Sometimes however the stream starts without any issue and uses only 3%CPU

Did anyone resolve that issue?

**Comment by J-Rogmann** [comment]
Hi @ruppen 
this sounds very unusual, since SRT does not encode/transcode, but it's just wrapping the MPEG-TS packets into the SRT stream. Do you use encryption? Did you compile `srt-live-transmit` yourself, or are you using a binary package?

**Comment by mbakholdina** [comment]
Closing as can't reproduce and due to inactivity. Please feel free to reopen the ticket in case of further issues or comments.
