### ISSUE TITLE
with heavy log on, connection callback do not work

### ISSUE THREAD

**Issue by cg82616424** [Haivision/srt#1845]
I open heavy log, but after that, connection callback never happened, is this a bug?

**Comment by ethouris** [comment]
Hmm, tested that case on `srt-test-live`, both with connection timeout and connection broken, at least it displays the call in the log result.

Please note that this callback is intended to be called in case of a broken connection so that you can be aware of the necessity to reestablish the broken member connection. For group, you rely on epoll write readiness to know that you can start sending, and the currently connected members will be available in the group data obtained from sender/receiver function or `srt_group_data()`.

**Comment by cg82616424** [comment]
Thanks for your reply;
I tested it in message mode, with async mode.
srt framework never call my connection callback function when i open heavy log.
but if i close heavy log, it works properly.

**Comment by ethouris** [comment]
What do you mean by "open" and "close" heavy log?

**Comment by cg82616424** [comment]
build option: --enable-heavy-logging (default: OFF in release mode) on/off

**Comment by ethouris** [comment]
Do you have any kinda snippet I could use to check it myself? As I said, I tested it with `--enable-heavy-logging` and the connect callback shows up - in case of failed connect, of course.

**Comment by cg82616424** [comment]
oh I tested it in case of connect successed

**Comment by ethouris** [comment]
Connection callback is not supposed to be called when you succeed. For success you should rely on:

* blocking until success or failure, in blocking mode
* epoll write-ready flag (SRT_EPOLL_OUT) on the connecting socket

**Comment by cg82616424** [comment]
so , documentation  about connect_callback:

> You can also use this mechanism as an alternative method for a single-socket connection in non-blocking mode to trigger an action when the connection process is finished. It is recommended, however, that you use this callback only to collect failure information, as the call will happen in one of the internal SRT threads.

should be modified to clearly confirmed "DO NOT USE srt_connect_callback when successed"?

**Comment by ethouris** [comment]
Yes. We had different plans for that in the beginning, but this has actually increased complications, while what we really wanted from it was a possibility for the application designed in event-style (so, using non-blocking mode) to know that a link got broken and needs to be restored.

**Comment by cg82616424** [comment]
okay, thanks very much, I will close this issue
