### ISSUE TITLE
[Refax] Make CEPoll const-friendly

### ISSUE THREAD

**Issue by maxsharabayko** [Haivision/srt#1847]
`CEPoll` can be more const-friendly.
If `srt::sync::Mutex m_EPollLock;` is marked as `mutable`, some functions could get a const qualifier, e.g. `isready(..)`

SRT version 1.4.2, 1.4.3.

**Comment by ethouris** [comment]
I think this PR could be made more general and check every mutex in the whole project if it can be marked mutable and therefore take advantage of const-capable methods.
