### ISSUE TITLE
How to use SRTO_MAXBW option properly?

### ISSUE THREAD

**Issue by cg82616424** [Haivision/srt#1850]
Hi :
    I write some tools to test srt bandwidth limitation, I used srt like below:
    mode and configs: file mode, with message api option on. use srt epoll and  async mode
    I write a client to send little packet and accept a mass of large packet, main procedure like below:
  
        1. init srt, start epolland connect to server,
        2. enter loop 
            （1）send a little packet(10 bytes) to server
            （2）receive a mass of large packet(about 1.4 kb), I tested req packet num from 1:5 to 1:10
        3. during loop, I try to set SRTO_MAXBW from 1.0 to 5.0(set it on sender side), I read data from srt_bistats, the mbpsRecvRate seem not very accuracy， 
        
![image](https://user-images.githubusercontent.com/6222464/110417153-fca21b80-80cf-11eb-8d10-d85b383fb4a1.png)

**Comment by KvanSteijn** [comment]
Based on the docs you have always above the maxbw extra data for overhead.
