### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by sat62010** [Haivision/srt#1861]
V 1.4.3 is not stable for ubuntu 20.04 (LTS) x64.

tried from 3mbps to 6mbps. with  srt-live-transmit srt://:2000  srt://:2001  -v

video freezes every five sec.

**Comment by ethouris** [comment]
Would you be able to help us? Could you repeat the same test, but with the version from the branch submitted for PR #1844?

**Comment by sat62010** [comment]
ok I tried  https://github.com/ethouris/srt.git

its worse and I received the below message 

Accepted SRT target connection
ERROR: error: recvmsg: Operation not supported: Invalid socket ID
SrtCommon: DESTROYING CONNECTION, closing sockets (rt%232591443 ls%-1)...
SrtCommon: ... done.
SrtCommon: DESTROYING CONNECTION, closing sockets (rt%-1 ls%232591445)...
SrtCommon: ... done.



also I tried  again https://github.com/Haivision/srt.git
with ubuntu 18 and still freezes every 5 sec
I tried with ubuntu server 94G of memory and 32 core still same problem

**Comment by ethouris** [comment]
Wait, I'm kinda confused. You showed a link to the main branch in my repository - this version is completely outdated and I don't know what it contains actually. I was talking about [this version](https://github.com/ethouris/srt/tree/dev-add-sanitizer-fixes1). Did you perform the test with this?

**Comment by sat62010** [comment]
yes I'm trying the below 
https://github.com/ethouris/srt.git

and I receive the below message 

Accepted SRT target connection
ERROR: error: recvmsg: Operation not supported: Invalid socket ID
SrtCommon: DESTROYING CONNECTION, closing sockets (rt%186571424 ls%-1)...
SrtCommon: ... done.
SrtCommon: DESTROYING CONNECTION, closing sockets (rt%-1 ls%186571426)...
SrtCommon: ... done.

**Comment by ethouris** [comment]
If you are trying the below:
https://github.com/ethouris/srt.git

Then this version is of unknown status and unknown changes.

This version:
https://github.com/ethouris/srt/tree/dev-add-sanitizer-fixes1

Should contain fixes on top of 1.4.3-rc.0 version. May I ask you to test this above version?

**Comment by sat62010** [comment]
ok I tried.  https://github.com/ethouris/srt/tree/dev-add-sanitizer-fixes1

I received the below message  during the installation 

 root@ubuntu-s-2vcpu-2gb-intel-nyc3-01:~/srt# sudo make install
[ 40%] Built target srt_virtual
[ 69%] Built target haicrypt_virtual
[ 71%] Built target srt_static
[ 83%] Built target srtsupport_virtual
[ 88%] Built target srt-multiplex
[ 92%] Built target srt-live-transmit
[ 95%] Built target srt_shared
[100%] Built target srt-file-transmit
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/lib/x86_64-linux-gnu/libsrt.so.1.3.0
-- Installing: /usr/lib/x86_64-linux-gnu/libsrt.so.1
-- Installing: /usr/lib/x86_64-linux-gnu/libsrt.so
-- Installing: /usr/lib/x86_64-linux-gnu/libsrt.a
-- Installing: /usr/include/srt/version.h
-- Installing: /usr/include/srt/srt.h
-- Installing: /usr/include/srt/logging_api.h
CMake Error at cmake_install.cmake:90 (file):
  file INSTALL cannot find "/root/srt/srtcore/platform_sys.h": No such file
  or directory.


make: *** [Makefile:72: install] Error 1
root@ubuntu-s-2vcpu-2gb-intel-nyc3-01:~/srt#



I tried. srt-live-transmit  srt://:2000   srt://:2001 -v  still not good  and I got the below message 

23:28:53.642587/srt-live-transm*E:SRT.d: SND-DROPPED 22 packets - lost delaying for 1041ms
23:28:53.672558/srt-live-transm*E:SRT.d: SND-DROPPED 20 packets - lost delaying for 1031ms
23:28:53.702569/srt-live-transm*E:SRT.d: SND-DROPPED 20 packets - lost delaying for 1031ms
23:28:53.742517/srt-live-transm*E:SRT.d: SND-DROPPED 20 packets - lost delaying for 1040ms
23:28:53.772489/srt-live-transm*E:SRT.d: SND-DROPPED 24 packets - lost delaying for 1031ms
23:28:53.802495/srt-live-transm*E:SRT.d: SND-DROPPED 22 packets - lost delaying for 1031ms
23:28:53.842528/srt-live-transm*E:SRT.d: SND-DROPPED 20 packets - lost delaying for 1041ms
23:28:53.872481/srt-live-transm*E:SRT.d: SND-DROPPED 20 packets - lost delaying for 1031ms
23:28:53.902516/srt-live-transm*E:SRT.d: SND-DROPPED 20 packets - lost delaying for 1030ms
23:28:53.942556/srt-live-transm*E:SRT.d: SND-DROPPED 22 packets - lost delaying for 1041ms
23:28:53.972838/srt-live-transm*E:SRT.d: SND-DROPPED 56 packets - lost delaying for 1021ms
23:28:53.973115/srt-live-transm*E:SRT.d: SND-DROPPED 18 packets - lost delaying for 1021ms
23:28:53.973289/srt-live-transm*E:SRT.d: SND-DROPPED 18 packets - lost delaying for 1021ms
23:28:53.973491/srt-live-transm*E:SRT.d: SND-DROPPED 10 packets - lost delaying for 1021ms
23:28:53.973715/srt-live-transm*E:SRT.d: SND-DROPPED 21 packets - lost delaying for 1021ms
23:28:53.973919/srt-live-transm*E:SRT.d: SND-DROPPED 14 packets - lost delaying for 1021ms
23:28:53.974132/srt-live-transm*E:SRT.d: SND-DROPPED 22 packets - lost delaying for 1021ms
23:28:53.974536/srt-live-transm*E:SRT.d: SND-DROPPED 2 packets - lost delaying for 1021ms
23:28:54.004115/srt-live-transm*E:SRT.d: SND-DROPPED 20 packets - lost delaying for 1048ms
23:28:54.042487/srt-live-transm*E:SRT.d: SND-DROPPED 26 packets - lost delaying for 1045ms
23:28:54.072522/srt-live-transm*E:SRT.d: SND-DROPPED 20 packets - lost delaying for 1041ms
23:28:54.102508/srt-live-transm*E:SRT.d: SND-DROPPED 27 packets - lost delaying for 1044ms
23:28:54.142570/srt-live-transm*E:SRT.d: SND-DROPPED 20 packets - lost delaying for 1041ms


you can test it   , its running on 104.131.0.12 for   srt-live-transmit  srt://:2000   srt://:2001

---------------------------------------
and then 
I downloaded the  Source code (zip) for v1.4.3-rc.0  for another ubuntu VM,  worked fine with no issues!

**Comment by ethouris** [comment]
Ok, just in case I tested how this gets installed; I made a temporary directory `/opt/installtest` for that purpose and ran installation, I saw no problems:
```
> make install
[ 13%] Built target srtsupport_virtual
[ 80%] Built target srt_virtual
[ 84%] Built target srt_static
[ 88%] Built target srt-live-transmit
[ 92%] Built target srt_shared
[ 96%] Built target srt-tunnel
[100%] Built target srt-file-transmit
Install the project...
-- Install configuration: "Release"
-- Installing: /opt/installtest/lib64/libsrt.so.1.4.3
-- Installing: /opt/installtest/lib64/libsrt.so.1.4
-- Installing: /opt/installtest/lib64/libsrt.so
-- Installing: /opt/installtest/lib64/libsrt.a
-- Installing: /opt/installtest/include/srt/version.h
-- Installing: /opt/installtest/include/srt/srt.h
-- Installing: /opt/installtest/include/srt/logging_api.h
-- Installing: /opt/installtest/include/srt/access_control.h
-- Installing: /opt/installtest/include/srt/platform_sys.h
-- Installing: /opt/installtest/include/srt/udt.h
-- Installing: /opt/installtest/lib64/pkgconfig/haisrt.pc
-- Installing: /opt/installtest/lib64/pkgconfig/srt.pc
-- Installing: /opt/installtest/bin/srt-live-transmit
-- Up-to-date: /opt/installtest/bin/srt-live-transmit
-- Installing: /opt/installtest/bin/srt-file-transmit
-- Up-to-date: /opt/installtest/bin/srt-file-transmit
-- Installing: /opt/installtest/bin/srt-tunnel
-- Up-to-date: /opt/installtest/bin/srt-tunnel
-- Installing: /opt/installtest/bin/srt-ffplay
```

Are you seeing any more issues with the release candidate or we are now clear?

**Comment by sat62010** [comment]
thanks!  no issues!
