### ISSUE TITLE
android undefined symbol in6addr_any

### ISSUE THREAD

**Issue by adwpc** [Haivision/srt#1890]
Hi, I build libsrt.a by mkall in `docs/Android`
I found undefined symbol `in6addr_any` when using libsrt.a
Please help me

```
nm armeabi-v7a/lib/libsrt.a|grep in6addr_any
         U in6addr_any
```

**Comment by adwpc** [comment]
i tryed three ndk:
android-ndk-r19c/
android-ndk-r20b/
android-ndk-r21e/

**Comment by ethouris** [comment]
On Linux it's in `/lib64/libc.so.6`. Not sure how Android is really laid out, but I'd look for it in system libraries. Might be though that your system configuration doesn't include IPv6.
