### ISSUE TITLE
How to test the ability to reproduce the magic of the SRT protocol in the packet loss environment in the demo video on the official website

### ISSUE THREAD

**Issue by Haoxw** [Haivision/srt#1896]
I am testing SRT version 1.4.2 and I can compile this version on my ARM development version without any problems. The server-side software I am using is Wowza Streaming Engine version 4.8.11. The official documentation from Wowza Software provides an explanation of simulating packet loss to test streams ( MPEG-TS/RTP) in Wowza Streaming Engine", the specific link is "https://www.wowza.com/docs/how-to-simulate-udp-packet-loss- to-test-streams-mpeg-ts-rtp", I tried to follow this document to test whether the SRT protocol would work in a packet loss environment as shown in the official video. However, in practice, I was unable to reproduce the effect in the demo video on the website. Is it possible that I am not testing in the right way? How did the demo video on the official website test out.

**Comment by J-Rogmann** [comment]
Hello @Haoxw 

I'm not sure, if that wowza-internal packet loss generator works also on SRT streams. You could try to generate packet loss with tc (traffic control) and netem (network emulator). I just wrote a small how-to tutorial on using this tool. It's currently in review and will be online maybe later today. I'll publish the link here, once available.

**Comment by Haoxw** [comment]
> 你好@Haoxw
> 
> 我不确定，wowza-internal数据包丢失生成器是否也适用于SRT流。您可以尝试使用tc（流量控制）和netem（网络仿真器）生成数据包丢失。我刚刚写了一个有关如何使用此工具的小指南。目前正在审核中，可能会在今天晚些时候上线。一旦可用，我将在此处发布链接。



> Hello @Haoxw
> 
> I'm not sure, if that wowza-internal packet loss generator works also on SRT streams. You could try to generate packet loss with tc (traffic control) and netem (network emulator). I just wrote a small how-to tutorial on using this tool. It's currently in review and will be online maybe later today. I'll publish the link here, once available.

Hello, have the guidelines written by you passed the review? Can you give me a link, I will test it according to the guide, thank you!

**Comment by mbakholdina** [comment]
I guess here is [the link](https://srtlab.github.io/srt-cookbook/how-to-articles/how-to-simulate-networks-with-netem/) you are looking for.
