### ISSUE TITLE
[BUG] SRTO_FC setter bug

### ISSUE THREAD

**Issue by cg82616424** [Haivision/srt#1898]
**Describe the bug**
SRTO_FC setter maxmum num is 32, no matter what number set

** in 1.4.2 tag, srto_fc setter code like below
`
    case SRTO_FC:
        if (m_bConnecting || m_bConnected)
            throw CUDTException(MJ_NOTSUP, MN_ISCONNECTED, 0);

        if (cast_optval<int>(optval, optlen) < 1)
            throw CUDTException(MJ_NOTSUP, MN_INVAL);

        // Mimimum recv flight flag size is 32 packets
        if (cast_optval<int>(optval) > 32)
            m_iFlightFlagSize = *(int *)optval;
        else
            m_iFlightFlagSize = 32;

        break;`
but in 1.4.3rc0 and master it is:
`
template<>
struct CSrtConfigSetter<SRTO_FC>
{
    static void set(CSrtConfig& co, const void* optval, int optlen)
    {
        int fc = cast_optval<int>(optval, optlen);
        if (fc < 1)
            throw CUDTException(MJ_NOTSUP, MN_INVAL);

        co.iFlightFlagSize = std::min(fc, +co.DEF_MAX_FLIGHT_PKT);
    }
};`

**Comment by cg82616424** [comment]
I think, right way to write this code is to use std::max() ?

**Comment by ethouris** [comment]
Right. Thinking "minimum value should be 32" so it requires std::max. Logic :D. I'll provide quickly a fix.

**Comment by cg82616424** [comment]
thinks for your quick reply, 
another question: 
![image](https://user-images.githubusercontent.com/6222464/112951038-8728e880-916d-11eb-8d10-e14f3e091236.png)
I reviewed the code, SRTO_FC is a number for describe pkt, not byte, I think the documentation here should also be modified. 
from: maximum number of bytes that can be sent without being acknowledged
to: maximum number of packets that can be sent without being acknowledged 

my English is very poor , so I think you had better to modified yourself

**Comment by ethouris** [comment]
Right. I checked this also in the code and this value is definitely expressed in packets, same as the internal value defining the sender and receiver buffer sizes, although for the buffer sizes the value is in the option interface converted to byte units.

**Comment by cg82616424** [comment]
thanks, I will close this issue

**Comment by ethouris** [comment]
No! It will be closed automatically when the fix is merged! :)

**Comment by cg82616424** [comment]
:D
