### ISSUE TITLE
files not received completely

### ISSUE THREAD

**Issue by metairie** [Haivision/srt#192]
Hello 
I'm trying to do a simple srt file transfer (code source master)

Sender 
srt/stransmit file:///tmp/$1 srt://IP_RECEIVER:4000?mode=caller

Receiver
srt/stransmit srt://:4000?mode=caller file:///tmp/$1 

I have multiple issues 
- Sender and Receiver seem to be worked, but the file is not entirely sent 
- Sender send file, receiver never stop, of course file is not entirely sent 

So it does not work at all, What's wrong?

**Comment by nitrat7** [comment]
Hello Stephane,

Long time ago I tested app srt-file-transmit in DEV-branch:

Please have a look here:
https://github.com/Haivision/srt/issues/17#issuecomment-332523428 <https://github.com/Haivision/srt/issues/17#issuecomment-332523428>


Anyway I’m also interested in your findings :-)

Thanks Martin

**Comment by metairie** [comment]
re test... apparently not working. Connection broken in any case ...

**Comment by metairie** [comment]
v1.2 stransmit it does not work
v1.3 srt-file-transmit : WORKS!

**Comment by ethouris** [comment]
Just for info: `stransmit` is for live transmission only.

To avoid confusion, we have decided (this change is already done in `dev` branch) that the filenames are more elaborate and clear: `srt-live-transmit` is for live transmission (`stransmit` is its backward compatibility name), `srt-file-transmit` for file transmission and `srt-multiplex` for sending multiple live streams using one outgoing port (which simulates one connection-channel towards the routers and firewall facilities). Additionally there are `sendfile` and `recvfile` utilities that come from the original UDT library, they are taken with only API changed.

Live transmission predicts that the input data speed IS ALREADY UNDER CONTROL, so sending data faster than the system can push through the network (and reading from file is already way too fast) will result in losing data. Additionally, in live mode the data may be dropped under certain conditions, including when interrupted.

Please note that the file transfer feature has been "restored" only in `dev` branch.
