### ISSUE TITLE
Basic atomic operation support

### ISSUE THREAD

**Issue by quink-black** [Haivision/srt#1920]
There are a lot of variables declared as volatile, but they don't be access via atomic_load/atomic_store. Looks like there is no basic atomic operation support. How to add the support when C++11 is unavailable?
1. Use compiler extensions?
2. Implement SrtAtomic by Mutex?

**Comment by maxsharabayko** [comment]
Good question. This is something we were thinking about as well (see #1813).
The best way would be to find some C++03 library for atomic, if there is any.

The fallback scenario is implementing SrtAtomic by Mutex. Likely this will provide some burden on the performance.

**Comment by maxsharabayko** [comment]
For further reference: PR #1863 suggests atomic support.

**Comment by maxsharabayko** [comment]
Closing as PR #1863 introduces support for `atomic` was merged.
