### ISSUE TITLE
how build srt for ios

### ISSUE THREAD

**Issue by JHCarpediem** [Haivision/srt#1946]
$ make
ld: cannot link directly with dylib/framework, your binary is not an allowed client of /usr/lib/libcrypto.dylib for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libsrt.1.4.3.dylib] Error 1
make[1]: *** [CMakeFiles/srt_shared.dir/all] Error 2
make: *** [all] Error 2

**Comment by ethouris** [comment]
Did you follow the instruction in docs/build_iOS.md ?

**Comment by JHCarpediem** [comment]
> Did you follow the instruction in docs/build_iOS.md ?

yes,i did

**Comment by JHCarpediem** [comment]
> Did you follow the instruction in docs/build_iOS.md ?

Yes

**Comment by ethouris** [comment]
And where has the OpenSSL library been installed?

**Comment by JHCarpediem** [comment]
> And where has the OpenSSL library been installed?

/Users/xxxxx/OpenSSL-for-iPhone

**Comment by ethouris** [comment]
How does the linker command look like then?

**Comment by JHCarpediem** [comment]
> How does the linker command look like then?

Sorry,I can't understand what you mean

**Comment by JHCarpediem** [comment]
> How does the linker command look like then?

Did you mean:"/Users/xxxxx/srt"?

**Comment by ethouris** [comment]
Ok, please do the following:

Collect all logs from making all things described in the instruction from scratch, including installing SSL library, then `configure` script calling cmake and then `make VERBOSE=1`. Then attach this log to the ticket.

**Comment by JHCarpediem** [comment]
> Ok, please do the following:
> 
> Collect all logs from making all things described in the instruction from scratch, including installing SSL library, then `configure` script calling cmake and then `make VERBOSE=1`. Then attach this log to the ticket.

I can't go on at this step:
"./configure --cmake-prefix-path=$IOS_OPENSSL --use-openssl-pc=OFF --cmake-toolchain-file=scripts/iOS.cmake"
-bash: ./configure: No such file or directory

**Comment by JHCarpediem** [comment]
> > Ok, please do the following:
> > Collect all logs from making all things described in the instruction from scratch, including installing SSL library, then `configure` script calling cmake and then `make VERBOSE=1`. Then attach this log to the ticket.
> 
> I can't go on at this step:
> "./configure --cmake-prefix-path=$IOS_OPENSSL --use-openssl-pc=OFF --cmake-toolchain-file=scripts/iOS.cmake"
> -bash: ./configure: No such file or directory

Should I download SRT first?

**Comment by ethouris** [comment]
The `configure` command is mentioned as required step in the instruction, which you have confirmed to have followed.

**Comment by JHCarpediem** [comment]
> The `configure` command is mentioned as required step in the instruction, which you have confirmed to have followed.

I went to this step:
"Building SRT code"
But i can't find  this file "configure" .
SO i got this error "-bash: ./configure: No such file or directory"

**Comment by JHCarpediem** [comment]
> > The `configure` command is mentioned as required step in the instruction, which you have confirmed to have followed.
> 
> I went to this step:
> "Building SRT code"
> But i can't find this file "configure" .
> SO i got this error "-bash: ./configure: No such file or directory"

Should i "cd" to some where and build "configure"?

**Comment by JHCarpediem** [comment]
> The `configure` command is mentioned as required step in the instruction, which you have confirmed to have followed.

Did i miss this instruction? 
"brew install srt"

**Comment by maxsharabayko** [comment]
Just as a side note, if you use `cmake`, you could also do:

```shell
export OPENSSL_ROOT_DIR=$(brew --prefix openssl)
export OPENSSL_LIB_DIR=$(brew --prefix openssl)"/lib"
export OPENSSL_INCLUDE_DIR=$(brew --prefix openssl)"/include"
```

The `configure` script does that for you. It is located in [the root directory](https://github.com/Haivision/srt/blob/master/configure) of SRT project.

**Comment by JHCarpediem** [comment]
> Just as a side note, if you use `cmake`, you could also do:
> 
> ```shell
> export OPENSSL_ROOT_DIR=$(brew --prefix openssl)
> export OPENSSL_LIB_DIR=$(brew --prefix openssl)"/lib"
> export OPENSSL_INCLUDE_DIR=$(brew --prefix openssl)"/include"
> ```
> 
> The `configure` script does that for you. It is located in [the root directory](https://github.com/Haivision/srt/blob/master/configure) of SRT project.

thank
