### ISSUE TITLE
[FR]Can support connection migrate? Or hot restart?

### ISSUE THREAD

**Issue by xiaozhihong** [Haivision/srt#1961]
Hi, We using SRT to build a high availability system to deliver MPEG-TS stream, work 7 x 24 hours.
We have two problems. 
1. The SRT publisher maybe change the network, and can libsrt support connection migrate like QUIC?
2. We update srt server, but we don't want to broken all the connections. Is there any way to restart srt server gracefully? For example, migrate all connection context into new srt-server,  or any other better function?

Thanks a lot.

**Comment by ethouris** [comment]
You can use a bonding group of type "broadcast" and simply use only one connection within the group in the beginning. Then, if you need another network pathway to be used, just add a new connection to the group, then close the first one.

Note that you will have a continuous stream only in case when you do soft handoff (both pathways are valid for at least a short time), but as far as I understand from the docs, same applies to QUIC.

**Comment by xiaozhihong** [comment]
> You can use a bonding group of type "broadcast" and simply use only one connection within the group in the beginning. Then, if you need another network pathway to be used, just add a new connection to the group, then close the first one.
> 
> Note that you will have a continuous stream only in case when you do soft handoff (both pathways are valid for at least a short time), but as far as I understand from the docs, same applies to QUIC.

Thanks for your reply, it's a good idea, I will try it later.
