### ISSUE TITLE
UDP packet sent via SRT code not reaching server

### ISSUE THREAD

**Issue by oviano** [Haivision/srt#1970]
Something weird has started happening, and I'm a bit stuck with it.

Server - based in Istanbul, on an LTE connection. Listens on port 8090. Router set up to forward UDP to port 8090. Been working fine for months.

Recently, with no code changes made, it stopped accepting/seeing incoming connections from clients. Tried from home LAN, from 4G, it makes no difference.

Enabled heavy logging on both sides. Client attempts to send handshake/connect packet, but doesn't get a response, so keeps trying. Server log shows no evidence of attempted connection, just silence.

Installed PacketSender utility. This is a simple utility that allows manually sending packets to a destination, and can also run as a server. So I sent UDP packets containing junk to same server + port, and these *did* show up in the heavy server log. Obviously, they were rejected. This shows there is nothing blocking the path. This was from the same client on the same network, sending the packet to the same server:port.

Installed Wireshark. Captured packets sent by both SRT, and by PacketSender utility.

Packet sent by SRT code in my client app:

Frame 108: 106 bytes on wire (848 bits), 106 bytes captured (848 bits) on interface en0, id 0
    Interface id: 0 (en0)
        Interface name: en0
        Interface description: Wi-Fi
    Encapsulation type: Ethernet (1)
    Arrival Time: Apr 27, 2021 11:39:25.158516000 BST
    [Time shift for this packet: 0.000000000 seconds]
    Epoch Time: 1619519965.158516000 seconds
    [Time delta from previous captured frame: 0.086529000 seconds]
    [Time delta from previous displayed frame: 0.086529000 seconds]
    [Time since reference or first frame: 5.687183000 seconds]
    Frame Number: 108
    Frame Length: 106 bytes (848 bits)
    Capture Length: 106 bytes (848 bits)
    [Frame is marked: False]
    [Frame is ignored: False]
    [Protocols in frame: eth:ethertype:ip:udp:data]
    [Coloring Rule Name: UDP]
    [Coloring Rule String: udp]
Ethernet II, Src: Apple_07:6e:0e (f8:ff:c2:07:6e:0e), Dst: DrayTek_08:3b:00 (14:49:bc:08:3b:00)
    Destination: DrayTek_08:3b:00 (14:49:bc:08:3b:00)
        Address: DrayTek_08:3b:00 (14:49:bc:08:3b:00)
        .... ..0. .... .... .... .... = LG bit: Globally unique address (factory default)
        .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
    Source: Apple_07:6e:0e (f8:ff:c2:07:6e:0e)
        Address: Apple_07:6e:0e (f8:ff:c2:07:6e:0e)
        .... ..0. .... .... .... .... = LG bit: Globally unique address (factory default)
        .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
    Type: IPv4 (0x0800)
Internet Protocol Version 4, Src: 192.168.1.129, Dst: 5.11.131.XXX
    0100 .... = Version: 4
    .... 0101 = Header Length: 20 bytes (5)
    Differentiated Services Field: 0x00 (DSCP: CS0, ECN: Not-ECT)
        0000 00.. = Differentiated Services Codepoint: Default (0)
        .... ..00 = Explicit Congestion Notification: Not ECN-Capable Transport (0)
    Total Length: 92
    Identification: 0x8315 (33557)
    Flags: 0x00
        0... .... = Reserved bit: Not set
        .0.. .... = Don't fragment: Not set
        ..0. .... = More fragments: Not set
    Fragment Offset: 0
    Time to Live: 64
    Protocol: UDP (17)
    Header Checksum: 0xac74 [validation disabled]
    [Header checksum status: Unverified]
    Source Address: 192.168.1.129
    Destination Address: 5.11.131.XXX
User Datagram Protocol, Src Port: 57257, Dst Port: 8090
    Source Port: 57257
    Destination Port: 8090
    Length: 72
    Checksum: 0xa272 [unverified]
    [Checksum Status: Unverified]
    [Stream index: 19]
    [Timestamps]
        [Time since first frame: 0.517841000 seconds]
        [Time since previous frame: 0.260104000 seconds]
    UDP payload (64 bytes)
Data (64 bytes)
    Data: 80000000000000000007e7190000000000000004000000020a33463c000005dc00004000…
    [Length: 64]

Packet sent via PacketSender, manually by me:

Manually sent:

Frame 18: 52 bytes on wire (416 bits), 52 bytes captured (416 bits) on interface en0, id 0
    Interface id: 0 (en0)
        Interface name: en0
        Interface description: Wi-Fi
    Encapsulation type: Ethernet (1)
    Arrival Time: Apr 27, 2021 11:40:45.471069000 BST
    [Time shift for this packet: 0.000000000 seconds]
    Epoch Time: 1619520045.471069000 seconds
    [Time delta from previous captured frame: 0.095868000 seconds]
    [Time delta from previous displayed frame: 0.095868000 seconds]
    [Time since reference or first frame: 2.025972000 seconds]
    Frame Number: 18
    Frame Length: 52 bytes (416 bits)
    Capture Length: 52 bytes (416 bits)
    [Frame is marked: False]
    [Frame is ignored: False]
    [Protocols in frame: eth:ethertype:ip:udp:data]
    [Coloring Rule Name: UDP]
    [Coloring Rule String: udp]
Ethernet II, Src: Apple_07:6e:0e (f8:ff:c2:07:6e:0e), Dst: DrayTek_08:3b:00 (14:49:bc:08:3b:00)
    Destination: DrayTek_08:3b:00 (14:49:bc:08:3b:00)
        Address: DrayTek_08:3b:00 (14:49:bc:08:3b:00)
        .... ..0. .... .... .... .... = LG bit: Globally unique address (factory default)
        .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
    Source: Apple_07:6e:0e (f8:ff:c2:07:6e:0e)
        Address: Apple_07:6e:0e (f8:ff:c2:07:6e:0e)
        .... ..0. .... .... .... .... = LG bit: Globally unique address (factory default)
        .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
    Type: IPv4 (0x0800)
Internet Protocol Version 4, Src: 192.168.1.129, Dst: 5.11.131.XXX
    0100 .... = Version: 4
    .... 0101 = Header Length: 20 bytes (5)
    Differentiated Services Field: 0x00 (DSCP: CS0, ECN: Not-ECT)
        0000 00.. = Differentiated Services Codepoint: Default (0)
        .... ..00 = Explicit Congestion Notification: Not ECN-Capable Transport (0)
    Total Length: 38
    Identification: 0xcb18 (51992)
    Flags: 0x00
        0... .... = Reserved bit: Not set
        .0.. .... = Don't fragment: Not set
        ..0. .... = More fragments: Not set
    Fragment Offset: 0
    Time to Live: 64
    Protocol: UDP (17)
    Header Checksum: 0x64a7 [validation disabled]
    [Header checksum status: Unverified]
    Source Address: 192.168.1.129
    Destination Address: 5.11.131.XXX
User Datagram Protocol, Src Port: 52410, Dst Port: 8090
    Source Port: 52410
    Destination Port: 8090
    Length: 18
    Checksum: 0xc86d [unverified]
    [Checksum Status: Unverified]
    [Stream index: 6]
    [Timestamps]
        [Time since first frame: 0.000000000 seconds]
        [Time since previous frame: 0.000000000 seconds]
    UDP payload (10 bytes)
Data (10 bytes)
    Data: 00000000000000000000
    [Length: 10]

I can't understand why the SRT one doesn't get through? Could something like DPI be interfering with it? If the ISP is analysing UDP packets in this way (pure speculation), is there anything I can do about it?

**Comment by maxsharabayko** [comment]
Hard to say what's going on. I would suggest trying [`srt-xtransmit`](https://github.com/maxsharabayko/srt-xtransmit) utility.
Maybe also trying different ports where possible.

### 1. Generating dummy payload and sending via pure UDP:

```shell
srt-xtransmit generate udp://target_ip:target_port --sendrate 5Mbps --duration 30s -v
```

### 2. Generating dummy payload and sending via SRT:

```shell
srt-xtransmit generate srt://target_ip:target_port --sendrate 5Mbps --duration 30s -v
```

### Receiver

```
srt-xtransmit receive udp://:target_port -v
```

or `srt://:target_port` for SRT.

**Comment by oviano** [comment]
Thanks for the tips, I'll try those.

In the meantime I managed to grab the packet data via Wireshark and use the same data in my PacketSender test and reproduced the issue of the server never seeing the packet.

Then I changed one of the bytes at the start of the packet data (one of the header bytes I guess), and by changing a single digit this meant the packet was received by the server (rejected of course).

Very strange.

**Comment by oviano** [comment]
So, check this out.

I can "fix" the issue by adding these lines after at the end of CPacket::toNL()

	// HACK!
	uint8_t* pp = (uint8_t*)((uint32_t*)m_nHeader);
	*pp = *pp + 1;

And these lines at the start of CPacket::toHL()

	// HACK!
	uint8_t* pp = (uint8_t*)((uint32_t*)m_nHeader);
	*pp = *pp - 1;

Also, using CPacket::toHL() at the bottom of CChannel::recvfrom() instead of the duplicated code.

Can only assume something is identifying the protocol as being SRT/UDT and blocking it?

**Comment by oviano** [comment]
> Hard to say what's going on. I would suggest trying [`srt-xtransmit`](https://github.com/maxsharabayko/srt-xtransmit) utility.
> Maybe also trying different ports where possible.
> 
> ### 1. Generating dummy payload and sending via pure UDP:
> ```shell
> srt-xtransmit generate udp://target_ip:target_port --sendrate 5Mbps --duration 30s -v
> ```
> 
> ### 2. Generating dummy payload and sending via SRT:
> ```shell
> srt-xtransmit generate srt://target_ip:target_port --sendrate 5Mbps --duration 30s -v
> ```
> 
> ### Receiver
> ```
> srt-xtransmit receive udp://:target_port -v
> ```
> 
> or `srt://:target_port` for SRT.

Are there any Windows binaries anywhere srt-xtransmit?

**Comment by oviano** [comment]
Interestingly (or not!) Wireshark is able to identify SRT traffic using its heuristics. If I mess with the header (in my latest test, I just invert all the bits in the four int32s) then Wireshark just identifies it as UDP and the data gets through to my server.

So maybe something on the route is using DPI to detect known protocols like SRT, and preventing them. I have no idea why it would be doing that!

**Comment by maxsharabayko** [comment]
I guess the conclusion here is that there is someone or something in the network detecting UDT or SRT traffic and limiting it.
Likely only some probing of different paths could provide any further hint on the actor.

In any case, nothing to do on SRT side. Closing.
Do not hesitate to reopen if required.

**Comment by oviano** [comment]
Maybe an optional “DISGUISE” flag that would just jumble up the header in such a way that it could no longer be considered a valid UDT/SRT packet, kind of like what I did but with more thought?

Perhaps also be able to pad packets to their maximum size. At a guess if you were designing a DPI for UDT/SRT you’d take the size of the handshake packets into account.

Happy for this to be closed and serve as a reference in case anybody else comes across something like this in future.
