### ISSUE TITLE
How to distinguish between publish and play request 

### ISSUE THREAD

**Issue by maxlapshin** [Haivision/srt#1978]
I want to write an SRT server using libsrt that can accept publishing video and playing from it via SRT.

I suppose that there will one port for all streams (in the same manner as with HTTP).

I cannot find guidelines for proper parsing streamid option for distinguishing between publishing and playing.

According to what I could find, seems that `r` should stand for stream name and sometimes we can see `m=publish` for publishing.

```
ffmpeg -re -i input.ts -c copy -y -f mpegts 'srt://localhost:9998?pkt_size=1316&streamid=#!::r=STREAM_NAME,m=publish'
```

Is it a well known standard?

How can I tell to server that I want to play?

**Comment by ethouris** [comment]
Note one important part here that the streamid feature is something that the application sets in the caller and it is readable by the listener. This means that the caller (client) defines `m=publish` if the client is going to send the stream to the listener (server) and `m=request` if it's going to receive a stream.

I'm not sure exactly what you mean by "I want to play". If it's that you might want to run a video player application and read and play the stream, then yes, according to the SRT AccessControl standard you should use `m=request`, which should be also default if `m` key isn't specified.

**Comment by maxlapshin** [comment]
Yes, this is exactly what I was looking for.

When player connects to server and tells that he wants to play some video from it, so it must send `m=request`.

Thanks. Couldn't find it in docs.

**Comment by maxsharabayko** [comment]
For further reference see the [SRT Access Control Guideline](https://github.com/Haivision/srt/blob/master/docs/features/access-control.md#standard-keys).
