### ISSUE TITLE
[BUG] sender/listener with passphrase crashes (SIGSEGV) on incoming call with no passphrase

### ISSUE THREAD

**Issue by jeandube** [Haivision/srt#1979]
Makito X4 encoder (SRT 1.4.2) caller/sender w/passphrase -> HMG listener/receiver no passphrase

SRTO_ENFORCEDENCRYPTION set (default) on caller/sender.

caller fails (REJECT from HS) and reconnect every 40ms multiple times (> 30 secs) before crashing (SIGSEGV).

Here a backtrace extracted from the attached log:

`[30/04/2021 10:09:59.843,sessmgrd:24257-619,CRITI,LIBMXTOOLS] _SIGSEVSignalHandler(threadcheck.c:172): SEGMENTATION FAULT (11) in thread "SRT:RcvQ:w13667"!!!
[30/04/2021 10:09:59.851,sessmgrd:24257-620,CRITI,LIBMXTOOLS] DumpBackTraceInfo(threadcheck.c:149): BACKTRACE INFO:
[30/04/2021 10:09:59.851,sessmgrd:24257-621,CRITI,LIBMXTOOLS] DumpBackTraceInfo(threadcheck.c:153): BT#1/9: /usr/lib/libmxtools.so(DumpBackTraceInfo+0x18) [0x7f909c8aec]
[30/04/2021 10:09:59.851,sessmgrd:24257-622,CRITI,LIBMXTOOLS] DumpBackTraceInfo(threadcheck.c:153): BT#2/9: /usr/lib/libmxtools.so(_SIGSEVSignalHandler+0xdc) [0x7f909c8d28]
[30/04/2021 10:09:59.851,sessmgrd:24257-623,CRITI,LIBMXTOOLS] DumpBackTraceInfo(threadcheck.c:153): BT#3/9: linux-vdso.so.1(__kernel_rt_sigreturn+0) [0x7f90ad266c]
[30/04/2021 10:09:59.851,sessmgrd:24257-624,CRITI,LIBMXTOOLS] DumpBackTraceInfo(threadcheck.c:153): BT#4/9: /usr/lib/libsrt.so.1(_ZNK14CCryptoControl17getKmMsg_needSendEmb+0x98) [0x7f907efd08]
[30/04/2021 10:09:59.851,sessmgrd:24257-625,CRITI,LIBMXTOOLS] DumpBackTraceInfo(threadcheck.c:153): BT#5/9: /usr/lib/libsrt.so.1(_ZN4CUDT18createSrtHandshakeEiiPKjmR7CPacketR10CHandShake+0xb4c) [0x7f907d57bc]
[30/04/2021 10:09:59.851,sessmgrd:24257-626,CRITI,LIBMXTOOLS] DumpBackTraceInfo(threadcheck.c:153): BT#6/9: /usr/lib/libsrt.so.1(_ZN4CUDT26processAsyncConnectRequestE11EReadStatus14EConnectStatusRK7CPacketRK12sockaddr_any+0x2bc) [0x7f907dc228]
[30/04/2021 10:09:59.851,sessmgrd:24257-627,CRITI,LIBMXTOOLS] DumpBackTraceInfo(threadcheck.c:153): BT#7/9: /usr/lib/libsrt.so.1(_ZN16CRendezvousQueue16updateConnStatusE11EReadStatus14EConnectStatusRK7CPacket+0x450) [0x7f90828f2c]
[30/04/2021 10:09:59.851,sessmgrd:24257-628,CRITI,LIBMXTOOLS] DumpBackTraceInfo(threadcheck.c:153): BT#8/9: /usr/lib/libsrt.so.1(_ZN9CRcvQueue6workerEPv+0x3d4) [0x7f90829c0c]
[30/04/2021 10:09:59.851,sessmgrd:24257-629,CRITI,LIBMXTOOLS] DumpBackTraceInfo(threadcheck.c:153): BT#9/9: /lib/libpthread.so.0(+0x6fd8) [0x7f90a82fd8]
`
[sys-snapshot-4.txt](https://github.com/Haivision/srt/files/6414746/sys-snapshot-4.txt)

**Comment by jeandube** [comment]
Reported in product ticket NKE-1189

**Comment by ethouris** [comment]
I suspect deleted object at `m_pCryptoControl` referred from `CUDT::createSrtHandshake`. There are still some PR related to TSAN findings that have been put aside.

**Comment by jlsantiago0** [comment]
This issue is reproducible in Kraken and Hub and is a denial of service vulnerability. Will this fixed in the upcoming release?

**Comment by ethouris** [comment]
Which version do these products use?

**Comment by jlsantiago0** [comment]
Currently v1.4.3.

**Comment by jeandube** [comment]
Something similar in NKE-1252: caller sender w/passphrase, listener/receiver without.
```
Thread 1962 "SRT:RcvQ:w384" received signal SIGSEGV, Segmentation fault.
[Switching to LWP 26467]
0x0000007ff7cfc7d0 in CCryptoControl::getKmMsg_needSend (this=0x0, ki=0, runtime=false)
    at /home/jdube/sandbox/makito2_project/components/vendors/haisrt/srt.git/srtcore/crypto.h:152
152     /home/jdube/sandbox/makito2_project/components/vendors/haisrt/srt.git/srtcore/crypto.h: No such file or directory.
(gdb) bt
#0  0x0000007ff7cfc7d0 in CCryptoControl::getKmMsg_needSend (this=0x0, ki=0, runtime=false)
    at /home/jdube/sandbox/makito2_project/components/vendors/haisrt/srt.git/srtcore/crypto.h:152
#1  0x0000007ff7ce16c0 in srt::CUDT::createSrtHandshake (this=0x7f20000b50, srths_cmd=1, srtkm_cmd=3, kmdata=0x0, kmdata_wordsize=0, w_pkt=..., w_hs=...)
    at /home/jdube/sandbox/makito2_project/components/vendors/haisrt/srt.git/srtcore/core.cpp:1743
#2  0x0000007ff7ce7fdc in srt::CUDT::processAsyncConnectRequest (this=0x7f20000b50, rst=RST_OK, cst=CONN_CONTINUE, response=..., serv_addr=...)
    at /home/jdube/sandbox/makito2_project/components/vendors/haisrt/srt.git/srtcore/core.cpp:3807
#3  0x0000007ff7d3ab34 in srt::CRendezvousQueue::updateConnStatus (this=0x7f20015a70, rst=RST_OK, cst=CONN_CONTINUE, pktIn=...)
    at /home/jdube/sandbox/makito2_project/components/vendors/haisrt/srt.git/srtcore/queue.cpp:950
#4  0x0000007ff7d3bc40 in srt::CRcvQueue::worker (param=0x7f20007600) at /home/jdube/sandbox/makito2_project/components/vendors/haisrt/srt.git/srtcore/queue.cpp:1313
#5  0x0000007ff7facfd8 in ?? () from /lib/libpthread.so.0
#6  0x0000007f39e0a228 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb)
```

**Comment by maxsharabayko** [comment]
Although there still remain issues around the `CCryptoControl` instance, there was a related fix and refactoring in #1919 and #1993.
I am trying to reproduce the issue with testing applications. And was not able to get crashes so far.
However, from the code itself, the `CUDT::m_pCryptoControl` is not always protected with `m_ConnectionLock`.

@jeandube @jlsantiago0 Could you check if the issue is reproducible with the latest master?

**Comment by jeandube** [comment]
@maxsharabayko I found that the issue was caused (triggered) by 2 parallel reconnecting loops, running in different threads. One of them closing the SRT socket before recreating a new one. Our app re-resolve the peer DNS name upon each reconnections in case something changes in the network. This has been in place for a while but another reconnection mechanism in a module wrapping libsrt is also reconnecting (using last IP address used) when connection fails or is disconnects. This last mechanism has been significantly modified to support group link reconnection and I suspect this what triggered the race condition of our poor architecture. I also suspect a change at some point of the default setting of ENFORCEDENCRYPTION for a caller. Both reconnection mechanism were supposed to be tame to a 5 seconds period but when tested with a non-responding peer with a connection timeout (SRTO_CONNTIMEO) of 8 secs a bad implementation was not detected. Connection rejection because of encryption misconfiguration was faster and caused a reconnecting loop period of ~40ms, which increased the probability to hit  an unprotected zone. Our fix (or workaround if you prefer) was to have the DNS resolution part to just set the new address in the module handling the reconnection loop, no longer closing and recreating the socket. Thanks to ABI backward compatibility I can try to reproduce by copying latest master libsrt.so on the product build showing the issue (I assume master is ABI compatible with 1.4.3).

**Comment by jeandube** [comment]
@maxsharabayko I found I was having the issue with libsrt master with PR#1588 (commit e2a00aa, May 28th)  which includes the 2 PRs you mentioned above that were merged in master on May 11th and 12th. Unless you think something that worth testing was added beyond that commit, testing with master with not add much.

**Comment by maxsharabayko** [comment]
So far I was not successful in reproducing the issue on my side.

The crash can happen if the following three conditions are true for the caller:
- CryptoControl is either not yet created or is already destroyed (by `srt_close()`).
- A socket is in the `CRendezvousQueue`.
- `CUDT::m_ConnReq.m_extension` is true (HS Induction response was received by the caller).
- `SRTO_PASSPHRASE` is set on the socket.

Those state changes are protected by `CUDT::m_ConnectionLock`. `srt_close(..)` first removes the socket from the `CRendezvousQueue` and then destroys the `CryptoControl`.
Because of the condition `if (m_bConnecting)`, the described crash could happen before PR #1919. But after the fix, I don't see where can it happen.
So with PR #2075 if it happens, we will see an error message and do not crash. Thus can proceed with gathering further information on the very reason for the situation.

```c++
CUDT::closeInternal(..) {
    // remove this socket from the snd queue
    if (m_bConnected)
        m_pSndQueue->m_pSndUList->remove(this);
    // ...
    m_bClosing = true;
    ScopedLock connectguard(m_ConnectionLock);
    
    if (m_bConnecting)
        m_pRcvQueue->removeConnector(m_SocketID);
    // ...
    
    if (m_bConnected) {
        // ...
        m_bConnected = false;
    }
    
    // waiting all send and recv calls to stop
    ScopedLock sendguard(m_SendLock);
    ScopedLock recvguard(m_RecvLock);

    // Locking m_RcvBufferLock to protect calling to m_pCryptoControl->decrypt((packet))
    // from the processData(...) function while resetting Crypto Control.
    enterCS(m_RcvBufferLock);
    if (m_pCryptoControl)
        m_pCryptoControl->close();

    m_pCryptoControl.reset();
    leaveCS(m_RcvBufferLock);

    m_bOpened = false;
}
```

**Comment by maxsharabayko** [comment]
The issue has been reproduced. Below is the diagram of how it can happen.
Before PR #2075 SRT was crashing on dereferencing a NULL pointer. After the PR - showing an IPE message.
Three main steps are designated in the comments.

```
         THREAD 1                                   THREAD 2
      CRcvQueue::worker()                           srt_close(..) {
           |                                            CUDT::closeInternal(..) {
    worker_RetrieveUnit()                                   // remove this socket from the snd queue
           |                                                if (m_bConnected)
HS Induction Response                                           m_pSndQueue->m_pSndUList->remove(this);
           v                                                // ...
worker_ProcessAddressedPacket(..) {                 
       ScopedLock cg(m_ConnectionLock);                     m_bClosing = true;
       createCrypter();                                     /// !!! Waiting for m_ConnectionLock
       return CONN_CONTINUE;                                
   }                               -- m_ConnectionLock -->  ScopedLock cg(m_ConnectionLock);
            |                                               .                 
            v                                               .                 
m_pRendezvousQueue->updateConnStatus(..) {                  .                 
    vector<> toProcess;                                     .                 
    qualifyToHandle(vector& toProces) {                     .        
        ScopedLock vg(m_RIDListLock);                       .             
        list m_lRendezvousID --CUDT*--> toProcess;          .             
    }                                                       .
    // 1. Now toProcess contains CUDT socket.               .
    for (auto entry : toProces) {                           // 2. The socket will be removed from the connection queue.
        processAsyncConnectRequest(..) {                    // And its CryptoControl will be destroyed.
            // Waiting for m_ConnectionLock                 if (m_bConnecting)
            .                                                   m_pRcvQueue->removeConnector(m_SocketID);
            .                                               // ...
            .                                               if (m_pCryptoControl) {
            .                                                   m_pCryptoControl->close(); // removed CryptoControl
            .                                                   m_pCryptoControl.reset();
            .                                                   leaveCS(m_RcvBufferLock);
            .                                                
            .                                                   m_bOpened = false;
            .                                              }
            .                                                             
            .                                                                   
            // 3. Acquired m_ConnectionLock. Now creating a handshake,
            // but m_pCryptoControl is already NULL.
            ScopedLock cg(m_ConnectionLock);
            if (cst != CONN_RENDEZVOUS) {
                CUDT::createSrtHandshake(..)                        
                    ... *m_pCryptoControl == *NULL // CRASH!!!
            }                                     
       }                                        
    }
}
```

**Comment by maxsharabayko** [comment]
A reproduction test. Connect to a listener without a passphrase.
Also `closeInternal(..)` needs to be slowed a bit to trigger the above situation.
E.g. place a log between `m_bClosing = true;` and `ScopedLock cg(m_ConnectionLock);` and before `m_pRcvQueue->removeConnector(m_SocketID);`

```c++
TEST_F(TestConnectionTimeout, CloseWhileConnecting) {

    const int yes = 1;
    const int no = 0;

    m_sa.sin_port = htons(4200);
    const sockaddr* psa = reinterpret_cast<const sockaddr*>(&m_sa);

    // Create another client

    const SRTSOCKET client_sock = srt_create_socket();
    ASSERT_GT(client_sock, 0);    // socket_id should be > 0

    srt_setloglevel(LOG_NOTICE);

    ASSERT_EQ(srt_setsockopt(client_sock, 0, SRTO_RCVSYN, &no, sizeof no), SRT_SUCCESS); // for async connect
    ASSERT_EQ(srt_setsockopt(client_sock, 0, SRTO_SNDSYN, &no, sizeof no), SRT_SUCCESS); // for async connect

    const char* pwd = "1234567890";
    ASSERT_EQ(srt_setsockopt(client_sock, 0, SRTO_PASSPHRASE, pwd, 10), SRT_SUCCESS); // for async connect

    // Set connection timeout to 500 ms to reduce the test execution time
    const int connection_timeout_ms = 300;
    EXPECT_EQ(srt_setsockopt(client_sock, 0, SRTO_CONNTIMEO, &connection_timeout_ms, sizeof connection_timeout_ms), SRT_SUCCESS);

    const int pollid = srt_epoll_create();
    ASSERT_GE(pollid, 0);
    const int epoll_out = SRT_EPOLL_OUT | SRT_EPOLL_ERR;
    ASSERT_NE(srt_epoll_add_usock(pollid, client_sock, &epoll_out), SRT_ERROR);


    auto fut = std::async([](SRTSOCKET s) { std::cout << "srt_close()\n"; srt_close(s); }, client_sock);
    ASSERT_NE(srt_connect(client_sock, psa, sizeof m_sa), SRT_ERROR);
    fut.wait();

    this_thread::sleep_for(5s);

    cout << "srt_close()\n";
    EXPECT_EQ(srt_epoll_remove_usock(pollid, client_sock), SRT_SUCCESS);
    EXPECT_EQ(srt_close(client_sock), SRT_SUCCESS);
    (void)srt_epoll_release(pollid);
}
```
