### ISSUE TITLE
How to send stream related metadata with succesfull response?

### ISSUE THREAD

**Issue by maxlapshin** [Haivision/srt#1981]
Player connects to server via SRT and asks to send stream.

Server is going to send it and wants to send some metadata with this stream.

If it was HTTP (SIP, SMTP or many other protocols), I can use response headers.  Does SRT has anything like this?  Is there any way to attach some metadata to the beginning of stream for receiver to get it with content?

**Comment by oviano** [comment]
You could have a parallel TCP connection for this sort of thing. In my project I have a "control" connection, using TCP, and a "stream" connection which uses SRT.

Because SRT is built on UDP, you can use the same port number for both types of connection.
