### ISSUE TITLE
Is anyone ported SRT to Java?

### ISSUE THREAD

**Issue by eneskuluk** [Haivision/srt#2019]
Is anyone ported SRT to Java?
I think it needs to be done via JNI, my question is if anyone is willing to share the ported SRT?

**Comment by maxsharabayko** [comment]
Hi @eneskuluk 
I doubt that there is a native port of SRT to Java.
The best way to go might be using [JNA](https://github.com/java-native-access/jna).

Also, [SWIG](http://swig.org/) seems to support Java. @lewk2 and I experimented with it a while ago. Here is the draft interface description for SRT in case you take the path: [srt.i](https://github.com/maxsharabayko/srt/blob/develop/swig/srtcore/srt.i).

Might be worth trying to ask the question in the `#development` channel on [Slack](https://srtalliance.slack.com). [Link to join.](https://slackin-srtalliance.azurewebsites.net/)
