### ISSUE TITLE
Compiling for Android

### ISSUE THREAD

**Issue by karlbrowns** [Haivision/srt#2022]
I'm trying to build this for Android and was pleasantly surprised to find the build-android script.  Unfortunately, I cannot get it to build.  I've got my Ubuntu VM and I've updated cmake on it, and installed Android Studio and the NDK.  I run the command line as suggested, pointing it to the NDK and it builds openssl and that seems to work, but then runs into a problem when running mksrt - the error message seems to be:
CMake Error at /home/simon/Downloads/cmake-3.20.2-linux-x86_64/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY
  OPENSSL_INCLUDE_DIR)

Now I've tried to point OPENSSL_ROOT_DIR to the installed openssl on my VM, but I suspect it wants to be pointed at the version that it's just build for Android, and I've also tried pointing it at that, but to no avail.

Can anyone help?
Thanks.

**Comment by maxsharabayko** [comment]
Android build scripts are maintained mainly by the community. Recent contributors are @sergeiignatov, @techmaticsnz.
Although your problem looks related to pointing to a proper version of OpenSSL.

Might be worth trying to look for help in the `#development` channel on [Slack](https://srtalliance.slack.com). [Link to join.](https://slackin-srtalliance.azurewebsites.net/)

**Comment by sergeiignatov** [comment]
I tried cmake 3.20.3 and something really goes wrong with it. 

Please stick to Ubuntu 20.4 LTS and cmake version 3.16.3 for now.
