### ISSUE TITLE
[BUG] srt-live-transmit sometimes introduces extreme burstiness in UDP playout

### ISSUE THREAD

**Issue by nhaleft** [Haivision/srt#2023]
**Describe the bug**
Under certain non-optimal conditions, srt-live-transmit introduces huge burstiness when playing out packets using srt-live-transmit's implementation of UDT.

**To Reproduce**
We have unfortunately not yet figured out how to reproduce this bug.

**Expected behavior**
I expect the UDP playout to match the traffic pattern of SRT, to a degree. Unfortunately we do not have access to the traffic pattern of the UDP stream being sent into srt-live-transmit.

**Screenshots**
<img width="1536" alt="image" src="https://user-images.githubusercontent.com/17421926/119728953-125aed80-be42-11eb-88ec-2ef1558df924.png">
The orange is SRT traffic coming into srt-live-transmit, and the green is UDP coming out of srt-live-transmit. Unfortunately, I only have access to this graph, and not the actual pcap file.

**Desktop (please provide the following information):**
 - OS: CentOS 7.6.1810
 - SRT Version / commit ID: v1.4.2

**Additional context**
The incoming SRT stream was provided by a third party, and we are working with them to recreate the stream so we can update this issue with more info, specifically a debug log and a pcap file. We do, however, have stat logs:
```
======= SRT STATS: sid=284006926
TIME         NOW: Tue Mar 16 21:06:51 2021
PACKETS     SENT:           0  RECEIVED:          9811
LOST PKT    SENT:           0  RECEIVED:             0
REXMIT      SENT:           0  RECEIVED:             0
DROP PKT    SENT:           0  RECEIVED:             0
FILTER EXTRA  TX:           0        RX:             0
FILTER RX  SUPPL:           0  RX  LOSS:             0
RATE     SENDING:           0  RECEIVING:      9.17798
BELATED RECEIVED:           0  AVG TIME:             0
REORDER DISTANCE:           0
WINDOW      FLOW:        8192  CONGESTION:        8192  FLIGHT:           0
LINK         RTT:    63.444ms  BANDWIDTH:  232.872Mb/s
BUFFERLEFT:  SND:    12288000  RCV:           11659500
```
This bug was reproduced on multiple machines, however each time the same source was used, as the calling srt-live-transmit process was provided by a third party.

**Comment by ethouris** [comment]
Would you be able to try out if `srt-test-live` gives the same result?

**Comment by maxsharabayko** [comment]
@nhaleft
Please try running `srt-live-transmit` with `-buffering 1` command-line option to disable buffering of incoming packets.
See also [command-line options](https://github.com/Haivision/srt/blob/master/docs/apps/srt-live-transmit.md#command-line-options).
