### ISSUE TITLE
SRT obs linux Mint

### ISSUE THREAD

**Issue by dbbrito** [Haivision/srt#2036]
Friends, I installed the obs on linux Mint but I can't send the videos through the larix app to the obs via srt, I have already released the ports on the firewall and performed the installation as below, on windows just install the obs and it works right away, but in the linux I'm not succeeding, can someone help me please.

cd /home/dan/ffmpeg_sources
git clone --depth 1 https://github.com/Haivision/srt.git
cd ~/ffmpeg_sources/srt
PKG_CONFIG_PATH="$HOME/ffmpeg_build/lib/pkgconfig" cmake -G "Unix Makefiles" -DCMAKE_INSTALL_BINDIR="$HOME/ffmpeg_build/bin" -DCMAKE_INSTALL_INCLUDEDIR="$HOME/ffmpeg_build/include" -DCMAKE_INSTALL_LIBDIR="$HOME/ffmpeg_build/lib" -DCMAKE_INSTALL_PREFIX="$HOME/ffmpeg_build" -DENABLE_SHARED:bool=off
make
make install

cd ~/ffmpeg_sources && \
wget -O ffmpeg-snapshot.tar.bz2 https://ffmpeg.org/releases/ffmpeg-snapshot.tar.bz2 && \
tar xjvf ffmpeg-snapshot.tar.bz2 && \
cd ffmpeg && \
PATH="$HOME/bin:$PATH" PKG_CONFIG_PATH="$HOME/ffmpeg_build/lib/pkgconfig" ./configure \
  --prefix="$HOME/ffmpeg_build" \
  --pkg-config-flags="--static" \
  --extra-cflags="-I$HOME/ffmpeg_build/include" \
  --extra-ldflags="-L$HOME/ffmpeg_build/lib" \
  --extra-libs="-lpthread -lm" \
  --ld="g++" \
  --bindir="$HOME/bin" \
  --enable-gpl \
  --enable-gnutls \
  --enable-libass \
  --enable-libfdk-aac \
  --enable-libfreetype \
  --enable-libmp3lame \
  --enable-libopus \
  --enable-libsvtav1 \
  --enable-libdav1d \
  --enable-libvorbis \
  --enable-libvpx \
  --enable-libsrt \
  --enable-libx264 \
  --enable-libx265 \
  --enable-nonfree && \
PATH="$HOME/bin:$PATH" make && \
make install && \
hash -r

thank you so much

**Comment by maxsharabayko** [comment]
Hi @dbbrito 
These guides may be helpfull:
- [OBS: Streaming with SRT Protocol](https://obsproject.com/wiki/Streaming-With-SRT-Protocol)
- [SRT Cookbook: FFMpeg](https://srtlab.github.io/srt-cookbook/apps/ffmpeg.html)
- [SRT Cookbook: OBS Studio](https://srtlab.github.io/srt-cookbook/apps/obs-studio.html)

It might be a good idea to try to find help in slack. [Join the conversation](https://slackin-srtalliance.azurewebsites.net/) in the `#general` channel on [Slack](https://srtalliance.slack.com).

**Comment by maxsharabayko** [comment]
Closing due to the lack of discussion. Don't hesitate to reopen and/or provide updates.
