### ISSUE TITLE
[BUG]SRT crash when sending data under a very heavily congested networks

### ISSUE THREAD

**Issue by cg82616424** [Haivision/srt#2039]
**Describe the bug**
srt crash under very heavily congested networks
**To Reproduce**
some conditions to reappear this core dump
1. a heavily congested network
2. send data under file mode 
3. do not modify SRTO_LINGER opptions
4. use async mode

**Expected behavior**
srt crash will be happened after one or two hours
**Screenshots**
stack trace:
![image](https://user-images.githubusercontent.com/6222464/122152211-8746a380-ce93-11eb-9ddd-e56e7bc587e0.png)
![image](https://user-images.githubusercontent.com/6222464/122152492-f3290c00-ce93-11eb-8657-de934ca4cb8e.png)

**Desktop (please provide the following information):**
 - OS: Android
 - SRT Version:1.4.3rc

**Additional context**
I reviewd srt code, I found that , when I use async mode and do not modify SRTO_LINGER, srt will let gc thread to release resources;  so the GC thread and the sender thread may have some thread synchronization problems; 
so I set SRTO_LINGER to off and 0, this crash never happened again;
but I dont know to use which lock to solve this problem appropriately

**Comment by maxsharabayko** [comment]
@cg82616424 Thanks for reporting!

> SRT Version:1.4.3rc

Please define whether RC.0 or RC.1 is used. Or v1.4.3 release.

**Comment by cg82616424** [comment]
1.4.3.RC.0

**Comment by maxsharabayko** [comment]
This may have been fixed already with a series of concurrency bug fixes.
Please don't hesitate to reopen if the issue still exists in the latest releases.
