### ISSUE TITLE
Error logged when setting bandwith-related options before connection is established

### ISSUE THREAD

**Issue by jeandube** [Haivision/srt#204]
Setting SRTO_MAXBW, SRTO_OHEADBW logs the following error (dev branch):
`updateCC(core.cpp:5534): /SRT:RcvQ:worker*E: SRT.c: updateCC: CAN'T DO UPDATE - smoother NOT READY; sending buffer created`.

**Comment by ethouris** [comment]
As I looked into the code, it looks like the update should not be done at all in that case because the function should know that there's no smoother and this will fail anyway. This should be fixed.

**Comment by ethouris** [comment]
Added a fix in #219
