### ISSUE TITLE
Use monotonic/steady clock by default if available

### ISSUE THREAD

**Issue by hololqq** [Haivision/srt#2044]
Hi,

I'm new to use the haivision srt project and have a question.
 
Out product uses v1.4.1 to achieve SRT transmit, but we found a bug that SRT will drop packet when system time is changed via NTP/manual. I checked the code and I though the related code is gettimeofday(), which use the system time as SRT start time.

Today I found the release logs of the 1.4.2&1.4.3, and some logs related to this function. So I imagined there's an issue indicated this bug and had been resolved in the following releases. Is this right? If so, please give me a reply.

Thanks for your time:)

**Comment by maxsharabayko** [comment]
Hu @hololqq 
SRT v1.4.2 adds two options for SRT to use monotonic time source:
1. C++11 `std::chrono::steady_clock` can be enabled with `-DENABLE_STDCXX_SYNC=ON` CMake build option.
2. POSIX `clock_gettime` with monotonic time source can be enabled with `-DENABLE_MONOTONIC_CLOCK`.

If you can use C++11 compliant compiler, consider using the first option.

**Comment by hololqq** [comment]
> Hi @hololqq
> SRT v1.4.2 adds two options for SRT to use monotonic time source:
> 
> 1. C++11 `std::chrono::steady_clock` can be enabled with `-DENABLE_STDCXX_SYNC=ON` CMake build option.
> 2. POSIX `clock_gettime` with monotonic time source can be enabled with `-DENABLE_MONOTONIC_CLOCK`.
> 
> If you can use C++11 compliant compiler, consider using the first option.

Thanks. I'll test it today.

**Comment by gizahNL** [comment]
> Hi @hololqq
> SRT v1.4.2 adds two options for SRT to use monotonic time source:
> 
> 1. C++11 `std::chrono::steady_clock` can be enabled with `-DENABLE_STDCXX_SYNC=ON` CMake build option.
> 2. POSIX `clock_gettime` with monotonic time source can be enabled with `-DENABLE_MONOTONIC_CLOCK`.
> 
> If you can use C++11 compliant compiler, consider using the first option.

What is the rationale for not having these turned on by default? It would seem to me that monotonic clock source is a strict requirement for a networking protocol doing time based recovery.

**Comment by maxsharabayko** [comment]
@gizahNL 
> What is the rationale for not having these turned on by default?

The end goal is to fully transition to a monotonic clock. There are/were several things to consider before transitioning.
1. Compatibility with old versions of SRT using wallclock. This has been confirmed. ✔️ 
2. Define what should be the new defaults.

As shared above, there are two ways to enable a monotonic clock:
1. C++11 `std::chrono::steady_clock` can be enabled with `-DENABLE_STDCXX_SYNC=ON` CMake build option.
2. POSIX `clock_gettime` with monotonic time source can be enabled with `-DENABLE_MONOTONIC_CLOCK`.

Without those options, the current defaults are:
- On MacOS SRT uses `mach_absolute_time(..)` by default, which is monotonic, except the timer is not incremented while the device is asleep.
- On Windows `QueryPerformanceCounter(..)` is used by default, though together with `gettimeofday()` port in pthreads4win. Not 100% accurate monotonic clock.
- On Linux `gettimeofday(..)` is used by default. Wall clock.

### The New Defaults to Apply

There are two options here.

1. The easiest way is to enable C++11 build of SRT by default, providing STL steady clock. However, it may impact some integrations, forcing them to explicitly disable C++11 in SRT. _Also, in some experiments, we observed STL steady clock to provide system clock, which is weird and requires further study_.

2. Another option is to enable C++11 by default only for Windows builds, and enable `-DENABLE_MONOTONIC_CLOCK` for Linux builds. If a Linux system does not support `CLOCK_MONOTONIC`, it is the user who should specify `-DENABLE_MONOTONIC_CLOCK=OFF`.
