### ISSUE TITLE
Dev branch: -stoptime: switch does not always stop srt-live-stransmit

### ISSUE THREAD

**Issue by alexanderdevm** [Haivision/srt#205]
While testing srt-live-transmit with `srt/srt-live-transmit -stoptime:305 srt://:5001?mode=listener file://con | ...` i have noticed that it doesn't always stop at the given stop time, and continues the process indefinitely.

**Comment by alexanderdevm** [comment]
Even with added timeout x, srt-live-transmit gets stuck exiting

**Comment by ethouris** [comment]
Interrupting looks even worse than I thought. I have to reinvent interrupting in stransmit then. Urgently.
