### ISSUE TITLE
Question: Using vcpkg to build SRT on windows

### ISSUE THREAD

**Issue by 2795918418** [Haivision/srt#2054]
**Describe the bug**
首先我是打算在window10系统上构建srt的，当我按照srt的build-win文档去一步一步操作时，操作到set VCPKG_ROOT=%cd%这一步时，没什么作用，下一步cd不进去，而且vcpkg下载任何东西都报错，说vcpkg.exe已停止工作
![image](https://user-images.githubusercontent.com/73520750/124694188-5b0ec780-df13-11eb-83a6-db415161a134.png)

**Comment by maxsharabayko** [comment]
Hi, @2795918418 
`set VCPKG_ROOT=%cd%` and further instructions should be done in the same terminal session, otherwise, the value of `VCPKG_ROOT` is lost.  As a fallback just replace the `VCPKG_ROOT` with the path to the root of the vcpkg folder.
