### ISSUE TITLE
Dev branch: -stoptime: switch should not be a required switch, should be optional

### ISSUE THREAD

**Issue by alexanderdevm** [Haivision/srt#206]
Presently if user will not add -stoptime switch, srt-live-transmit will show an error 

> ERROR: -stoptime (-d) must be at least 10 seconds

Although stoptime switch should be optional, and when not provided the srt-live-transmit should run indefinitely.

**Comment by ethouris** [comment]
I provided a fix in #218; and have even created a "competitive" issue for that :).
