### ISSUE TITLE
How to two-way transmission

### ISSUE THREAD

**Issue by Canees** [Haivision/srt#2065]
Are there any instructions about two-way transmission? Most of them are single-item transmissions

**Comment by maxsharabayko** [comment]
In short and simplified, once you have an SRT socket and it is connected to the per, you can do both reading and writing on it,
```c++
int srtsock = srt_create_socket();
// ... establish a connection

srt_readmsg2(srtsock, ...);
srt_sendmsg2(srtsock, ...);
```

**Comment by Canees** [comment]
> 简而言之，一旦您拥有一个 SRT 套接字并将其连接到 per，您就可以在其上进行读取和写入操作，
> 
> ```c++
> int srtsock = srt_create_socket();
> // ... 建立连接
> 
> srt_readmsg2 (srtsock, ...);
> srt_sendmsg2 (srtsock, ...);
> ```

thank
