### ISSUE TITLE
The compiled SO file is called by Python, and the API return status does not match the documentation

### ISSUE THREAD

**Issue by Canees** [Haivision/srt#2072]
Hello, as shown in the title, I use cmake | make packaged into the so file, use the python calls (srt_getsockstate), the status returned to digital, but the document is returned SOCKSTATUS, don't know if I do this right, I do not understand c + +
![image](https://user-images.githubusercontent.com/40012261/128326498-b1d668d9-c424-40ba-8f94-26db21056445.png)
![image](https://user-images.githubusercontent.com/40012261/128326568-027bfe6d-d6cf-46a3-baa7-d72a7448a242.png)

**Comment by ethouris** [comment]
I'm sorry I don't exactly know how this Python biding works, but how could you be able to call `srt_getsockstate()` without an argument? You should pass there the value of `SRTSOCKET`, which should be created by the call to `srt_create_socket()`.

**Comment by Canees** [comment]
> 对不起，我不完全知道这个 Python 投标是如何工作的，但是你怎么能在`srt_getsockstate()`没有参数的情况下调用呢？您应该在那里传递 的值`SRTSOCKET`，该值应该由对 的调用创建`srt_create_socket()`。

![image](https://user-images.githubusercontent.com/40012261/128331539-22c81ef9-10a9-46cc-94a5-e00e031eb6c6.png)
I don't know, maybe it's a compilation problem?
