### ISSUE TITLE
[FR]Does the moderator intend to support python calls?

### ISSUE THREAD

**Issue by Canees** [Haivision/srt#2078]
Since I am not familiar with the data types in C++, I can only compile so library for python to call and use. However, there are too many data types in C++ that need to be converted, which is somewhat complicated. Could the moderator provide libraries that python can use, such as initialization and receiving data? Pass parameters like port:4200, and host:'127.0.0.1' are similar to common types

**Comment by quink-black** [comment]
Welcome to create a python binding project if you can, but this is out of scope of current project.

请别在发和本项目不相关的问题！

**Comment by maxsharabayko** [comment]
Hi @Canees 

As @quink-black rightfully noted, this is currently out of the scope of the project. But any contribution to this would be welcome!

There was some rough study of the subject done in the past. In particular, examinating [SWIG](http://swig.org/) as a way to provide bindings to different languages. There is a dedicated channel `#swig` in [SRT Alliance slack](https://srtalliance.slack.com), feel free to [join](https://slackin-srtalliance.azurewebsites.net/).
I did a bit of a python wrapping in my branch [develop/swig](https://github.com/maxsharabayko/srt/tree/develop/swig). Feel free to take it from there.

**Comment by Canees** [comment]
> Welcome to create a python binding project if you can, but this is out of scope of current project.
> 
> 请别在发和本项目不相关的问题！

who are you！
自以为是

**Comment by Canees** [comment]
> Hi @Canees
> 
> As @quink-black rightfully noted, this is currently out of the scope of the project. But any contribution to this would be welcome!
> 
> There was some rough study of the subject done in the past. In particular, examinating [SWIG](http://swig.org/) as a way to provide bindings to different languages. There is a dedicated channel `#swig` in [SRT Alliance slack](https://srtalliance.slack.com), feel free to [join](https://slackin-srtalliance.azurewebsites.net/).
> I did a bit of a python wrapping in my branch [develop/swig](https://github.com/maxsharabayko/srt/tree/develop/swig). Feel free to take it from there.

OK，thanks
