### ISSUE TITLE
Feature Request: ts file to stream play back (limited/simple pacing support)

### ISSUE THREAD

**Issue by alexanderdevm** [Haivision/srt#208]
It would be nice to have a feature in srt-live-transmit or srt-file-transmit to be able to play a local ts file into an srt or udb stream.

**Comment by ethouris** [comment]
If you think about making a live streaming out of a local ts file, this is impossible because "live streaming a file" requires that the file reader interprets and is aware of the timestamps in the ts file, and this requires that the stream be at least demuxed.

The `ffmpeg -re` solution is something that does it, however I'm not sure how this really works with pipes.

**Comment by ggnull35** [comment]
You can try: https://github.com/kynesim/tstools/blob/master/tsplay.c
It is great for TS file to UDP streaming.

**Comment by alexanderdevm** [comment]
I am actually using tsplay for ts to udp streaming. 

The suggestion was more of instead of running 2 processes (ts play and srt) to stream is ts file to srt, there would only be one.

**Comment by ggnull35** [comment]
I got the idea, however if you check tsplay code there are multi-modes for PCR processing. I belive it is not meaningful to add those functions to stransmit as its'nt its purpose. It can open other suggestions like adding RTP input / output function etc. best way is to fork code for this purpose. (this is my comment - I am just a SRT user/deployer.)

**Comment by maxlovic** [comment]
[TSDuck](https://tsduck.io/) can be used as well
Example:
```
tsp -I file --infinite "filename.ts" -P regulate --bitrate 7500000 -O ip localhost:4900
./srt-live-transmit udp://:4900 “srt://:4200?mode=listener”
```
Adding this to `srt-live-transmit` will require parsing of MPEG-TS and some additional logic around. While the app is targeted as a sample application.

**Comment by maxlovic** [comment]
Closing as `won't be done`.
