### ISSUE TITLE
multicast stream to srt

### ISSUE THREAD

**Issue by bsi-ksk** [Haivision/srt#2090]
I want to redirect the multicast stream to srt:
**./srt-live-transmit -v udp://238.1.1.86:1234?adapter=10.10.71.246 srt://:2000?adapter=192.168.1.15 &**

**root@srt2udp:~# ./udp-to-srt.sh
root@srt2udp:~# Media path: 'udp://238.1.1.86:1234?adapter=10.10.71.246' --> 'srt://:2000?adapter=192.168.1.15'
Multicast: home address: 10.10.71.246:1234
Multicast(POSIX): will bind to IGMP address: 238.1.1.86
SRT parameters specified:

        adapter = '192.168.1.15'
Opening SRT target listener on :2000
Binding a server on 192.168.1.15:2000 ...
 listen...
 accept...
 connected.
Accepted SRT target connection**

I'm trying to get a vlc player: **srt://@192.168.1.15:2000**

does not work

srt to udp multicast works:

**/usr/src/Haivision/srt-master/srt-live-transmit -v srt://:2000 udp://238.1.1.161:1234?adapter=10.10.71.246 &**

**Comment by J-Rogmann** [comment]
Hello @bsi-ksk 

I'm pretty sure, that VLC has some issue playing back the stream. Can you make sure, that no password is set for SRT stream in VLC? 

I gave it a very quick try with SRT v1.4.2 by creating a multicast MPEG-TS stream on a another computer with multicast output to  238.1.1.86:1234.

With `./srt-live-transmit -v udp://238.1.1.86:1234?adapter=10.1.50.2 srt://:2000?adapter=192.168.2.3` I grabbed that multicast on one interface and made it available on another interface on port 2000, just like you in your example.

I worked right away and VLC showed picture when opening `srt://@192.168.2.3:2000` from a 3rd PC (macbook in this case)

```
./srt-live-transmit -v udp://238.1.1.86:1234?adapter=10.1.50.2 srt://:2000?adapter=192.168.2.3
Media path: 'udp://238.1.1.86:1234?adapter=10.1.50.2' --> 'srt://:2000?adapter=192.168.2.3'
Multicast: home address: 10.1.50.2:1234
Multicast(POSIX): will bind to IGMP address: 238.1.1.86
SRT parameters specified:

	adapter = '192.168.2.3'
Opening SRT target listener on :2000
Binding a server on 192.168.2.3:2000 ...
 listen...
 accept... 
 connected.
Accepted SRT target connection
28952 bytes lost, 1688240 bytes sent, 1717192 bytes received
SRT target disconnected
```  

And that is where I see similarities to your config:
your logfile said:
```
Opening SRT target listener on :2000
Binding a server on 192.168.1.15:2000 ...
listen...
accept...
connected.
Accepted SRT target connection**
```

So the handshake seems to happen and the SRT connection is established. For just some reason your VLC has an issue

Try checking your VLC config by clicking in `options/show all/inputs & codecs/access modules/SRT` like in attached picture

<img width="769" alt="Screenshot 2021-08-18 at 13 38 06" src="https://user-images.githubusercontent.com/47855715/129892925-c38996b1-ffb7-49f6-8bdb-e19c675f9f27.png">

You can also try to capture the SRT traffic with tcpdump or wireshark, so we can have a closer look. Pleae make sure, you start the capture before establishing the SRT connection, so you grab the handshake.

best regards,
Justus
