### ISSUE TITLE
raspberry pi vlc + srt

### ISSUE THREAD

**Issue by akoryuerek** [Haivision/srt#2110]
Hi guys,

can anybody tell me how they did this? Currently is vlc not supporting srt on raspberry.

https://www.haivision.com/blog/broadcast-video/open-source-video-streaming-protocol-disrupting-broadcast-news/

**Comment by maxsharabayko** [comment]
Hi @akoryuerek 
Your question is not quite related to the SRT library, hosted here on GitHub. I would suggest asking in the SRT Alliance slack instead. In particular, you might find people from Sky News there.
[Join the conversation](https://slackin-srtalliance.azurewebsites.net/) on the [SRT Alliance Slack](https://srtalliance.slack.com).
