### ISSUE TITLE
primary / backup stream selector

### ISSUE THREAD

**Issue by QHossein** [Haivision/srt#2120]
Please consider following conditions:
There are two different SRT streams that send to a SRT server (for example Haivision SRT Gateway on aws). The first one is primary stream and the second one is backup. Note that these two streams are not exactly the same, for example there may be differences in resolution and bit rate. 
It is desirable that the primary stream be routed when it is available, otherwise the backup stream is selected for routing.  Whenever primary stream is available, the backup stream is disconnected and the primary stream is routed to the destination again.

![](https://user-images.githubusercontent.com/6464606/132343074-69198830-1a1a-4fa3-a2f8-ee07f0828eae.png)

Is there anyway to reach this goal by existing libs? I did not find any options in 'Haivision SRT Gateway'.

I have already read [bonding-main-backup](https://github.com/Haivision/srt/blob/master/docs/features/bonding-main-backup.md) but it seems that it is about sending same streams with different interfaces.
Thanks.

**Comment by ethouris** [comment]
This is something completely different than SRT can offer with the main/backup solution.

Most important thing is that SRT is content-agnostic, so the only thing that SRT itself can offer for such a soluition is to send exactly the same stream (potentially) on all member connections.

The main/backup solution offers (at best) the smooth switching. If you send the same stream, you simply glue it by the positions it originally had in the original bitstream. If the streams have different parameters, they are simply different streams (and only the application knows that they come originally from the same camera), so there's no way how they can be glued together. This can only be done by the application, as this requires that the beginning of the "newly switched in" stream start with all initial parameters that are also synchronized with the pictures from the other stream. There's no way to do this without proper recognition, interpretation and configuration of the source streams - and this is something SRT does not do.

Here SRT can offer just sending two different streams over two independent SRT connections, and it's up to the application to decide what to sent, when, and over which link. SRT can help here probably by delivering the user the value of the last response time, which is the key factor used in the backup activation decision - and that probably SRT could do. Rest of the things - activation, matching the split points, smoothness - is up to the application.

**Comment by maxsharabayko** [comment]
Hi @QHossein 
Thank you for this feature request. Indeed it is a very interesting use case!
As already stated by @ethouris above, switching between two or more different source streams is more of an application-level solution, rather than the path redundancy the library is to offer.
I am not aware if anyone offers such already, but it is totally possible by the means of the SRT library.

Closing this FR as "won't implement" as it is out of the library's scope.
