### ISSUE TITLE
[BUG] configure broken for aarch64 cross-compiling toolchain

### ISSUE THREAD

**Issue by jeandube** [Haivision/srt#2121]
A Makefile building v1.4.4-rc.0 fails for v1.4.4-rc.1.
Last working commit: 4fc0f317b04196b9f36c5ac46ba4f357295baa50
Error introduced in: 409a40d408090c56026413e5706414f1363aa430
CMake Error at scripts/FindPThreadGetSetName.cmake:34 (unset):
  unset called with an invalid second argument
Call Stack (most recent call first):
  CMakeLists.txt:279 (FindPThreadGetSetName)

Step to reproduce may require our cross-compiling toolchain
`jdube@indigo:~/sandbox/makito2_project/components/vendors/haisrt$ make
[ -d srt.git ] || mkdir srt.git
git clone https://github.com/haivision/srt.git srt.git
Cloning into 'srt.git'...
remote: Enumerating objects: 10881, done.
remote: Counting objects: 100% (1018/1018), done.
remote: Compressing objects: 100% (593/593), done.
remote: Total 10881 (delta 659), reused 644 (delta 425), pack-reused 9863
Receiving objects: 100% (10881/10881), 12.80 MiB | 10.79 MiB/s, done.
Resolving deltas: 100% (8352/8352), done.
(cd srt.git; git checkout 409a40d408090c56026413e5706414f1363aa430; git config core.fileMode false;)
Note: checking out '409a40d408090c56026413e5706414f1363aa430'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 409a40d... [core] Detect pthread_getname* availability
(cd srt.git; echo -n "COMMIT=" >>../lastgitco.txt; \
         git log -n1 |grep commit|cut -f 2 -d ' '>>../lastgitco.txt;)
[ -d srt.git ] || mkdir srt.git
(cd srt.git;\
         echo -n "# Made " >srtgitco.NAGA.inc; \
         date >>srtgitco.NAGA.inc;\
         echo "SRTGITREPO=" https://github.com/haivision/srt.git >>srtgitco.NAGA.inc; \
         echo -n "SRTGITCO=" >>srtgitco.NAGA.inc; \
         git log -n1 |grep commit|cut -f 2 -d ' '>>srtgitco.NAGA.inc; \
         mv srtgitco.NAGA.inc ..)
(cd srt.git;\
         ./configure --with-compiler-prefix=/opt/Xilinx/petalinux-v2017.3-final/tools/linux-i386/aarch64-linux-gnu/bin/aarch64-linux-gnu-\
         --disable-c++11\
         --enable-monotonic-clock\
         --enable-debug\
         --enable-logging\
         --disable-heavy-logging\
         --enable-experimental-bonding\
         \
         --enable-thread-check --with-thread-check-includedir=/home/jdube/sandbox/makito2_project/build/NAGA/../../components/include)
NOTE: --disable-c++11 changed into --enable-c++11=0
NOTE: --disable-heavy-logging changed into --enable-heavy-logging=0
NOTE: toolchain changed by '--with-compiler-prefix' option
NOTE: foreign target type detected (aarch64-linux-gnu)
NOTE: no --with-target-path found, will try to autodetect at /opt/Xilinx/petalinux-v2017.3-final/tools/linux-i386/aarch64-linux-gnu/bin
Checking path '/opt/Xilinx/petalinux-v2017.3-final/tools/linux-i386/aarch64-linux-gnu/bin'
Checking path '/opt/Xilinx/petalinux-v2017.3-final/tools/linux-i386/aarch64-linux-gnu/aarch64-linux-gnu'
NOTE: target path detected: /opt/Xilinx/petalinux-v2017.3-final/tools/linux-i386/aarch64-linux-gnu/aarch64-linux-gnu
PKG_CONFIG_PATH: Found pkgconfig in lib for '/opt/Xilinx/petalinux-v2017.3-final/tools/linux-i386/aarch64-linux-gnu/aarch64-linux-gnu' - using it
Running: cmake . -DWITH_COMPILER_PREFIX=/opt/Xilinx/petalinux-v2017.3-final/tools/linux-i386/aarch64-linux-gnu/bin/aarch64-linux-gnu- -DENABLE_CXX11=0 -DENABLE_MONOTONIC_CLOCK=1 -DENABLE_DEBUG=1 -DENABLE_LOGGING=1 -DENABLE_HEAVY_LOGGING=0 -DENABLE_EXPERIMENTAL_BONDING=1 -DENABLE_THREAD_CHECK=1 -DWITH_THREAD_CHECK_INCLUDEDIR=/home/jdube/sandbox/makito2_project/build/NAGA/../../components/include -DCMAKE_PREFIX_PATH=/opt/Xilinx/petalinux-v2017.3-final/tools/linux-i386/aarch64-linux-gnu/aarch64-linux-gnu
-- The C compiler identification is GNU 4.6.3
-- The CXX compiler identification is GNU 4.6.3
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26")
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- BUILD TYPE: Debug
-- Performing Test HAVE_CLOCK_GETTIME_IN
-- Performing Test HAVE_CLOCK_GETTIME_IN - Failed
-- Performing Test HAVE_CLOCK_GETTIME_LIBRT
-- Performing Test HAVE_CLOCK_GETTIME_LIBRT - Success
-- CLOCK_MONOTONIC: available, requires -lrt
-- LOGGING: ENABLED
-- USE_BUSY_WAITING: OFF (default)
-- Handling compiler with PREFIX=/opt/Xilinx/petalinux-v2017.3-final/tools/linux-i386/aarch64-linux-gnu/bin/aarch64-linux-gnu- TYPE=gcc
-- Compiler type: gcc. C: /opt/Xilinx/petalinux-v2017.3-final/tools/linux-i386/aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc; C++: /opt/Xilinx/petalinux-v2017.3-final/tools/linux-i386/aarch64-linux-gnu/bin/aarch64-linux-gnu-g++
-- Looking for inet_pton
-- Looking for inet_pton - found
CMake Error at scripts/FindPThreadGetSetName.cmake:34 (unset):
  unset called with an invalid second argument
Call Stack (most recent call first):
  CMakeLists.txt:279 (FindPThreadGetSetName)

-- checking for module 'openssl libcrypto'
/usr/bin/pkg-config: /usr/lib64/libpopt.so.0: no version information available (required by /usr/bin/pkg-config)
/usr/bin/pkg-config: /usr/lib64/libpopt.so.0: no version information available (required by /usr/bin/pkg-config)
/usr/bin/pkg-config: /usr/lib64/libpopt.so.0: no version information available (required by /usr/bin/pkg-config)
/usr/bin/pkg-config: /usr/lib64/libpopt.so.0: no version information available (required by /usr/bin/pkg-config)
/usr/bin/pkg-config: /usr/lib64/libpopt.so.0: no version information available (required by /usr/bin/pkg-config)
--   found openssl libcrypto, version 1.0.2o;1.0.2o
/usr/bin/pkg-config: /usr/lib64/libpopt.so.0: no version information available (required by /usr/bin/pkg-config)
/usr/bin/pkg-config: /usr/lib64/libpopt.so.0: no version information available (required by /usr/bin/pkg-config)
/usr/bin/pkg-config: /usr/lib64/libpopt.so.0: no version information available (required by /usr/bin/pkg-config)
/usr/bin/pkg-config: /usr/lib64/libpopt.so.0: no version information available (required by /usr/bin/pkg-config)
/usr/bin/pkg-config: /usr/lib64/libpopt.so.0: no version information available (required by /usr/bin/pkg-config)
/usr/bin/pkg-config: /usr/lib64/libpopt.so.0: no version information available (required by /usr/bin/pkg-config)
/usr/bin/pkg-config: /usr/lib64/libpopt.so.0: no version information available (required by /usr/bin/pkg-config)
/usr/bin/pkg-config: /usr/lib64/libpopt.so.0: no version information available (required by /usr/bin/pkg-config)
/usr/bin/pkg-config: /usr/lib64/libpopt.so.0: no version information available (required by /usr/bin/pkg-config)
/usr/bin/pkg-config: /usr/lib64/libpopt.so.0: no version information available (required by /usr/bin/pkg-config)
/usr/bin/pkg-config: /usr/lib64/libpopt.so.0: no version information available (required by /usr/bin/pkg-config)
/usr/bin/pkg-config: /usr/lib64/libpopt.so.0: no version information available (required by /usr/bin/pkg-config)
/usr/bin/pkg-config: /usr/lib64/libpopt.so.0: no version information available (required by /usr/bin/pkg-config)
/usr/bin/pkg-config: /usr/lib64/libpopt.so.0: no version information available (required by /usr/bin/pkg-config)
-- WARNING: pkg-config has incorrect prefix - enforcing target path prefix: /opt/Xilinx/petalinux-v2017.3-final/tools/linux-i386/aarch64-linux-gnu/aarch64-linux-gnu
-- SSL via pkg-config: -L /opt/Xilinx/petalinux-v2017.3-final/tools/linux-i386/aarch64-linux-gnu/aarch64-linux-gnu/lib/x86_64-linux-gnu -I /opt/Xilinx/petalinux-v2017.3-final/tools/linux-i386/aarch64-linux-gnu/aarch64-linux-gnu/include -l;ssl;crypto
-- ENCRYPTION: ENABLED, using: openssl libcrypto
-- SSL libraries: ssl;crypto
-- COMPILER CHANGED TO: gcc - forcing C++11 standard for apps
CMake Warning at CMakeLists.txt:438 (message):
  Parts that require C++11 support will be disabled (srt-live-transmit)

-- STDCXX_SYNC: OFF
-- MONOTONIC_CLOCK: 1
-- C++ STD: Forcing C++11 on applications
-- DETECTED SYSTEM: LINUX;  LINUX=1
-- APP: srt_virtual: using default C++ standard
-- ADDING TRANSITIVE LINK DEP to:srt_shared : -lpthread
-- ADDING TRANSITIVE LINK DEP to:srt_static : -lpthread
-- INSTALL DIRS: bin=bin lib=lib/x86_64-linux-gnu shlib=lib/x86_64-linux-gnu include=include
-- APPS: DISABLED
-- Configuring incomplete, errors occurred!
See also "/home/jdube/sandbox/makito2_project/components/vendors/haisrt/srt.git/CMakeFiles/CMakeOutput.log".
See also "/home/jdube/sandbox/makito2_project/components/vendors/haisrt/srt.git/CMakeFiles/CMakeError.log".
CONFIGURE: cmake reported error: child process exited abnormally
(cd srt.git; make VERBOSE=1   srt_shared)
make[1]: Entering directory `/home/jdube/sandbox/makito2_project/components/vendors/haisrt/srt.git'
make[1]: *** No rule to make target `srt_shared'.  Stop.
make[1]: Leaving directory `/home/jdube/sandbox/makito2_project/components/vendors/haisrt/srt.git'
make: *** [srt.git/libsrt.so] Error 2
jdube@indigo:~/sandbox/makito2_project/components/vendors/haisrt$

**Comment by maxsharabayko** [comment]
Looks like CMake 2.8.12 does not support the `PARENT_SCOPE` argument for `unset`.
https://cmake.org/cmake/help/v2.8.12/cmake.html

This was added somewhere around CMake 3.0.2…

Would make sense to configure a CI with CMake 2.8.12 to avoid such situations in the future. 🤔

**Comment by jeandube** [comment]
Our build server has been update with CMake 3.1.0. 
Problem solved, closing issue.

**Comment by maxsharabayko** [comment]
Unfortunately have to reopen as we state that the minimum supported CMake version is 2.8.12.
```cmake
cmake_minimum_required (VERSION 2.8.12 FATAL_ERROR)
```

So either the minimum supported version has to be set to 3.0.2, or `unset(var PARENT_SCOPE)` must be avoided.

**Comment by ethouris** [comment]
How about using `macro` instead of `function`?
