### ISSUE TITLE
[FR]Can you give an example of an android player?

### ISSUE THREAD

**Issue by pray166** [Haivision/srt#2124]

**Comment by quink-black** [comment]
VLC has libsrt wrapper. However, the last release version 3.0 doesn't support streamid. VLC 4.0 isn't released yet.

**Comment by pray166** [comment]
OK,Actually I just want a simple demo, written in java, source code.

**Comment by quink-black** [comment]
> OK,Actually I just want a simple demo, written in java, source code.

Add java binding via JNI is easy, but out of scope of current project.

**Comment by pray166** [comment]
OK, Thank you!

**Comment by mbakholdina** [comment]
@pray166 See also [Free of Charge Players with SRT support](https://srtlab.github.io/srt-cookbook/apps/index.html#free-of-charge-players-with-srt-support).

**Comment by pray166** [comment]
> @pray166 See also [Free of Charge Players with SRT support](https://srtlab.github.io/srt-cookbook/apps/index.html#free-of-charge-players-with-srt-support).

Thank you! But i need source code.

**Comment by linhnv106** [comment]
Hi @pray166  was you able to play srt in android with sample of source?
