### ISSUE TITLE
Drop packets earlier than set latency 

### ISSUE THREAD

**Issue by BlueWaterCrystal** [Haivision/srt#2151]
Hi,

Example:
```
Sender > latency 10s > receiver
drop packet 5 seconds late  instead of 10 seconds
```

I've tried `srt_sendmsg` but the packets are still dropping 10 seconds later.

**Comment by mbakholdina** [comment]
Hi @BlueWaterCrystal,

Could you please describe in a more detailed way what's your test setup and what's exactly the problem?
What kind of test application and commands do you use? Any logs from receiver/sender?

**Comment by BlueWaterCrystal** [comment]
Hi,

**New Issue**
It seems a new issue has occurred, where around 30 seconds into the stream all bandwidth is lost and it can't recover.

Legend: green is buffer in milliseconds and blue is bandwidth 
The tests were done over LAN.

Sender 100% overhead
![bandwidth drop local sender](https://user-images.githubusercontent.com/55627513/136250458-8b95b6a2-28b4-42f1-b955-7fee25c4c91e.png)
)

Sender 25% overhead
![bandwidth drop local sender 25 ](https://user-images.githubusercontent.com/55627513/136250517-a0e98214-69f0-44b9-8325-ce1916376b7c.png)


**=================================================**

The original issue is when there is a massive drop in bandwidth/packet drop, the sender buffer gets backlogged and then a massive delay for it to be emptied even though bitrate has changed, making recovery time high.


Possibly `SRTO_SNDBUF` or `SRTO_SNDDATA`  could help to reduce accumulated packets in the buffer to lower recovery time or reduce the distance between old and new packets?

Receiver
![bandwidth drop local](https://user-images.githubusercontent.com/55627513/136254153-657d1d6e-7d0f-4757-ba11-3df1f21e893a.png)

Encoder adapted to the massive drop but accumulated packets still overrun the buffer.
It's not the delay of the encoder as a test was done by removing the encoder and the buffer still landed up full.

I'm not sure but it also looks like it isn't using any bandwidth to recovery the packets?



Config:
```
SRTO_LATENCY:10000
SRTO_PAYLOADSIZE:1000
SRTO_SNDSYN:false
SRTO_RCVSYN:false
SRTO_LINGER:false
SRTO_MAXBW:0
SRTO_INPUTBW:0
Version 1.4.4
```
