### ISSUE TITLE
ITMS-90430: invalid Swift Support - The file libsrt.1.4.dylib does't have a signing ID. Sign the file, rebuild your app using the current public(GM) version of Xcode and resubmit it

### ISSUE THREAD

**Issue by wallecechen** [Haivision/srt#2174]
I met the ITMS-90430/90426: invalid Swift support w/ no libsrt.1.4.dylib signing ID when uploading to App store.
Researching the other suggestions from internet, but no solution at all even I did :

"Always embedded swift support enable" -> [YES] @ build option of Xcode
Auto-create "SwiftSupport" by "Package_ipa.sh"
Embedded w/ signed at "General" option of XCode for libsrt.1.4.dylib ==> it is working fine to execute from the iphone/ipad via XCode.
Anyone can help how to fix the signing ID problem for libsrt.1.4.dylib? Or others solution.
thanks

**Comment by maxsharabayko** [comment]
@wallecechen Did you manage to resolve the issue?
