### ISSUE TITLE
[BUG] srt-live-transmit.exe outputs nothing

### ISSUE THREAD

**Issue by TTsdzb** [Haivision/srt#2198]
When running srt-live-transmit.exe, the program exits immediately with no output, even with -version or -h.  

To Reproduce:  
1. Build the master branch exactly as srt/docs/build/build-win.md shown on Windows, with:  
    OpenSSL_1_1_1-stable from <https://github.com/openssl/openssl> built from sources
    Standard C++ threading library, CMake option ```-DENABLE_STDCXX_SYNC=ON```
2. Try to run the program through Powershell or Command Prompt in Windows Terminal, then in a normal Command Prompt window.  

Expected behavior:  
Something should happen when I run it, maybe.

Screenshots:  
![image](https://user-images.githubusercontent.com/62687036/144434680-942db1aa-28b4-4b8e-8b9b-12f3683c9a2f.png)
![image](https://user-images.githubusercontent.com/62687036/144434802-8f04f6b6-3ed6-468c-be08-0af4141735c1.png)
![image](https://user-images.githubusercontent.com/62687036/144434968-e4bebe9e-fbc8-4c9f-a2e3-b3540cdbdca9.png)

Desktop (please provide the following information):  
 - OS: Windows10 Professional 20H1 (19043.1348)
 - SRT commit ID: 8b68157

Additional context:  
Please let me know if needing more information, or I have done something wrong.

**Comment by TTsdzb** [comment]
I checked the return value of the program, and it returns a huge value.  
![image](https://user-images.githubusercontent.com/62687036/144709792-97ac9aed-f55d-4897-9dd4-d79c428dbe93.png)

**Comment by maxsharabayko** [comment]
It looks more like a crash. Do you see a pop-up window with an error message? Maybe you don't have OpenSSL dynamic library (DLL) available to start.
You could try to run it under a debugger to try to fin the reason for the issue.
As an option, you can build SRT without encryption, and check if it works this way (CMake build option `-DENABLE_ENCRYPTION=OFF`).

**Comment by maxsharabayko** [comment]
> However, there isn't any pop-ups or something report the problem.

Should be. Maybe it is the PowerShell that is blocking the pop-up. If you run from a normal command line, you should see it.

**Comment by TTsdzb** [comment]
I think there should be too but there isn't any. In the original comment I tried to run it in a normal cmd window, but nothing happend. Just as you can see in the 3rd screenshot. Bats does not work, too, regardless of running in PowerShell or cmd or by double clicking.
