### ISSUE TITLE
udp source bind error while using for second instance

### ISSUE THREAD

**Issue by mks75** [Haivision/srt#220]
Hi,
I have multicast source mpegts (udp://238.1.1.1:1234), that I want to send to two different locations. 
1st instance works well
./stransmit -v udp://238.1.1.1:1234 srt://server1-ip:38000?mode=server
But when I try to use the same source for second location, it gives following error
./stransmit -v udp://238.1.1.1:1234 srt://server1-ip:39000?mode=server
bind: Address already in use

How can I use same source and create multiple instance to send them to different locations?
Please advise. Thanks

**Comment by ggnull35** [comment]
I had same issue. Most probably, stransmit blocks the input port.
Workaround: Use multicat to duplicate streams on localhost with different ports and use these newly generated streams with stransmit.

**Comment by mks75** [comment]
thanks @ggnull35 , for suggesting the workaround!
@ethouris, is the fix available on dev branch or the master branch? please advise.

**Comment by ethouris** [comment]
As the description says "backport", then it's a fix to "master" branch, so it should be now available everywhere.
