### ISSUE TITLE
[BUG] group backup link bstats.mbpsMaxBW is 1250

### ISSUE THREAD

**Issue by jeandube** [Haivision/srt#2200]
Our reference: NKE-1458
Sender/Listener
SRTO_GROUPCONNECT=1
SRTO_MAXBW=0 //auto
SRTO_INPUTBW=0 //auto
SRTO_MININPUTBW=1884kbps //streamer output (1.5Mbps video+audio+MPEG overhead)
SRTO_OHEADBW=25

Active link report bstats.mbpsMaxBW=2 355 kbps (~1 884*1.25)
Backup link reports bstats.mbpsMaxBW=1 250 000 kbps (1Gbps*1.25)
Like if SRTO_MAXBW was set to -1 (infinite).

most likely caused by no traffic measured on the backup link since if active-backup links swap 2355 will be reported on both links. Even if technically the traffic is measured at the link level, it is submitted at the group level and this is what should define the snd BW ceiling.

**Comment by jeandube** [comment]
```  Redundancy            : Active-Backup
  SRT v1.4.4:
  Path 1:
    State               : CONNECTED
    Peer Version        : 1.4.4
    Peer Endpoint       : 10.65.10.230:38442
    Local Endpoint      : 10.65.10.234:9172
    Reconnections       : 1
    AES Encryption      : Off
    Resent Packets      : 0
    Resent Bytes        : 0
    Dropped Packets     : 0
    Dropped Bytes       : 0
    Received ACKs       : 0
    Received NAKs       : 0
    Max Bandwidth       : 1,250,000 kbps
    Path Max Bandwidth  : 11,968 kbps
    RTT                 : 100 ms
    Local Buffer Level  : 0 ms
    Latency             : 250 ms
  Path 2:
    State               : STREAMING
    Peer Version        : 1.4.4
    Peer Endpoint       : 192.168.10.230:53005
    Local Endpoint      : 192.168.10.234:9172
    Reconnections       : 1
    AES Encryption      : Off
    Resent Packets      : 0
    Resent Bytes        : 0
    Dropped Packets     : 0
    Dropped Bytes       : 0
    Received ACKs       : 3,808
    Received NAKs       : 0
    Max Bandwidth       : 2,355 kbps
    Path Max Bandwidth  : 83,859 kbps
    RTT                 : < 1 ms
    Local Buffer Level  : 14 ms
    Latency             : 250 ms
```

**Comment by jeandube** [comment]
Note that bstats.mbpsBandwidth (Path Max Bandwidth) is returned for both paths.

**Comment by maxsharabayko** [comment]
### Steps to reproduce

Using the `srt-xtransmit` built with `-DENABLE_EXPERIMENTAL_BONDING`.

```shell
(receive on two ports)
srt-xtransmit receive srt://:4200 srt://:4201

(generate, main/backup mode)
srt-xtransmit generate --sendrate 1Mbps "srt://127.0.0.1:4200?maxbw=0&grouptype=backup" srt://127.0.0.1:4201 \
    --statsfile group-snd.csv --statsfreq 1s -v --duration 5s
```
The resulting `group-snd.csv` would have the `mbpsMaxBW` of one socket set to 1250.

### Analysis (What to Do?)

> most likely caused by no traffic measured on the backup link since if active-backup links swap 2355 will be reported on both links.

That's exactly the reason.

> Even if technically the traffic is measured at the link level, it is submitted at the group level and this is what should define the snd BW ceiling.

Might be true for the main/backup mode. But not for the broadcast mode.
Each socket within a group is considered as an independent connection, and therefore it might make sense to independently estimate source (input) bitrate and adjust the MaxBW accordingly.
On the other hand, it might be reasonable to update the input bitrate estimation of all idle backup links in order to have a reasonable limit during the switch.
Also related to #2122.
