### ISSUE TITLE
Switch project to the Apache License

### ISSUE THREAD

**Issue by adamyellen** [Haivision/srt#221]

**Comment by russelltg** [comment]
I'm in support of this change.

**Comment by jlsantiago0** [comment]
I am in favor of changing the license to Apache 2.0.

**Comment by ethouris** [comment]
I support this idea.

**Comment by blakewenzel** [comment]
I support this change.

**Comment by rndi** [comment]
I am in favor of the proposed licence change

**Comment by cdunklau** [comment]
I support this change.

**Comment by stevomatthews** [comment]
I support this change.

**Comment by CrashZebra** [comment]
@alexpokotilo @SSE4 @midicase @jbroberg 
Do I have your permission?

**Comment by adamyellen** [comment]
@alexpokotilo @SSE4 @jbroberg @midicase 
Do I have your permission?

**Comment by jbroberg** [comment]
Yes

**Comment by alexpokotilo** [comment]
Yes, sure. LGPL was fine. R.I.P:) Apache much better.
I want to thank Haivision for this movement.

**Comment by adamyellen** [comment]
After further reflection I believe the MPL-2.0 is a more appropriate license for this project. The MPL-2.0 is more permissive than the current LGPL-2.1 while affording the contributors/authors more protection than the APL. The MPL-2.0 would ensure that the SRT source code files, modified or not, must be made available upon distribution of a larger work -- something the APL lacks.

I'm going to close this issue and open a new issue.
