### ISSUE TITLE
Desktop Capture

### ISSUE THREAD

**Issue by ksmuthucv** [Haivision/srt#2211]
Hello Team.

**Environment Details:**
OS: Windows 10
SRT: v1.4.4
Language: C++

**Request:**
We are trying to create an utility for desktop capturing (screen content+ audio). Approach is, to capture the image/audio and convert them into in-memory std::vector<uint8_t> and send it across the network for rendering/playing. At present using srt, in file mode and message api being on, we are able to send (from the server) the raw buffer (1920*1080*4) in single attempt by invoking _srt_sendmsg2(targetsocket, (const char *) data, (int)len, pmc);_ But on the client it takes up 2-3 secs to receive the above buffer. Can you please advice how to configure srt, so that delay be brought down to (least possible) milliseconds? PFA attached log generated during client reception.

[srt-log.txt](https://github.com/Haivision/srt/files/7721128/srt-log.txt)

Thanks for your help!!

Regards,
Muthu

**Comment by maxsharabayko** [comment]
In such configuration, the receiver has to wait for the whole message to arrive. Can you estimate the size of the frame you send and divide it on an approximate throughput of your network?

**Comment by ksmuthucv** [comment]
Hello @maxsharabayko,

Thanks for your help. At server side, after compressing the stream (image/audio size has come down to kbs) that need to be sent across, we would send the size to be expected first and then the actual message using srt_sendmsg2. With clients, we will read the size first and will wait for the size to be received via srt_recvmsg2 in a while loop.

Can you please provide your feedback on the items below?
1. How long should we wait for the message to be received in a while loop? In case there is a pocket loss or network issue, how can we skip and move to the next image/audio in order?
2. Upon connecting to the server without any error and after receiving a frame or two, we would run into "Connection was broken. error no: 2001.". Is there a way to know the cause of this issue? This would happen occasionally.  7/10 times client and server would be connected without connection loss for 30+ mins.
3. Let's say we would start the server, a client connects to the server then it is closed in a few mins. Then after a few mins of time, a new client connects to the same server, we would receive an error Operation not supported: Incorrect use of Message API (sendmsg/recvmsg).

Please note that, we have file mode, message api (messages order is enabled) and time-stamp-based packet delivery mode configured for both server and client.

Regards,
Muthu

**Comment by maxsharabayko** [comment]
Hi @ksmuthucv 
I saw a related correspondence in the `general` SRT Alliance slack channel. Did you manage to solve the issue?

**Comment by ksmuthucv** [comment]
Yes @maxsharabayko. We are able to sort out the issues. Thanks for your help and follow up.

**Comment by maxsharabayko** [comment]
@ksmuthucv
Could you please sum up what was wrong or what have you changed in case someone with a similar question finds this thread?
