### ISSUE TITLE
SRT NO OPER WITH MODE=RENDEZVOUS

### ISSUE THREAD

**Issue by nadinlozano** [Haivision/srt#2216]
I HAVE 2 DUCKDNS IPs external and have to commun port srt , inot receive srt tarjet connect

**Comment by maxsharabayko** [comment]
Without further details, it is hard to suggest anything here.
Maybe check [the documentation on srt-live-transmit](https://github.com/Haivision/srt/blob/master/docs/apps/srt-live-transmit.md#medium-srt).
