### ISSUE TITLE
Some thread names (shown by top -H) not set properly

### ISSUE THREAD

**Issue by jeandube** [Haivision/srt#222]
the linux command top -H shows thread names and some threads of SRT lib are not set properly. For a single receiving connection the duplicated SRT: tsbpd thread and missing SRT:RcvQ:worker thread (parent of SRT:tsbpd) suggests the parent thread name was lost (set in parent for children to inherit but not restored after thread creation). Same for SRT:GC (the garbage collector thread), there should be only one instance of it.

**Comment by jeandube** [comment]
`{
       ThreadName tn("SRT:GC");
       pthread_create(&m_GCThread, NULL, garbageCollect, this);
   }`

**Comment by ethouris** [comment]
#225 provided for fixing
