### ISSUE TITLE
ffmpeg srt caller SRTO_PAYLOADSIZE on socket: Operation not supported error [BUG]

### ISSUE THREAD

**Issue by lemmykilmister34** [Haivision/srt#2228]
Hello , 

When i try to send file to srt with ffmpeg i get SRTO_PAYLOADSIZE error. 

here is my command ; 

ffmpeg -re -i /tmp/xx.ts -c copy -f mpegts srt://x.x.x.x:1235

[mpegts @ 0x431fec0] start time for stream 3 is not set in estimate_timings_from_pts
[mpegts @ 0x431fec0] PES packet size mismatch
[mpegts @ 0x431fec0] Packet corrupt (stream = 1, dts = 8357548589).
[mpegts @ 0x431fec0] PES packet size mismatch
[mpegts @ 0x431fec0] Packet corrupt (stream = 2, dts = 8357548589).
Input #0, mpegts, from '/tmp/sinema_aksiyon_adalet4.ts':
  Duration: 00:01:39.63, start: 92762.866989, bitrate: 5260 kb/s
  Program 8110
    Metadata:
      service_name    : SINEMA AKSIYON HD
      service_provider: PlatformTurk
    Stream #0:0[0xa2a]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuv420p(tv, bt709, top first), 1920x1080 [SAR 1:1 DAR 16:9], 25 fps, 50 tbr, 90k tbn, 50 tbc
    Stream #0:1[0xa8e](tur): Audio: mp2 ([3][0][0][0] / 0x0003), 48000 Hz, stereo, fltp, 128 kb/s
    Stream #0:2[0xaf2](eng): Audio: mp2 ([3][0][0][0] / 0x0003), 48000 Hz, stereo, fltp, 128 kb/s
    Stream #0:3[0xe42](tur): Subtitle: dvb_subtitle ([6][0][0][0] / 0x0006)
[srt @ 0x46e8d80] failed to get option SRTO_PAYLOADSIZE on socket: Operation not supported.
srt://10.100.255.130:1235: Input/output error

my ffmpeg version : 
ffmpeg -version
ffmpeg version n4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
built with gcc 4.8.5 (GCC) 20150623 (Red Hat 4.8.5-44)
configuration: --enable-libsrt --enable-libx264 --enable-gpl
libavutil      56. 51.100 / 56. 51.100
libavcodec     58. 91.100 / 58. 91.100
libavformat    58. 45.100 / 58. 45.100
libavdevice    58. 10.100 / 58. 10.100
libavfilter     7. 85.100 /  7. 85.100
libswscale      5.  7.100 /  5.  7.100
libswresample   3.  7.100 /  3.  7.100
libpostproc    55.  7.100 / 55.  7.100

**Comment by maxsharabayko** [comment]
You are trying to send a file using SRT in live configuration. I assume the command line you share misses a playback functionality (pace sending based on the timestamps of the MPEG-TS file and split the data into chunks).
In live configuration, SRT expects packets of 1316 bytes.
See the `payload_size` in https://www.ffmpeg.org/ffmpeg-protocols.html#srt

Try something else, e.g. TSDuck
([How to replay a .ts file as a stream](https://srtlab.github.io/srt-cookbook/apps/tsduck.html#how-to-replay-a-ts-file-as-a-stream)).
