### ISSUE TITLE
Newbie to srt-live-transmit/ save raw srt stream from OBS

### ISSUE THREAD

**Issue by tvadi** [Haivision/srt#2240]
Looking on the main srt-live-transmit page, it does not seem clear to me (a newbie) how to use srt-live-transmit.
I have srt-tools installed on Ubuntu 21.10 showing:
`Built with SRT Library version: 1.4.2
SRT Library version: 1.4.2`
Just trying to record 30 seconds of the raw SRT stream coming from OBS which is streaming on:
`srt://127.0.0.1:10000?mode=listener`
Looking to save as a .TS file.  What would that command look like?  
`srt-live-transmit srt://127.0.0.1:10000 file://out.ts`
Gets: "Unsupported target type"
Thanks in advance!

**Comment by tvadi** [comment]
cd to the folder you want to save the file..  -t:60  > makes roughly a minute file

`srt-live-transmit -t:60 srt://127.0.0.1:10000 file://con > test.ts`

**Comment by maxsharabayko** [comment]
`srt-live-transmit` does not support output to file. Only to `stdout` via `file://con`.
