### ISSUE TITLE
large of packets are dropped when I test between china and germany ecs server.

### ISSUE THREAD

**Issue by shenlei190810** [Haivision/srt#2249]
I have two ecs server, one in Beijing, China; and another in Frankfurt, Germany. I have test the ping rtt is about 200ms. I have deployed the srt server in the two ecs, ecs in Beijing as srt-client, and ecs in Frankfurt as srt-server. Now I send tcp data in beijing, and the srt-client trans it to srt packet , then proxy to srt-server, the srt-server trans the srt packet to tcp server.
![未命名文件 (4)](https://user-images.githubusercontent.com/3354569/154235759-fed42adb-116b-4e55-b508-c316a186d014.png)

I have captured the srt data with tcpdump, and I found almost no packets miss.

the receive side log is as below
[error2.log](https://github.com/Haivision/srt/files/8078588/error2.log)
.
the tcpdump packet capture,download and change the file suffix to pcap, then you can analysis with wireshark.
[srt.log](https://github.com/Haivision/srt/files/8078725/srt.log)

**Comment by maxsharabayko** [comment]
In the log I see RCV-DROPPED messages starting from seqno %875477239,
```
@869911235:RCV-DROPPED 31 packet(s), packet seqno %875477239 delayed for 556.761 ms
```
while the network capture only has packets up to seqno 837019961.

The very first packet with seqno 799665852 is being reported lost for almost three seconds (from 9.766 to 11.959 seconds), and is repeatedly re-transmitted.
On which side was the capture made? It looks as if on the receiver side, but if so, it is strange that the packet is captured by tcpdump, but has never reached the receiver.

Which SRT version/commit are you using?

**Comment by shenlei190810** [comment]
> The very first packet with seqno 799665852 is being reported lost for almost three seconds (from 9.766 to 11.959 seconds), and is repeatedly re-transmitted. On which side was the capture made? It looks as if on the receiver side, but if so, it is strange that the packet is captured by tcpdump, but has never reached the receiver.

I am sorry, the packet capture and log do not match; I just want to emphasize that there is really no data is lost when I capture. my srt version is 1.4.4

**Comment by maxsharabayko** [comment]
If you could collect logs and related network captures, that would help diagnose the issue.
