### ISSUE TITLE
Installing SRT on RasberryPie

### ISSUE THREAD

**Issue by OekPhlesym** [Haivision/srt#2251]
Hey Everyone, i m new to Github as well a beginner in Linux. I m using various distros of Linux and was able to install "srt-tools" on mint , ubuntu and manjaro ....however on the rapberryPie which is debbian,i cannot seem to install it let alone comprehend fully what the issues are on my side. 

From following the instructions of the cli used to install it. Copying  the 

" sudo apt-get install tclsh pkg-config cmake libssl-dev build-essential
./configure
make"

brings up error saying " -bash: ./configure: NO such file directory" any help, I would really appreciate your assistance thanks.

**Comment by maxsharabayko** [comment]
Hi,

> brings up error saying " -bash: ./configure: NO such file directory" any help, I would really appreciate your assistance thanks.

The `./configure` file is located in the root folder of the project. Please ensure you are running it from that folder.

```shell
cd <your_srt_source_dir>
./configure
```

**Comment by ethouris** [comment]
This may be a misleading error report for lacking `tclsh` command in your system. You need this to run `configure`. Note that this is only an optional convenience wrapper for `cmake`, so if you can't provide tclsh in your system, you can always use cmake directly.

**Comment by ethouris** [comment]
This might be also a misleading error report for lacking `tclsh` command. Although the installation instruction requires installing tcl package, might be there's some problem with this on your system, so please check if you can run `/usr/bin/tclsh` (as the first line in `configure` requires).
