### ISSUE TITLE
[BUG]Memory not released in use

### ISSUE THREAD

**Issue by Jake-Ye** [Haivision/srt#2263]
Memory is not freed until srt_cleanup() is called method, using  After the srt_cleanup(), the socket ends. Can't you free the memory automatically?

**Comment by ethouris** [comment]
Which exactly memory or which objects are not freed? Note that some of the global data are intended to last until there's no more need to use them.

The problem with calling `srt_cleanup()` in the destructor is that there's no guarantee of the order of destruction of the global objects, while it is required in case of SRT, as a library, is that its global objects must be freed before any part of the application or the library that depends on it. I've tried that before with the demo applications and it resulted in crashes.

**Comment by Jake-Ye** [comment]
Thank you for your reply. After my detailed verification, I found that the memory leak was caused by my use. After resolution, there is no memory leak when sending and receiving data. i 'm sorry.
