### ISSUE TITLE
[BUG] StreamID in the API documentation is Misnamed and Misleading

### ISSUE THREAD

**Issue by jlsantiago0** [Haivision/srt#2281]
The whole concept of the current implementation of StreamID is misnamed and misleading and is currently only referenced here:

The Access Control Documentation https://github.com/Haivision/srt/blob/master/docs/features/access-control.md

It says that StreamID is one type of information that is interchanged with caller-listener when a connection is being established. 'interchanged' implies that information is being exchanged in both direction but this is not the case. As it is only being sent from the caller to the listener and needs to be documented better that it is not 'interchanged' but sent to the listener from the caller.

Also what does this have to with a StreamID? It has nothing to do with identifying a Stream. So it should be named as AccessControl or something that does not imply Stream information.

Also the access control it seems only applies in one direction. It seems like it would be more useful if AccessControl information could be exchanged in both directions.

Furthermore, the impact of the SteramID concept appears rather undefined for Rendevous mode connections. Who is caller and who is listener in that situation? Who can tell? It might be one side, one time and the other side another time?

This concept should be better baked before it gets widely used.

**Comment by maxlapshin** [comment]
>  It has nothing to do with identifying a Stream. 

It can be used to identify stream name, so it is not only about access control, it is also about requested stream.

You should remember about scenario, when server works with dozens and hundreds of streams and single port can be used for them.

**Comment by ethouris** [comment]
Ok, maybe the statement "interchanged" wasn't very fortunate, although in the document it isn't said that StreamID itself is being interchanged, but that it belongs to the set of information interchanged between caller and listener. Also the statement "interchange" only says that the information is being sent in both directions, but not that the information is for exactly the same purpose. In the same paragraph there's also a precise declaration that StreamID is set on the caller and can be retrieved on the listener side.

As per the StreamID name - it has some historical explanation as it has started for only one purpose, that is, to be able to distinguish various purposes of the connection to one listener. Might be that it would be reasonable to change the name to avoid confusion. For that purpose I think the option could be renamed into `SRTO_STREAMINFO` and StreamInfo would be the new feature name, of course with the old name remaining.
