### ISSUE TITLE
[BUG] StreamID containing bytes of value 0 not used consistently

### ISSUE THREAD

**Issue by jlsantiago0** [Haivision/srt#2284]
The documentation seems to indicate that StreamID is a blob whose meaning is up to the application and application business logic to use. However there are places in the SRT library where StreamID is utilized as a std::string with a size and other places where it is treated as a C-String. So the library breaks situations where a user wants to have values of '\0' as bytes in the StreamID.

**Comment by maxsharabayko** [comment]
That's true. It is not a limitation of the SRT protocol on the wire, as the StreamID Extension has the length field. Thus it can have any number of null characters inside.
However, the library converts the content into a null-terminated string. As well as accepts it as a string via the `SRTO_STREAMID` socket option.

```
   +=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+
   |         Extension Type        |        Extension Length       |
   +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
   |                                                               |
   +                       Extension Contents                      +
   |                                                               |
   +=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+=+
```

**Comment by jlsantiago0** [comment]
Right the library should not be enforcing any particular encoding of this unless or until it is part of the Protocol Specification.

**Comment by ethouris** [comment]
Excuse me, I must have missed something. Do you know any cases of "losing part of the string"?

I found one problem in `StringStorage`, for example:
```
    std::string str() const
    {
        return len == 0 ? std::string() : std::string(stor);
    }
```
This should use `std::string(stor, len)`, otherwise it will stop on first NUL character. Another is here:

```
               m_config.sStreamName.set(target, strlen(target));
```

These are problems that should be fixed.
