### ISSUE TITLE
How to calculate the time from entering the send buffer to the receive buffer of a packet during srt-test-live transmission

### ISSUE THREAD

**Issue by ypp1104** [Haivision/srt#2299]
How to calculate the time from entering the sending buffer to the receiving buffer of a data packet during srt-test-live transmission, this data packet can be a regular data packet and a retransmission packet or a control packet
My idea is to subtract the incoming buffer time from the packet time in the receive queue, but I don't know which one is the time the packet goes into the send buffer. and where do I need to calculate that can be printed out?

**Comment by maxsharabayko** [comment]
There is no API to achieve the goal. But one could dig into the code to extract those times.
