### ISSUE TITLE
[BUG] getAvailRcvBufferSizeNoLock() reports a negative value causing srt-live-transmit to shut down an otherwise healthy connection

### ISSUE THREAD

**Issue by TerjeGundersen** [Haivision/srt#2306]
**Describe the bug**
I'm working on writing a TS transmitter using SRT library. I only have one function that actually calls `srt_send()` and I use this function regardless of whether the connection was established in listener mode, caller mode or rendezvous. Caller & listener mode works well, however, when the connection has been established using rendezvous mode, I get this output on the `srt-live-transmit` application that attempts to receive the TS:

```
./srt-live-transmit srt://10.0.28.232:8888?mode=rendezvous udp://10.0.28.232:9999
Media path: 'srt://10.0.28.232:8888?mode=rendezvous' --> 'udp://10.0.28.232:9999'
12:59:58.115288/SRT:RcvQ:w1*E:SRT.cn: cookieContest: agent=-705126473 peer=101587914
12:59:58.119616/SRT:RcvQ:w1*E:SRT.qr: @1013203658:SEQUENCE DISCREPANCY. BREAKING CONNECTION. seq=1518897272 buffer=(1518897272:1518897271+1518905462), 1027654368 past max. Reception no longer possible. REQUESTING TO CLOSE.
```

**Some clues from our friend gdb**
![Preliminary debugging](https://user-images.githubusercontent.com/4103367/164470455-3dc30f85-8ee0-4f41-9815-c65ebd74fbd6.png)
It appears that it is possible for the receive buffer to report that it's available size is negative.
This may prove to be a good starting point to investigate this bug.

**What goes over the wire?**
![Wireshark](https://user-images.githubusercontent.com/4103367/164471741-343a4eaf-7756-4455-8a98-9725f3466ae8.png)
Sometimes there are more than one packet sent before the receiving application (`srt-live-transmit`) shuts down the connection, but usually far less than 10, and always >=1. _Note that this capture is not from the same execution as the output pasted above._

**To Reproduce**
This may prove very difficult as I'd have to give you my code for the transmitter.
However, I have followed the examples in the documentation to setup a rendezvous connection and simply
used srt_send() to transmit over that connection once established. 

**Expected behavior**
Expected behavior would be `srt-live-transmit` not shutting down the connection due to a "sequence discrepancy" and continuing reception of data as normal.

**Workaround**
I have found a simple work-around for this issue, which is to disable the use of the so-called "new" receiver buffer and compiling
SRT with the "old" implementation of the receiver buffer. I did this by adding the following line to `CMakeLists.txt`:
 `set (ENABLE_NEW_RCVBUFFER OFF)`

**Transmitting machine details**
 ```[root@btech ~]# neofetch
        #####           root@btech 
       #######          ---------- 
       ##O#O##          OS: x86_64 
       #######          Host: VirtualBox 1.2 
     ###########        Kernel: 3.10.0-1160.el7.x86_64 
    #############       Uptime: 10 days, 5 hours, 28 mins 
   ###############      Packages: 523 (rpm) 
   ################     Shell: bash 4.2.46 
  #################     Terminal: /dev/pts/1 
#####################   CPU: Intel i7-7820X (8) @ 3.599GHz 
#####################   GPU: VirtualBox Graphics Adapter 
  #################     Memory: 8409MiB / 15884MiB
  ```
SRT Version 1.4.4

**Receiving machine details**
```                 ..
               .PLTJ.
              <><><><>
     KKSSV' 4KKK LJ KKKL.'VSSKK        terjegun@localhost.localdomain 
     KKV' 4KKKKK LJ KKKKAL 'VKK        ------------------------------ 
     V' ' 'VKKKK LJ KKKKV' ' 'V        OS: CentOS Linux 7 (Core) x86_64 
     .4MA.' 'VKK LJ KKV' '.4Mb.        Host: VirtualBox 1.2 
   . KKKKKA.' 'V LJ V' '.4KKKKK .      Kernel: 3.10.0-1160.59.1.el7.x86_64 
 .4D KKKKKKKA.'' LJ ''.4KKKKKKK FA.    Uptime: 5 hours, 39 mins 
<QDD ++++++++++++  ++++++++++++ GFD>   Packages: 2138 (rpm), 1 (pkg) 
 'VD KKKKKKKK'.. LJ ..'KKKKKKKK FV     Shell: bash 4.2.46 
   ' VKKKKK'. .4 LJ K. .'KKKKKV '      Terminal: /dev/pts/0 
      'VK'. .4KK LJ KKA. .'KV'         CPU: Intel i7-7820X (8) @ 3.599GHz 
     A. . .4KKKK LJ KKKKA. . .4        GPU: 00:02.0 VMware SVGA II Adapter 
     KKA. 'KKKKK LJ KKKKK' .4KK        Memory: 3761MiB / 23379MiB 
     KKSSA. VKKK LJ KKKV .4SSKK
              <><><><>                                         
               'MKKM'                                          
                 ''
```
SRT Version 1.4.4

Both receiving and transmitting machines are virtual machines hosted on the same hardware.

**Comment by TerjeGundersen** [comment]
I find it probable that the bug is caused by `srt-live-transmit` storing the return value of `srt::CUDT::getAvailRcvBufferSizeNoLock()` in an integer, when the function returns an unsigned long. I will when time allows test this and if I am correct create a PR.

**Comment by ethouris** [comment]
What exactly do you man "storing the return value" - the one you passed here by reference or which one? I would keenly see it reproduced, even with modifications of the app code.

BTW the way how you use these `sockaddr_in` is kinda nonportable and can lead to problems. I'd recommend using `sockaddr_any` from the SRT source code header file `srtcore/netinet_any.h`.

**Comment by maxsharabayko** [comment]
> However, I have actually tested storing the return value of the function in a `long` rather than an `int` and it seems to have solved the problem.

From your code sample, you don't change the default receiver buffer size. I am confused how you get a negative value.

Could you please share the values of using gdb or adding logs:
- `CRcvBufferNew::m_iStartSeqNo`
- `CUDT::m_iRcvLastAck` from `CUDT::getAvailRcvBufferSizeNoLock()`

**Comment by TerjeGundersen** [comment]
@maxsharabayko Correct, I never change the default receive buffer size. I can run the debugger again tomorrow and get you those values but it's getting late over here, so I'm headed out.
I should say I don't mean that I get a negative value for it from the function. However, in srtcore/core.cpp on line 9934, that function is called and the return value stored in an int, and _that_ is what turns negative.

@ethouris Sorry, I should probably have worded myself better - but now there's a PR that I'm sure makes it obvious: #2307.

As for reproduction, I'm not entirely sure what the best steps towards it is, because the transmitter I am writing is part of a larger software product, so there's no way to send you a working copy of the application as a stand-alone thing. And even if there was it would have no signal to transmit as it gets that through custom APIs. Does Haivision have a Software Probe from Bridgetech  on hand, perhaps? If not, I'll see if I can't reproduce it on one of our hardware probes later, which I know you guys have at least one of on hand.

**Comment by maxsharabayko** [comment]
I reproduced the issue:
```shell
./srt-live-transmit "srt://127.0.0.1:4201?mode=rendezvous&port=4200" udp://127.0.0.1:4202 -v

./bin/srt-xtransmit generate "srt://127.0.0.1:4200?mode=rendezvous&bind=:4201" -v --sendrate 1Mbps
```

The problem is the ISN of the new receiver buffer is not being set properly in case of the rendezvous connection.

**Comment by maxsharabayko** [comment]
The fix should be roughly like this:

```patch
diff --git a/srtcore/buffer_rcv.h b/srtcore/buffer_rcv.h
index a5e113df..440184ba 100644
--- a/srtcore/buffer_rcv.h
+++ b/srtcore/buffer_rcv.h
@@ -109,6 +109,10 @@ public:
     /// Get the starting position of the buffer as a packet sequence number.
     int getStartSeqNo() const { return m_iStartSeqNo; }
 
+    /// Sets the start seqno of the buffer.
+    /// Must be used with caution and only when the buffer is empty.
+    void setStartSeqNo(int isn) { m_iStartSeqNo = isn; }
+
     /// Given the sequence number of the first unacknowledged packet
     /// tells the size of the buffer available for packets.
     /// Effective returns capacity of the buffer minus acknowledged packet still kept in it.
diff --git a/srtcore/core.cpp b/srtcore/core.cpp
index fcc36833..0195749e 100644
--- a/srtcore/core.cpp
+++ b/srtcore/core.cpp
@@ -10035,6 +10035,8 @@ int srt::CUDT::processData(CUnit* in_unit)
                     LOGC(qrlog.Error, log << CONID() <<
                             "SEQUENCE DISCREPANCY. BREAKING CONNECTION."
                             " seq=" << rpkt.m_iSeqNo
+                            << " m_RcvLastAck=" << m_iRcvLastAck
+                            << " startSeqNo= " << m_pRcvBuffer->getStartSeqNo()
                             << " buffer=(" << m_iRcvLastSkipAck
                             << ":" << m_iRcvCurrSeqNo                   // -1 = size to last index
                             << "+" << CSeqNo::incseq(m_iRcvLastSkipAck, m_pRcvBuffer->capacity()-1)
diff --git a/srtcore/core.h b/srtcore/core.h
index fe70b38f..771dec56 100644
--- a/srtcore/core.h
+++ b/srtcore/core.h
@@ -896,6 +896,15 @@ private: // Timers
         m_iRcvLastSkipAck = m_iRcvLastAck;
         m_iRcvLastAckAck = isn;
         m_iRcvCurrSeqNo = CSeqNo::decseq(isn);
+
+        sync::ScopedLock rb(m_RcvBufferLock);
+        if (m_pRcvBuffer)
+        {
+            // TODO: dropp all packets if the buffer is not empty
+            if (m_pRcvBuffer->empty())
+                std::cerr << "Rbuf not empty\n";
+            m_pRcvBuffer->setStartSeqNo(m_iRcvCurrSeqNo);
+        }
     }
 
     int32_t m_iISN;                              // Initial Sequence Number
```

Hello #2268.

**Comment by gou4shi1** [comment]
Then https://github.com/Haivision/srt/commit/c76f43df6887b414799211441b733fc2a94abdf5 can be reverted :)
Previously, I tried to minimize the diff, so I didn't change  `setInitialRcvSeq()`, but if it can be changed, it would be great :)
