### ISSUE TITLE
Auth SRT-to-SRT connection

### ISSUE THREAD

**Issue by dangolbeeker** [Haivision/srt#2314]
What options besides passwords do I have? Is jwt possible? I want the users to authenticate and view the stream from within there browser like hls. Think PPV event.

**Comment by ethouris** [comment]
Inside SRT there's only passphrase possible. In order to use any other method of authentication you have to use it on your own. Using this you can exchange the passphrase.

**Comment by dangolbeeker** [comment]
Is there a way to restrict password sharing between users?

**Comment by ethouris** [comment]
I don't exactly understand what you mean, but this thing is beyond SRT anyway. In SRT you can only use a single passphrase, there are no users, and the only way how both connection parties have the passphrase is that both "somehow know" it.

**Comment by maxsharabayko** [comment]
You can let different users or user groups have different passphrases, see [Access Control Guidelines](https://github.com/Haivision/srt/blob/master/docs/features/access-control.md#example).
A passphrase can also be something exchanged aside from SRT, e.g. via OAUTH granting user access to the server, the server can then provide a passphrase via a secure channel (e.g. HTTPS) that his app would automatically use to establish a secure SRT connection.

**Comment by ethouris** [comment]
As I said, SRT supports only encryption through the passphrase, although passphrase can be also set as dedicated for particular incoming connection using the listener callback mechanism. Whatever other mechanisms can be used basing on these mechanisms, it's beyond SRT.
