### ISSUE TITLE
[BUG] srt_getsockname()  addr length fail.

### ISSUE THREAD

**Issue by mGaosi** [Haivision/srt#2334]
**Describe the bug**
srt_getsockname() `namelen` always =16.

sockaddr_any::size(int family) use sizeof(sockaddr_in) or sizeof(sockaddr_in6). It's always align with  `sockaddr`.

**Desktop (please provide the following information):**
 - OS: All

**Comment by maxsharabayko** [comment]
Not sure I understood the issue.
`srt_getsockname(SRTSOCKET, sockaddr* name, int* namelen)` expects a pointer to a `sockaddr` structure, but any compliant structure is expected to be submitted.

For example, `sockaddr_storage`:
```c++
sockaddr_storage name;
int namelen = sizeof sockaddr_storage;
srt_getsockname(m_listener_sock, (sockaddr*) &name, &namelen);
```

Or `sockaddr_in6`:
```c++
sockaddr_in6 name;
int namelen = sizeof sockaddr_in6;
srt_getsockname(m_listener_sock, (sockaddr*) &name, &namelen);
```

**Comment by mGaosi** [comment]
@maxsharabayko That's my fault.  I think, I was mistake understood the relationship between `sockaddr` and `sockaddr_in6`.
At first I thought `sizeof (SOCKADDR) equal sizeof (sockaddr_in6)`, But I understood the meaning of `getsockname` and `srt_getsockname` parameters , when I carefully read their declarations. 

Thanks for your reply.
