### ISSUE TITLE
Question: Binding to a specific NIC

### ISSUE THREAD

**Issue by chenguo123456** [Haivision/srt#2347]
![1653545767(1)](https://user-images.githubusercontent.com/88373004/170433668-477d41ff-c171-4a6e-b190-0a0db2f99232.jpg)
在我设置好参数之后点击RECOED SCREEN 之后的报错

**Comment by chenguo123456** [comment]
![image](https://user-images.githubusercontent.com/88373004/170434585-a9b92bb0-0187-46f1-93de-e0bb5adfe829.png)

**Comment by maxsharabayko** [comment]
这似乎与我们的项目无关。

**Comment by chenguo123456** [comment]
我是用IDEA打开后没有改代码和应用，可以提供帮助吗？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Maxim ***@***.***&gt;; 
发送时间: 2022年5月26日(星期四) 下午3:30
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Haivision/srt] [BUG] (Issue #2347)





 
这似乎与我们的项目无关。

**Comment by chenguo123456** [comment]
我在是查看使用摄像头srt推流的之后，只有使用wifi的情况下才可以推流，这个可以修改吗？谢谢






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Haivision/srt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月26日(星期四) 下午3:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Haivision/srt] [BUG] (Issue #2347)





 
这似乎与我们的项目无关。

**Comment by gou4shi1** [comment]
@chenguo123456 请用英文描述清楚您的使用场景，这个项目的维护者不是中国人  :）

**Comment by chenguo123456** [comment]
Demo只有kotlin语言吗？有java的版本吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Haivision/srt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月26日(星期四) 下午4:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Haivision/srt] [BUG] (Issue #2347)





 
@chenguo123456 请用英文描述清楚您的使用场景，这个项目的维护者不是中国人  :）

**Comment by chenguo123456** [comment]
1.I want to use the SRT + camera video transmission function in the demo, but now the demo can only be transmitted when WiFi is connected. How can I modify it to directly transmit without WiFi?
2.Is the SRT used in the demo caller or listener? Am I free to choose?&nbsp;Can I set the time to request a connection?
3.Today's question: when testing the demo of screen recording, I set the IP and port of SRT and click start screen recording. Which question I raised today is the screenshot. Can you give me some suggestions to solve it?




Thank you !!





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Haivision/srt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月26日(星期四) 下午4:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Haivision/srt] [BUG] (Issue #2347)





 
@chenguo123456 请用英文描述清楚您的使用场景，这个项目的维护者不是中国人  :）

**Comment by ethouris** [comment]
1. If you have multiple network interfaces and you want to chose which one to use, you can use `srt_bind` on the connecting socket with the IP address that is set on the device you want to use. Otherwise it will use the "system selected default one".
2. Not sure which demo you mean, but usually all demo apps in our repo allow to choose. As per timeout, the default connection timeout is 3s, but you can change using the `SRTO_CONNTIMEO` socket option.
3. I can't see any described problem to solve here, or I'm confused...

**Comment by chenguo123456** [comment]
For the first question, what I want to do is to rely on my mobile phone to connect to SRT or RTMP instead of WiFi. Can you understand?If your advice is aimed at this problem, I don't understand it. Can you explain it in more detail? thanks







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Haivision/srt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月27日(星期五) 下午2:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Haivision/srt] [BUG] (Issue #2347)





  
If you have multiple network interfaces and you want to chose which one to use, you can use srt_bind on the connecting socket with the IP address that is set on the device you want to use. Otherwise it will use the "system selected default one".
 
Not sure which demo you mean, but usually all demo apps in our repo allow to choose. As per timeout, the default connection timeout is 3s, but you can change using the SRTO_CONNTIMEO socket option.
 
I can't see any described problem to solve here, or I'm confused...

**Comment by ethouris** [comment]
No, I don't understand. I get WiFi as just a network medium that can carry out SRT or RTMP as well. An alternative to WiFi would be at best a cable network, which can also carry out SRT or RTMP. SRT can also work on the mobile phone, there's for example Haivision Play application that can also play an SRT stream.

**Comment by chenguo123456** [comment]
Thank you for your reply. When using app, you can only push streams when connecting to WiFi. Can you understand that you can also push streams when using 5g without WiFi?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Haivision/srt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月27日(星期五) 下午4:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Haivision/srt] [BUG] (Issue #2347)





 
No, I don't understand. I get WiFi as just a network medium that can carry out SRT or RTMP as well. An alternative to WiFi would be at best a cable network, which can also carry out SRT or RTMP. SRT can also work on the mobile phone, there's for example Haivision Play application that can also play an SRT stream.

**Comment by ethouris** [comment]
I know nothing about 5G, sorry. I heard that there are some complications for a typical network usage and mainly UDP protocol, some people have mentioned it here. I don't know if any of them have been solved so far.

**Comment by chenguo123456** [comment]
I mean, after installing the app on the mobile phone, use the mobile card to push the stream





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Haivision/srt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月27日(星期五) 下午4:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Haivision/srt] [BUG] (Issue #2347)





 
I know nothing about 5G, sorry. I heard that there are some complications for a typical network usage and mainly UDP protocol, some people have mentioned it here. I don't know if any of them have been solved so far.

**Comment by chenguo123456** [comment]
Tell me your Facebook account and add some friends. In this way, it will be more convenient to communicate. Is that ok?





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Haivision/srt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月27日(星期五) 下午4:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Haivision/srt] [BUG] (Issue #2347)





 
I know nothing about 5G, sorry. I heard that there are some complications for a typical network usage and mainly UDP protocol, some people have mentioned it here. I don't know if any of them have been solved so far.

**Comment by chenguo123456** [comment]
Is this the way to choose the connection?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Haivision/srt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月27日(星期五) 下午4:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Haivision/srt] [BUG] (Issue #2347)





 
I know nothing about 5G, sorry. I heard that there are some complications for a typical network usage and mainly UDP protocol, some people have mentioned it here. I don't know if any of them have been solved so far.

**Comment by ethouris** [comment]
From mobile you can use SRT just like with the network.

Just FYI, I don't use social media for communication at work.

**Comment by chenguo123456** [comment]
Yes, I want to use mobile network SRT transmission, so I can choose whether to use WiFi or mobile network. Can this be modified in the demo source code? thanks





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Haivision/srt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月27日(星期五) 下午5:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Haivision/srt] [BUG] (Issue #2347)





 
From mobile you can use SRT just like with the network.
 
Just FYI, I don't use social media for communication at work.

**Comment by maxsharabayko** [comment]
Binding to a specific IP or using [SRTO_BINDTODEVICE](https://github.com/Haivision/srt/blob/master/docs/API/API-socket-options.md#SRTO_BINDTODEVICE) might be what you are looking for.
Please refer to [docs/apps/srt-live-transmit.md#medium-srt](https://github.com/Haivision/srt/blob/master/docs/apps/srt-live-transmit.md#medium-srt) if you mean `srt-live-transmit` by the "demo source code".

**Comment by ethouris** [comment]
In general, you can bind the socket to the IP address of the device you want to use (using `adapter` parameter). The above option can be also used through the `bindtodevice` parameter, as long as it works on that platform.

**Comment by chenguo123456** [comment]
Can Android SRT transmit data only when WiFi is connected？





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Haivision/srt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月30日(星期一) 下午4:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Haivision/srt] [BUG] (Issue #2347)





 
In general, you can bind the socket to the IP address of the device you want to use (using adapter parameter). The above option can be also used through the bindtodevice parameter, as long as it works on that platform.

**Comment by ethouris** [comment]
Only if the UDP packets sent from the current device can reach the other device and vice versa.

**Comment by chenguo123456** [comment]
Thank you for your reply.


I didn't understand what you meant. The question I want to ask is whether SRT transmission can be used when the mobile phone no longer has WiFi. Thank you.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Haivision/srt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月28日(星期四) 晚上6:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Haivision/srt] Question: Binding to a specific NIC (Issue #2347)





 
Only if the UDP packets sent from the current device can reach the other device and vice versa.

**Comment by ethouris** [comment]
Whether this is WiFi or any other kind of medium, it doesn't matter. What matters is that there exist a possibility to pass UDP packets on the network link to and from the other device (in both directions). Any medium that satisifes this condition can be used with SRT.

**Comment by chenguo123456** [comment]
好的，我编辑一下，辛苦您了








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Haivision/srt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月26日(星期四) 下午4:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Haivision/srt] [BUG] (Issue #2347)





 
@chenguo123456 请用英文描述清楚您的使用场景，这个项目的维护者不是中国人  :）

**Comment by chenguo123456** [comment]
Thank you for your reply.


Now I can understand what you mean. Now the problem I encounter is that when downloading the demo on the official website and transmitting the video, it is OK to use WiFi. The receiving end can receive the picture, but when using the mobile phone card, the receiving end cannot receive the picture. How do I deal with this? thank you!






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Haivision/srt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月28日(星期四) 晚上6:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Haivision/srt] Question: Binding to a specific NIC (Issue #2347)





 
Whether this is WiFi or any other kind of medium, it doesn't matter. What matters is that there exist a possibility to pass UDP packets on the network link to and from the other device (in both directions). Any medium that satisifes this condition can be used with SRT.
