### ISSUE TITLE
Non-blocking Modes Cannot close directly

### ISSUE THREAD

**Issue by Jake-Ye** [Haivision/srt#2349]
Hello！

In non blocking mode.Caller disconnected. But the listener did not quit directly. Still receiving data. Even if I take the initiative to close it, I can't stop receiving. Is this normal? How to make the listener stop directly？（Currently, a packet of data is sent every 0.1 Ms）

**Comment by ethouris** [comment]
That's not possible to have one party disconnected and the other receiving data because there's no one to send them. Might be that there's still something in the flight, but for a very short time. Can you show us your connection details?

**Comment by Jake-Ye** [comment]
> That's not possible to have one party disconnected and the other receiving data because there's no one to send them. Might be that there's still something in the flight, but for a very short time. Can you show us your connection details?

hello！
The Caller establishes a connection with the listener and sends a packet of data every 0.1 milliseconds. However, 
caller use srt_epoll_release、srt_close、srt_cleanup Active disconnect.the listener can still receive data through the srt_recvmsg method for a long time, and can not disconnect until the data is received,May be reading cached data.However, when I view the document, it can be stopped immediately under the non blocking model. How can I do this?Is this information useful？

**Comment by Jake-Ye** [comment]
> Hi! By "listener" do you mean the socket accepted by the listener or the listener socket itself? Those are two different beasts. What was the reason for a caller to disconnect? Peer idle timeout or a normal closing of a connection?

"listener" mean socket accepted. "caller" mean socket connected,disconnect reason is Caller actively disconnects.

**Comment by Jake-Ye** [comment]
> > That's not possible to have one party disconnected and the other receiving data because there's no one to send them. Might be that there's still something in the flight, but for a very short time. Can you show us your connection details?
> 
> hello！ The Caller establishes a connection with the listener and sends a packet of data every 0.1 milliseconds. However, caller use srt_epoll_release、srt_close、srt_cleanup Active disconnect.the listener can still receive data through the srt_recvmsg method for a long time, and can not disconnect until the data is received,May be reading cached data.However, when I view the document, it can be stopped immediately under the non blocking model. How can I do this?Is this information useful？

SRT Version is 1.5.0

**Comment by Jake-Ye** [comment]
Caller:

- (void)sendCacheData
{
    while (1) {
        if (!_connected) {
            return;
        }
        [self didSend:data];
        usleep(100);
    }
}

- (void)didSend:(NSData *)data
{
    if (![self waitForReadReady:_eid :self.ss]) {
        return;
    }
    
    const void *buffer = [data bytes];
    int length = (int)[data length];
    
    int st = srt_sendmsg2(_ss, buffer, length, nil);
    if (st == SRT_ERROR) {
        NSLog(@"srt_sendmsg: %s\n", srt_getlasterror_str());
    }
    NSLog(@"sending");
}

- (void)close
{
    if (_eid != -1) {
        srt_epoll_release(_eid);
    }
    int st = srt_close(_ss);
    if (st == SRT_ERROR) {
        NSLog(@"srt_close: %s\n", srt_getlasterror_str());
        return;
    }
    NSLog(@"srt_cleanup");
    srt_cleanup();
}

Listener:

- (void)accept:(int)read_modes
{
    struct sockaddr_storage their_addr;
    int addr_size = sizeof(their_addr);
    int their_fd = 0;

    their_fd = srt_accept(self.ss, (struct sockaddr*)&their_addr, &addr_size);

    if (their_fd == SRT_ERROR) {
        NSLog(@"srt_accept: %s\n", srt_getlasterror_str());
        return;
    }
    
    srt_epoll_add_usock(_eid, their_fd, &read_modes);
    srt_epoll_remove_usock(_eid, self.ss);

    while (1) {
        
        if (![self waitForReadReady:_eid :their_fd]) {
            NSLog(@"waitForRead: %s\n", srt_getlasterror_str());
            [self close];
            return;
        }
        
        void *buf = malloc(2048);
        int st = srt_recvmsg(their_fd, buf, 2048);
        if (st == SRT_ERROR) {
            NSLog(@"srt_recv: %s\n", srt_getlasterror_str());
            
            if (_delegate && [_delegate respondsToSelector:@selector(socketDidDisConnected:)])
            {
                [_delegate socketDidDisConnected:self];
            }
            return;
        }
        NSData *data = [NSData dataWithBytesNoCopy:buf length:st freeWhenDone:YES];
        if (_delegate && [_delegate respondsToSelector:@selector(socket:recv:)]) {
            [_delegate socket:self recv:data];
        }
    }
}

**Comment by Jake-Ye** [comment]
Caller:

-(void)sendCacheData
{
   while (1) {
      if (!_connected) {
       return;
      }
      [self didSend:data];
      usleep(100);
   }
}

-(void)didSend:(NSData *)data
{
     if (![self waitForReadReady:_eid :self.ss]) {
         return;
     }

     const void *buffer = [data bytes];
     int length = (int)[data length];

     int st = srt_sendmsg2(_ss, buffer, length, nil);
     if (st == SRT_ERROR) {
          NSLog(@"srt_sendmsg: %s\n", srt_getlasterror_str());
     }
     NSLog(@"sending");
}

-(void)close
{
     if (_eid != -1) {
          srt_epoll_release(_eid);
     }
     int st = srt_close(_ss);
     if (st == SRT_ERROR) {
           NSLog(@"srt_close: %s\n", srt_getlasterror_str());
           return;
     }
     NSLog(@"srt_cleanup");
     srt_cleanup();
}

Listener:

-(void)accept:(int)read_modes
{
       struct sockaddr_storage their_addr;
       int addr_size = sizeof(their_addr);
       int their_fd = 0;

       their_fd = srt_accept(self.ss, (struct sockaddr*)&their_addr, &addr_size);

       if (their_fd == SRT_ERROR) {
             NSLog(@"srt_accept: %s\n", srt_getlasterror_str());
             return;
       }

       srt_epoll_add_usock(_eid, their_fd, &read_modes);
       srt_epoll_remove_usock(_eid, self.ss);

       while (1) {

            if (![self waitForReadReady:_eid :their_fd]) {
                   NSLog(@"waitForRead: %s\n", srt_getlasterror_str());
                   [self close];
                   return;
            }
  
            void *buf = malloc(2048);
            int st = srt_recvmsg(their_fd, buf, 2048);
            if (st == SRT_ERROR) {
                  NSLog(@"srt_recv: %s\n", srt_getlasterror_str());
      
            if (_delegate && [_delegate respondsToSelector:@selector(socketDidDisConnected:)])
            {
                  [_delegate socketDidDisConnected:self];
            }
            return;
       }
       NSData *data = [NSData dataWithBytesNoCopy:buf length:st freeWhenDone:YES];
       if (_delegate && [_delegate respondsToSelector:@selector(socket:recv:)]) {
             [_delegate socket:self recv:data];
       }
    }
}

**Comment by Jake-Ye** [comment]
> That's not possible to have one party disconnected and the other receiving data because there's no one to send them. Might be that there's still something in the flight, but for a very short time. Can you show us your connection details?

hello！ The Caller establishes a connection with the listener and sends a packet of data every 0.1 milliseconds. However, caller use srt_epoll_release、srt_close、srt_cleanup Active disconnect.the listener can still receive data through the srt_recvmsg method for a long time, And the connection cannot be disconnected until all data is received. This may be because all the data in the completion cache has not been read. However, when I view the document, it can stop immediately under the non blocking model. What should I do? Is this information usefu？

**Comment by ethouris** [comment]
You said you are using epoll - what exactly data are being received from `srt_recvmsg` after the connection is broken? What's the return value from `srt_recvmsg`?

Note one not exactly obvious thing - if an error occurs, which is also in case when the connection is broken, the IN, OUT and ERR readiness is set on epoll. This is because not everyone subscribes sockets for ERROR readiness, but if the IN event isn't reported on a broken socket, you will never know that it happened. This way, if you don't subscribe for ERROR and you don't check this flag on readiness event, you should try to read and check the return value for error.

**Comment by ethouris** [comment]
@Jake-Ye : please also try to edit the comments with pasted code and put: the  ` marker 3 times at the beginninng and the end. That isn't readable in this form and I can't reformat it myself because Github renderer has damaged too much.

**Comment by Jake-Ye** [comment]
> @Jake-Ye : please also try to edit the comments with pasted code and put: the ` marker 3 times at the beginninng and the end. That isn't readable in this form and I can't reformat it myself because Github renderer has damaged too much.

non-Blocking Mode Service

///Initialization method
- (void)initData
{
    srt_startup();
    self.ss = srt_create_socket();
}

///Binding port
- (void)bind:(NSURL *)uri
{
    NSString *scheme = uri.scheme;
    NSString *host = uri.host;
    int port = uri.port.intValue;
    
    int yes = 1;
    _eid = -1;
    int lsn_modes = SRT_EPOLL_IN | SRT_EPOLL_ERR;
    
    struct sockaddr_in sa;
    sa = [SrtTool sockaddr_innn:host port:port];
    
    srt_setsockflag(self.ss, SRTO_RCVSYN, &yes, sizeof(yes));
    
    int st = srt_bind(self.ss, (struct sockaddr *)&sa, sizeof(sa));
    if (st == SRT_ERROR) {
        [self close];
    }
    
    int blockingMode = 0;
    srt_setsockflag(self.ss, SRTO_RCVSYN, &blockingMode, sizeof(blockingMode));
    _eid = srt_epoll_create();
    srt_epoll_add_usock(_eid, self.ss, &lsn_modes);
    
    st = srt_listen(self.ss, 2);
    if (st == SRT_ERROR) {
        [self close];
    }
    
    if (![self waitForReadReady:_eid :self.ss]) {
        [self close];
    }
    
    socketQueue = dispatch_queue_create([ATSRTSocketQueueName cStringUsingEncoding:NSUTF8StringEncoding], DISPATCH_QUEUE_SERIAL);
    __weak typeof(self)weakSelf = self;
    dispatch_async(socketQueue, ^{
        __strong typeof(weakSelf)strongSelf = weakSelf;
        [strongSelf accept];
    });
}

///receive socket messages
- (void)accept
{
    struct sockaddr_storage their_addr;
    int addr_size = sizeof(their_addr);
    int their_fd = 0;
    their_fd = srt_accept(self.ss, (struct sockaddr*)&their_addr, &addr_size);

    if (their_fd == SRT_ERROR) {
        NSLog(@"srt_accept: %s\n", srt_getlasterror_str());
        return;
    }

    while (1) {
        
        void *buf = malloc(2048);
        int st = srt_recvmsg(their_fd, buf, 2048);
        if (st == SRT_ERROR) {
            NSLog(@"srt_recv: %s\n", srt_getlasterror_str());
            
            if (_delegate && [_delegate respondsToSelector:@selector(socketDidDisConnected:)])
            {
                [_delegate socketDidDisConnected:self];
            }
            return;
        }
        
        NSData *data = [NSData dataWithBytesNoCopy:buf length:st freeWhenDone:YES];
        if (_delegate && [_delegate respondsToSelector:@selector(socket:recv:)]) {
            [_delegate socket:self recv:data];
        }
    }
}

**Comment by Jake-Ye** [comment]
### non-Blocking Client

### Initialization method
- (void)initData
{
    srt_startup();
    self.ss = srt_create_socket();
}

**Comment by Jake-Ye** [comment]
> @Jake-Ye : please also try to edit the comments with pasted code and put: the ` marker 3 times at the beginninng and the end. That isn't readable in this form and I can't reformat it myself because Github renderer has damaged too much.

### step

1、service  Initialization method（initData method）
2、service Binding port （bind:(NSURL *)uri  method）
3、service epoll set up（waitForReadReady:(int)eid :(SRTSOCKET)ss method）
4、service prepare receive socket messages（accept method;when run 8 step,client is disconect，but service can also accept message for a long time until cache is clear,here service will report srt_clearup）

5、client Initialization method（initData method）
6、client connect to Service（connect:(NSURL *)uri method）
7、client send socket data（didSend:(NSData *)data method.Send every 0.1 ms）
8、client disconnect to service（close method）

**Comment by Jake-Ye** [comment]
> You said you are using epoll - what exactly data are being received from `srt_recvmsg` after the connection is broken? What's the return value from `srt_recvmsg`?
> 
> Note one not exactly obvious thing - if an error occurs, which is also in case when the connection is broken, the IN, OUT and ERR readiness is set on epoll. This is because not everyone subscribes sockets for ERROR readiness, but if the IN event isn't reported on a broken socket, you will never know that it happened. This way, if you don't subscribe for ERROR and you don't check this flag on readiness event, you should try to read and check the return value for error.

The exact data returned is the string data sent by the client, and the return value is the byte length of the received data

Do I need to actively check the flag to know the status at this time? But I can't close and clear current socket.

**Comment by ethouris** [comment]
Ok, so the code isn't exactly completely shown (what is `_eid` there, is that a field of the class, like `ss`, why is it then passed to `waitForReady`?), but I get the picture more-less.

First, I don't exactly understand why you are using a non-blocking mode here, while you are still waiting for a readiness of a single socket. But even if, this isn't consistent - you are not waiting for readiness before the call of `srt_recvmsg`. The socket returned from `srt_accept()` will derive most settings from the listener socket, including `SRTO_RCVSYN`, so it will also work in non-blocking mode, so you may even get SRT_EASYNCRCV error here. In this scenario you also have a leak on the memory allocated before reading.

In the case of closing, if the socket is set non-blocking reading, you also get an "asynchronous closing", that is, the socket will only be closed when there are no more data coming to it. For having a timeout for closing anyway you may use `SRTO_LINGER` option, or you can simply set the `SRTO_RCVSYN` flag back to 1 before closing - this way closing will be synchronous.

**Comment by Jake-Ye** [comment]
> > The exact data returned is the string data sent by the client, and the return value is the byte length of the received data
> > Do I need to actively check the flag to know the status at this time? But I can't close and clear current socket now.
> 
> Actually when - internally - the data have been already sent through the network and then the connection got broken, you will still be reading data from the socket, if they are available. If you send them really fast, it's likely you have your receiver buffer full, so an attempt to read will give you the data because they still are in the buffer, and will do so until the buffer is empty, even if the connection was broken a long time ago.
> 
> If you want to be able to close the socket even if there are still available data to read, but synchronize this in time with the broken connection and abandon the available data, you should check periodically the socket state by calling `srt_getsockstate` (for example, after every reading operation) and if the result is `SRTS_BROKEN` (or the state value is greater than the value of `SRTS_CONNECTED`), simply close the socket forcefully.

ok，thank you very much，I give it a try.

**Comment by Jake-Ye** [comment]
> > The exact data returned is the string data sent by the client, and the return value is the byte length of the received data
> > Do I need to actively check the flag to know the status at this time? But I can't close and clear current socket now.
> 
> Actually when - internally - the data have been already sent through the network and then the connection got broken, you will still be reading data from the socket, if they are available. If you send them really fast, it's likely you have your receiver buffer full, so an attempt to read will give you the data because they still are in the buffer, and will do so until the buffer is empty, even if the connection was broken a long time ago.
> 
> If you want to be able to close the socket even if there are still available data to read, but synchronize this in time with the broken connection and abandon the available data, you should check periodically the socket state by calling `srt_getsockstate` (for example, after every reading operation) and if the result is `SRTS_BROKEN` (or the state value is greater than the value of `SRTS_CONNECTED`), simply close the socket forcefully.

ok，thank you very much，I give it a try.

**Comment by ethouris** [comment]
Ok, I made the following test:

Using `srt-file-transmit` I requested to send a large file from one computer to another (it is also using non-blocking mode). This will quickly fill in the buffer, the sender quickly gets to the end, the reader takes it a little longer to receive everything.

When I interrupt the application, it stops reading and closes the socket. I have no possibility to interrupt any blocking call inside, so if the `srt_close()` call would block, it would block the application until the whole contents of the buffer is retrieved. But I can't observe any stopping.

It still might be that it's because the buffer gets purged anyway and it happens so fast that I can't even notice. But still, I have no possibility to have it demonstrated by myself. If you can make a very short, simple program, possibly as unit test, that demonstrates the problem, it would help.

**Comment by ethouris** [comment]
Closing due to too long inactivity. Please reopen if anything new appears in this topic.
