### ISSUE TITLE
How to check the '?latency' value from SRT statistics

### ISSUE THREAD

**Issue by Dronissim0** [Haivision/srt#2354]
Hello,

I hope someone could help me to figure it out. I am looking the way to find out the actual latency value for both caller and receiver sides, via SRT default statistics. 

According to 
https://github.com/Haivision/srt/blob/64d7f69fbd03057beede5cd1b5ba370fad92cc66/apps/socketoptions.hpp
Latency is SRTO_LATENCY,
`{ "latency", 0, SRTO_LATENCY, SocketOption::PRE, SocketOption::INT, nullptr},`

According to  https://github.com/Haivision/srt/blob/master/docs/API/API-socket-options.md#srto_latency
This option sets both [SRTO_RCVLATENCY](https://github.com/Haivision/srt/blob/master/docs/API/API-socket-options.md#SRTO_RCVLATENCY) and [SRTO_PEERLATENCY](https://github.com/Haivision/srt/blob/master/docs/API/API-socket-options.md#SRTO_PEERLATENCY) to the same value specified.

But when I specified something like 
`srt://192.168.1.103:4444?mode=caller&latency=300 on the caller side `
and
`srt://192.168.1.103:4444?mode=listener&latency=300  on the receiver side `

in SRT stats I am still able to see the 
msRcvTsbPdDelay = 120
msRcvTsbPdDelay = 120 

Am I checking the wrong stastics? 

Thank you.

**Comment by ethouris** [comment]
I'm not sure what app you are using, but I tried with `srt-live-transmit` and `srt-test-live` apps from this repo with setting `latency` and also setting only `rcvlatency` on the receiver side with value 500 - and in the json stats I can see 500 in `recv.msTsbPdDelay` field (this reflects actually the `msRcvTsbPdDelay` field from the stats struct).

If you can see the default latency value in the stats, it means that the app somehow failed to set these values properly.
