### ISSUE TITLE
Can srt-tunnel be used in production and is it stable enough?

### ISSUE THREAD

**Issue by seamanm** [Haivision/srt#2356]
Can srt-tunnel be used in production and is it stable enough?

**Comment by ethouris** [comment]
It's an example application and not intended to be used in production. I have found also several cases of deadlocks when closing the connection and the latest version seems not to work (there's a ticket raised against it, but it's on low priority). So it should better be treated as "in development".

**Comment by seamanm** [comment]
i got,thank you for your answer
