### ISSUE TITLE
How to use a local file as a source

### ISSUE THREAD

**Issue by nagyj2** [Haivision/srt#2367]
I am trying to use srt-live-transmit to send a video from a file to a receiver which then decodes to HDMI however I cannot figure out the command to allow me to do this. I looked through the [main documention page](https://github.com/Haivision/srt/blob/master/docs/apps/srt-live-transmit.md) but could not find an example of using a local file as a source. So far I have tried 2 commands but neither worked (although the first command printed `Accepted SRT target connection` to the console when ran but there was no output to HDMI):

    cat test.ts | srt-live-transmit file://con srt://192.168.x.x:4200
    srt-live-transmit file://con srt://192.168.x.x:4200 < test.ts

I can get the smoke testing example working from the documentation so I don't think there is a connection problem. I was also able use srt-live-transmit to receive and record a stream to a file.

**Comment by ethouris** [comment]
None of the tools provided in the SRT repository offers making a live stream from a file.

Among available tools to do it there exist, for example, ffmpeg (with `-re` option) or tsduck.

**Comment by maxsharabayko** [comment]
- [TSDuck](https://tsduck.io/) 
- [tsplay](https://github.com/kynesim/tstools).
