### ISSUE TITLE
Compilation in ancient platforms

### ISSUE THREAD

**Issue by lars18th** [Haivision/srt#237]
Hi,

I like to compile SRT in a Debian 7 distribution. Here the "./configure" prints:

```
Running: cmake .
CMake Error at CMakeLists.txt:18 (cmake_minimum_required):
  CMake 2.8.12 or higher is required.  You are running version 2.8.9
```

So, in order to support ancient distributions, I suggest to do:

1. Add to the configure tool the option "--enable-static", for compiling with minimal shared objects dependency.

2. If you can, distribute simple binaries in the release section. This can be valuable.

3. Add support, in the toolchain for ancient platforms. For example, documenting how to compile on it; or with a cross-compile environment.

I hope this helps.
Regards!

**Comment by ethouris** [comment]
There can be several problems:

1. We already have `--enable-static`, in the planned release, this is currently on the `dev` branch, and if everything goes well, we'll have static and shared version compiled by default, with possibility to turn off particular form. We don't plan to backport this to `master`, as `dev` will be released soon.
2. We don't have much possibilities to distribute the binaries. You should be able to take binaries from the public CI servers, however.
3. The build configuration might be sometimes pretty complicated, especially if multiple various platforms are supported, not even mentioning user options; if not for it, we might stay with pure `make`. And the minimum version of cmake is not just kinda "caprice", but an important precondition that declares the ability of cmake to provide particular functions as well as even understand some specific syntax.

An alternative build system understood by ancient platforms might probably help, but this must be something very simple that will always be treated as a "secondary" (or "unofficial") build system, which must be always annotated about the version to which it was lately updated, and any changes in the project structure that requires build system changes will get updated only the official cmake build.

**Comment by lars18th** [comment]
Hi @ethouris ,

Regarding the use of the CMake, I can compile SRT in Debian 7 doing this:

- Download a recent version of CMake (in my case, v3.10.x doesn't compile, so I used v3.9.6).
- Compile CMake in your target environment, but **not** install it.
- Call to the configure script passing the full path of the compiled CMake:

```
 env PATH=/opt/CMake-3.9.6/bin:$PATH ./configure
```

This it's required for not replacing the distribution packages. After done, you can call the regular _make_ and compile SRT without troubles (if your platform has all requirements).

I suggest to put this info in the documentation. Perhaps other users will use it.

In reference to the `--enable-static` parameter in the configure script, I installed the dev tree (_git clone -b dev https://github.com/Haivision/srt.git_). However:

- The "configure" script doesn't show this parameter (I use `./configure --help`).
- If I use it `./configure --enable-static` I see:

```
CMake Warning:
  Manually-specified variables were not used by the project:

    ENABLE_STATIC
```

And the compilation fails.
Any idea about how to support static compilation?

Regards!

**Comment by lars18th** [comment]
Hi @ethouris ,

The compilation error seems not to be related with the `--enable-static` parameter, as the compilation fails even without it. I can achieve a compilation using `./configure --disable-c++11 --enable-static`, but this only compiles the _lib_ and not the tools (stransmit) when using the _dev_ repo. However, the library isn't compiled statically:

```
$ ldd libsrt.so
        linux-vdso.so.1 =>  (0x00007ffda95b7000)
        libssl.so.1.0.0 => /usr/lib/x86_64-linux-gnu/libssl.so.1.0.0 (0x00007f9091de6000)
        libcrypto.so.1.0.0 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f90919ec000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f90917d0000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f90915c8000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f90913c4000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f90910bd000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f9090e3b000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f9090c25000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f909089a000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f9090683000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f9092310000)
```

I hope you can help me to fix these troubles (using Debian 7 x64).
Thank you!

**Comment by ethouris** [comment]
Well, actually if you want to do it this way, you should be able to actually DO INSTALL cmake, just use the prefix path "/opt/CMake-3.9.6".

I have made a mistake about this `--enable-static`, it's not in the dev branch yet. So far you can only compile either shared or static, and ENABLE_SHARED is the only option for that, so use `--disable-shared` in configure.

The `--disable-c++11` option is for users who don't have a C++11-compliant compiler. The SRT library itself doesn't need C++11, so it's not so important for users who have their own applications and need just the library. The applications, however, require C++11, so you need a more recent compiler to compile them. For gcc it means that it needs at least version 4.8. AFAIR there should be some available binaries for at least so new compiler also for "ancient platforms", I found that for CentOS 6.5, for example.

**Comment by lars18th** [comment]
Hi @ethouris ,

> Well, actually if you want to do it this way, you should be able to actually DO INSTALL cmake, just use the prefix path "/opt/CMake-3.9.6".

Why? If I compile the CMake in the directory "/opt/CMake-3.9.6/", then with the call `env PATH=/opt/CMake-3.9.6/bin:$PATH ./configure` all the work done by the CMake tool it's completed for configuring the SRT package, and the `make` works!
Did I miss something?

> I have made a mistake about this --enable-static, it's not in the dev branch yet. So far you can only compile either shared or static, and ENABLE_SHARED is the only option for that, so use --disable-shared in configure.

I'll check with `--disable-shared`. But if you do some advance with the `--enable-static` then please let me know. Thank you!

> The --disable-c++11 option is for users who don't have a C++11-compliant compiler. The SRT library itself doesn't need C++11, so it's not so important for users who have their own applications and need just the library. The applications, however, require C++11, so you need a more recent compiler to compile them. For gcc it means that it needs at least version 4.8. AFAIR there should be some available binaries for at least so new compiler also for "ancient platforms", I found that for CentOS 6.5, for example.

In Debian 7 we have in the stock repository: gcc-4.4, gcc-4.6 and gcc-4.7. So version 4.8 it's out of scope. As the SRT lib doesn't needs the C++11 extensions, I suggest to include one "stransmit" example/tool that not needs C++11. Why? Because this will enable compatibility with a lot of platforms. So, please think in the whole list of hardware devices without the lastest edge tools.

I hope you can consider these two requests (static and stransmit-legacy). :smile: 
Regards.

**Comment by lars18th** [comment]
Hi @ethouris ,

Regarding the support for ancient platforms, I have done the following test:

I compiled the "master" and "dev" branches in a Debian 7. For compiling the "dev" branch I disabled the C++11 code with `./configure --disable-c++11`. Then for the "dev" branch I get only the library "libsrt.so.1.3.0". And for the "master" branch I get the "stransmit" tool and the lib "libsrt.so.1.2.2".

So I copied the "stransmit" binary from the "master" to a new directory, and I put the "dev" library in this directory (I create the symlink manually). And the result (as expected) is that the tool works right with the "new" library.

Conclusion: The "stransmit" tool in the master does not requires C++11 extensions (even the source code says it). Then I suggest to include this tool renamed as "stransmit-legacy" in the "dev" branch. Without touching anything in the code. With this change, in platforms when the `--disable-c++11` it's used the ancient tool will be available.

You agree?

**Comment by lars18th** [comment]
Hi @ethouris ,

I like to comment that I sucessful compiled the "dev" branch in a Debian 7 with the GCC 4.7. This it's the trick:

- Download and compile the CMake 3.9.6
- Rewrite the file "apps/srt-multiplex.cpp" with "apps/srt-file-transmit.cpp"
- Configure with `env PATH=/opt/CMake-3.9.6/bin:$PATH ./configure`
- Run `make`

The only trouble it's with the source of the "srt-multiplex" tool. I suggest to fix the source to remove the incompatibility, as the "srt-*-transmit" tools compile without problems. I know that the official support for C++11 it's from GCC 4.8; however ancient versions prior to this have support for C++0x (from 4.3 to 4.7). Perhaps ins't complex to support this. What you think?

Regards!

**Comment by ethouris** [comment]
Well, actually it's better if you block the "srt-multiplex" target at all in cmake :)

Show me the compile errors you get from srt-multiplex; I'd bet this is some weird C++11 statement that 4.7 did not yet support. C++0x is the name for C++11 created at the times when they hoped the standard to be ready in 2008 year. So for earlier compilers you might find it under this name, however note that this support is experimental, which means that these compilers support at best only some parts of the new things defined in C++11 standard.

Here is the complete list: https://gcc.gnu.org/projects/cxx-status.html#cxx11

**Comment by lars18th** [comment]
> Well, actually it's better if you block the "srt-multiplex" target at all in cmake :)

Yes! I'll do.

> Show me the compile errors you get from srt-multiplex

I'll try. The idea can be:

1. Fix the compile error in "srt-multiplex".
2. Add a configuration option for enabling _partial C++11_ support; that is for compilers that can compile fine even without C++11 official support. Perhaps with a simple `--enable-force-c++11`. This will act as a workaround for the CMake test of C++11 support when the check fails.

You agree?

**Comment by lars18th** [comment]
Hi @ethouris ,

>Show me the compile errors you get from srt-multiplex

```
[ 79%] Building CXX object CMakeFiles/srt-multiplex.dir/apps/srt-multiplex.cpp.o
In file included from /opt/srt/srt/apps/srt-multiplex.cpp:12:0:
/opt/srt/srt/common/appcommon.hpp: In function ‘sockaddr_in CreateAddrInet(const string&, short unsigned int)’:
/opt/srt/srt/common/appcommon.hpp:152:19: error: ‘invalid_argument’ is not a member of ‘std’
In file included from /opt/srt/srt/apps/srt-multiplex.cpp:16:0:
/opt/srt/srt/common/transmitbase.hpp: At global scope:
/opt/srt/srt/common/transmitbase.hpp:71:5: error: expected class-name before ‘{’ token
/opt/srt/srt/common/transmitbase.hpp: In constructor ‘Source::ReadEOF::ReadEOF(const string&)’:
/opt/srt/srt/common/transmitbase.hpp:73:59: error: expected class-name before ‘(’ token
/opt/srt/srt/common/transmitbase.hpp:73:59: error: expected ‘{’ before ‘(’ token
/opt/srt/srt/common/transmitbase.hpp: At global scope:
/opt/srt/srt/common/transmitbase.hpp:73:9: warning: unused parameter ‘fn’ [-Wunused-parameter]
/opt/srt/srt/apps/srt-multiplex.cpp: In member function ‘void MediumPair::TransmissionLoop()’:
/opt/srt/srt/apps/srt-multiplex.cpp:93:11: warning: unused variable ‘mq’ [-Wunused-variable]
/opt/srt/srt/apps/srt-multiplex.cpp: In function ‘int main(int, char**)’:
/opt/srt/srt/apps/srt-multiplex.cpp:456:7: warning: unused variable ‘cleanupobj’ [-Wunused-variable]
make[2]: *** [CMakeFiles/srt-multiplex.dir/apps/srt-multiplex.cpp.o] Error 1
make[1]: *** [CMakeFiles/srt-multiplex.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by lars18th** [comment]
Hi @ethouris ,

And two different annoying warnings:

```
[ 11%] Building CXX object CMakeFiles/srt.dir/srtcore/core.cpp.o
/opt/srt/srt/srtcore/core.cpp: In member function ‘void CUDT::processCtrl(CPacket&)’:
/opt/srt/srt/srtcore/core.cpp:6064:34: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
```

```
[ 75%] Building CXX object CMakeFiles/srt-file-transmit.dir/common/transmitmedia.cpp.o
/opt/srt/srt/common/transmitmedia.cpp: In member function ‘void SrtCommon::InitParameters(std::string, std::map<std::basic_string<char>, std::basic_string<char> >)’:
/opt/srt/srt/common/transmitmedia.cpp:177:36: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
/opt/srt/srt/common/transmitmedia.cpp:179:39: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
```

That's all that I see in a Debian 7.

**Comment by ethouris** [comment]
Ah, looxlike my error! `std::invalid_argument` is defined in `<stdexcept>`. Actually all reported errors are by this reason. Please add this include in all files for which this error was reported and see if this fixed the problem.

These warnings are because there are compared values of `size_t` and `int`. You can try to make some common type out of them, or use constructor-cast at the comparison expression.

**Comment by lars18th** [comment]
Hi @ethouris ,

> Ah, looxlike my error! std::invalid_argument is defined in <stdexcept>. Actually all reported errors are by this reason. Please add this include in all files for which this error was reported and see if this fixed the problem.

I'm not sure this can be a solution (even I recommend to add the include).
As you can see here: https://github.com/zcash/zcash/issues/1703 The _std::invalid_argument()_ is a common problem with GCC < 4.8.
So it's an unresolved problem with Debian 7.

I'll search for alternatives. :smile: 

> These warnings are because there are compared values of size_t and int. You can try to make some common type out of them, or use constructor-cast at the comparison expression.

I'm not worried about these errors. But I like to report them if you need to fix them (if this has sense).
Regards!

**Comment by lars18th** [comment]
Hi @ethouris ,

Confirmed, if you add the include in the "srt/common/appcommon.hpp" file, then the compilation completes in Debian 7:

```
 #include <string>
 #include <cstring>
+#include <stdexcept>
 // For Options
```
Please, commit the fix!

Futhermore, I like to check if this code it's sufficient portable to compile it in other platforms: OpenWRT and the Raspberry Pi, running in ARM and MIPS.

**Comment by ethouris** [comment]
Yes, please do, and report if you have encountered any more problems! I'll prepare a fix.

**Comment by lars18th** [comment]
Hi @ethouris ,

Current "dev" branch compiles without troubles in Debian 7. So I close this issue.
I'll open another one when I have feeback about compile in OpenWRT and the Raspberry Pi.

In any case, I posted #254 as reference for the current compilation warnings (I think easy to fix).
