### ISSUE TITLE
Condition '2==sek_cnt' is always true

### ISSUE THREAD

**Issue by marakew** [Haivision/srt#2378]
https://github.com/Haivision/srt/blob/e8b713e954345291e8d6e2314d1e5094a6a14179/haicrypt/hcrypt_ctx_rx.c#L192

**Comment by ethouris** [comment]
I'm not exactly convinced about this. This value is set here:
```
		if (hcryptMsg_KM_HasBothSek(km_msg)) {
			sek_cnt = 2;
		} else {
			sek_cnt = 1;
		}
```
This function-like call resolves to a macro that checks a bit flag set on the value extracted as:
```
km_msg[HCRYPT_MSG_KM_OFS_KFLGS]
```
which is a runtime value and by no means can be always equal to something. The km_msg also contains data extracted from the network packet passed from SRT core, so it cannot be any value certainly set anywhere in this code always the same way.

I might be wrong, but that's what results from my code analysis.

**Comment by maxsharabayko** [comment]
Looks like a false positive warning.
Indeed the value is set based on the contents of a packet received on the wire. It is not guaranteed to be always equal to 2.

```c++
if (hcryptMsg_KM_HasBothSek(km_msg)) {
	sek_cnt = 2;
} else {
	sek_cnt = 1;
}
```
