### ISSUE TITLE
BUG: DEV Branch doesn't load "libsrt.so.1" from the local directory

### ISSUE THREAD

**Issue by lars18th** [Haivision/srt#238]
Hi,

When compiling the "master" branch, the "stransmit" binary searchs for the library ("libsrt.so.1") first in the running directory. However, when compiling the "dev" branch the binary searchs all the times in the system directories for the library. This it's annoying! I prefer that the binary uses the local library if a new version it's in the same directory.

Please, can you restore the previous behaviour?
Thank you!

**Comment by ethouris** [comment]
Workaround: add "." to the list of paths in `LD_LIBRARY_PATH`, if you are trying to run stransmit directly from the directory when the build has created it. The version after installation should not have problems with running.

**Comment by lars18th** [comment]
Hi @ethouris ,

> Workaround: add "." to the list of paths in LD_LIBRARY_PATH, if you are trying to run stransmit directly from the directory when the build has created it. The version after installation should not have problems with running.

The use of the LD_LIBRARY_PATH it's a pain in the ***. In a lot of platforms this only generates problems. So the idea is tweak the compile configuration for searching first in the current path (aka ".") for libraries. This is what it's doing the "master" branch. I don't know why it's changed in the "dev" branch.

And don't worry when you _install_ the library. If you don't have any lib in the local directory, then the system library will be in use.

You agree?

**Comment by ethouris** [comment]
I know, that's why this is a workaround, not a fix. There's already waiting a fix, which allows to compile both static and shared libraries, and when static is on, apps will be linked statically. I hope this should fix the problem completely.

**Comment by lars18th** [comment]
> I know, that's why this is a workaround, not a fix. There's already waiting a fix, which allows to compile both static and shared libraries, and when static is on, apps will be linked statically. I hope this should fix the problem completely.

I agree! If we can compile "static" then the problem can be overcome.

In any case, it will be also interesting to search first in the local dir for loading the shared libraries (when used).

Thank you!

**Comment by lars18th** [comment]
Hi @ethouris ,

I found where is the problem, however still I don't have a solution...

First to comment: After you compile the package (dev branch), and previous to install it (so no lib in the system) the tool "./utility-test" can be executed. But the "./stramsmit" (aka "srt-live-transmit") fails.

Why this? See these lines 642 and 645:
https://github.com/Haivision/srt/blob/dev/CMakeLists.txt#L642

The difference it's in the _${FORCE_RPATH}_ environment var.
In the line 638 you can see that you're forcing "-rpath,../lib". And I don't know why?
Are you sure that searching in "../lib" it's required?

What do you think?

**Comment by ethouris** [comment]
That was intended as the trick to make the stransmit work OOTB when it is installed. You'll then have, say with `/usr` prefix, the following locations:

    /usr/bin/srt-live-transmit
    /usr/lib/libsrt.so

This way, `srt-live-transmit` will try to look into a path relative to `/usr/bin` + `../lib` for `libsrt.so, and it will find it when this resolves to existing `/usr/lib`. That's not the case when you are trying to run it directly from the place where it was compiled, without installing it.

The fact that `utility-test` app does not contain this `${FORCE_RPATH}` is mainly that it does not link against SRT library at all.

**Comment by lars18th** [comment]
Hi @ethouris ,

With this simple change the problem will be fixed: CMakeList.txt#638

```
-		set(FORCE_RPATH LINK_FLAGS -Wl,-rpath,../lib BUILD_WITH_INSTALL_RPATH TRUE INSTALL_RPATH_USE_LINK_PATH TRUE)
+               set(FORCE_RPATH LINK_FLAGS -Wl,-rpath,.,-rpath,../lib BUILD_WITH_INSTALL_RPATH TRUE INSTALL_RPATH_USE_LINK_PATH TRUE)
```

I suggest to commit too this patch.
Yoou agree?

**Comment by ethouris** [comment]
I'm not a big fan of this solution, especially that the default static linkage should fix the problem for "default users", and users who would like to block the static version and link against the shared one, should know what they are doing. But I'd let others speak.

**Comment by lars18th** [comment]
> The fact that utility-test app does not contain this ${FORCE_RPATH} is mainly that it does not link against SRT library at all.

Are you sure?

```
$ strace ./utility-test
...
open("/opt/srt/srt/libsrt.so.1", O_RDONLY) = 3
...
```

I feel you're wrong in this case.
Please, commit my fix! :smile: 

Regards

**Comment by ethouris** [comment]
Ah, so it looks like no one was using it for a long time. But anyway, static linkage should take care of that problem, too.

**Comment by lars18th** [comment]
> I'm not a big fan of this solution, especially that the default static linkage should fix the problem for "default users", and users who would like to block the static version and link against the shared one, should know what they are doing. But I'd let others speak.

Ummm....
Please think on this: What it's the **default** behaviour done by GCC? It's search in "." prior to system paths.
You can check it with a simple strace of the "utility-test" that uses the _default_ config!

Searching first for the same directory where the binary exists it's a common practice, and it's too a good coding (linking) practice.
I think why you like to control this. However, it's not a problem to simple search **first** in "." and after in "../lib". It can't generate a new problem.
And yes, the static linking can solve this problem. However, why not fix it? :smile: 

Regards.

**Comment by ethouris** [comment]
#244 should fix it, please close this issue once this PR is merged

**Comment by lars18th** [comment]
> #244 should fix it, please close this issue once this PR is merged

OK. And please remember to add too the patch of `#include <stdexcept>` in a PR. https://github.com/Haivision/srt/issues/237#issuecomment-360516989

**Comment by lars18th** [comment]
Completed! :+1: 
Thank you!
