### ISSUE TITLE
Cant compile on Ubuntu 20.04

### ISSUE THREAD

**Issue by morbificagent** [Haivision/srt#2394]
Hi together... I am trying to compile it but ending in:

[ 98%] Linking CXX shared library libsrt.so
/usr/bin/ld: /usr/local/lib/libcrypto.a(p5_crpt2.o): relocation R_X86_64_PC32 against symbol `PBE2PARAM_it' can not
be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/srt_shared.dir/build.make:158: libsrt.so.1.5.0] Error 1
make[1]: *** [CMakeFiles/Makefile2:226: CMakeFiles/srt_shared.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

I don't know how to solve this :-(

Any ideas?

Many thanks

**Comment by ethouris** [comment]
Your libcrypto library is not compiled with `-fPIC` option.

Normally the practice is that if you are making a shared library with some dependent library, then the dependent one is shared, too. Here your libcrypto is static, while libsrt being built is shared. It's not impossible to link this way, but to make it possible you need to have the dependent static library compiled explicitly with `-fPIC` option.

If you can't influence the way how the libcrypto has been built, then you can only build a static libsrt. By default both static and shared are being built, so for that you'd have to `--disable-shared`.

**Comment by morbificagent** [comment]
Great this is working. Many thanks!
