### ISSUE TITLE
SRT-Server via ffmpeg ignoring latency?

### ISSUE THREAD

**Issue by morbificagent** [Haivision/srt#2396]
Hi together, i try to get an srt-server via ffmpeg working but have problems with dropped packets at the moment.

**When i use your live-transmit tool everything is working fine with:**
OBS -> srt-live-transmit "srt://0.0.0.0:9998?mode=listener&transtype=live&latency=3000000&ffs=128000&rcvbuf=100058624"

**But using ffmpeg with:**
OBS -> ffmpeg -f mpegts -i 'srt://0.0.0.0:9998?mode=listener&transtype=live&latency=3000000&ffs=128000&rcvbuf=100058624'

gives me tonns of dropped packets:

11:11:57.136843/SRT:TsbPd!W:SRT.br: @410742855:RCV-DROPPED 1 packet(s), packet seqno %885485485 delayed for 1274.725 ms
11:11:57.147443/SRT:TsbPd!W:SRT.br: @410742855:RCV-DROPPED 1 packet(s), packet seqno %885485502 delayed for 1285.286 ms
[mpegts @ 0x56104111e2c0] Packet corrupt (stream = 0, dts = 162000).
[h264 @ 0x561041152b40] non-existing PPS 0 referenced
    Last message repeated 1 times
[h264 @ 0x561041152b40] decode_slice_header error
[h264 @ 0x561041152b40] no frame!
11:11:57.159982/SRT:TsbPd!W:SRT.br: @410742855:RCV-DROPPED 2 packet(s), packet seqno %885485508 delayed for 1274.653 ms

Is the latency-var ignored by ffmpeg? Is anything wrong with my command here?

Would be great if someone has an idea!

Many thanks

Alex

**Comment by maxsharabayko** [comment]
> Is the latency-var ignored by ffmpeg?

You can find out the negotiated latency by checking the SRT conclusion handshake in a network capture.
The FFmpeg command line looks good, the latency should be 3 seconds.
