### ISSUE TITLE
Feature request: persistent stransmit sessions

### ISSUE THREAD

**Issue by colleenkhenry** [Haivision/srt#24]
Right now when you launch stransmit it runs for one session, then shuts off. 

I'd love to see if there could be a persistent daemon that is a tunnel between a client and a server natively as part of the stransmit technology. Sort of like how stunnel works. 

I'd also love if there was a way for it to take in TCP streams, and spit out TCP streams on the other side. For example, RTMP input from an encoder -> srt client -> srt -> srt sever -> RTMP to a server. You could also use it to accelerate HTTP push content.

**Comment by jbroberg** [comment]
This is a pretty essential feature. +1

**Comment by heidabyr** [comment]
I agree, that would be a very useful feature for TCP transfers. It's possible, but requires a layer on top of the current SRT in order to handle the bi-directional SRT <-> TCP conversion on both sides of the tunnel. We'll discuss!

**Comment by ethouris** [comment]
The stransmit application isn't exactly prepared for that. In the solution where we use stransmit somewhere and want to have a persistent session, we simply start it again when it exited. This can be accomplished very easily by doing kinda `while true; do ./stransmit ..PARAMETERS..; done`. Note also that stransmit wasn't predicted to be used as a stream server - for this there would better be a separate application created, which this time will use SRT as a target in listener mode only and it will send the data coming from the source into every connected client.

**Comment by maxlovic** [comment]
PR #504 introduces `srt-tunnel` application.
[Docs](https://github.com/Haivision/srt/blob/master/docs/srt-tunnel.md)
