### ISSUE TITLE
[BUG] Static Sanitizer Error

### ISSUE THREAD

**Issue by jlsantiago0** [Haivision/srt#2400]
Testing with Master, reported by Static Sanitizer GCC-12.1.0.

In `‘srt::CPacket::CPacket()’`: constructor. value in `m_nHeader[SRT_PH_SEQNO]` is referenced before it is set.

```
/mnt/share/open/toolchain/gcc12/tesu/ub16-32/srt/srtcore/packet.cpp: In constructor ‘srt::CPacket::CPacket()’:
/mnt/share/open/toolchain/gcc12/tesu/ub16-32/srt/srtcore/packet.cpp:180:25: warning: member ‘srt::CPacket::m_nHeader’ is used uninitialized [-Wuninitialized]
  180 |     m_iSeqNo((int32_t&)(m_nHeader[SRT_PH_SEQNO])),
```

**Comment by ethouris** [comment]
I think a constructor added to `DynamicStruct` with a parameter (so that it doesn't cover the default constructor) could be called before these fields and that would clear it earlier than the reference initialization, but I don't know if it's worth a shot.

**Comment by jlsantiago0** [comment]
You can read it inside the body of the constructor after m_nHeader.clear() is called. Probably not a huge deal, although reading from uninitialized memory is undefined behavior.

What can happen for instance if this field happens to be in a page frame that has not been mapped by the OS yet (Linux does it lasily and some other OSes as well) and has not been written too, then the read from it could cause a segfault. Might not happen very often of very likely, but can happen.

**Comment by ethouris** [comment]
Hmm, then it may be worth a shot.
