### ISSUE TITLE
How to avoid the  mosaic  when play ?

### ISSUE THREAD

**Issue by kubbo** [Haivision/srt#2409]
Loss packet happened when RTT jitter , exceed config latency ,  How to avoid the  mosaic  when play ? Thanks

**Comment by maxsharabayko** [comment]
The obvious answer would be to increase the latency 😃 
Otherwise, it really depends on the player (decoder). When RTT exceeds latency, SRT has no room to recover packet loss. You could also enable FEC, but it cannot recover much, only below 1% of lost packets.
Normally latency should be 3xRTT.

**Comment by ethouris** [comment]
FEC actually also has its "latency penalty". In the documentation there's an equation that defines how the latency should be shaped depending on the stream's bitrate.
