### ISSUE TITLE
Statistics callback for file transfert

### ISSUE THREAD

**Issue by newbeewan** [Haivision/srt#241]
Hi,

srt-file-transmit is very useful and efficient for file transfert, but it is not possible to easily get real time information concerning the transfert (bytes send, data lost...).

2 ways could be interesting
 - feed back in the output of the command,
 - callback for a custom field...

I thing the second option is the best for letting user creating a custom script for getting the feedback...

Regards

C. Mourad Jaber

**Comment by ethouris** [comment]
Statistics should be exactly the same way available inside the library. This is just, well, not implemented in the application. I think it should be not so hard to be done the same way as in `srt-live-transmit`...
