### ISSUE TITLE
TSBPD vs jitterbuffer 

### ISSUE THREAD

**Issue by kubbo** [Haivision/srt#2410]
SRT TSBPD should set a fixed latency time to avoid network jitter,  why not use self adative  like  Jitterbuffer in webrtc  ?

**Comment by maxsharabayko** [comment]
Hi @kubbo 
The mission of the TSBPD in SRT is to have a fixed end-to-end latency right from the start of the connection and during the whole streaming. This way application (decoder/demuxer) does not have to worry much about buffering (although still needs some buffer). At the same time, the protocol can leverage the maximum from this buffer to try recovering a missing packet right to the very end.

**Comment by ethouris** [comment]
The jitterbuffer in WebRTC is being used exactly because the medium used for it is purely UDP (RTP just adds its own header, that's all). TSBPD in SRT is doing much like the same job.
