### ISSUE TITLE
SRT to RTMP not working

### ISSUE THREAD

**Issue by Binksuk** [Haivision/srt#2415]
Hi 

Not sure what I am missing, no errors that I can see.

Trying to convert an h.265 SRT stream to rtmp using FFMPEG

`srt-live-transmit srt://0.0.0.0:30000?streamid=play/live/KEY file://con | ffmpeg -i pipe:0 -c:v copy -c:a copy -f flv "rtmp://RTMPINGESTURL/APP/KEY`

Like I say, I can't see any errors when running the command

Thanks in advance

**Comment by vojam2001** [comment]
Please try -c:v libx264..

**Comment by ethouris** [comment]
To see if this is correctly received by ffmpeg, try first playing directly with `ffplay` or convert by `ffmpeg` to UDP output with `pkt_size=1316`. If this is working correctly, the other problems can only be on the FFMPEG's side.

**Comment by maxsharabayko** [comment]
As @vojam2001 pointed out, try to convert to H.264 as well.
RTMP does not support H.265 without hacks, thus I assume most (if any) RTMP receivers (players) do not support H.265 in RTMP, which might be the problem.

**Comment by JunTVDE** [comment]
Hi,
I have the same problem. Like already mentioned I added `-c:v libx264`.
Sadly that didn't fix all errors. I got this:

```
[hevc @ 0x5631bdc46200] Error parsing NAL unit #2.
[hevc @ 0x5631bdc46200] PPS id out of range: 0
    Last message repeated 1 times
[hevc @ 0x5631bdc46200] Error parsing NAL unit #2.
[mpegts @ 0x5631bdc37ec0] decoding for stream 0 failed
[mpegts @ 0x5631bdc37ec0] Could not find codec parameters for stream 0 (Video: hevc (HEVC / 0x43564548), none): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, mpegts, from 'pipe:0':
  Duration: N/A, start: 1262.070667, bitrate: N/A
  Program 1
    Stream #0:0[0x100]: Video: hevc (HEVC / 0x43564548), none, 60 fps, 60 tbr, 90k tbn, 90k tbc
    Stream #0:1[0x101]: Audio: aac (LC) ([15][0][0][0] / 0x000F), 48000 Hz, stereo, fltp, 162 kb/s
[rtmp @ 0x5631bdc64a40] Cannot open connection tcp://fra06.contribute.live-video.net:1935
rtmp://fra06.contribute.live-video.net/app/KEY-REMOVED: Immediate exit requested
Exiting normally, received signal 2.
```

My command: `./srt-live-transmit srt://SERVER-IP:5001?mode=caller file://con | ffmpeg -i pipe:0 -c:v libx264 -c:a copy -f flv "rtmp://fra06.contribute.live-video.net/app/KEY-REMOVED"`

Any ideas?
Thanks!
