### ISSUE TITLE
Make a static library no links to  gcc_s

### ISSUE THREAD

**Issue by Adonis-Song** [Haivision/srt#2419]
Hi
I want to make a static  srt library for static ffmpeg. My command is   `../configure  --enable-static --disable-shared --enable-debug=0 --openssl-use-static-libs=ON`.

After I make install successfully ,I found ffmpeg cannot configure successful. When I check ffbuild log ,I found libsrt.a links to gcc_s. 

I find https://github.com/Haivision/srt/issues/925#issuecomment-546612495 has met this issue.  Howerver I cannot solve it by add `CMAKE_EXE_LINKER_FLAGS` and `CMAKE_EXE_LINKER_FLAGS `. 

So my question is what should I do If I want to get a static library not links to gcc_s. 

I also add `-static-libcc -static-libstdc++` to `CAMKE_C_FLAGS` and `CMAKE_CXX_FLAGS`, but I get same error.

**Comment by ethouris** [comment]
The `libsrt.a` library doesn't link to anything. That's impossible. A static library is just an archive with *.o files. Whatever part of the build requested linkage against libgcc_s.so, it wasn't libsrt.a.

The comment you are referring to speaks about a shared library on Windows with MinGW (it's even shown as LIBSRT.DLL in the picture).

If you show what exactly error you get, it will be helpful.

**Comment by Adonis-Song** [comment]
Hi，
This is my ffmeg coufigure
`../configure  --enable-gpl --enable-version3 --disable-shared --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --extra-cflags="-static -static-libgcc" --extra-cxxflags="-static -static-libgcc -static-libstdc++" --extra-ldflags="-static -static-libgcc -static-libstdc++" --extra-libs="-lpthread -lm -lstdc++ -ldl" --pkg-config-flags="--static" --cc=gcc --enable-libsrt `

And this is ffbuild log which shows why configure error

```
gcc -static -static-libgcc -static-libstdc++ -Wl,--as-needed -Wl,-z,noexecstack -I/usr/local/include **-I/usr/local/include/sr**t -L/usr/local/lib -pthread -o /tmp/ffconf.3JiDkLu4/test /tmp/ffconf.3JiDkLu4/test.o -lsrt -lstdc++ -lm **-lgcc_s** -lgcc -lc -lgcc_s -lgcc -lssl -lcrypto -ldl -lpthread -lm -lstdc++ -ldl

**/usr/bin/ld: cannot find -lgcc_s: No such file or directory**

/usr/bin/ld: /usr/local/lib/libsrt.a(channel.cpp.o): in function `srt::CChannel::open(int)':

channel.cpp:(.text+0x10e5): warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking

/usr/bin/ld: cannot find -lgcc_s: No such file or directory

```
`
My mistake, I donot know how to describe it. Every time I enable srt, I will get this error `/usr/bin/ld: cannot find -lgcc_s`. 

And I get same error when I enable other library , but after I could fix it by adding `-static-libcc -static-libstdc++` to   CAMKE_C_FLAGS and CMAKE_CXX_FLAGS

**Comment by Adonis-Song** [comment]
After disable CXX_DEPS， ffmpeg could make successfully

**Comment by xiaolitongxue666** [comment]
> 

Hi, how to disable CXX_DEPS? or can you show you final  ffmeg coufigure command . Thanks

**Comment by rdp** [comment]
Startlingly, at least with mingw, the .o obj files have to be compiled against the same (static vs not) style of libstdc++ as the main executable ends up being (in this case ffmpeg).  But that's probably not what this is about.

I'm assuming it was srt as -DENABLE_CXX_DEPS=ON
Looks like this is using a variable set by cmake itself, but it does have this message:
```
# Required if linking a C application.
# This may cause trouble when you want to compile your app with static libstdc++;
# if your build requires it, you'd probably remove -lstdc++ from the list
# obtained by `pkg-config --libs`.
if(ENABLE_CXX_DEPS)
        foreach(LIB ${CMAKE_CXX_IMPLICIT_LINK_LIBRARIES})
```

FWIW...
