### ISSUE TITLE
[FR] it's diffcult to porting to some embedded platform because of using c++17 feature, why not use pure c++11? and there is any other solution on embedded platform?

### ISSUE THREAD

**Issue by yangyouqing** [Haivision/srt#2426]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. For example: "When I try to do X, I am blocked by Y..."

**Describe the solution you'd like**
A clear and concise description of how you would like to see this feature implemented.

**Describe alternatives you've considered**

**Additional context**

**Comment by ethouris** [comment]
Which exactly used future is from C++17?

**Comment by yangyouqing** [comment]
Thks for your answer, I  have already porting to embeded platform with C++11 feather, it work well.
 before this,  I think the 'inline' keyworks in .hpp file is used only by C++17.

**Comment by ethouris** [comment]
`inline` keyword is used since the "ARM C++" standard and it's even in C language from the 1999 year standard. The only new feature since C++03 for inline is "inline namespaces", but still, this is C++11.
