### ISSUE TITLE
peer version (SRTO_PEERVERSION) not set when peering with non-1.3.0 SRT peer (HSv4)

### ISSUE THREAD

**Issue by jeandube** [Haivision/srt#243]
dev branch (SRT 1.3.0 dev)
peer version obtained from sockopt SRTO_PEERVERSION is 0  when connected to a peer running SRT 1.1.5. Version is 0x10300 when peering with a peer running SRT 1.3.0. I assume hte same problem exist with a peer running 1.2.x (or any pre-HSv5 handshake).

**Comment by ethouris** [comment]
Depends on "how fast" you are trying to obtain it. Don't forget that HSv4 makes that handshake exchange only after the UDT handshake is done, at some time later. But if this stays with 0 value forever, even after 1 second of transmission, then there's something wrong; probably the version extracted from the "legacy" handshake message is not written to appropriate field.

**Comment by jeandube** [comment]
Fixed by PR#250. Closing.
