### ISSUE TITLE
SRT for webinars 

### ISSUE THREAD

**Issue by SudoDios** [Haivision/srt#2455]
Hi
I wanted to know if this protocol is good for making a webinar with 5 callers and 50 listeners ?

**Comment by ethouris** [comment]
Excuse me but I can't really imagine what setup you mean. How exactly the transmission would happen and where are all these people situated?

**Comment by SudoDios** [comment]
We are going to create a virtual audio conference room where a few people speak as hosts and the rest listen.
Now my question is, is it possible to have several callers in one stream in SRT?

**Comment by ethouris** [comment]
Well, but note that SRT helps you only with the transmission and nothing else. If you have an application that can receive multiple streams and possibly select one of them, or somehow mix them together, then resend to multiple recipients - why not.

SRT is also bidirectional so over the same link the data can be sent in both directions at a time.

Note of course that there's nothing similar to the UDP multicast functionality there, so every transmission to a single recipient will be a completely separate transmission, even within the same network.

**Comment by SudoDios** [comment]
I am new to SRT.  
There is no SDK listener for Android and iOS

**Comment by ethouris** [comment]
I don't know what you mean by "SDK listener".

**Comment by SudoDios** [comment]
Player sdk for srt

**Comment by ethouris** [comment]
I still don't get it. SRT has the C API to be used by the application, that's all. There are some special cases for Android, but it's maintained by the community. See [build instructions](../../docs/build/build-android.md).

**Comment by SudoDios** [comment]
Thanks 👍🌹
