### ISSUE TITLE
Release executable for windows doesn't provide pdb files, so building an app crashes on linkage stage [BUG]

### ISSUE THREAD

**Issue by avanspector** [Haivision/srt#2475]
**Describe the bug**

**To Reproduce**
1. Configure '...'
2. Run '....'
3. See error

**Expected behavior**

**Screenshots**

**Desktop (please provide the following information):**
 - OS: [e.g. Windows, Linux, macOS,...]
 - SRT Version / commit ID:

**Additional context**

**Comment by ethouris** [comment]
Just a technical note here. The text in the template that is put under a bold-highlighted text is a stub that should be replaced by your own description according to what is defined by the bold-highlighted text.

Also the description "Configure" means nothing if you don't mention what kind of tool you are using to make the application.
