### ISSUE TITLE
[BUG] Incorrect detection of unstable links

### ISSUE THREAD

**Issue by manueldev** [Haivision/srt#2507]
I am trying to create an audio link with srt-test-mpbond and srt-test-live in backup mode. From the beginning unstable link problems are recorded despite the fact that both links have 0 packet loss. This generates duplicate traffic.

Build SRT Windows:

```
git clone --branch v1.5.1 https://github.com/haivision/srt.git srt
cd srt
set SRT_ROOT=%cd%
rmdir /Q /S _build
md _build && cd _build
cmake ../  -G "Visual Studio 16 2019" -A x64 -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake -DPTHREAD_INCLUDE_DIR="C:\vcpkg\packages\pthreads_x64-windows\include" -DENABLE_BONDING=ON -DENABLE_TESTING=ON
cmake --build .
cd Debug
```

Sender side: 
```
ffmpeg -loglevel debug -re -i "http://192.168.250.30:8000/audio.mp3" -c libopus -ab 512k -f mpegts -flush_packets 0 -muxrate 1M  "udp://127.0.0.1:12122?pkt_size=1316"
srt-test-mpbond.exe -ll debug 192.168.250.115:10901 192.168.88.115:10898 -i udp://:12122
```

Receiver side:
```
srt-test-live.exe -g "srt://*?type=backup&latency=1500&groupminstabletimeo=2000" 186.103.x.x:10901 186.103.x.y:10898 "udp://127.0.0.1:12345?pkt_size=1316" -c 1316 -ll debug -s 100 -rc -1 -t 50
vlc udp://@:12345
```

Sender side output log:

```
srt-test-mpbond.exe -ll debug 192.168.250.115:10901 192.168.88.115:10898 -i udp://:12122
12:48:36.436000/T4104 D:SRT.sm: generateSocketID: : @25323725
12:48:36.438000/T4104 D:SRT.km: CHANNEL: Bound to local address: 192.168.250.115:10901
12:48:36.440000/T4104 D:SRT.sm: generateSocketID: : @25323724
12:48:36.441000/T4104 D:SRT.km: CHANNEL: Bound to local address: 192.168.88.115:10898
12:48:39.137000/T4228.N:SRT.cn: PASSING request from: 186.78.24.238:62752 to agent:25323725
12:48:39.138000/T4228.N:SRT.cn: Listener managed the connection request from: 186.78.24.238:62752 result:waveahand
12:48:39.139000/T3124.N:SRT.cn: PASSING request from: 186.78.24.238:62753 to agent:25323724
12:48:39.140000/T3124.N:SRT.cn: Listener managed the connection request from: 186.78.24.238:62753 result:waveahand
12:48:39.148000/T4228.N:SRT.cn: PASSING request from: 186.78.24.238:62752 to agent:25323725
12:48:39.149000/T4228 D:SRT.sm: generateSocketID: : @25323723
12:48:39.151000/T4228.N:SRT.cn: HSREQ/rcv: cmd=1(HSREQ) len=12 vers=0x10501 opts=0xbf delay=1500
12:48:39.152000/T4228 D:SRT.sm: generateSocketID: (group): @1099065546
12:48:39.153000/T4228.N:SRT.cn: listen ret: -1 - conclusion
12:48:39.154000/T4228.N:SRT.cn: Listener managed the connection request from: 186.78.24.238:62752 result:waveahand
12:48:39.161000/T3124.N:SRT.cn: PASSING request from: 186.78.24.238:62753 to agent:25323724
12:48:39.162000/T3124 D:SRT.sm: generateSocketID: : @25323721
12:48:39.164000/T3124.N:SRT.cn: HSREQ/rcv: cmd=1(HSREQ) len=12 vers=0x10501 opts=0xbf delay=1500
12:48:39.166000/T3124.N:SRT.cn: listen ret: -1 - conclusion
12:48:39.167000/T3124.N:SRT.cn: Listener managed the connection request from: 186.78.24.238:62753 result:waveahand
12:48:39.190000/T4104!W:SRT.gs: grp/sendBackup: trying to activate a stand-by link (2 available). Reason: no stable links
12:48:39.191000/T4104!W:SRT.gs: @25323721 FRESH-ACTIVATED
12:48:41.036000/T4104!W:SRT.gs: grp/sendBackup: trying to activate a stand-by link (1 available). Reason: no stable links
12:48:41.037000/T4104!W:SRT.gs: @25323723 FRESH-ACTIVATED
12:48:42.613000/T4104.N:SRT.gs: grp/sendBackup: silencing member @25323721 (weight 0 ACTIVE_UNSTABLE_WARY) in favor of @25323723 (weight 0)
12:48:48.276000/T4104!W:SRT.gs: grp/sendBackup: trying to activate a stand-by link (1 available). Reason: no stable links
12:48:48.277000/T4104!W:SRT.gs: @25323721 FRESH-ACTIVATED
12:48:49.837000/T4104.N:SRT.gs: grp/sendBackup: silencing member @25323723 (weight 0 ACTIVE_UNSTABLE_WARY) in favor of @25323721 (weight 0)
12:48:53.884000/T4104!W:SRT.gs: grp/sendBackup: trying to activate a stand-by link (1 available). Reason: no stable links
12:48:53.885000/T4104!W:SRT.gs: @25323723 FRESH-ACTIVATED
12:48:55.449000/T4104.N:SRT.gs: grp/sendBackup: silencing member @25323721 (weight 0 ACTIVE_UNSTABLE_WARY) in favor of @25323723 (weight 0)
12:48:58.353000/T4104!W:SRT.gs: grp/sendBackup: trying to activate a stand-by link (1 available). Reason: no stable links
12:48:58.354000/T4104!W:SRT.gs: @25323721 FRESH-ACTIVATED
12:48:59.910000/T4104.N:SRT.gs: grp/sendBackup: silencing member @25323723 (weight 0 ACTIVE_UNSTABLE_WARY) in favor of @25323721 (weight 0)
12:49:01.919000/T4104!W:SRT.gs: grp/sendBackup: trying to activate a stand-by link (1 available). Reason: no stable links
12:49:01.920000/T4104!W:SRT.gs: @25323723 FRESH-ACTIVATED
12:49:03.481000/T4104.N:SRT.gs: grp/sendBackup: silencing member @25323721 (weight 0 ACTIVE_UNSTABLE_WARY) in favor of @25323723 (weight 0)
12:49:03.595000/T4104!W:SRT.gs: grp/sendBackup: trying to activate a stand-by link (1 available). Reason: no stable links
12:49:03.596000/T4104!W:SRT.gs: @25323721 FRESH-ACTIVATED
12:49:05.164000/T4104.N:SRT.gs: grp/sendBackup: silencing member @25323723 (weight 0 ACTIVE_UNSTABLE_WARY) in favor of @25323721 (weight 0)
12:49:15.836000/T4104!W:SRT.gs: grp/sendBackup: trying to activate a stand-by link (1 available). Reason: no stable links
12:49:15.837000/T4104!W:SRT.gs: @25323723 FRESH-ACTIVATED
12:49:17.397000/T4104.N:SRT.gs: grp/sendBackup: silencing member @25323721 (weight 0 ACTIVE_UNSTABLE_WARY) in favor of @25323723 (weight 0)
12:49:18.115000/T4104!W:SRT.gs: grp/sendBackup: trying to activate a stand-by link (1 available). Reason: no stable links
12:49:18.116000/T4104!W:SRT.gs: @25323721 FRESH-ACTIVATED
12:49:19.678000/T4104.N:SRT.gs: grp/sendBackup: silencing member @25323723 (weight 0 ACTIVE_UNSTABLE_WARY) in favor of @25323721 (weight 0)
12:49:24.001000/T4104!W:SRT.gs: grp/sendBackup: trying to activate a stand-by link (1 available). Reason: no stable links
12:49:24.002000/T4104!W:SRT.gs: @25323723 FRESH-ACTIVATED
12:49:25.557000/T4104.N:SRT.gs: grp/sendBackup: silencing member @25323721 (weight 0 ACTIVE_UNSTABLE_WARY) in favor of @25323723 (weight 0)
12:49:26.198000/T4104!W:SRT.gs: grp/sendBackup: trying to activate a stand-by link (1 available). Reason: no stable links
12:49:26.199000/T4104!W:SRT.gs: @25323721 FRESH-ACTIVATED
12:49:27.757000/T4104.N:SRT.gs: grp/sendBackup: silencing member @25323723 (weight 0 ACTIVE_UNSTABLE_WARY) in favor of @25323721 (weight 0)
12:49:33.961000/T4104!W:SRT.gs: grp/sendBackup: trying to activate a stand-by link (1 available). Reason: no stable links
12:49:33.962000/T4104!W:SRT.gs: @25323723 FRESH-ACTIVATED
12:49:35.523000/T4104.N:SRT.gs: grp/sendBackup: silencing member @25323721 (weight 0 ACTIVE_UNSTABLE_WARY) in favor of @25323723 (weight 0)
12:49:40.475000/T4104!W:SRT.gs: grp/sendBackup: trying to activate a stand-by link (1 available). Reason: no stable links
12:49:40.476000/T4104!W:SRT.gs: @25323721 FRESH-ACTIVATED
12:49:42.029000/T4104.N:SRT.gs: grp/sendBackup: silencing member @25323723 (weight 0 ACTIVE_UNSTABLE_WARY) in favor of @25323721 (weight 0)
12:49:46.924000/T4104!W:SRT.gs: grp/sendBackup: trying to activate a stand-by link (1 available). Reason: no stable links
12:49:46.925000/T4104!W:SRT.gs: @25323723 FRESH-ACTIVATED
12:49:48.477000/T4104.N:SRT.gs: grp/sendBackup: silencing member @25323721 (weight 0 ACTIVE_UNSTABLE_WARY) in favor of @25323723 (weight 0)
12:49:49.316000/T4104!W:SRT.gs: grp/sendBackup: trying to activate a stand-by link (1 available). Reason: no stable links
12:49:49.317000/T4104!W:SRT.gs: @25323721 FRESH-ACTIVATED
12:49:50.891000/T4104.N:SRT.gs: grp/sendBackup: silencing member @25323723 (weight 0 ACTIVE_UNSTABLE_WARY) in favor of @25323721 (weight 0)
12:49:55.230000/T4104!W:SRT.gs: grp/sendBackup: trying to activate a stand-by link (1 available). Reason: no stable links
12:49:55.231000/T4104!W:SRT.gs: @25323723 FRESH-ACTIVATED
12:49:56.784000/T4104.N:SRT.gs: grp/sendBackup: silencing member @25323721 (weight 0 ACTIVE_UNSTABLE_WARY) in favor of @25323723 (weight 0)
12:49:57.634000/T4104!W:SRT.gs: grp/sendBackup: trying to activate a stand-by link (1 available). Reason: no stable links
12:49:57.635000/T4104!W:SRT.gs: @25323721 FRESH-ACTIVATED
12:49:59.195000/T4104.N:SRT.gs: grp/sendBackup: silencing member @25323723 (weight 0 ACTIVE_UNSTABLE_WARY) in favor of @25323721 (weight 0)
12:50:06.724000/T4104!W:SRT.gs: grp/sendBackup: trying to activate a stand-by link (1 available). Reason: no stable links
12:50:06.725000/T4104!W:SRT.gs: @25323723 FRESH-ACTIVATED
12:50:08.288000/T4104.N:SRT.gs: grp/sendBackup: silencing member @25323721 (weight 0 ACTIVE_UNSTABLE_WARY) in favor of @25323723 (weight 0)
12:50:11.191000/T4104!W:SRT.gs: grp/sendBackup: trying to activate a stand-by link (1 available). Reason: no stable links
12:50:11.192000/T4104!W:SRT.gs: @25323721 FRESH-ACTIVATED
12:50:12.749000/T4104.N:SRT.gs: grp/sendBackup: silencing member @25323723 (weight 0 ACTIVE_UNSTABLE_WARY) in favor of @25323721 (weight 0)
12:50:13.078000/T4104!W:SRT.gs: grp/sendBackup: trying to activate a stand-by link (1 available). Reason: no stable links
12:50:13.079000/T4104!W:SRT.gs: @25323723 FRESH-ACTIVATED
12:50:14.651000/T4104.N:SRT.gs: grp/sendBackup: silencing member @25323721 (weight 0 ACTIVE_UNSTABLE_WARY) in favor of @25323723 (weight 0)`
```

**Expected behavior**
The expected behavior is that links health are successfully detected without problems.

**Desktop (please provide the following information):**
 - OS: Windows 11, Windows 8
 - SRT Version / commit ID: v1.5.1

**Comment by ethouris** [comment]
It could be helpful if you grab the network traffic and send back some pcap files.

Link stability counts by not whether there are packet losses, but exclusively whether any packet comes from the peer receiving the packets (usually ACK packets, if we are talking about the unidirectional transmission). The criteria to activate an idle link are that - provided you have one link active - no links are stable, that is, the currently activated link didn't receive any packet after the previously received packet (be it even the handshake packet) in a predictable time. Normally, even if some link has been once falsely perceived as unstable, after ACK packets come predictably in time, multiple stable links should resolve to selection of the one link to remain stable and others are silenced. I can see that this is happening, but then weirdly that silenced link gets activated again due to "not having stable links". That's why we'd need some information about the packets coming from the receiver to see how the times when they come is related with all other time measurement and qualification criteria.

**Comment by maxsharabayko** [comment]
Hi @manueldev 
Please note [Mode Limitations](https://github.com/Haivision/srt/blob/v1.5.1/docs/features/bonding-main-backup.md#mode-limitations). In particular, "the bitrate should be > 180 kbps".
_Although I admit the idea must be expanded..._

Anyway, if you are working with a small bitrate, you should consider increasing the [`SRTO_GROUPMINSTABLETIMEO`](https://github.com/Haivision/srt/blob/v1.5.1/docs/API/API-socket-options.md#SRTO_GROUPMINSTABLETIMEO).

**Comment by manueldev** [comment]
> It could be helpful if you grab the network traffic and send back some pcap files.
> 
> Link stability counts by not whether there are packet losses, but exclusively whether any packet comes from the peer receiving the data packets (usually ACK packets, if we are talking about the unidirectional transmission). The criteria to activate an idle link are that - provided you have one link active - no links are stable, that is, the currently activated link didn't receive any packet after the previously received packet (be it even the handshake packet) in a predictable time. Normally, even if some link has been once falsely perceived as unstable, after ACK packets come predictably in time, multiple stable links should resolve to selection of the one link to remain stable and others are silenced. I can see that this is happening, but then weirdly that silenced link gets activated again due to "not having stable links". That's why we'd need some information about the packets coming from the receiver to see how the times when they come is related with all other time measurement and qualification criteria.


Pcaps files here. 

[[https://drive.google.com/drive/folders/1cdLVqdALdTb7IYuTiZ-9ciAfhTRlKrw7?usp=share_link](url)
](https://drive.google.com/drive/folders/1cdLVqdALdTb7IYuTiZ-9ciAfhTRlKrw7?usp=share_link)

**Comment by maxsharabayko** [comment]
@manueldev Could you please enable backup tracing by setting `-DENFORCE_ SRT_DEBUG_BONDING_STATES=1` CMake build option and share the trace files you get?

From the Wireshark dump, I see the distance between ACK packets may get up to 100 ms.
Consider increasing the [`SRTO_GROUPMINSTABLETIMEO`](https://github.com/Haivision/srt/blob/v1.5.1/docs/API/API-socket-options.md#SRTO_GROUPMINSTABLETIMEO) to at least 100 ms.

**Comment by maxsharabayko** [comment]
Closing as resolved: consider increasing the [SRTO_GROUPMINSTABLETIMEO](https://github.com/Haivision/srt/blob/v1.5.1/docs/API/API-socket-options.md#SRTO_GROUPMINSTABLETIMEO) to at least 100 ms.
Don't hesitate to reopen would you have updates.

**Comment by manueldev** [comment]
> @manueldev Could you please enable backup tracing by setting `-DENFORCE_ SRT_DEBUG_BONDING_STATES=1` CMake build option and share the trace files you get?

I'm not sure if this is what you need but this file was generated automatically by doing the same test in the first post. The file was generated only on the sender side (srt-test-mpbond).
[stability_trace_23_19_03.033607.csv](https://github.com/Haivision/srt/files/10283286/stability_trace_23_19_03.033607.csv)

> From the Wireshark dump, I see the distance between ACK packets may get up to 100 ms. Consider increasing the [`SRTO_GROUPMINSTABLETIMEO`](https://github.com/Haivision/srt/blob/v1.5.1/docs/API/API-socket-options.md#SRTO_GROUPMINSTABLETIMEO) to at least 100 ms.
In the test of the first message the value of groupminstabletimeo was 2000 but I have tried with different values without getting differences. From 500, 2000, 1000, 1500, etc. This is always as a parameter to srt-test-live.exe on the receiver side (I think mpbond doesn't accept SRT parameters).
