### ISSUE TITLE
dissector for SRT

### ISSUE THREAD

**Issue by zmousm** [Haivision/srt#251]
I'm not sure this is the right place to ask, but here goes anyway:

Is there a (Wireshark) dissector for the SRT protocol?

**Comment by maxlovic** [comment]
Hi @zmousm 
The SRT dissector is in the master branch of Wireshark ([commit](https://github.com/wireshark/wireshark/commit/04005c07290a12f23443fd84c7dd3577d685c378)). The latest Wirehark release version (2.6.5) does not have it yet. You can build master yourself or wait for it to be included in the next release. Also some automated Wireshark builds can be found [here](https://www.wireshark.org/download/automated/).
