### ISSUE TITLE
how about change type of SRT_SOCKET?

### ISSUE THREAD

**Issue by marakew** [Haivision/srt#2512]
wish to change type of SRT_SOCKET under windows to SOCKET instead "int"
because of windows SOCKET has type of lon long for x64 arch
its not good for using with OOP programming with base derive class
where type of function return SOCKET for base socket
and type int(SRT_SOCKET) for srt implementation

**Comment by maxsharabayko** [comment]
It would touch the API. Potentially could be done in v1.6.0.
But the thing is that SRT socket ID does not take more than 32 bits.
```c
typedef int32_t SRTSOCKET;
```
