### ISSUE TITLE
Create::Source compilation error

### ISSUE THREAD

**Issue by enricovittorini** [Haivision/srt#2514]
following the srt-live-transmit, i am trying to build my own app. At compilation time i have the following error:

```
/usr/lib/gcc/x86_64-alpine-linux-musl/10.3.1/../../../../x86_64-alpine-linux-musl/bin/ld: /tmp/ccLopPID.o: in function `main':
test.cpp:(.text+0x65): undefined reference to `Source::Create(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
collect2: error: ld returned 1 exit status
```
So I restricted the code at minimum but still have the issue. Any suggestion?

```
...
#include "../srtevi/srt.h"
#include "../srtevi/transmitbase.hpp"
using namespace std;

int main(int argc, char** argv)
{
    string srcurl = "udp://239.0.0.1:5000";
    unique_ptr<Source> src;
    src =  Source::Create(srcurl);
    
```
  }

**Comment by enricovittorini** [comment]
by opening the transmitbase.hhp file where the class Source is defined, I noticed that visual studio report that the "_Function Definition for create is not defined_"

could this be the issue? any clue on how to fix it?

class Source: public Location
```
{
public:
    virtual int  Read(size_t chunk, MediaPacket& pkt, std::ostream &out_stats = std::cout) = 0;
    virtual bool IsOpen() = 0;
    virtual bool End() = 0;
    static std::unique_ptr<Source> **Create(c**onst std::string& url);
    virtual void Close() {}
    virtual ~Source() {}

...
...

```

**Comment by maxsharabayko** [comment]
Hi @enricovittorini 
It is not that much related to SRT, but rather developing a custom project. Please consider using [StackOverflow](https://stackoverflow.com/) or similar services for this kind of issue.
