### ISSUE TITLE
PMT/PAT Interval greater than 1s

### ISSUE THREAD

**Issue by asspye** [Haivision/srt#2518]
Details:
Software - Cesbo Astra
Incoming stream: UDP | MPEG-TS | CBR 
Stream target: SRT | Latency 500 | Default values | No encryption

When sending the SRT out to another device I am seeing ETR290 P1 alarms for PMT and PAT intervals at 1000-1200ms (Maximum 500ms expected).
This is critical when sending a UDP stream to a satellite.

**Comment by ethouris** [comment]
Do you have comparison data when sending (be it even with dropped lost packets) over exactly the same link using UDP instead of SRT?

**Comment by maxsharabayko** [comment]
Can you replace SRT with UDP to confirm it is not related to the source stream?

**Comment by asspye** [comment]
Everything is fine at the input UDP source - we monitor it

The problem was solved by replacing the server

**Comment by maxsharabayko** [comment]
Do you mean there was a hardware issue?
