### ISSUE TITLE
srt wifi/lan connectivity

### ISSUE THREAD

**Issue by ksmuthucv** [Haivision/srt#2519]
Hello Team,

srt client fails (srt_connect returns -1) to connect to a srt server running in a wifi (ipv4)/lan(ipv6, has ipv 4 address) network. But it is not always the case. Most of the time it works fine. Please note that srt server will have in-bound firewall rules created for UDP and TCP protocols, against the network mode it is started with and server/client can ping each other.

Code to connect to a server:
—---------------------------------------
struct sockaddr_in sa {};
sa.sin_family = AF_INET;
sa.sin_port = htons(opts.port);
if (inet_pton(AF_INET, opts.address, &sa.sin_addr) != 1)
return false;
m_onlog(LOGG_DEBUG, "srt client connection attempt");
result = srt_connect(m_socket, (struct sockaddr*)&sa, sizeof sa); //this call returns -1
m_onlog(LOGG_DEBUG, (std::string("srt client connection status: ") + std::to_string(result) 
			+ std::string(" address: ") + std::string(opts.address) + std::string(" port: ") + std::to_string(opts.port)).c_str());

Code to enable the log:
—---------------------------------------
srt_setloghandler(this, stlog); //stlog function manages the logging as highlighted below
srt_setloglevel(srt_logging::LogLevel::error | srt_logging::LogLevel::fatal);

logs:
—---------------------------------------
2022-11-03 15:00:14.110 +03:30 [DBG] srt core constructed
2022-11-03 15:00:14.111 +03:30 [DBG] srt client constructed
2022-11-03 15:00:14.112 +03:30 [DBG] starting srt client. sid: 3
**2022-11-03 15:00:14.114 +03:30 [DBG] api.cpp: srt::CUDTUnited::generateSocketID: 15:00:14.114000/T7264 D:SRT.sm: generateSocketID: : @1021352879**
2022-11-03 15:00:14.114 +03:30 [DBG] srt client connection attempt
2022-11-03 15:00:17.118 +03:30 [DBG] srt client connection status: -1 address: 192.***.*.*** port: 8555
2022-11-03 15:00:17.118 +03:30 [FTL] srt_connect failed: 192.***.*.***:8555 error no: -1

os: 		windows 10 (both server and client)
srt lib: 		1.5.1

Can you please advise?

Thanks,
Muthu

**Comment by ethouris** [comment]
If the problem is due to more time required to get a connection response, you can extend the time using `SRTO_CONNTIMEO` option.

**Comment by ksmuthucv** [comment]
Thanks for your feedback. Is there anything more need to be done so that srt would give more while unable to connected to particular ipv4 address? below is how we have enabled logging in code.
---------------------------------------------------------------------------------
srt_startup();
srt_setloglevel(srt_logging::LogLevel::error | srt_logging::LogLevel::fatal);
srt_setloghandler(this, stlog);
---------------------------------------------------------------------------------

Thanks,
Muthu

**Comment by maxsharabayko** [comment]
> Is there anything more need to be done so that srt lib would give more logs while unable to connect to a particular ipv4 address & port?

The [ENABLE_HEAVY_LOGGING](https://github.com/Haivision/srt/blob/master/docs/build/build-options.md#enable_heavy_logging) build option may help.

**Comment by maxsharabayko** [comment]
Closing due to the lack of activity.
