### ISSUE TITLE
how to send constant bitrate srt stream using srt-file-transmit

### ISSUE THREAD

**Issue by flnewsoft** [Haivision/srt#2523]
HI.
    I try to send constant bitrate srt stream using srt-file-transmit, my command is like:
    ./srt-file-transmit -r 25 -c 5 -s 25 -statsout:out.log  -v xx.ts "srt://@xxx.xxx.xxx.xxx:port"
    From out.log, I find packet number which is sened by srt-file-transmit is variable during some time(like one sec, file sec).
    Could I send a cbr stream using  srt-file-transmit, how to do it?
    status report:
======= SRT STATS: sid=551288801
 PACKETS     SENT:          18  RECEIVED:             0
 LOST PKT    SENT:           0  RECEIVED:             0
 REXMIT      SENT:           0  RECEIVED:             0
 DROP PKT    SENT:           0  RECEIVED:             0
 FILTER EXTRA  TX:           0        RX:             0
 FILTER RX  SUPPL:           0  RX  LOSS:             0
 RATE     SENDING:     59.1429  RECEIVING:            0
 BELATED RECEIVED:           0  AVG TIME:             0
 REORDER DISTANCE:           0
 WINDOW      FLOW:        8188  CONGESTION:          16  FLIGHT:          15
 LINK         RTT:       100ms  BANDWIDTH:       12Mb/s
 BUFFERLEFT:  SND:           0  RCV:                  0
======= SRT STATS: sid=551288801
 PACKETS     SENT:           8  RECEIVED:             0
 LOST PKT    SENT:           0  RECEIVED:             0
 REXMIT      SENT:           0  RECEIVED:             0
 DROP PKT    SENT:           0  RECEIVED:             0
 FILTER EXTRA  TX:           0        RX:             0
 FILTER RX  SUPPL:           0  RX  LOSS:             0
 RATE     SENDING:      24.809  RECEIVING:            0
 BELATED RECEIVED:           0  AVG TIME:             0
 REORDER DISTANCE:           0
 WINDOW      FLOW:        8189  CONGESTION:          16  FLIGHT:          10
 LINK         RTT:       100ms  BANDWIDTH:       12Mb/s
 BUFFERLEFT:  SND:           0  RCV:                  0

**Comment by ethouris** [comment]
If that's a live stream what you are trying to send, you should rather use `srt-live-transmit`.

**Comment by maxsharabayko** [comment]
Consider using TSDuck.
[How to replay a .ts file as a stream](https://srtlab.github.io/srt-cookbook/apps/tsduck.html#how-to-replay-a-ts-file-as-a-stream) - SRT Cookbook.

**Comment by ethouris** [comment]
Ah, didn't extract the right intention from the command line.

`srt-file-transmit` is an example application to copy a file to another machine using SRT (does more-less the same thing as `scp`).

`srt-live-transmit` can only flip an existing live stream into a different medium (including SRT). It cannot make a live stream from a file - you need to use a different tool for it, TSDuck or `ffmpeg` with `-re` option.

**Comment by flnewsoft** [comment]
> Ah, didn't extract the right intention from the command line.
> 
> `srt-file-transmit` is an example application to copy a file to another machine using SRT (does more-less the same thing as `scp`).
> 
> `srt-live-transmit` can only flip an existing live stream into a different medium (including SRT). It cannot make a live stream from a file - you need to use a different tool for it, TSDuck or `ffmpeg` with `-re` option.

Got it, thanks

**Comment by flnewsoft** [comment]
> Consider using TSDuck. [How to replay a .ts file as a stream](https://srtlab.github.io/srt-cookbook/apps/tsduck.html#how-to-replay-a-ts-file-as-a-stream) - SRT Cookbook.

thanks, Got it.
