### ISSUE TITLE
how to bind device in srt-live-transmit?

### ISSUE THREAD

**Issue by flnewsoft** [Haivision/srt#2524]
I run srt-live-transmit in centos and need to change network interface to get udp stream.
I try to do like this:
1. Modify transmitmedia.cpp
2. under line:
    int shareAddrRes = setsockopt(m_sock, SOL_SOCKET, SO_REUSEADDR, reinterpret_cast<const char*>(&reuse), sizeof(reuse));               
    if (shareAddrRes == status_error)
             {
                 throw runtime_error("marking socket for shared use failed");
             }
             Verb() << "Multicast(Windows): will bind to home address";
 #else
             Verb() << "Multicast(POSIX): will bind to IGMP address: " << host;
 #endif
3. add code like this:
             char inf[]="eno2";             
             int res1 = setsockopt(m_sock, SOL_SOCKET, SO_BINDTODEVICE, inf, sizeof inf);
             if (res1 == -1)
                 Verb() << "WARNING: failed to set 'bindto device' (SRTO_BINDTODEVICE) to " << inf;
             else
                 Verb() << "WARNING: ok to set 'bindto device' (SRTO_BINDTODEVICE) to " << inf << "result" << res1;
4. But it seems not working, I could not receive udp stream still.
Any ideas?

**Comment by ethouris** [comment]
How do you run `srt-live-transmit` exactly and what is the command for `tcpdump`, or something similar, which succeeds to read the stream?

**Comment by flnewsoft** [comment]
env:
1. send multicast udp stream to 192.168.2.111, network interface eno2(just a sample )
2. running  ffmpeg command in 192.168.2.111:./ffmpeg -i "udp://@239.0.0.1:6655?buffer_size=131072000&reuse=1&connect=0&overrun_nonfatal=1&timeout=5000000&fifo_size=800000&localaddr=192.168.2.169",  stream info could be found.
3. running srt-live-transmit(added SO_BINDTODEVICE) in 192.168.2.111: ./srt-live-transmit "udp://@239.0.0.1:6655" "srt://@xxx.xxx.x.xxx:1234?mode=caller", I could not dump udp stream.

**Comment by flnewsoft** [comment]
any ideas?

**Comment by ethouris** [comment]
I can't see anything like the `localaddr` parameter you have used for ffmpeg. For UDP URI there's an `adapter` parameter that allows to specify the IP address of the device that should be used. Your command also doesn't specify the bindtodevice option.
