### ISSUE TITLE
[BUG] listener can not send message to caller with AES GCM mode

### ISSUE THREAD

**Issue by ppiao** [Haivision/srt#2534]
**Describe the bug**
listener can not send message to caller with AES GCM mode.

```
23:38:47.968034/SRT:RcvQ:w1*E:SRT.cn: decrypt ERROR (IPE): HaiCrypt_Rx_Data failure=-1 - returning failed decryption
23:38:47.968238/SRT:RcvQ:w1*E:SRT.qr: @72980686: AEAD decryption failed, breaking the connection.
23:38:48.846745/test-gcm-mode!W:SRT.br: CRcvBuffer.readMessage(): nothing to read. Ignored isRcvDataReady() result?
```

**To Reproduce**
1. ./configure  --enable-haicrypt-logging=ON --enable-encryption=ON --use-enclib=openssl-evp
2. download code: https://gist.github.com/ppiao/379b0ab2deca8b2e4030ab827824f24b
3. execute: ./test-gcm-mode listener 2 and ./test-gcm-mode caller 2

**Expected behavior**
Listener and caller transmit normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/16552206/201481873-cee5f9cd-abac-4850-aa58-93096cd483e0.png)

**Desktop (please provide the following information):**
 - OS: 4.15.0-107-generic #108~16.04.1-Ubuntu
 - SRT Version / commit ID: master

**My point of view**

I found that `m_hSndCrypto->ctx->mode != HCRYPT_CTX_MODE_AESGCM`, maybe `processSrtMsg_KMREQ` -> `HaiCrypt_Clone` did not clone `m_hSndCrypto->ctx->mode` value properly.

**Comment by maxsharabayko** [comment]
@ppiao Thanks for noticing and sharing the reproduction steps!

One more way to reproduce:

```shell
(sender)
./srt-xtransmit generate "srt://:4200?passphrase=abcdefghijk&cryptomode=2" --sendrate 10Mbps
(receiver)
./srt-xtransmit receive "srt://127.0.0.1:4200?passphrase=abcdefghijk&cryptomode=2" -v
```

Result:
```shell
E:SRT.qr: @946231774: AEAD decryption failed, breaking the connection.
```
