### ISSUE TITLE
Streaming a webcam with low latency between 2 linux machines

### ISSUE THREAD

**Issue by Bark33p3r** [Haivision/srt#2537]
Hello there,

I try to stream a webcam between 2 ubuntu 20.04 machines. I managed it to stream on a local machine with ffmpeg but had like 10s latency somehow.

https://github.com/Haivision/srt/issues/7#issuecomment-456643617 unfortunately doesn't work on my setup.
I saw some more examples in the docs but couldn’t stream between to PCs on the LAN. Because I can't figure out which IP has to be in the Uri from the caller and the listener. Mostly docs talk about localhost. If you provide an example, you might use 192.168.1.10 for the PC with the webcam and 192.168.1.11 for the receiving computer.
192.168.1.10 has an Nvidia GPU, ...1.11 has nonseparated GPU (Intel UHD 630)

Most imported for me is a latency as low as possible. Nice to have would be the hevc/libx265 codec.

I tried right now for some days, but I didn't get it working. I would me more than happy if you can answer my question and provide an example for sender and receiver.

**Comment by ethouris** [comment]
I'm sorry, you've lost me. What exactly does it have to do with SRT?

**Comment by maxsharabayko** [comment]
@Bark33p3r I would suggest starting with UDP to find the minimal delay you can get. Maybe even start with I-frame-only encoding.

**Comment by Bark33p3r** [comment]
> I'm sorry, you've lost me. What exactly does it have to do with SRT?

As I understood is SRT a streaming protocol which supports hevc. I'm used to rtsp, but this only supports h264.
Did I get something wrong about SRT?

**Comment by maxsharabayko** [comment]
SRT is content-agnostic and supports any format.

**Comment by ethouris** [comment]
@Bark33p3r : That's kinda different level of containment. The RTSP protocol is used for establishing sessions only and it's using TCP for the transport layer, and several other protocols (RTCP, RTP) for doing other parts of the job for stream transmission.

SRT is a transport-only protocol, that is, you can send any kind of data through it, although most likely, if you send synchronized media of different types, you would need to send it in some multiplexing container, for which there's mostly used MPEG-TS (known also as H.222). Of course, you can send anything else through SRT and even use multiple connections, just note that a single multiplexed stream is the only thing that you can use here to still match any standards (and count on having it handled by other tools, such as ffmpeg).
