### ISSUE TITLE
Remote GPU

### ISSUE THREAD

**Issue by xiejiashu** [Haivision/srt#2549]
Now I get the rendered graphics data from the graphics card and send it to the client at about 60 frames per second, and the sound is also sent to the client.
But the playback delay of the client is getting bigger and bigger, and the connection is forcibly disconnected after about 20 seconds due to data congestion. The above test environments are all done locally. Can anyone tell me how to configure parameters in this case? thanks

**Comment by ethouris** [comment]
What's the bitrate and bandwidth data in the statistics?

**Comment by xiejiashu** [comment]
I have solved this problem. Thanks, please close.
I have solved this problem. Thanks, please close.
