### ISSUE TITLE
[BUG] SRTO_MSS = 1300 splits one message into two packets in TSBPD mode.

### ISSUE THREAD

**Issue by maxsharabayko** [Haivision/srt#2589]
The default configuration in TSBPD mode is
- `SRTO_MSS = 1500`;
- `SRTO_PAYLOADSIZE = 1316`.

Trying to send a payload exceeding `SRTO_PAYLOADSIZE ` leads to an error returned from `srt_sendmsg2(..)`.
In the live configuration, it is expected that a message must fit into a single SRT data packet.

If `SRTO_MSS  < SRTO_PAYLOADSIZE`, a message will be split into two packets.
For e.g. setting ` `SRTO_MSS = 1300` and sending 1316 bytes long messages would produce two packets per message.

SRT v1.5.1 and prior.

**Comment by ethouris** [comment]
Does this happen even if a message is of a less size than 1300 bytes?

**Comment by jeandube** [comment]
AT some point in the evolution of SRT, the default MSS was changed from 1500 to 1360 (payload 1316 + headers), indirectly with the introduction of SRTO_PLAYLOADSIZE (default:1316).  From memory, this broke some apps using RTP/SRT causing packet fragmentation and hard to diagnose problems. I suspect that at the time, returning an error in live mode was seen as a preferred behavior than fragmentation.

**Comment by ethouris** [comment]
Ah, so the problem was that with modified MSS, the PAYLOADSIZE option should be modified accordingly, that is, if the value of MSS-44 is less than the current payloadsize, it should be set to this value?

**Comment by jeandube** [comment]
I though they were synched but never tested the limits. I don't understand which problem SRTO_PAYLOADSIZE fixed. SRTO_MSS exists to prevent IP fragmentation on network's MTU and do it under SRT control (first/middle/last message packet flags). The actual defaults 1500 and 1316 work but are not optimal as 1500-1360 bytes per buffer are allocated but unused.
