### ISSUE TITLE
how to multicast the output srt

### ISSUE THREAD

**Issue by udhayNuk** [Haivision/srt#2597]
@fallenhaivision 
How to multicast the srt streams
tsp -I srt --caller 192.168.0.103:4900 -P analyze -i 10 -o output-analysis1.txt -O srt 192.168.0.10:2000 --transtype live --messageapi

This script only unicast, how to multicast the srt, please solve my question
Thank you in advance

**Comment by maxsharabayko** [comment]
SRT does not support multicast (at least yet). SRT is a connection-based protocol.

**Comment by udhayNuk** [comment]
@maxsharabayko 
Thank you dude
