### ISSUE TITLE
Is the slack open?

### ISSUE THREAD

**Issue by toots** [Haivision/srt#2601]
The front page mentions a public slack channel at https://srtalliance.slack.com but the signup is only limited to certain specific email domains.

**Comment by mbakholdina** [comment]
Hi @toots, the SRT slack channels are open for everybody. Do you mean it's limited to `.com` only? I thought this is just an example, however haven't tried any other domains. If you could share with what kind of domains you do have problems, we will double check.

**Comment by mbakholdina** [comment]
Hi @toots,

Please use the following link to register in the SRT slack channels:

> To ask a question [join the conversation](https://slackin-srtalliance.azurewebsites.net/) in the #development channel on ...

It's [here](https://github.com/Haivision/srt#what-is-srt) in the "What is SRT?" section of main README:

<img width="866" alt="Screenshot 2023-01-06 at 12 46 27" src="https://user-images.githubusercontent.com/41019697/211006590-a8664e60-c822-4965-8ee8-fb118f5ff28b.png">

**Comment by toots** [comment]
This worked great, thanks @mbakholdina
