### ISSUE TITLE
Question about "Stransmit"

### ISSUE THREAD

**Issue by dciszk** [Haivision/srt#263]
Hello

Q1: Is it able to use 'Stransmit' transmit UDP to SRT?

Q2: If Q1 is possible, is it possible to implement the following flow?
"[Non-SRT Encoder] - UDP -> [Stransmit] - SRT -> [Wowza Server] - HLS -> [Playback Device]"

by the way, we are using wowza 4.7.3

**Comment by heidabyr** [comment]
Yes, that's totally possible.

**Comment by nitrat7** [comment]
yes, already done and working :-)

Wowza SRT-output is a little bit problematic.

**Comment by lars18th** [comment]
> Is it able to use 'Stransmit' transmit UDP to SRT?

Sure! :smile: 
However, _test_ the "srt-live-transmit" in the "dev" branch. It has several updates.
At time, not use it for production; but it's good for testing.
