### ISSUE TITLE
[BUG] srt-tunnel  HSREQ/rcv: Agent uses STREAM API, but the Peer declares MESSAGE API. Not compatible transmission type, rejecting.

### ISSUE THREAD

**Issue by alatteri** [Haivision/srt#2646]
I am trying to use srt-tunnel with srt-live-transmit.  srt-tunnel complains that one side is STREAM the other side is MESSAGE, but both sides are using srt-live-transmit

**To Reproduce**
Machine A:
 `srt-live-transmit -s 2000 udp://:5104 srt://machineA:6010`
Machine B:
`srt-tunnel -v -l2 srt://:6010 srt://machineC:6010`
Machine C:
`srt-live-transmit -s 2000 srt://:6010 udp://:5004`

At this point Machine B errors:
```
root@vultr:~# srt-tunnel -v -l2 srt://172.25.5.212:6010 srt://machineC:6010
LISTEN type=srt, CALL type=srt
Waiting for connection...
07:32:33.695669/SRT:RcvQ:w1*E:SRT.cn: HSREQ/rcv: Agent uses STREAM API, but the Peer declares MESSAGE API. Not compatible transmission type, rejecting.
07:32:33.695954/SRT:RcvQ:w1*E:SRT.cn: interpretSrtHandshake: process HSREQ returned unexpected value 0
07:32:34.008178/SRT:RcvQ:w1*E:SRT.cn: HSREQ/rcv: Agent uses STREAM API, but the Peer declares MESSAGE API. Not compatible transmission type, rejecting.
```

**Expected behavior**
srt-tunnel passes on to Machine C

**Desktop (please provide the following information):**
 - OS: Ubuntu Server 22.04
 - SRT Version / commit ID: 1.5.1

**Comment by ethouris** [comment]
The srt-tunnel application is using file/stream mode and srt-live-transmit is using the live mode. These applications weren't ever intended to work together.

Why don't you simply run srt-live-transmit instead of srt-tunnel, with the same arguments.

**Comment by alatteri** [comment]
I need to get a stream from Los Angeles to Australia.  My plan was to get cloud machine in AUS, and bounce the signal from LA -> Cloud AUS -> endpoint AUS.  Now I could do srt-live-transmit all the way thru, but each hop adds incurred SRT latency.  I thought that srt-tunnel would pass the packets thru without adding additional SRT latency.  Guess not.  Thanks for the info.  Closing this as it is not a bug, but by design.

**Comment by ethouris** [comment]
You can set even a very small latency, but how big this latency should be, depends on the RTT between the endpoints. Even if you split the path by intermediate points, all you can save is that you set the minimum latency required for the particular fragment of the pathway.

**Comment by alatteri** [comment]
Let's assume the following situation.   A -> B-> C-> D.  Where A & D are geographically separated by large distances (inter-continental).

A is source stream.  D is receiving endpoint.  B & C are AWS cloud machines used as passthrough with optimized routes.  
A -> D direct uses unknown routes on public internet path.  I'm going to make up RTT numbers here just for demonstration.

A -> D (RTT=300ms) Un-optimized public internet route.

[A -> B (RTT 100ms)] --> [B->C (RTT 100ms)] --> [C->D (25ms)] - Total RTT=225ms.  Using optimized long distance backbone of AWS.

Now lets look at same thing with SRT_LATENCY using a multiplier of 3x.

A -> D (SRT_LATENCY=900ms)

[A -> B (SRT_LATENCY 300ms)] --> [B->C (SRT_LATENCY 300ms)] --> [C->D (SRT_LATENCY 75ms)] - Total SRT_LATENCY=675ms.   

Even here  multiple hop SRT still wins.  But what if you could use a "srt-tunnel" that instead of adding SRT_LATENCY at each hop, it just passes SRT packets and the endpoint srt receiver (D) does the NACKs back to original sender (A).  In that case we still have an  SRT_LATENCY= 675ms.  (100+100+25)*3=675ms.   But this all is assuming that multiple hop solution here assumes no in-efficiency of SRT, such that there is no additional latency added during processing of incoming and outgoing stream.  If each step of SRT ingestion/egress adds let's say 20ms, we are now incurring additional latency penalties at each hop. (300+20)+(300+20)+75=715ms

Would a "stream" aware SRT-TUNNEL forward the packets without such penalty?

All this is just assumptions on my part, and dialog.

Thanks,
Alan
