### ISSUE TITLE
Headers for compile

### ISSUE THREAD

**Issue by lars18th** [Haivision/srt#265]
Hi,

Perhaps this sounds as an stupid request. However, after compile it I can't see the "headers" for compile other programs using the API (srt.h). All the files are mixed in the package.

So, can you add a target for put all headers in the right place?
Thank you!

**Comment by ethouris** [comment]
Not sure if I understand.

The current regulations are the following:

1. All headers that belong to API are declared in `filelist.maf` as PUBLIC HEADERS and PROTECTED HEADERS (the latter are those that should not be included directly by the application). These exactly headers are extracted for installation.
2. Public header files are contained in the source directory together with all other sources.
3. The "in-package apps" use the NONINSTALLED version of the headers, so they use the `-I` path directly to the source directory and they don't use directory prefix: `#include <srt.h>`. The same for library - they use a NONINSTALLED version directly from the build directory.
4. The external apps should use the official method of reaching includes and libraries as from where it should be, that is, the installation directory, which follows the usual POSIX directory layout. The SRT header files are additionally contained in `srt` directory, so external apps should use `#include <srt/srt.h>`.

I think this "put all headers in the right place" is exactly what is being done when you run `make install`.

**Comment by lars18th** [comment]
Hi @ethouris ,

Thank you for clarification. This info isn't in any DOC or WIKI. So for this reason I ask for it! :smile: 

Some comments:

> All headers that belong to API are declared in filelist.maf as PUBLIC HEADERS and PROTECTED HEADERS (the latter are those that should not be included directly by the application). These exactly headers are extracted for installation.

Great! The info in the file `srtcore/filelist.maf` it's the one that I need.

> Public header files are contained in the source directory together with all other sources.

I perfer to have "public" headers in a independent directory (like `include`). Why? Because with this it's very easy to _distribute_ manually the binary library and the headers for use in another project.

> The "in-package apps" use the NONINSTALLED version of the headers, so they use the -I path directly to the source directory and they don't use directory prefix: #include <srt.h>. The same for library - they use a NONINSTALLED version directly from the build directory.

I can't see any declaration of `NONINSTALLED` in the entire project. Can you explain more?

> The external apps should use the official method of reaching includes and libraries as from where it should be, that is, the installation directory, which follows the usual POSIX directory layout. The SRT header files are additionally contained in srt directory, so external apps should use #include <srt/srt.h>.
I think this "put all headers in the right place" is exactly what is being done when you run make install.

This is right for regular use. However, when you need to cross-compile for example, then the use of other paths is valuable. Now I see that the solution is easy: copy the entire `srtcore/` directory and remove all except "*.h" files. However, in this case the file `version.h` is missing. You need to copy it from a compiled version.

Thank you!

**Comment by ethouris** [comment]
My bad, I wrote NONINSTALLED just to emphasize the statement - not that it were any symbol declaration :D I should have written **noninstalled** rather probably :)

Noninstalled, means, that the internal applications are taking the header files directly from where they are located in the source directory. In contrast to external applications which would like to use SRT library, which use the "installed" ones - that is, from the location where they are copied when you do "make install".

So, I can tell you we are also doing crosscompiling and SRT project is fully prepared for that. Why don't you simply do:

   ./configure --prefix target --with-compiler-prefix=/path/to/your/crosscompiler/

When you do `make install` this will create a local directory here named `target` and it will put all files exactly according to the standard POSIX directory layout inside. You then got exactly what you need - all libraries, header files only those that you need, also applications.

This description surely should be placed on the Wiki, I'll see to that - very good suggestion.

**Comment by lars18th** [comment]
Hi,

Maybe this looks too nooby. However, as I like to promote the compilation of the SRT library with _any_ external project (even C projects in other platforms and with cross-compilation)...

Here a simple guide for compiling the tool `examples/testcapi-connect.c` (or any custom program **in C**):

- First compile the SRT library ("dev" branch at time), with parameter `./configure --use-static-libstdc++`. This it's required for linking with C projects.
- Create the directories `examples/include/` and `examples/lib/`.
- Copy all required headers to  `examples/include/` (you can see the list in the file "srtcore/filelist.maf", they are the PUBLIC and PROTECTED headers, plus the file `version.h` that only exists in the form of ".in" in the srtcore). The current list its:
-- logging_api.h
-- platform_sys.h
-- srt4udt.h
-- srt.h
-- udt.h
-- version.h
- Copy static library (`libsrt.a`) to `examples/lib/`.
- Then you can compile using this command line: `c++ -DENABLE_LOGGING=1 -Wall -Wextra -O3 -DNDEBUG -rdynamic -I./include -L./lib testcapi-connect.c -lsrt -o testcapi-connect -lssl -lcrypto -lpthread
`

The result it's the file `testcapi-connect` that it's an executable statically linked with the SRT library that only depends on regular libraries.

I hope this helps! :smile:

**Comment by maxlovic** [comment]
Closed as #276 was merged. Do not hesitate to reopen if there is still something left unsolved.
