### ISSUE TITLE
seqlen always > 0

### ISSUE THREAD

**Issue by marakew** [Haivision/srt#2656]
https://github.com/Haivision/srt/blob/f57beb6ef957204b6fd563fe45e91a47d5351009/srtcore/common.h#L651

when seqlen < or == 0 ?
your are always use at many places as check result >= 0 or <= 0
https://github.com/Haivision/srt/blob/f57beb6ef957204b6fd563fe45e91a47d5351009/srtcore/list.cpp#L123
https://github.com/Haivision/srt/blob/f57beb6ef957204b6fd563fe45e91a47d5351009/srtcore/group.cpp#L2131
https://github.com/Haivision/srt/blob/f57beb6ef957204b6fd563fe45e91a47d5351009/srtcore/group.cpp#L2135
there are no sense i think

**Comment by ethouris** [comment]
As for explanation: there is kinda weak guarantee that the sequence number is written on 31 bits only, and `m_iMaxSecNo` is equal to 0x8000000-1, and therefore only 31 bits are taken to read the message number, so this number is physically unable to exceed this value, even if read from the packet data.

There is, however, no guarantee that the values from `seq1` and `seq2` really come from a source that has certainly cut off all bits above 31. In cases like this, various things may happen, and these checks are precautions to prevent an impossible situation from killing the application.

Although the function `isValidSeqNo` from `group.cpp` looks like kinda ignoring special conditions concerning the `seqlen` function, @maxsharabayko what do you think?

**Comment by marakew** [comment]
> Let's go on shortcut. Can you tell us, what exactly tool you are using to find these kind of problems? We might address multiple problems at once this way.

pvs studio static analyzer
you can do the same check

yes i have many notice after analyze about srtlib
but i make issue only an interesting as iam decide

**Comment by maxsharabayko** [comment]
For a longer list of warning please see [SRT in SonarCloud](https://sonarcloud.io/project/issues?resolved=false&id=srt). Although, a lot of them suggest using C++17.

**Comment by maxsharabayko** [comment]
```c++
EXPECT_EQ(CSeqNo::seqlen(0, 2147483647), -2147483648);
```
