### ISSUE TITLE
C API example outdated

### ISSUE THREAD

**Issue by lars18th** [Haivision/srt#267]
Hi,

I like to start to include the srt library in one C project. So, I'm checking the `apps/testcapi.c` example. However, this file is outdated. It doesn't compile. I can prepare a simple patch for fix the compilation; however it still doesn't run (because a crash dump).

My suggestion, if you agree, it's this:

- Create a new directory `examples` for put in it C and C++ API examples.
- Move the `apps/testcapi.c` to `examples/testcapi.c` and add a simple build script and a readme.
- Upgrade the example to a more detailed source. For example, using the proposed https://github.com/Haivision/srt/pull/21
- Add to the compilation of the package the _testing_ of these examples, but only for checks linking to the `libsrt.so/a` (remove after end).
- Improve the documentation about how to use the library in C and C++ projects.

What you think?

**Comment by ethouris** [comment]
I'm currently working on that and yes, that's a correct suggestion. I think there will be also more examples, some simple programs that users can play with.

**Comment by ethouris** [comment]
#270 Is provided with fixes in the testapi.c file; it's also moved to "examples" directory.

Test for linking should be well enough done when linking the official applications.

The documentation should be provided in docs/API.md file.

**Comment by lars18th** [comment]
Hi @ethouris ,

Good work! However, some conflicts exist. I do a comment in the PR regarding lost changes in the _movement_ of source files. https://github.com/Haivision/srt/pull/270#issuecomment-364425379

I'll review in more detail in the next days.

**Comment by lars18th** [comment]
The update it's in the PR #276

**Comment by maxlovic** [comment]
Closed with PR #276 merged.
