### ISSUE TITLE
[FR] Override global log level for a functional area

### ISSUE THREAD

**Issue by Chardrazle** [Haivision/srt#2673]
We had a scenario where the log produced from the `SRT_LOGFA_BUF_RECV` functional area produced a lot of noise ("RCV-DROPPED") at _warning_ level.

We have several options to reduce this noise; however, none of them are ideal.  For example:

* Adjust the global logging level.
 This has the danger of then missing information across the board.
* Switch off logging for the functional area.
 We may still be interested in seeing logs for the functional area at (e.g.) _error_ level.
* Perform our own filtering in the logging callback.
 This is likely to add an overhead.

It would be useful to be able to set a logging-level override for a functional area.  This looks like it could be solvable (mainly) in the `LogDispatcher::CheckEnabled` method.  For example, the single enabling flag for a functional area (in the bitset) could be changed to a logging-level that overrides the global level.

**Comment by ethouris** [comment]
@maxsharabayko I think this is the time to make the solution provided in #2602 reusable.
