### ISSUE TITLE
[BUG] Compiler warning: uninitialized var used

### ISSUE THREAD

**Issue by xback** [Haivision/srt#2698]
[16/30] Building CXX object CMakeFiles/srt_virtual.dir/srtcore/packet.cpp.o
/home/koen/git/openwrt_staging/build_dir/target-mips_24kc_musl/libsrt-1.5.1/srtcore/packet.cpp: In constructor 'srt::CPacket::CPacket()':
/home/koen/git/openwrt_staging/build_dir/target-mips_24kc_musl/libsrt-1.5.1/srtcore/packet.cpp:179:27: warning: member 'srt::CPacket::m_nHeader' is used uninitialized [-Wuninitialized]
  179 |     , m_iSeqNo((int32_t&)(m_nHeader[SRT_PH_SEQNO]))
      |                           ^~~~~~~~~
[30/30] Creating library symlink libsrt.so.1.5 libsrt.so

Compiler used:  GCC 12.2

**Comment by maxsharabayko** [comment]
Similar issue #2400.
Please specify the SRT version/commit you are building.

**Comment by xback** [comment]
It was the 1.5.1 tagged release tarball

**Comment by maxsharabayko** [comment]
@xback Please check with 1.5.2 RC.2.
