### ISSUE TITLE
Resource allocation failure - not processing further

### ISSUE THREAD

**Issue by aunhappy** [Haivision/srt#2713]
> You are encouraged to ask general questions regarding SRT in the [SRT Alliance Slack channel](https://slackin-srtalliance.azurewebsites.net/).  the link is broken for me.

when I tried the command, 
```
ffmpeg -i libx265-demo.mp4 -f mpegts "srt://live-push.bilivideo.com:1937?streamid=#!::h=live-push.bilivideo.com,r=live-bvc/?streamname=live_5154*_*917,key=5b83bb9c6d*_*289a7ef8a32861af1e,schedule=srtts,pflag=1"
```
I got the error
```
18:27:07.806000/!W:SRT.cn: @267920422: processConnectResponse: rejecting per reception of a rejection HS response: ERROR:RESOURCE
18:27:07.806000/!W:SRT.cn: @267920422: processAsyncConnectRequest: REJECT reported from HS processing: Resource allocation failure - not processing further
[srt @ 0000022d672a1540] Connection to srt://live-push.bilivideo.com:1937?streamid=#::h=live-push.bilivideo.com,r=live-bvc/?streamname=live_5154*_*917,key=5b83bb9c6d*_*289a7ef8a32861af1e,schedule=srtts,pflag=1 failed (I/O error), trying next address
18:27:07.890000/!W:SRT.cn: @267920421: processConnectResponse: rejecting per reception of a rejection HS response: ERROR:RESOURCE
18:27:07.890000/!W:SRT.cn: @267920421: processAsyncConnectRequest: REJECT reported from HS processing: Resource allocation failure - not processing further
[srt @ 0000022d672a1540] Connection to srt://live-push.bilivideo.com:1937?streamid=#::h=live-push.bilivideo.com,r=live-bvc/?streamname=live_5154*_*917,key=5b83bb9c6d*_*289a7ef8a32861af1e,schedule=srtts,pflag=1 failed: I/O error
srt://live-push.bilivideo.com:1937?streamid=#::h=live-push.bilivideo.com,r=live-bvc/?streamname=live_5154*_*917,key=5b83bb9c6d*_*289a7ef8a32861af1e,schedule=srtts,pflag=1: I/O error
```
i'm not sure whose problem it is, ffmpeg or srt. Can anyone help me? Thanks.
And I download ffmpeg from this [link](https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-gpl.zip). The platform is win64.

**Comment by oviano** [comment]
From looking at that code, and from my own experience, that error can occur when it can't initialise the encryption for some reason (although it can also occur for other reasons).

Do you have more details about where that build comes from and how it was configured - maybe your command line is trying to encrypt it but it wasn't built with encryption or something?

**Comment by maxsharabayko** [comment]
> rejecting per reception of a rejection HS response: ERROR:RESOURCE

See also [Rejection Codes](https://github.com/Haivision/srt/blob/master/docs/features/access-control.md#rejection-codes).
Probably the server (listener) has rejected your connection.

> The listener callback handler is also able to decide about rejecting the incoming connection. In a normal situation, the rejection code is predefined as SRT_REJ_RESOURCE. The handler can, however, set its own rejection code. 

I am also not quite sure if FFmpeg supports SRT Stream ID.

**Comment by ethouris** [comment]
What you are likely missing here is that this is a code received from the peer. So the problem IS NOT in the command that you have run here, it's reported from the application to which your command is connecting.

By the code value I can see that this peer application had a problem with resource allocation. That's something you don't see every day, to say the least; I could speculate that it was tried to allocate some large portion of memory for some buffers, which may result from some parameter values, but this thing can be only traced for sure by checking what happened on the peer application.
