### ISSUE TITLE
I can't seem to build srt with my own custom openssl version

### ISSUE THREAD

**Issue by TJBrunson** [Haivision/srt#2715]
My project depends on a specific version of openssl. I am trying to configure/make srt while pointing at my specific openssl lib. Its important to note my project structure:

1. I have the standard openssl installed on my system. 
2. I have an older openssl version that is dynamically linked inside my project

My goal is to use the --open-use-static-libs option with --openssl-crypto-library, --openssl-include-dir, and --openssl-ssl-library. Like this: 
```
./configure --openssl-crypto-library=/home/wherever/openssl/lib --openssl-ssl-library=/home/wherever/openssl/lib --openssl-include-dir=/home/wherever/openssl/include --openssl-use-static-libs
```

When I do this, I get this output:
```
CMake Warning:
  Manually-specified variables were not used by the project:

    OPENSSL_CRYPTO_LIBRARY
    OPENSSL_INCLUDE_DIR
    OPENSSL_SSL_LIBRARY
```
Which indicates that my specified library paths aren't taken into account. Based on my reading of CMakeLists.txt, they are either named wrong or not taken into account if SSL could not be found by pkg-config.

So can I not do this because I also have openssl actually installed on the system? Or am I making some other mistake?

**Comment by oviano** [comment]
I wonder if you added use_openssl_pc=off whether that would help?

That option tells CMake not to use pkg-config, so maybe this would persuade it to use your own supplied libs rather than the system-installed ones?
