### ISSUE TITLE
build SRT with --enable-heavy-logging success,but ffmpeg still not print srt detailed log

### ISSUE THREAD

**Issue by bigmisspanda** [Haivision/srt#2719]
**my configuration:**
srt:./configure --enable-heavy-logging
ffmpeg:/configure --prefix=/usr/local/ffmpeg --enable-libsrt --enable-shared --disable-static
**when ffmpeg build succss,I test with**
 ./ffmpeg -loglevel debug  -re -i /home/ffmpegsource/龙虎山.mp4  -codec copy -f mpegts 'srt://192.168.0.125:10080?passphrase=fcymfcymfcym&latency=10000000&timeout=7000000&pbkeylen=16&streamid=#!::h=live/OPU-9-08,m=publish
but nothing srt detail log showing up.

![image](https://user-images.githubusercontent.com/12532421/232692010-24c4149a-7463-4a1c-ad22-c398fd9d839c.png)

**Comment by ethouris** [comment]
This option only enables the "heavy" (usually detailed debugging) logs. That is, without this option they will not be in the library code. Note that all other logs are enabled by default.

Whether logs of the `LOG_DEBUG` level are enabled to be printed in ffmpeg and in SRT is another matter.

**Comment by bigmisspanda** [comment]
> This option only enables the "heavy" (usually detailed debugging) logs. That is, without this option they will not be in the library code. Note that all other logs are enabled by default.
> 
> Whether logs of the `LOG_DEBUG` level are enabled to be printed in ffmpeg and in SRT is another matter.

yes,I do understand LOG_DEBUG is the ffmpeg log option,what I try to do is like https://github.com/Haivision/srt/issues/1050.I want to find some more useful log to debug .but not success yet.

**Comment by ethouris** [comment]
I don't know the structure of ffmpeg, I can only tell you that SRT provides a possibility to bind the logging system with any upper-level logging system the client provides. I tried to take a look at the ffmpeg sources and unfortunately I can't see the call to `srt_setloglevel` function anywhere. Of course if you had an application using ffmpeg, you can call it yourself independently, but if you are using the `ffmpeg` command, it may be needed that you modify the code a bit (for example, add the call to `srt_setloglevel(LOG_DEBUG)` inside `libsrt_open` function).

**Comment by bigmisspanda** [comment]
> I don't know the structure of ffmpeg, I can only tell you that SRT provides a possibility to bind the logging system with any upper-level logging system the client provides. I tried to take a look at the ffmpeg sources and unfortunately I can't see the call to `srt_setloglevel` function anywhere. Of course if you had an application using ffmpeg, you can call it yourself independently, but if you are using the `ffmpeg` command, it may be needed that you modify the code a bit (for example, add the call to `srt_setloglevel(LOG_DEBUG)` inside `libsrt_open` function).

oh,that was really help.thanks,cheers~
