### ISSUE TITLE
[FR] Silence compiler warning for gcc -Wshadow=local

### ISSUE THREAD

**Issue by Chardrazle** [Haivision/srt#2725]
The gcc `-Wshadow=local` warning isn't that common, but on rare occasions can discover something.
Give there's only one case of it in the SRT (main) build, it would be nice to silence it.

https://github.com/Haivision/srt/blob/6fcff6dfe4eed9df17a05168b88b5b069808c91c/srtcore/epoll.cpp#L218

(There are others in the unit-tests.)

**Comment by maxsharabayko** [comment]
Thanks for spotting! Those are better to fix rather than silence. 🙂 
Addressed in PR #2726.

**Comment by Chardrazle** [comment]
Sure; I meant to imply fix when I said silence. We tend to build with a lot of extra gcc warnings.
Thank-you.
