### ISSUE TITLE
SRT Connection time out error

### ISSUE THREAD

**Issue by nobimac7449** [Haivision/srt#2737]
Hello team,

I'm facing an issue while connecting to socket on my local server, Where i am getting an error of connection time out (1001) shown in attached screen shots. 

Is there any default SRT socket address and port using which i can test my code on connection socket?

Here is my code 
![Screenshot 2023-05-16 at 10 49 38 AM](https://github.com/Haivision/srt/assets/62747013/032fb598-99c7-4109-9e4f-a68a059a2135)

Error log
![Screenshot 2023-05-16 at 10 27 35 AM](https://github.com/Haivision/srt/assets/62747013/34c78e58-8f83-486e-8c3b-4579ec8f9587)

**System Configuration**
- Xcode 14.2
- Lang: Objective C
- SRT Lib: 1.5.2

**Comment by ethouris** [comment]
Try to make a test application (or use some tool like netcat) and see if you can send a UDP packet to the specified address:port endpoint and display its source endpoint, then send a UDP packet in the opposite direction and see if it is also received.

If this is working, please add this line in your application: `srt_setloglevel(LOG_DEBUG)`

Then run and and send us back the logs that the application prints after running.
