### ISSUE TITLE
Failed building SRT on iOS

### ISSUE THREAD

**Issue by martinzsapka** [Haivision/srt#2741]
Hello!

I followed the instructions in the documentation (https://github.com/Haivision/srt/blob/master/docs/build/build-iOS.md), but unfortunately I got the following error when I tried to build SRT. 

When I run the command
`./configure --cmake-prefix-path=$IOS_OPENSSL --use-openssl-pc=OFF --cmake-toolchain-file=scripts/iOS.cmake
make`

I got the following error message:
`CMake Error at /opt/homebrew/Cellar/cmake/3.26.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY
  OPENSSL_INCLUDE_DIR)
Call Stack (most recent call first):
  /opt/homebrew/Cellar/cmake/3.26.3/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /opt/homebrew/Cellar/cmake/3.26.3/share/cmake/Modules/FindOpenSSL.cmake:670 (find_package_handle_standard_args)
  CMakeLists.txt:428 (find_package)`

I also carried out the previous steps of the build process (building OpenSSL, set IOS_OPENSSL variable)

Do you have any idea what the problem is?

_Hardware spec:
MacBook Air M1
macOS Ventura 13.3.1_

Thanks!

**Comment by ethouris** [comment]
What do you get when run:
```
ls $IOS_OPENSSL
```
?

**Comment by ethouris** [comment]
Closing due tu inactivity
