### ISSUE TITLE
The udp stream in local 2 lan was not working 

### ISSUE THREAD

**Issue by AMDahamed** [Haivision/srt#2750]
When asking a question please also include where you looked for an answer (so we can update the documentation if needed).

You are encouraged to ask general questions regarding SRT in the [SRT Alliance Slack channel](https://slackin-srtalliance.azurewebsites.net/).

The udp stream in local 2 lan was not working but in primary lan in which internet working there it was working ?

can you give me the solution

srt-live-transmit  "srt://:2003" "udp://224.30.30.140:3000localaddr=192.168.5.140" 
OS: ubuntu / rasbian (Raspberry pi) i want to send the udp stream to laptop through eth2 that ip was 192.168.5.140 through this olny plz.. reply

**Comment by ethouris** [comment]
I can't see how SRT is involved here. The command-line you showed uses SRT in listener mode with listening on all local interfaces.

If the problem is that you can't connect to it from a different LAN, you should get the rejection code at the caller side (the listener side doesn't report any connection failures). For `srt-live-transmit` use `-a no` option to prevent it from reconnection on connection break so that you can see the error message.

**Comment by maxsharabayko** [comment]
Note that a quotation mark is missing here: `"udp://224.30.30.140:3000localaddr=192.168.5.140"`.
Also `localaddr` is an unknown URI query option, I believe.
[Documentation on `srt-live-transmit`](https://github.com/Haivision/srt/blob/master/docs/apps/srt-live-transmit.md).

**Comment by AMDahamed** [comment]
![Cn1](https://github.com/Haivision/srt/assets/132189855/0015ed2d-2f29-438e-89d2-59cc70be26cc)



This is my concept i have tried but it was working only in primary lan only not in particular lan is it have any solution for this 
i am using srt-live-transmit to convert srt to udp 

srt-live-transmit "srt://:2525" "udp://224.1.1.1:1234?localaddr=192.168.5.140"

192.168.5.140 this was my 2d la ip address 

if it solved thank in advance.......

**Comment by AMDahamed** [comment]
> Note that a question mark is missing here: `"udp://224.30.30.140:3000localaddr=192.168.5.140"`. Also `localaddr` is an unknown URI query option, I believe. [Documentation on `srt-live-transmit`](https://github.com/Haivision/srt/blob/master/docs/apps/srt-live-transmit.md).

https://github.com/Haivision/srt/issues/2750#issuecomment-1593490495

**Comment by AMDahamed** [comment]
> I can't see how SRT is involved here. The command-line you showed uses SRT in listener mode with listening on all local interfaces.
> 
> If the problem is that you can't connect to it from a different LAN, you should get the rejection code at the caller side (the listener side doesn't report any connection failures). For `srt-live-transmit` use `-a no` option to prevent it from reconnection on connection break so that you can see the error message.

https://github.com/Haivision/srt/issues/2750#issuecomment-1593490495

**Comment by ethouris** [comment]
Again: There's no such thing as `localaddr` for the UDP URI. Please review the documentation mentioned in the link above, especially the "Medium: UDP" section. There's also a subsection dedicated specifically to your case, sending to multicast UDP.
