### ISSUE TITLE
[FR] Provide srt_select API

### ISSUE THREAD

**Issue by xiaozhihong** [Haivision/srt#2756]
I found the code in https://github.com/Haivision/srt/blob/master/srtcore/api.h#L302-L303, the select/selectEx API had been implemented, but no API provides in srt.h, why not provide it? I can submit a pull request to support it.

**Comment by ethouris** [comment]
The `select` and `selectEx` functions are still available through the legacy UDT API, for which you have to `#include <srt/udt.h>`. Note that this is a C++-only API and functions are enclosed in the `UDT` namespace, and it is deprecated.

We didn't provide this because we would have to completely reimplement them so that they can accept parameters that can be used in a C API, as well as they are rather inefficient, and epoll provides exactly the same functionality. Note also that these functions are available only for SRT sockets. If your application needs only to wait for SRT sockets, you may consider using `srt_epoll_uwait`, which has a slightly better interface than `srt_epoll_wait`.

Normally this function should be used this way:

```
int64_t timeout = 1000; // 1s
vector<SRTSOCKET> read_poll, read_ready, error_ready;
read_poll.push_back(socket1);
read_poll.push_back(socket2);
...
int res = UDT::selectEx(read_poll, &read_ready, NULL, &error_ready, timeout);
if (res)
{  
// handle read_ready and error_ready sockets
}
```

Because you define for which direction you want to poll readiness by specifying the target vector or NULL. The same exactly effect you can have by using this:

```
int64_t timeout = 1000; // 1s
int eid = srt_epoll_create();
int read_err = SRT_EPOLL_IN | SRT_EPOLL_ERR;
srt_epoll_add_usock(eid, socket1, &read_err);
srt_epoll_add_usock(eid, socket2, &read_err);
SRT_EPOLL_EVENT ready_sockets[2];
...
int res = srt_epoll_uwait(eid, ready_sockets, 2, timeout);
if (res)
{
   // handle items in `ready_sockets` array
}
```

**Comment by xiaozhihong** [comment]
Thanks for your reply, I found it now. I'm sorry for my carelessness.

 I want to check if there are any new sockets available to be accepted once. But the `SRTO_EVENT` option doesn't meet my requirements because it only cares about the data socket which is not in the listening state. And I don't want to use srt_epoll because it's too complex for one check, so `select` may be the best choice. 

Is there any API that can meet my requirements? Or the `SRTO_EVENT` can return the listening socket's state?

**Comment by ethouris** [comment]
To check if a socket can be accepted off a listener socket (with some timeout), you should subscribe this listner socket's SRT_EPOLL_IN event.

Alternatively you can try to use `srt_accept_bond`. This function requires you to pass an array of listener sockets, but you can just as well put just one in the array. And, in distinction to `srt_accept`, it allows for timeout, after which it returns a typical nonblocking-mode error, if there's no connection pending. Of course, this function simply uses epoll internally, but for your purpose it might be easier.

**Comment by xiaozhihong** [comment]
https://github.com/ossrs/srs/blob/43dfb1bcaa28271a13758473f38adb7220a291f5/trunk/src/protocol/srs_protocol_srt.cpp#L749-L777

**Comment by xiaozhihong** [comment]
My code is in https://github.com/ossrs/srs/blob/43dfb1bcaa28271a13758473f38adb7220a291f5/trunk/src/protocol/srs_protocol_srt.cpp#L749-L777
It works like this.
![image](https://github.com/Haivision/srt/assets/8449258/5a2b8b55-10b0-4b16-9d41-6d7765e72a56)


Can reference this article [Coroutine Native for SRT](https://ossrs.net/lts/en-us/blog/coroutine-native-srt)
And when I start the server, the error log is shown below.

![image](https://github.com/Haivision/srt/assets/8449258/7b11dce3-3abd-47fe-a709-6ba3ead895b8)

So I want to change the code to avoid the error message from
```
srt_accept()
```
to 
```
if (have_sockets_to_accept) {
    srt_accept()
}
```

**Comment by ethouris** [comment]
Then just call `srt_accept_bond` with zero timeout. This will return you the accepted socket, if available, and if not, it will return error with `SRT_ETIMEOUT`.

**Comment by xiaozhihong** [comment]
`srt_accept_bond` can work, but have a problem, it always returns SRT_ETIMEOUT when the client socket has already inserted into the accept queue because the temporary srt epoller create after the socket had been accepted.

**Comment by ethouris** [comment]
If you get `SRT_ETIMEOUT` from this call it means that no packet is waiting for accept at the moment. If you know that one should be waiting and you get this result, it means that some other functionality has extracted it already by calling `srt_accept` or similar.

Epoll plays no role here. You can subscribe the same socket to multiple EIDs and all of them should be updated on readiness of a socket. This works differently only if you use the edge-triggered flag (SRT_EPOLL_ET), but this must be done explicitly. And a accept-candidate socket cannot simply "disappear" from the listener queue unless you explicitly retrieve them by calling `srt_accept`.

**Comment by xiaozhihong** [comment]
Thanks for your reply.
