### ISSUE TITLE
srt-live-transmit with fec

### ISSUE THREAD

**Issue by yuchengmao** [Haivision/srt#2761]
when i use srt-live-transmit with packetfilter=fec,cols:10,rows:5, there's always this error: SRT:RcvQ:w1!W:SRT.pf: FEC/V: rebuilding/hanging FAILED, does it matter? What can I do to eliminate this mistake?

**Comment by ethouris** [comment]
This message appears - in this case for a vertical group - if the sequence number of the incoming packet could not be matched to any of the existing active FEC groups. Hard to say from upside what this could be, only the debug logs can provide some details. Might also be that the incoming packet is a retransmitted packet even requested through irrecoverable situation in FEC and it's too old to fit in any group.

If you would like to track it down, the best would be to enable debug logs with limited FA to packet filter.

Debug logs are usually in the heavy category so you need to enable them at compile time (-DENABLE_HEAVY_LOGGING=1 or -DENABLE_DEBUG=1). Then run the application with these options:
```
-ll debug -lfa pfilter
```

**Comment by maxsharabayko** [comment]
@yuchengmao Please specify the SRT version you are using.

**Comment by yuchengmao** [comment]
@maxsharabayko SRT Library version: 1.5.2, clock type: GETTIME_MONOTONIC

**Comment by yuchengmao** [comment]
@ethouris Okay, thanks. I'll try it later.

**Comment by ethouris** [comment]
Likely solved and long inactive - closing.

**Comment by ethouris** [comment]
Closing: over 1 month inactivity. Please reopen if anything is still irresolved.
