### ISSUE TITLE
Question: Thread safe?

### ISSUE THREAD

**Issue by lars18th** [Haivision/srt#277]
Hi,

I need to know if the SRT library is thread safe.

I like to incorporate it in a current project that uses multiple threads. Mainly working threads that each one controls one connection. However, a centralized data it's managed using semaphores and all thread can use it.

So, if I use the SRT library (in C, as this project not uses C++)... what I need to know for not have thread errors calling to the library from different threads?

**Comment by alexpokotilo** [comment]
Hi,
we use SRT for both publishing and receiving SRT streams in our program. We have separate threads for publishing and receiving. We use async api and process all publishing in single thread while process all receiving in another thread. Everything work fine.

**Comment by ethouris** [comment]
SRT uses threads by itself, so it must be thread safe by definition.

Just remember what exactly you want to do with multiple threads. The following things are allowed:
- use one thread per connection and read-write operations are done on particular socket in the thread assigned to this socket exclusively
- you can close a socket from another thread in order to interrupt a blocking operation

which is rather not different to thread safety of the system sockets.

**Comment by lars18th** [comment]
Hi,

Thank you! Great news to know. :smile:

**Comment by alexpokotilo** [comment]
@ethouris "you can close a socket from another thread in order to interrupt a blocking operation".
It's bad idea from my POV. I think it's better to use send/receive timeout to return from send/receive and check exit flag set from another thread.

**Comment by alexpokotilo** [comment]
@ethouris maybe I'm wrong

**Comment by ethouris** [comment]
Alex: To have a "timeout for operation" you can use non-blocking mode and `srt_epoll_wait`, which can have a timeout. I know that there are various concepts along to which this can be designed, but we'd like not to go too far from the overall concept of using the system devices that everybody is familiar with. The original UDT library has driven it to the extreme, by following the POSIX API even when it doesn't make any sense (e.g. functions with always unused parameters like `UDT::socket` or `UDT::setsockopt`, just to have the exact number of parameters as the system `socket` and `setsockopt` functions) - in SRT we are not **that** extreme. But still, we aim to follow at least the overall understood philosophy. The blocking mode is generally for the use with threads, whereas the non-blocking mode with fibers.

**Comment by ethouris** [comment]
Ah, note that there are also options: `SRTO_RCVTIMEO` and `SRTO_SNDTIMEO`, which may define the maximum time to wait for having data/possibility to send data. I think I saw similar options in the system.
