### ISSUE TITLE
[FR] Accept a listener backlog value of zero

### ISSUE THREAD

**Issue by lelegard** [Haivision/srt#2783]
**Is your feature request related to a problem? Please describe.**

Using `srt_listen()`, the backlog parameter indicates the number of waiting incoming clients, in addition to the currently connected clients. The minimum value for the backlog is 1. Using 0, `srt_listen()` fails with a "Bad parameters" error.

Consider a listener application which will accept only one client and terminates when the unique client connection is terminated (this is the default behavior of the `srt` plugin in [TSDuck](https://github.com/tsduck/tsduck)). After `srt_listen()`, `srt_accept()` will be called once only. When the unique client session terminates, we `srt_close()` the listener socket and the client socket.

The expected behavior is that the first client should be accepted and any other subsequent client should be rejected.

Because the minimum backlog value is 1, the second client has its `srt_connect()` successful as well as all `srt_send()`. Forever. So, the second client may assume that it successfully participates in a communication while all its outgoing packets are sent to the void and oblivion.

In the third and subsequent clients, on the other hand, `srt_connect()` fails with a "Listener's backlog exceeded" error.

**Describe the solution you'd like**

In such a use case, after the first successful `srt_accept()`, all clients connections should fail, including the second one.

One possible solution is to accept the value zero as backlog in `srt_listen()`, meaning "zero additional connection".

However, I wonder if this has an impact on the processing of the first connection. If there is a `srt_accept()` in progress, waiting for the first client, will the connection be immediately accepted or will it be rejected because there is zero room for an incoming request?

**Additional question**

Out of curiosity, in the current situation, when the second client's `srt_connect()` succeeds and packets are sent (without formal `srt_accept()` on the other side), what is the impact of the sent packets in the listener process? Do they fill some internal buffer inside the listener process? Do they use any kind of resource in the listener process?

**Comment by lelegard** [comment]
> You can use the listener callback and reject there any but the first connection. 

Thanks @ethouris, good idea. It works well.

Just one additional question. On the `srt_connect()` side, on `SRT_ECONNREJ` error, the rejection reason is displayed using `srt_rejectreason_str(srt_getrejectreason(sock))`. I get the string "Application-defined rejection reason".

Since `srt_getrejectreason(sock)` is `SRT_REJX_OVERLOAD`, I can display a custom error message in that specific case.

However, is there a way to have an explanatory message string for `_REJX_` rejection reasons? It seems that `srt_rejectreason_str()` just returns  "Application-defined rejection reason".

**Comment by ethouris** [comment]
Yeah, we have in plan also some error messages assigned also to those REJX codes, but these codes are for free use for the application. These codes are only standardized to allow application use some "common meaning" of several errors, but the exact meaning is still application-specific.

**Comment by lelegard** [comment]
OK, thanks @ethouris. The originally requested feature is no longer necessary. The callback solution is more deterministic. I close this one.
