### ISSUE TITLE
Why is it that I set the size of rcvbuf but the actual m_pRcvBuffer->capacity() size doesn't change it is always 25599

### ISSUE THREAD

**Issue by yuchengmao** [Haivision/srt#2790]
<img width="1106" alt="image" src="https://github.com/Haivision/srt/assets/56284740/ebb125f5-bc5d-4213-a74b-2473702342f5">

**Comment by ethouris** [comment]
Do you check the result of `srt_setsockopt/srt_setsockflag`?

**Comment by ethouris** [comment]
Ok, to clear things up about the terminology: "Capacity" is the total size of the memory allocated by the buffer, and it encloses the used and unused space. Used space in the buffer is "size" and unused - "avail".

**Comment by yuchengmao** [comment]
I found that it seems to be limited by this parameter (SRTO_FC) to the rcvbuf max value

**Comment by yuchengmao** [comment]
<img width="721" alt="image" src="https://github.com/Haivision/srt/assets/56284740/6ea84980-f193-4045-824f-e671c945293d">

**Comment by yuchengmao** [comment]
Since I set the latency very large, it took a long time to release the packets in the buffer, so the rcvbuf was not enough

**Comment by ethouris** [comment]
Latency doesn't influence the buffer capacity. If it too small in particular circumstances, it should be adjusted. Whether it is, it depends not only on latency, but also bitrate, for which there is no corresponding option in SRT.

**Comment by maxsharabayko** [comment]
Please refer to the [Configuration Guidelines](https://github.com/Haivision/srt/blob/v1.5.3/docs/API/configuration-guidelines.md).
See also #700.
