### ISSUE TITLE
Meaning of state variables on the receiving end

### ISSUE THREAD

**Issue by yuchengmao** [Haivision/srt#2792]
I would like to ask the meaning of these two state variables on the receiver side: 
1, Metric<BytesPackets> recvd;
2, Metric<BytesPackets> recvdUnique;

**Comment by ethouris** [comment]
Meaning of the stats is [here](https://github.com/Haivision/srt/blob/master/docs/API/statistics.md).

In `core.cpp` the function `srt::CUDT::bstats` transcribes these internal variables into statistical structure.

**Comment by yuchengmao** [comment]
> 

I mean does this pktRecvUnique represent the number of raw data frames received while pktRecv represents the number of all packets received (including FEC packets and retransmission packets)?

**Comment by ethouris** [comment]
Have you read the [documentation](https://github.com/Haivision/srt/blob/master/docs/API/statistics.md#pktRecvTotal) ?

**Comment by yuchengmao** [comment]
> Have you read the [documentation](https://github.com/Haivision/srt/blob/master/docs/API/statistics.md#pktRecvTotal) ?
I think I found it. Thanks.

**Comment by yuchengmao** [comment]
> Have you read the [documentation](https://github.com/Haivision/srt/blob/master/docs/API/statistics.md#pktRecvTotal) ?
Hello, I have another question for you, how to enable dynamic FEC, that is to say, the col and row of packetfilter can be automatically adjusted

**Comment by ethouris** [comment]
Not implemented

**Comment by ethouris** [comment]
> Hello, I have another question for you, how to enable dynamic FEC, that is to say, the col and row of packetfilter can be automatically adjusted

Parameters of the connection cannot be changed during the connection.

However, if  you want to experiment a bit, there's a possibility for having a kinda soft handoff of the connection. Make a broadcast type group and simply establish a single connection within the group. At the moment when you would like to modify parameters of the group, add a new connection to the group (using different parameters) and close the old one. Personally I haven't tried that, but it might work. Just note that for a quick time for switching the link you'll have a high burst of packets, although the alternative is to simply break the connection and re-establish it, with accepted the cost of having a short transmission break.
