### ISSUE TITLE
Why i can not pull the same stream on 2 different decoders at the same time

### ISSUE THREAD

**Issue by youssef-haidar** [Haivision/srt#2800]
Hello everyone 👋​

I would really appreciate it, if someone would give an answer for a following doubt or question!!

As far as i know that SRT can be point to point , point to multi point, and point to all since it is based on UDP.

So i used to think that if my decoder was on caller (pulling a certain stream from xxx.xx ip and xxx port) and other decoder (caller) some where remotely also using the same ip, port, and passphrase would be able to pull the stream as well. But what i concluded that it if he managed to connect or started to pull the stream before me i wont be  able to pull and vice versa.

So how can i manage to recieve the same stream from the same source using same ip and port but from 2 different decoders which could be also far away from each other (different public ip)

Another question below?

What are the situations where we have to configure point to point and/or point to multi point can you please give me examples?

Thanks in advance

**Comment by jeandube** [comment]
@youssef-haidar The limitation you describe is not in SRT but in the application (device) implementing the SRT listener/sender. You should address your request in the appropriate forum or describe your listener/sender device.

**Comment by ethouris** [comment]
Think TCP.

If you have an application that awaits only one client to connect to the listening point and it sends the data stream only to one connected client and ignores all other potentially later connected ones, you'd get exactly the same result.

**Comment by stanislavpetkov** [comment]
There are some SW implementations over SRT, that are forcefully set only one accept at a time, because it is easy to manage the bandwidth of your internet connection. If you allow many (you don't know number in advance), than how you are going to calculate your bandwidth. It is application implementation, not SRT protocol itself.
