### ISSUE TITLE
srt_setsockflag(SRTO_MAXBW) failed after upgrading from v1.4.1 to v1.5.3

### ISSUE THREAD

**Issue by duiniuluantanqin** [Haivision/srt#2802]
After upgrading from v1.4.1 to v1.5.3, one of the interfaces encountered an error, with the error message: 
`Operation not supported: Bad parameters`.
```
int64_t maxbw = 20000;
srt_setsockflag(srtfd, SRTO_MAXBW, &maxbw, sizeof(maxbw))
```
Could you give me some hints?

**Comment by ethouris** [comment]
Ok, so this is the message (`strerror_defs.cpp`):
```
    "Operation not supported: Bad parameters", // MN_INVAL = 3
```

and this is the code that sets it (`socketoptions.cpp`):

```
template<>
struct CSrtConfigSetter<SRTO_MAXBW>
{
    static void set(CSrtConfig& co, const void* optval, int optlen)
    {
        const int64_t val = cast_optval<int64_t>(optval, optlen);
        if (val < -1)
            throw CUDTException(MJ_NOTSUP, MN_INVAL, 0);

        co.llMaxBW = val;
    }
};
```
So, the only possibility for your app to get this error is when a negative value has been passed, or such a kind of value has been interpreted from the bytestream you passed to the `srt_setsockflag` function, which maybe wasn't `int64_t` type, as required for this very option.

**Comment by duiniuluantanqin** [comment]
Thank you very much for your reply, it's been a great help. While debugging, I found that the `maxbw` variable indeed turned into a negative value. I will continue to analyze the root cause.
