### ISSUE TITLE
[BUG] Docs: iOS Build instructions don't fnd the correct OpenSSL

### ISSUE THREAD

**Issue by daytime-em** [Haivision/srt#2810]
**Describe the bug**
The build instructions in `build_iOS.md` don't work. On my system (M1 Mac Pro on Sonoma 14.0), `configure` will fail to locate the iOS OpenSSL builds. It tries to link with my OSX openSSL, which fails the build 

**To Reproduce**
1) Clone the project on OSX
2) Install cmake and pkg-config as directed
3) Build `OpenSSL-For-iPhone` as direced
4) run `configure` with the args given in the iOS build docs.
5) run `make`
6) observe that the build fails in the linking stage

**Expected behavior**
The build should not fail if you build in encryption. You can accomplish this using `pkg-config` and it seems fine.

This command works seems to appropriately and build all libs and tools
```console
./configure --ios-disable-bitcode=1 --openssl-include-dir=$OPENSSL_INCLUDE_DIR --openssl-crypto-library=$OPENSSL_ROOT_DIR --openssl-ssl-library=$OPENSSL_ROOT_DIR  --use-openssl-pc=ON --cmake-toolchain-file=scripts/iOS.cmake

make

```
These are the values of `$OPENSSL_INCLUDE_DIR` and `$OPENSSL_ROOT_DIR`:

```console
OPENSSL_ROOT_DIR=/Users/edixon/repos/OpenSSL-for-iPhone/bin/iPhoneOS17.0-arm64.sdk
OPENSSL_INCLUDE_DIR=/Users/edixon/repos/OpenSSL-for-iPhone/bin/iPhoneOS17.0-arm64.sdk/include
```

**Desktop (please provide the following information):**
 - OS: Cross-compiling for iOS on OSX Sonoma
 - SRT Version / commit ID: `f477af5`

**Additional context**
Sorry I didn't make a PR, but for some reason I couldn't (?)

**Comment by ethouris** [comment]
Wait. Why do you specify directories for openssl and simultaneously use `--use-openssl-pc=ON` ?

What do you get from `pkg-config --cflags openssl`?

**Comment by daytime-em** [comment]
After some more testing, I think I was just doing something wrong. I went back and tried again from a fresh clone and it worked fine.

Sorry for the bad report!
