### ISSUE TITLE
To srt encryption caller, must pdkeylen be set?

### ISSUE THREAD

**Issue by flnewsoft** [Haivision/srt#2814]
To a live listener srt srt://192.168.1.225:5757?passphrase=xxx&pbkeylen=32&enforcedencryption=true&mode=listener&ipttl=8&nakereport=1&listen_timeout=-1&pkt_size=1316
. I can get the stream using following command:
1. ./ffmpeg -i "srt://192.168.1.225:5757?passphrase=123456879123&pdkeylen=3&transtype=live&mode=caller" -c copy -f null /dev/null
2. /opt/bravo/bin/ffmpeg -i "srt://192.168.1.225:5757?passphrase=123456879123&pdkeylen=16&transtype=live&mode=caller" -c copy -f null /dev/null
3. /opt/bravo/bin/ffmpeg -i "srt://192.168.1.225:5757?passphrase=123456879123&transtype=live&mode=caller" -c copy -f null /dev/null

Is it means that pdkeylen could be ignore to srt caller?

**Comment by almson** [comment]
@ethouris But it says that for `HSv4` encryption is only enabled when SRTO_PBKEYLEN is set to non-0.

**Comment by ethouris** [comment]
Encryption is enabled only if `SRTO_PASSPHRASE` is set to an nonempty string. `SRTO_PBKEYLEN` only configures the key length. If it is written anywhere that the latter enables or disables encryption, please report this (using a separate PR) because it's wrong.

**Comment by almson** [comment]
@ethouris It says, `HSv4: This [PBKEYLEN] is set on the sender and enables encryption, if not 0.` So it implies that encryption is not enabled if it is 0.
