### ISSUE TITLE
+1 xxx 555 xxxx phone numbers test_5555skip_srt

### ISSUE THREAD

**Issue by rukker8** [Haivision/srt#2822]
Hello guys i recently stumbled across a bunch of phone numbers registered on WhatsApp all of them share the same pattern being a number from the usa they use any area code and most of the time only 5 after that
example +1 953 555 5555
the name of his account is weird "test_5555skip_srt" that's how i came to this thing in github because of the srt 
other people hat names like cheng smb test 
if anyone knows what's up with these numbers and why people are able to register them literally any random person is able to register them if he knows how (i don't) then tell me if you know something about these numbers

i already know they shouldn't be existing no worry

**Comment by maxsharabayko** [comment]
No idea and not related to the SRT protocol. Try srt subtitles format.
