### ISSUE TITLE
How to specify NIC with SRTO_BINDTODEVICE for a SRT caller in bonding mode

### ISSUE THREAD

**Issue by clime** [Haivision/srt#2825]
Hello,

I have a following pseudocode:

```
    for (size_t i = 0; i < addrs.size(); i++) {
        const char * iface_cstr = locations[i].interface.c_str();
        printf("caller connect interface: %s\n", iface_cstr);
        srt_setsockflag(fd, SRTO_BINDTODEVICE, (const void *) iface_cstr, strlen(iface_cstr));
        // in group mode, srt_connect returns ID of the newly created group socket
        srt_connect(fd, (const struct sockaddr *) &addrs[i], sizeof addrs[i]);
}
```

But getting:

```
caller connect interface: eno2
01:07:33 AM.833214/CMPTO_NET_INIT*E:SRT.gm: setsockopt(group): Group is connected, this option can't be altered
```

How to properly specify the interface for redundant connections?

Thank you!

**Comment by ethouris** [comment]
See `srt_create_config` and `srt_config_add`. In the documentation, `docs/API/API-functions.md`.

Note that some options must be set prior to connection and others prior to binding. As in case of socket groups member sockets are created automatically, the only way to inject some settings change between creation and connection is to use the configuration object.

Also don't forget that the use of `SRTO_BINDTODEVICE` requires running the app as root.
