### ISSUE TITLE
How to clone an srt input to multiple out?

### ISSUE THREAD

**Issue by openaspace** [Haivision/srt#2827]
Hi. 
I have created a personal srt relay where accept 30 srt input and automatically out the input, now i need that 1 srt out can be cloned to other 10 srt out stream obviously on different ports.

I have tried cloning the srt input using ffmpeg and output cloned to different ports, but each time i clone the latency encrease of 3 seconds proably for the ffmpeg process.. there is no way to clone an input using native srt library?

Thank you.

**Comment by ethouris** [comment]
I don't think ffmpeg exposes the socket to the outer world, so I have no idea what you mean by "cloning the input socket".

With TCP you have one endpoint that listens and can accept multiple connections. On the listening side you accept connections and get an individual socket for each one. If you want to make the listening side send the same to multiple outputs, you simply send the data to every socket extracted by accept().

If you have defined multiple outputs, to which you have to connect, then the same thing - you have a separate socket for each of them and send the same data to them one by one.

In SRT you do exactly the same thing.

Whether ffmpeg has any special mode to do this with TCP, I don't know. But if they do, I think exactly the same model should be at least doable with SRT.

**Comment by matiaspl** [comment]
If you don't really need different ports you can use gstreamer for the purpose of "cloning" the srt stream. Their implementation supports multiple connections on the same port.
