### ISSUE TITLE
[BUG] Extra ACK is sent at the start of a connection (due to an uninitialized variable)

### ISSUE THREAD

**Issue by maxsharabayko** [Haivision/srt#2829]
After PR #2745 once a connection is established both sides (sender and receiver) without any reason send the first full ACK with the initial sequence number.

### To Reproduce

Start a Wireshark capture and run:

```shell
srt-xtransmit generate "srt://:4200" --enable-metrics -v --sendrate 5Mbps --duration 3s

srt-xtransmit receive "srt://127.0.0.1:4200" --enable-metrics -v
```

In the capture right after the handshake you will see those two useless ACKs.
![image](https://github.com/Haivision/srt/assets/12700120/89f527f3-b4cc-45a7-b725-9161d7e89165)

#### SRT Version Affected : v1.5.3.

**Comment by yomnes0** [comment]
See #2832
