### ISSUE TITLE
Comment clean up

### ISSUE THREAD

**Issue by StephaneStH** [Haivision/srt#283]
https://github.com/Haivision/srt/blob/fcb5c707e4450f070fc0262b8f8f731b41b8c39e/srtcore/srt_compat.c#L91

The implementation of strerror_r by GNU C library has nothing to do with the kernel (Linux or otherwise).
strerror_r just returns a ptr to it's own array of strings for standard errno codes and will use the supplied buffer only in cases where the error number is unknown/out of bounds.

**Comment by ethouris** [comment]
Actually it isn't kernel's caprice, but libc caprice - whatever, both may be returned, depending on the situation. This only explains why there's a buffer needed to be passed to the function, but still the resulting string should be taken from the returned value.
