### ISSUE TITLE
Build srt-1-fit failed, ret=1 [BUG]

### ISSUE THREAD

**Issue by prio158** [Haivision/srt#2835]
**Describe the bug**

sudo ./configure --osx --without-ssl --without-hls --without-hds --without-dvr --without-nginx --without-http-callback --without-http-server --without-stream-caster --without-http-api --without-ffmpeg --without-transcode --without-ingest --without-stat --without-librtmp

```
Build srt-1-fit
patching file ./objs/Platform-SRS5-Darwin-21.6.0-Clang14.0.0-arm64/srt-1-fit/srtcore/api.cpp
Hunk #1 succeeded at 1133 (offset 17 lines).
You must have OpenSSL installed from 'brew' tool. The standard Mac version is inappropriate.
    while executing
"error "You must have OpenSSL installed from 'brew' tool. The standard Mac version is inappropriate.""
    (procedure "postprocess" line 172)
    invoked from within
"postprocess"
    invoked from within
"if { [info proc postprocess] != "" } {
        postprocess
}"
    (file "./configure" line 254)
Build srt-1-fit failed, ret=1
```

**To Reproduce**
1. Configure '...'
2. Run '....'
3. See error

**Expected behavior**

**Screenshots**
![Uploading image.png…]()

**Desktop (please provide the following information):**
 - OS: macOS M1 Pro
 - SRT Version / commit ID: 5.0release

**Additional context**

**Comment by maxsharabayko** [comment]
The message says:
> You must have OpenSSL installed from 'brew' tool.

Please see the [Building on MacOS document](https://github.com/Haivision/srt/blob/master/docs/build/build-macOS.md).
