### ISSUE TITLE
strncpy does not guarantee NULL termination

### ISSUE THREAD

**Issue by StephaneStH** [Haivision/srt#284]
https://github.com/Haivision/srt/blob/fcb5c707e4450f070fc0262b8f8f731b41b8c39e/srtcore/srt_compat.c#L91

While strerror_r guarantees a NULL terminated string, the current use of strncpy here removes this protection.

**Comment by ethouris** [comment]
Right. The size of the buffer shall be decreased by 1.

**Comment by ethouris** [comment]
#285 added to fix this.
