### ISSUE TITLE
API: Check optlen for string OPTIONS (e.g. SRTO_STREAMID).

### ISSUE THREAD

**Issue by maxsharabayko** [Haivision/srt#2845]
## Bug Description

Negative option lengths are not checked in `srt_setsockopt()` calls, except for those having integer types.

A `memcpy` with the to unsigned converted negative value is being done then.

## To Reproduce

```c
srt_setsockopt(SRTO_STREAMID, ..., -1 /*optlen*/);
```

## Expected behavior

Report `SRT_EINVPARAM`.

## TODO

- [x] Handle invalid optlen values where not handled.
- [x] Add a unit test to validate the expected behavior.

**Comment by yomnes0** [comment]
PR #2849 should address this by returning SRT_EINVPARAM whenever optlen is set to -1

**Comment by ethouris** [comment]
Wait. What was the final decision then?

Note that there are already applications that RELY on that setting a string-typed option with passing -1 as length treats the string as a NUL-terminated array of characters.

**Comment by maxsharabayko** [comment]
The majority has voted for not using `optlen=-1` (7 votes against using, only 2 support).
The "feature" is only implemented for `SRTO_BINDTODEVICE` and not documented officially. Thus may be considered as a bug and safely fixed without breaking the API/ABI backward compatibility.

**Comment by ethouris** [comment]
Ah, in that case, it should be ok.

**Comment by jlsantiago0** [comment]
Perhaps using -1 or size can also help solve https://github.com/Haivision/srt/issues/2284

**Comment by maxsharabayko** [comment]
@jlsantiago0 
#2284 has been already fixed by #2804.

**Comment by maxsharabayko** [comment]
Fixed by #2849.
