### ISSUE TITLE
SRT transport video stream

### ISSUE THREAD

**Issue by liumanfang** [Haivision/srt#2850]
I want to transmit the real-time h264 encoded video stream data through srt, but I currently encounter a problem:
//Send data to SRT server
     if (self.srtSocket > 0) {
         int result = srt_send(self.srtSocket, [data bytes], (int)[data length]);
         if (result < 0) {
             NSLog(@"SRT send failed with error: %s", srt_getlasterror_str());
                 }
     }
Output: 2024-01-10 17:46:46.541453+0800 ARKitDemo[6478:2477342] SRT send failed with error: Operation not supported: Incorrect use of Message API (sendmsg/recvmsg)
What is the reason for this and how to solve it?

**Comment by ethouris** [comment]
In live mode the single call to `srt_send` (all sending functions actually) is limited to the size of `SRTO_PAYLOADSIZE`.

The value for this option in the default live mode is 1316. This is a value typically used for MPEG-TS.

I'm not sure what format you inteded to use for transmitting this, but I doubt that bare h264 format is a good idea.

Even if you think that you spare some space by not using the MPEG-TS format, I'd recommend you use at least the PES packets from MPEG-TS. It will allow you at least to define proper timestamps. Of course, you'll still have to split it yourself in smaller pieces that can fit in a single packet.

The value for `SRTO_PAYLOADSIZE` can be also increased, but only up to 1456 bytes (IPv4) or 1444 bytes (IPv6).

**Comment by liumanfang** [comment]
@ethouris
Thank you so much. This problem has been successfully solved. However, considering that the delay seems to be relatively large, will converting to mp4 format be more delay-friendly?

**Comment by ethouris** [comment]
I'm not sure where this delay can come from. SRT has a default latency of 120ms. The only delay in data delivery is then this latency plus time to send the UDP packet from the source to destination machine.

You can try to use the MPEG-TS format. I'm not sure about mp4.
