### ISSUE TITLE
[BUG] cmake compiler prefix doesn't seem to work well

### ISSUE THREAD

**Issue by rdp** [Haivision/srt#2854]
**To Reproduce**

```
srt$  cmake . -DCMAKE_SYSTEM_NAME=Windows -DWITH_COMPILER_PREFIX=x86_64-w64-mingw32-
-- The C compiler identification is GNU 11.4.0
-- The CXX compiler identification is GNU 11.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - broken
CMake Error at /usr/share/cmake-3.22/Modules/CMakeTestCCompiler.cmake:69 (message):
  The C compiler

    "/usr/bin/cc"

  is not able to compile a simple test program.
```

**Expected behavior**

To use x86_64-w64-mingw32-g++

Thanks :)

**Comment by ethouris** [comment]
We are using this WITH_COMPILER_PREFIX in one of our internal project where it changes the compiler after autodetection. So autodetection of a compiler must succeed, even if this compiler isn't going to be used.  If this isn't working, the only way is to use CMAKE_C_COMPILER and CMAKE_CXX_COMPILER, or environment variables CC and CXX.

**Comment by rdp** [comment]
CMAKE_C_COMPILER and CMAKE_CXX_COMPILER do work, thanks.
