### ISSUE TITLE
[FR] ability to use static library within shared library

### ISSUE THREAD

**Issue by rdp** [Haivision/srt#2856]
**Is your feature request related to a problem? Please describe.**

When I cmake srt (as linux library) with  -DENABLE_SHARED=0 
then use that library with another library that is "creating its own shared" library:

I get this:

```
/usr/bin/ld: /home/rdp/new/sandbox/linux_shared/build_files/lib/libsrt.a(core.cpp.o): warning: relocation against _ZTIi@@CXXABI_1.3' in read-only section .text.unlikely'
/usr/bin/ld: /home/rdp/new/sandbox/linux_shared/build_files/lib/libsrt.a(srt_c_api.cpp.o): relocation R_X86_64_PC32 against symbol `_ZTTSt13basic_fstreamIcSt11char_traitsIcEE@@GLIBCXX_3.4' can not be used when making a shared object; recompile with -fPIC
```
or
```
/usr/bin/ld: /home/rdp/new/sandbox/linux_shared/build_files/lib/libsrt.a(api.cpp.o): warning: relocation against `in6addr_any@@GLIBC_2.2.5' in read-only section `.text._ZNK3srt12sockaddr_any5isanyEv[_ZNK3srt12sockaddr_any5isanyEv]'
/usr/bin/ld: /home/rdp/new/sandbox/linux_shared/build_files/lib/libsrt.a(api.cpp.o): relocation R_X86_64_PC32 against symbol `in6addr_any@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
```
**Describe the solution you'd like**

Would like cmake to have a fPIC option.

Related: this is me using srt within ffmpeg configured with --enable-shared --disable-static.

Work around: add -DCMAKE_CXX_FLAGS="-fPIC"
Maybe OK for now.

Thank you! :)

**Comment by rdp** [comment]
Looks like this flag works too: `-DCMAKE_POSITION_INDEPENDENT_CODE=ON` so in a way there's already an option for it.  Maybe it's not worth noting, or maybe worth noting as a build option, this is a fairly obscure case of compiling a static library into a "shared" library in the end...

**Comment by maxsharabayko** [comment]
@rdp The `CMAKE_POSITION_INDEPENDENT_CODE` is a cmake option, no SRT option. Not sure if it should go to the build-options.md. Only if a separate section like FAQ in the end, describing this situation with FFmpeg. Or this issue would be a guide.

**Comment by rdp** [comment]
I'm OK with this issue being enough since it's pretty edgey, or feel free to note it elsewhere too, thanks!
