### ISSUE TITLE
One listener Multi-caller

### ISSUE THREAD

**Issue by eurekao** [Haivision/srt#2864]
set obs like srt://127.0.0.1:10080?mode=listener&timeout=5000000 to push stream
run 2 VLC read stream like srt://127.0.0.1:10080?mode=caller
just the first vlc can show the stream, the second connect error
what i can do?

**Comment by ethouris** [comment]
SRT offers a solution of a listener, which works merely like the `listen` and `accept` function for TCP. But it's the application's choice how it makes use of it.

Many simply accept one connection and then don't accept anything at all until this one connection is broken. Others accept multiple connections, but then the application's code must be prepared to manage multiple receivers and distribute the stream throughout them. If OBS rejects the second connection then it likely doesn't do it. You should check this with OBS if it offers something like this. From the perspective of SRT there's no problem with having that (at least potentially).

**Comment by matiaspl** [comment]
FFmpeg's implementation of SRT listener is single connection. You need to play with obs-gstreamer to get multiple connections or use e.g. srt-live-transmit as a proxy.

**Comment by ethouris** [comment]
Actually not; `srt-live-transmit` in listener mode also accepts only a single connection. After a successful accept it closes the listener socket, then recreates it when the connection breaks.

**Comment by matiaspl** [comment]
my bad, I was under the impression that one of the console tools other than gstreamer did support that...

**Comment by eurekao** [comment]
@matiaspl thx, i see libsrt.c in ffmpeg 
```c++
    if (s->mode == SRT_MODE_LISTENER) {
        // multi-client
        ret = libsrt_listen(write_eid, fd, cur_ai->ai_addr, cur_ai->ai_addrlen, h, s->listen_timeout);
        srt_epoll_release(write_eid);
        if (ret < 0)
            goto fail1;
        srt_close(fd);
        fd = ret;
    } 
```
srt will close  after accept one client, is there any ready to use solution?

**Comment by maxsharabayko** [comment]
The `srt-xtransmit` app has a PR adding multiple client connections to the `receive` and `generate` subcommand. Those is used for testing. You probably need to add this feature to the `route` subcommand as well.
https://github.com/maxsharabayko/srt-xtransmit/pull/37

**Comment by ethouris** [comment]
@eurekao I really think you should rather try to talk with OBS guys whether they would like to have something like that.

You can use `srt-xtransmit` to try out if this works, but note that this is a tool that we are using for testing, not something you can use in production.
