### ISSUE TITLE
srt-file-transmit connection issue (listener)

### ISSUE THREAD

**Issue by apellat** [Haivision/srt#287]
Hello,

When using srt-file-transmit in listener mode we get the following error:
```
bash-4.4# srt-file-transmit srt://:8080/ file:///tmp/RECEIVE

ERROR #6002: Non-blocking call failure: no data available for reading.
ERROR: error: srt_accept: Non-blocking call failure: no data available for reading.
bash-4.4#
```

last commit I used (and was working) was 9e8c640aad65c420d712cde259b3fc94a0ff2770

regards,

Alexandre

**Comment by metairie** [comment]
I precise that I have the dev version, with a specific commit  ("stransmit new stats( #264)") 1 feb :

> git reset --hard 9e8c640aad65c420d712cde259b3fc94a0ff2770

**Comment by nitrat7** [comment]
same issue here 84d5e5ea7c59c667dd64008bc2ef9e5783c6f00f

**Comment by nitrat7** [comment]
issue still existent in master branch 1.3 👎 

Listener:
ubuntu@ip-172-31-29-161:~$ srt-file-transmit  srt://:5002 file:///home/ubuntu/ 
Source connected (listener), id [1Gigfile]
Writing output to [/home/ubuntu//1Gigfile]
Download: SRT error: Non-blocking call failure: no data available for reading.


Caller:
ubuntu@ip-172-31-47-227:~$ srt-file-transmit  file:///home/ubuntu/1Gigfile srt://ec2-52-90-58-218.compute-1.amazonaws.com:5002
Target connected (caller)
Target disconnected


**Only if I turn on verbose logging transmission might work out ...**
Caller:
srt-file-transmit -v file:///home/ubuntu/1Gigfile srt://ec2-52-90-58-218.compute-1.amazonaws.com:5002 > caller.log 2>&1
Receiver:
srt-file-transmit -v srt://:5002 file:///home/ubuntu/ > listener.log  2>&1


Double-Checked and not existent at least at dev-branch 9e8c640aad65c420d712cde259b3fc94a0ff2770

**Comment by rndi** [comment]
Hello @nitrat7 ,

Just did a quick test with a 1G file here and it works ok with 1.3, without verbose logging . There seems to be an interrupt issue if sender is started before the listener and sender needs to be restarted but is not the same problem you are having (I will look into that anyway). I will try to do more tests in different topologies tomorrow. Any other hints you can provide? Is the error immediate upon connection or some time into the transfer? What is the file size (if any) on the receiving side?

**Comment by nitrat7** [comment]
hello @rndi 
thanks for fast reply. 
Issue happens immediately. File size is 1GByte. Issue does not happen, if verbose logging is activated (as if this slows down operation). 
It's a fast connection between two instances of EC2 in AWS in Germany <-> US .
I might share public key for interim testing (SSHing), but surely not here ;-)

**Comment by maxlovic** [comment]
@nitrat7 Is there still a problem with `srt-file-transmit` in v1.3.3?

**Comment by mbakholdina** [comment]
Closed due to inactivity. The problem is no reproducible anymore.
