### ISSUE TITLE
[BUG] Sequence number in the ACK packet isn’t correct

### ISSUE THREAD

**Issue by kura979** [Haivision/srt#2873]
**Describe the bug**
I’m currently using SRT 1.5.2 to distribute MPEG TS streams. Recently, I stumbled upon a rare issue where the sequence number (SN) in the ACK packet isn’t correct. This messes up retransmissions and causes data packets to get dropped.

Here’s a snapshot from tcpdump to illustrate:
![tcpdump](https://github.com/Haivision/srt/assets/86100095/d7447a24-673e-4c7c-9352-3285a8a05fa2)
`
[Black] NAK packet of lost SN:1102276611
`
`
[Yellow] ACK packet of larger SN:1102276613
`

Ideally, **the ACK packet should have an SN of 1102276611** . This causes retransmissions from the sender to be canceled, resulting in a drop.
Turns out, in such cases, the first SN stored in `srt::CUDT::m_pRcvLossList` is used for the ACK packet, according to srtcore/core.cpp:
```
int srt::CUDT::sendCtrlAck(CPacket& ctrlpkt, int size)
{

     ...omitted...

     {
         // If there is no loss, the ACK is the current largest sequence number plus 1;
         // Otherwise it is the smallest sequence number in the receiver loss list.
         ScopedLock lock(m_RcvLossLock);
         // TODO: Consider the Fresh Loss list as well!!!
        ack = m_pRcvLossList->getFirstLostSeq();
     }

    // We don't need to check the length prematurely,
    // if length is 0, this will return SRT_SEQNO_NONE.
    // If so happened, simply use the latest received pkt + 1.
    if (ack == SRT_SEQNO_NONE)
    {
        ack = CSeqNo::incseq(m_iRcvCurrSeqNo);
        IF_HEAVY_LOGGING(reason = "expected next");
    }
```
As a result of investigation, I realized that `m_pRcvLossList` was not updated and the list remained empty because the following condition of `CSeqNo::seqcmp(seqno1, m_iLargestSeq) <= 0` was met, as mentioned in srtcore/list.cpp:
```
void srt::CRcvLossList::insert(int32_t seqno1, int32_t seqno2)
{
     // Data to be inserted must be larger than all those in the list
     if (m_iLargestSeq != SRT_SEQNO_NONE && CSeqNo::seqcmp(seqno1, m_iLargestSeq) <= 0)
     {
         if (CSeqNo::seqcmp(seqno2, m_iLargestSeq) > 0)
         {
             LOGC(qrlog.Warn,
                  log << "RCV-LOSS/insert: seqno1=" << seqno1 << " too small, adjust to "
                      << CSeqNo::incseq(m_iLargestSeq));
             seqno1 = CSeqNo::incseq(m_iLargestSeq);
         }
         else
         {
             LOGC(qrlog.Warn,
                  log << "RCV-LOSS/insert: (" << seqno1 << "," << seqno2
                      << ") to be inserted is too small: m_iLargestSeq=" << m_iLargestSeq << ", m_iLength=" << m_iLength
                      << ", m_iHead=" << m_iHead << ", m_iTail=" << m_iTail << " -- REJECTING");
             return;
         }
     }
     m_iLargestSeq = seqno2;
```
As a result, `m_pRcvLossList->getFirstLostSeq()` returns SRT_SEQNO_NONE, so the current larger `m_iRcvCurrSeqNo` **1102276613** is used.

**To Reproduce**
Further investigation revealed the conditions under which this issue arises. The **SN1** from a previous packet loss event is stored in `m_iLargestSeq`. A next generated packet loss **SN2** will occur under the following conditions.
`
m_iSeqNoTH < The distance from S1 to S2  <= m_iMaxSeqNo
`
In other words, the distance from S1 to S2 is the second half of the SN cycle.

This occurs under the following circumstances. This is super rare and unlikely to happen in a normal environment.

- The data packet transfer rate is very high, and SN cycle over a several days.
- It is a very stable network with no packet loss occurring for few days.

**Possible Solution**
To fix this, I suggest adding two lines of code to initialize `m_iLargestSeq` when the list is empty, in two places before the return statement of the `CRcvLossList::remove()` function.

```
bool srt::CRcvLossList::remove(int32_t seqno)
{

     ...omitted...

         m_iLength--;
>        if (m_iLength == 0)
>          m_iLargestSeq = SRT_SEQNO_NONE;
         return true;
     }

     ...omitted...

     m_iLength--;
>    if (m_iLength == 0)
>      m_iLargestSeq = SRT_SEQNO_NONE;
     return true;
}
```

**Comment by maxsharabayko** [comment]
@mediagram-kurata Thank you for such an in-depth investigation!

The `m_iLargestSeq` was introduced in PR #2195. Hence affected SRT versions are v1.5.0, 1.5.1, 1.5.2 and 1.5.3.

Your proposed solution looks correct. Would you please submit a PR?
[Developer's Guide - Submitting a Pull Request](https://github.com/Haivision/srt/blob/master/docs/dev/developers-guide.md#submitting-a-pull-request)

**Comment by kura979** [comment]
> Your proposed solution looks correct. Would you please submit a PR?
Yes, I made a pull request.
https://github.com/Haivision/srt/pull/2877

**Comment by maxsharabayko** [comment]
Thank you, @kura979 

The further improvement would be the one contained in the PR #2527.
> (...) the ACK number to be sent back to the sender is extracted exclusively from the receiver buffer, and no longer from the loss list and internal fields. This is because the receiver buffer was added a functionality to be able to check this thing quickly. This is also a more reliable source of information and not prone to any race conditions.
