### ISSUE TITLE
srt-file-transmit caller exit before the listener has the whole file

### ISSUE THREAD

**Issue by metairie** [Haivision/srt#289]
hi
when I send a big file (for instance >300MB)

> srt-file-transmit -v -loglevel=debug file:///tmp/QUEUE/bigfile.mp4 srt://10.69.0.1:8080/

the file is correctly sent :

> Sending buffer still: bytes=11886329 blocks=8164
> Sending buffer still: bytes=2748473 blocks=1888
> Sending buffer DEPLETED - ok.
> SrtCommon: DESTROYING CONNECTION, closing sockets (rt%576887260 ls%-1)...
> SrtCommon: ... done.

the caller has finished and exit, the listener/receiver continues 10s or more second to receive packets. The file is ok, no problem, but ... if another call occurred during this period of time it fails.

Is it possible to have caller which exit only when listener save the entire file ?

**Comment by metairie** [comment]
I precise that I have the dev version, with a specific commit ("stransmit new stats( #264)") 1 feb :

> git reset --hard 9e8c640

**Comment by ethouris** [comment]
Please describe the procedure more precisely. The srt-file-transmit tool wasn't actually predicted to do any more job than just send one file completely (the listener mode isn't predicted to be a file server). Is it failing only when another call is made at this "cooldown time" or at any time of transmission?

It sounds strange what you say about "receiving packets" - the messages you can see about "buffer still" inform that there are still some parts of the file that are scheduled for sending, but not pushed through the network pipe yet. When the buffer is depleted, it means that there's nothing more to be send. When the connection is closed, this should be also accompanied with sending appropriate message to the listener to close the connection, so the listener should exit immediately upon reception of it.

Tell me how big this file is and more-less how distant are the sites through which you are trying to transfer, I'll try to reproduce it myself.

**Comment by metairie** [comment]
The file are sent to the same enterprise network , so distance is very small. File is ~1GB to ~3GB

What I mean is, caller has finished to send. Listener continues to receive packet during a random period of seconds , until 10 - 15 seconds as I could experiment

Of course we can live with that and catch the error , and retry later ;)

**Comment by maxsharabayko** [comment]
Looks duplicated to #1234. Should be fixed by #1236.
Do not hesitate to reopen if the problem persists.
