### ISSUE TITLE
[FR]: Support for merging MPEGTS multiple PMTs into one PMT.

### ISSUE THREAD

**Issue by Brainiarc7** [Haivision/srt#2901]
**Is your feature request related to a problem? Please describe.**
Yes. Using `srt-live-transmit` application produces an MPEGTS stream with multiple PMTs by default. This is not desirable in workflows where downstream packaging madates single PMTs to be present, e.g Shaka-packager. 

**Describe the solution you'd like**
Provide a method to merge all PMTs into one. FFmpeg [has a similar workaround](https://trac.ffmpeg.org/ticket/2261) to this in their mpegts demuxer, toggled on via `-scan_all_pmts 1 -merge_pmt_versions`. 

**Describe alternatives you've considered**
Using FFmpeg as an alternative in SRT bridges when a single PMT in the output is required. However, this is NOT an ideal solution in the long term.

**Additional context**
As described above.

**Comment by ethouris** [comment]
This is out of scope for SRT. Although SRT has been primarily created for transmitting MPEG-TS, it is still content-agnostic transport layer only.

The work you would like to be done relies on trans-muxing, which uses format-specific parsing and formatting. This is what ffmpeg or gstreamer can do for you. SRT is a transport layer only.
