### ISSUE TITLE
Having massive grey artefacts with SRT livestreams / any tuning possible?

### ISSUE THREAD

**Issue by glowfishDE** [Haivision/srt#2916]
Hi,

i´m using the latest SRT build from Haivision but i get massive grey artefacts when my bandwith goes below 3-4 mbit/sec.

I remember before (2 years ago) it was possible to have bitrates around 800 kbit/sec without problems.

So i really wonder: What might be causing this and is it possible to tweak/fine tune the SRT protocol when compiling it with some additional parameters?

When watching other IRL streamers i see they dont have any artefacts at all. Their images just pause or become blurry instead of showing such horrible grey frames.

Can someone please help me ?

Thanks alot
Glowi
![9b168452-b4b4-4237-91f6-6c5feea936e7](https://github.com/Haivision/srt/assets/44566242/5b4a9b01-2411-444b-98e1-aee3cbf2892f)

**Comment by maxsharabayko** [comment]
Try increasing SRT latency. Take a look at SRT stats to diagnose possibilities for tuning/tweaking.

**Comment by maxsharabayko** [comment]
Closing due to the lack of activity.
