### ISSUE TITLE
SRT streamer set as listener crashes when the caller disconnects

### ISSUE THREAD

**Issue by barixdev** [Haivision/srt#2943]
**Describe the bug**
When we run FFMPEG as SRT streamer set in listener mode, it crashes when the caller disconnects.

FFMPEG is compiled with libsrt version 84b5bb8c2bfd331ac55aba70fe09e5d3cbb00dee

**To Reproduce**

Run the SRT "pusher"/server on embedded ARM device:
ffmpeg -f alsa -i plug:linein_stereo -c:a libfdk_aac -profile:a aac_he -b:a 128k -f mpegts srt://:20002?mode=listener

Run the player on a PC (Mac PC with libsrt compiled)

./srt-ffplay srt://192.168.1.191:20002?mode=caller

When the caller is disconnected, the running SRT streamer crashes with this error

Output #0, mpegts, to 'srt://:20002?mode=listener':
  Metadata:
    encoder         : Lavf58.29.100
    Stream #0:0: Audio: aac (libfdk_aac) (HE-AAC), 48000 Hz, stereo, s16, 128 kb/s
    Metadata:
      encoder         : Lavc58.54.100 libfdk_aac
[alsa @ 0x188830] ALSA buffer xrun.
12:24:47.249695/ffmpeg*E:SRT.ea: remove_usock: @418015475 not found as either socket or group. Removing only from epoll system.
[srt @ 0x1a2d50] Operation not supported: Invalid socket ID
av_interleaved_write_frame(): Unknown error occurred
Error writing trailer of srt://:20002?mode=listener: Unknown error occurred
size=     296kB time=00:01:25.72 bitrate=  28.3kbits/s speed=4.85x    
video:0kB audio:267kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 10.917702%
Conversion failed!

We have tried with different timeout and buffer options, but none of them did help. 

**Expected behavior**
I would expect that the server continues listening to that port, and start streaming the next time the caller connects. Instead, seems like it is closing the listening socket on disconnect, and then tries to reuse it.

**Comment by barixdev** [comment]
I did find a temporary workaround this issue. It works if I pipe the FFMPEG to live transmit via a local UDP socket like suggested in the srt-live-transmit help:

One process:

ffmpeg -f alsa -i plug:linein_stereo -c:a libfdk_aac -profile:a aac_he -b:a 128k -f mpegts udp://127.0.0.1:5000?pkt_size=1316


And then in another one:

srt-live-transmit udp://:5000 srt://:20002?mode=listener

Like this disconnecting the caller does not cause issues with the streamer

**Comment by ethouris** [comment]
If that workaround works, it's hard to say where the problem really is and whether in SRT. The `srt-live-transmit` works more-less the same way by just hosting the listener and it also uses non-blocking mode, just like ffmpeg.

You can also do it simpler - instead of using UDP as output for fmpeg, use pipe:1 and then pipe it to the `srt-live-transmit` using `file://con` as a source (this designates stdin, if used as input and stdout if used as output).

**Comment by ethouris** [comment]
Ah, one more thing. Might be that it's not a "crash", but not exactly the right way of handling the broken connection by ffmpeg. If you can get the call stack at the crash, it would be helpful - at least to rule out some possibilities.

**Comment by barixdev** [comment]
> Ah, one more thing. Might be that it's not a "crash", but not exactly the right way of handling the broken connection by ffmpeg. If you can get the call stack at the crash, it would be helpful - at least to rule out some possibilities.

How can I do that? FFMPEG is run on embedded device without any debugging tools

**Comment by ethouris** [comment]
The least you can do is to allow a coredump on that device (at least temporarily). As long as the crash would normally end up with a coredump.

**Comment by maxsharabayko** [comment]
Is it a crash or just an error reported in the terminal?

**Comment by barixdev** [comment]
It is a crash-ffmpeg exits when it happens and the process has to be restarted

**Comment by maxsharabayko** [comment]
There is just no reconnection feature in FFmpeg, [at least for SRT](https://github.com/FFmpeg/FFmpeg/blob/master/libavformat/libsrt.c). It would make more sense to submit a feature request to FFmpeg. It is the responsibility of the application to handle broken connections.
