### ISSUE TITLE
Loss-based NAK vs Periodic NAK

### ISSUE THREAD

**Issue by oviano** [Haivision/srt#2960]
From reading the SRT draft spec my understanding is that SRT will send a NAK in two circumstances:

1. when it detects a gap in the received packet sequence numbers (sends a NAK for each "missing" packet)
2. periodically according to RTT and RTTvar etc (sends a NAK containing the loss list)

I'm curious as to how much thought/investigation was done using just 2. alone, as I would have thought that it was pretty common for UDP packets to be delivered out of order and that this shouldn't necessarily generate a NAK and thus an immediate resend which could add a fair bit of overhead for no reason, especially as the periodic NAK will take care of it within a minimum of 20ms in any case.

**Comment by oviano** [comment]
Thanks - and that's off by default, is that because there are some issues with it, or the default is just preferred to be more aggressive about re-sending?

**Comment by maxsharabayko** [comment]
Just most of the time there is not much reordering observed in most networks used for live streaming.
Even in mobile networks [[SRT over 4G]](https://medium.com/innovation-labs-blog/examining-srt-streaming-over-4g-networks-925e71c45cdf).
Earlier detection of a lost packet improves min latency and packet recovery.

**Comment by oviano** [comment]
Yes, that makes sense, thank you.
