### ISSUE TITLE
Fix SockaddrToString to display IP address

### ISSUE THREAD

**Issue by ethouris** [Haivision/srt#298]
The SockaddrToString function used also in log messages should display the address contained in the sockaddr structure. It tries to display the reverse-name address, however if the reverse-resolving is not possible, it displays "unknown". It should display the 4-dot formatted IP address in this case.

**Comment by fboucher67** [comment]
The SockaddrToString function sometimes takes more than 1 second to return because of getnameinfo().  This causes connection to fail.  Insert a 1 second sleep in SockaddrToString to reproduce.

**Comment by rndi** [comment]
@fboucher67, I agree. I think this part needs to be surrounded by some sort of optional compilation flag and probably disabled by default:
```
    if (!getnameinfo(sadr, sizeof(*sadr), hostbuf, 1024, NULL, 0, NI_NAMEREQD))
    {
        output << hostbuf;
    }
    else
```
Would you like to open a PR for review?

**Comment by ethouris** [comment]
I didn't pay much attention on it because this function should be called *exclusively* inside `HLOGC` macro, which is expanded only when `ENABLE_HEAVY_LOGGING`.

When there's any case that this function is called in any other circumstances, it should be fixed. Although might be that it would be a good idea to make it a conditional flag to resolve it as a name, or just print in the dot-notation numeric format only.

**Comment by ethouris** [comment]
In #312, now by default the name is displayed as numeric. To have names displayed with rev-dns, you need `--enable-getnameinfo` option.

Please note that the `getnameinfo` function itself is used in `CUDT::bake` call, which creates the cookie, although I understand that with NUMERICHOST and NUMERICSERV options it won't do any rev-dns and will simply turn given sockaddr into a numeric string representation.
