### ISSUE TITLE
Recommended fec configuration?

### ISSUE THREAD

**Issue by mycrl** [Haivision/srt#2987]
First of all is there any recommended fec configuration?

Then I recently encountered a problem. SRT would disconnect after about 3 hours, almost always about 3 hours. What is the reason? My network is a local area network, with little packet loss and a good network environment. Is there a problem with SRT Windows support? I am using the master branch.

**Comment by ethouris** [comment]
Well, there's no recommended configuration for FEC, it depends on characteristics of the network link that you use, and how much of the potential overhead capacity you have and how often the current capacity drops below your sending rate.

That interrupt after 3 hours is something not known to us. There are many factors that could cause this, and to determine what it could be, the best approach would be to turn on debug logs, likely also with limited functional areas to network related one only. This can be just as well some setting in the local network that limits the use of a UDP link, but an emergency connection break in SRT is also potentially possible. That would be also visible in the logs, should that be the case.

**Comment by mycrl** [comment]
> Well, there's no recommended configuration for FEC, it depends on characteristics of the network link that you use, and how much of the potential overhead capacity you have and how often the current capacity drops below your sending rate.
> 
> That interrupt after 3 hours is something not known to us. There are many factors that could cause this, and to determine what it could be, the best approach would be to turn on debug logs, likely also with limited functional areas to network related one only. This can be just as well some setting in the local network that limits the use of a UDP link, but an emergency connection break in SRT is also potentially possible. That would be also visible in the logs, should that be the case.

OK, thanks!
