### ISSUE TITLE
Fix an incorrect setting of ENABLE_DEBUG on back-synch from CMAKE_BUILD_TYPE

### ISSUE THREAD

**Issue by ethouris** [Haivision/srt#304]
Since introduction of ENABLE_DEBUG=2, this should be no longer ON and OFF. It's set to ON or OFF if undefined, which may later fail the test for being equal to 1 or 2.

**Comment by NickDrouin** [comment]
In CMakeLists.txt, in the case where ENABLE_DEBUG is not defined, it defaults to OFF, which is neither 1 nor 2, thereby setting CMAKE_BUILD_TYPE to Release regardless of it's previous value.  Your initial bug description seems to speak to this issue, but seems to have been closed without a commit to fix it.

As written ENABLE_DEBUG has logic for both ON/OFF and 1/2/Other.

**Comment by ethouris** [comment]
Well, yes, this is wrong. The idea is that `ENABLE_DEBUG` may accept values of 0, 1 or 2. With 0 it's Release, with 2 it's RelWithDebInfo, with 1 it's Debug. Maybe the ON/OFF can be translated into 1 and 0 respectively, but the value should be enforced as 0, 1, 2 only.

**Comment by maxlovic** [comment]
Fixed by #664
