### ISSUE TITLE
Is there any way to detect that the incoming connection is rejected by passphrase conflict?

### ISSUE THREAD

**Issue by kobayashi750** [Haivision/srt#3058]
Is there any way to detect that the incoming connection is rejected by passphrase conflict, at listener side with non-blocking mode? Although the connect rejection message is printed on a terminal at listener side, I can't find the way to detect it with API.

**Comment by jeandube** [comment]
@kobayashi750  None that I know, see [FR 2847](https://github.com/Haivision/srt/issues/2847)

**Comment by kobayashi750** [comment]
I checked FR 2847. Thank you for answer.
