### ISSUE TITLE
srt_listen_callback() fails with SRT 1.5.4-RC.0

### ISSUE THREAD

**Issue by lelegard** [Haivision/srt#3062]
Hi,

On Fedora 41, they decided to include SRT 1.5.4-RC.0 as a standard package. The installed packages, after a standard upgrade from Fedora 40 to Fedora 41 are the following:
~~~
srt-libs-1.5.4-0.rc0.fc41.aarch64
srt-devel-1.5.4-0.rc0.fc41.aarch64
~~~

Whether or not it is a good idea to include a RC version in an official release is a good question. But my point is elsewhere.

I have a problem with that 1.5.4-RC.0 which did not exist before and I would like your opinion on it, to decide whether it is a problem with my code (TSDuck project) or with that RC release of SRT.

As part of the automatic test suite of TSDuck, a [test involving SRT](https://github.com/tsduck/tsduck-test/blob/master/tests/test-130.sh) fails on Fedora 41 while it works on all other platforms (with SRT 1.5.3 so far) and with Fedora 40 (presumably with SRT 1.5.3 also).

The error in the test log is the following:
~~~
* Error: srt: error during srt_listen_callback(): Operation not supported: Cannot do this operation on a CONNECTED socket
~~~

The sequence is the following:
~~~
if (srt_bind(sock, &sock_addr, sizeof(sock_addr)) < 0) {
    report.error(u"error during srt_bind(): %s", srt_getlasterror_str());
    return false;
}

if (srt_listen(sock, backlog) < 0) {
    report.error(u"error during srt_listen(): %s", srt_getlasterror_str());
    return false;
}

// Install a listen callback which will reject all subsequent connections after the first one.
if (srt_listen_callback(sock, listenCallback, this) < 0) {    <=========== here
    report.error(u"error during srt_listen_callback(): %s", srt_getlasterror_str());
    return false;
}

const int data_sock = srt_accept(sock, &peer_addr, &peer_addr_len);
if (data_sock == SRT_INVALID_SOCK) {
    report.error(u"error during srt_accept(): %s", srt_getlasterror_str());
    return false;
}
~~~

It is possible that the client tried to connect between `srt_listen` and `srt_listen_callback` but `srt_accept` was not yet called.

Is it an expected behaviour? What would be the right way to use `srt_listen_callback`?

In this scenario, the SRT input and output plugins for TSDuck use a one-to-one connection. Therefore, on the listener side, we accept only one incoming client. As the comment suggests, the listen callback is used here to reject all connections after the first one (it calls `srt_setrejectreason` with `SRT_REJX_OVERLOAD` and returns -1).

Thank you for your help.

EDIT: there is no connection attempt. The command immediately fails when interactively run in a simplified form:
~~~
$ tsp -b 1,000,000 -I null -P regulate -O srt --listener 127.0.0.1:2222 --transtype live
* Error: srt: error during srt_listen_callback(): Operation not supported: Cannot do this operation on a CONNECTED socket
~~~

**Comment by ethouris** [comment]
The listener callback cannot be altered since you have set up the listener. Set up the callback first, and then call `srt_listen`.

**Comment by maxsharabayko** [comment]
PR #2683 changes conditions for settings callbacks. Now this operation is only allowed before a connection procedure is started for a socket (listen on a listener socket, call on a caller socket). This change is done to improve thread safety.

@lelegard Would that be a blocker for you to upgrade to v1.5.4?

**Comment by lelegard** [comment]
> The listener callback cannot be altered since you have set up the listener. Set up the callback first, and then call srt_listen.

Thanks @ethouris, I will try. I just broke my Fedora 41 and I have to rebuild it. Your suggestion works with 1.5.3 anyway. I will try with 1.5.4 after solving my system issues.

> @lelegard Would that be a blocker for you to upgrade to v1.5.4?

@maxsharabayko, not at all, I will update my code, nothing more.

Just a few remarks: 

- It could be worth documenting the required order of calls [here](https://github.com/hwangsaeul/libsrt/blob/master/docs/API-functions.md#srt_listen_callback).
- The error message is misleading: "Cannot do this operation on a CONNECTED socket". The socket is not in a connected state because no client is connected. This made me think that the error was wrong. If the message mentioned "LISTEN state", I would have tried to swap the calls before creating an issue.
- Since it worked differently up to 1.5.3, you may get other similar reports...

**Comment by lelegard** [comment]
@ethouris, @maxsharabayko, I have fixed my Fedora 41 VM and I can confirm that swapping the two calls work with 1.5.4 ([link to code here](https://github.com/tsduck/tsduck/blob/629251477d69eb7f9afb59911a8020c252d395df/src/libtsduck/base/network/tsSRTSocket.cpp#L920)).

I close this issue as resolved.

Thanks for your help.
