### ISSUE TITLE
[BUG] srt_bind() fails for ipv6 addr any on MacOS and Windows when TOS is also set

### ISSUE THREAD

**Issue by jlsantiago0** [Haivision/srt#3095]
Unsure, but the logic at srtcore/channel.cpp line 445 does not match the comment. It seems like the condition should be if the comment is correct:

```
if (IN6_IS_ADDR_UNSPECIFIED(&m_BindAddr.sin6.sin6_addr) && IN6_IS_ADDR_V4MAPPED(&m_BindAddr.sin6.sin6_addr))
```
Instead of:

```
if (IN6_IS_ADDR_UNSPECIFIED(&m_BindAddr.sin6.sin6_addr) || IN6_IS_ADDR_V4MAPPED(&m_BindAddr.sin6.sin6_addr))
```

Or perhaps the code should not throw in case the setsockopt() fails?

We have tested by commenting out the throw in the case of failure and srt_bind() works as expected.

**Comment by ethouris** [comment]
@jlsantiago0 Please try out the branch of the #3096 PR and see if this behaves as expected.

**Comment by jlsantiago0** [comment]
>>Can you describe the exact case where you have a situation that result in an unexpected error?

On Linux if we have TTL or TOS values set and call srt_bind() with ipv6 addr any, it succeeds. But does not on MacOS and Windows. Perhaps the behavior should be the same on both platforms?

**Comment by ethouris** [comment]
In API-socket-options.md the SRTO_IPTOS and SRTO_IPTTL options are described with "pre-bind" restriction.

**Comment by jlsantiago0** [comment]
> In API-socket-options.md the SRTO_IPTOS and SRTO_IPTTL options are described with "pre-bind" restriction.

OK. My mistake. You can close this ticket.

**Comment by ethouris** [comment]
Still, you have pointed out some unclear code, so a PR is scheduled to fix that. This will drag this ticket with itself.
