### ISSUE TITLE
missing UDP packets through SRT

### ISSUE THREAD

**Issue by ricaonline** [Haivision/srt#321]
we use a Windows PC installed SRT with two eth ports, eth1 is connected to the source PC1, and eth2 is connected to the destination PC2.
on the PC with SRT
stransmit udp://PC1:2222 srt://PC2:1234?mode=caller
on the PC2
stransmit srt://PC2:1234?mode=listener udp://127.0.0.1:5555

on the PC with SRT, using wireshark to capture UDP packets on eth1 and eth2, it shows the number of UDP packets on eth1 is larger than eth2, it seems the SRT lossing some UDP packets.

**Comment by ethouris** [comment]
There are several reasons why SRT may lose packets - one of them is that by default it's using 125ms latency and TLPKTDROP is turned on, which means that the packet is recovered only until the next packet passed the latency time and is ready to play, in this case the lost previous packet is never recovered.

To make sure where exactly your packets are being lost, you should grab the pcap not only for these UDP media, but also for UDP media used for SRT transfer. We don't have a plugin for SRT dissector for Wireshark yet, but you can try to use UDT dissector, at least to see sequence numbers in data packets.

**Comment by 1div0** [comment]
Few weeks ago I have started to work on https://gitlab.websupport.sk/nct/srt/dissector

**Comment by ricaonline** [comment]
I have tried UDP dissector in Wireshark, it shows the sequence number is continuous without missing any number, but the data content is missing. As attachment, we have two dummy data flow, one is filled with all 00 and increased in 6th byte by 1, the other is filled with 01, all.pcapng is from eth1, and missing.pcapng is from eth2, for example, the seqno 903829307 and 903829308, data content 0030 is missing.

________________________________
ricaonline@hotmail.com

**Comment by ricaonline** [comment]
I have tried UDP dissector in Wireshark, it shows the sequence number is continuous without missing any number, but the data content is missing. As attachment, we have two dummy data flow, one is filled with all 00 and increased in 6th byte by 1, the other is filled with 01, all.pcapng is from eth1, and missing.pcapng is from eth2, for example, between the seqno 903829307 and 903829308, data content 0030 is missing.
[SRT.zip](https://github.com/Haivision/srt/files/1858438/SRT.zip)

**Comment by ethouris** [comment]
(I believe you were using UDT, not UDP dissector :)
If you don't have any missed sequence numbers in SRT, it means that the content sent by SRT is exactly the content that has been passed to it in subsequent calls of `srt_sendmsg` function. In other words, if you can't see holes in sequence numbers, it means that it's not SRT responsible for the loss of data.

**Comment by maxlovic** [comment]
Hi @ricaonline,
Can you provide the sources for the testing application you use?

In `missing.pcapng` I see that one data content is missing. And it looks like it was lost not in the network, but at the moment of passing it inside the SRT library. Do you check the return of `srt_send` function? What SRT configuration do you use?
What is the purpose of the `all.pcapng` file? What can we see there?

**Comment by mazz** [comment]
> Few weeks ago I have started to work on https://gitlab.websupport.sk/nct/srt/dissector

The gitlab repo appears to be empty.
