### ISSUE TITLE
Is possible to compile a x86 version of stransmit for windows XP?

### ISSUE THREAD

**Issue by manueldev** [Haivision/srt#322]
I made some modifications to the appveyor.yml file and gather-package.bat for this purpose but I think it is not enough to compile a 32bit version of stransmit.exe. Is it possible to compile a 32bit version of stransmit.exe for windows or the srt code needs to be compiled in 64bit? (I apologize if this question does not go here or is too basic, I am learning with some difficulty).

[https://github.com/manueldev/srt/blob/master/gather-package.bat](url)
[https://github.com/manueldev/srt/blob/master/.appveyor.yml](url)

**Comment by ethouris** [comment]
Did you try to compile it and have any problems doing it? The build system is mainly prepared for 64-bit build, but as long as all dependencies for 32-bit version are satisfied, there shouldn't be any problems. If you say "not enough", I state you have found some problems when trying to compile it and you can share them.

**Comment by ethouris** [comment]
Well, this might be the problem if Microsoft Visual Studio, which no longer compiles binaries executable under older systems than Windows 7. Or maybe it needs some extra options to do this.

If you try this with a different compiler, mind FOA that stransmit itself uses C++11 - I'd recommend to try with MinGW gcc compiler, it should at least give you a chance.

**Comment by maxlovic** [comment]
Hi @manueldev,
You should indeed use something like the `v140_xp` platform toolset in Visual Studio to be able to build the application targeting Windows XP.

At the same time, your message seems to say that there is no `inet_pton` function defined in Windows system headers. See the [doc](https://docs.microsoft.com/en-us/windows/desktop/api/ws2tcpip/nf-ws2tcpip-inet_pton): Minimum supported client | Windows 8.1, Windows Vista.
So the next step might be to manually define the `inet_pton` function.

But I guess it would be easier to build with MinGW.
