### ISSUE TITLE
Building with msys2 fails

### ISSUE THREAD

**Issue by mifritscher** [Haivision/srt#329]
Compiling works after trivial hacks to configure (change the shebang to #!/mingw64/bin/tclsh) and CMakeLists.txt (adding `elseif(MINGW) add_definitions(-DMINGW=1)` arount lin 177), but linking fails miserable. Because of lines like `CMakeFiles/srt.dir/srtcore/buffer.cpp.obj:buffer.cpp:(.text+0x11e): undefined reference to `operator new(unsigned long long)'` I assume that it isn't link against the standard library?

Log:

> $ make
> System is unknown to cmake, create:
> Platform/MINGW64_NT-6.1 to use this system, please send your config file to cmake@www.cmake.org so it can be added to cmake
> Your CMakeCache.txt file was copied to CopyOfCMakeCache.txt. Please send that file to cmake@www.cmake.org.
> -- SSL libraries: /mingw64/lib/libssl.a;/mingw64/lib/libcrypto.a
> -- COMPILER: GNU compat: /mingw64/bin/CC.exe
> -- MINGW detected
> -- SOURCES(haicrypt): haicrypt/hc_openssl_aes.c;haicrypt/hc_openssl_evp_cbc.c;haicrypt/hc_openssl_evp_ctr.c;haicrypt/hcrypt.c;haicrypt/hcrypt_ctx_rx.c;haicrypt/hcrypt_ctx_tx.c;haicrypt/hcrypt_rx.c;haicrypt/hcrypt_sa.c;haicrypt/hcrypt_tx.c;haicrypt/hcrypt_xpt_srt.c;haicrypt/hcrypt_xpt_sta.c
> -- Haicrypt attached to sources of srt
> -- Target haicrypt: TYPE:VIRTUAL ACTUAL TARGET: srt HEADERS: {haicrypt/haicrypt.h;haicrypt/hcrypt_ctx.h;haicrypt/hcrypt_msg.h}
> -- Target srt: TYPE:SHARED SOURCES: {srtcore/api.cpp;srtcore/buffer.cpp;srtcore/cache.cpp;srtcore/ccc.cpp;srtcore/channel.cpp;srtcore/common.cpp;srtcore/core.cpp;srtcore/csrtcc.cpp;srtcore/epoll.cpp;srtcore/list.cpp;srtcore/md5.cpp;srtcore/packet.cpp;srtcore/queue.cpp;srtcore/srt_c_api.cpp;srtcore/window.cpp;srtcore/../common/srt_compat.c;haicrypt/hc_openssl_aes.c;haicrypt/hc_openssl_evp_cbc.c;haicrypt/hc_openssl_evp_ctr.c;haicrypt/hcrypt.c;haicrypt/hcrypt_ctx_rx.c;haicrypt/hcrypt_ctx_tx.c;haicrypt/hcrypt_rx.c;haicrypt/hcrypt_sa.c;haicrypt/hcrypt_tx.c;haicrypt/hcrypt_xpt_srt.c;haicrypt/hcrypt_xpt_sta.c} DEPENDS: {} HEADERS: {srtcore/srt.h;srtcore/logging_api.h;srtcore/platform_sys.h;srtcore/udt.h;srtcore/srt4udt.h}
> -- C++ VERSION: Setting C++11 compat flag for gnu compiler
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/michaelfritscher/srt/srt
> 
> ...
> [ 92%] Building C object CMakeFiles/srt.dir/haicrypt/hcrypt_xpt_srt.c.obj
> [ 96%] Building C object CMakeFiles/srt.dir/haicrypt/hcrypt_xpt_sta.c.obj
> [100%] Linking CXX shared library libsrt.so
> CMakeFiles/srt.dir/srtcore/api.cpp.obj:api.cpp:(.text+0x139): undefined reference to `operator delete(void*, unsigned long long)'
> CMakeFiles/srt.dir/srtcore/api.cpp.obj:api.cpp:(.text+0x14e): undefined reference to `operator delete(void*, unsigned long long)'
> CMakeFiles/srt.dir/srtcore/api.cpp.obj:api.cpp:(.text+0x165): undefined reference to `operator delete(void*, unsigned long long)'
> CMakeFiles/srt.dir/srtcore/api.cpp.obj:api.cpp:(.text+0x17a): undefined reference to `operator delete(void*, unsigned long long)'
>  ...
> CMakeFiles/srt.dir/haicrypt/hcrypt_xpt_sta.c.obj:hcrypt_xpt_sta.c:(.text+0x6d): undefined reference to `__imp_htonl'
> C:/msys64/mingw64/lib/libcrypto.a(rand_win.o):(.text+0xd5b): undefined reference to `__imp_GetDeviceCaps'
> C:/msys64/mingw64/lib/libcrypto.a(rand_win.o):(.text+0xd88): undefined reference to `__imp_CreateCompatibleBitmap'
> C:/msys64/mingw64/lib/libcrypto.a(rand_win.o):(.text+0xd9e): undefined reference to `__imp_GetObjectW'
> C:/msys64/mingw64/lib/libcrypto.a(rand_win.o):(.text+0xe61): undefined reference to `__imp_GetDIBits'
> C:/msys64/mingw64/lib/libcrypto.a(rand_win.o):(.text+0xef0): undefined reference to `__imp_DeleteObject'
> collect2.exe: error: ld returned 1 exit status
>

**Comment by ethouris** [comment]
This definitely looks like the standard library. If you show the actual command line (`make VERBOSE=1`) for the linker it would help.

To make the `configure` script runnable with an unknown location of tclsh, the standard way is to do:
```
#!/bin/bash
# Switch to Tcl \
exec tclsh "$0" "$@"
```
But I'm not sure as to whether `/bin/bash` is a correct path for msys either.

This looks for me like not adding some standard library, but then, well, it looks like it would have problems with compiling any least C++ application. I'd recommend also that you try out the version at the `dev` branch cause this is going to be a new release soon, and I know that it got some fixes also concerning unusual platforms. Any platform fix better goes there.

**Comment by mifritscher** [comment]
VERBOSE=1:
[  3%] Linking CXX shared library libsrt.so
/usr/bin/cmake.exe -E cmake_link_script CMakeFiles/srt.dir/link.txt --verbose=1
/mingw64/bin/CC.exe  -fPIC    -Wall -Wextra  -shared  -o libsrt.so CMakeFiles/srt.dir/srtcore/api.cpp.obj CMakeFiles/srt.dir/srtcore/buffer.cpp.obj CMakeFiles/srt.dir/srtcore/cache.cpp.obj CMakeFiles/srt.dir/srtcore/ccc.cpp.obj CMakeFiles/srt.dir/srtcore/channel.cpp.obj CMakeFiles/srt.dir/srtcore/common.cpp.obj CMakeFiles/srt.dir/srtcore/core.cpp.obj CMakeFiles/srt.dir/srtcore/csrtcc.cpp.obj CMakeFiles/srt.dir/srtcore/epoll.cpp.obj CMakeFiles/srt.dir/srtcore/list.cpp.obj CMakeFiles/srt.dir/srtcore/md5.cpp.obj CMakeFiles/srt.dir/srtcore/packet.cpp.obj CMakeFiles/srt.dir/srtcore/queue.cpp.obj CMakeFiles/srt.dir/srtcore/srt_c_api.cpp.obj CMakeFiles/srt.dir/srtcore/window.cpp.obj CMakeFiles/srt.dir/common/srt_compat.c.obj CMakeFiles/srt.dir/haicrypt/hc_openssl_aes.c.obj CMakeFiles/srt.dir/haicrypt/hc_openssl_evp_cbc.c.obj CMakeFiles/srt.dir/haicrypt/hc_openssl_evp_ctr.c.obj CMakeFiles/srt.dir/haicrypt/hcrypt.c.obj CMakeFiles/srt.dir/haicrypt/hcrypt_ctx_rx.c.obj CMakeFiles/srt.dir/haicrypt/hcrypt_ctx_tx.c.obj CMakeFiles/srt.dir/haicrypt/hcrypt_rx.c.obj CMakeFiles/srt.dir/haicrypt/hcrypt_sa.c.obj CMakeFiles/srt.dir/haicrypt/hcrypt_tx.c.obj CMakeFiles/srt.dir/haicrypt/hcrypt_xpt_srt.c.obj CMakeFiles/srt.dir/haicrypt/hcrypt_xpt_sta.c.obj /mingw64/lib/libssl.a /mingw64/lib/libcrypto.a
CMakeFiles/srt.dir/srtcore/api.cpp.obj:api.cpp:(.text+0x139): undefined reference to `operator delete(void*, unsigned long long)'

yes, `/bin/bash` (and `/bin/sh`) exists on msys, too.

Ok, I'll trying the dev branch.

**Comment by mifritscher** [comment]
Your configure Patch indeed works on msys2.
The dev branch has exactly the same problems as master.

**Comment by ethouris** [comment]
Hey, WTF is going on there, `/mingw64/bin/CC.exe` is used as a linker? This surely won't work. I have no idea how this most intelligent build tool in the world has figured out that for "Linking CXX" it should use `CC.exe`, but this definitely should be changed.

There is a method to override the "cmake's guess" of the C++ linker - e.g. `CMAKE_LINKER` variable (you can enforce it from `configure` by adding `--cmake-linker` option and set it to the C++ compiler executable); when you prove that this is something specific for msys, try to add a fix in CMakeLists.txt file.

**Comment by ethouris** [comment]
@mifritscher : I need to know if this thing is a problem anymore. Build system underwent some changes since.
