### ISSUE TITLE
Statistic shows zero values for stransmit tool

### ISSUE THREAD

**Issue by maxmashnitsky** [Haivision/srt#33]
I have run server by command:
`/srt-master/stransmit -v udp://:5555 'srt://0.0.0.0:9000?mode=server&latency=500'`

and client by command:
`/srt-master/stransmit 'srt://xxx.xxx.xxx.xxx:9000/?mode=client&latency=2000' udp://127.0.0.1:5000  -s:100 -r:100 -t:60`

And see stats report with 0 values for packages:

```
======= SRT STATS: sid=831244345
PACKETS SENT: 0 RECEIVED: 0
LOST PKT SENT: 0 RECEIVED: 0
REXMIT SENT: 0 RECEIVED: 0
RATE SENDING: 0 RECEIVING: 0
BELATED RECEIVED: 1230 AVG TIME: 1.844674407e+16
REORDER DISTANCE: 0
WINDOW: FLOW: 8192 CONGESTION: 8192 FLIGHT: 0
RTT: 173.01ms  BANDWIDTH: 0.011648Mb/s
BUFFERLEFT: SND: 12288000 RCV: 11914500
+++/+++SRT TRANSFER: 13063141084B DURATION: 75666814ms SPEED: 168.608kB/s
```

I have build srt from master branch source
What should I do additional that stransmit calculate collect more statistic?

Thanks at advance.

**Comment by ethouris** [comment]
Confirmed. From the code theoretical analysis for me it should work, so I have to take a closer look to it.

**Comment by ethouris** [comment]
@maxmashnitsky , please check if the latest version, with the aforementioned commit included, fixes the problem, and close if so.

**Comment by maxmashnitsky** [comment]
It works. 
Thank you very much for your support
