### ISSUE TITLE
Direct integration in ffmpeg?

### ISSUE THREAD

**Issue by mifritscher** [Haivision/srt#330]
Are there any plans to integrate the library directly into ffmpeg?

**Comment by ethouris** [comment]
There are plans to integrate into libav.

**Comment by heidabyr** [comment]
Yes, we have the patch ready, but the ffmpeg team hasn't accepted it. No technical or logical reasons for it though. libav.org accepted the patch and it is part of the project now.

**Comment by heidabyr** [comment]
https://github.com/libav/libav/commit/a2fc8dbae85339d1b418d296f2982b6c04c53c57

**Comment by mifritscher** [comment]
Oh, ok, I see the discussion in ffmpeg-devel. So all we can do for now hoping... I've already wrote some lines to the list.
