### ISSUE TITLE
clients not connecting to srt server [UDT::connect: [1001] Connection setup failure]

### ISSUE THREAD

**Issue by mks75** [Haivision/srt#344]
Hi,
I am seeing strange issue with my SRT server. Earlier this was working and connecting well to clients. But now no client is able to connect and client shows following error:

UDT::connect: [1001] Connection setup failure: connection time out.
SrtCommon: DESTROYING CONNECTION, closing sockets

Nothing has changed on either server or the client side as far as configuration is concerned.
Could you please advise on what could be the issue here?

Thanks-

**Comment by ethouris** [comment]
I need more details. What version were of the SRT library on every side and what was the command line?

This message usually means that neither one UDP packet sent with the handshake control message has reached the other party - either the caller, when calling in, or the listener, when responding.

**Comment by maxlovic** [comment]
Closing.
