### ISSUE TITLE
stransmit symlink missing when DESTDIR is set

### ISSUE THREAD

**Issue by heftig** [Haivision/srt#357]
The build tries to create a symlink `stransmit` → `srt-live-transmit` but ignores the `DESTDIR` environment variable. As a result, when attempting to package srt the symlink is missing.

E.g. it tries to run `ln -s srt-live-transmit /usr/bin/stransmit` when it should be running `ln -s srt-live-transmit $DESTDIR/usr/bin/stransmit`.

**Comment by devurandom** [comment]
Please see whether this patch fixes the issue for you: #503

**Comment by devurandom** [comment]
It turned out to be impossible to do with CMake.

See-Also: https://github.com/Haivision/srt/pull/503#issuecomment-447600237
See-Also: https://bugs.gentoo.org/672088
