### ISSUE TITLE
CPU Overload

### ISSUE THREAD

**Issue by garybruckheimer** [Haivision/srt#363]
I try to benchmark SRT Library CPU Load on different systems like x86 and ARM.

I start with the latest github version and have seen that i have an cpu leak on OSX over 99% on one core when i set srt first then udp as second argument. SRT Library was 1.3.

Example 1 (CPU Over 99%) - OSX Sierra - No Network Load
./srt-live-transmit srt://192.168.1.122:9002?mode=listener udp://192.168.1.122:9003 -v

![bildschirmfoto 2018-04-29 um 13 13 56](https://user-images.githubusercontent.com/566761/39405959-5c1b9806-4baf-11e8-8041-eca69a6ff62c.jpg)

Example 2 (CPU 6.9%) - OSX Sierra - No Network Load
./srt-live-transmit udp://192.168.1.122:9002 srt://192.168.1.122:9003?mode=client -v

![bildschirmfoto 2018-04-29 um 13 15 58](https://user-images.githubusercontent.com/566761/39405964-8435ed64-4baf-11e8-92ad-03df43d2c51a.jpg)

Before i start gdb and profiling i would like to know if anyone can please check this on his own systems if he see the same CPU values.

**Comment by ethouris** [comment]
Does this mean that you are trying it in "dry run" (that is, without connecting anything and transmission)? What happens in the "listener" configuration if you connect some other party and start sending?

**Comment by garybruckheimer** [comment]
This is a dry-run, cause i need cpu load on a low power and in-expensive ARM board which has just 2 cores, but as i said it also happend on my mac. 

I will test to send traffic and report the results.

**Comment by ethouris** [comment]
Note that if this is a dry-run then it surely shows you how the listener is behaving during actually doing nothing. You can also retry this test using the `srt-test-live` application (enabled with `--enable-testing`), which is a developer-only version designed a little bit different way (straightforward and one-to-one only, no reconnections etc.) and if one of the media is SRT in listener mode, it won't start reading from UDP until one client connects. The SRT listener behavior in this application should be exactly the same (may differ the blocking or non-blocking mode, which is controlled by the `blocking` option).

**Comment by garybruckheimer** [comment]
We continued to look at the problem with the CPU load and the problem seems more difficult than I thought. Here are my results. 

instance 1) Start SRT Listener (CPU Load is around 98%)
./srt-live-transmit srt://192.168.1.122:9003?mode=listener udp://192.168.1.122:9004 -v

instance 2) Start SRT Client (CPU Load is around 6%)
./srt-live-transmit udp://192.168.1.122:9002 srt://192.168.1.122:9003?mode=client -v

Start transmission over UDP with an MpegTS h.264 and aac to port:9002. 

After 5 seconds the CPU from instance 1 goes over 147%:

![bildschirmfoto 2018-05-01 um 23 28 08](https://user-images.githubusercontent.com/566761/39494728-cf5d36a0-4d97-11e8-9cf9-6723fbc8bff2.jpg)

There is no transcoding, just the protocol transmuxing without any encryption. It seems that i have to run profiling now. 

Another strange thing is that the CPU is only high when we have the listener on the first input pipe, when we set it as output, CPU goes down: 

CPU is low (6-8%)!
./srt-live-transmit udp://192.168.1.122:9002 srt://192.168.1.122:9003?mode=listener -v

CPU is high (99%)
./srt-live-transmit srt://192.168.1.122:9002=mode=listener srt://192.168.1.122:9003?mode=listener -v

CPU is high (99%)
./srt-live-transmit srt://192.168.1.122:9002=mode=listener udp://192.168.1.122:9003 -v

Can anyone confirm my results and my try the same tests to confirm the high cpu usage?

Will now go into debug and profilling!

Thanks for any help..

**Comment by ethouris** [comment]
Again, please retry the same using `srt-test-live` instead of `srt-live-transmit`, and test with both `blocking` parameter set to true and false. To have this application compiled, you need extra `--enable-testing` option for configure. I'm trying to narrow down the FA that might be responsible for the problem.

**Comment by garybruckheimer** [comment]
Will do the test with srt-test-live ethouris and come back with the result. Thanks for your feedback.

**Comment by garybruckheimer** [comment]
Had some time today and test with srt-test-live. This looks much better. Got a cpu load of <1%. I also test OpenSSL Version openssl-1.1.0h, encryption performs also better with this version 6-8% CPU with encryption on. It´s Great!!!

Screenshot attached. 

![bildschirmfoto 2018-05-05 um 14 07 10](https://user-images.githubusercontent.com/566761/39663163-79fe0b88-506e-11e8-83fb-dd8cb7989858.jpg)

With this version i was able to run it on a very low power and low cost embedded tiny ARM device where i want to build a cluster of 128 devices for SRT Cloud Computing.  

![img_7378](https://user-images.githubusercontent.com/566761/39663173-a03d381e-506e-11e8-8938-aab0303bff21.jpg)

I will try now to understand the difference between these two versions, re-connection is a must have, but i do not think that this is the only reason for the high CPU.

Thanks a lot for helping me out, i can now bring our project to the next round.

Cheers
Gary

**Comment by heidabyr** [comment]
Thank you for your passion, Gary, you rock!!!

**Comment by matiaspl** [comment]
Judging from the picture - are you trying to run SRT on an ESP or Arduino?
:)

2018-05-05 21:01 GMT+02:00 Marc Cymontkowski <notifications@github.com>:

**Comment by rndi** [comment]
Hello @garybruckheimer ,

More on OSX CPU load topic on the newly re-opened issue here: #291

Thanks for your help with finding this!

**Comment by garybruckheimer** [comment]
@matiaspl , yes i test now several plattforms from armv8, atmel, x86 etc. I love low power devices.

**Comment by rndi** [comment]
Fixed under #291
