### ISSUE TITLE
srt://host:1234 Protocol not found

### ISSUE THREAD

**Issue by nawer56** [Haivision/srt#364]
Hello,
 I'm trying to use libsrt from ffmpeg 4.0. But I'm stuck Into this issue. 

My ffmpeg command : `ffmpeg -re -i big_buck_bunny_1080p_stereo.avi -c copy -f mpegts srt://127.0.0.1:4242`
My listener is : `stransmit srt://:1234 udp://127.0.0.1:4141`

When I execute this line, I receive this log from ffmpeg : 

"ffmpeg version 4.0 Copyright (c) 2000-2018 the FFmpeg developers
  built with Apple LLVM version 9.0.0 (clang-900.0.39.2)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.0 --enable-shared --enable-pthreads --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-gpl --enable-chromaprint --enable-ffplay --enable-libass --enable-libfdk-aac --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-librsvg --enable-librtmp --enable-librubberband --enable-libsnappy --enable-libsoxr --enable-libssh --enable-libtesseract --enable-libvidstab --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libzimg --enable-libzmq --enable-opencl --enable-videotoolbox --enable-openssl --enable-lzma --enable-libopenjpeg --disable-decoder=jpeg2000 --extra-cflags=-I/usr/local/Cellar/openjpeg/2.3.0/include/openjpeg-2.3 --enable-nonfree
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
Input #0, avi, from 'big_buck_bunny_1080p_stereo.avi':
  Metadata:
    encoder         : MEncoder 2:1.0~rc2-0ubuntu13
  Duration: 00:09:56.46, start: 0.000000, bitrate: 9586 kb/s
    Stream #0:0: Video: msmpeg4v2 (MP42 / 0x3234504D), yuv420p, 1920x1080, 9328 kb/s, 24 fps, 24 tbr, 24 tbn, 24 tbc
    Stream #0:1: Audio: mp3 (U[0][0][0] / 0x0055), 48000 Hz, stereo, fltp, 245 kb/s
srt://127.0.0.1:4242: Protocol not found
~/Downloads$ 
" 

Any idea where the problem come from ? 

Edit : when I list the protocol supported by ffmpeg it seems srt isn't supported ....
`ffmpeg --protocols -v 0`

"Supported file protocols:
Input:
  async
  cache
  concat
  crypto
  data
  file
  ftp
  gopher
  hls
  http
  httpproxy
  https
  mmsh
  mmst
  pipe
  rtp
  srtp
  subfile
  tcp
  tls
  udp
  udplite
  unix
  rtmp
  rtmpe
  rtmps
  rtmpt
  rtmpte
  sftp
Output:
  crypto
  file
  ftp
  gopher
  http
  httpproxy
  https
  icecast
  md5
  pipe
  prompeg
  rtp
  srtp
  tee
  tcp
  tls
  udp
  udplite
  unix
  rtmp
  rtmpe
  rtmps
  rtmpt
  rtmpte
  sftp
"

**Comment by jeandube** [comment]
I don't see --enable-libsrt in the configuration line so ffmpeg was not built with it.

**Comment by nawer56** [comment]
ok my bad, 

I though it would be install by default. 

That's solve my issue, thank you.

**Comment by digenPrime** [comment]
@jeandube how to enable --enable-libsrt ?

**Comment by ethouris** [comment]
When running `configure`

**Comment by maxsharabayko** [comment]
@digenPrime 
> I have the same issue but I don't know how to enable libsrt.

Useful links:
- [Building FFmpeg with SRT](https://srtlab.github.io/srt-cookbook/apps/ffmpeg/#building-ffmpeg-with-srt) - SRT Cookbook.
- [FFmpeg's Compilation Guide](https://trac.ffmpeg.org/wiki/CompilationGuide)

**Comment by anujkv** [comment]
Hello,

I'm currently working on an Android application using ffmpeg-kit-full 6.0 and aiming to utilize libsrt for streaming. However, I've encountered an issue where the application does not recognize the SRT protocol.

When I run the command below in the Android terminal, it shows that the SRT protocol is present:

ffmpeg -protocols | grep srt
However, when I check the supported protocols within the app using FFmpegKit, the SRT protocol appears to be missing:

FFmpegKit.executeAsync("-protocols") { session ->
    val output = session.output
    Log.d("FFmpeg", "Supported Protocols:\n$output")
}

I need to add SRT protocol support to the application to convert RTSP URLs into SRT URLs and enable playback in ExoPlayer using the SRT URL.

If this functionality is unavailable, could you consider adding RTSP to SRT protocol conversion support in future releases?

Additionally, if there's an existing solution or workaround, please let me know.

Thank you!
