### ISSUE TITLE
Compiling for Windows

### ISSUE THREAD

**Issue by mattibutt** [Haivision/srt#373]
Hi
Can anyone help me to compile SRT for windows, I have tried to follow through steps but its not working for me.

![compile](https://user-images.githubusercontent.com/38955314/39585961-db409960-4eed-11e8-9bb3-1da974a43e59.JPG)

**Comment by ethouris** [comment]
`configure` is a script that you should simply run: `./configure`. For Cygwin you might want to use `--cygwin-use-posix` option if you want to make it compile much like you'd do it on Linux.

**Comment by mattibutt** [comment]
Hi
it seems to be difficult to follow through it would be help if you have
visual studio project which has these sources and I can use that to build
the exe version.

thanks


On Fri, May 4, 2018 at 8:13 AM, Sektor van Skijlen <notifications@github.com

**Comment by ethouris** [comment]
The `configure` script is just a helper script written in Tcl that should ease up option specification for cmake. The whole build system is based on cmake; `configure` is just an optional user-friendly wrapper.

If you want to have a VS project created for this, I suggest you try out the GUI tool for cmake for Windows.

**Comment by mattibutt** [comment]
ok now i understand and able to open the project using cmake.txt file
however its difficult for me build pthread could you please send me this,




On Fri, May 4, 2018 at 2:38 PM, Sektor van Skijlen <notifications@github.com

**Comment by mattibutt** [comment]
Hi
My colleague has built pthread and I copied
this C:\srt-master\submodules\pthread-win32 but its not finding this file
when i try to build the project. does it need to go in another location?


Severity Code Description Project File Line Suppression State
Error CMake Error at CMakeLists.txt:341 (message):
  Failed to find pthread.h.  Specify PTHREAD_INCLUDE_DIR. CMakeLists.txt

**Comment by ethouris** [comment]
Yes, you need to compile pthread, install it somewhere, and then pass this location to this variable.

**Comment by maxlovic** [comment]
@mattibutt 
Use the following command. Modify it based on your VS version and PThreads path.:
```
cmake ../ -G"Visual Studio 15 2017 Win64" -DPTHREAD_INCLUDE_DIR="C:\srt-master\submodules\pthread-win32\include" -DPTHREAD_LIBRARY=C:\srt-master\submodules\pthread-win32\lib\pthread_lib.lib"
```
See the [ReadMe](https://github.com/Haivision/srt/blob/master/README.md#for-windows) for other tips for Windows.
