### ISSUE TITLE
anyone managed to play an SRT stream in VLC 4.0 nightly for Windows ?  

### ISSUE THREAD

**Issue by Svyatk0** [Haivision/srt#392]
I guess the title says it all. 
Trying to play an SRT stream in windows version of  VLC 4.0 player. but its just not happening. its almost as if it's not detecting the SRT stream at all.
Same sender pushing udp to the same receiver works without issues, so cant be firewall. 
 
Wonder whether anyone tested it with win VLC. 

thanks

**Comment by heidabyr** [comment]
That was one of my demos at NAB this year, streaming 4Kp60 HEVC in MPEG-TS over SRT from our encoder to VLC on Windows.

**Comment by rndi** [comment]
@Svyatk0 , listener mode is not supported for the moment. The code is [here](https://github.com/videolan/vlc/blob/master/modules/access/srt.c) if you would like to take a look.

Also try removing '@' from the URI, i.e. srt://ffmpeg.host.ip:8000
I just tested in a Win10 VM using GUI and the build quoted above and it does not connect when '@' is added.

**Comment by Svyatk0** [comment]
@rndi Thanks for the clues mate. Finally got it working with VLC, including the latest nightly build. what was tripping me off was the fact that listener mode was not supported, which changes everything :-)

As it currently stands i got it working with ffmpeg as a "sender" and VLC 4 as a "Receiver"
here where my commands for anyone that needs it : 
**FFMPEG** 
 `./ffmpeg-4.1dev -y -i 'udp://@239.44.100.250:5001?reuse=true&timeout=500&fifo_size=573440&buffer_size=128000&overrun_nonfatal=true&localport=30503' -c:v copy -c:a copy -f mpegts -muxrate 7M 'srt://0.0.0.0:7000?pkt_size=1316&mode=listener&nakreport=1&listen_timeout=-1'`
  
**VLC 4.0 win64**
`srt://ffmpeg.server.IP:7000`

Next step is to get this working with Wowza sender. 

Thanks again for the help.

**Comment by rndi** [comment]
Not a problem @Svyatk0 , glad I could help!
