### ISSUE TITLE
multiple streams with different modes

### ISSUE THREAD

**Issue by vandanachadha** [Haivision/srt#396]
My requirement is to start a process which will create multiple streams, with my server being in listener mode for some, and in caller mode for others. From what I understand of srt-multiplex, this can be used for either i (input) or o (output). For my problem, do I start multiple instances of srt-multiplex in different threads? Or is there a better solution.  Pls advise

**Comment by rndi** [comment]
@vandanachadha , I would suggest a single thread serving a collection of listener and caller sockets configured for non-blocking operation. In fact, you should be able to re-use at least some of the code in srt-live-transmit main loop to do just that. You don't have to call SRT send/receive APIs from the same thread as these calls are protected internally.

**Comment by vandanachadha** [comment]
Thank you both for your comments, but pls help me decide whether to use stransmit-live or srt-multiplex. I am a novice in this arena and your guidance is very valuable. 
From what I have understood from above:
1. Make changes to starnsmit-live main function to start a thread, and in this thread, within a loop, create a source/target and start a stream with a name in non blocking mode, and then iterate to next source/target, start another stream and so on.  
2. Or use srt-multiplex?
To clarify, what I am trying to do is,  "trying to run transmission of multiple streams", and each stream consists of a mode (listener,caller, rendezvous) and a source port/ip and a destination port/ip. So there can be a stream in caller mode on source 192.168.1.1:8001 and destination 192.168.1.2:8002 and another stream in listener mode with source :8003 and destination 192.168.1.3:8003 and so on.

**Comment by stoyanovgeorge** [comment]
Actually, there are more people who want exactly that feature @rndi . You can refer to [issue 574](https://github.com/Haivision/srt/issues/574)

**Comment by maxsharabayko** [comment]
Closing this request.
`srt-live-transmit` is meant to be a simple application, a quick start for people to get themselves familiar with the protocol and workflows. The main development effort is focused on the SRT library itself.

Having multiple clients sounds like a solution (e.g. [SRT Gateway](https://www.haivision.com/products/srt-gateway/)) that depends on the target appliance. Definitely not something for a sample application.

But the application you need can be quite easily done based on the code of the `srt-live-transmit`. The SRT library fully supports this workflows.
