### ISSUE TITLE
MPEG-TS transfer issue with V1.3.0

### ISSUE THREAD

**Issue by mks75** [Haivision/srt#405]
Hi,
I recently tried using V1.3.0 for MPEG-TS transfer and seeing strange issue.
The transfer keeps dropping completely and resuming back after sometime. I tried using both ./stransmit and ./srt-live-transmit.
However previous version V1.2.3 works well without any issue.
Attaching one snapshot for reference.

Please advise - Thanks
![transfer-bandwidth-snapshot](https://user-images.githubusercontent.com/34006918/40865242-610c7c56-65c5-11e8-9c65-869d2466c18a.png)

**Comment by ethouris** [comment]
Let's start with [this](../tree/master/docs/reporting.md).

**Comment by mks75** [comment]
Hi,
I will try to capture debug logs and share with you.
Quick question - 
Should we use  fifo_size=1000000&overrun_nonfatal=1 while taking udp source as input, for better stability or it's taken care in SRT? This we usually do in ffmpeg.
for example:
/home/sysadmin/stransmit -r:1000 -t:300 "udp://@239.12.5.10:12510?fifo_size=1000000&overrun_nonfatal=1" "srt://10.10.10.10:30012?mode=rendezvous&latency=1000&passphrase=123456789qwer"

Please advise.

Thanks-MKS

**Comment by ethouris** [comment]
These options are not supported in UDP URI in stransmit. I tried to understand what these options do in case of ffmpeg, but it's rather unclear, does't look like any system option related to UDP and looks like something to be tweaked in the ffmpeg implementation - this "fifo" is probably some internal buffer for UDP transmission and "overrun" may happen when the buffer is fed but not purged.

As you use "stransmit", I hope you use the latest version, where it's a symbolic link to "srt-live-transmit". This one, AFAIR, does use buffering for UDP and the intermediate buffer is dynamically allocated. I don't think it has any size limit, this rather relies on the fact that the stubborn non-readers got cut off on timeout.

**Comment by mks75** [comment]
Thanks @ethouris.
Actually, I am seeing intermittent CC errors and PCR accuracy errors on the receiving side, and I wonder what is causing this? I have kept the latency to 1000, which is more than required for my network. It might be possible that the transfer is ok but UDP buffer values on source or destination servers could be causing packet loss within the server. I am trying to fine tune the entire transfer process from source input (udp mpegts)-> SRT transfer -> destination output (udp mpegts).

[1] Do I need to allocate more udp buffer (read/write buffer) to Linux OS?
[2] I understood from you that stransmit allocates dynamic buffer to the input udp stream and no separate commands are required, but do I need to allocate some additional buffer to the output udp stream at the destination side?

Please advise.

At present, I am using Ver 1.2.3, as in my case the stream keeps dropping with Ver 1.3.0, and I will try to capture logging for that.

Thanks - MKS

**Comment by ethouris** [comment]
Ok, there's not much you can do when the local UDP is losing data. Might be better if you try to push the stream throught the pipe directly.

If you are using version 1.2.3, note that `stransmit` is in the "tester version" here yet, and there's no UDP buffering at all (at least not at the application level) - it just reads one UDP packet and sends it over SRT immediately, that's all. You just need to remember that every packet that is **received** over UDP must be at most 1316 bytes long. This "dynamic buffer allocation" is only in the new version coming with 1.3.0 and `srt-live-transmit` application, which is more user-friendly, for example, it supports auto-reconnection and multiple callers connected to the listener.

I don't think there's any tweaking needed in the system; usually the packet drops on the local machine should never occur, unless there is some system performance problem.

If you experience large drops with version 1.3.0, I'd keenly see this in action, so if you can record the debug logs (from both parties) and the pcap file from such a session, it'd be great.

**Comment by mks75** [comment]
Hi  @ethouris,
I did some testing on V1.3 and noticed that, -t option is causing the stream to stop after the mentioned duration in seconds. In my case I used -t:120 at source side, and I noticed the stream stops close to 2 minutes.

command at source:
./srt-live-transmit -v -r:1000 -s:1000 -t:120 "udp://@239.1.1.1:1234" "srt://10.10.10.10:30000?mode=rendezvous&latency=1000&passphrase=test12345678"

(The display shows:)
TIMEOUT: will interrupt after 30s
.
.
.
.
.
(and after 120 seconds, it shows the follwing message and connection drops)
---------- INTERRUPT ON TIMEOUT!

SrtCommon: DESTROYING CONNECTION, closing sockets (rt%953330112 ls%-1)...

SrtCommon: ... done.



Command at destination:

 ./srt-live-transmit -v -r:1000 -s:1000 "srt://20.20.20.20:30000?mode=rendezvous&latency=1000&passphrase=test12345678" "udp://@239.2.2.2:2222"

(after 120sec, this side keeps waiting for connection)


-t option is for input timeout but in this case the transfer only runs for this duration. Please advise.

Thanks-MKS

**Comment by ethouris** [comment]
Yes, the `-t` option's meaning is different in `stransmit` (1.2) and `srt-live-transmit` (1.3). In stransmit it was the time up to which the "transmission silence" is tolerated (the help explanation is somewhat misleading) and it was set to 30s by default. In 1.3 srt-live-transmit this option is predicted to be used for testing and it's the time after which the application exits - simultaneously there's no timeout for transmission by default. Also the `-b` option is deprecated - it was for testing only and never intended for any serious use.

**Comment by mks75** [comment]
Thanks @ethouris,
That answers why the transfer was stopping.

I was looking at srt.h for options and there is one regarding latency.
SRTO_LATENCY = 23,    // DEPRECATED. SET: to both SRTO_RCVLATENCY and SRTO_PEERLATENCY. GET: same as SRTO_RCVLATENCY.

Are there any changes in Latency option? Please advise.

Thanks- MKS

**Comment by ethouris** [comment]
There were only changes related to bidirectional transmission support. If you use one direction only, you can still use `SRTO_LATENCY` to set the latency, it simply sets both.

**Comment by mks75** [comment]
Thanks @ethouris
