### ISSUE TITLE
srt_epoll_wait for srt_accept

### ISSUE THREAD

**Issue by justinjoy** [Haivision/srt#406]
I am not sure if it is intended or a bug, but I'd like to ask a question about how to use `srt_epoll_wait` for `srt_accept`. Please take a look the below code which I did to be waiting for a connection request.

``` 
  SRTSOCKET rsock;
  gint rsocklen = 1;

 ...

  if (srt_epoll_wait (srtobject->listener_poll_id, &rsock,
          &rsocklen, 0, 0, poll_timeout, NULL, 0, NULL, 0) < 0) {
    gint srt_errno = srt_getlasterror (NULL);

    if (srt_errno == SRT_ETIMEOUT) {
      return TRUE;
    } else {
      GST_ELEMENT_ERROR (srtobject->element, RESOURCE, FAILED,
          ("abort polling: %s", srt_getlasterror_str ()), (NULL));
      return FALSE;
    }
  }

  caller_sock =
      srt_accept (srtobject->listener_sock, &caller_sa, &caller_sa_len);
```

`srtobject->listener_poll_id` is associated with `srtobject->listener_sock` and it has `SRT_EPOLL_ERR | SRT_EPOLL_IN` option.
For the sock, I have set SRT socket options to the sock as the following values.

```
  {"SRTO_SNDSYN", SRTO_SNDSYN, 0},      /* 0: non-blocking */
  {"SRTO_RCVSYN", SRTO_RCVSYN, 0},      /* 0: non-blocking */
  {"SRTO_LINGER", SRTO_LINGER, 0},
  {"SRTO_TSBPMODE", SRTO_TSBPDMODE, 1}
```

However, `srt_epoll_wait` seems to return immediately even though the timeout is `-1`. I guess there are some mix-ups, but I can't find a proper solution to make it wait for a connection request. Any advice?

**Comment by rndi** [comment]
Maybe check what timeout is set to and what is return value of srt_epoll_wait().

Also, as far as I know, this implementation works correctly: https://github.com/rndi/gst-plugins-bad/blob/1.12-with-srt/ext/srt/gstsrtsrc.c

**Comment by maxlovic** [comment]
Hi @justinjoy, 
Do you have updates on this issue? Please provide a code sample, so we could reproduce it. E.g., we don't know if you call `srt_epoll_add_usock(...)` or `srt_listen(…)` somewhere in you code.

**Comment by justinjoy** [comment]
That would be my mismtake (maybe not?) but I didn’t do any further investigation. Actually, I haven’t set the timeout as -1 since I filed this issue.

I think this can be closed. If I do further investigation and see similar symptoms, I’ll reopen this.

Thank you guys.
