### ISSUE TITLE
Write on Multicast IGMP v3

### ISSUE THREAD

**Issue by madmaz** [Haivision/srt#412]
Hi,
is it SRT expected to work with Multicast IGMP v3 networks?

For example if you have a scenario like the following with two machines (the first is the sender, the second is the receiver):
                                    
(Unicast UDP)----->[ src:UDP  dst:SRT ]--------[ src:SRT dst:UDP ]----->(Multicast UDP IGMP V3)

The receiver needs to write into the IGMP V3 network.
There is something in particular that must be configure on the stransmit tool or in the machine OS?
Thanks.

**Comment by ethouris** [comment]
At least the `srt-live-transmit` application (others probably too) predicts the possibility of using multicast with UDP-type medium. The multicast IP address is automatically recognized by the multicast address mask. The `adapter` and `source` URI parameters are handled in this case.
