### ISSUE TITLE
failed to set option SRTO_PASSPHRASE on socket: Operation not supported: Bad parameters

### ISSUE THREAD

**Issue by Svyatk0** [Haivision/srt#416]
Hey guys. have an odd one here, and wonder if anyone came across this issue. 
I have FFMPEG built with libsrt, and i can happily send and receive SRT streams, except for when i try to use encryption. I get the above error message. 

here is my FFMPEG command: 
 
> ./ffmpeg-4.1dev -loglevel debug -y -i 'udp://237.44.100.14:1234?reuse=true&timeout=500&fifo_size=573440&buffer_size=128000&overrun_nonfatal=true&localport=30503' -c:v copy -c:a copy -f mpegts -mpegts_flags +resend_headers+system_b -pcr_period 15 -muxrate 6M 'srt://xx.xx.xx.xx:7000?pkt_size=1316&mode=caller&oheadbw=5&nakreport=1&latency=250&pbkeylen=16&passphrase=123qwerty0'

The output (truncated):

> ffmpeg version N-91135-g2c2d689 Copyright (c) 2000-2018 the FFmpeg developers
>   built with gcc 4.8.5 (GCC) 20150623 (Red Hat 4.8.5-28)
>   configuration: --prefix=/root/ffmpeg_build --pkg-config-flags=--static --extra-cflags=-I/root/ffmpeg_build/include --extra-ldflags=-L/root/ffmpeg_build/lib --extra-libs=-lpthread --extra-libs=-lm --bindir=/root/bin --enable-gpl --enable-libfdk_aac --enable-libfreetype --enable-libmp3lame --enable-libaom --enable-libopus --enable-libvorbis --enable-libvpx --enable-libx264 --enable-libx265 --enable-nonfree --enable-openssl --enable-libsrt --disable-shared --enable-static
>   libavutil      56. 18.102 / 56. 18.102
>   libavcodec     58. 19.102 / 58. 19.102
>   libavformat    58. 15.100 / 58. 15.100
>   libavdevice    58.  4.100 / 58.  4.100
>   libavfilter     7. 24.100 /  7. 24.100
>   libswscale      5.  2.100 /  5.  2.100
>   libswresample   3.  2.100 /  3.  2.100
>   libpostproc    55.  2.100 / 55.  2.100
> Splitting the commandline.
> .
> .
> .
> .
> Successfully parsed a group of options.
> Opening an output file: srt://xx.xx.xx.xx:7000?pkt_size=1316&mode=caller&oheadbw=5&nakreport=1&latency=250&pbkeylen=16&passphrase=123qwerty0.
> [srt @ 0x4eb1740] No default whitelist set
> [srt @ 0x4eb1740] failed to set option SRTO_PASSPHRASE on socket: Operation not supported: Bad parameters.
> srt://81.96.64.217:7000?pkt_size=1316&mode=caller&oheadbw=5&nakreport=1&latency=250&pbkeylen=16&passphrase=123qwerty0: Input/output error
> [AVIOContext @ 0x4e437c0] Statistics: 5206096 bytes read, 0 seeks
> 11:24:14.429436/SRT:GC!!FATAL!!: SRT.c: IPE: For socket %128047458 MUXER id=-1 NOT FOUND!
> 

FFMPEG was compiled with both --enable-openssl --enable-libsrt

Its worth mentioning that using SRT-Live-Transmit (compiled at the time of building FFMPEG) with encryption works without any issues. 

Will appreciate any ideas on where i am going wrong. 

Thanks

**Comment by ethouris** [comment]
So much is in the code about the conditions under which setting `SRTO_PASSPHRASE` ends up with error:
```
        // Password must be 10-80 characters.
        // Or it can be empty to clear the password.
        if ( (optlen != 0) && (optlen < 10 || optlen > HAICRYPT_SECRET_MAX_SZ) )
            throw CUDTException(MJ_NOTSUP, MN_INVAL, 0);
```
And this seems to be the case here...
```
        case MN_INVAL:
           m_strMsg += ": Bad parameters";
           break;
```
Although it's weird for me that such a condition was satisfied here because `123qwerty0` is definitely 11 characters and it definitely is between 10 and 80.

Might be probably the only way to determine what happened when you compile with debug info and break in the above shown [position in the code](../tree/master/srtcore/core.cpp#L590) and see in the debugger, what exactly string you have in `optval`.

**Comment by Svyatk0** [comment]
weird indeed. I have tried the same passphrase and longer with both FFMPEG and SRT-Live-Transmit and it only fails in FFMPEG. 
also, just so i am clear, are you talking about compiling SRT or FFMPEG ? 

thanks

**Comment by jeandube** [comment]
ffmpeg code (libavformat/libsrt.c) does not look good (here passphrase is a char *):
        (s->passphrase && libsrt_setsockopt(h, fd, SRTO_PASSPHRASE, "SRTO_PASSPHRASE", &s->passphrase, sizeof(s->passphrase)) < 0) ||

**Comment by Svyatk0** [comment]
i am literally staring at this "char* " right now :-) trying to make sense.

**Comment by ethouris** [comment]
It's enough if you have SRT compiled in debug mode (also debug-optimized, if you add `--enable-debug=2`).

**Comment by Svyatk0** [comment]
Rights, so while recompiling with debug on, this is the only thing i can spot, warning wise. 

> In file included from libavformat/libsrt.c:24:0:
> /root/ffmpeg_build/include/srt/srt.h:520:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
>  SRT_API extern SRTSOCKET srt_create_socket();
>  ^
> libavformat/libsrt.c: In function ‘libsrt_open’:
> libavformat/libsrt.c:440:27: warning: assignment from incompatible pointer type [enabled by default]
>              s->passphrase = av_strndup(buf, strlen(buf));
> 

Although, not being exactly a C++ developer this means rather little to me. I guess its reading time ..

**Comment by ethouris** [comment]
srt.h is a C header. That looks strange. SRT_API is a macro that resolves to some compiler-platform-dependent declaration usually adding some information to the function prototype (including to nothing). Would be nice to pass this through preprocessor only (add `-E` option to the gcc command and look into the produced output file) and see what is exactly at this `srt_create_socket`.

Important is to run this in debug mode and stop the debugger in `CUDT::setOpt` function in the case for `SRTO_PASSPHRASE` and see what exactly the value of `optlen` variable is. And if this value is some crazy, just go up the stack and see how this value was crafted.

**Comment by ethouris** [comment]
Looxlike ffmpeg has taken care of the problem; please close if so.
