### ISSUE TITLE
SRT-Multiplex - CATCH! ERROR #6002: Non-blocking call failure: no data available for reading.

### ISSUE THREAD

**Issue by Svyatk0** [Haivision/srt#422]
Hey guys. 
After successful tests with SRT-Live-Transmit, i want to see multiplex in action and need a bit of guidance on using SRT-Multiplex app. Testing both Caller and Listener mode for sender and receiver, i cant seem to get enough data to understand where i am going wrong with the setup. 
I end up with the error message "**CATCH! error: srt_accept: Non-blocking call failure: no data available for reading.**"

I am trying to apply the syntax from the example: 
> "\tSender:    srt-multiplex srt://remhost:2000 -i udp://:5000?id=low udp://:6000?id=high\n"
"\tReceiver:  srt-multiplex srt://:2000 -o output-high.ts?id=high output-low.ts?id=low\n"

My real life example command looks like this: 

**Sender in caller mode**
`./srt-multiplex-1.3.1 -v -loglevel:debug 'srt://10.23.205.62:7000?mode=caller&adapter=eth1&port=8000' -i 'udp://237.44.100.12:1234?id=raw12'`
> Parameters:
        adapter = 'eth1'
        mode = 'caller'
        port = '8000'
Connect with requesting stream [raw12]
Setting outgoing port: 8000
Connecting to 10.23.205.62:7000

> Multicast: home address: INADDR_ANY:1234
Multicast(POSIX): will bind to IGMP address: 237.44.100.12
Found QUIT mediumpair: udp://237.44.100.12:1234?id=raw12  ->  10.23.205.62:7000[raw12]%238942176 - removing from base

> SrtCommon: DESTROYING CONNECTION, closing sockets (rt%238942176 ls%-1)...

> SrtCommon: ... done.

> All media have quit. Marking exit.
SrtCommon: DESTROYING CONNECTION, closing sockets (rt%-1 ls%-1)...

> SrtCommon: ... done.

**Receiver in Listener mode**
`./srt-multiplex -v -loglevel:debug 'srt://:7000?mode=listener&port=8000' -o 'test.ts?id=raw12'`
or 
`./srt-multiplex -v -loglevel:debug 'srt://0.0.0.0:7000?mode=listener&port=8000' -o 'udp://239.10.10.1:1234?id=raw12'`
> Parameters:
        mode = 'listener'
        port = '8000'
Setting up listener: port=7000 backlog=5
Binding a server on 0.0.0.0:7000 ...
 listen...

> Accepting a client...
 accept...

> ERROR #6002: Non-blocking call failure: no data available for reading.

> CATCH!
error: srt_accept: Non-blocking call failure: no data available for reading.
SrtCommon: DESTROYING CONNECTION, closing sockets (rt%-1 ls%-1)...

> SrtCommon: ... done.

I have also tried leaving the "port" parameter out in the SRT URI, but without much change. 

Any obvious flaws in my tests that i am not seeing ? 

Thanks

**Comment by Svyatk0** [comment]
Hey guys. This ticket's been without any love for over a month. Can someone confirm whether multiplex application is actually working or its put on hold with bugs. 

Thanks

**Comment by ethouris** [comment]
What's the purpose of using `srt-multiplex` if you have only one stream to send? This won't do anything more than what `srt-live-transmit` would do, uselessly requiring you to add the stream identifier.

@rndi You may want to see into the reported error; I think `SrtCommon::AcceptNewClient` isn't prepared to work with nonblocking socket.

**Comment by dnastrain** [comment]
Hi @ethouris, an advice on working around this issue? It appears to still be open...

When I try the receiving side like so:
`srt-multiplex -v srt://:7000?mode=listener -i output-high.ts?id=high output-low.ts?id=low`

The app exits immediately with:
```
SRT parameters specified:

        mode = 'listener'
Setting up listener: port=7000 backlog=5
Binding a server on :7000 ...
 listen...
Accepting a client...
 accept...

ERROR #6002: Non-blocking call failure: no data available for reading
CATCH!
error: srt_accept: Non-blocking call failure: no data available for reading
SrtCommon: DESTROYING CONNECTION, closing sockets (rt%-1 ls%-1)...
SrtCommon: ... done.
```

A sample of my test setup for this is:

*Source with 2 UDP streams:*
`ffmpeg -re -stream_loop -1 -i ./data/big_buck_bunny.ts -codec copy -flush_packets 0 -f mpegts udp://127.0.0.1:6001?pkt_size=1316 -c copy -flush_packets 0 -f mpegts udp://127.0.0.1:6000?pkt_size=1316`

*Sender:*
`srt-multiplex -v srt://127.0.0.1:7000?mode=caller -i udp://:6000?id=low udp://:6001?id=high`

*Receiver:*
`srt-multiplex -v srt://:7000?mode=listener -i output-high.ts?id=high output-low.ts?id=low`

*Note:* I also rolled back from *current master* to *Release v1.3.2*, and the behavior seems unchanged.

**Comment by ethouris** [comment]
@dnastrain I saw that; it's a version changed for the needs of easy breaking and nonblocking mode. If you need for testing, please try temporarily the "testing version" of this app created on this branch:

https://github.com/ethouris/srt/tree/dev-add-test-multiplex

(you need `--enable-testing` option for `configure` so that the testing apps are also compiled)

I'm taking a look at it in the meantime.

**Comment by dnastrain** [comment]
ok, that `srt-test-multiplex` version in your branch worked well for some quick testing purposes. thanks!

**Comment by ethouris** [comment]
#718 created to address this. This PR actually removes srt-multiplex and adds srt-test-multiplex.

**Comment by ethouris** [comment]
#718 fixes it
