### ISSUE TITLE
URI syntax

### ISSUE THREAD

**Issue by ltrayanov** [Haivision/srt#435]
I am having a problem starting srt with the following URI:

> ./stransmit -r:5000 -s:5000 srt://:51021?adapter="192.168.1.240"&mode=listener&tlpktdrop=true&latency=150 "udp://192.168.1.111:50001"

It seems that srt input uri cant have more than one parameter.  Am I doing something wrong?

**Comment by rndi** [comment]
Please use quotes around the URL: otherwise `&` will be interpreted 'daemonize' modifier by bash and the rest of URL will become separate commands.

**Comment by ltrayanov** [comment]
I inserted the quotes in my previous post. 
After further testing I cant seem to start srt app if I have additional parameters after "adapter" or "mode" 
For example srt input with 

> "?passphrase=1234567812345678&pbkeylen=16&tlpktdrop=true&latency=150"

 starts without any problem.

**Comment by rndi** [comment]
Your command still does not look right.

Could you please try `stransmit -r:5000 -s:5000 "srt://:51021?adapter=192.168.1.240&mode=listener&tlpktdrop=true&latency=150" "udp://192.168.1.111:50001"`?

**Comment by ltrayanov** [comment]
Thank you! It works.
