### ISSUE TITLE
Question: Log not reporting any issue

### ISSUE THREAD

**Issue by aamirrad** [Haivision/srt#437]
Hi,

I have started using SRT as part of my system for a few months now. I just faced an issue which I need some clarification.

I am using SRT to send ts stream over internet and using a monitoring device on the other side to monitor the stream after its been sent as SRT and converted to UDP. Sometimes I get Continuity Count error and I was hoping that the SRT logs will give some detail as to what is going on. Unfortunately, SRT is not reporting any error or warning, so I am not too sure what is going on. I use the following command and if i change error to debug I see logs been printed. Is there anything else I need to do to see what is happening?

./stransmit -logfa:all -loglevel:error -logfile:"/tmp/error1.log" -v udp://ip:port srt://ip:port/?mode=server
./stransmit -v -logfa:all -loglevel:info -logfile:"/tmp/error2.log" srt://ip:port/?mode=client udp://ip:port

**Comment by ethouris** [comment]
No, this should be ok. Do you observe any logs if you leave them streamed to stderr (no `-logfile` option) and make `-loglevel:debug`?

**Comment by aamirrad** [comment]
I see debug both on sdterr and file. warnings and errors are not displayed in either outputs.

**Comment by maxlovic** [comment]
Hi @aamirrad,
Can you check the outgoing stream with your monitoring device? You have two UDP entry points in your example. You can potentially loose data there. So if you check that you have a valid data, received via UDP on the stransmit input, and CC issues on UDP output after stransmit on this very machine, that sends UDP, then we can say the losses are related to SRT.
When SRT looses data, it sends a loss report. You will not see it in logs (only if you build SRT with heavy logging enabled), but can catch this with, e.g., Wireshark.
