### ISSUE TITLE
stransmit UDP ports and IPTABLES 

### ISSUE THREAD

**Issue by rmsoto** [Haivision/srt#441]
Hello all,

We were playing with iptables and some servers that we have running with SRT. At the momment we have secured them and write the sentences to allow certain UDP traffic we faced that more UDP ports are used than expected.

> Server:
> stransmit -v -r:30 -s:5 -t:-1 "udp://@224.168.240.70:2070" "srt://:9001?latency=500&maxbw=625000&inputbw=625000"

> Client:
> stransmit -v -r:30 -s:5 -t:-1 "srt://@10.192.1.86:9001?latency=500&maxbw=625000&inputbw=625000" "udp://@224.168.1.1:2250"

We only set up udp port 9001 so we wrote in IPTABLES the next:

> -A INPUT -i eth0 -p udp -m udp --dport 9001 -m comment --comment "SRT_udp" -m state --state NEW,RELATED,ESTABLISHED -j ACCEPT

It didn´t work. But we´ve read something in the deployment guide that if UDP Source Port it´s not specified, it´s something optional, an ephemeral source port will be assigned (between 32768 and 61000)...so we wrote the next rule:

> -A INPUT -i eth0 -p udp -m udp --match multiport --dports 32768:61000 -m comment --comment "SRT_udp" -j ACCEPT

It worked....how do I set up the UDP Source Port...is it only for the SERVER or for both, server and client?

Thanks.

**Comment by jeandube** [comment]
The source port of the server is 9001. The source port of the client is the ephemeral port. Unlike a UDP stream SRT has returned control traffic. I see no option in stransmit to bind the local port of the client but you can use the rendezvous connection mode that will set the source and destination port to the same.

**Comment by ethouris** [comment]
First, keep in mind that SRT uses a "bidirectional UDP channel", not just sending by UDP.

This means that you must open not only the path of sending UDP packets to the given port in this direction, but you must also open the way for sending these packets back (that is, where in the UDP packet's header the SOURCE and TARGET content is reversed).

AFAIK IPTABLES has the ability to trace also the bidirectional UDP channels, that is, when a rule is established in one direction only, it will apply also to "returning packets", just I don't know exactly the syntax.

By opening the "ephemeral port range" you just make it potentially allowed for "any returning packets", but that's rather not the best way stating that you open for potentially any kind of packets, also those that have set this port explicitly.

An alternative solution is to enforce the source (outgoing) port for the connection:

    ... srt://10.192.1.86:9001?port=9005&latency=500 ...

This way you'd know that you should open the 9001 port in the forward direction and 9005 port in the reverse direction.

**Comment by rmsoto** [comment]
Thanks all, I´m going to check all the comments out :-)

Regards!
