### ISSUE TITLE
SRT stream resilience and a possibility of adding SMPTE 2022-7 seamless failover model?  

### ISSUE THREAD

**Issue by Svyatk0** [Haivision/srt#446]
Hey guys, 

This is probably more of a wishful thinking, but what would it take to add a seamless failover model to SRT? Or is such an option already achievable? and if so, how? 

Thanks

Svyatko

**Comment by ethouris** [comment]
You mean, redundancy?

Currently there's nothing of this kind available out-of-the-box in SRT.

**Comment by heidabyr** [comment]
Hi Svyatko,

we have evaluated several possibilities and actually did test implementations for two of them. We actually showed seamless failover as a demo at the big broadcast shows (NAB, IBC) already. We are currently discussing the options going forward, but you can expect a solution within this year.

- Marc

**Comment by Svyatk0** [comment]
Thanks. Good news indeed.

**Comment by rmsoto** [comment]
Hello guys! Any update about this feature?

Thanks a lot!

**Comment by MarcCymontkowski** [comment]
Hi, it went a bit slower as expected, but we are in the internal testing stage.

**Comment by maxsharabayko** [comment]
SRT connection bonding functionality is partially available in the current master. Scheduled for v1.5.0 release. Currently supported bonding modes are broadcast and main/backup.

Closing this request. Please refer to #1103 for the roadmap and updates on current status.
