### ISSUE TITLE
Add support for travis-ci

### ISSUE THREAD

**Issue by adamyellen** [Haivision/srt#45]

**Comment by adamyellen** [comment]
@russelltg I hear you might have a travis-ci config file?? :smiley:

**Comment by russelltg** [comment]
Actually funny story, I'm literally working on that right now. I have it working on linux, just getting OSX to work. https://travis-ci.org/russelltg/srt/builds/245918816

**Comment by russelltg** [comment]
(queue times for OSX are really long so it takes a while to tweak)

**Comment by russelltg** [comment]
This can be closed once somebody who's a org member logs into travis and enables this repository

**Comment by adamyellen** [comment]
Build is already in-progress: https://travis-ci.org/Haivision/srt

Thank you very much @russelltg!
