### ISSUE TITLE
Contains unredistributable MSVC stdint.h header

### ISSUE THREAD

**Issue by jcowgill** [Haivision/srt#453]
This file:
https://github.com/Haivision/srt/blob/master/common/win/stdint.h

Contains this license notice at the bottom:
```
/*
 * Copyright (c) 1992-2009 by P.J. Plauger.  ALL RIGHTS RESERVED.
 * Consult your license regarding permissions and restrictions.
V5.20:0009 */
```

This is one of the notices used by headers supplied with MSVC, and in my research this file appears to be almost identical to the copy of the header shipped with at least MSVC 2010. These headers are not free software and cannot be redistributed without infringing copyright. Please remove this file. It would also be nice to remove the file from git history as well (so that hosting a public clone of this repository is legal), but that's obviously much more complex.

**Comment by ethouris** [comment]
#454 submitted to fix.

That was a smart move by P. J. Plauger. Place the copyright at the end so that no one will notice. :)

**Comment by alanbirtles** [comment]
I've made a pull request to fix the install
