### ISSUE TITLE
Issue SRT Transmit of MPEG2TS input and Receive and Playback with VLC 3.04 

### ISSUE THREAD

**Issue by sivarajendranaidu** [Haivision/srt#461]
I took the latest source from [https://github.com/Haivision/srt.git] and build it on centos7 
I am trying to use the SRT for transmitting an input MPEG2TS (H.264 Video and AAC audio) file based.

First I tried to use **stransmit**; I got the following error:
[siva@localhost srt]$ ./stransmit file://home/siva/stream/fifo.ts  srt://192.168.159.135:1234/?mode=server
Media path: 'file://home/siva/stream/fifo.ts' --> 'srt://192.168.159.135:1234/?mode=server'
Unsupported source type

Next I tried to use **srt-file-transmit file**
[siva@localhost srt]$ ./srt-file-transmit file:///home/stream/fifo.ts  srt://192.168.159.135:1234/?mode=server
Target connected (listener)
File sent
Buffers flushed
16:52:13.975579/SRT:RcvQ:worker!!FATAL!!: SRT.c: CChannel reported ERROR DURING TRANSMISSION - IPE. INTERRUPTING worker anyway.

Tired to playback using VLC Player V 3.0.4
Few frames are playback with macro blocks and stopped.

Please find the screen shots version, playback and SRT configurations attached.
![playback_screen](https://user-images.githubusercontent.com/25329744/45881383-a1c5be00-bdc8-11e8-92d9-7455edf58139.jpg)
![vlc_srt_configurations](https://user-images.githubusercontent.com/25329744/45881385-a1c5be00-bdc8-11e8-9fd1-afb2beae84a1.jpg)
![vlc_version](https://user-images.githubusercontent.com/25329744/45881386-a1c5be00-bdc8-11e8-8702-b54e37755094.jpg)

Please provide your inputs

**Comment by sivarajendranaidu** [comment]
Thanks a lot.  Sending UDP packets of 1316 size solved this issue.
I notice around 3-4 seconds from ffmpeg to VLC playback. Is there any params to fine tune the same.
Please provide your inputs.

**Comment by ethouris** [comment]
If you test it on a local cable network (you should not have any packet loss on UDP, unless enforced), you should get the same when you stream from ffmpeg to VLC over UDP. This should give you the best results you can expect from so built pipeline - just to have idea what you can count on.

**Comment by sivarajendranaidu** [comment]
With your recommendation I was able to solve the issue streaming with stransmit and playback with VLC by Sending UDP packets of 1316 size in ffmpeg.
I notice around 3-4 seconds latency from ffmpeg to VLC playback. Is there any params to fine tune this latency.
Please provide your inputs

**Comment by ethouris** [comment]
It's hard to speak about any "delay" when you stream from a file - as it's hard to state as to whether really ffmpeg is pre-buffering the file in order to have idea about the required bitrate and therefore time gaps between sent UDP packets (but really, it can determine it quickly after the first few frames, which takes less than 0.5s of the stream) or simply the file reading itself is delayed by some other reason.

Anyway, as in this mode you can observe this delay as well, it simply means that it's not caused anyhow by SRT.

**Comment by garybruckheimer** [comment]
Try
1) ?pkt_size=1316 on Sever
2) Disable for a test Audio
3) Increase Latency > 1500ms 
4) Test with native UDP from A->B and see if its the same

Let me know if one point from 1-4 helps.

**Comment by ethouris** [comment]
Anyway, first two basic rules for making a live stream from a file and then sending it over SRT:

1. For ffmpeg `-re` option is required
2. If ffmpeg streams to UDP, `pkt_size=1316` parameter in the URI is required

**Comment by maxlovic** [comment]
Hi @sivarajendranaidu What is the status of this? Can be closed?

**Comment by sivarajendranaidu** [comment]
Yes I am good and hence this can be closed.
