### ISSUE TITLE
Cross Compilation uClinux

### ISSUE THREAD

**Issue by hacktarus13** [Haivision/srt#462]
Hi/Hello,

no way to cross compile libSRT, no data/commentary to find a way to compile it.
We want to use ffmpeg on embedded device (router/modem) to link/broadcast an IP stream (H264/H265) between to 2 points:

IP stream ==> | Router with ffmpeg | ==>  WEB  ==> | Receiver/Router with ffmpeg | ==> TV/Receiver

My embedded device are uCLinux OS on ARM chipset without MMU

Thanks in advance

**Comment by maxlovic** [comment]
Closing as abandoned.
