### ISSUE TITLE
File target in srt-live-transmit not working

### ISSUE THREAD

**Issue by jorgegonzalezf** [Haivision/srt#473]
Trying to save to file a srt stream:

server:
/srt_sources/srt/srt-live-transmit -v -r:30 -s:5 -t:-1 "udp://@224.168.208.175:2175" "srt://:9001?latency=3000&maxbw=12750000&inputbw=12750000"
Media path: 'udp://@224.168.208.175:2175' --> 'srt://:9001?latency=3000&maxbw=12750000&inputbw=12750000'
Multicast: home address: INADDR_ANY:2175
Multicast(POSIX): will bind to IGMP address: 224.168.208.175
Parameters:
	inputbw = '12750000'
	latency = '3000'
	maxbw = '12750000'
Opening SRT target listener on :9001

Binding a server on :9001 ...
 listen...

client:
/srt_sources/srt/srt-live-transmit -v -r:30 -s:5 -t:-1 "srt://192.168.208.71:9001?latency=3000&maxbw=12750000&inputbw=12750000" "file:///mnt/test_srt.ts"
Media path: 'srt://192.168.208.71:9001?latency=3000&maxbw=12750000&inputbw=12750000' --> 'file:///mnt/test_srt.ts'
Parameters:
	inputbw = '12750000'
	latency = '3000'
	maxbw = '12750000'
Opening SRT source caller on 192.168.208.71:9001

Connecting to 192.168.208.71:9001

NOTE: SRT/post::inputbw=12750000

Unsupported target type 
SrtCommon: DESTROYING CONNECTION, closing sockets (rt%254515457 ls%-1)...

SrtCommon: ... done.

The error is "Unsupported target type".
This works with previous libsrt.so.1.2.2 but not in current libsrt.so.1.3.1.
Is there a way to use medium file as a target with srt-live_transmit?

**Comment by ethouris** [comment]
This is now not implemented.

But you should be able to emulate it by using `file://con` as output specification, which sends the stream to stdout. Then you can redirect it to a file.

**Comment by heidabyr** [comment]
To be clear, srt-live-transmit uses the live mode in SRT, which has been designed for low latency real-time streaming with content such as MPEG-TS. For file related workflows, there are tools available and the API is used in slightly different ways.

This is neither a bug, nor an actual limitation. just not the use case for the live transmit command line tool.

**Comment by heidabyr** [comment]
Please write to stdout and redirect the live stream to a named pipe. In my test I am sending a live stream from our Makito X encoder with Listener output.

The SRT receiver container process would do something like this:
mkfifo ThisIsMyPipe
srt-live-transmit "srt://10.129.10.36:8444?latency=200" "file://con" > ThisIsMyPipe

The transcoder process then reads from the named pipe. I tried this with VLC and it worked fine for me:
vlc - < /Path/To/File/ThisIsMyPipe

I hope this helps!

**Comment by jorgegonzalezf** [comment]
I tried it with  "file://con" > and worked. Thanks!

**Comment by jorgegonzalezf** [comment]
Hi, I noticed that in version 1.3.2  "srt://10.129.10.36:8444?latency=200" "file://con" > ThisIsMyPipe it does not work any more as with version 1.3.1. How can you use now stdout or stdin with "file://con" and srt-live-transmit?

Thanks

**Comment by maxlovic** [comment]
@jorgegonzalezf Please specify the exact commit you are testing.
`file://con` should work as before. If it does not, it should be fixed.
