### ISSUE TITLE
Problem with Error logs

### ISSUE THREAD

**Issue by prabh13singh** [Haivision/srt#492]
LOGC(tslog.Debug) << self->CONID() << "TSBPD:DROPSEQ: up to seq=" << CSeqNo::decseq(skiptoseqno)
                << " (" << seqlen << " packets) playable at " << logging::FormatTime(tsbpdtime) << " delayed "
                << (timediff/1000) << "." << (timediff%1000) << " ms" ;
I replaced Debug with error but it's only getting written to the file when I enable any other debug statement or kill the application.
When the application is running and I have only this log enabled, the logs start accumulating in some buffer/pipe and only gets written to the file when I kill the file.

**Comment by prabh13singh** [comment]
I solved it. Actually the buffer is storing it and not flushing it. Added fflush.
inline void LogDispatcher::SendLogLine(const char* file, int line, const std::string& area, const std::string& msg)
{
    src_config->lock();
    if ( src_config->loghandler_fn )
    {
        (*src_config->loghandler_fn)(src_config->loghandler_opaque, int(level), file, line, area.c_str(), msg.c_str());
    }
    else if ( src_config->log_stream )
    {
        (*src_config->log_stream) << msg;
        _(*src_config->log_stream).flush();_
    }
    src_config->unlock();
}

**Comment by ethouris** [comment]
Right. I completely forgot that streams usually get lump-buffered, not line-buffered. It should be ok to flush it here because it is important that the flushing happen not more often as once per line. Could you please make a PR out of it?
