### ISSUE TITLE
how to compile SRT library for Android on Mac?

### ISSUE THREAD

**Issue by jseun112** [Haivision/srt#497]
Hi all.
How can I compile SRT Library for Android on Mac?

When I compile on my Mac, compile error occured as following.
srt/srtcore/common.cpp:62:16: fatal error: 'mach/mach_time.h' file not found
      #include <mach/mach_time.h>

I don't know why the compiler can't find that header file such a system header files.
Can anyone help me?

and I wonder that it's possible to cross compile android on Mac.

**Comment by fallenhaivision** [comment]
Hi,
It is possible to cross compile SRT for Android on MacOS. Have you taken a look at ‎⁨docs⁩/⁨Android⁩/Compiling.md. mach/mach_time.h is only include if you are compiling for OSX/iOS/tvOS.

**Comment by Edward-Wu** [comment]
hi jseun112 and fallenhaivision,
I compile the SRT library for Android on MAC following the docs/Android/Compiling.md. But get the same error info :
srt/srtcore/common.cpp:62:16: fatal error: 'mach/mach_time.h' file not found
#include <mach/mach_time.h>
 Can you tell me how to avoid this error?

**Comment by Edward-Wu** [comment]
In mkall file, there is a following line:
toolchain=$NDK/toolchains/llvm/prebuilt/linux-x86_64

I download the NDK r19, but there's no linux-x86_64 folder in prebuilt folder, only darwin-x86_64 folder. so I change the linux-x86_64 to darwin-x86_64, as following :
toolchain=$NDK/toolchains/llvm/prebuilt/darwin-x86_64
 
after exec /bin/bash mkall > build.log, I get the error info:
srt/srtcore/common.cpp:62:16: fatal error: 'mach/mach_time.h' file not found
#include <mach/mach_time.h>

Can you help me ?

**Comment by jseun112** [comment]
Edward, 
Finally, I couldn't compile the SRT library on MAC.
So I compiled that on my other Windows PC. it does well now.
But I did not try the compiling on MAC after that. Sorry, I can't help you.

**Comment by fallenhaivision** [comment]
Edward,
We need to be able to tell the cmake scripts that we are compile for Android and not OSX. I'm looking into creating a android.cmake file similar to iOS.cmake.

**Comment by tobisweb** [comment]
@fallenhaivision 
Hi fallenhaivision, did you continue to work on creating a android.cmake file? I am trying to compile for Android on OSX.
