### ISSUE TITLE
relative DT_RUNPATH is a security problem

### ISSUE THREAD

**Issue by candrews** [Haivision/srt#499]
You really should not have relative DT_RUNPATHs as they are a security problem.

Can you please avoid relative rpaths, or at least make a cmake option that avoids them?

The problem is at:
https://github.com/Haivision/srt/blob/v1.3.1/CMakeLists.txt#L657

> relative RPATH (i.e. foo.so rather than /usr/lib/foo.so) can go quite wrong: your user might be running from a working directory (Eg. /tmp) that's subject to attacker control who could plant a malicious version of /tmp/foo.so.

-- https://security.stackexchange.com/questions/161799/why-does-checksec-sh-highlight-rpath-and-runpath-as-security-issues

Thanks!

**Comment by maxlovic** [comment]
`-rpath,../lib` was first introduced in commit baaaa5a9d775ddffe3c76ffa67df0de23ada53ac, referencing a CMake recommendation.
```
set(FORCE_RPATH LINK_FLAGS -Wl,-rpath,../lib BUILD_WITH_INSTALL_RPATH TRUE INSTALL_RPATH_USE_LINK_PATH TRUE) 
```
Then #244 adds `-rpath,.` and `-rpath,../lib64`, followed by the discussion in #238.

Finally, in #323 the hardcoded `../lib` and `../lib64` are replaced with `../${CMAKE_INSTALL_LIBDIR}`.

Generally, the applications are only to show the example usage of SRT. OTOH, they are frequently used as is. This looks like a potential security breach and should be either deleted or tuned off for release builds.
The SRT library has a static linkage by default, Other libraries (SSL, crypto, etc.) are in the system path.
One more solution: `if (LINUX)` -> `if (LINUX) AND NOT (srt_libspec_static)`
