### ISSUE TITLE
Keep listener in listen mode

### ISSUE THREAD

**Issue by decosteri** [Haivision/srt#506]
Hi i have a test setup that de caller is sending an rtsp to srt and listener forwarding to rtp.
When the caller stops sending and resend after a while I need to restart the listener command.
Is there a way to keep the listener in constant listen mode?

ffmpeg -i rtsp://184.72.239.149/vod/mp4:BigBuckBunny_175k.mov -f mpegts srt://127.0.0.1:50000?mode=caller

ffmpeg -i srt://:50000?mode=listener -f rtp_mpegts rtp://localhost:4000

Thanks

**Comment by ethouris** [comment]
That's rather kinda the problem how this is implemented in ffmpeg - it probably just waits for a new connection, then turns into reading from this connection, when disconnected, the command is interrupted.

The SRT listener is fully capable of handling multiple connections at a time, just the same way as TCP does. You can try to use the SRT tool for live stream flipping `srt-live-transmit` (part of this package) and push it to ffmpeg through a pipe. Try the second command as:

`srt-live-transmit srt://::50000 file://con | ffmpeg -i - -f (...)`

AFAIR `srt-live-transmit` should be capable of handling connecting and disconnecting callers.

**Comment by decosteri** [comment]
Sorry for the late reply,
Tested it today an this is working for me using the srt-live-transmit
Thanks for your help
