### ISSUE TITLE
SRTS_BROKEN can be return from getStatus when connecting

### ISSUE THREAD

**Issue by fallenhaivision** [Haivision/srt#508]
In api.cpp::CUDTUnited::getStatus there's a line to check if connecting has timed out
   // Connecting timed out
   if ((s->m_Status == SRTS_CONNECTING) && !s->m_pUDT->m_bConnecting)
       return SRTS_BROKEN;

In core.cpp::CUDT::postConnect "m_bConnecting" can go to false before "m_Status" changes from SRTS_CONNECTING to SRTS_CONNECTED when s_UDTUnited.connect_complete is called a few lines down.
If we switch threads between those two points and CUDTUnited::getStatus is called, it will return SRTS_BROKEN.

**Comment by maxlovic** [comment]
Like @fallenhaivision wrote, the `CUDTUnited::getStatus(...)` has the following condition:
```
SRT_SOCKSTATUS CUDTUnited::getStatus(const SRTSOCKET u)
{
    // (…)

    // CUDTSocket* s;
    // Connecting timed out
    if ((s->m_Status == SRTS_CONNECTING) && !s->m_pUDT->m_bConnecting)
        return SRTS_BROKEN;
```
`s->m_pUDT->m_bConnecting` is set to `false` several steps before the `CUDTSocket::m_Status` is changed to `SRTS_CONNECTED` in `s_UDTUnited.connect_complete(m_SocketID);`
Therefore, the CUDTUnited::getStatus(...) function can return `SRTS_BROKEN`, if it is called inbetween those status changes, although it should return `SRTS_CONNECTING` instead.
```
EConnectStatus CUDT::postConnect(const CPacket& response, bool rendezvous, CUDTException* eout, bool synchro)
{
    // (...)

    // And, I am connected too.
    m_bConnecting = false;
    m_bConnected = true;

   // (...)

   // acknowledge the management module.
   // !Here we change CUDTSocket m_Status to SRTS_CONNECTED
   s_UDTUnited.connect_complete(m_SocketID);
```

**Comment by maxlovic** [comment]
### Why does the `getStatus(...)` has the additional check for `m_bConnecting`?
Let's take a look at the `CUDTUnited::getStatus()`:
```
SRT_SOCKSTATUS CUDTUnited::getStatus(const SRTSOCKET u)
{
    // (…)

    // CUDTSocket* s;
    // Connecting timed out
    if ((s->m_Status == SRTS_CONNECTING) && !s->m_pUDT->m_bConnecting)
        return SRTS_BROKEN;

    return s->m_Status;
}
```
In general case `CUDTSocket::m_Status` is what should be returned. But there is only one case where the above conditional check is needed. `CRendezvousQueue::updateConnStatus()` sets `m_pUDT->m_bConnecting = false;` on TTL expiry (connection timeout). But the status of `CUDTSocket` remains `SRTS_CONNECTING` until the connection is closed.
Basically the `CUDTSocket` can be accessed from the `CRendezvousQueue` with:
`CUDTSocket *s = CUDT::s_UDTUnited.locate(i->m_pUDT->socketID());`
and its status can be changed. But that does not seem to be the correct way to fix the issue.

### Restrictions for status changing
If the `getStatus()` function remains unchanged, checking both `m_bConnecting` and `m_Status`, then the following restrictions have to be followed.

1.  `s->m_pUDT->m_bConnecting = true` must happen before `s->m_Status = SRTS_CONNECTING`.
2. `s->m_Status = SRTS_CONNECTED` must happen before `s->m_pUDT->m_bConnecting = false`.

### The existing issues are:
1️⃣ ❕ `CUDTUnited::connect()` sets `s->m_Status = SRTS_CONNECTING;`, then calls `s->m_pUDT->startConnect(name, forced_isn);`, that sets `m_bConnecting = true;`. This violates the above restriction no. 1.

2️⃣ ❕  The `CUDT::postConnect` behavior, described in the previous comment, violates the restriction no. 2.

3️⃣ ❔  Probably if `s->m_pUDT->m_bConnecting`, then `return SRTS_CONNECTING`.
