### ISSUE TITLE
[feature] Specify different remote and local ports for rendezvous connections in stransmit

### ISSUE THREAD

**Issue by russelltg** [Haivision/srt#526]
Related: #369 

It seems useful to be able to specify different port numbers for the local and remote while negotiating rendezvous connections.

For example, the public port (on the router) may not match the port on the machine (is is already mapped to a different local ip, etc), so it would be difficult to configure. 

Additionally, it allows for local testing of rendezvous connections (my personal interest). 

If there is interest in such a feature, I am willing to implement it.

One possible syntax could be `stransmit srt://hello.com:3333?mode=rendezvous?local_port=4444 ...`, where this would bind to port 4444 but connect to port 3333.

This syntax could also be added for callers.

**Comment by ethouris** [comment]
I haven't tracked down exactly this requirement that the port number should be the same on both sides for rendezvous. For what I know about the rendezvous process, there should be no real obstacle to use different ports per site in rendezvous. The parameter you designated as `local_port` already exists and it's simply `port`, although the only current use of it is in caller mode to specify the local outgoing port, but it does what you want: sets the port to which the local UDP socket is bound.

But to be sure that this can be used safely, I need to make more investigation.

**Comment by maxsharabayko** [comment]
It looks like this was resolved in #1202, that removed extra checks for local and remote ports in rendezvous to be the same. 
Now the following syntax can be used:
`srt-live-transmit srt://hello.com:3333?mode=rendezvous?port=4444`, where this would bind to port 4444 but connect to port 3333.

**Comment by maxsharabayko** [comment]
Waiting for #1198 which fix rendezvous handling in URI parsing.

**Comment by maxsharabayko** [comment]
#1198 is merged. Closing this request.
@russelltg Please don't hesitate to reopen in case something was missed.
