### ISSUE TITLE
SRT Client on Andorid maximum packet size 112 bytes

### ISSUE THREAD

**Issue by JamesGibo** [Haivision/srt#534]
Hi,

I have built SRT for Android NDK and loaded it as a library. 
The library correctly connects to the SRT Sender and starts receiving data, but I am not receiving the correct amount of data. 
The first packet is received correctly, but then for the subsequent packets I only receiving a fraction of the send data, for example:
```
35 Bytes Sent    ->  35 Bytes Recv
53000 Bytes Sent  ->  638 Bytes Recv
22500 Bytes Sent  ->  112 Bytes Recv
22800 Bytes Sent  ->  112 Bytes Recv
17000 Bytes Sent  ->  112 Bytes Recv
```

After the first two packets i constantly receive just 112 Bytes per call the to the srt_recv function.

Here is the read call
```
extern "C"
JNIEXPORT jint JNICALL
Java_com_example_srttest_MainActivity_getData(JNIEnv* env, jobject, jbyteArray outData, jint offset, jint outSize)
{
    if (m_client_sock)
    {
        jbyte* buffer = env->GetByteArrayElements(outData, NULL);
        int bytesRead = srt_recv(m_client_sock, (char*)&(buffer[offset]), outSize);
        env->ReleaseByteArrayElements(outData, buffer, 0);
        LOGD("Bytes Read: %d", bytesRead);
        return bytesRead;
    }
    return 0;
}
```
I have tried running this code on a separate thread but this didn't help. 
I have an almost identical piece of software built for Mac OS, that receives the data correctly. 

Any advice on how to debug this problem further, would be much appreciated. 

Thanks

**Comment by maxlovic** [comment]
Hi @JamesGibo,
Please specify the version of SRT you use.

Are you testing this on the target device or in an emulator?
Try to set a debug log level `srt_setloglevel(7)`.
Even more logging info can be retrieved with HEAVY_LOGGING enabled (`configure --enable_heavy_loggging` or with a CMake option `-DENABLE_HEAVY_LOGGING=ON`).

Might be that the system does not have enough memory for receiving data. But this is just a guess.

**Comment by JamesGibo** [comment]
Thanks for your response.

I am using srt_version=v1.3.0
Using a Samsung Galaxy S8, so should have enough memory to receive the 5MBits/s stream.  

I will increasing the logging level and get back to you.

**Comment by maxlovic** [comment]
@JamesGibo, try to use `v1.3.2-rc.0`.

**Comment by JamesGibo** [comment]
Hi Maxim, 
Thanks for your help, this turned out to be an issue with the cloud provider I was using, not an issue with SRT. Increasing the logging level didn't help as I wasn't able to the log messages from SRT with the Android debugger. 

I also tried to build version `v1.3.2-rc.0` and `v1.3.1` for Android using my Docker build system, both failed due to type errors.
```
/Android/srt/apps/transmitmedia.cpp:911:39: error: member reference base type '__be32' (aka 'unsigned int') is not a structure or union
                mreq_ssm.imr_multiaddr.s_addr = sadr.sin_addr.s_addr;
``` 

I will close this issue and when I get chance to investigate the build error I will raise another issue if required. 

Thanks

**Comment by maxlovic** [comment]
Thanks for the feedback, James. Looking forward for the details on those build errors.

**Comment by maxlovic** [comment]
@JamesGibo, my colleagues provided the following information regarding the Android build issues you might be facing.
Can you try to place the following lines into the code and check whether if it fixes the issues? If it does, we would appreciate if you could make a PR for that.

```
#ifdef ANDROID
//
// Android defines imr_multiaddr, imr_sourceaddr, and imr_interface
// in struct ip_mreq_source as __be32 instead of struct in_addr as linux does.
// Handle this difference with these macros
//
#define IMR_multiaddr   imr_multiaddr
#define IMR_interface   imr_interface
#define IMR_sourceaddr  imr_sourceaddr
#else
#define IMR_multiaddr   imr_multiaddr.s_addr
#define IMR_interface   imr_interface.s_addr
#define IMR_sourceaddr  imr_sourceaddr.s_addr
#endif
```

**Comment by JamesGibo** [comment]
Thanks, will have a look into this.

**Comment by maxlovic** [comment]
Hi @JamesGibo,
Do you have any updates regarding the building issue on Android you had discovered?

**Comment by JamesGibo** [comment]
No not had chance to look at it in any detail yet, hopefully will have some time towards the end of next week.
