### ISSUE TITLE
Slack invite link in README fails

### ISSUE THREAD

**Issue by stevendesu** [Haivision/srt#543]
When I try to join Slack, I get the following:

![screenshot from 2019-01-28 11-05-40](https://user-images.githubusercontent.com/1384974/51848973-b2dd8900-22ec-11e9-9731-3f720d2f03c6.png)

Any assistance would be appreciated

**Comment by maxlovic** [comment]
Hi @stevendesu.
The SRT slack channel is currently for SRT alliance members only. So this link is invalid, we will delete it.
If you are the member and you want to join the channel, please let us know.

**Comment by wimsweldens** [comment]
@maxsharabayko : Kiswe is an SRT alliance member. Can I get an invite to the slack channel? wim.sweldens@kiswe.com - thanks much.

**Comment by maxsharabayko** [comment]
@wimsweldens Sure, just use [this link](https://slackin-srtalliance.azurewebsites.net/).

**Comment by MauroGlookast** [comment]
The company I work for is SRT Alliance member. How can I get an invite to the slack channel? Thank you guys!

**Comment by mbakholdina** [comment]
@MauroGlookast Please follow [this link](https://slackin-srtalliance.azurewebsites.net/) to get an invite. It's done automatically and everybody is welcome to join.
