### ISSUE TITLE
Cross Compiling for ARM

### ISSUE THREAD

**Issue by jeremygerdes** [Haivision/srt#547]
I am having troubles determining exactly what to do to cross compile srt for ARM.  I tried creating a .cmake file and placing it on the scripts folder then using the --cmake-toolchain-file option for .configure  When I do that the output from .configure says "CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_TOOLCHAIN_FILE

**Comment by rndi** [comment]
Tried exactly that just now, worked just fine. My exact commands were:
```
./configure --cmake-toolchain-file=./toolchain.cmake --enable-c++11=FALSE
make
```
the contents of `toolchain.cmake` were:
```
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(tools /opt/CodeSourcery/Sourcery_G++_Lite)
set(CMAKE_FIND_ROOT_PATH
   ${tools}/arm-none-linux-gnueabi/;
   ${tools}/arm-none-linux-gnueabi/libc)

set(CMAKE_C_COMPILER ${tools}/bin/arm-none-linux-gnueabi-gcc)
set(CMAKE_CXX_COMPILER ${tools}/bin/arm-none-linux-gnueabi-g++)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
```
