### ISSUE TITLE
Generate logs and display them

### ISSUE THREAD

**Issue by thepocho** [Haivision/srt#55]
Dear,

 Im telling you that Im building an html with php to be able to control the ./stransmit sender and receiver. 
What I can not do is get the logs that the ./stransmit delivers and display them in the html or php. 
Would you have any ideas that could help me? 

Greetings and thanks
Martin

**Comment by nitrat7** [comment]
have a look at supervisor, currently using it for monitoring processes on gateways..
http://supervisord.org
e.g.
__
[program:routex]
command=/usr/local/bin/stransmit srt://:6000 srt://gl-srt-test.japanwest.cloudapp.azure.com:6100 -r:10 -s:10
autostart=true
autorestart=true
redirect_stderr=True
__
or using X-stransmit-processes as routes...
using redirect messages for parsing stats in supervisor - nice 👍 

Maybe I'll prepare demo soon for routing UDP-traffic from A-B-C for _elemental_ output/ingest UDP for interconnecting securely / fast & reliable encoders over different locations.

**Comment by thepocho** [comment]
Thanks for the quick reply.

But I was referring to the logs delivered by the app / stransmit.cpp.
This is the same as delivery by console, see it in html


.cout << "======= SRT STATS: sid=" << sid << endl;
 cout << "PACKETS SENT: " << mon.pktSent << " RECEIVED: " << mon.pktRecv << endl;
 cout << "LOST PKT SENT: " << mon.pktSndLoss << " RECEIVED: " << mon.pktRcvLoss << endl;
    cout << "REXMIT SENT: " << mon.pktRetrans << " RECEIVED: " << mon.pktRcvRetrans << endl;
    cout << "RATE SENDING: " << mon.mbpsSendRate << " RECEIVING: " << mon.mbpsRecvRate << endl;
    cout << "BELATED RECEIVED: " << mon.pktRcvBelated << " AVG TIME: " << mon.pktRcvAvgBelatedTime << endl;
    cout << "REORDER DISTANCE: " << mon.pktReorderDistance << endl;
    cout << "WINDOW: FLOW: " << mon.pktFlowWindow << " CONGESTION: " << mon.pktCongestionWindow << " FLIGHT: " << mon.pktFlightSize << endl;
    cout << "RTT: " << mon.msRTT << "ms  BANDWIDTH: " << mon.mbpsBandwidth << "Mb/s\n";
    cout << "BUFFERLEFT: SND: " << mon.byteAvailSndBuf << " RCV: " << mon.byteAvailRcvBuf << endl;

Thanks
Martin

**Comment by ethouris** [comment]
If there's some format that would be preferred better, it can be easily added as an alternative format controlled by an option.

**Comment by thepocho** [comment]
Dear,

Sorry for the delay, try to add the following code to be able to have the logs in a file and to be able to read them from a php.
But the application randomly does a "stack smashing detected".
Why could this be generated?

This is the code that you add:

// Start added code

Ofstream logout1;
Logout1.open ("/ opt / srt / logs")
Logout1 << "Srt Packets Send:" << mon.pktRecv << endl;
Logout1 << "RTT:" << mon.msRTT << "ms" << endl;
Logout1 << "Estimated Bandwith:" << mon.mbpsBandwith << "Mb / s" << endl;
Logout1.close ();

// End added code

Regards,
Martin

**Comment by ethouris** [comment]
What do you think about having kinda template like this:

SRT STATS: sid=%sid
Sent packets: %pktRecv
RTT: %RTT
Estimated Bandwidth: %mbpsBandwidth

The current form of `PrintSrtStats` can be turned into a template so that this can be used as a default, and with an extra option a file with an alternative template can be supplied.

**Comment by mbakholdina** [comment]
Hi @thepocho , let me share the script I wrote for SRT statistics visualization and analysis with you: [srt-stats-plotting](https://github.com/mbakholdina/srt-stats-plotting). It's written in Python with the usage of [bokeh](https://bokeh.org/) library. The output is `html` file with all the statistics plots. The statistics should be collected in `csv` format.

Have you found the solution for your task? Is my understanding right that you wanted to output the statistics from the application in real time?

**Comment by maxsharabayko** [comment]
### TODO
- [ ] Add template based stats output in srt-live-transmit

Provide a template definition file like
```
SRT STATS: sid=%sid
Sent packets: %pktRecv
RTT: %RTT
Estimated Bandwidth: %mbpsBandwidth
```
`srt-live-transmit` could use it to generate a statistics log.

It is a good idea, but probably not something that would be added to srt-live-transmit.
It is intended to be a sample application. It already provides CSV and JSON outputs for stats.
This looks like customization. Closing.
