### ISSUE TITLE
udp igmpv3 source

### ISSUE THREAD

**Issue by Zulianino** [Haivision/srt#557]
Hi,

im trying to use stransmit to read a multicast igmpv3 mpts and send it over srt.
I'm using this string: stransmit udp://ip@multicast:5000?adapter=ipofinterface srt://:1234
app starts with correct parameters, otherwise i cannot see any kind of packet sent or lost.

If i join the multicast on the same machina with another app it is joined correctly.

What is wrong?

Thanks

**Comment by ethouris** [comment]
Please specify again what exactly you are using in places of `ip`, `multicast` and `ipofinterface`.

The syntax for using multicast group for reading is `udp://@multicastaddr:port`, with `multicastaddr` resolved if passed by name.

In the latest version the multicast IP address should be recognized by the bits in the IP address, so the `@` before the name is superfluous.

Please try using stransmit first from udp to udp (unicast this time) and try playing it.

**Comment by Zulianino** [comment]
unicast is working well.
I have an answer from haivison that igmpv3 SSM is not yet supported
By the way the correct url is udp://SSMip@multicast:port

**Comment by fatpelt** [comment]
ssm is supported. use the "source" parameter on the src.  see PR #374
