### ISSUE TITLE
tsppd wrap period begins on Win10 x64

### ISSUE THREAD

**Issue by vidanio** [Haivision/srt#561]
SRT version 1.3.2-rc0 on Windows 10 x64.
Natively compiled apps.

Commandline used:
srt-live-transmit.exe udp://:2000 srt://wowzaserver_out -s:200

Always after 1631 seconds after starting:

`
08:13:43.192748 D: SRT.t: tsppd wrap period begins
......
8460 bytes lost, 0 bytes sent, 960759712 bytes received
......
258312 bytes lost, 2398128 bytes sent, 963407692 bytes received
......
08:14:43.167851 D: SRT.t: tsppd wrap period ends
.........
08:15:01.272488*E: SRT.c: %503954449:No room to store incoming packet: offset=1 avail=1 ack.seq=672529499 pkt.seq=672529500 rcv-remain=8190
...... (stream disconnects)
`
This is only reproducible in the same computer.
The same binary in another Win10 x64 box, works w/o notice 24 hours long.
UDP source is the same binary ffmpeg.exe on both computers.

**Comment by ethouris** [comment]
Well, that's an interesting case, I don't know where to start so far, but could you, for starters, add the following line in `CUDT::open` function (core.cpp file), after
```
   m_ullCPUFrequency = CTimer::getCPUFrequency();
```
This one:
```
   LOGC(mglog.Note, log << "CPU Frequency: " << m_ullCPUFrequency);
```
With enabled logging and the default log settings you should see this log after running. Please run this on both computers, this will give us at least some hook point.
