### ISSUE TITLE
processor choice for SRT based system : dual core or Quad core

### ISSUE THREAD

**Issue by mks75** [Haivision/srt#564]
Hi,
For SRT process, which is a better choice:
[1] Intel Celeron 3965U @2.2Ghz - dual core (benchmark - 2411)
[2] Intel J1900 @1.99GHz - Quad core (Benchmark - 1848)

Thanks
MKS

**Comment by maxlovic** [comment]
@mks75,
Hard to tell. I can only suggest, that for one process (instance) of SRT the second option (Intel J1900) might be better. SRT intensively uses 2 threads internally. The rest depends on the way you feed in and read out the data.
SRT does not consume a lot of CPU power, so you should not see a differencee in a regular usage scenario.

Given that the frequency is almost the same, probably having four threads is beneficial. It can let you handle some pre- or postprocessing of data in parallel. But again, it is only my suggestion. **Do not consider this as a guide to action.**

**Comment by ethouris** [comment]
Just mind that SRT uses 2 threads PER MULTIPLEXER. The "caller sockets" use one multiplexer per socket, while a listener socket with all accepted sockets out of it all use one common multiplexer. Although that the "amount of work" done in both cases depends on the number of data being passed through, so with the same bitrate, 3 simultaneous transmissions on 3 separate sockets will take more-less the same amount of CPU regardless of the number of threads.

**Comment by mks75** [comment]
Thanks @maxlovic and @ethouris 
This is very helpful.

Thanks
mks75
