### ISSUE TITLE
warning: catching polymorphic type ‘class std::invalid_argument’ by value [-Wcatch-value=]  catch (std::invalid_argument)

### ISSUE THREAD

**Issue by stoyanovgeorge** [Haivision/srt#568]
I got this error during the `srt-live-transmit` compilation on Ubuntu 18.10 running kernel: `4.18.0-15-generic` it is just a warning and after all the package managed to compile. This is an excerpt of the warning: 
```
Scanning dependencies of target srt-live-transmit
[ 97%] Building CXX object CMakeFiles/srt-live-transmit.dir/apps/srt-live-transmit.cpp.o
/home/gstoyanov/srt/apps/srt-live-transmit.cpp: In function ‘int main(int, char**)’:
/home/gstoyanov/srt/apps/srt-live-transmit.cpp:229:17: warning: catching polymorphic type ‘class std::invalid_argument’ by value [-Wcatch-value=]
     catch (std::invalid_argument)
                 ^~~~~~~~~~~~~~~~
[100%] Linking CXX executable srt-live-transmit
```

**Comment by stoyanovgeorge** [comment]
**[OFFTOPIC]** Is there a real difference between `srt-live-transmit` and `stransmit`? Would be great if you can also insert some version tag on the program so that I know which version of the SRT library I am using.

**Comment by maxlovic** [comment]
Thanks, @stoyanovgeorge,
 we need to change it to `catch (std::invalid_argument &)`.

`stransmit` on Linux is just a link to `srt-live-transmit` for legacy usage. On Windows it is just a copy.
