### ISSUE TITLE
SRT installation on Raspbian

### ISSUE THREAD

**Issue by stoyanovgeorge** [Haivision/srt#573]
When you are compiling the SRT package on Raspbian, the `make` command doesn't really put the files into the `/usr/local/bin` directory, because you need `sudo` access to it, so you need to either execute after `make`, `sudo make install` or just copy/symlink the `srt-live-transmit`, `srt-file-transfer`, `stransmit` and `srt-ffplay` manually to `/usr/local/bin/`. It is really not a big issue, but I was thinking that you can update your documentation, it might be useful for other ppl running into the same problem.

**Comment by stoyanovgeorge** [comment]
You need to generate the `ssh_host_ed25519_key` and `ssh_host_rsa_key` files in `/etc/ssh/` directory and to delete the remaining `ssh_host_*key*` files containing the weak cyphers. 
```
cd /etc/ssh
rm ssh_host_*key*
ssh-keygen -t ed25519 -f ssh_host_ed25519_key -N "" < /dev/null
ssh-keygen -t rsa -b 4096 -f ssh_host_rsa_key -N "" < /dev/null
```

The /etc/ssh/moduli file contains prime numbers and generators used by the SSH server for the Diffie-Hellman key exchange. Your current /etc/ssh/moduli is probably not unique. Generating a new file may harden your server. Generating these file might take awhile.

```
ssh-keygen -G moduli-2048.candidates -b 2048
ssh-keygen -T moduli-2048 -f moduli-2048.candidates
cp moduli-2048 /etc/ssh/moduli
rm moduli-2048
```

After all these changes, it is possible to not be able to connect to the server with your private key, if it is not strong enough. So you might need to generate a new one with `ssh-keygen -t rsa -b 4096`.

**Comment by ethouris** [comment]
Looks weird. This what you described is true for every Linux system everywhere.

If you want to do a user preinstallation, use the `--prefix` option in `configure` (turns into `-DCMAKE_INSTALL_PREFIX` in cmake call). By default this prefix is `/usr/local`, which is a generally known default for both autotools and cmake.
