### ISSUE TITLE
srt-file-transmit not working on the master branch

### ISSUE THREAD

**Issue by stoyanovgeorge** [Haivision/srt#582]
I am trying to test the `srt-file-transfer` and it doesn't seem to work for me in all modes (caller, listener, rendezvous). This is rendezvous mode: 
```
$ srt-file-transmit -v file:///home/ubuntu/recordings/test.ts srt://10.88.159.75:6000?mode=rendezvous -loglevel:debug
SOURCE type=file, TARGET type=srt
Extract path '/home/ubuntu/recordings/test.ts': directory=/home/ubuntu/recordings/
filename=test.ts
Parameters:
        mode = 'rendezvous'
Opening SRT target rendezvous on 10.88.159.75:6000

Binding a server on :6000

Connecting to 10.88.159.75:6000

17:14:03.956694/SRT:RcvQ:worker*E: SRT.c: processAsyncConnectRequest: REJECT reported from processRendezvous, not processing further.
17:14:03.956810/SRT:RcvQ:worker*E: SRT.c: RendezvousQueue: processAsyncConnectRequest FAILED. Setting TTL as EXPIRED.
Event with status 6

Target disconnected
SrtCommon: DESTROYING CONNECTION, closing sockets (rt%1058516876 ls%-1)...

SrtCommon: ... done.
```
This is when using listener mode:
```
$ srt-file-transmit -v file:///home/ubuntu/recordings/test.ts srt://:6000 -loglevel:debug                                                             SOURCE type=file, TARGET type=srt
Extract path '/home/ubuntu/recordings/test.ts': directory=/home/ubuntu/recordings filename=test.ts
Parameters:
Opening SRT target listener on :6000

Binding a server on :6000 ...
 listen...

17:19:46.153706/SRT:RcvQ:worker*E: SRT.c: HSREQ/rcv: Agent uses STREAM API, but the Peer declares MESSAGE API. Not compatible transmission type, rejecting.
17:19:46.153826/SRT:RcvQ:worker*E: SRT.c: interpretSrtHandshake: process HSREQ returned unexpected value 0
17:19:46.153876/SRT:RcvQ:worker*E: SRT.c: %66430949:newConnection: connection rejected due to: ACCEPT ERROR
17:19:46.153901/SRT:RcvQ:worker*E: SRT.c: UU:newConnection: rsp(REJECT): 1002
```
And that's for caller: 
```
$ srt-file-transmit -v file:///home/ubuntu/recordings/test.ts srt://10.88.159.75:6000 -loglevel:debug
SOURCE type=file, TARGET type=srt
Extract path '/home/ubuntu/recordings/test.ts': directory=/home/ubuntu/recordings filename=test.ts
Parameters:
Opening SRT target caller on 10.88.159.75:6000

Connecting to 10.88.159.75:6000

17:22:10.292306/SRT:RcvQ:worker*E: SRT.c: processAsyncConnectRequest: REJECT reported from HS processing, not processing further.
17:22:10.292456/SRT:RcvQ:worker*E: SRT.c: RendezvousQueue: processAsyncConnectRequest FAILED. Setting TTL as EXPIRED.
Event with status 6

Target disconnected
SrtCommon: DESTROYING CONNECTION, closing sockets (rt%533226121 ls%-1)...

SrtCommon: ... done.
```

**Comment by stoyanovgeorge** [comment]
I am also getting the same result if I want to accept an SRT stream and save it to a file: 
```
$ srt-file-transmit srt://:3000 file:///home/ubuntu/recordings/test_srt.ts
17:24:57.097537/SRT:RcvQ:worker*E: SRT.c: HSREQ/rcv: Agent uses STREAM API, but the Peer declares MESSAGE API. Not compatible transmission type, rejecting.
17:24:57.097674/SRT:RcvQ:worker*E: SRT.c: interpretSrtHandshake: process HSREQ returned unexpected value 0
17:24:57.097805/SRT:RcvQ:worker*E: SRT.c: %630300602:newConnection: connection rejected due to: ACCEPT ERROR
17:24:57.097852/SRT:RcvQ:worker*E: SRT.c: UU:newConnection: rsp(REJECT): 1002
```
And the same stream works with `srt-live-transmit`: 
```
$ srt-live-transmit srt://:3000 udp://225.0.0.0:9000
Media path: 'srt://:3000' --> 'udp://225.0.0.0:9000'
Accepted SRT source connection
```

**Comment by maxlovic** [comment]
@stoyanovgeorge 
Do you use `srt-file-transmit` on both sides of a connection?

**Comment by stoyanovgeorge** [comment]
nope, I have used `srt-live-transmit` to transmit a live UDP incoming multicast to SRT and then on the receiving side, I have used `srt-file-transmit`. I have also used `srt-file-transmit` to transmit the file and then on the other end `srt-live-transmit` to forward the SRT  stream to UDP multicast. Do I really need to use on both ends `srt-file-transmit`?

**Comment by maxlovic** [comment]
@stoyanovgeorge 
That is actually the problem. Because `srt-live-transmit` and `srt-file-transmit` will never connect to each other, as they operate in different modes (the handshake fails).
For your use case you can use `srt-live-transmit` and output to `file://cout`, then pipe it to file with `> file.dat`. This way you are not guaranteed to get the very last bytes of the streaming, though.
You can also go to `apps/transmitmedia.cpp` in `CreateMedium(const string& uri)` and enable file output for `srt-live-transmit`. But again, you are not guaranteed to receive the final bytes of the sequence. In most cases you will, though.
```
    case UriParser::FILE:
        if ( u.host() == "con" || u.host() == "console" )
            ptr.reset( CreateConsole<Base>() );
// Disable regular file support for the moment
#if 0
        else
            ptr.reset( CreateFile<Base>(u.path()));
#endif
```

Why don't you use [Haivisiion Media Gateway](https://www.haivision.com/products/media-gateway/) for your task? You might be spending time on something, that has already been solved.

**Comment by stoyanovgeorge** [comment]
@maxlovic , I don't really need that functionality right now, I was just testing it in order to be sure what the SRT library(apps) can do. I guess I can do the same with `ffmpeg`, by using SRT input and file output. 

I have also tested the VLC SRT support and managed to make it work only when the VLC is acting as an SRT caller, I am not sure if this is intended behavior, or just the other modes are not implemented by VLC.

**Comment by maxlovic** [comment]
Closing as invalid (used srt-live-transmit together with srt-file-transmit).
