### ISSUE TITLE
link error on windows 10 using msys2

### ISSUE THREAD

**Issue by jo-qzy** [Haivision/srt#584]
```
make -j16
[  2%] Building CXX object CMakeFiles/srtsupport_virtual.dir/apps/logsupport.cpp.obj
[  4%] Building C object CMakeFiles/haicrypt_virtual.dir/haicrypt/hc_openssl_aes.c.obj
[  7%] Building C object CMakeFiles/haicrypt_virtual.dir/haicrypt/hc_openssl_evp_cbc.c.obj
[  9%] Building CXX object CMakeFiles/srt_virtual.dir/srtcore/api.cpp.obj
[ 11%] Building CXX object CMakeFiles/srtsupport_virtual.dir/apps/socketoptions.cpp.obj
[ 14%] Building CXX object CMakeFiles/srtsupport_virtual.dir/apps/transmitmedia.cpp.obj
[ 19%] Building CXX object CMakeFiles/srt_virtual.dir/srtcore/buffer.cpp.obj
...

[ 80%] Built target srt_virtual
[ 83%] Building C object CMakeFiles/srt_static.dir/cmake_object_lib_support.c.obj
[ 85%] Building C object CMakeFiles/srt_shared.dir/cmake_object_lib_support.c.obj
[ 88%] Linking CXX static library libsrt.a
[ 90%] Linking CXX shared library libsrt.so
D:/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.1/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lwsock32.lib
D:/msys2/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.2.1/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lws2_32.lib
collect2.exe: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/srt_shared.dir/build.make:142：libsrt.so] error 1
make[1]: *** [CMakeFiles/Makefile2:149：CMakeFiles/srt_shared.dir/all] error 2
make[1]: *** waiting for unfinished tasks....
[ 90%] Built target srt_static
make: *** [Makefile:130：all] error 2
[ 90%] Built target srt_static
make: *** [Makefile:130：all] error 2
```
I use msys2 to build this in win10 and it occured link error cannot find lib, i put WSock32.lib and WS32_2.lib two lib file into lib path, but it seems didn't work, how can I solve it? Please help me to solve this..
I open vs2013 x64 Tools Command Prompt then type the command ```.\msys2_shell.cmd -mingw64```
Then I type following command
```
./configure
 make -j 8
```
Waiting for your reply, thank you~

**Comment by freeman1974** [comment]
have you fixed this issue? I encounter the same issue with you.

**Comment by maxsharabayko** [comment]
`pthreads` are no longer needed to build SRT on Windows. C++11 can be used instead. See [Windows Build instructions](https://github.com/Haivision/srt/blob/master/docs/build-win.md).
Therefore, depending on your goals, you might build with VC directly.

There is also a Travis CI pipeline that builds SRT using msys, but under Linux. Might be helpgfult. See [here](https://github.com/Haivision/srt/blob/master/.travis.yml#L57).

**Comment by jo-qzy** [comment]
> have you fixed this issue? I encounter the same issue with you.

You can refer to my blog at that time, for reference only
https://blog.csdn.net/Boring_Wednesday/article/details/88674854

**Comment by freeman1974** [comment]
> > have you fixed this issue? I encounter the same issue with you.
> 
> You can refer to my blog at that time, for reference only
> https://blog.csdn.net/Boring_Wednesday/article/details/88674854

I want to compile ffmpeg so I want libsrt compiled under msys2+mingw64.
And as your guide, still require pthread as build log:
D:\wincpp\ffmpeg\srt\srt-master\buildwin32>cmake ../ -G"Visual Studio 16 2019" -A win32 -DOPENSSL_ROOT_DIR=D:\wincpp\ffmpeg\srt\winx64
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
-- BUILD TYPE: Release
-- LOGGING: ENABLED
-- USE_BUSY_WAITING: OFF (default)
-- No WITH_COMPILER_PREFIX - using C++ compiler C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x86/cl.exe
-- Checking for module 'openssl libcrypto'
--
-- Found OpenSSL: D:/wincpp/ffmpeg/srt/winx64/lib/libcrypto.lib (found version "1.0.2g")
-- SSL via find_package(OpenSSL): -I C:/Strawberry/c/include -l;D:/wincpp/ffmpeg/srt/winx64/lib/libssl.lib;D:/wincpp/ffmpeg/srt/winx64/lib/libcrypto.lib
-- ENCRYPTION: ENABLED, using: openssl libcrypto
-- SSL libraries: D:/wincpp/ffmpeg/srt/winx64/lib/libssl.lib;D:/wincpp/ffmpeg/srt/winx64/lib/libcrypto.lib
-- COMPILER: MSVC (C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x86/cl.exe) - NOT GNU compat
-- STDCXX_SYNC: OFF
-- DETECTED SYSTEM: WINDOWS;  WIN32=1; PTW32_STATIC_LIB=1
CMake Error at CMakeLists.txt:659 (message):
  Failed to find pthread.h.  Specify PTHREAD_INCLUDE_DIR.


-- Configuring incomplete, errors occurred!
See also "D:/wincpp/ffmpeg/srt/srt-master/buildwin32/CMakeFiles/CMakeOutput.log".
See also "D:/wincpp/ffmpeg/srt/srt-master/buildwin32/CMakeFiles/CMakeError.log".

**Comment by freeman1974** [comment]
> > have you fixed this issue? I encounter the same issue with you.
> 
> You can refer to my blog at that time, for reference only
> https://blog.csdn.net/Boring_Wednesday/article/details/88674854

your blog is very good. but a key point is how mingw64 link srt.lib compiled by MSVC2019? how to transform srt.lib to libsrt.so /libsrt.a ?

tyc@DESKTOP-V7DQ7EV MINGW64 ~/download/ffmpeg-4.3.1
$ ./configure --prefix=/home/tyc/win64 --host-os=x86_64-w64-mingw32 --enable-libsrt --enable-gpl --enable-nonfree --enable-postproc --enable-ffplay --enable-avfilter --enable-runtime-cpudetect --disable-x86asm --enable-libx264 --enable-sdl2 --disable-debug --enable-shared --arch=x86_64 --extra-cflags=-I/home/tyc/win64/include --extra-ldflags=-L/home/tyc/win64/lib
ERROR: srt >= 1.3.0 not found using pkg-config     // i already give out the srt.pc 

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.
