### ISSUE TITLE
[question] release binaries

### ISSUE THREAD

**Issue by boxerab** [Haivision/srt#586]
Hello again! Is there a plan to generate release binaries for the majour platforms ?
windows, osx, ubuntu, for example ?

**Comment by m-garanin** [comment]
build for macOS takes half-day for me... For Windows I tried compile it 3 days already, it's so not easy.... 
PLEASE provide binary library for Win 64.

**Comment by ethouris** [comment]
The Windows builds should be available here: https://ci.appveyor.com/project/Haivision/srt/history

Just the problem is that they are currently done per PR fix. There should be some method to have a list of only release builds, with link available at the main project page.

**Comment by maxlovic** [comment]
For example: [Visual Studio 2015; Configuration: Release; Platform: x64](https://ci.appveyor.com/project/Haivision/srt/builds/28861907/job/to7eti6spwwkqb55/artifacts)

**Comment by lelegard** [comment]
> Hello again! Is there a plan to generate release binaries for the majour platforms ?
windows, osx, ubuntu, for example ?

This answer comes a bit late but libsrt is available on Fedora 31 (package `srt-devel`), on Ubuntu 19.04 (package `libsrt-dev`) and macOS 10.15 (homebrew package `srt`).

For Windows, see a proposal in #1068.

**Comment by boxerab** [comment]
Thanks! I will close this then.
