### ISSUE TITLE
transmitmedia.cpp wont build on OpenBSD

### ISSUE THREAD

**Issue by jlsantiago0** [Haivision/srt#590]
Seems that there are some non-portable multicast socket operations being used that are not supported by OpenBSD. Tested with OpenBSD-6.4. See https://man.openbsd.org/multicast .
In issue https://github.com/Haivision/srt/pull/588 the Sample/Support applications are disabled when building for OpenBSD.
The SRT library itself currently builds and runs correctly under OpenBSD.

**Comment by maxlovic** [comment]
Fixed by #588.
