### ISSUE TITLE
SRT support for chunked transfer encoding

### ISSUE THREAD

**Issue by akouSDN** [Haivision/srt#596]
Hi All,

I am wondering if we can use SRT together with chunked transfer encoding (CMAF-based). If no, is there any plan to provide such integration.

Thanks.

**Comment by MarcCymontkowski** [comment]
Hi, Yes, it is possible by using the message mode. I am in the process of writing a blog article about the different modes in SRT and will cover this use case.

**Comment by akouSDN** [comment]
Ok great @MarcCymontkowski. Please keep me update.

Can you explain how we can do that?

**Comment by maxsharabayko** [comment]
A separate repo is created for this initiative. https://github.com/Haivision/DSRT
Also refer to [srt-xtransmit](https://github.com/maxsharabayko/srt-xtransmit) `file send` and `file receive` subcommands (C++17).

**Comment by akouSDN** [comment]
Thanks @maxsharabayko
