### ISSUE TITLE
Recommended settings for KA Band Delivery

### ISSUE THREAD

**Issue by stream-gpl** [Haivision/srt#604]
HI SRT,

Is there recommended settings for KA Band delivery with a higher RTT. 

Thank you

Dave

**Comment by maxlovic** [comment]
Hi @stream-gpl,
For KA Band delivery the latency buffer needs to be pretty high … according to the “3-4x RTT” rule between 3-4s for a typical RTT of 700-800ms.
You can increase the latency further when your solution is not "low latency"-critical, and you'd prefer maximum stability
