### ISSUE TITLE
Building with --disable-logging failed

### ISSUE THREAD

**Issue by sepkooo** [Haivision/srt#616]
Hi, I have recently downloaded SRT Lib version 89cb4786a444038461725c9044c31ae9405c2ba9 (tag v1.3.2) and tried to build it with 
> --disable-logging 

but without success. Here is log from cmake (configure) and make:
>-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.27.1") 
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- BUILD TYPE: Release
-- LOGGING: DISABLED
-- No WITH_COMPILER_PREFIX - using C++ compiler /usr/bin/c++
-- Looking for inet_pton
-- Looking for inet_pton - found
-- SSL Dependency: using OpenSSL (default)
-- checking for module 'openssl libcrypto'
--   found openssl libcrypto, version 1.0.2k;1.0.2k
-- SSL via pkg-config: -L  -I  -l;ssl;crypto
-- SSL libraries: ssl;crypto
-- COMPILER: GNU compat: /usr/bin/c++
-- DETECTED SYSTEM: LINUX;  LINUX=1
-- ADDING TRANSITIVE LINK DEP to:srt_shared : -lpthread 
-- ADDING TRANSITIVE LINK DEP to:srt_static : -lpthread 
-- INSTALL DIRS: bin=bin lib=lib64 shlib=lib64 include=include
-- C++ VERSION: Setting C++11 compat flag for gnu compiler
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/tmp_trc/srt-89cb4786a444038461725c9044c31ae9405c2ba9

> Scanning dependencies of target haicrypt_virtual
[  2%] Building C object CMakeFiles/haicrypt_virtual.dir/haicrypt/hc_openssl_aes.c.o
[  5%] Building C object CMakeFiles/haicrypt_virtual.dir/haicrypt/hc_openssl_evp_cbc.c.o
[  7%] Building C object CMakeFiles/haicrypt_virtual.dir/haicrypt/hc_openssl_evp_ctr.c.o
[ 10%] Building C object CMakeFiles/haicrypt_virtual.dir/haicrypt/hcrypt.c.o
[ 12%] Building C object CMakeFiles/haicrypt_virtual.dir/haicrypt/hcrypt_ctx_rx.c.o
[ 15%] Building C object CMakeFiles/haicrypt_virtual.dir/haicrypt/hcrypt_ctx_tx.c.o
[ 17%] Building C object CMakeFiles/haicrypt_virtual.dir/haicrypt/hcrypt_rx.c.o
[ 20%] Building C object CMakeFiles/haicrypt_virtual.dir/haicrypt/hcrypt_sa.c.o
[ 23%] Building C object CMakeFiles/haicrypt_virtual.dir/haicrypt/hcrypt_tx.c.o
[ 25%] Building C object CMakeFiles/haicrypt_virtual.dir/haicrypt/hcrypt_xpt_srt.c.o
[ 28%] Building C object CMakeFiles/haicrypt_virtual.dir/haicrypt/hcrypt_xpt_sta.c.o
[ 30%] Building CXX object CMakeFiles/haicrypt_virtual.dir/haicrypt/haicrypt_log.cpp.o
[ 30%] Built target haicrypt_virtual
Scanning dependencies of target srt_virtual
[ 33%] Building CXX object CMakeFiles/srt_virtual.dir/srtcore/api.cpp.o
In file included from /tmp/tmp_trc/srt-89cb4786a444038461725c9044c31ae9405c2ba9/srtcore/handshake.h:49:0,
                 from /tmp/tmp_trc/srt-89cb4786a444038461725c9044c31ae9405c2ba9/srtcore/api.h:66,
                 from /tmp/tmp_trc/srt-89cb4786a444038461725c9044c31ae9405c2ba9/srtcore/api.cpp:60:
/tmp/tmp_trc/srt-89cb4786a444038461725c9044c31ae9405c2ba9/srtcore/crypto.h: In member function ‘void CCryptoControl::getKmMsg_markSent(size_t, bool)’:
/tmp/tmp_trc/srt-89cb4786a444038461725c9044c31ae9405c2ba9/srtcore/crypto.h:158:28: error: ‘srt_logging::mglog’ has not been declared
         using srt_logging::mglog;
                            ^
make[2]: *** [CMakeFiles/srt_virtual.dir/srtcore/api.cpp.o] Error 1
make[1]: *** [CMakeFiles/srt_virtual.dir/all] Error 2
make: *** [all] Error 2

I've also tried to build SRT with 
> --ENABLE_LOGGING=0 --ENABLE_HAICRYPT_LOGGING=0

but it produces same error when compiling.

Is there any workaround to build SRT v1.3.2 with logging turned off? 
Thank you.

**Comment by maxlovic** [comment]
Fixed by #632
