### ISSUE TITLE
Implement Adaptive Listener

### ISSUE THREAD

**Issue by ethouris** [Haivision/srt#619]
Add a possibility to pre-configure an accepted socket before it's returned in `srt_accept` function.

This should provide a user with a bunch of information retrieved from the handshake that allow to make a decision and set up some settings that normally would be derived from the listener and on the caller socket can only be set prior to connecting.

The socket should be given up to the user AFTER the settings derived from listener and handshake exchange have been applied.

**Comment by mbakholdina** [comment]
Implemented.
