### ISSUE TITLE
Why srt no support flv?

### ISSUE THREAD

**Issue by HuyaJohn** [Haivision/srt#624]
Why vlc and ffmpeg only support srt over ts?
Srt is just an transmit protocol, like udp or tcp, it's no need to care about the payload.

**Comment by maxlovic** [comment]
Hi @HuyaJohn,
That is more a question to VLC and ffmpeg communities.
SRT is indeed just a content-agnostic transmission protocol, Live transmission is the very reason it was created, and mostly used. MPEG-TS is a more convenient live transfer container, while flv is more a file storage and transfer container.
