### ISSUE TITLE
Make OpenSSL dependency optional on request

### ISSUE THREAD

**Issue by ethouris** [Haivision/srt#63]
Not in every case of platform/system combination is it possible to rely on that the `OpenSSL.cmake` file will  function correctly. Moreover, it was already requested that haicrypt work with also different providers for an SSL library.

Is that possible that when `find_package(OpenSSL)` somehow fails, the system tries to apply for OpenSSL by trying out the pkg-config file directly (`pkg_search_module`)?

**Comment by russelltg** [comment]
[You can pass `OPENSSL_ROOT_DIR`](https://cmake.org/cmake/help/v3.0/module/FindOpenSSL.html) to FindOpenSSL.cmake, which should be enough flexibility. If not, you can always pass `OPENSSL_LIBRARIES` and `OPENSSL_INCLUDE_DIR` manually.

**Comment by ethouris** [comment]
Ok, I checked again and on this system with "unusual" settings for OpenSSL it was done such a way that OpenSSL wasn't linked against this library at all. This wasn't a problem because in this mode all programs were turned off (it was crosscompiling for ARM architecture), they only needed libraries to be compiled, and the executables were linked against OpenSSL anyway, using their own rules.

Because of that there would be nice to have a possibility to completely turn off dependency on OpenSSL (pthread too, of course) if so explicitly requested, and in this mode of course all programs are turned off. I'd do it by using a variable kinda `WITHOUT_OPENSSL`, but maybe cmake has some other nomenclature for that occasion...

**Comment by jeandube** [comment]
The hook to thr crypto provider is described by the hcrypt_Cipher structure, a set of 5 functions (open, close, setkey, encrypt, decrypt). the source file hc_openssl_evp_ctr.c implements AES-CRT usin openssl. This API is essentially for the media stream encryption and should be completed with other crypto functions required by the key exchange (PRNG, PBKDF2, AES Key Wrap/Unwrap).

**Comment by adamyellen** [comment]
This is more or less resolved with PR #149.
