### ISSUE TITLE
srtsupport_virtual.dir error

### ISSUE THREAD

**Issue by ntminh90** [Haivision/srt#631]
I have an error when install srt on Centos Linux.

Log on screen when "make" command like this:

Scanning dependencies of target srtsupport_virtual
[ 79%] Building CXX object CMakeFiles/srtsupport_virtual.dir/apps/socketoptions.cpp.o
/root/Setup/srt-master/apps/socketoptions.cpp:31: error: stray ‚Äò\302‚Äô in program
/root/Setup/srt-master/apps/socketoptions.cpp:31: error: stray ‚Äò\267‚Äô in program
/root/Setup/srt-master/apps/socketoptions.cpp:31: error: stray ‚Äò\302‚Äô in program
/root/Setup/srt-master/apps/socketoptions.cpp:31: error: stray ‚Äò\267‚Äô in program
/root/Setup/srt-master/apps/socketoptions.cpp:244:10: warning: missing terminating ' character
/root/Setup/srt-master/apps/socketoptions.cpp:244: error: missing terminating ' character
/root/Setup/srt-master/apps/socketoptions.cpp:290: error: stray ‚Äò\342‚Äô in program
/root/Setup/srt-master/apps/socketoptions.cpp:290: error: stray ‚Äò\206‚Äô in program
/root/Setup/srt-master/apps/socketoptions.cpp:290: error: stray ‚Äò\265‚Äô in program
/root/Setup/srt-master/apps/socketoptions.cpp:295: error: stray ‚Äò\342‚Äô in program
/root/Setup/srt-master/apps/socketoptions.cpp:295: error: stray ‚Äò\206‚Äô in program
/root/Setup/srt-master/apps/socketoptions.cpp:295: error: stray ‚Äò\265‚Äô in program
/root/Setup/srt-master/apps/socketoptions.cpp:331: error: stray ‚Äò\342‚Äô in program
/root/Setup/srt-master/apps/socketoptions.cpp:331: error: stray ‚Äò\206‚Äô in program
/root/Setup/srt-master/apps/socketoptions.cpp:331: error: stray ‚Äò\265‚Äô in program
/root/Setup/srt-master/apps/socketoptions.cpp:336: error: stray ‚Äò\342‚Äô in program
/root/Setup/srt-master/apps/socketoptions.cpp:336: error: stray ‚Äò\206‚Äô in program
/root/Setup/srt-master/apps/socketoptions.cpp:336: error: stray ‚Äò\265‚Äô in program
/root/Setup/srt-master/apps/socketoptions.cpp:363: error: stray ‚Äò\342‚Äô in program
/root/Setup/srt-master/apps/socketoptions.cpp:363: error: stray ‚Äò\206‚Äô in program
/root/Setup/srt-master/apps/socketoptions.cpp:363: error: stray ‚Äò\265‚Äô in program
/root/Setup/srt-master/apps/socketoptions.cpp:368: error: stray ‚Äò\342‚Äô in program
/root/Setup/srt-master/apps/socketoptions.cpp:368: error: stray ‚Äò\206‚Äô in program
/root/Setup/srt-master/apps/socketoptions.cpp:368: error: stray ‚Äò\265‚Äô in program
/root/Setup/srt-master/apps/socketoptions.cpp:528:50: error: invalid suffix "f008a4055c492aed39896290f015a47" on integer constant
/root/Setup/srt-master/apps/socketoptions.cpp:533:16: warning: missing terminating ' character
/root/Setup/srt-master/apps/socketoptions.cpp:533: error: missing terminating ' character
/root/Setup/srt-master/apps/socketoptions.cpp:588: error: stray ‚Äò\342‚Äô in program
/root/Setup/srt-master/apps/socketoptions.cpp:588: error: stray ‚Äò\200‚Äô in program
/root/Setup/srt-master/apps/socketoptions.cpp:588: error: stray ‚Äò\246‚Äô in program
/root/Setup/srt-master/apps/socketoptions.cpp:593:13: error: invalid suffix "a28026" on integer constant
/root/Setup/srt-master/apps/socketoptions.cpp:724: error: stray ‚Äò#‚Äô in program
/root/Setup/srt-master/apps/socketoptions.cpp:1182:12: warning: missing terminating ' character
/root/Setup/srt-master/apps/socketoptions.cpp:1182: error: missing terminating ' character
/root/Setup/srt-master/apps/socketoptions.cpp:1237: error: stray ‚Äò\342‚Äô in program
/root/Setup/srt-master/apps/socketoptions.cpp:1237: error: stray ‚Äò\200‚Äô in program
/root/Setup/srt-master/apps/socketoptions.cpp:1237: error: stray ‚Äò\231‚Äô in program
/root/Setup/srt-master/apps/socketoptions.cpp:7: error: expected unqualified-id before ‚Äò<‚Äô token
/root/Setup/srt-master/apps/socketoptions.cpp:147: error: expected unqualified-id before ‚Äò<‚Äô token
/root/Setup/srt-master/apps/socketoptions.cpp:160: error: expected unqualified-id before ‚Äò<‚Äô token
/root/Setup/srt-master/apps/socketoptions.cpp:161: error: expected unqualified-id before ‚Äò<‚Äô token
/root/Setup/srt-master/apps/socketoptions.cpp:181: error: expected unqualified-id before ‚Äò<‚Äô token
/root/Setup/srt-master/apps/socketoptions.cpp:184: error: expected constructor, destructor, or type conversion before ‚Äò<‚Äô token
/root/Setup/srt-master/apps/socketoptions.cpp:217: error: expected unqualified-id before ‚Äò<‚Äô token
/root/Setup/srt-master/apps/socketoptions.cpp:225: error: expected unqualified-id before ‚Äò<‚Äô token
/root/Setup/srt-master/apps/socketoptions.cpp:226: error: expected unqualified-id before ‚Äò<‚Äô token
/root/Setup/srt-master/apps/socketoptions.cpp:385: error: expected constructor, destructor, or type conversion before ‚Äò<‚Äô token
/root/Setup/srt-master/apps/socketoptions.cpp:387: error: expected constructor, destructor, or type conversion before ‚Äò<‚Äô token
/root/Setup/srt-master/apps/socketoptions.cpp:724: error: expected unqualified-id before ‚Äò<‚Äô token
/root/Setup/srt-master/apps/socketoptions.cpp:724: error: expected unqualified-id before ‚Äò<‚Äô token
/root/Setup/srt-master/apps/socketoptions.cpp:733: error: expected unqualified-id before ‚Äò<‚Äô token
/root/Setup/srt-master/apps/socketoptions.cpp:747: error: expected constructor, destructor, or type conversion before ‚Äò&‚Äô token
/root/Setup/srt-master/apps/socketoptions.cpp:747: error: expected constructor, destructor, or type conversion before ‚Äò=‚Äô token
/root/Setup/srt-master/apps/socketoptions.cpp:747: error: expected unqualified-id before ‚Äò<‚Äô token
/root/Setup/srt-master/apps/socketoptions.cpp:751: error: expected constructor, destructor, or type conversion before ‚Äò&‚Äô token
/root/Setup/srt-master/apps/socketoptions.cpp:751: error: expected constructor, destructor, or type conversion before ‚Äò=‚Äô token
/root/Setup/srt-master/apps/socketoptions.cpp:751: error: expected unqualified-id before ‚Äò<‚Äô token
/root/Setup/srt-master/apps/socketoptions.cpp:760: error: expected constructor, destructor, or type conversion before ‚Äò,‚Äô token
/root/Setup/srt-master/apps/socketoptions.cpp:760: error: expected unqualified-id before ‚Äò<‚Äô token
/root/Setup/srt-master/apps/socketoptions.cpp:760: error: expected constructor, destructor, or type conversion before ‚Äò=‚Äô token
make[2]: *** [CMakeFiles/srtsupport_virtual.dir/apps/socketoptions.cpp.o] Error 1
make[1]: *** [CMakeFiles/srtsupport_virtual.dir/all] Error 2
make: *** [all] Error 2

Please help me.

Thank for supporting

**Comment by ethouris** [comment]
Well, the problem is that `apps/socketoptions.cpp` file has only 114 lines. You have something quite problematic in the repository.

I'm viewing the latest version with code hash `c4d94fc2`.
