### ISSUE TITLE
Solution required: whether pc file should add -lstdc++

### ISSUE THREAD

**Issue by ethouris** [Haivision/srt#64]
The application using SRT should rely on information found in the `srt.pc` file.

The problem is that the API is suited for C language (to make it most possibly universal), and an a build system for the C application would have to be somehow instructed that it should link against libstdc++/libc++.

I did it by adding `-lstdc++` in `Libs:` section - but this has caused another problem: a C++ application must find this option and take it out, at least when it's going to link the application against libstdc++ statically.

Something sensible is required so that the same PC file can be used for C applications using SRT and C++ applications using SRT and linking against libstdc++ statically. Might be that some extra steps are required in particular case, such as reading from a custom variable from a pc file.

**Comment by ocrete** [comment]
You want to add it to Libs.private
As this is only required for static builds, as a dynamic library, the dependency should already be in the linker informatioin of the library.

**Comment by ethouris** [comment]
Even if I add this to Libs.private, the problem persists. Let me be clear on both use cases:

1. A C++ application is using SRT and it links ITSELF against a static libstdc++. It needs SRT library to be free of any direct references to libstdc++, as this static libstdc++ will satisfy this dependency for both the application and SRT library.
2. A C application linking statically against SRT must be instructed to link against libstdc++.

If I add -lstdc++ to Libs.private, then it will make the -lstdc++ option to be added to the compiler, which will conflict with -static-libstdc++, especially if you want to specify some custom location of this library.

My current solution is that the C++ application is aware of that problem and it removes any -lstdc++ option from the library flags extracted from the srt.pc file. But that's kinda clumsy.
