### ISSUE TITLE
Feature Request: support for transport of files 

### ISSUE THREAD

**Issue by CT99** [Haivision/srt#65]
According to the SRT team, SRT is designed to transport live streams. Transmitting a file is not a supported use case of the protocol or the stransmit utility. The stransmit utility allows for file input and output options as a way to allow for stdin/stdout.

This is an issue for us as we work with both livestream and archived content. In some cases we overlay both for certain use cases. While we're working to establish a workaround, support for both livestream and archived / filed-based content would make the protocol and the srtransmit utility something we could standardize on as oppose to experiment with. Thanks.

**Comment by ethouris** [comment]
Please, a little bit patience :)

The precondition for having a file transmission possible is the "integrated handshake" working. I have a solution already at hand, just trying to merge the changes done in our private repository and this repository, there are also some small formal problems to solve.

Of course, this version won't be an "out of the box" possibility for file transmission, but at least this possibility should be much easier to add. Local file transmission tests have even succeeded, but still, this can be so easily done only in a local network testing environment and only for very short files. For a real sending a file over the network there's still lots of problems to solve, first of all there should be some pace control mechanism added, as a part of a special "file transfer" mode.

**Comment by adamyellen** [comment]
@CT99 Thank you very much for opening this enhancement request!

**Comment by ethouris** [comment]
This Pull Request is created for supporting file transfer in SRT.
https://github.com/Haivision/srt/pull/90

It may still take some time until it's finally approved, and it's announced to be approved only in `dev` branch.

Whoever would like to try this out, you can see it on my replica on `dev-congestion-control` branch:
https://github.com/ethouris/srt

**Comment by ethouris** [comment]
The pull request that introduces file transfer has been merged to `dev` branch on the official repository.
