### ISSUE TITLE
IPE every time when calling srt_clean_up() on macOS

### ISSUE THREAD

**Issue by oviano** [Haivision/srt#652]
00:17:14.639157!!FATAL!!:SRT.c: CChannel reported ERROR DURING TRANSMISSION - IPE. INTERRUPTING worker anyway.

I can provide more details, example code, but this happens every time, and all you need to do is create and bind a socket. Thereafter, calling clean_up() produces the above error message.

Same code does not do this under Windows.

**Comment by oviano** [comment]
Just to add that iOS and tvOS also produce the same error. It doesn't appear to adversely affect anything, but I'm assuming it is not desired behaviour to produce an error labelled "FATAL".

**Comment by oviano** [comment]
Here is some trace. This is on macOS 10.14, latest SRT code, all it does it start up the library, open a socket for listening, add it to an epoll and keep checking it, before being told a few seconds later to close the listen socket, and then clean up the library.

1:38:37.119338 D:SRT.c: @998058484:newSocket: mapping socket 998058484
21:38:37.119768 D:SRT.c: clearData: PAYLOAD SIZE: 1456
21:38:37.119841 D:SRT.c: CHANNEL: Bound to local address: 0.0.0.0:8090
21:38:37.120053 D:SRT.c: creating new multiplexer for port 8090
21:38:38.122502 D:SRT.c: GC: sleep until 21:38:39.122499
21:38:39.122615 D:SRT.c: GC: sleep until 21:38:40.122614
21:38:40.123753 D:SRT.c: GC: sleep until 21:38:41.123751
21:38:41.124968 D:SRT.c: GC: sleep until 21:38:42.124966
21:38:42.129094 D:SRT.c: GC: sleep until 21:38:43.129092
21:38:43.130868 D:SRT.c: GC: sleep until 21:38:44.130867
21:38:44.134784 D:SRT.c: GC: sleep until 21:38:45.134782
21:38:44.861405 D:SRT.c: %998058484: CLOSE. Acquiring control lock
21:38:44.861491 D:SRT.c: %998058484: CLOSING (removing from listening, closing CUDT)
21:38:44.861510 D:SRT.c: %998058484: CLOSING (removing listener immediately)
21:38:44.861552 D:SRT.c: %998058484: GLOBAL: CLOSING DONE
21:38:44.861669 D:SRT.c: GC: GLOBAL EXIT - releasing all pending sockets. Acquring control lock...
21:38:44.861760 D:SRT.c: %998058484: - closing socket:
21:38:44.861860 D:SRT.c: %998058484: ... (linger)
21:38:44.862148 D:SRT.c: %998058484:CLOSING STATE. Acquiring connection lock
21:38:44.862259 D:SRT.c: %998058484:CLOSING, removing from listener/connector
21:38:44.862295 D:SRT.c: CLOSING, joining send/receive threads
21:38:44.862334 D:SRT.c: GC: GLOBAL EXIT - releasing all CLOSED sockets.
21:38:44.862351 D:SRT.c: GC/removeSocket: closing associated UDT %998058484
21:38:44.862361 D:SRT.c: GC/removeSocket: DELETING SOCKET %998058484
21:38:44.862404 D:SRT.c: MUXER id=998058484 lost last socket %998058484 - deleting muxer bound to port 8090
21:38:44.862459 D:SRT.c: (sys)recvmsg: Bad file descriptor [9]
21:38:44.862482!!FATAL!!:SRT.c: CChannel reported ERROR DURING TRANSMISSION - IPE. INTERRUPTING worker anyway.
Program ended with exit code: 0

**Comment by oviano** [comment]
I’m also observing this sporadically as sockets are closed during execution of my program, ie not just via srt_cleanup.

**Comment by ethouris** [comment]
Ok, it's here:
```
       HLOGC(mglog.Debug, log << "MUXER id=" << mid << " lost last socket %"
           << u << " - deleting muxer bound to port "
           << m->second.m_pChannel->bindAddressAny().hport());
      m->second.m_pChannel->close();
      delete m->second.m_pSndQueue;
      delete m->second.m_pRcvQueue;
      delete m->second.m_pTimer;
      delete m->second.m_pChannel;
      m_mMultiplexer.erase(m);
```

First, there's nothing wrong happening and this message is kinda misleading. Intended in this case was that you see this message (with Debug level):

"CChannel reported error, but Queue is closing - INTERRUPTING worker."

This is because the call to `CChannel::close` is closing the socket, and this causes that the operation done on this socket in another thread gets an error. Whether you can see it or not, it actually depends on the good luck in the thread scheduling.

Not sure how to fix it - what should be actually done is to "silence" the SndQueue and RcvQueue before calling CChannel::close.

**Comment by ethouris** [comment]
I've prepared a fix for this on the branch. Could you test it please?

https://github.com/ethouris/srt/tree/dev-fix-misleading-close-error

**Comment by oviano** [comment]
I've tested it by manually putting those changes into my copy of the main branch and I can confirm this removes the IPE message.

Thank you.
