### ISSUE TITLE
Suggestions For Identifying Cause Of Packet Drops

### ISSUE THREAD

**Issue by BananaHemic** [Haivision/srt#653]
I'm using the SRT library to stream live video from a camera to a server in the cloud. I'm experiencing intermittent packet loss, frequently every 4 seconds (the same as my keyframe interval) but sometimes at intervals of 0.5s to 20 minutes.
 
My first thought was that this was an issue with the link capacity, but running iperf2:
` .\iperf.exe -c [my-ip] -u -p 8042 -b 8m -t 120 -i 1 -f m -l 1316 --tos 0xB8 --ttl 64`
shows no dropped packets and a jiter of only 1.5ms. Iperf is using a bandwidth of 8Mbps, whereas my stream is 4Mbps.

I'm not convinced that this is an actual issue within SRT, more likely an issue with my specific system. The sender is a Windows 10 x64, and the receiver is an Ubuntu 16 server. I've set rmem_default rmem_max to 8388608 on the server.

Does anyone have any suggestions for diagnosing the cause of packet loss?

**Comment by BananaHemic** [comment]
Upon further investigation, this seems to be related to #637. Iperf has a very constant rate of packet sends, whereas srt has massive spikes of packet sends that appear to occur at the same time as packet drops

**Comment by ethouris** [comment]
Whoever did "massive spikes" of packet sends, it wasn't SRT. SRT sends exactly the packet just after it has been sent from the application and after punching through the congestion in the local machine.
