### ISSUE TITLE
How to receive CodeMajor and CodeMinor from C API

### ISSUE THREAD

**Issue by oviano** [Haivision/srt#654]
So I can see that srt_getlasterror() returns a combination of the major and minor codes, using the formula major * 1000 + minor.

So if I wanted to check for MJ_AGAIN, am I supposed to call srt_getlasterror() / 1000, which obviously works, but seems to rely on the internal formula not changing?

**Comment by ethouris** [comment]
At least we don't plan to change this formula and with any new types of errors we generally try to keep up with the current categories.
