### ISSUE TITLE
FFMpeg "Invalid timestamps" then "No room to store incoming packet" and stops

### ISSUE THREAD

**Issue by gregfr** [Haivision/srt#659]
Greetings
I'm new to SRT so please forgive me if I'm not doing things correctly.

I'm trying to grab a stream from a hardware encoder I don't have control on.

I've just recompiled ffmpeg and srt (latest versions).

I'm using it like this:

`./bin/srt-live-transmit srt://my_ip file://con | ./bin/ffplay -`

I get hundreds of:

`[mpegts @ 0x7f4814000940] Invalid timestamps stream=0, pts=1136390514, dts=1136394114, size=2239`

After a few seconds a ugly image appear, and the video plays for a variable duration (from a few seconds to two hours) ; then:

`SRT:RcvQ:worker*E:SRT.c: %174854797:No room to store incoming packet: offset=0 avail=0 ack.seq=48374278 pkt.seq=48374278 rcv-remain=31`

and finally:

`SRT:RcvQ:worker*E:SRT.c: %174854797:SEQUENCE DISCREPANCY, reception no longer possible. REQUESTING TO CLOSE.`

Neither the server nor the client are short on bandwidth/memory/cpu.

How can I fix this problem? are they any parameters I can specify from the client? buffer size or paquet size maybe?

I've tried using the `srt-live-transmit` binary and also the ffmpeg module (`ffmpeg -i srt://...`) with the same results.

Thanks in advance

Regards

**Comment by gregfr** [comment]
Note: to avoid codec potential issues, I've tried the null demux:

`./bin/ffmpeg -i - -c:a copy  -c:v copy -f null -`

The same problems happend.

**Comment by maxlovic** [comment]
@gregfr This may be related to several things.
Have a look at the [live streaming guide](https://github.com/Haivision/srt/blob/master/docs/live-streaming.md).
`srt-live-transmit` expects packet with payload size 1316, while ffmpeg by default will send a different payloads. Try the following to stream to srt:
```
ffmpeg -xerror -y -i 'rtmp://127.0.0.1/app/zenlink_m1' -c:v copy -c:a copy -f mpegts 
'srt://127.0.0.1:17241?pkt_size=1316`
```
Check with `ffplay` accepting from SRT first, then try to increase the number of processes used in your pipeline..

Take a look at #407 if you are on Windows.

**Comment by maxlovic** [comment]
Also have a look at discussion in #642.

**Comment by gregfr** [comment]
Thanks for your answer. I'm on linux and receiving a stream from a device I don't control, so I cannot change its settings (unless the client can tell the sender about the packet size?)
The problem doesn't occur under heavy load, but after hours of streaming. Maybe a memory leak?

**Comment by maxlovic** [comment]
@gregfr With `srt-live-transmit` you can turn on SRT statistics output. Try to check packets reported lost (that will be retransmitted) and dropped.
```
-s:<stats-report-freq=0> - frequency of status report
-pf:<format> - printformat (json or default)
-statsout:<filename> - output stats to file
```
Statistics report frequency in in packets, thus specifying 1000 will produce stats report every 1000 packets.
I recommend using `-s <bitrate / (8*1316)> -ps csv -statsout stats.csv` for live.

**Comment by gregfr** [comment]
OK I'll try that. My stream is 5Mbps, so it's `-s 500` ?

**Comment by maxlovic** [comment]
Yes, this should roughly give you 1 second interval.

**Comment by gregfr** [comment]
When I run the command:
```
./srt-live-transmit -s 500 -statsout /tmp/srt.csv -logfile /tmp/srt.log srt://<sourceip> file://con | ./ffmpeg ...
```
I get :

```
ERROR: Can't open ' /tmp/srt.log' for writing - fallback to cerr
ERROR: Can't open ' /tmp/srt.csv' for writing stats. Fallback to stdout.
```

whatever the user (even root). I just pulled and recompiled `srt-live-transit`...

**Comment by gregfr** [comment]
Also `ERROR: Unsupported print format:  csv`

**Comment by maxlovic** [comment]
Try `-pf:csv`. There seems to be an error, when space is used as a separator.
Regarding the error openning files. seems like the same issue with extra space at the start.

**Comment by gregfr** [comment]
```
ERROR. Invalid syntax. Specify source and target URIs.
The following options are passed without a key: udp://localhost:12345,
```

It seems the source argument is used as a value for the `-pf:csv` parameter (since `udp://localhost:12345` is the target).

**Comment by gregfr** [comment]
As a test, I did:
```
/home/streams/srt-live-transmit -s 500 -ll warning -v -r 500 srt://<myip> udp://localhost:12345 >> /tmp/srt.log 2>> /tmp/srt.err
```

and here are the corresponding stats:

```
======= SRT STATS: sid=226392826
PACKETS     SENT:           0  RECEIVED:           514 
LOST PKT    SENT:           0  RECEIVED:             0 
REXMIT      SENT:           0  RECEIVED:             0  
DROP PKT    SENT:           0  RECEIVED:             0
RATE     SENDING:           0  RECEIVING:       4.5198
BELATED RECEIVED:           0  AVG TIME:             0 
REORDER DISTANCE:           0                                  
WINDOW      FLOW:        8192  CONGESTION:        8192  FLIGHT:           0    
LINK         RTT:      0.39ms  BANDWIDTH:    90.06Mb/s     
BUFFERLEFT:  SND:    12288000  RCV:           12220500
```

The bandwidth is about 100Mb/s, why? is it because I don't have an actual target?

**Comment by maxlovic** [comment]
Bandwidth is estimated based on 64 probing packets, where only every 16th packet is a probing packet. And the So at least 1024 packets are required to estimate the bandwidth. Also don't expect very precise estimation.

**Comment by gregfr** [comment]
But my input stream is only 5Mbps, so why 100Mb/s?

**Comment by maxlovic** [comment]
It is an estimation of a bandwidth of your network link. The bitrate you could potentially send over the link.
Receiving speed is
`RECEIVING:       4.5198` Mbps

If you still have issues with CL options, try to use quotes: "srt://<myip>" "udp://localhost:12345"

**Comment by gregfr** [comment]
The estimation is good: it's the actual bandwith between the two servers.
For the CLI options, I found the solution: the parameters should go AFTER the source and target...

**Comment by gregfr** [comment]
But nothing is written to the files :(

**Comment by maxlovic** [comment]
> The estimation is good: it's the actual bandwith between the two servers.

Cool. What is the network link? Ethernet, WiFi, 3G? How do you know 100 Mbps is your link bandwidth?

> But nothing is written to the files :(

Please provide again a complete command-line you specify. Everything should work. Just use `:` instead of space for now. And stats report (` "s", "stats", "stats-report-frequency"`), not bandwidth report. Bandwidth report is not redirected to file. E.g.
`srt-live-transmit -s:500 -ll:warning -v -s:500 -statsout:/tmp/srt.log srt://<myip> udp://localhost:12345`

**Comment by gregfr** [comment]
The network is managed by the datacenter, so I think it's shaped by the switches.

The command line is:
```
./srt-live-transmit srt://<myip> file://con -s 500 -ll debug -v -r 500 -statsout /tmp/srt.csv -logfile /tmp/srt.log  -pf:csv  2>/tmp/srt.err | ./ffmpeg ...
```

This gives garbage in the stream, but:
```
./srt-live-transmit srt://<myip> file://con -q -ll fatal 2>/tmp/srt.err | ./ffmpeg ...
```

gives a clean image, so I guess `srt-live-transmit` pollutes it own output stream...
I still have a lot of
```
[mpegts @ 0x3ebef40] Invalid timestamps stream=0, pts=941983107, dts=941984907, size=1726
```

but the video is ok ; I'll let it run to see if it breaks after a few hours.

**Comment by gregfr** [comment]
After recompiling everything with the latest versions, I'm happy to report that my stream have been live for more than 190 hours. I still see the "invalid timestamps" but I think it's because of the sender packet size (I'm in contact with them).

**Comment by maxlovic** [comment]
@gregfr Great! Thanks for reporting back.

**Comment by danrossi** [comment]
I am also receiving this problem. I'm trying to run a push test to wowza. But testing locally sending mpegts with gstreamer I get the same problems. 

I've had some serious issues trying to find the right commands to push mpegts or h264 to mpegts through SRT using gstreamer. This is what I have some up with so far which isn't anywhere to be found.  I can't seem to get SRT working yet. SRT in Gstreamer is only found in source builds, the same might be for ffmpeg. 

I have the latest libsrt compiled from the sourced. 

```
gst-launch-1.0 filesrc location=sintel_lang.ts ! tsparse set-timestamps=1 smoothing-latency=40000000 ! chopmydata step-size=188 min-size=188 max-size=1316 ! srtsink uri=srt://127.0.0.1:8081
```

```
23:30:53.384001*E: SRT.d: SND-DROPPED 24 packets - lost delaying for 1024ms
23:30:53.393016*E: SRT.d: SND-DROPPED 23 packets - lost delaying for 1023ms
23:30:53.402105*E: SRT.d: SND-DROPPED 23 packets - lost delaying for 1023ms
23:30:53.411108*E: SRT.d: SND-DROPPED 28 packets - lost delaying for 1023ms
```


On the listener

```
gst-play-1.0 srt://:8081
```

```
23:30:53.421856*E: SRT.c: %811065518:No room to store incoming packet: offset=31623 avail=6340 ack.seq=601059341 pkt.seq=601090964 rcv-remain=1851
23:30:53.422561*E: SRT.c: %811065518:No room to store incoming packet: offset=31624 avail=6340 ack.seq=601059341 pkt.seq=601090965 rcv-remain=1851
```

**Comment by maxlovic** [comment]
@danrossi 
Default receiver buffer size is approximately 96 Mbits. Please check this
[recommendation](https://github.com/Haivision/srt/issues/703#issuecomment-495570496) to see if the size is enough for your set up.

The receiver buffer must have enough space for (latency + RTT) * bitrate.

**Comment by danrossi** [comment]
I'm testing this locally on the same machine, but remotely has provided worse results so far. What does this mean sorry ? I need more options on the receiver ?

**Comment by maxlovic** [comment]
First of all you should know the RTT of the link and SRT configuration, in particular, latency value.
`smoothing-latency=40000000` is that 40 seconds?

**Comment by danrossi** [comment]
It's not explanitory what the value means, I was advised on those properties to get mpeg-ts working properly. I'm trying it locally to make sure the comand is working and playing back smoothly. Setting the latency property doesnt help.

```
gst-launch-1.0 filesrc location=sintel_lang.ts ! tsparse set-timestamps=1 ! chopmydata step-size=188 min-size=188 max-size=1316 ! srtsink uri=srt://127.0.0.1:8081 latency=0
```
It plays back smoothly, and the receiver stops with this after all the errors. 

```
02:04:03.557791*E: SRT.c: %399191957:SEQUENCE DISCREPANCY, reception no longer possible. REQUESTING TO CLOSE.
```

These commands, there is no such error until a few minutes

```
//listener
gst-launch-1.0 -v srtsrc uri="srt://:8888" ! decodebin ! videoconvert ! autovideosink

//caller
gst-launch-1.0 videotestsrc ! video/x-raw, height=360, width=640 ! videoconvert ! x264enc tune=zerolatency ! video/x-h264, profile=high ! mpegtsmux ! srtsink uri="srt://127.0.0.1:8888"
```
```
02:08:28.761176*E: SRT.c: %906882074:No room to store incoming packet: offset=7046 avail=6816 ack.seq=114405053 pkt.seq=114412099 rcv-remain=1373
```

**Comment by maxlovic** [comment]
Recommended latency value is 4 × RTT. 
Still looks like you should find a way to increase the receiver's buffer. Based on #445, the `srt-recv:{INT, 0...}` for GStreamer. And try the senders buffer to be the same value as the receivers buffer. In case you receiving on Wowza, please check the configuration steps with them.

**Comment by danrossi** [comment]
Thankyou. How do I implement this, on the uri directly ie


```
srt://:8081?srt-recv=0
```

or

```
srt://:8081?srt-recv={INT, 0}
```

**Comment by danrossi** [comment]
According to the gstreamer source code , there is no such property handled. There is just a latency property. I am trying to test it actually works on the local machine before trying remotely.

**Comment by danrossi** [comment]
Commented elsewhere. I see no configuration. It's on a local test also.

I managed to get ffmpeg compiled with srt on debian. ffmpeg as a caller to gstreamer on the same machine works fine. I get no such error. 

```
ffmpeg -fflags +genpts  -re -i sintel_lang.ts -acodec copy -vcodec copy -strict -2 -y -f mpegts 'srt://192.168.4.43:8081?pkt_size=1316&mode=caller'
ffmpeg -fflags +genpts  -re -i sintel_lang_2000k.mp4 -acodec copy -vcodec copy -strict -2 -y -f mpegts 'srt://127.0.0.1:8081?pkt_size=1316&mode=caller'
```

Simple receiver command

```
gst-play-1.0 srt://:8081
```

Only when I use gstreamer as a caller do I get problems right away. Do I file a bug with them then ?

```
gst-launch-1.0 filesrc location=sintel_lang.ts ! tsparse set-timestamps=1 smoothing-latency=40000000 ! chopmydata step-size=188 min-size=188 max-size=1316 ! srtsink uri=srt://127.0.0.1:8081
```

**Comment by danrossi** [comment]
A remote test of ffmpeg produces the problem sadly. I'm not sure where the latency is needed for ffmpeg sender

```
22:05:43.755167/ffmpeg*E:SRT.d: SND-DROPPED 19 packets - lost delaying for 1026ms
22:05:43.799042/ffmpeg*E:SRT.d: SND-DROPPED 6 packets - lost delaying for 1037ms
22:05:43.851925/ffmpeg*E:SRT.d: SND-DROPPED 41 packets - lost delaying for 1068ms
22:05:43.873842/ffmpeg*E:SRT.d: SND-DROPPED 19 packets - lost delaying for 1024ms
[srt @ 0x56148fe11400] Operation not supported: Invalid socket ID.
av_interleaved_write_frame(): Unknown error occurred
Error writing trailer of srt://13.211.34.61:8081?pkt_size=1316&mode=caller&latency=2000: Unknown error occurred
```

**Comment by danrossi** [comment]
I just figured out this test fails with ffmpeg, because the upload traffic is greater than what the WAN can handle. reducing the bitrate to an extremely small size worked. I could not find how to configure latency and send buffers properly. It doesn't explain gstreamer's  issues locally though.
