### ISSUE TITLE
Suggestion: API function to indicate how long until first/next packet can be read by the receiver

### ISSUE THREAD

**Issue by oviano** [Haivision/srt#660]
If I am understanding things correctly, you can configure a latency of up to 8000ms, and in this case the receiver would be expected to wait 8s from the time the first encoded packet is fed to the socket by the sender.

Would it be possible to be able to call a function on the receiver to determine when the first (or next?) packet is expected to be available?

This would allow a "Buffering %" to be displayed on the player at the start when you've set the latency to something this high.

I realise I could probably estimate this myself knowing when the first packet on the sender side was sent, but it would seem more reliable to get this information directly from the receiver which I assume has a list of packets in the receive buffer along with when they are expected to be receivable by the application.

**Comment by oviano** [comment]
So on closer inspection it would seem that the stat field msRcvBuf provides what I am looking for.

**Comment by maxlovic** [comment]
@oviano `msRcvBuf` should tell the timespan in ms of the data in the receiving buffer.
It may be used to estimate the buffering, but it is not the time until the data can be read.
You might use it together with the known latency, and I think it will give you more or less accurate value. However, I asume the full buffering will have a timespan like (latency - RTT/2).
Requires review though.

**Comment by oviano** [comment]
Yes I tried this and it works pretty well. Good enough for what I need it for anyway, which is just a rough indication of how long until the buffer will be full when I've set a large latency value.

**Comment by maxlovic** [comment]
@oviano Good. Then probably we do not need to introduce additional statistical measure for that. Can close this issue then?

**Comment by oviano** [comment]
Yes, this can be closed. If anyone needs to to display a kind of buffering % then hopefully this thread provides a reference.
