### ISSUE TITLE
I added msLastRTT which is different from msRTT (which is a weighted average), is this useful?

### ISSUE THREAD

**Issue by oviano** [Haivision/srt#665]
In my player application I wanted to be able to open a test SRT connection to the server purely to measure RTT. So I opened a connection in live mode, and had the server send a ping packet every 5s.

I found that across LAN the msRTT stat would start off at something like 70ms and gradually drop down over time to the expected 1ms. But every time, a new connection would start high before reaching it's true value over something like 60s.

I found that this was because it is initialised to a higher value, and then uses the formula msRTT = (7 * msRTT + rtt)/8 to gradually tend towards the actual value (rtt).

I guess this is an artefact of my ping being infrequent (every 5s), and by sending a constant stream of data I expect it would reach the accurate value more quickly.

However, I don't want to send a constant stream of data just to measure the ping, so I have added a msLastRTT stat which is the actual last RTT value rather than the weighted average.

Would a patch be useful for this?

**Comment by jeandube** [comment]
From memory SRT initializes RTT to 100ms and calculates a moving average using  the last 7 sampled RTTs 
RTT are calculated with the ACK/ACK-ACK exchanges. SRT cache the RTT measured for a peer address and initializes it to the cached value upon reconnection. I don't think there is actually an API to initialize RTT (would an application cache the last RTT for a peer and persist it between app restarts).

**Comment by oviano** [comment]
Yes so I just followed the same pattern exactly with msLastRTT (and m_iLastRTT) except 1) it is initialised to zero and 2) it gets set directly to the latest RTT instead of a moving average.

It works as I would expect, but not sure if it is useful to anyone else!

**Comment by maxlovic** [comment]
@oviano 
It might have been good to have last reported RTT, but it will require changes to SRT API, and the appliance of last reported RTT is quite narrow.
SRT performs IIR filtering on RTT to have more stable values, as RTT measurement is used to control sending rates, estimate flow window (number of packets in flight), congestion window, etc. For instant measurements with out-of-the-library appliances better to use `ping`.
So I would say that adding it to SRT just to have this value does not make sense.

Thanks for reporting anyway.
I will close the issue. Would you have additional point on the topic, please do not hesitate to reopen.

**Comment by oviano** [comment]
It’s fine, I will keep this change in my local branch as using ping from code to time the connection that I already have open is a way more complicated solution for me.
