### ISSUE TITLE
SRTO_LINGER, SRTO_MAXBW and SRTO_UDP_SNDBUF default values != "SRT recommended" values

### ISSUE THREAD

**Issue by oviano** [Haivision/srt#667]
It might be more logical if the API documentation specifically recommends certain settings if they were also the default?

https://github.com/Haivision/srt/blob/master/docs/API.md

**Comment by maxlovic** [comment]
@oviano Thanks for reporting. We have this on out list.

**Comment by ethouris** [comment]
Summary:

1. `SRTO_LINGER`. Type: `linger { bool l_onoff, seconds_t l_linger }`.
    * Recommended: `{ off, 0 }`
    * Default: `{ on, 180 }`
2. `SRTO_MAXBW`. Type:  `int {bits/s}` with trap repr: `0`: use `SRTO_INPUTBW`, `-1`: unlimited
   * Recommended: 0
   * Default: -1
3. `SRTO_UDP_SNDBUF`. Type: `int {size in bytes}`
   * Recommended: `1024*1024`
   * Default: `65536` (64*1024)
4. Worth mentioning: `SRTO_UDP_RCVBUF` Default: `8192[rcv-buffer] * 1500[mss]`.
5. Worth mentioning: `SRTO_INPUTBW` Default: `0`. This is a trap repr which defines automatically sampled input bandwidth.

My first thoughts about this:

1. Linger: in Live mode it can be off - in Live mode the "proper closing" of the transmission is not predicted, any interrupt is treated as abnormal. Another matter is file mode. Might be that this option should be included in the `SRTO_TRANSTYPE` setting.

2. Maxbw: The default is -1 and it should be. Not sure why there's recommended `0`, which means that the bandwidth shape should follow the measured input bandwidth, which is preset by `SRTO_INPUTBW` option. What is interesting, its default is 0, which means that the bandwidth should follow the measurement of the input with overhead configured in `SRTO_OHEADBW`, which is default `25` (in percent of the bandwidth).

3. I believe this was kinda mistake. What is interesting, this is a value passed to `SOL_SOCKET/SO_SNDBUF` socket option, and there's a fallback value for the case od BSD/Mac systems only, which is `64000`. This fallback is applied silently in case of error reported by `::setsockopt`. This is moreover interesting provided that the size of this buffer should still be, I think, multiplicity of MSS.

**Comment by ethouris** [comment]
Here's a good explanation of the `SO_LINGER` option. It looks like the default value for this option is "off" ("`close()` returns immediately and any remaining sending continues in background"). Another possibility is when it's on and the value is:

* 0: `close()` terminates the connection and the data that were not sent so far are discarded
* N>0: `close()` is blocking for up to N seconds or when all remaining scheduled packets are sent, whichever comes first

https://notes.shichao.io/unp/ch7/#so_linger-socket-option

**Comment by maxlovic** [comment]
Your proposal on the linger option is the way we should go.
Linger: in Live mode - 0. File transfer mode - 180.
Not sure if 3 minutes makes sense. Might be better to reduce. But that is a different point of discussion.

**Comment by ethouris** [comment]
Status: Linger and MAXBW is now fixed. We need some sensible explanation for `SRTO_UDP_SNDBUF`, as the default value should rather be not directly specified, as it is the system default.
