### ISSUE TITLE
Feature Request: be able to set socket option for COMM_RESPONSE_TIMEOUT_US and COMM_RESPONSE_MAX_EXP

### ISSUE THREAD

**Issue by oviano** [Haivision/srt#672]
I have noticed a weird thing happening.

My client app opens two connections on different ports to my server app. One is a "control" connection and uses SRTT_FILE in non-message API, so similar to TCP. The other is a "stream" connection operating in SRTT_LIVE mode.

On a more lossy connection, e.g. 4G, I find that my SRTT_LIVE connection copes fine, but my SRTT_FILE connection, which is mostly idle (except for the client sending a message every 60s) sometimes gets dropped by the server.

In the heavy logging trace I can see on the server that it receives SRT keepalives every 1s up to a point, and then doesn't report receiving any more, so eventually EXP TIMER count reaches 16 and when 5s has passed the connection is dropped. This is reported cleanly on the client by a shutdown control message (all keepalives are received up to that point on the client), so clearly the server can still reach the client, if not the other way around.

I just wondered if this was an edge case that hadn't been tested much, i.e. using the SRTT_FILE mode, with an idle connection. With TCP this would stay up for hours, but maybe with SRT I need to add some additional messaging at my application level to keep things going, so even if the SRT internal keepalives don't always get through, then other messages might?

It just seems strange that it is the idle connection that mostly gets dropped, whereas the live connection mostly deals with the packet loss without losing connection, perhaps because there is so much more data being transferred that sooner or later an ACK for this data gets received so the EXP TIMER 16/16 + 5s situation never hits?

**Comment by maxlovic** [comment]
@oviano To check that we are on the same page. After some time the client and the server stop exchanging with keepalive messages, right? I ran a quick experiment with connecting two `srt-live-transmit`'s without exchanging the data, and they keep exchanging with keepalive messages for at least 3 minutes (the time of the test).
What do you think is the reason for those keepalive messages stop sending?

**Comment by oviano** [comment]
The client continued receiving keepalives until it suddenly received a shutdown control message.

The server stopped receiving keepalives and when the exp timer hit 16 and 5s had passed it closed the connection (which was why the client received the shutdown).

At the same time, on a different port and connection a live stream continued with no issues.

It repeated pretty reliably yesterday (not tried since).

My theory was that the live stream data required ACKs to be exchanged so even when packets dropped sooner or later retransmits etc would get through and reset EXP TIMER.

But with the idle connection I assume the keepalives don’t retransmit if lost/not received so if you lost enough in a row the connection could break more easily than with an active live connection.

But it’s just a theory...

**Comment by maxlovic** [comment]
@oviano Can you please provide tcpdump capture (pcapng) and heavy logs for that channel? Otherwise it is hard to know what happens.

> The client continued receiving keepalives until it suddenly received a shutdown control message.

Was it the server who sent the shutdown .What was the reason? Was it before it has stopped receiving keepalive messages or after?

**Comment by oviano** [comment]
Yes the server sent the shutdown because it had not received keepalives from the client for about 5s and the EXP TIMER had hit 16/16.

I will set things up again with heavy logging and get some logs.

**Comment by oviano** [comment]
So here are the SRT logs. This is slightly different to described above though, in that both connections dropped here, but I'm including it because it follows the same pattern of the client continuing to receive data but the server being unable to receive the data (on either connection) from the client when it enters this state.

My application reported the disconnection at 11:39:17, and you can see corresponding activity in both logs at that time.

Note that there would have been two active connections at this time;  the one that disconnected (SRTT_FILE) connecting through port 8090 and the streaming one (SRTT_LIVE) connecting through port 8091.

[srt_server.txt](https://github.com/Haivision/srt/files/3130870/srt_server.txt)
[srt_client.txt](https://github.com/Haivision/srt/files/3130889/srt_client.txt)

**Comment by oviano** [comment]
So as a test I increased COMM_RESPONSE_MAX_EXP and COMM_RESPONSE_TIMEOUT_US to much higher values (I tried 128 and 60s) and observed the same thing occurring but the EXP TIMER count only reached 29 before some data finally arrived.

Ok, so that's not going to work too well if you want a really low latency connection, but in this case I'm using a high latency (4-8s) because the client is on 4G, so raising these timeouts is ok.

I'm tempted to say that when using SRT in this scenario (and I don't think this what you guys have really targeted?) i.e. a bit of a flakey mobile connection, then the connection timeouts are a bit too harsh as they are disconnecting before the stream has really become choppy - especially when you have chosen a high latency.

**Comment by maxlovic** [comment]
@oviano 
> So as a test I increased COMM_RESPONSE_MAX_EXP and COMM_RESPONSE_TIMEOUT_US to much higher values (I tried 128 and 60s) and observed the same thing occurring but the EXP TIMER count only reached 29 before some data finally arrived.

So you are saying that for 4G network the connection timeout being at least 30 sec (currently 5 sec), solves the connection break issue you have? Does it mean that the network you work with has that high latency?

If increasing the time to live works for you, then probably having those options configurable will fit your needs.

**Comment by oviano** [comment]
Yes, that's what I have concluded.

My code looks like this:

    static const int COMM_RESPONSE_TIMEOUT_US = 40*1000*1000; // 40 seconds
    static const int COMM_RESPONSE_MAX_EXP = 128;

I haven't seen the issue since, it's been very stable.

Previously it one or both of the connections would be broken by the timeout before I'd seen any real problems with the video stream. I believe this is because I am using a high latency value (4-8s).

I agree making it a configurable option would be the best solution.

**Comment by maxlovic** [comment]
@oviano Please rename this issue to feature request then.

**Comment by ethouris** [comment]
#719 - but this makes only the response timeout configurable, not max exp number. I hope this should be enough.

**Comment by maxlovic** [comment]
@oviano Do you think a socket option instead of `COMM_RESPONSE_MAX_EXP` is still needed?

**Comment by oviano** [comment]
I think this is ok, I assume even if MAX_EXP has been reached then it won't break the connection until the timeout has been reached, correct?

**Comment by maxlovic** [comment]
Correct. No responce from the peer for (`COMM_RESPONSE_MAX_EXP` x 10 ms) is the first condition, and no response for `SRTO_PEERIDLETIMEO` is the second condition to consider the connection expired.
