### ISSUE TITLE
procdump64 reports tons of exceptions, not sure if that is to be expected?

### ISSUE THREAD

**Issue by oviano** [Haivision/srt#674]
I use ProcDump64.exe on Windows to create a dump if my application crashes. Since integrating SRT the procdump output is full of these lines:

[12:18:02] Exception: E06D7363.?AVCUDTException@@

Normally it doesn't output anything unless the application crashes. I couldn't see a way to stop procdump producing these, not sure if this is an SRT issue, a procdump issue, or not an issue.

**Comment by manueldev** [comment]
![image](https://user-images.githubusercontent.com/3420027/57184114-776ecf80-6e84-11e9-9fea-7ccf0289e811.png)
In visual studio they also appear.

**Comment by maxlovic** [comment]
Those are handled exceptions, that SRT core throws and catches. They are handled inside the core, and you will not catch them outside of the API.

**Comment by oviano** [comment]
Ok thanks.
