### ISSUE TITLE
LoadBalancing the traffic

### ISSUE THREAD

**Issue by ba1dr** [Haivision/srt#681]
I am writing a service (Python backend with GStreamer) which will accept incoming video streams from multiple clients. Video will be processed (does not matter how).

To reduce the load to one server I am going to have many servers, but would like to have one entry point for all clients. This is like HTTP and load balancing across multiple upstreams (session-aware).

I cannot find any existing solutions to do this with SRT traffic - could you describe whether it is possible at all?

**Comment by ethouris** [comment]
It is possible, but may be complicated and there's currently no publicly available solution for it.

You can create for it a kind of tunnel, which will listen on given port and will flip the traffic into a selected server. This is quite simple. Just note that this will function as a real SRT listener, which means that if the stream is encrypted, this will have to decrypt it exactly there. The "latency penalty" for every such intermediate point should be "paid" as well - this intermediate point will eat up this latency, and the connection from this intermediate point to the target server will suffer another latency, although the latter might be set to a very low value, if this is within a local network.
