### ISSUE TITLE
srt-tunnel app in v.1.3.2

### ISSUE THREAD

**Issue by rmsoto** [Haivision/srt#682]
Hello all!

I´m wondering which is the use for srt-tunnel app in v1.3.2

```
ovesrt@ovesrt-ji4-001:~/srt_132/srt$ ./srt-tunnel
 Usage: ./srt-tunnel <listen-uri> <call-uri>
```

Thanks!

**Comment by maxlovic** [comment]
Hi @rmsoto.  It simply passes the transmission from a given endpoint to another endpoint in both directions. Check out the [SRT Tunnel doc](https://github.com/Haivision/srt/blob/master/docs/srt-tunnel.md).

**Comment by rmsoto** [comment]
Ups, I didn´t check the docs folder, my mistake!!! thanx!
