### ISSUE TITLE
On Mac, compile for Android, Error: 'mach/mach_time.h' file not found

### ISSUE THREAD

**Issue by Edward-Wu** [Haivision/srt#694]
hi, 
I compile the SRT library for Android on MAC following the docs/Android/Compiling.md. But get the same error info :
srt/srtcore/common.cpp:62:16: fatal error: 'mach/mach_time.h' file not found
#include <mach/mach_time.h>

In mkall file, there is a following line:
toolchain=$NDK/toolchains/llvm/prebuilt/linux-x86_64

I download the NDK r19, but there's no linux-x86_64 folder in prebuilt folder, only darwin-x86_64 folder. so I change the linux-x86_64 to darwin-x86_64, as following :
toolchain=$NDK/toolchains/llvm/prebuilt/darwin-x86_64

after exec /bin/bash mkall > build.log, I get the error info:
srt/srtcore/common.cpp:62:16: fatal error: 'mach/mach_time.h' file not found
#include <mach/mach_time.h>

Can you help me ?

**Comment by Edward-Wu** [comment]
and I found out a clue in the log info:
-- DETECTED SYSTEM: DARWIN;  OSX=1
should be this statement OSX=1, but I don't knows how to resolve it.

**Comment by ethouris** [comment]
Sorry, but the Android support has been provided by some volunteers here. All I know is that `cmake` must recognize the crosscompiling environment correctly, that is, it should get the correct value of `CMAKE_PREFIX_PATH`.

The "DETECTED SYSTEM" entry also depends on the value of `CMAKE_SYSTEM_NAME`. Might be that you need this value also tricked.

Not sure how the Android build providers have done it so far, but might be that the Android builds were done so far on Linux only, so they haven't even noticed that this value is mistakenly taken from the host, not target system. I'd experiment with adding `-DCMAKE_SYSTEM_NAME=Linux`.

I tried to find any cases on the net and it seems to be quite a rare case that someone is trying to cross-compile for Android on Mac. There seem to be also problems with cmake there.

**Comment by ethouris** [comment]
TO DO: Install Android SDK on Mac and try these steps.

**Comment by fallenhaivision** [comment]
@ethouris I'm in the process of getting FFMpeg, openSSL, and SRT compiled on my Mac this week. Switching to the latest NDK (ie from GCC to Clang). I will let you know what I find.

**Comment by lisafei** [comment]
hi,
I compile static srt by these steps for android.
after  openssl step, set export params,  /bin/bash mksrt,

./configure --use-openssl-pc=OFF --CMAKE_PREFIX_PATH=/opt/work/srt/android --CMAKE_INSTALL_PREFIX=/opt/work/srt/android 
Running: cmake . -DUSE_OPENSSL_PC=OFF -DCMAKE_PREFIX_PATH=/opt/work/srt/android -DCMAKE_INSTALL_PREFIX=/opt/work/srt/android
-- BUILD TYPE: Release
-- LOGGING: ENABLED
-- USE_BUSY_WAITING: OFF (default)
-- No WITH_COMPILER_PREFIX - using C++ compiler /usr/bin/c++
-- WARNING: pkg-config has incorrect prefix - enforcing target path prefix: /opt/work/srt/android
-- SSL via pkg-config: -L /opt/work/srt/android/lib64 -I /opt/work/srt/android/include -l;ssl;crypto
-- ENCRYPTION: ENABLED, using: openssl libcrypto
-- SSL libraries: ssl;crypto
-- COMPILER: GNU (/usr/bin/c++) - GNU compat
-- NOTE: GCC 4.8.5 is detected with default C++98. Forcing C++11 on applications.
-- STDCXX_SYNC: OFF
-- C++ STD: Forcing C++11 on applications
-- DETECTED SYSTEM: LINUX;  LINUX=1
-- APP: srt_virtual: using default C++ standard
-- ADDING TRANSITIVE LINK DEP to:srt_static : -lpthread 
-- INSTALL DIRS: bin=bin lib=lib64 shlib=lib64 include=include
-- APPS: ENABLED, std=11
-- DEVEL APPS (testing): DISABLED
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/work/srt/srt

is that true for android?
The env:
[root@localhost srt]# export -p
declare -x AR="arm-linux-androideabi-ar"
declare -x AS="arm-linux-androideabi-as"
declare -x CC="armv7a-linux-androideabi24-clang"
declare -x CFLAGS="-fPIE -fPIC"
declare -x CMAKE_SYSTEM_NAME="ANDROID"
declare -x CXX="armv7a-linux-androideabi24-clang++"
declare -x GOBIN="/root/gobin"
declare -x GOPATH="/root/App/Go"
declare -x GOROOT="/root/go"
declare -x HISTCONTROL="ignoredups"
declare -x HISTSIZE="1000"
declare -x HOME="/root"
declare -x HOSTNAME="localhost.localdomain"
declare -x LANG="zh_CN.UTF-8"
declare -x LD="arm-linux-androideabi-ld"
declare -x LDFLAGS="-pie"
declare -x LD_LIBRARY_PATH=":/usr/local/ffmpeg/lib:/usr/local/lib64:/usr/local/lib"
declare -x MAIL="/var/spool/mail/root"
declare -x OLDPWD="/opt/work/srt"
declare -x PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/usr/local/ffmpeg/bin:/root/go/bin:/root/bin:/opt/android-ndk-r20b/toolchains/llvm/prebuilt/linux-x86_64/bin"
declare -x PWD="/opt/work/srt/srt"

how can i build libsrt.a for andorid successfully?

**Comment by maxsharabayko** [comment]
Hi @lisafei 
Based on what you've shared, build files were generated successfully. You need to run build. Probably with `make`.
See also [Android Build Instructions](https://github.com/Haivision/srt/blob/master/docs/Android/Compiling.md).

**Comment by lisafei** [comment]
Hi @maxsharabayko 
Thanks for  attention.
I found the solution by try to clean the CMakeFiles Directory. After clean it, the compiler information changed, worked. 
It's a happy result.

**Comment by maxsharabayko** [comment]
@lisafei Glad to hear! Thanks for reporting back.
Closing the issue then.
