### ISSUE TITLE
srt-live-transmit ignores timeout settings

### ISSUE THREAD

**Issue by alexdjca** [Haivision/srt#698]
Hi all,

In Linux Ubuntu 18 Launching srt-live-transmit like this:

/usr/local/bin/srt-live-transmit -t 10 -timeout-mode 1 -r 10000 -s 10000 udp://x.x.x.x:xxxxx "srt://y.y.y.y:yyyy?passphrase=xxxxxxxxPassword3&mode=caller"

No matters if i set timeout-mode to 1 or 0, in any case the application resets after 10 seconds.

At the same time if i don't set timeout and stop the listener, the caller detects the disconnection but just stays appended sending data and never stops.

Is it a expected behaviour or something changed?

thanks in advance
Alex

**Comment by maxlovic** [comment]
Which OS? Timeout is not working on Windows.

**Comment by alexdjca** [comment]
max in Linux... sorry but my message was sent erroneously before being finished :) I've just edit it

**Comment by maxlovic** [comment]
When you don't set a timeout, auto-recommect mode is in operation.
Command-line options: `"a", "auto", "autoreconnect"`.
So you keep receiving data from UDP socket, but have nowhere to send it.

**Comment by maxlovic** [comment]
> No matters if i set timeout-mode to 1 or 0, in any case the application resets after 10 seconds.

`-timeout-mode=1` is expected to cancel the timeout if the connection was established.
If the connection was established, but the application resets, then this is an issue.

**Comment by maxlovic** [comment]
Reproduced. Missing timeout canceling if target has connected.
