### ISSUE TITLE
Create example for using this for low-latency screen sharing

### ISSUE THREAD

**Issue by nh2** [Haivision/srt#7]
I would be very interested to see if this can be used for high quality low latency screen sharing.

For example with `ffmpeg -y -f x11grab`.

**Comment by nitrat7** [comment]
hmm...
transmitting udp-stream
ffmpeg -f avfoundation -i "1"   -fflags nobuffer -flags low_delay  -vcodec libx264  -vb 500000 -g 60 -vprofile high422 -vbsf h264_mp4toannexb -strict experimental -f mpegts udp://127.0.0.1:10000
(here for Mac)
will produce too much latency?

**Comment by matiaspl** [comment]
I'd say the latency will be "as usual". SRT is only about transport so it cannot do any good for encoding. 

For low latency use -preset ultrafast, -profile baseline and -tune zerolatency. Or even better - use an intra-frame codec (or I-frame only H264).

**Comment by nh2** [comment]
For a `gstreamer` based pipeline I use for screen sharing, I have the feeling that encoding is fast enough when given the right flags, but that transport is the key problem -- that's why I openend this issue, I'd be very interested if the overall experience is better when running over srt.

**Comment by matiaspl** [comment]
I don't think SRT will be any better than ffmpeg's udp:// or tcp:// in this regard. Stop me if I'm wrong, but the key feature of SRT is the reliability.

**Comment by nh2** [comment]
> Stop me if I'm wrong, but the key feature of SRT is the reliability.

From how I read http://www.srtalliance.org, that seems to be right, but regarding

> I don't think SRT will be any better than ffmpeg's udp:// or tcp:// in this regard.

That's what I want to find out: My ffmpeg-UDP based H.264 screenshares sometimes suffern from ugly corruption when packet loss happens, and the TCP based ones have very bad latency. I'd like to find out if SRT can help here.

**Comment by ethouris** [comment]
If you make this UDP output to localhost:5555 (for example), and then use:

   ./stransmit udp://:5555 srt://remote.host.com:5000

then your local UDP should be reliable enough, and then you take advantage of SRT for transmitting over a less reliable network.

If you can make the output of the streaming command line redirected to the standard output, you can also send it to `stransmit` command through a pipe, just use then `file://con` as a source URI.

**Comment by maxlovic** [comment]
@nh2 
**ffmpeg** also supports SRT (you need to build it with `-enable-protocol=libsrt` `--enable-libsrt`).
You can get a list of available protocols with `ffmpeg -protocols`. `srt` should be listed both as an input, and as an output protocol.
With a built in SRT you can specify is as an output like this:
```
"srt://<destination_ip>:<destination_port>"
```Probably it would be a good idea to use MPEG-TS as a container `-f mpegts `.

**Comment by nh2** [comment]
@maxlovic 

Ah, cool! I'll try that out and report back.

**Comment by nh2** [comment]
@maxlovic Do you happen to know which gstreamer pipeline element I can use on the receiving/decoding side, if that exists? Because in my tests so far I use `ffmpeg` for sending and gstreamer for receiving.

**Comment by maxlovic** [comment]
@nh2, I haven't tried SRT with gstreamer, but they should have support for it.
See [the release notes for 1.14](https://gstreamer.freedesktop.org/releases/1.14/).
Please share your final results.

**Comment by maxlovic** [comment]
@nh2, thank you for sharing and providing the detailed description. Do you mind if we'll put it in our docs?

**Comment by ethouris** [comment]
Can this be done bidirectional? Just sayin' :)

**Comment by nh2** [comment]
> Do you mind if we'll put it in our docs?

@maxlovic I don't mind at all! In some of the gstreamer tickets it's also being discussed to add more concrete examples, so later you may want to just want to refer to these (especially when for 1.16 the element pipeline names/arguments will change), but until then having the concrete examples in the docs makes sense.

> Can this be done bidirectional? Just sayin' :)

@ethouris Haven't tried yet; would there be a benfit to do it bi-directional vs just each side starting a screenshare? Having the two separate does seem to have some benefits, e.g. that multiple clients can join 1 person's screenshare, and that you can terminate one without terminating the other.
