### ISSUE TITLE
[question] logs stats

### ISSUE THREAD

**Issue by Litrona** [Haivision/srt#704]
Anyone could explain me the difference in srt-live-transmit's stats among :
1- LOST PKT
2- REXMIT
3- DROP PKT
Will 1 include 2 + 3 ? And 2 includes 3 ?

Thanks in advance.
Lit/

**Comment by maxlovic** [comment]
1. LOST packet is a packet, that was lost during transmission, and is expected to be retransmitted.
2. Retransmitted packet - the actual packets retranmsissions count.
3. Packet dropped, meaning it is considered lost and will not be retransmitted, usually because it is too late to retransmit it within the specified latency.

**Comment by Litrona** [comment]
@maxlovic 
OK, Thanks.
Does BANDWIDTH indicates the real available bandwidth in the link ?

**Comment by maxlovic** [comment]
Estimated overall bandwidth of a link. But do not rely too much on it. as it has a certain inaccuracy.

**Comment by jatinderkumargupta** [comment]
Hello,

Does -s command-line option of stransmit, return statistics reports to the standard output, in case <input-uri> is UPD and <output-uri> is also UDP?

I want to get stats, similar to what I get in case of SRT.
Is there any way to get that?

Regards

**Comment by maxlovic** [comment]
Hi @jatinderkumargupta 
> Does -s command-line option of stransmit, return statistics reports to the standard output, in case is UPD and is also UDP?

No, the statistics is only for SRT connection.

**Comment by jatinderkumargupta** [comment]
Thanks @maxlovic

**Comment by AlexandreLicinio** [comment]
hi, @maxlovic could you please explain to me what is *mbitRate* in logs stats ? Even if i down the muxbitrate of the encoder, the value still the same.

![image](https://user-images.githubusercontent.com/10514064/60650950-71c24580-9e45-11e9-8e5e-51cfdeb94984.png)

thanks

**Comment by maxlovic** [comment]
@AlexandreLicinio mbitRate is sending/receiving rate in Mbits/s.
> Even if i down the muxbitrate of the encoder, the value still the same.
You decrease the encoder bitrate, but still get the same sending rate? You can check the network utilization to have another point of comparisson.

**Comment by AlexandreLicinio** [comment]
yep @maxlovic when the bitrate goes low (2mb/s), the router shows 2mb/s but mbitRate still 7 or 8.

![image](https://user-images.githubusercontent.com/10514064/60654202-cf599080-9e4b-11e9-9b0a-ad234c13bbe5.png)

![image](https://user-images.githubusercontent.com/10514064/60654698-c74e2080-9e4c-11e9-8edd-bfa248990bef.png)

Srt stats you see in the picture is related to a listener (for the decoder) on each side

**Comment by maxlovic** [comment]
@AlexandreLicinio How often do you get an updated value for mbitRate?

**Comment by AlexandreLicinio** [comment]
i refresh the value every 1000 with ```./srt-live-transmit srt://192.168.1.29:3469?mode=listener udp://127.0.0.1:3469 -t:-1 -v -pf:json -s:1000 -f```` and i refresh every 2sec the value in browser.
