### ISSUE TITLE
[docs] Add missing socket options to API.md

### ISSUE THREAD

**Issue by maxlovic** [Haivision/srt#721]
Socket options currently missing in [API.md](https://github.com/Haivision/srt/blob/master/docs/API.md):
- [ ] `SRTO_STRICT_ENC`
- [ ] `SRTO_SNDDROPDELAY`
- [ ] `SRTO_KMREFRESHRATE`
- [ ] `SRTO_KMPREANNOUNCE`

**Comment by ethouris** [comment]
Taking it
