### ISSUE TITLE
question about function CRendezvousQueue::updateConnStatus()

### ISSUE THREAD

**Issue by NKTelnet** [Haivision/srt#723]
the function CRendezvousQueue::updateConnStatus() will traverse all rendezvous connections for the same response and may call i->m_pUDT->processAsyncConnectRequest(rst, cst, response, i->m_pPeerAddr) for some rendezvous connections that are not related to the response.  i->m_iID does not equal to response.m_iID in some cases when i->m_pUDT->processAsyncConnectRequest(rst, cst, response, i->m_pPeerAddr) is called. Is it reasonable ?

**Comment by NKTelnet** [comment]
> the function CRendezvousQueue::updateConnStatus() will traverse all rendezvous connections for the same response and may call i->m_pUDT->processAsyncConnectRequest(rst, cst, response, i->m_pPeerAddr) for some rendezvous connections that are not related to the response. i->m_iID does not equal to response.m_iID in some cases when i->m_pUDT->processAsyncConnectRequest(rst, cst, response, i->m_pPeerAddr) is called. Is it reasonable ?

I know processAsyncConnectRequest() will do the retransmission work. But it seems that processAsyncConnectRequest() needs to check response.m_iID and according to the response.m_iID to do different jobs.

**Comment by ethouris** [comment]
Please cite in which position of the code this is so.

What I remember is that the Socket ID value from the packet header is the DESTINATION socket ID, which should match the local socket ID at the agent. Peer's socket ID is only present in the handshake messages, where it's treated as a SOURCE socket ID. When the latter is compared to any local socket ID, it's definitely wrong.
