### ISSUE TITLE
SYNC Streams via SRT

### ISSUE THREAD

**Issue by garybruckheimer** [Haivision/srt#73]
We are getting more and more SRT fans :)

We have seen that Haivision demonstrate video that stayed in sync:
http://www.haivision.com/products/secure-reliable-transport

This is amazing and i´m thinking how you did this Haivision. I have an Live HEVC Encoder SoC which is able to generate a h.264 and HEVC at the same bitrate/resolution/fps etc.. Cause the timing of the encoding (preset vs. motion estimation) are different in timestamps, but not too far to each other, max. maybe 80-120ms.

I can get set both streams in MpegTS via UDP to grab them both.

How can SRT help me to sync both streams? I do not find any information about syncing in SRT or i oversee it yet. 

When you think that you can mix SRT audio an video channels with an big "sync" buffer, then the possibilities for IPTV are endless.
 
Anyone?

**Comment by heidabyr** [comment]
Hi Gary,

the Open SRT protocol is completely content agnostic and shuffles through whatever you feed it. The demo we did on stereo stream synchronization was a custom layer we put on top of the SRT transmission itself. It was multiplexing multiple network streams before sending it over the SRT link, demultiplexing it on the receiver side. Therefore the streams kept in sync on a network level. This demo project isn't included in the Open SRT package though.

Thanks,
Marc

**Comment by garybruckheimer** [comment]
Marc,

i thought like this. 

Today i tried more experiments. I´m impressed how fast i got a stable demo ready with some very small changes in SRT example tools.

Example:
I grabed a RTMP live Stream at 12.000Kbit, replaced the audio with a AAC demo file, muxed it together, transcode it to 1800kbit HEVC, piped it again with SRT, send to my friends in the US over SRT. 

They received it over the SRT, transmux again from SRT to UDP and send to 4 monitors at the same time in 4 rooms. All in sync.

It need some times before for developers before you understand what you can do now with SRT. With MpegTS and the mapping channels, i can group and mixed as many channels as i want. I will try now an multiplex with h.264 and HEVC in one ts with different programm groups and different channels. 

Crazy
Gary

**Comment by heidabyr** [comment]
Ha, that's awesome!

**Comment by ethouris** [comment]
I think the `srt-multiplex` (formerly `siplex`) application should be able to do this job. If so, this issue can be considered complete.
