### ISSUE TITLE
High PCR Interval and Accuracy error rates

### ISSUE THREAD

**Issue by machship-mm** [Haivision/srt#737]
I have been trying to get an SRT stream to work from an iPhone to a Nimble Streaming server in AWS then to VLC, however, I’m continuously running into PCR errors, both priority 1 and priority 2. 

Using Larix via the Nimble server in AWS,  we experience lots of P2 PCR errors. 

To try to avoid as much network as possible, I attempted to stream entirely locally.

To do this, I streamed my MacBook webcam from ffmpeg piped into srt-live-transmit and back out as an SRT stream which I consumed in VLC on the same machine. Recording that stream and analysing the stream would still show PCR errors, especially priority 2 PCR Interval and Accuracy errors. Short streams around 20 seconds would give PCR interval errors around approx 150 and PCR accuracy errors around 100, and longer streams around would give PCR interval and accuracy errors > 1000.

I’ve tried every URI switch I can find, including latency, bandwidth, etc. to no avail; nothing I’m doing is making a difference. 

I’m running SRT v1.3.2 and the latest VLC (FYI I also saw these when I piped the live stream directly to file). I’ve tried my best to find any hints in related issues but I can’t seem to progress.

If someone here could assist me, that would be great.

Any info you need, including logs or any packet captures, etc. just let me know how to run them and I’ll get them for you.

**Comment by maxlovic** [comment]
Hi @machship-mm 
So far it does not look like an SRT issue. The SRT protocol does not do any modifications to the source streram, it only transmits the data.

**Comment by ethouris** [comment]
Provided that you are using the transmission only locally, did you try to repeat this test with streaming via UDP?

**Comment by Spidey01** [comment]
I suspect this has to do with variations in packet arrival time and ordering.

E.g. if I feed UDP multicast -> srt-live-transmit -> SRT, or UDP multicast into a GStreamer pipe on another machine: warnings come from the tsdemux about continuity errors, that do not show up when feeding the source UDP directly to the same pipeline.

**Comment by machship-mm** [comment]
Sorry guys, this turned out to be an issue at the transmission end as suspected.
