### ISSUE TITLE
adding TTL to a multicast at receiver side

### ISSUE THREAD

**Issue by msanis** [Haivision/srt#74]
Hi
I am new to SRT and manged to make it working
On receiving end, i use the below command
./stransmit -v srt://:9000 udp://@225.6.220.41:3000

Can you tell me how to add TTL value to the multicast ?
i tried ./stransmit -v srt://:9000 udp://@225.6.220.41:3000?ttl=32 , but not working

**Comment by ethouris** [comment]
According to what is written in the source file (stransmit.cpp) the IP_TOS and IP_TTL options are exposed as "iptos" and "ipttl" parameters. Note that these options are available also for SRT sockets under the same names. Sorry that the socket options for UDP are here, whereas options for SRT sockets are in `common/socketoptions.hpp` file.

**Comment by msanis** [comment]
Thanks Ethouris. I will check this.

**Comment by msanis** [comment]
I tried various combinations, but still no luck with TTL of output multicast. (The output multicast seems to stay on default TTL 1)
i tried:
./stransmit -v srt://:9000 udp://@225.6.220.41:3000?ipttl=32
./stransmit -v srt://:9000 udp://225.91.11.1:6000?adapter=10.177.10.191?ipttl=32
./stransmit -v srt://:9000 udp://@225.6.220.41:3000 -ipttl:32

appreciate your help on this

**Comment by ethouris** [comment]
Wow, w8. I'm not sure if UDP output supports multicast at all. `-ipttl` is not provided as an option, it should be a parameter, like in the first one. And I also don't think there's `adapter` parameter used in UDP, but heck, it's theoretically reasonable. I'll try to test how stransmit supports multicast, just I need a bit more time because I'm now in progress with merging the new fantastic code for SRT.

**Comment by msanis** [comment]
Gr8. No rush, will wait for your further comment

i confirm the UDP output supports multicast as i can able to receive and play within same switch. Because of TTL vlaue 1 i am not able to propogate the multicast to other part of my network.

**Comment by ethouris** [comment]
The `IP_TTL` and `IP_MULTICAST_TTL` are distinct options. There has been added a fix which handles the second one - use them by parameters in the UDP URI: `ipttl` and `mcttl` respectively. So, the second one, for example, would be:

    ./stransmit -v srt://:9000 udp://@225.6.220.41:3000?mcttl=32

**Comment by ethouris** [comment]
According to the requirements, the fix has been finally resolved this way: There's a `ttl` option which sets both `IP_TTL` and `IP_MULTICAST_TTL` to the same value.

**Comment by msanis** [comment]
Great. We tested it and is working. Superb !!!!

**Comment by msanis** [comment]
Hi Ethouris

Seems on latest v1.2.3, mcttl and ipttl are missing which is causing the same multicast TTL issue on receiving end.
i checked stransmit.cpp and there are no refernce to mcttl

However on previous version mcttl are working

**Comment by rndi** [comment]
Hello @msanis ,

These two options have been merged into single "ttl" option with this commit: https://github.com/Haivision/srt/commit/35c1335469410a2e67bcb437d8d1b1ca9be38387

**Comment by msanis** [comment]
Thanks. This works well now
