### ISSUE TITLE
write statspf in json file instead append to the file 

### ISSUE THREAD

**Issue by AlexandreLicinio** [Haivision/srt#744]
Hi, 

Is there a way to write and not append to file all the stats ? In case we have srt running for days or weeks the json file is big and only the last dict contains what the stream does in real time.

Thanks

**Comment by maxlovic** [comment]
@AlexandreLicinio At the moment there is no way to do it.
You can modify the `PrintSrtStats` function if you need to overwrite the file.
Or you can print to pipe and process the stats whatever you want.

**Comment by AlexandreLicinio** [comment]
thanks @maxlovic yes could be nice to have -append or -overwrite. So yes i will modify ```PrintSrtStats``` 
cheers

**Comment by Widixo** [comment]
Hi,
do you mean PrintSrtStats function in transmitmedia.cpp ?

**Comment by maxlovic** [comment]
@Widixo Yes, e.g. replace `output << "{";` with `output < "{";` on [this line](https://github.com/Haivision/srt/blob/master/apps/transmitmedia.cpp#L115).

**Comment by Widixo** [comment]
thanks a lot, i add this to create a special file that wee need for a probe process :
ofstream alex;
alex.open ("probe.txt", ios::trunc);
alex << output.str() << std::flush;

Which is create a probe.txt file for Alex

Thx !
