### ISSUE TITLE
Example app connection rejected

### ISSUE THREAD

**Issue by NenadMihajlovic** [Haivision/srt#757]
Hi,

I am trying to test SRT with provided example files test-c-client.c and test-c-server.c .
I tried this with Client and Server on same machine with IP address from my NIC (network adapter). Tried to put Client on another machine in same local network but same issue.
Client is getting connection rejected error.
I am attaching logs from Client and Server.
In server log I see message RECEIVED negative socket id '-842150451', rejecting (PO
SSIBLE ATTACK) .
Please help.

Best regards.
Nenad
[Client.txt](https://github.com/Haivision/srt/files/3389713/Client.txt)
[Server.txt](https://github.com/Haivision/srt/files/3389714/Server.txt)

**Comment by ethouris** [comment]
Something is completely wrong there at library's compile time:
```
12:16:04.893297.N:SRT.c: HSREQ/rcv: cmd=1(HSREQ) len=12 vers=0x0 opts=0x3f delay
=120
12:16:04.920493*E:SRT.c: HSREQ/rcv: With HSv5 version must be >= 1.3.0 .
```

The value that is sent here is set from `m_lSrtVersion` field, which is set by default to `SRT_DEF_VERSION`, which is the value set from the preprocessor-defined `SRT_VERSION`, which is set in the `CMakeLists.txt` file here:
```
add_definitions(
	-D_GNU_SOURCE
	-DHAI_PATCH=1
	-DHAI_ENABLE_SRT=1
	-DSRT_VERSION="${SRT_VERSION}"
)
```
This variable is set in the beginning:
```
set (SRT_VERSION 1.3.2)
```

So, the only explanation is that this `SRT_VERSION` was somehow overridden or unset or I don't know, but  it has no format of "x.y.z", may be even an empty string. I can see that `SrtParseVersion` function had earlier some possibility to throw an exception in this case, but someone looxlike "fixed" it by making it return 0 - and here is why you have this `vers=0x0` in the log.

Did you really compile SRT using the standard procedure?

**Comment by NenadMihajlovic** [comment]
I was compiling with Visual Studio 2013.
And it was complaining that SRT_VERSION is not defined, so I defined it to some random value and later forgot about it. Sorry this was not careful from me :-) 
I defined it to 1.3.2 and now it is working fine.

Thank you for your help.
You can close this ticket.
