### ISSUE TITLE
Unsupported source type

### ISSUE THREAD

**Issue by tomasguirao** [Haivision/srt#765]
Hello,
I´m trying to send mpegts stream from http source. I have an chinese H264 encoder for hardware extern.. 

./srt-live-transmit http://192.168.100.201/main srt://:1234
Unsupported source type

Could you help me...
thank you

**Comment by maxlovic** [comment]
Hi @tomasguirao 
`srt-live-transmit` does not support http. Only UDP, SRT and `STDIN`.

**Comment by tomasguirao** [comment]
ops.. Thank You maxlogic..
And.. Can I capture this encoder source else?
thank you

**Comment by maxlovic** [comment]
You could try ffmpeg of [GStreamer](https://github.com/Haivision/srt/blob/master/docs/gstreamer.md).
