### ISSUE TITLE
Pixelad image in SRT transmission.

### ISSUE THREAD

**Issue by Panchitor** [Haivision/srt#767]
I have a problem receiving the image.
Currently from an RTMP source I send an image to an Nginx server, that server with FFMPEG I transform it into UDP.
This udp sent by SRT to another destination where I have an SRT in listening mode.
once I receive the SRT signal I transform it to UDP and with an OMXPlayer I play the UDP.
Here I see the image blurred or pixelated.

RTMP Source (1) ---- Internet ---- RTMP Server --- UDP: pkt_size? 1316 (2) --- SRT (3) --- Internet --- SRT (4) ---- UDP --- OMXPlayer (5) --- HDMI - Unstable image  .-

Commands in each line
1 - rtmp: // IP: 1935/lot/live
2 - ffmpeg -i rtmp: //127.0.0.1/lotevivo/live -c: v libx264 -c: a aac -preset ultrafast -f mpegts udp: //239.0.0.1: 5000? Pkt_size = 1316
3- ./srt-live-transmit udp: //239.0.0.1: 5000 srt: //192.168.192.111: 5000;
4 - ./srt-live-transmit -s: 200 srt: //: 5000 udp: //239.0.0.1: 5001? Mode = server
5 - os.system ('omxplayer -o hdmi udp: //239.0.0.1: 5001')

Could someone help me with the solution?

**Comment by maxlovic** [comment]
Hi. You can collect SRT statistics with, e.g.:
`./srt-live-transmit udp://239.0.0.1:5000 srt://192.168.192.111:5000 -s 200 -statsout stats-snd.csv -pf csv`
and check if there are any dropped packets.
If you find dropped packets, you would need to increase latency (e.g. `srt://192.168.192.111:5000?latency=2000` and on the receiving side too).
Otherwise the losses happen in UDP connection.

**Comment by maxlovic** [comment]
Also ffmpeg supports SRT (requires to be built with libsrt), so you could use something like
`ffmpeg -i rtmp: //127.0.0.1/lotevivo/live -c: v libx264 -c: a aac -preset ultrafast -f mpegts srt://192.168.192.111:5000`

**Comment by Panchitor** [comment]
Hi, you know that I have no losses, and if I put a retransmission by rtmp replacing the SRT, I get perfect !.
I tried to put latency only on the emitting side, I will try to put it on both. and I tell you.

With respect to ffmpeg -i rtmp: //127.0.0.1/lotevivo/live -c: v libx264 -c: a aac -preset ultrafast -f mpegts srt: //192.168.192.111: 5000

When I put it inside the nginx.conf below the app, I don't establish the connection to the other end, if I put it on the console I don't remember at this moment, but it was my first choice.

**Comment by maxlovic** [comment]
Pixelated image should mean losses. If you don't have losses in SRT, the it is in UDP
`udp: //239.0.0.1`.
> if I put a retransmission by rtmp replacing the SRT, I get perfect !

How does your pipeline look in that case? Like this?
RTMP Source (1) ---- Internet ---- RTMP Server --- Internet --- RTMP --- OMXPlayer (5) --- HDMI

**Comment by Panchitor** [comment]
This way it works perfect, I have it in production this format.
Currently, this is how you indicate:
RTMP Source (1) ---- Internet ---- RTMP Server --- Internet --- RTMP --- OMXPlayer (5) --- HDMI
But I wanted to replace the rtmp with SRT on the client.
as I put it before:
RTMP Source (1) ---- Internet ---- RTMP Server --- UDP: pkt_size? 1316 (2) --- SRT (3) --- Internet --- SRT (4) ---- UDP --- OMXPlayer (5) --- HDMI

Should I modify any of the files installed in the SRT folder?

**Comment by premultiply** [comment]
Please keep in mind that ffmpeg does not produce valid mpeg-ts streams (non-bursty) without proper pthreaded version and several additional parameters. This might be the reason for the problems.

**Comment by Panchitor** [comment]
What parameters should I add for a good performance?
I am reminded that when the RTMP source is a Vmix connected directly to the server, it works fine, there are some pauses and pixels, but when I send the vmix I connect to REstream.io and from there the server fails more often.-

There with these parameters in the ffmpeg could better, but which?

**Comment by premultiply** [comment]
You can find some hints on this page: https://github.com/jaskie/Server/wiki/Creating-perfectly-stable-CBR-MPEG-transport-stream

You may need some special equipment to verify ffmpegs output regarding ip packet timing and pcr accuracy.

**Comment by Panchitor** [comment]
Thank you very much for the help, but I don't have 8000kbps for the transmission. at most 2.5mb.
I transmit in 720P.-
How would the command be like with ffmpeg?
Anyway, the udp is local traffic, and the srt adapts to the correct internet bandwidth?

**Comment by Panchitor** [comment]
I attached the statistics files with the latency types.

On the server run:

ffmpeg -i rtmp: //127.0.0.1/loteriavivo/live -c: v libx264 -c: a aac -preset: v ultrafast -f mpegts udp: //239.0.0.1: 5000? pkt_size = 1316

Y

./srt-live-transmit -s: 200 -statsout stats-snd-lat2000.csv -pf csv udp: //239.0.0.1: 5000: pkt_size? 1316 srt: //192.168.192.110: 5001? latency = 2000

Client:

./srt-live-transmit -s: 200 srt: //: 5001 udp: //239.0.0.1: 5002

omxplayer -o hdmi udp: //@239.0.0.1: 5002


[stats.zip](https://github.com/Haivision/srt/files/3424845/stats.zip)

If I get the attention I had a delay of about 10 seconds between sending the video and receiving it at the end

thank you very much for your help!!

**Comment by gmadeo** [comment]
Hi,

Your hardware may not appreciate multicast. Try replacing 239.0.0.1 for 127.0.0.1.

Like this:

ffmpeg -i rtmp: //127.0.0.1/loteriavivo/live -c: v libx264 -c: a aac -preset: v ultrafast -f mpegts udp: //127.0.0.1: 5000? pkt_size = 1316

./srt-live-transmit -s: 200 udp: //127.0.0.1: 5000: pkt_size? 1316 srt: //192.168.192.110: 5001? latency = 2000

./srt-live-transmit -s: 200 srt: //: 5001 udp: //127.0.0.1: 5002

omxplayer -o hdmi udp: //@127.0.0.1: 5002

This *should* work.

Regards

**Comment by Panchitor** [comment]
I have a problem between SRT - TX and RX.

Because if I raise the signal on the same pc that I want to do the transmission I see it well !!! the subject is in the receiver, it seems to me that I have a lot of lost packages.

the issue that if instead of using SRT I use RTMP everything is fine.

**Comment by premultiply** [comment]
Does it work at all if you use UDP transport only without SRT protection?

**Comment by maxlovic** [comment]
@Panchitor 
According to the statistics you have collected, you have dropped packets:

### Receiver (latency 2000)
![stats-rcv-lat2000-packets](https://user-images.githubusercontent.com/12700120/62063495-3b50ce00-b22b-11e9-8788-6966e1a4ac18.png)

### Sender (latency 2000)

![stats-snd-lat2000-packets](https://user-images.githubusercontent.com/12700120/62063573-63d8c800-b22b-11e9-92a1-871f94cb3c51.png)

### RTT

![image](https://user-images.githubusercontent.com/12700120/62063669-a13d5580-b22b-11e9-8c2a-c9cea5508509.png)

**Comment by maxlovic** [comment]
@Panchitor 
Do you have some other traffic between those endpoints (`srt://192.168.192.111`)?
3- ./srt-live-transmit udp: //239.0.0.1: 5000 srt: //192.168.192.111: 5000;
4 - ./srt-live-transmit -s: 200 srt: //: 5000 udp: //239.0.0.1: 5001? Mode = server

**Comment by Panchitor** [comment]
Hello, it is a server that the only thing you have installed is a ubuntu and the nginx server.
what do you think it can be?

a lot of lost packages, right?
I still can't make the statistics script work.

**Comment by Panchitor** [comment]
Estimated according to the graphics you see? Can it be a problem in the internet upstream?

since I broadcast a video at 1mbps by SRT, and I had no problems as they looked before.

Shouldn't the SRT automatically calculate the transfer rate?

attached graphic.

Thank you.

![bokeh_plot(1)](https://user-images.githubusercontent.com/53226705/62099171-94d4ef00-b263-11e9-98e3-0960718af401.png)
![bokeh_plot(2)](https://user-images.githubusercontent.com/53226705/62099172-94d4ef00-b263-11e9-9588-e2f5616b0a58.png)
![bokeh_plot(3)](https://user-images.githubusercontent.com/53226705/62099173-94d4ef00-b263-11e9-8a9f-fb15a9e8b587.png)
![bokeh_plot(4)](https://user-images.githubusercontent.com/53226705/62099174-956d8580-b263-11e9-968b-b878f31ffcf7.png)
![bokeh_plot(6)](https://user-images.githubusercontent.com/53226705/62099176-956d8580-b263-11e9-9072-53688b547153.png)

**Comment by maxlovic** [comment]
According to your stats, you have dropped packets. This looks more like a network issue. Also RTT varies notably. What kind of network is it (Ethernet, WiFi, 4G, etc.)?

**Comment by Panchitor** [comment]
There are two cable modem connections, a 50/5 service and a 100/8 service.

I connect them both through a VPN through ZeroTier.-

**Comment by premultiply** [comment]
Try skiping the VPN first. Maybe this is the bottleneck.

**Comment by Panchitor** [comment]
Dear good morning,

I wanted to comment that yesterday I took 3 samples of 3 streaming at different bitrate rates.
I'm still doing the same way: Encoder RTMP - Internet --- RTMP Server - RTMP to UDP - UDP to SRT - Internet - SRT - SRT to UDP - OMXPLAYER UDP.

The rates used were 1.5mb, 2.5mb and 4mb.-

While I know that I don't have the capacity to do the upstream at those rates, shouldn't the SRT accommodate the available bandwidth and not have these packet losses?

**1.5Mb**
![bokeh_plot(4)](https://user-images.githubusercontent.com/53226705/62297182-26508680-b447-11e9-8928-8320f1fc2486.png)
![bokeh_plot(6)](https://user-images.githubusercontent.com/53226705/62297183-26508680-b447-11e9-9e2b-5fff7fda8f08.png)
![bokeh_plot(1)](https://user-images.githubusercontent.com/53226705/62297184-26e91d00-b447-11e9-89b5-b543e1dbe805.png)
![bokeh_plot(2)](https://user-images.githubusercontent.com/53226705/62297185-26e91d00-b447-11e9-9f08-15a35cc7d406.png)
![bokeh_plot(3)](https://user-images.githubusercontent.com/53226705/62297186-26e91d00-b447-11e9-8cfa-6f0548615662.png)

**2.5Mb**
![bokeh_plot(1)](https://user-images.githubusercontent.com/53226705/62297257-4a13cc80-b447-11e9-9d1a-c1ec2d7709e0.png)
![bokeh_plot(2)](https://user-images.githubusercontent.com/53226705/62297259-4aac6300-b447-11e9-808b-776a7a39640f.png)
![bokeh_plot(3)](https://user-images.githubusercontent.com/53226705/62297260-4aac6300-b447-11e9-826c-4542896ef532.png)
![bokeh_plot(4)](https://user-images.githubusercontent.com/53226705/62297261-4aac6300-b447-11e9-894a-47ad69031f1a.png)
![bokeh_plot(6)](https://user-images.githubusercontent.com/53226705/62297263-4b44f980-b447-11e9-947a-9bf50ba85187.png)

**4Mb**
![bokeh_plot(1)](https://user-images.githubusercontent.com/53226705/62297325-644daa80-b447-11e9-8c46-fc7fd14e565a.png)
![bokeh_plot(2)](https://user-images.githubusercontent.com/53226705/62297326-644daa80-b447-11e9-96bb-2cc418cdc4d7.png)
![bokeh_plot(3)](https://user-images.githubusercontent.com/53226705/62297327-644daa80-b447-11e9-821e-171f4337d954.png)
![bokeh_plot(4)](https://user-images.githubusercontent.com/53226705/62297328-64e64100-b447-11e9-99ec-6c163b84088e.png)
![bokeh_plot(6)](https://user-images.githubusercontent.com/53226705/62297329-64e64100-b447-11e9-8180-0e0c05260de0.png)

According to these graphs is there any way that bitrate suits the available bandwidth?

Thank you.

**Comment by gmadeo** [comment]
SRT will not adjust your encoding rate. How are you specifying your encoding bitrate in ffmpeg? With your network specifications, I would recommend "-b:v 3M -bufsize 6M -maxrate 3M". 

Your network has a high fluctuation of the RTT and that can be challenging for SRT. When you have drops, you also have a 100% increase in RTT. What latency did you use in your last tests? 2000ms should be fine.

The VPN is likely the main cause of RTT fluctuation. Is it possible for you to test directly without the VPN?

**Comment by Panchitor** [comment]
For now, ffmpeg comes in as it comes out.
Is this ok if I put it on? -b: v 3M 6M -bufsize -maxrate 3M
since I don't understand 3M 6M, or is it one or the other?
today I will do the test without the VPN, and I did not have it with latency, I will put latency of 2000, but as it is to make alive, I cannot exceed 3 or 4 seconds.

Given that on the server, I will have different srt points, I can limit the bw in ./srt-live-transmit?
Thank you

**Comment by gmadeo** [comment]
You should specify all options, but -maxrate is the most important. -b:v 3M will tell the encoder to target a bitrate of 3Mb, -bufsize 6M will help keeping the bitrate stable and -maxrate will tell the encoder to not go over 3Mb.

You must control your bandwidth in your encoder before SRT bandwidth controls can do their magic. Otherwise you risk overloading your network and then SRT is overloaded also.

For latency, keep testing with 2000 and when you have a stable stream you can try less.

**Comment by Panchitor** [comment]
perfect, should the code be like that, right?

-b: v 3M -bufsize 6M -maxrate 3M

I try and tell you today.

**Comment by gmadeo** [comment]
Yes this is good.

To be clear, this is for ffmpeg, so according to the command in your first post, it should now look like this:

 ffmpeg -i rtmp: //127.0.0.1/lotevivo/live -c: v libx264 -b: v 3M -bufsize 6M -maxrate 3M -c: a aac -preset ultrafast -f mpegts udp: //239.0.0.1: 5000? Pkt_size = 1316

**Comment by maxsharabayko** [comment]
Closing due to the lack of activity.

**Panchitor:**
> I try and tell you today.
