### ISSUE TITLE
Question about maxBandwidth status

### ISSUE THREAD

**Issue by calanor** [Haivision/srt#768]
When SRTO_MAXBW is set to 0 (relative) in the sender the maxBandwidth shows correctly the input bandwidh + overhead,  but in receiver always show 12.5Mbps.
Why these 12.5Mbps?  
It be possible to have the correct value of maxBandwidth in the receiver status?

**Comment by maxlovic** [comment]
Hi @calanor.
Assuming you mean the statistics value `mbpsBandwidth`, it is not related to the `SRTO_MAXBW` value set.

The `SRTO_MAXBW` and related socket options specify the bandwidth limitation for SRT sender. 

While the statistical value `mbpsBandwidth` shows the estimated bandwidth value (capacity) of the network link. Although you should not rely on it too much, as it is only an heuristic estimation.

**Comment by calanor** [comment]
Thanks @maxlovic,
I mean to mbpsMaxBW statics value set in core.cpp line 6104.   When maxbw in srt-live-transmit command line is set to 0,  the receiver always show 12.5Mbps. Te sender show de correct value corresponding to  inputBw (set or calculated) + Overhead.

**Comment by maxlovic** [comment]
In this mode the sender calculates the inbut bitrate and limits the bandwidth to that value plus some overhead (25% by default).
The receiver shows some default value, because it does not send a stream, and it has no data to calculate input bitrate and set the bandwidth limitation.

**Comment by maxlovic** [comment]
See also #763 
Closing as resolved.
