### ISSUE TITLE
Question about test-c-client/server and srt-live-transmit

### ISSUE THREAD

**Issue by deepkh** [Haivision/srt#775]
Test-c-client/server is look so simple. But, srt-live-transmit is look so complex. If test-c-client/server is good enough why we need srt-live-transmit? What's different between then? Due to there are no documents mentions that, so I post the question here. 😄

**Comment by maxlovic** [comment]
Hi @deepkh 
`test-c-client` recognizes only IP and port to connect to, and connects only in SRT caller mode, and sends sample data.
On the other hand, `srt-live-transit` supports SRT, UDP and STDIN/STDOUT, all the connection modes (caller, listener, rendezvous), socket options, command line options (run with `-help`) and transmits data from source to destination.

**Comment by ethouris** [comment]
The `test-c-client` etc. are predicted to serve only a demonstration purpose.

The `srt-live-transmit` is predicted as a full-fledged user application for streaming.

There's also `srt-test-live`, which has more-less the same functions, but it's rather predicted for developers to test SRT internals (it's way less user friendly, rather adjusted for developers' needs).
