### ISSUE TITLE
countBytes bad call in CRcvBuffer::getRcvReadyMsg

### ISSUE THREAD

**Issue by smsajjadi** [Haivision/srt#776]
Hi

I am reading the SRT codes to have a better understanding. (By the way, should not there be a better/more complete documentation?)
I encountered this, which seems to be a bug:
In CRcvBuffer::getRcvReadyMsg in buffer.cpp, the number of removed pakcets/bytes are being counted inside a loop on the queue locations. Then at the end, after the loop, the statistics are being  updated according to these counters. 
But the function might be returned inside the loop. For example when after some bad packets we at last find a good packet with all the needed specs and return that packet spec. In such a case the countBytes would not be called and the statistics would drift away from what really is there in.

**Comment by maxlovic** [comment]
Hi @smsajjadi You might be right. Will have to take a closer look.
Do you think you could create a unit test for that case? I have created some in #708 to start with.
