### ISSUE TITLE
Multi Socket SRT without Multiplexer

### ISSUE THREAD

**Issue by smsajjadi** [Haivision/srt#786]
Could SRT code be used to concurrently manage two different SRT sockets who are connected through two different UDP sockets? Or the Socket queues are only usable only when all sockets are targetting the same UDP socket?

**Comment by ethouris** [comment]
AFAIR thread safety is similar to that of the system - you can use multiple sockets operated in different threads, about that there's no problem at all.

And don't worry about UDP sockets at all. This is internal thing of SRT, and every UDP socket used inside has its own dedicated sender queue and receiver queue - even if occasionally a UDP socket is shared between multiple SRT sockets.

**Comment by mbakholdina** [comment]
Closed due to inactivity.
