### ISSUE TITLE
Hi author,I am a student,could you tell me how to use mbedtls crypto?

### ISSUE THREAD

**Issue by Jsondp** [Haivision/srt#788]
error：
-- Checking for module 'mbedtls mbedcrypto'
--   No package 'mbedtls' found
No package 'mbedcrypto' found

What should I do?

**Comment by ethouris** [comment]
Install mbedtls.

In your current system, cmake fails to find mbedtls. It's either not installed, or somehow cmake doesn't recognize installation of mbedtls. I can't help you without knowing specifics of your system.

**Comment by Jsondp** [comment]
Thank you for your reply.Could you tell me how to configure mbedtls library paths.




------------------ 原始邮件 ------------------
发件人: "Sektor van Skijlen"<notifications@github.com>;
发送时间: 2019年8月5日(星期一) 下午5:00
收件人: "Haivision/srt"<srt@noreply.github.com>;
抄送: "nlft"<577423282@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Haivision/srt] Hi author,I am a student,could you tell me how touse mbedtls crypto? (#788)




Install mbedtls.
 
In your current system, cmake fails to find mbedtls. It's either not installed, or somehow cmake doesn't recognize installation of mbedtls. I can't help you without knowing specifics of your system.

**Comment by ethouris** [comment]
> I can't help you without knowing specifics of your system.

**Comment by maxlovic** [comment]
Hi @Jsondp. How is your progress with mbedTLS?
The general steps are:
1. Make sure you have [mbedTLS](https://tls.mbed.org/download) in your system.
2. Add CMake option `-DUSE_ENCLIB=mbedtls`
3. If mbedTLS is not found automatically, check CMakeLists.txt [section](https://github.com/Haivision/srt/blob/master/CMakeLists.txt#L257).

**Comment by Jsondp** [comment]
The problem has been solved.Thank you for your reply.Thanks
