### ISSUE TITLE
SRT 1.3.3 do not compile under iOS due undefined type "hcrypt_CipherData"

### ISSUE THREAD

**Issue by alvid** [Haivision/srt#789]
Older version 1.3.2 has been normally compiled under iOS due type "hcrypt_CipherData" was defined into file "haicrypt/hcrypt_ctx.h" as void*. But newest version has not.

I set compiler flags:
-DSRT_VERSION="1.3.3"
-DSRT_ENABLE_ENCRYPTION
-DUSE_OPENSSL=1
-DHAICRYPT_DYNAMIC
-DHAI_ENABLE_SRT=1
-DHAI_PATCH=1
-DOSX=1
-D_GNU_SOURCE

**Comment by alvid** [comment]
I have to delete 3 files from build:

**Comment by maxlovic** [comment]
@alvid Why did you have to exclude those files? I mean, if you can't build the library after a clean checkout, then that should be fixed.

**Comment by alvid** [comment]
Because they need into undefined type hcrypt_CipherData, as I wrote into issue’s title..
And excluding these files do not affect building too..

**Comment by jeandube** [comment]
I seems to me your CMakeFiles cache has not been cleaned if you need files non longer needs. The old crypto lib interface sources (that need hcrypt_cipherData) have been replaced by CRYSPRs. The old files should not be part of the build. They were kept until PR/742 was merged. They will be removed soon.
