### ISSUE TITLE
srt-tunnel.cpp:386:19: error: ‘Medium::Medium’ names constructor

### ISSUE THREAD

**Issue by midicase** [Haivision/srt#793]
v1.3.3
Some of us are stuck at 4.7 and can't compile the example app.  Was able to in 1.3.2.

**Comment by maxlovic** [comment]
```
#ifndef _MSC_VER
    using Medium::Medium;
#else // MSVC not exactly supports C++11
    SrtMedium(UriParser u, size_t ch): Medium(u, ch) {}
#endif
```
Inheriting Constructors have been available in GCC since version 4.8.
TODO: check GCC version.

**Comment by ethouris** [comment]
@midicase please check the fix on my branch `dev-fix-almost-c++11`. Installing gcc 4.7 on my system may require from me some more gymnastics and would take more time.

**Comment by midicase** [comment]
Not sure that patch is needed or helps.  CmakeLists.txt test for compat compiler passes and compiler flags are added, -std=c++11.  With this arg, __cplusplus is changed from 199711 to 201103.  Messes the test up since HAVE_FULL_CXX11 get left defined. 

The tests could be inverted to first check for partial, then full, but a small change to the patch worked:

#elif defined(__GNUC__) && defined(__GXX_EXPERIMENTAL_CXX0X__) && __GNUC_MINOR__ >= 7 // 4.7 only!
#define HAVE_CXX11 1
#undef HAVE_FULL_CXX11
....
Had to undef.    Not sure though if it has be >= 7 or == 7.

It's probably better for me to just avoid -std=c++11 by using -DDISABLE_CXX11 when using 4.7, which is trivial to do in the build system.  

Thanks

**Comment by ethouris** [comment]
Well, I expected some mess and misinformation here, that's why I needed this test. I updated the branch - now this check is made when gcc is detected as BEING in C++11 mode.

Actually you might be right that probably you don't need these apps for C++11 and disabling them would save you trouble. But still, if something can be easily fixed and allow the app to compile, it's worth doing it.

Please retest - in this form it should work now.

**Comment by midicase** [comment]
__GNUC__ not __GNUC_MAJOR__

Also needs 
-#ifndef _MSC_VER
+#ifdef HAVE_FULL_CXX11

in class TcpMedium: public Medium around line 485.  

Works great with those two minor changes.

**Comment by ethouris** [comment]
Ok, #809 created to submit the fix. I added this and fixed also in other places where "almost C++11" support was only for MSVC.
