### ISSUE TITLE
Raspberry decoder

### ISSUE THREAD

**Issue by Panchitor** [Haivision/srt#798]
Raspberry:

Has anyone been able to make a good reception on a raspberry?

Do you know if it is possible to make ffmpeg srt to hdmi port?

Since otherwise, I should receive srt to udp and then omxplayer udp.

Each step generates a delay.

I await your comments.

Thank you.

**Comment by premultiply** [comment]
> Since otherwise, I should receive srt to udp and then omxplayer udp.
This is the standard way to go.

Maybe omxplayer does support srt-URLs directly through ffmpeg-libs.
Try it yourself or ask on omxplayers issue tracker.

**Comment by jreykdal** [comment]
udp with omxplayer is what I've done on Pi3. ffplay etc. was a bit taxing for the pi (overheating) but omxplayer was a breeze.

The delay it adds is minimal.

**Comment by Panchitor** [comment]
I see the signal with omxplayer myself, but I need to see how they emit and receive, with what codes since at some point I have a lot of delay

**Comment by maxlovic** [comment]
See also #769

**Comment by maxlovic** [comment]
Closing, as no further discussion is expected.
