### ISSUE TITLE
Using Stransmit for 1080P@60 Streaming

### ISSUE THREAD

**Issue by gurtajs4** [Haivision/srt#80]
Hi EveryOne,
I am trying to explore and see how we can use the SRT to overcome the Packet Loss Issue(Local Wireless Network) with little introduction of Latency & Buffering into the overall System.

I started off by using the Stransmit APP as described below over Wired LAN:
PC1 (VLC first instance: UDP out :9000) : Streaming MP4
|
SERVER1 (stransmit: UDP :9000, SRT server mode out :1234)
./stransmit -v udp://srv1_ip:9000 srt://srv1_ip:1234/?mode=server
|
SERVER2 (PC2 stransmit: SRT client mode in :1234, UDP out :9001)
./stransmit -v srt://srv1_ip:1234/?mode=client udp://pc1_ip:9001
|
PC2 (VLC second instance: UDP in :9001)

Using the above setup I can see some data is getting transmitted from PC1->PC2, But the video performance is not up-to the mark, even over the Wired Ethernet Connection.
I could barely play 480@30FPS Video but 1080P@60 is too bad and it pauses a lot and buffer a lot in between.

So this made me into thinking...
1. Is Stransmit is a correct way to test Video Streaming over SRT?
2. Is there any parameters that I need to provide other than what specified above?
3. Is this could be issue with VLC app which is dropping lots of late Frame?

I believe that I am missing some key information here. Can someone provide me the correct direction?
Regards,
Gurtaj

**Comment by gurtajs4** [comment]
Hi,
Thanks for a quick reply.
Can you help me with the arguments.

Server:
./stransmit -v -c:1500 udp://127.0.0.1:9000 srt://10.0.2.15:1234/?mode=server&latency=1000

Client:
./stransmit srt://10.0.2.15:1234/?mode=client udp://127.0.0.1:9001

I am not sure how to add latency parameters to Client and Server side correctly and it throws me error every-time I try to add latency to client pipeline.

Regards,
Gurtaj

**Comment by adamyellen** [comment]
Are you putting quotes around the URL?

**Comment by gurtajs4** [comment]
This is the exact thing I tried and it did not worked

Server: 
./stransmit -v -c:1500 udp://127.0.0.1:9000 srt://10.0.2.15:1234/?mode=server&latency=1000

Client:
./stransmit srt://10.0.2.15:1234/?mode=client&latency=1000 udp://127.0.0.1:9001
Or
./stransmit srt://10.0.2.15:1234/?mode=client udp://127.0.0.1:9001&latency=1000

above Client cmdline does not work and Even if I have added the latency to Server, it does not improve my performance.

Regards.
Gurtaj

**Comment by adamyellen** [comment]
Please put quotes around the URLs that contain ampersands.

**Comment by gurtajs4** [comment]
Hi All,

I have added the latency param within the double quote and tried to stream 1080p@60FPS Video 
using VLC and Wired ethernet network but on the receiver side I see the video pause a lot and buffers while playing.
I do not see anything close to the once showed below in the video.
Can someone point out the issue in my setup

[https://www.youtube.com/watch?v=rJCzkXhoMEE](https://www.youtube.com/watch?v=rJCzkXhoMEE)

Thanks,
Gurtaj

**Comment by heidabyr** [comment]
Hi Gurtaj,

things work as expected when you are streaming directly from one VLC to another? I am not sure what the MP4 format does in this context, since MP4 is not a streaming format. We are typically streaming MPEG-TS data. Can you provide a little more detail on your demo setup and maybe also share some test content?

Thank you,
Marc

**Comment by gurtajs4** [comment]
Hi All,
[mediainfo.txt](https://github.com/Haivision/srt/files/1245852/mediainfo.txt)

Please find the MP4 format in the mediainfo.txt file.

Test Scenario 
VLC(source)->Stream
:sout=#transcode{vcodec=h264,scale=Auto,acodec=none}:udp{dst=127.0.0.1:9000} :sout-keep
SRT Server ./stransmit -v -c:1500 "udp://127.0.0.1:9000" "srt://10.0.2.15:1234/?mode=server&latency=1000"
|
SRT Client
./stransmit "srt://10.0.2.15:1234/?mode=client&latency=1000" udp://127.0.0.1:9001
VLC(Client)

Regards,
Gurtaj

**Comment by heidabyr** [comment]
I still don't quite understand how you are streaming an MP4 file, since it's no streaming standard. I see VLC is transcoding, is it wrapping h.264 and AAC into an MPEG Transport Stream container for the transmission? And again, VLC to VLC directly is working fine for you?

**Comment by heidabyr** [comment]
Hi Gurtaj,

what I meant by VLC to VLC is directly, without any SRT (stransmit) in-between. just to make sure your general setup works without SRT being involved.

SRT s totally work fine for you, as it is completely content agnostic, yes. It would do packet loss recovery and the latency introduced depends on the RTT (round trip time), which is quite low for a local network.

We should first try to get your test setup running and then it would make sense to do different tests under different network conditions in order to come to the best latency, low enough to maintain low latency and high enough to recover from the packet loss you are experiencing.

Thanks,
Marc

**Comment by thepocho** [comment]
Dear,
I use these commands:
Client: ./stransmit -r:1000 -s:1000 udp://:1000 srt://IP-SERVER:5000/?tsbpddelay=1000
Server: ./stransmit -r:1000 -s:1000 srt://5000 udp://IP-DECODER:2000

Hope this can help you..

Regards,
Martin

**Comment by gurtajs4** [comment]
Hi Marc,
I did not check VLC to VLC playback(without SRT), will check that and update you tomorrow.

Yes, I do believe that We will have to run lot of test with different resolution of streams and routers to come a conclusion where we will be able to decide if SRT can be deployed into our system.

But below I do that on actual system, I have some small hurdles which I need to figure out first
1. Does SRT currently support Multicast Streams to be passed thru them.
2. I will have to compile the SRT Source or may be port the SRT to Android, so that the player can take advantage of the SRT Core.
Do you have any suggestion on how should I go?

Regards,
Gurtaj

**Comment by gurtajs4** [comment]
Martin,
Thanks for the command, I shall try the commands out first thing next morning.

Regards,
Gurtaj

**Comment by heidabyr** [comment]
Gurtaj,

> 1. Does SRT currently support Multicast Streams to be passed thru them.

If using stransmit, you can flip MultiCast to SRT, do an SRT MultiCast and flip SRT back to UDP MultiCast on the other side.

> 2. I will have to compile the SRT Source or may be port the SRT to Android,
> so that the player can take advantage of the SRT Core.

SRT can be compiled on all kinds of systems, so there should be no problem. You can start with a pragmatic approach for testing, using stransmit on the target hardware. But ultimately you should integrate the SRT protocol into your application.

- Marc

**Comment by gurtajs4** [comment]
Marc,

I dont really get the Multicast flip part.
Given the below commands that I am using for Server & CLient,
./stransmit -v -c:1500 udp://127.0.0.1:9000 "srt://10.0.2.15:1234/?mode=server&latency=1000"
./stransmit "srt://10.0.2.15:1234/?mode=client&latency=1000" udp://127.0.0.1:9001

How do you want me to use Multicast stream(ex: 224.8.96.1:101054), which I now directly fed to the Player as Multicast Source?

-Gurtaj

**Comment by garybruckheimer** [comment]
Dear Gurtaj,

i use SRT in my daily business. 

Here you see my latest demo:
https://www.youtube.com/watch?v=Gv9TD2v4IyY <https://www.youtube.com/watch?v=Gv9TD2v4IyY>

I grab from an hardware SoC a UDP TS-Stream, then use SRT to transmit to an SRT Server instance, then back to UDP where i can play it back with any compatible player.

This works with H.264 and HEVC in perfect sync as you can see. I want to help, you, but i need more pipeline information how you generate the stream and how you implement SRT on both side. 

Best Regards,
Gary
rebontix technologies
-
https://rebontix.com <https://rebontix.com/>
a SRT Alliance Member

**Comment by gurtajs4** [comment]
Hi Gary,

Our Setup is quite simple, which consist of some Encoders(SOC's) capable of transcoding HD 1080p/i @60FPS and convert them to Multicast Streams( RTP H264 Baseline Profile and PCM Samples)  and send it out to network.
On the Client Side, we have Hardware capable of decoding(H264 using Hardware/Software codecs) that host Player which decodes and render the H264 Frames.
The setup is currently a closed Wired Network and hence we don't see any issues which normally a Wireless network would have.

Going forward, we want to host the Client Player onto say a COTS Android tablet connected to the system over a wireless router.
If we do that today, then the Player would incur lots of Packet Loss given the Stream is 1080P 30/60 FPS.
So the goal is the address this by deploying SRT or equivalent with little overhead latency added on both Encoder and Player side to allow Wireless Devices to Play the HD RTP Video Content.

Regards,
Gurtaj

**Comment by gurtajs4** [comment]
> Dear,
I use these commands:
Client: ./stransmit -r:1000 -s:1000 udp://:1000 srt://IP-SERVER:5000/?tsbpddelay=1000
Server: ./stransmit -r:1000 -s:1000 srt://5000 udp://IP-DECODER:2000
Hope this can help you..
Regards,
Martin
>
Hi Martin,

I used tried using the above client/server pipeline and it does not seems to connect at all.
Can you please describe the resolution of the Video you are using and the player, because I use VLC and stream and play Video.

Regards,
Gurtaj

**Comment by gurtajs4** [comment]
> Marc,
I dont really get the Multicast flip part.
Given the below commands that I am using for Server & CLient,
./stransmit -v -c:1500 udp://127.0.0.1:9000 "srt://10.0.2.15:1234/?mode=server&latency=1000"
./stransmit "srt://10.0.2.15:1234/?mode=client&latency=1000" udp://127.0.0.1:9001

How do you want me to use Multicast stream(ex: 224.8.96.1:101054), which I now directly fed to the Player as Multicast Source?

Also I checked direct VLC to VLC playback on my setup and the video plays fine, except some initial latency & Buffering of few seconds.

But, if I pass the same stream over SRT and play using VLC on the other side, the video pauses or sometime I see logs like late frames in VLC. 
Is there any other parameter that I need to take care of in my SRT Cmd line to allow more TTL

Regards,
Gurtaj

**Comment by thepocho** [comment]
Dear,

I send and receive by dedicated hardware.

Capable that you can prove if you are receiving in the ports.
In linux you can use the command: tcpdump port XXXX.

If you add the option -v (verbose) to the command, you can see more data of the ./stransmit.

If you want, you could enter your machine remotely and help.

Regards,

**Comment by gurtajs4** [comment]
Hi Martin,

I do have other Server/Client commands which seems to work for me now.
I am trying to experiment and collect data based on different resolution of video and average latency on a wireless network.

I now understand the PC based setup and need to deploy SRT to the actual system and use it on Android  app side to see if Wireless Video Playback give me good performance.

Regards,
Gurtaj

**Comment by ethouris** [comment]
Not sure if I'm not too late, but I have seen in the beginning the `stransmit` command calls in the second instance transmits from one computer to another with SRT source and UDP target. Not sure how you configured that and what the hostname is on the computer where your run this command, but remember that you should not transmit packets from one computer to another over UDP, if you want to take advantage of SRT packet recovery. You should use UDP URL in this command with always the same host as the host on which you are running the command. Unless you have multiple network interfaces on the host, simply use an empty host in UDP URL:

    ./stransmit udp://:9000 srt://:1234?mode=listener
    ./stransmit srt://remotehost:1234 udp://:5001

**Comment by thepocho** [comment]
What are the commands you use?

I only put lantecia in transmitter.
Should I set it in the receiver?

Regards,

**Comment by ethouris** [comment]
You can use both; the resulting value will be the maximum of these. Generally the most interested should be the receiver because this is where the latency control really happens, however this value is also interesting for the sender because it needs it in the on-premise retransmission control and controlled packet dropping.
