### ISSUE TITLE
srt_bind throws exception for valid IN6_ADDR when setting TTL/HOPS or TOS/TCLASS

### ISSUE THREAD

**Issue by ormike** [Haivision/srt#810]
Relates to commit ee311d6ac10a008a5a27f079cbc22463f8565690

srt_bind() ends up calling CChannel::setUDPSockOpt().  If the socket is an AF_INET6 socket and the user has specified SRTO_IPTTL or SRTO_IPTOS options, this function will try to set these options in both IPPROTO_IP (IPv4) and IPPROTO_IP6 (IPv6), assuming a dual protocol stack, so that the listening socket can receive messages from an IPv4 or IPv6 remote sender.  However the internal call to ::setsockopt() returns an error for some important scenarios, resulting in an exception thrown.

Reported on Windows 10 Enterprise version 1703 

The current code does work for setting SRTO_IPTTL if the IN6_ADDR associated with the socket is unspecified.  This is the case if getaddrinfo() is not called to set the bind address, or if getaddrinfo() is called with an empty string for the network interface address.  In these cases, the IN6_ADDR is [::], and the srt_bind() operation results in listening on both 0.0.0.0 (all IPv4 interfaces) and [::] (all IPv6 interfaces).  

The problem happens when you try to bind the socket to a specific interface.  For example, if the IN6_ADDR associated with the socket is a pure IPv6 socket such as [::1] (localhost) then the call to ::setsockopt() with IPPROTO_IP will fail with WIndows Sockets Error Code WSAEINVAL 10022 Invalid argument.

Likewise if the IN6_ADDR is an IPv4-mapped IPv6 address such as [::FFFF:127.0.0.1] (localhost) then the call to ::setsockopt() with IPPROTO_IP6 will fail with the same error code.

I think the current code does not work for setting SRTO_IPTOS in any case.  Check the #ifdef IPV6_TCLASS around line 230.  The matching #endif appears to be in the wrong place.

Here is the code we're using to fix these issues, replacing the code around lines 214 and 230 in channel.cpp.  It works in all the cases we have tested.

```
#ifdef SRT_ENABLE_IPOPTS
      if (-1 != m_iIpTTL)
      {
         if(m_iIPversion == AF_INET)
         {
            if(0 != ::setsockopt(m_iSocket, IPPROTO_IP, IP_TTL, (const char*)&m_iIpTTL, sizeof(m_iIpTTL)))
               throw CUDTException(MJ_SETUP, MN_NORES, NET_ERROR);
         }
         else //Assuming AF_INET6
         {
            if (m_BindAddr.family() == AF_INET6) {
               if (IN6_IS_ADDR_UNSPECIFIED(&m_BindAddr.sin6.sin6_addr) || !IN6_IS_ADDR_V4MAPPED(&m_BindAddr.sin6.sin6_addr)) {
                  if (0 != ::setsockopt(m_iSocket, IPPROTO_IPV6, IPV6_UNICAST_HOPS, (const char*)&m_iIpTTL, sizeof(m_iIpTTL))) {
                     throw CUDTException(MJ_SETUP, MN_NORES, NET_ERROR);
                  }
               }
               if (IN6_IS_ADDR_UNSPECIFIED(&m_BindAddr.sin6.sin6_addr) || IN6_IS_ADDR_V4MAPPED(&m_BindAddr.sin6.sin6_addr)) {
                  //For IPv4mapped-IPv6 accepted connection also set the IPV4 socket.
                  if (0 != ::setsockopt(m_iSocket, IPPROTO_IP, IP_TTL, (const char*)&m_iIpTTL, sizeof(m_iIpTTL))) {
                     throw CUDTException(MJ_SETUP, MN_NORES, NET_ERROR);
                  }
               }
            }
         }
      }
      if (-1 != m_iIpToS)
      {
         if(m_iIPversion == AF_INET)
         {
            if(0 != ::setsockopt(m_iSocket, IPPROTO_IP, IP_TOS, (const char*)&m_iIpToS, sizeof(m_iIpToS)))
               throw CUDTException(MJ_SETUP, MN_NORES, NET_ERROR);
         }
         else //Assuming AF_INET6
         {
            if (m_BindAddr.family() == AF_INET6) {
               if (IN6_IS_ADDR_UNSPECIFIED(&m_BindAddr.sin6.sin6_addr) || !IN6_IS_ADDR_V4MAPPED(&m_BindAddr.sin6.sin6_addr)) {
#ifdef IPV6_TCLASS
                  if (0 != ::setsockopt(m_iSocket, IPPROTO_IPV6, IPV6_TCLASS, (const char*)&m_iIpToS, sizeof(m_iIpToS))) {
                     throw CUDTException(MJ_SETUP, MN_NORES, NET_ERROR);
                  }
#endif
               }
               if (IN6_IS_ADDR_UNSPECIFIED(&m_BindAddr.sin6.sin6_addr) || IN6_IS_ADDR_V4MAPPED(&m_BindAddr.sin6.sin6_addr)) {
                  //For IPv4mapped-IPv6 accepted connection also set the IPV4 socket.
                  if (0 != ::setsockopt(m_iSocket, IPPROTO_IP, IP_TOS, (const char*)&m_iIpToS, sizeof(m_iIpToS))) {
                     throw CUDTException(MJ_SETUP, MN_NORES, NET_ERROR);
                  }
               }
            }
         }
      }
#endif
```

**Comment by ethouris** [comment]
I've applied the fix on my branch [dev-fix-ipv6-opt](https://github.com/ethouris/srt/tree/dev-fix-ipv6-opt), please review. I changed it slightly. What I don't understand is why you are specifically checking for IPv6 and do it through `m_BindAddr.family()` check. Actually the family here and the `m_iIPVersion` field are set from the constructor to the same value (the second constructor with empty parameter list is a dead code - it's not used anywhere, just the code isn't refactored yet).

**Comment by ormike** [comment]
@ethouris The reason I had a check for if (m_BindAddr.family() == AF_INET6) was to ensure that m_BindAddr was an IPv6 address before using the IN6_IS_ADDR_UNSPECIFIED and IN6_IS_ADDR_V4MAPPED macros on it. I did not want to rely on other code to ensure it, although as you said there was little risk.  An else clause on those tests may be merited to signal an internal error if the test ever failed.

**Comment by ethouris** [comment]
My question wasn't why you check whether the address is IPv6, but why you are doing this check through `m_BindAddr.family()` instead of through `m_iIPVersion`.

Might be that some more pedantic check would be nicer here. I'll make an update.
