### ISSUE TITLE
"Belated received" packets in stats with out any Lost or Drop packets

### ISSUE THREAD

**Issue by mks75** [Haivision/srt#840]
Hi,
I have observed "Belated received" packets during transfer, that increases bandwidth utilization.
During this time there were no Lost/Drop packets. What is "Belated received" and the cause for this. How this can be resolved?
snapshot from RX node:
======= SRT STATS: sid=737099491
PACKETS     SENT:           0  RECEIVED:          1001
LOST PKT    SENT:           0  RECEIVED:             0
REXMIT      SENT:           0  RECEIVED:             0
DROP PKT    SENT:           0  RECEIVED:             0
RATE     SENDING:           0  RECEIVING:      3.61689
BELATED RECEIVED:           0  AVG TIME:   1.81144e+16
REORDER DISTANCE:           0
WINDOW      FLOW:        8192  CONGESTION:        8192  FLIGHT:           0
LINK         RTT:   314.493ms  BANDWIDTH:   42.636Mb/s
BUFFERLEFT:  SND:    12288000  RCV:           10294500
======= SRT STATS: sid=737099491
PACKETS     SENT:           0  RECEIVED:          1395
LOST PKT    SENT:           0  RECEIVED:             0
REXMIT      SENT:           0  RECEIVED:          1111
DROP PKT    SENT:           0  RECEIVED:             0
RATE     SENDING:           0  RECEIVING:      5.04015
**BELATED RECEIVED:        1111**  AVG TIME:    1.6466e+16
REORDER DISTANCE:           0
WINDOW      FLOW:        8192  CONGESTION:        8192  FLIGHT:           0
LINK         RTT:   314.593ms  BANDWIDTH:     4.02Mb/s
BUFFERLEFT:  SND:    12288000  RCV:           11368500
======= SRT STATS: sid=737099491
PACKETS     SENT:           0  RECEIVED:          1650
LOST PKT    SENT:           0  RECEIVED:             0
REXMIT      SENT:           0  RECEIVED:           306
DROP PKT    SENT:           0  RECEIVED:             0
RATE     SENDING:           0  RECEIVING:      5.98364
**BELATED RECEIVED:         306**  AVG TIME:   1.84467e+16
REORDER DISTANCE:           0
WINDOW      FLOW:        8192  CONGESTION:        8192  FLIGHT:           0
LINK         RTT:   314.829ms  BANDWIDTH:   62.592Mb/s
BUFFERLEFT:  SND:    12288000  RCV:           10858500
======= SRT STATS: sid=737099491
PACKETS     SENT:           0  RECEIVED:          1365
LOST PKT    SENT:           0  RECEIVED:             0
REXMIT      SENT:           0  RECEIVED:             0
DROP PKT    SENT:           0  RECEIVED:             0
RATE     SENDING:           0  RECEIVING:      4.95201
BELATED RECEIVED:           0  AVG TIME:   1.84467e+16
REORDER DISTANCE:           0
WINDOW      FLOW:        8192  CONGESTION:        8192  FLIGHT:           0
LINK         RTT:   314.913ms  BANDWIDTH:   49.992Mb/s
BUFFERLEFT:  SND:    12288000  RCV:           10297500

Thanks
MKS

**Comment by maxlovic** [comment]
A packet is belated if it has arrived out of order, and it was not a re-transmitted packet. So it is an originally sent packet, that was received later, then one of the next packets in order.
See also #735.

**Comment by maxlovic** [comment]
Description for stats is requested in #142. This one can be closed.

**Comment by mks75** [comment]
Hi @maxlovic,
I have a new observation to share. In one of my test transfers, I have observed huge amount of "Belated received" packets for many hours. The same amount of packets are also reflected in "Rexmit received". This increased the stream transfer bitrate by almost double.
It started around 09-06-2019--05:49:16 and got corrected by itself around 09-07-2019--04:21:46
Not sure what caused this ?

Please see the following graphs and log at the Rx side.
![image](https://user-images.githubusercontent.com/34006918/64651130-bee70880-d3ee-11e9-8ef2-fb2956222189.png)

![image](https://user-images.githubusercontent.com/34006918/64651149-cdcdbb00-d3ee-11e9-8b34-e311cd02818d.png)

![image](https://user-images.githubusercontent.com/34006918/64651170-d7efb980-d3ee-11e9-88b7-9bf6db624686.png)

![image](https://user-images.githubusercontent.com/34006918/64651182-e047f480-d3ee-11e9-8cd0-a9df892a07c6.png)


Rx log:
09-06-2019--05:49:10 ======= SRT STATS: sid=106073246
09-06-2019--05:49:10 PACKETS     SENT:           0  RECEIVED:          1001
09-06-2019--05:49:10 LOST PKT    SENT:           0  RECEIVED:             0
**09-06-2019--05:49:10 REXMIT      SENT:           0  RECEIVED:             0**
09-06-2019--05:49:10 DROP PKT    SENT:           0  RECEIVED:             0
09-06-2019--05:49:10 RATE     SENDING:           0  RECEIVING:      3.61805
**09-06-2019--05:49:10 BELATED RECEIVED:           0**  AVG TIME:   1.84467e+16
09-06-2019--05:49:10 REORDER DISTANCE:          16
09-06-2019--05:49:10 WINDOW      FLOW:        8192  CONGESTION:        8192  FLIGHT:           0
09-06-2019--05:49:10 LINK         RTT:   344.298ms  BANDWIDTH:   31.092Mb/s
09-06-2019--05:49:10 BUFFERLEFT:  SND:    12288000  RCV:           10296000
09-06-2019--05:49:13 ======= SRT STATS: sid=106073246
09-06-2019--05:49:13 PACKETS     SENT:           0  RECEIVED:           996
09-06-2019--05:49:13 LOST PKT    SENT:           0  RECEIVED:             0
**09-06-2019--05:49:13 REXMIT      SENT:           0  RECEIVED:             0**
09-06-2019--05:49:13 DROP PKT    SENT:           0  RECEIVED:             0
09-06-2019--05:49:13 RATE     SENDING:           0  RECEIVING:      3.61254
**09-06-2019--05:49:13 BELATED RECEIVED:           0**  AVG TIME:   1.84467e+16
09-06-2019--05:49:13 REORDER DISTANCE:          16
09-06-2019--05:49:13 WINDOW      FLOW:        8192  CONGESTION:        8192  FLIGHT:           0
09-06-2019--05:49:13 LINK         RTT:   344.324ms  BANDWIDTH:   48.348Mb/s
09-06-2019--05:49:13 BUFFERLEFT:  SND:    12288000  RCV:           10297500
09-06-2019--05:49:16 ======= SRT STATS: sid=106073246
09-06-2019--05:49:16 PACKETS     SENT:           0  RECEIVED:          1206
09-06-2019--05:49:16 LOST PKT    SENT:           0  RECEIVED:             0
**09-06-2019--05:49:16 REXMIT      SENT:           0  RECEIVED:           613**
09-06-2019--05:49:16 DROP PKT    SENT:           0  RECEIVED:             0
09-06-2019--05:49:16 RATE     SENDING:           0  RECEIVING:      4.37296
**09-06-2019--05:49:16 BELATED RECEIVED:         613**  AVG TIME:   1.84467e+16
09-06-2019--05:49:16 REORDER DISTANCE:          16
09-06-2019--05:49:16 WINDOW      FLOW:        8192  CONGESTION:        8192  FLIGHT:           0
09-06-2019--05:49:16 LINK         RTT:   344.425ms  BANDWIDTH:   27.912Mb/s
09-06-2019--05:49:16 BUFFERLEFT:  SND:    12288000  RCV:           10902000
09-06-2019--05:49:19 ======= SRT STATS: sid=106073246
09-06-2019--05:49:19 PACKETS     SENT:           0  RECEIVED:          1591
09-06-2019--05:49:19 LOST PKT    SENT:           0  RECEIVED:             0
**09-06-2019--05:49:19 REXMIT      SENT:           0  RECEIVED:          1090**
09-06-2019--05:49:19 DROP PKT    SENT:           0  RECEIVED:             0
09-06-2019--05:49:19 RATE     SENDING:           0  RECEIVING:      5.74473
**09-06-2019--05:49:19 BELATED RECEIVED:        1090**  AVG TIME:   1.84374e+16
09-06-2019--05:49:19 REORDER DISTANCE:          16
09-06-2019--05:49:19 WINDOW      FLOW:        8192  CONGESTION:        8192  FLIGHT:           0
09-06-2019--05:49:19 LINK         RTT:   344.502ms  BANDWIDTH:   22.524Mb/s
09-06-2019--05:49:19 BUFFERLEFT:  SND:    12288000  RCV:           11650500
09-06-2019--05:49:22 ======= SRT STATS: sid=106073246
09-06-2019--05:49:22 PACKETS     SENT:           0  RECEIVED:          1689
09-06-2019--05:49:22 LOST PKT    SENT:           0  RECEIVED:             0
**09-06-2019--05:49:22 REXMIT      SENT:           0  RECEIVED:          1071**
09-06-2019--05:49:22 DROP PKT    SENT:           0  RECEIVED:             0
09-06-2019--05:49:22 RATE     SENDING:           0  RECEIVING:      6.12039
**09-06-2019--05:49:22 BELATED RECEIVED:        1071**  AVG TIME:   1.84467e+16
09-06-2019--05:49:22 REORDER DISTANCE:          16
09-06-2019--05:49:22 WINDOW      FLOW:        8192  CONGESTION:        8192  FLIGHT:           0
09-06-2019--05:49:22 LINK         RTT:   344.502ms  BANDWIDTH:   32.352Mb/s
09-06-2019--05:49:22 BUFFERLEFT:  SND:    12288000  RCV:           12223500


.
.
.
.
.

09-07-2019--04:21:37 ======= SRT STATS: sid=106073246
09-07-2019--04:21:37 PACKETS     SENT:           0  RECEIVED:          1701
09-07-2019--04:21:37 LOST PKT    SENT:           0  RECEIVED:             0
**09-07-2019--04:21:37 REXMIT      SENT:           0  RECEIVED:           674**
09-07-2019--04:21:37 DROP PKT    SENT:           0  RECEIVED:             0
09-07-2019--04:21:37 RATE     SENDING:           0  RECEIVING:      6.15248
**09-07-2019--04:21:37 BELATED RECEIVED:         674**  AVG TIME:   1.84467e+16
09-07-2019--04:21:37 REORDER DISTANCE:          23
09-07-2019--04:21:37 WINDOW      FLOW:        8192  CONGESTION:        8192  FLIGHT:           0
09-07-2019--04:21:37 LINK         RTT:   339.562ms  BANDWIDTH:   28.176Mb/s
09-07-2019--04:21:37 BUFFERLEFT:  SND:    12288000  RCV:           12058500
09-07-2019--04:21:40 ======= SRT STATS: sid=106073246
09-07-2019--04:21:40 PACKETS     SENT:           0  RECEIVED:          1734
09-07-2019--04:21:40 LOST PKT    SENT:           0  RECEIVED:            13
**09-07-2019--04:21:40 REXMIT      SENT:           0  RECEIVED:           741**
09-07-2019--04:21:40 DROP PKT    SENT:           0  RECEIVED:            13
09-07-2019--04:21:40 RATE     SENDING:           0  RECEIVING:      6.19223
**09-07-2019--04:21:40 BELATED RECEIVED:         741**  AVG TIME:   1.84467e+16
09-07-2019--04:21:40 REORDER DISTANCE:          23
09-07-2019--04:21:40 WINDOW      FLOW:        8192  CONGESTION:        8192  FLIGHT:           0
09-07-2019--04:21:40 LINK         RTT:   322.831ms  BANDWIDTH:   30.636Mb/s
09-07-2019--04:21:40 BUFFERLEFT:  SND:    12288000  RCV:           12069000
09-07-2019--04:21:43 ======= SRT STATS: sid=106073246
09-07-2019--04:21:43 PACKETS     SENT:           0  RECEIVED:          1692
09-07-2019--04:21:43 LOST PKT    SENT:           0  RECEIVED:             0
**09-07-2019--04:21:43 REXMIT      SENT:           0  RECEIVED:            80**
09-07-2019--04:21:43 DROP PKT    SENT:           0  RECEIVED:             0
09-07-2019--04:21:43 RATE     SENDING:           0  RECEIVING:      6.12034
**09-07-2019--04:21:43 BELATED RECEIVED:          80**  AVG TIME:   1.84467e+16
09-07-2019--04:21:43 REORDER DISTANCE:          23
09-07-2019--04:21:43 WINDOW      FLOW:        8192  CONGESTION:        8192  FLIGHT:           0
09-07-2019--04:21:43 LINK         RTT:   314.072ms  BANDWIDTH:    41.52Mb/s
09-07-2019--04:21:43 BUFFERLEFT:  SND:    12288000  RCV:           11154000
09-07-2019--04:21:46 ======= SRT STATS: sid=106073246
09-07-2019--04:21:46 PACKETS     SENT:           0  RECEIVED:          1575
09-07-2019--04:21:46 LOST PKT    SENT:           0  RECEIVED:             0
**09-07-2019--04:21:46 REXMIT      SENT:           0  RECEIVED:             0**
09-07-2019--04:21:46 DROP PKT    SENT:           0  RECEIVED:             0
09-07-2019--04:21:46 RATE     SENDING:           0  RECEIVING:      5.72531
**09-07-2019--04:21:46 BELATED RECEIVED:           0**  AVG TIME:   1.84467e+16
09-07-2019--04:21:46 REORDER DISTANCE:          23
09-07-2019--04:21:46 WINDOW      FLOW:        8192  CONGESTION:        8192  FLIGHT:           0
09-07-2019--04:21:46 LINK         RTT:   314.117ms  BANDWIDTH:   38.256Mb/s
09-07-2019--04:21:46 BUFFERLEFT:  SND:    12288000  RCV:           10293000
09-07-2019--04:21:49 ======= SRT STATS: sid=106073246
09-07-2019--04:21:49 PACKETS     SENT:           0  RECEIVED:           998
09-07-2019--04:21:49 LOST PKT    SENT:           0  RECEIVED:             0
**09-07-2019--04:21:49 REXMIT      SENT:           0  RECEIVED:             0**
09-07-2019--04:21:49 DROP PKT    SENT:           0  RECEIVED:             0
09-07-2019--04:21:49 RATE     SENDING:           0  RECEIVING:      3.61867
**09-07-2019--04:21:49 BELATED RECEIVED:           0**  AVG TIME:   1.84467e+16
09-07-2019--04:21:49 REORDER DISTANCE:          23
09-07-2019--04:21:49 WINDOW      FLOW:        8192  CONGESTION:        8192  FLIGHT:           0
09-07-2019--04:21:49 LINK         RTT:   314.239ms  BANDWIDTH:    24.54Mb/s
09-07-2019--04:21:49 BUFFERLEFT:  SND:    12288000  RCV:           10290000

Thanks
MKS
