### ISSUE TITLE
srt_recvmsg failing with SRT_ERROR

### ISSUE THREAD

**Issue by ravtr** [Haivision/srt#842]
srt version: 1.3.1
we are seeing a occasional disconnections in srt receiver in client mode and at the same time there is no error reported in sender.
Below are the logs observed

Error received from element :srtclientsrc0: Could not read from resource.Debugging information: gstsrtclientsrc.c(205): gst_srt_client_src_fill (): /GstPipeline:pipeline0/GstSRTClientSrc:srtclientsrc0:
srt_recvmsg error: Connection was broken.Error received from element :srtclientsrc0: Internal data stream error.Debugging information: gstbasesrc.c(3055): gst_base_src_loop (): /GstPipeline:pipeline0/GstSRTClientSrc:srtclientsrc0:

Please find the implementation of gstsrtclientsrc.c [here](https://github.com/GStreamer/gst-plugins-bad/blob/566e4ecc223b18fce8bd932f5e4885f41f746dd4/ext/srt/gstsrtclientsrc.c)

Please let us know if this is a known issue and fixed in latest releases.
Let us know if you need more details

**Comment by maxlovic** [comment]
Hi @ravtr. This may happen due to network link gets disconnected. Is it possible in your environment.
Anyway better to use the latest release v1.3.4. There are bugfixes, that might also be related.

**Comment by ravtr** [comment]
Thanks for reply, there is a possibility of network error. This is happening in AWS environment across EC2 instances.
Can you help me understand how is link disconnection detected? Is it based on SRT ack timeout or is it from lower layer failures?

**Comment by maxlovic** [comment]
@ravtr,
When two peers are connected, they keep exchanging packets. If there is data transmission taking place, then sender will send DATA packets, receiver should reply with ACK packets, sender should reply with ACKACK packets to confirm it has received ACK packet from the receiver.
In case there is not data transmission happening, the peers exchange keepalive packets every 1 second.

In case no packet come from another side, the connection is considered broken after a certain timeout. The default timeous is 5 seconds.
Starting from v1.3.3 there is a [`SRTO_PEERIDLETIMEO`](https://github.com/Haivision/srt/blob/master/docs/API.md) socket option (PR #719). It defines the timeout to consider a connection broken.

When a connection is closed in a regular way (e.g. `srt_close()), a certain control packet called SHUTDOWN is sent from the side, initiating closure, to another side.

Some unexpected error may also happen on a socket. In case if is a fatal error (which should not normally happen), there will be an error message in stderr, the socket will be considered broken and will be closed. But so far it does **not** look you have this case.

**Comment by ravtr** [comment]
@maxlovic  thanks for detailed explanation.
Is there a way we can run srt library with debugs enabled, so catch the root cause of this?

**Comment by maxlovic** [comment]
There is. 
First, CMake offers two build options:

1. `ENABLE_LOGGING` is on by default. With this logs enabled you will see major errors and important notes.
2. Furthermore, verbose log can be turned on by `ENABLE_HEAVY_LOGGING` build option.

Then, SRT API provides `srt_setloglevel(...)`  and some other functions, described in [this document](https://github.com/Haivision/srt/blob/master/docs/API-functions.md#Logging-control). The default log level is error, so even with heavy logs enabled you might not see much of them. But with the `LOG_DEBUG` you should see almost everything.

**Comment by maxlovic** [comment]
Hi @ravtr Any updated on this issue?

**Comment by ravtr** [comment]
@maxlovic  this turns out to be our application issue, please go ahead and close this issue.
Thanks for looking into this
