### ISSUE TITLE
SRT STATS FREQUENCY ISSUE

### ISSUE THREAD

**Issue by dduquesne** [Haivision/srt#846]
Hello,

I have an issue or maybe it's just a question.
It's related to -s option using stransmit-live.
After some research, i understand that the integer passed here is not a "time period" but rather a "packet period".

https://github.com/Haivision/srt/issues/135
https://github.com/Haivision/srt/issues/38

It does not match with my experiments.
After looking at the source code, i am realy confused with this **counter** variable.
I have not found anything modifying this variable except the last second to last line of the read method below (Where the same variable is initialized).
So from my understanding, counter is always equal to one when computing need_stats_report.
That would break the purpose of -s option (And explain what i see).
Am i missing something ?

Thanks for your help,

int SrtSource::Read(size_t chunk, bytevector& data, ostream &out_stats)
{
    static unsigned long counter = 1;
    const bool need_bw_report = transmit_bw_report && (counter % transmit_bw_report) == transmit_bw_report - 1;
    const bool need_stats_report = transmit_stats_report && (counter % transmit_stats_report) == transmit_stats_report - 1;
    if (need_bw_report || need_stats_report)
    {
        CBytePerfMon perf;
        srt_bstats(m_sock, &perf, need_stats_report && !transmit_total_stats);
        if (stats_writer != nullptr) 
        {
            if (need_bw_report)
                cerr << stats_writer->WriteBandwidth(perf.mbpsBandwidth) << std::flush;
            if (need_stats_report)
                out_stats << stats_writer->WriteStats(m_sock, perf) << std::flush;
        }
    }
    ++counter;
    return stat;
}

**Comment by maxlovic** [comment]
Hi @dduquesne 
Yes, `-s` specifies a packet period. The variable `counter` is updated on every read or write. So if you specify `-s:1000`, you will get the stats after a 1000th packet is read by the application.
This is a known behaviour,
There are some plans to make it more convenient after higher priority tasks is done.

**Comment by dduquesne** [comment]
Hello @maxlovic 
Thanks for your feedback.
So counter is updated by the Read and Write method before evaluation to define need_stats_report.

**Comment by maxlovic** [comment]
@dduquesne
In you code snippet there is `++counter;`. It is called after the check for `need_stats_report`. Also please note it is initialized with 1.
`static unsigned long counter = 1;`

This innacuracy was also discussed a bit in #774.

**Comment by mbakholdina** [comment]
@dduquesne There is a feature request #1058 created to address this issue. Until the time this is implemented in `srt-live-transmit`, please feel free to use the test application [srt-xtransmit](https://github.com/maxsharabayko/srt-xtransmit) written by @maxsharabayko  which supports this function. In case of any questions regarding the `srt-xtransmit` usage, please submit an issue in its repo.
