### ISSUE TITLE
Axis ACAP platform implementation

### ISSUE THREAD

**Issue by renzo-s** [Haivision/srt#85]
Are there any efforts made/experiments done to see if the SRT protocol could be compiled for the Axis ip-camera ACAP platform? Or are there any foreseeable incompatibilities which would prevent such a 3rd party application?

**Comment by gurtajs4** [comment]
Hi,
Do you have toolchain  for Axis ACAP Platform available with you?

Regards,
Gurtaj

**Comment by adamyellen** [comment]
Hi @renzo-s. As long as the platform can meet the requirements there should be no issues building the project for any embedded system.

**Comment by jancamstreamer** [comment]
Hi, you can use CamStreamer ACAP which is already able to provide SRT on Axis camera. See https://camstreamer.com/
