### ISSUE TITLE
Add configuration option to disable deprecated functions.

### ISSUE THREAD

**Issue by zerodefect** [Haivision/srt#865]
Would a patch be welcomed so that a CMake configuration option could be included to disable deprecated functions from being included during compile time?

`
option(ENABLE_DEPRECATED_FUNCS "If off, deprecated functions will be ignored/excluded at compile time" ON)
`

**Comment by maxlovic** [comment]
Hi @zerodefect 
Not sure if this will be very helpful, unless someone really needs it. Better to gradually delete all the deprecated functions and constants.

**Comment by ethouris** [comment]
Turning on warning as errors as extra compile flags, with the deprecation warning turned on, should cause the same effect.
