### ISSUE TITLE
test-c-server example. undefined reference to `srt_startup', `srt_create_socket' and other

### ISSUE THREAD

**Issue by UnderOverCovered** [Haivision/srt#866]
Hello, can you help me please? When I am compiling test-c-server, from examples, I am getting an error:
`gcc fork2.c -o fork`
`/tmp/ccqhZ97y.o: In function `main':`
`fork2.c:(.text+0x76): undefined reference to `srt_startup'`
`fork2.c:(.text+0x8c): undefined reference to `srt_create_socket'`
`fork2.c:(.text+0xa4): undefined reference to `srt_getlasterror_str'`
`fork2.c:(.text+0x167): undefined reference to `srt_setsockflag'`
`fork2.c:(.text+0x18f): undefined reference to `srt_bind'
`fork2.c:(.text+0x1a7): undefined reference to `srt_getlasterror_str'`
`fork2.c:(.text+0x1ed): undefined reference to `srt_listen'
`fork2.c:(.text+0x205): undefined reference to `srt_getlasterror_str'`
`fork2.c:(.text+0x261): undefined reference to `srt_accept'`
`fork2.c:(.text+0x2ab): undefined reference to `srt_recvmsg'`
`fork2.c:(.text+0x2c3): undefined reference to `srt_getlasterror_str'`
`fork2.c:(.text+0x331): undefined reference to `srt_close'`
`fork2.c:(.text+0x349): undefined reference to `srt_getlasterror_str'`
`fork2.c:(.text+0x37f): undefined reference to `srt_cleanup'`
collect2: error: ld returned 1 exit status 

So what I did. I added a path to #include "srt/srt.h", because without it I got an fatal error. Also I tried to use <> insteed "", full path, nothing works...
I installed srt on ubuntu 18 via git clone and make.
`sudo apt-get install tclsh pkg-config cmake libssl-dev build-essential`
`git clone https://github.com/Haivision/srt`
`./configure`
`make`
`sudo make install`
Thank you in advance

**Comment by ethouris** [comment]
This command you showed doesn't look like compiling `test-c-server`.

**Comment by maxlovic** [comment]
@UnderOverCovered
The best way to build examples is to use cmake.
`cmake ./ -DENABLE_EXAMPLES=ON`
`cmake --build ./`
Or similar with configure:
`./configure --enable-examples`
`make`

**Comment by maxlovic** [comment]
And the message "undefined reference to `srt_startup', `srt_create_socket' and other" means that SRT library is not linked to the example application.

**Comment by UnderOverCovered** [comment]
> This command you showed doesn't look like compiling test-c-server
I copied test-c-server code in my own file, for test. I planned to modify it for my own goals. Sorry for confusion, fork2.c file is a full copy of test-c-server with include correction (`#include"srt/srt.h"`)

**Comment by UnderOverCovered** [comment]
@maxlovic thank you, I will try it

**Comment by ethouris** [comment]
If so, then please make an installation package of SRT library first, then install it, and then use `pkg-config` to obtain appropriate cflags and libs for apps that depend on it.

Kinda
```
gcc fork2.c -o fork $(pkg-config --cflags --libs srt)
```

**Comment by UnderOverCovered** [comment]
@ethouris thank you, i'll try

**Comment by UnderOverCovered** [comment]
@ethouris Maybe I missed something, gcc made compilation successful, but when I am running code, it returns an error: `./fork: error while loading shared libraries: libsrt.so.1: cannot open shared object file: No such file or directory
` 

Also, I do not touched the code (#include "srt" like in test-c-server example)

**Comment by ethouris** [comment]
Well, did you install the library? If so, do you have the path to your library in the ld.so configuration or `LD_LIBRARY_PATH` variable?

**Comment by UnderOverCovered** [comment]
O, yes I got it. `-- Install configuration: "Release"
-- Up-to-date: /usr/local/lib/libsrt.so.1.3.4`

Ok, I will add it by `LD_LIBRARY_PATH`

**Comment by UnderOverCovered** [comment]
About ld.so... I don't know where it is, sorry

**Comment by UnderOverCovered** [comment]
Ok, I have done this:
`export LD_LIBRARY_PATH="/usr/local/lib/libsrt.so.1.3.4"
`

and this:
`export LD_LIBRARY_PATH="/usr/local/lib/libsrt.so.1"
`
It doesn't helps

**Comment by ethouris** [comment]
Response to this largely exceeds the scope of the SRT library or associated applications.

**Comment by UnderOverCovered** [comment]
Excuse me, maybe it is language barrier, so can't understand correctly. So, you mean, that SRT can't work with custom c codes?

**Comment by maxlovic** [comment]
Use `export LD_LIBRARY_PATH="/usr/local/lib/`

**Comment by UnderOverCovered** [comment]
@maxlovic Thank you! That works! @ethouris Thank you too! Now we can close that issue. Good luck, SRT is the best!
