### ISSUE TITLE
"Belated received" packets in Rx stats

### ISSUE THREAD

**Issue by mks75** [Haivision/srt#868]
Hi @maxlovic,
With reference to #840, I have a new observation to share. In one of my test transfers, I have observed huge amount of "Belated received" packets for many hours. The same amount of packets are also reflected in "Rexmit received". This increased the stream transfer bitrate by almost double.
It started around 09-06-2019--05:49:16 and got corrected by itself around 09-07-2019--04:21:46
Not sure what caused this ?
![image](https://user-images.githubusercontent.com/34006918/64652266-6c5b1b80-d3f1-11e9-8a82-4709b2e56425.png)

![image](https://user-images.githubusercontent.com/34006918/64652274-711fcf80-d3f1-11e9-961e-8fac64ddd4c3.png)

![image](https://user-images.githubusercontent.com/34006918/64652285-7846dd80-d3f1-11e9-9919-67c5300d6d8a.png)

![image](https://user-images.githubusercontent.com/34006918/64652294-7da42800-d3f1-11e9-8f2c-a104e5b40c1a.png)

Rx log:
09-06-2019--05:49:10 ======= SRT STATS: sid=106073246
09-06-2019--05:49:10 PACKETS     SENT:           0  RECEIVED:          1001
09-06-2019--05:49:10 LOST PKT    SENT:           0  RECEIVED:             0
**09-06-2019--05:49:10 REXMIT      SENT:           0  RECEIVED:             0**
09-06-2019--05:49:10 DROP PKT    SENT:           0  RECEIVED:             0
09-06-2019--05:49:10 RATE     SENDING:           0  RECEIVING:      3.61805
**09-06-2019--05:49:10 BELATED RECEIVED:           0**  AVG TIME:   1.84467e+16
09-06-2019--05:49:10 REORDER DISTANCE:          16
09-06-2019--05:49:10 WINDOW      FLOW:        8192  CONGESTION:        8192  FLIGHT:           0
09-06-2019--05:49:10 LINK         RTT:   344.298ms  BANDWIDTH:   31.092Mb/s
09-06-2019--05:49:10 BUFFERLEFT:  SND:    12288000  RCV:           10296000
09-06-2019--05:49:13 ======= SRT STATS: sid=106073246
09-06-2019--05:49:13 PACKETS     SENT:           0  RECEIVED:           996
09-06-2019--05:49:13 LOST PKT    SENT:           0  RECEIVED:             0
**09-06-2019--05:49:13 REXMIT      SENT:           0  RECEIVED:             0**
09-06-2019--05:49:13 DROP PKT    SENT:           0  RECEIVED:             0
09-06-2019--05:49:13 RATE     SENDING:           0  RECEIVING:      3.61254
**09-06-2019--05:49:13 BELATED RECEIVED:           0**  AVG TIME:   1.84467e+16
09-06-2019--05:49:13 REORDER DISTANCE:          16
09-06-2019--05:49:13 WINDOW      FLOW:        8192  CONGESTION:        8192  FLIGHT:           0
09-06-2019--05:49:13 LINK         RTT:   344.324ms  BANDWIDTH:   48.348Mb/s
09-06-2019--05:49:13 BUFFERLEFT:  SND:    12288000  RCV:           10297500
09-06-2019--05:49:16 ======= SRT STATS: sid=106073246
09-06-2019--05:49:16 PACKETS     SENT:           0  RECEIVED:          1206
09-06-2019--05:49:16 LOST PKT    SENT:           0  RECEIVED:             0
**09-06-2019--05:49:16 REXMIT      SENT:           0  RECEIVED:           613**
09-06-2019--05:49:16 DROP PKT    SENT:           0  RECEIVED:             0
09-06-2019--05:49:16 RATE     SENDING:           0  RECEIVING:      4.37296
**09-06-2019--05:49:16 BELATED RECEIVED:         613**  AVG TIME:   1.84467e+16
09-06-2019--05:49:16 REORDER DISTANCE:          16
09-06-2019--05:49:16 WINDOW      FLOW:        8192  CONGESTION:        8192  FLIGHT:           0
09-06-2019--05:49:16 LINK         RTT:   344.425ms  BANDWIDTH:   27.912Mb/s
09-06-2019--05:49:16 BUFFERLEFT:  SND:    12288000  RCV:           10902000
09-06-2019--05:49:19 ======= SRT STATS: sid=106073246
09-06-2019--05:49:19 PACKETS     SENT:           0  RECEIVED:          1591
09-06-2019--05:49:19 LOST PKT    SENT:           0  RECEIVED:             0
**09-06-2019--05:49:19 REXMIT      SENT:           0  RECEIVED:          1090**
09-06-2019--05:49:19 DROP PKT    SENT:           0  RECEIVED:             0
09-06-2019--05:49:19 RATE     SENDING:           0  RECEIVING:      5.74473
**09-06-2019--05:49:19 BELATED RECEIVED:        1090**  AVG TIME:   1.84374e+16
09-06-2019--05:49:19 REORDER DISTANCE:          16
09-06-2019--05:49:19 WINDOW      FLOW:        8192  CONGESTION:        8192  FLIGHT:           0
09-06-2019--05:49:19 LINK         RTT:   344.502ms  BANDWIDTH:   22.524Mb/s
09-06-2019--05:49:19 BUFFERLEFT:  SND:    12288000  RCV:           11650500
09-06-2019--05:49:22 ======= SRT STATS: sid=106073246
09-06-2019--05:49:22 PACKETS     SENT:           0  RECEIVED:          1689
09-06-2019--05:49:22 LOST PKT    SENT:           0  RECEIVED:             0
**09-06-2019--05:49:22 REXMIT      SENT:           0  RECEIVED:          1071**
09-06-2019--05:49:22 DROP PKT    SENT:           0  RECEIVED:             0
09-06-2019--05:49:22 RATE     SENDING:           0  RECEIVING:      6.12039
**09-06-2019--05:49:22 BELATED RECEIVED:        1071**  AVG TIME:   1.84467e+16
09-06-2019--05:49:22 REORDER DISTANCE:          16
09-06-2019--05:49:22 WINDOW      FLOW:        8192  CONGESTION:        8192  FLIGHT:           0
09-06-2019--05:49:22 LINK         RTT:   344.502ms  BANDWIDTH:   32.352Mb/s
09-06-2019--05:49:22 BUFFERLEFT:  SND:    12288000  RCV:           12223500

.
.
.
.
.

09-07-2019--04:21:37 ======= SRT STATS: sid=106073246
09-07-2019--04:21:37 PACKETS     SENT:           0  RECEIVED:          1701
09-07-2019--04:21:37 LOST PKT    SENT:           0  RECEIVED:             0
**09-07-2019--04:21:37 REXMIT      SENT:           0  RECEIVED:           674**
09-07-2019--04:21:37 DROP PKT    SENT:           0  RECEIVED:             0
09-07-2019--04:21:37 RATE     SENDING:           0  RECEIVING:      6.15248
**09-07-2019--04:21:37 BELATED RECEIVED:         674**  AVG TIME:   1.84467e+16
09-07-2019--04:21:37 REORDER DISTANCE:          23
09-07-2019--04:21:37 WINDOW      FLOW:        8192  CONGESTION:        8192  FLIGHT:           0
09-07-2019--04:21:37 LINK         RTT:   339.562ms  BANDWIDTH:   28.176Mb/s
09-07-2019--04:21:37 BUFFERLEFT:  SND:    12288000  RCV:           12058500
09-07-2019--04:21:40 ======= SRT STATS: sid=106073246
09-07-2019--04:21:40 PACKETS     SENT:           0  RECEIVED:          1734
09-07-2019--04:21:40 LOST PKT    SENT:           0  RECEIVED:            13
**09-07-2019--04:21:40 REXMIT      SENT:           0  RECEIVED:           741**
09-07-2019--04:21:40 DROP PKT    SENT:           0  RECEIVED:            13
09-07-2019--04:21:40 RATE     SENDING:           0  RECEIVING:      6.19223
**09-07-2019--04:21:40 BELATED RECEIVED:         741**  AVG TIME:   1.84467e+16
09-07-2019--04:21:40 REORDER DISTANCE:          23
09-07-2019--04:21:40 WINDOW      FLOW:        8192  CONGESTION:        8192  FLIGHT:           0
09-07-2019--04:21:40 LINK         RTT:   322.831ms  BANDWIDTH:   30.636Mb/s
09-07-2019--04:21:40 BUFFERLEFT:  SND:    12288000  RCV:           12069000
09-07-2019--04:21:43 ======= SRT STATS: sid=106073246
09-07-2019--04:21:43 PACKETS     SENT:           0  RECEIVED:          1692
09-07-2019--04:21:43 LOST PKT    SENT:           0  RECEIVED:             0
**09-07-2019--04:21:43 REXMIT      SENT:           0  RECEIVED:            80**
09-07-2019--04:21:43 DROP PKT    SENT:           0  RECEIVED:             0
09-07-2019--04:21:43 RATE     SENDING:           0  RECEIVING:      6.12034
**09-07-2019--04:21:43 BELATED RECEIVED:          80**  AVG TIME:   1.84467e+16
09-07-2019--04:21:43 REORDER DISTANCE:          23
09-07-2019--04:21:43 WINDOW      FLOW:        8192  CONGESTION:        8192  FLIGHT:           0
09-07-2019--04:21:43 LINK         RTT:   314.072ms  BANDWIDTH:    41.52Mb/s
09-07-2019--04:21:43 BUFFERLEFT:  SND:    12288000  RCV:           11154000
09-07-2019--04:21:46 ======= SRT STATS: sid=106073246
09-07-2019--04:21:46 PACKETS     SENT:           0  RECEIVED:          1575
09-07-2019--04:21:46 LOST PKT    SENT:           0  RECEIVED:             0
**09-07-2019--04:21:46 REXMIT      SENT:           0  RECEIVED:             0**
09-07-2019--04:21:46 DROP PKT    SENT:           0  RECEIVED:             0
09-07-2019--04:21:46 RATE     SENDING:           0  RECEIVING:      5.72531
**09-07-2019--04:21:46 BELATED RECEIVED:           0**  AVG TIME:   1.84467e+16
09-07-2019--04:21:46 REORDER DISTANCE:          23
09-07-2019--04:21:46 WINDOW      FLOW:        8192  CONGESTION:        8192  FLIGHT:           0
09-07-2019--04:21:46 LINK         RTT:   314.117ms  BANDWIDTH:   38.256Mb/s
09-07-2019--04:21:46 BUFFERLEFT:  SND:    12288000  RCV:           10293000
09-07-2019--04:21:49 ======= SRT STATS: sid=106073246
09-07-2019--04:21:49 PACKETS     SENT:           0  RECEIVED:           998
09-07-2019--04:21:49 LOST PKT    SENT:           0  RECEIVED:             0
**09-07-2019--04:21:49 REXMIT      SENT:           0  RECEIVED:             0**
09-07-2019--04:21:49 DROP PKT    SENT:           0  RECEIVED:             0
09-07-2019--04:21:49 RATE     SENDING:           0  RECEIVING:      3.61867
**09-07-2019--04:21:49 BELATED RECEIVED:           0**  AVG TIME:   1.84467e+16
09-07-2019--04:21:49 REORDER DISTANCE:          23
09-07-2019--04:21:49 WINDOW      FLOW:        8192  CONGESTION:        8192  FLIGHT:           0
09-07-2019--04:21:49 LINK         RTT:   314.239ms  BANDWIDTH:    24.54Mb/s
09-07-2019--04:21:49 BUFFERLEFT:  SND:    12288000  RCV:           10290000

Thanks
MKS

**Comment by maxlovic** [comment]
Hi @mks75
You might want to set `SRTO_LOSSMAXTTL` to increase handle reordered packets.
Please see `SRTO_LOSSMAXTTL` in [API.md](https://github.com/Haivision/srt/blob/master/docs/API.md), and check #735

**Comment by jeandube** [comment]
In this case and unlike issue #840, the belated packets are also rexmitted packets. Here I think the retransmit upon timeout has triggerred, retransmitting all packet stuck by a stalled ACK, not knowing which one are really missing.

**Comment by mks75** [comment]
Yes, I agree. This is an unusual observation.
I understand from our previous discussion, that a belated packet is an original sent packet that has arrived late (out of order), and it's not a re-transmitted packet.
Here, all the belated packets are re-transmitted packets and took additional bandwidth for a long time (almost 22 hrs).
Please correct me in case I am wrong here. 

Also, what should be the value for SRTO_LOSSMAXTTL in this case?

Thanks
MKS

**Comment by maxlovic** [comment]
Depends on the network conditions and the sending rate. Start with 100 and see if it changes something.
What is the network you are using? LTE, Ethernet, something else?

**Comment by mks75** [comment]
@maxlovic, The source stream is 3.5Mbps approx, and I am using the public internet with ethernet connection to the device.

Thanks
MKS

**Comment by ethouris** [comment]
Belated packets are packets that have arrived with sequence past the last ACK-ed sequence at the receiver (that is, were sent uselessly in result). Note that ACK-ing in case of live mode could also happen due to that these packets were dropped.

Normally all these packets are also retransmitted packets only. Even though the R flag isn't checked when counting them, it's hardly possible that they are original packets - the only way when this can happen is when your network reorders UDP packets so often and on so large scale that the delay of a single reordered packet exceeds the latency setting.

The `SRTO_LOSSMAXTTL` option allows that - upon **detection** of reordering - the reordering tolerance grow, and this option defines the upper limit up to which it may grow. This tolerance then defines by how many packets sending a loss report for a detected loss should be postponed. Example:

* 11
* 12
* 15 -- LOSS: 13-14! -> report it.
* 16
* 17
* 13 -- late, but NOT RETRANSMITTED. RT=17-13 = 4
* 18
* 13 -- BELATED (retransmitted uselessly)
* 14 -- loss sealed (retransmitted)
* 19
* 21 -- LOSS: 20 -> but wait RT=4 more packets...
* 22 -- 3 more
* 23 -- 2 more
* 24 -- 1 more
* 25 - NOW, -> report the loss of packet **20**
* 26
* 27
* 28
* 20 -- GOT it, retransmitted
* 29
* 31 -- LOSS: 30 -> but wait 4 more packets...
* 32 -- 3 more
* 30 -- Well, reordered, but sealed the hole - no more loss, NO LOSS REPORTED.
* 33
...

**Comment by mks75** [comment]
Thanks @ethouris  for explaining the process.
So, ideally the Rx should wait for some time (defined by SRTO_LOSSMAXTTL) to receive the out of order packet, and if it's not received within this window (may be the packet is lost and/or further delayed), then only it should report Tx for a re-transmit?
 
But, I understand this time window should have a relation with the set latency for the transfer. So, like in this case, I have a stream of 3.5Mbps and have set a latency value of 1000, what range for SRTO_LOSSMAXTTL is available, before its too late for the process and the stream at Rx starts to give error?

Thanks
MKS

**Comment by maxlovic** [comment]
@mks75 
The receiver only processes incoming packets. So if a packet has arrived, its sequence number (`rpkt.m_iSeqNo`) is checked against the highest value of the received packet (`CUDT::m_iRcvCurrSeqNo`).
`if (rpkt.m_iSeqNo > CUDT::m_iRcvCurrSeqNo)`, then loss detection is triggered. Missing packets are added to loss list, but a loss report is not sent if the difference is within the tolerance.
This loss report is sent periodically if the `SRTO_NAKREPORT` is set to true (see [API.md](SRTO_NAKREPORT)). It is also sent when a new loss is detected.

The latency specifies when it is too late to try to resend a packet.

**Comment by maxlovic** [comment]
Closing as resolved. Please do not hesitate to reopen if required.
