### ISSUE TITLE
When remuxing SRT to MPEGTS using FFMPEG, CPU slowly grows. (Windows)

### ISSUE THREAD

**Issue by squinn92** [Haivision/srt#869]
I am using the following command line to grab an SRT stream from a Matrox Edge encoder.  Over time, CPU slowly climbs until we hit 100% on the system.  I need to copy the PTS times from the source stream to the destination to maintain stream sync between devices, if I use -re before the -i and don't use -copyts, I don't see this problem, but in my workflow I need -copyts.

ffmpeg -i srt://0.0.0.0:1050?mode=listener -c copy -copyts -y test.ts

I am guessing the timestamps being ahead of real-time is causing some sort of problem.  Any pointers would be appreciated.

**Comment by ethouris** [comment]
Just to let you know - we are aware of several issues related to CPU usage on Windows. We have some ongoing work to replace the threads and timers, and on Windows there will be used only those from C++11 standard library. The Windows version is using currently some 3rd party wrappers, which don't provide best emulation and accuracy.

**Comment by squinn92** [comment]
Is the refactoring work mentioned above expected to be part of the #800 pull request?  If so, is there an ETA on when that work may get back to mainline?  Thanks.

**Comment by ethouris** [comment]
Hard to say, we are in the middle of autumn vacation time, surprisingly. In about two weeks (when we are all back) we will likely have a defined date for 1.4.1 release. Anything else I'd tell you about it would be a speculation.

**Comment by maxsharabayko** [comment]
Hi @squinn92 
We've merged recently PR #929. It introduces steady clock (monotonic) timers.
Please check if it resolves this issue.

**Comment by squinn92** [comment]
It did seem to fix the problem!  Thank you for reaching out.  I’ve been running my workflow for over 30 minutes now with no CPU increase.  I’ll keep testing to be sure, but looks good.


Steve

**Comment by maxsharabayko** [comment]
Closing as resolved by #929. Fell free to reopen if the problem still persists.
Related issue #669
