### ISSUE TITLE
SRTO_LATENCY of 5000 with SRTO_TSBPDMODE enabled does not delay the received packets by 5 seconds

### ISSUE THREAD

**Issue by ryanbarber** [Haivision/srt#87]
My intent is to transmit an mpeg-ts stream with a fixed 5 second delay on the receiver side to allow for ample retransmission time of missed packets. My simplified example code setup for sender and receiver are below. Upon connection, the receiver's srt_recvmsg(..) starts by getting the packets with an expected 5 second delay from the sender; however, after approximately 30 seconds, that delay has linearly reduced to approximately 150ms. Is anyone else seeing this problem? Is there an error in my setup or am I fundamentally misunderstanding something?

//--------------------------------------------
Sender Setup example code:

int tsbpdMode = 1;
srt_setsockopt(ssock, 0, SRTO_TSBPDMODE, &tsbpdMode, sizeof(tsbpdMode));
int latencyMs = 5000;
srt_setsockopt(ssock, 0, SRTO_LATENCY, &latencyMs, sizeof(latencyMs));
srt_connect(ssock, (struct sockaddr*)&server, sizeof(server));
while(1){
    waitForNextPkt(pkt, pktlen);
    srt_sendmsg2(ssock, pkt, pktlen, NULL);
}

//--------------------------------------------
Receiver Setup example code:

int tsbpdMode = 1;
srt_setsockopt(rsock, 0, SRTO_TSBPDMODE, &tsbpdMode, sizeof(tsbpdMode));
int latencyMs = 5000;
srt_setsockopt(rsock, 0, SRTO_LATENCY, &latencyMs, sizeof(latencyMs));
srt_bind(rsock, (struct sockaddr*)&(serverdesc), sizeof(serverdesc));
srt_listen(rsock, 1);
csock = srt_accept(rsock, (struct sockaddr*)&from, &fromlen);
while(1){
    bytesRead = srt_recvmsg(csock, buf, buflen);
}

**Comment by gurtajs4** [comment]
+1 I believe the same is happening on my setup, need to verify the same

Regards,
Gurtaj

**Comment by ethouris** [comment]
Ok, it looks like you have forgotten one thing in the Sender's code:

    int yes = 1;
    srt_setsockopt(rsock, 0, SRTO_SENDER, &yes, sizeof yes);

Without this the connection is "pure UDT" and the "extra SRT handshake exchange" step, which does flag and value exchange for TSBPD mode and latency, isn't done.

This is the problem with the current stable version, which exchanges the extended information using the custom control messages, and the SENDER flag is just to mark the side that should initiate this control exchange. The party that hasn't this flag set simply awaits that the other party do it.

This problem has been dealt with, but only in the version that is currently available only in `dev` branch.

**Comment by ryanbarber** [comment]
Ok great, thank you for the explanation. I do have a follow up question: if both the sender and receiver have the SRTO_SENDER option set to yes, which sides' settings (i.e. latencyMs) are used?

**Comment by ethouris** [comment]
The latency value is "exchanged", even if you have one sender. If you set the latency value on both sides, the greater of the two will be taken. The sender initiates the extended handshake, and its sends its latency to the other party. The other party adjusts its latency value basing on its own and the incoming one, then sends the response with the adjusted latency value.

Not sure what will happen if both set `SRTO_SENDER`, but I guess this will be just one extra redundant operation. It won't change the latency anyway, probably this will just repeat the whole process.

Note that in the version below 1.3.0 SRT is considered unidirectional - you should send only from the side that declares itself sender. So, `SRTO_LATENCY` has kinda different meaning on sender and receiver: on receiver it defines the latency that it wants to use for the received data; on sender it defines a "minimum latency that a receiver may use".

**Comment by ocrete** [comment]
This sounds like a big whole in the documentation. The fact that one needs to set the latency or SRTO_TSBPDDELAY for the library to work as advertised should be documented in the readme or something.

**Comment by ethouris** [comment]
The documentation is currently under review; we'll post it on Wiki once it's ready.
