### ISSUE TITLE
SRT fails to recover when there's a momentary disconnection of input

### ISSUE THREAD

**Issue by yvvarun** [Haivision/srt#882]
GStreamer version: 1.14.4
SRT library version: 1.3.1

I'm using GStreamer to send SRT over a network and receive SRT.
There are 2 applications (GStreamer pipelines) - sender and receiver.
Sender is running in client/caller mode. Receiver is running in server/listener mode.

Receiver pipeline was able to receive data from the sender application until there was a momentary disconnection in the network. Whenever there's a network disconnection, the sender application will try to connect to the receiver repeatedly till it succeeds. However, it was never able to connect to the receiver application until the receiver application was restarted. Before restarting the receiver application, I suspected the issue could be in the sender application (which is GStreamer based), so I tried connecting to the receiver using stransmit test application which resulted in the same behaviour. What might be the issue here?

--------------------------------------------------
**using stransmit:**
/stransmit udp://:2222 srt://10.x.y.z:5000 -v -f
Media path: 'udp://:2222' --> 'srt://10.x.yz:5000'Opening SRT target caller on 10.x.y.z:5000

Parameters:
Opening SRT target caller on 10.x.y.z:5000

Connecting to 10.x.y.z:5000

Parameters:
Opening SRT target caller on 10.x.y.z:5000

Connecting to 10.x.y.z:5000

2360904 bytes lost, 0 bytes sent, 45345412 bytes received
Parameters:
Opening SRT target caller on 10.x.y.z:5000

Connecting to 10.x.y.z:5000

Parameters:
Opening SRT target caller on 10.x.y.z:5000

Connecting to 10.x.y.z:5000

601412 bytes lost, 0 bytes sent, 53154556 bytes received
794864 bytes lost, 7620956 bytes sent, 60968964 bytes received (This was after restarting the receiver application)

---------------------------------------------------

**Sender pipeline (SRT in caller mode):**
udpsrc name=srtudpsrc multicast-iface=lo address=127.0.0.1 port=2701 caps="application/x-rtp, media=(string)video, clock-rate=(int)90000, payload=(int)33, encoding-name=(string)MP2T" ! queue name=udpsrcqueue max-size-buffers=80000 max-size-bytes=100000000 max-size-time=10000000000 min-threshold-time=0 min-threshold-buffers=0 min-threshold-bytes=0 leaky=upstream  ! rtpjitterbuffer latency=40 ! queue name=rtpjitterbufferqueue ! rtpmp2tdepay ! queue max-size-buffers=0 max-size-bytes=0 max-size-time=600000000 min-threshold-time=0 min-threshold-buffers=0 min-threshold-bytes=0 ! srtclientsink uri=srt://192.168.1.222:7000 latency=500 max-lateness=100000000 key-length=16 passphrase=""

--------------------------------------------------

**Receiver pipeline:**
srtserversrc uri=srt://192.168.1.222:7000 latency=500  ! queue name=srtsrcqueue max-size-buffers=80000 max-size-bytes=100000000 max-size-time=10000000000 min-threshold-time=0 min-threshold-buffers=0 min-threshold-bytes=0 leaky=upstream ! queue ! tsparse ! queue ! rtpmp2tpay ! queue max-size-bytes=100000000 max-size-time=10000000000 min-threshold-time=0 min-threshold-buffers=0 min-threshold-bytes=0 leaky=upstream ! udpsink host=10.0.5.153 port=7001 multicast-iface=eno1 sync=false async=false

**Comment by ethouris** [comment]
Firstly, please note that we don't remember all bugs that we have probably fixed in the past (and could possibly affect your test results). Therefore I will be grateful if you can upgrade to the latest version available and repeat the test. Please note that the `stransmit` symbolic link as an alias to `srt-live-transmit` is no longer provided since version 1.3.3.

As I can see, additionally, you have tried to replace GStreamer with srt-live-transmit when sending, and this one uses SRT in caller mode. Inability to connect can result from two reasons: either the caller somehow fails, or the listener party has closed the listener socket and no longer listens. So, in order to see what happened at the latter site, you'd have to replace GStreamer with srt-live-transmit, too.

**Comment by mbakholdina** [comment]
Closed due to inactivity. Please do not hesitate to reopen if needed.
