### ISSUE TITLE
PowerPC Cross-compiled library disconnects/reconnects.

### ISSUE THREAD

**Issue by torlangballe** [Haivision/srt#895]
I've managed to cross-compile the library to 32-bit (!) PowerPC for embedded use. But I can't get it to work properly. Keeps destroying connection and reconnecting, I can get a second of video through from a multicast.

Has anybody tested on PowerPC. I guess using 32-bit and no floating point is really pushing my luck.

Is this even worth persuing?

Tor

**Comment by ethouris** [comment]
[Collecting log files](../blob/master/docs/reporting.md) could be helpful.

**Comment by torlangballe** [comment]
Thanks, that was very usefull and I couldn't see how to turn on more logging.

I figured it out, our probe does special stuff with network packages at the kernel level, which messed up the srt transport. It's working great now!

**Comment by ethouris** [comment]
Nice to see that the problem solved without involving us :)
