### ISSUE TITLE
Please provide a pkg-config file

### ISSUE THREAD

**Issue by lu-zero** [Haivision/srt#9]
It makes much easier to integrate with libraries in a clean way.

**Comment by ethouris** [comment]
Do you have any problems with the pkg-config file (`haisrt.pc`)?

In the projects in which we use SRT, we rely on the information stored there, so it must work.

These are the entries in CMakeLists.txt file that should be responsible for that:

    configure_file(scripts/haisrt.pc.in haisrt.pc @ONLY)
    install(FILES ${CMAKE_CURRENT_BINARY_DIR}/haisrt.pc DESTINATION lib/pkgconfig)

**Comment by lu-zero** [comment]
I overlooked those lines and I was looking for srt when blindly running
pkg-config :)

You should populate the `Version:` tag though.

**Comment by ethouris** [comment]
Oh, sorry, yes, I overlooked that small aspect when I was changing HAISRT prefix to SRT - sorry, my fault :)

Providing the fix now...

**Comment by ethouris** [comment]
AFAIK now all fixes are in place: all variables are correctly filled in, and the pkg-config file is generated as both `haisrt.pc` (for legacy and backward compatibility, DEPRECATED) and `srt.pc`. Please check if it's ok and close if so.
