### ISSUE TITLE
overwrite output stats to file for srt-live-transmit

### ISSUE THREAD

**Issue by gewinnerr** [Haivision/srt#902]
1. Is it possible to overwrite output stats file without restarting srt-live-transmit ?
2 .Is it possible to get zero values in output stats file for all metrics when the SRT source is disconnected, but srt-live-transmit app enable?

**Comment by mbakholdina** [comment]
@gewinnerr I am not sure whether we will implement this, because `srt-live-transmit` was designed as a simple test application which supports SRT. But adding the ticket in the roadmap #1215  for future consideration. Closing the issue for now.
