### ISSUE TITLE
Error decoding json stats with python "Extra data"

### ISSUE THREAD

**Issue by AlexandreLicinio** [Haivision/srt#905]
Hello, i get error when loading json file from stats with python:

`raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 2 column 1 - line 3 column 1 (char 438 - 441)`

And the file with `cat ../../db/json/19911.json`:
`{"sid":1567223,"time":78630,"window":{"flow":8131,"congestion":8192,"flight":1},"link":{"rtt":87.304,"bandwidth":14.58,"maxBandwidth":30},"send":{"packets":21936,"packetsLost":2030,"packetsDropped":0,"packetsRetransmitted":1938,"bytes":29832960,"bytesDropped":0,"mbitRate":3.03527},"recv": {"packets":0,"packetsLost":0,"packetsDropped":0,"packetsRetransmitted":0,"packetsBelated":0,"bytes":0,"bytesLost":0,"bytesDropped":0,"mbitRate":0}}
}}`

you see, the `}}` is extra data !

**Comment by maxlovic** [comment]
@AlexandreLicinio  Please specify the version you have tried.

Checked with the latest master b9a4d1f51ec77c6807d8594b91a3da6379d2f396
Command-line
```
srt-live-transmit srt://:4200 udp://127.0.0.1:4201 -pf json -statsout "stats.json" -s 100
```
Output (stats.json):
```
{"sid":629361413,"time":1184,"window":{"flow":8192,"congestion":8192,"flight":0},"link":{"rtt":0.075,"bandwidth":12,"maxBandwidth":1000},"send":{"packets":0,"packetsLost":0,"packetsDropped":0,"packetsRetransmitted":0,"packetsFilterExtra":0,"bytes":0,"bytesDropped":0,"mbitRate":0},"recv": {"packets":110,"packetsLost":0,"packetsDropped":0,"packetsRetransmitted":0,"packetsBelated":0,"packetsFilterExtra":0,"packetsFilterSupply":0,"packetsFilterLoss":0,"bytes":149600,"bytesLost":0,"bytesDropped":0,"mbitRate":1.01069}}
{"sid":629361413,"time":2247,"window":{"flow":8192,"congestion":8192,"flight":0},"link":{"rtt":0.073,"bandwidth":12,"maxBandwidth":1000},"send":{"packets":0,"packetsLost":0,"packetsDropped":0,"packetsRetransmitted":0,"packetsFilterExtra":0,"bytes":0,"bytesDropped":0,"mbitRate":0},"recv": {"packets":100,"packetsLost":0,"packetsDropped":0,"packetsRetransmitted":0,"packetsBelated":0,"packetsFilterExtra":0,"packetsFilterSupply":0,"packetsFilterLoss":0,"bytes":136000,"bytesLost":0,"bytesDropped":0,"mbitRate":1.02337}}
{"sid":629361413,"time":3311,"window":{"flow":8192,"congestion":8192,"flight":0},"link":{"rtt":0.058,"bandwidth":12,"maxBandwidth":1000},"send":{"packets":0,"packetsLost":0,"packetsDropped":0,"packetsRetransmitted":0,"packetsFilterExtra":0,"bytes":0,"bytesDropped":0,"mbitRate":0},"recv": {"packets":100,"packetsLost":0,"packetsDropped":0,"packetsRetransmitted":0,"packetsBelated":0,"packetsFilterExtra":0,"packetsFilterSupply":0,"packetsFilterLoss":0,"bytes":136000,"bytesLost":0,"bytesDropped":0,"mbitRate":1.02242}}
{"sid":629361413,"time":4375,"window":{"flow":8192,"congestion":8192,"flight":0},"link":{"rtt":0.069,"bandwidth":12,"maxBandwidth":1000},"send":{"packets":0,"packetsLost":0,"packetsDropped":0,"packetsRetransmitted":0,"packetsFilterExtra":0,"bytes":0,"bytesDropped":0,"mbitRate":0},"recv": {"packets":100,"packetsLost":0,"packetsDropped":0,"packetsRetransmitted":0,"packetsBelated":0,"packetsFilterExtra":0,"packetsFilterSupply":0,"packetsFilterLoss":0,"bytes":136000,"bytesLost":0,"bytesDropped":0,"mbitRate":1.02237}}
```
No extra "}}" in the end of line. Passes json validation: [link](https://jsonformatter.curiousconcept.com/).

**Comment by AlexandreLicinio** [comment]
This one [https://github.com/Widixo/srt](url) my colleague cedric make me ones with data write instead append. I can bypass the error in python but i would like something clean.
Also why you don'tre-write data and do append ? Imagine the server ou the stream runs for months, the log will be BIG !
thanks

**Comment by maxlovic** [comment]
Please share your command line.
Do you happen to use SRT both as source and destination?

**Comment by AlexandreLicinio** [comment]
yes both are SRT, the encoder and the decoder

for the transmitter:
`./srt-live-transmit srt://<public_ip>:11199?mode=listener udp://239.127.0.1:11199 -t:-1 -v -statspf:json -statsout:$HOME/programs/ekla/collect/db/json/11199.json -s 5000 -f -loglevel:info -logfa:all -logfile:/home/ekla/programs/ekla/collect/db/logs/11199.log 2>&1 | tee /home/ekla/programs/ekla/collect/db/stdout/11199.stdout`

we use stdout to read current statuts (Accepted, listen, etc...) because that info isn't present in stats or log.

**Comment by maxlovic** [comment]
I see. There is no mutex on writing stats to the same output. Therefore two streams might mix up.

**Comment by AlexandreLicinio** [comment]
what is a mutex ? 2x streams ? why ? Sorry this is not clear for me.

**Comment by maxlovic** [comment]
Please check if #939 fixed the issue.

> what is a mutex ? 2x streams ? why ? Sorry this is not clear for me.

No worries. That was a developer's note to state the problem.

**Comment by AlexandreLicinio** [comment]
ah ok my bad! thanks @maxlovic 👍 as i said for now i can bypass the error with a python trick so this isn't mandatory for us

**Comment by maxlovic** [comment]
**A developer's note**
Now I remembered source and destination in srt-live-transmit are processed in a loop. There are no threadsd sharing the same resource (stats output). Therefore no mutex is required.
Therefore unlikely to be the root of the problem.

**Comment by maxlovic** [comment]
Checked with **srt** both as source and target. Works perfect even without a fix #939 (_because both source and destination sockets are processed in a loop, not in a different threads_).

> This one https://github.com/Widixo/srt my colleague cedric make me ones with data write instead append.

I suppose you might have a mistake in the place where you chenge append to write. Please check.

**Comment by AlexandreLicinio** [comment]
since the latest update you did about srt, json stats are still append or re-write ?

**Comment by maxlovic** [comment]
Every new line is appended into the output file. Output for stats was designed to provide the possibility to analyze the behavior in dynamics, therefore all the stats are accumulated.

> we use stdout to read current statuts (Accepted, listen, etc...)

With stats output to `stdout` you can read line by line with the current version. You don't need to change anything in the code.

You could also try to turn the verbose mode on with `-v`. You will get connection and disconnect notifications in stderr then.

**Comment by AlexandreLicinio** [comment]
Could you please enable an option --append to --write ? A i said it is difficult to handle 1GB or more about log files in occasionnal services. And also we could code a netdata plugin for such a case and send the data to a prometheus to long store metrics.
And if i may, stderr or stdout are always tricky, it could be nice to have a status key in the json and with the value, disconnect, connect, listen, error.
thanks

**Comment by maxlovic** [comment]
Please submit a separate feature request for this. With a detailed description of the usage scenario.
So far does not look like a general use case. Maybe you could try a named [pipe](https://linux.die.net/man/3/mkfifo).

Please also note that `srt-live-transmit` is a sample application. Such feature requests to sample apps have low prioority. We encourage the community to submit PRs if some functionality is missing.

**Comment by AlexandreLicinio** [comment]
Ok, thanks.
