### ISSUE TITLE
How to know is stream is Connected or Disconnected in stats/logs ?

### ISSUE THREAD

**Issue by AlexandreLicinio** [Haivision/srt#908]
Hello, 

Is there a way to know if the stream is connected and/or disconnected in stats ?
Currently when stream is disconnected, all stats are freezed.
In log we can only get new lines when the source is connected but not when it disconnects.
It could be very helpful to get a status key in the json file with 0 or 1 regarding the connection status of the stream.
Thanks

**Comment by mbakholdina** [comment]
Hi @AlexandreLicinio , thank you for your suggestion! I am not yet sure whether we will have time to implement this functionality in `srt-live-transmit` as it was designed as a simple test application. However, I am adding this FR for future consideration in ["Revise and improve SRT stats API" roadmap](https://github.com/Haivision/srt/issues/1215). Will see whether we can make some improvements in this direction.

Relates to #902 .

Closing the ticket for now.
