### ISSUE TITLE
SRT apps build with static SSL linking

### ISSUE THREAD

**Issue by colmaengus** [Haivision/srt#909]
We are locally building mbedtls so I'm using USE_ENCLIB, SSL_LIBRARY_DIRS and SSL_INCLUDE_DIRS build flags to build libsrt.a.

The libsrt.a builds fine but I would like to have srt-live-transmit built using libmbedcrypto.a and libmbedtls.a to confirm that our mbedtls build is working.

Is this somehow supported with the current build flags? If not any pointers on how to add support for this?

**Comment by ethouris** [comment]
Is the question how to force it compile against the static SSL libraries as well? I'm not sure if we have any "slot" to screw in the `-static` option for the linker, although you can try using `WITH_EXTRALIBS` build variable (`-DWITH_EXTRALIBS=-static`), as long as you use gcc or clang.

**Comment by colmaengus** [comment]
When I enable the applications it wants to link against dynamic versions of mbedtls rather than static. I start making changes to the CMakeLists.txt but thought I should double check first in case this was already supported. I was thinking of adding a STATIC_SSL mode which could enable linking against static rather than dynamic SSL libs.

**Comment by lewk2** [comment]
I have used the OPENSSL_USE_STATIC_LIBS option when compiling against VS2013.

It has issues with 2015, one of our devs at Cinegy indicated with might be something to do with cmake rather than the SRT code.

You can see a commit with this set here:
https://github.com/Cinegy/srt/commit/6d467f228060c0c21e176ad0f61715e6252a0379

I realise you are talking about a different library than OpenSSL here, but the title of the issue compelled me to add this info :)

**Comment by maxsharabayko** [comment]
Hi @colmaengus 
> ... I start making changes to the CMakeLists.txt but thought I should double check first in case this was already supported. 

I wonder if you have these changes ready for contribution. Is it still topical?

**Comment by colmaengus** [comment]
Looking back at the code it seems that we skipped the application build using ENABLE_APPS=OFF and included both srt and mbedtls in our application. This is the cmake command we are using:
`cmake -DENABLE_APPS=OFF -DENABLE_SHARED=OFF -DUSE_ENCLIB="mbedtls" -DSSL_INCLUDE_DIRS=${TLS_SRC_DIR}/include -DSSL_LIBRARY_DIRS=${TLS_BUILD_DIR}/library -B${SRT_BUILD_DIR} -H${SRT_SRC_DIR}`
I

**Comment by maxsharabayko** [comment]
So as I understand, with OpenSSL there is a `-DOPENSSL_USE_STATIC_LIBS` CMake option that makes it possible to link static OpenSSL with apps.

However, there is no similar option for mbedTLS, and apps are trying to link themselves against the dynamic mbedTLS.
> When I enable the applications it wants to link against dynamic versions of mbedtls rather than static.

**Comment by colmaengus** [comment]
I don't see a OPENSSL_USE_STATIC_LIBS switch. There are ENABLE_STATIC and ENABLE_SHARED which enable static/dynamic builds of libsrt. I think we need an extra flag to indicate that the apps should use static or dynamic linking against dependency libs.

**Comment by ethouris** [comment]
Depends where you search for it. SRT build system doesn't define it. I'm not sure how exactly other projects solve this problem, but definitely exposing library-specific flags for the users is a working approach.

**Comment by maxsharabayko** [comment]
It is the option of the FindOpenSSL module of CMake
https://cmake.org/cmake/help/v3.7/module/FindOpenSSL.html

**Comment by maxsharabayko** [comment]
So, it looks like we can close it.
CMake just does not have a dedicated option to link against the static mbedTLS library.
But it is probably not something SRT should handle in its CMake.

**Comment by rdp** [comment]
CMakeLists.txt has some custom sections that uses OPENSSL_USE_STATIC_LIBS in case it's useful...
