### ISSUE TITLE
High bit-rate video support

### ISSUE THREAD

**Issue by prabh13singh** [Haivision/srt#911]
Hi,
Anybody able to use bit-rate video of more than 300 Mbps?
What should be changed in the code like buffer sizes to achieve the bit-rate because I am continuously seeing packet drops.
Thanks.

**Comment by maxlovic** [comment]
Hi @prabh13singh Please check #703.

**Comment by prabh13singh** [comment]
I was busy on some other issue but still not able to get it working.
Video bitrate is 640Mbps.
According to your suggestions:
 const int FC = 2 * bps * msRTT / 1000 / 8 / (1500 - 28);
    const int rcvBufBytes = msLatency * bps / 1000 + bps * msRTT / 1000 / 8 / (1500 - 28);
    const int sndBufBytes = rcvBufSize;

My RTT is around 270 ms.

So, FC should be = 2*640,000,000*270/1000/8/1472 = 29,347.
and buffer sizes should be 76800000+14673 =76814673
 
I have tried even double than that, but no luck. 
Transmitter logs show : "Congested maxbw"
Receiver logs show : "No room to store incoming packets"

Correct me If am wrong.
Thanks.

**Comment by maxlovic** [comment]
Please consider setting latency to 4xRTT.
If does not help, please collect CSV stats. If you are using srt-live-transmit, use options
-pf csv -statsout stats.csv -s 1000
