### ISSUE TITLE
Command line for Cmake, don't want to use configure and tcl interpreter  

### ISSUE THREAD

**Issue by topilski** [Haivision/srt#912]
Hello, is it possible to build a project without tcl interpreter? Also will be good to know do you have tar.gz archives with stabled versions, not in Github? thank you

**Comment by ethouris** [comment]
Yes, cmake can be as well used directly. `configure` (Tcl-dependent) is only a wrapper.
No, we don't have any archives of old versions.

**Comment by topilski** [comment]
Hello @ethouris , thank you for your answers, we don't need old packages, we need repository where we can download needed version. Also will be glad to have test link with srt output and players as well, because we using GStreamer plugins and can't check how our service works.

**Comment by ethouris** [comment]
Use `git tag` to list all the tags. Tags according to vX.X.X scheme mark the releases. By issuing `git checkout vX.X.X` on the repository you can reach particular version.

**Comment by topilski** [comment]
Thank you @ethouris what about tests streams and players, do you have suggestions?

**Comment by maxlovic** [comment]
Check out [VLC media player](https://maxlovic.gitbook.io/srt-cookbook/apps/vlc-media-player) for playback and [FFmpeg](https://maxlovic.gitbook.io/srt-cookbook/apps/ffmpeg) for streaming.

**Comment by topilski** [comment]
Thank you @maxlovic i'am interested of GStreamer part, want to test srtsink and srtsrc, 1.16 version

**Comment by topilski** [comment]
Very strange but stream playing without an image. Do you know srtsink in GStreamer 1.16 is stable?

**Comment by maxlovic** [comment]
> Do you know srtsink in GStreamer 1.16 is stable?

Don't know this. But you can join the SRTAlliance slack channel and ask there: [invitation link](https://slackin-srtalliance.azurewebsites.net/).

We also have some docs on GStreamer you might want to take a look: [link](https://github.com/Haivision/srt/blob/master/docs/gstreamer.md).

Closing this thread as resolved.
