### ISSUE TITLE
srt_epoll_wait  return different error no between v1.3.x and v1.4 within multiple threads. 

### ISSUE THREAD

**Issue by Edward-Wu** [Haivision/srt#918]
hi,all
I call the srt_epoll_wait within multiple threads, when no event readiness, this function will return -1 value with error-no SRT_ETIMEOUT(6003) in v1.3.x, but return -1 value with error-no 5003 ‘Operation not supported: Bad parameters’ in v1.4.0

I want to know as timeout why not return SRT_ETIMEOUT in v1.4.0 ?

**Comment by ethouris** [comment]
It's not possible. I checked the sources and the errors reported by `srt_epoll_wait` are:

* `SRT_EINVPARAM`, when the epoll container is empty (NOTE: also if it became empty while this function was stuck in a call)
* `SRT_ETIMEOUT`, when the time limit was passed (not -1) and it was reached before any sockets are ready

So, if you got the `SRT_EINVPARAM` error (5003), the only situation that could have triggered it was that the epoll container is (also: became) empty. This could have happed also if:

* you have unsubscribed all sockets from the epoll container (`srt_epoll_remove_usock`)
* you have closed all sockets that the epoll container was subscribed to

This was so in 1.3.4 and this remains so in 1.4.0. 

In 1.4.0 version there was some extra flexibility added, which allows that the first one isn't reported, while the risk that the function could get stuck here forever is acceptable. It is useful when you have a multithreaded application and you'd like to start waiting **without** any sockets added at this time, but you will add them later from another thread. If you want this behavior, add this call after `epol_container = srt_epoll_create()`:
```
srt_epoll_set(epoll_container, SRT_EPOLL_ENABLE_EMPTY);
```
If you call this function with `0` as flags, it will reset all behavior flags to default ones. This may be useful if you have a still waiting call to `srt_epoll_wait()`, but all sockets were unsubscribed from the epoll container, and you would like to interrupt it somehow.

**Comment by Edward-Wu** [comment]
hi, ethouris
thanks for your analyzation.

As you said, I call the srt_epoll_create function in one thread and call the srt_epoll_wait in another thread. 

my called srt_epoll_wait function code is as follow:
------
ret = srt_epoll_wait(m_eid, m_read_socks, &read_len, m_write_socks, &write_len, POLLING_TIME, 0, 0, 0, 0);
     if (ret < 0) {
         sls_log(SLS_LOG_TRACE, "[%p]CSLSGroup::handle, worker_number=%d, srt_epoll_wait, no epoll event, ret=%d.",
                 this, m_worker_number, ret);
         ret = srt_getlasterror(NULL);
         if (ret == SRT_ETIMEOUT)//6003
             ret = SLSERROR(EAGAIN);
         else
             ret = CSLSSrt::libsrt_neterrno();
------

I test the difference between srt v1.3.4 and srt v1.4.0 again when the epoll container is empty. in v1.3.4 the result of function srt_epoll_wait is <0 and the result of srt_getlasterror is SRT_ETIMEOUT, but in v1.4.0 the result of srt_getlasterror is SRT_EINVPARAM (5003).
so I get the conclusion that the error code of srt_epoll_wait function has different value.

According to your suggestion I add the srt_epoll_set function after srt_epoll_create call, the result of srt_epoll_wait is SRT_ETIMEOUT(6003) in both versions when the container is empty.

thank you again.
