### ISSUE TITLE
FEC static checker complaints

### ISSUE THREAD

**Issue by maxlovic** [Haivision/srt#922]
|    file        |line  |   category  | description                                                   |
|----------------|------|-------------|---------------------------------------------------------------|
|srtcore/fec.cpp | 1911 | Performance | Function parameter 'loss' should be passed by const reference.|
|srtcore/fec.cpp | 1716 | Code Style  | Variable 'any_dismiss' is assigned a value that is never used.|
|srtcore/fec.cpp | 2123 | Code Style  | Variable 'oldbase' is assigned a value that is never used.|

**Comment by ethouris** [comment]
Fix 1: ok, taking it, should work
Fix 2: not true, this variable is used in HLOGC macro below, which is though removed when ENABLE_HEAVY_LOGGING is off.
Fix 3: yes, and it is also explicitly declared as unused, intentionally. It's also used in the logs.
