### ISSUE TITLE
Cross compiling with mingw results in SRT lib that links to pthread, stdc++, gcc_s and gcc

### ISSUE THREAD

**Issue by Xaymar** [Haivision/srt#925]
When cross compiling srt using x86_64-w64-mingw32 tools, the SRT library additionally links to libstdc++ libgcc_s_seh-1 and libwinpthread-1.  I understand the dependency on libwinpthread-1, but don't quite get where libstdc++ and libgcc_s_seh-1 are added. The dependency on libstdc++ and libgcc_s_seh-1 isn't added by libwinpthread-1, but seem to come from srt itself. Is there any way to avoid these being added when cross compiling?

**Comment by Xaymar** [comment]
I tried `-DUSE_STATIC_LIBSTDCXX=On`, however it only had an effect on the `srt.pc` file. The `libsrt.dll` file continued to link dynamically against libstdc++-6.dll and libgcc_s_seh-1.dll:
![image](https://user-images.githubusercontent.com/437395/67621640-946fd400-f811-11e9-9ff8-bff5d8a2b8e3.png)

**Comment by Xaymar** [comment]
Managed to fix the extra dependencies by overriding CMAKE_EXE_LINKER_FLAGS and CMAKE_SHARED_LINKER_FLAGS with `-static-libcc -static-libstdc++`. Now I'm getting exactly what I needed.

**Comment by ethouris** [comment]
> Managed to fix the extra dependencies by overriding CMAKE_EXE_LINKER_FLAGS and CMAKE_SHARED_LINKER_FLAGS with `-static-libcc -static-libstdc++`. Now I'm getting exactly what I needed.

@Xaymar just a quick note: the `USE_STATIC_LIBSTDCXX` option does add `-static-libstdc++` to `CMAKE_EXE_LINKER_FLAGS` (and that's event its only result). Are you saying that without `-static-libgcc` the libstdc++ library will still be linked dynamically on MinGW?

**Comment by Xaymar** [comment]
It seems like it, as the final dll was still dynamically being linked to both.

**Comment by freedreamer** [comment]
I am building SRT use a customed toolchains.
I tried -DUSE_STATIC_LIBSTDCXX=1, however it had non effect  The libsrt.so is still linked dynamically against libstdc++.so.6...
I used cmake commands like this:
cmake . \
  -DCMAKE_TOOLCHAIN_FILE=${SRT_DIR}/cmake/toolschain/${ARCH}.toolchain.cmake \
  -DCROSS_TOOLS_PATH=${CROSS_TOOLS_PATH} \
  -DCROSS_TARGET=${CROSS_TARGET} \
  -DKERNEL_INCLUDE=${KERNEL_INCLUDE} \
  -DENABLE_APPS=0 \
  -DENABLE_CODE_COVERAGE=0 \
  -DENABLE_ENCRYPTION=0 \
  -DENABLE_SHARED=1 \
  -DENABLE_STATIC=0 \
  -DUSE_STATIC_LIBSTDCXX=1 \
  -DUSE_CXX_STD=11 \
  -DCMAKE_INSTALL_PREFIX=${SRT_INSTALL_DIR} \

It seems the  -DUSE_STATIC_LIBSTDCXX=1 not effected, is there still some other config need to add？
