### ISSUE TITLE
ffmpeg: listener can't read streamid from caller

### ISSUE THREAD

**Issue by m-garanin** [Haivision/srt#934]
I use ffmpeg as listener and got SRTContext , but "streamid" is null (caller sent it).

It very seems "libsrt_set_options_post" does not include reading of SRTO_STREAMID from caller.

// PRE handler consists reading SRTO_STREAMID but it's not for caller in my opinion....

**Comment by ethouris** [comment]
That is possible. Trouble is, we are not tracking the development of ffmpeg to see how good they implement the existing concepts from SRT. I think it would be best if you start raising issues against ffmpeg for this, and you can link this issue to it so that we are updated about the state, or provide some help if needed.

**Comment by m-garanin** [comment]
I created https://trac.ffmpeg.org/ticket/8351 
Let me ask: I should use UDT::getstreamid inside listener   for read "stream id" from caller?

**Comment by ethouris** [comment]
This is a helper function that could be used for that, yes, but this is a kinda "extended" C++-only API. This value can be simply read by `srt_getsockflag` function using `SRTO_STREAMID` option. The difference is that this is kept as `std::string` internally and `UDT::getstreamid` simply returns it, while `srt_getsockflag` will have to copy it into an array passed to this function, and it should have a space for maximum 512 characters.

**Comment by m-garanin** [comment]
thank you,

so I can use this steps:

srt_listen --> srt_accept--->srt_getsockflag(...SRTO_STREAMID..)

// without timeout for wait when caller send streamid

**Comment by ethouris** [comment]
Right.
