### ISSUE TITLE
"// XXX Note that the srctime functionality doesn't work yet and needs fixing." is this true or false?

### ISSUE THREAD

**Issue by oviano** [Haivision/srt#937]
I have been looking through the code and from what I can see if you set this field in MSGCTRL and use sendmsg2 then it does find it's way down to m_ullSourceTime_us and then appears to be getting picked up by CSndBuffer::readData

So is that just an old comment in the code I should ignore?

I noticed that the API describes "srctime" and doesn't mention anything about it not working yet, so am I safe to use it?

I am splitting up my encoded video stream into packets and then calling srt_send() at appropriate time intervals, but of course that means I have to run my own send timing/delay code which I'd rather not do if I can just use sendmsg2 and pass in the srctime and let SRT deal with it.

Of course, I also need to then add srt_gettime() to return get CUDT::CTimer()::getTime() so I can use the same timing system - assuming I am taking the right approach here, can we have a srt_gettime()?

**Comment by maxlovic** [comment]
This functionality does not work yet. Refer to #930

**Comment by oviano** [comment]
930 states that the srctime is ignored, but I don't think it is?

Inside...

int CUDT::sendmsg2(const char* data, int len, ref_t<SRT_MSGCTRL> r_mctrl)

...we have...

m_pSndBuffer->addBuffer(data, size, mctrl.msgttl, mctrl.inorder, mctrl.srctime, Ref(mctrl.msgno));

...then inside...

void CSndBuffer::addBuffer(const char* data, int len, int ttl, bool order, uint64_t srctime, ref_t<int32_t> r_msgno)

...we have...

        s->m_ullSourceTime_us = srctime;
        s->m_ullOriginTime_us = time;
        s->m_iTTL = ttl;

...then inside...

int CSndBuffer::readData(char** data, int32_t& msgno_bitset, uint64_t& srctime, int kflgs)

...we have...

   srctime =
      m_pCurrBlock->m_ullSourceTime_us ? m_pCurrBlock->m_ullSourceTime_us :
      m_pCurrBlock->m_ullOriginTime_us;

...so why wouldn't I be able to just provide a different (e.g. slightly later) srctime retrieved from a call to CTimer::getTime()?

I guess I'm missing something else?

**Comment by maxlovic** [comment]
You are right. The `srctime` is only used if peer has TSBPD enabled, and 
`if (origintime >= m_stats.startTime)`
where `m_stats.startTime` is the time when the socket was opened.

This means that the time stamp to be provided by the application is better to come from the same clock, as used by the library.

> I am splitting up my encoded video stream into packets and then calling srt_send() at appropriate time intervals, but of course that means I have to run my own send timing/delay code which I'd rather not do if I can just use sendmsg2 and pass in the srctime and let SRT deal with it.

Could you please describe your use case in more details? So that we can use it to describe the target usage.

The source time will only impact the reading time on the receiver's side.
A packet will be sent as soon as it is given to the library (with respect to the minimum inter packet time, set by MAXBW).
After the receiver receives the packet, it will wait until it is the right time to give the packet to the application. And here is when the timestamp (taken from source time) is used.

**Comment by ethouris** [comment]
There are many things that need to work correctly so that this mechanism can work properly and as expected. This mechanism more-less should work, but there are some distinct problems we detected during testing and they must be taken care of first.

**Comment by oviano** [comment]
Thank you! Yes, having studied the code further I now understand better. As you mention I previously thought that the srctime would influence the time a message was sent in addition to the timestamp when it was received. I now see this is not the case.

My server application encodes a live video stream and I am delaying the send of each packet to try and get an optimum situation; e.g. if a particular video frame had time stamp T, but was split into N packets, then each packet 1...N would be sent at a slightly different time so that the whole transmission time takes the duration of one frame.

So to achieve this I sleep a short amount of time before calling srt_send() but then I fall into the same inaccuracy based on Windows timers. So my thinking was that if srctime was influencing the send time (which I now know is not the case!) then I could instead use srctime to do the delayed scheduling and I wouldn't need my additional code. This would be more efficient, as especially if I am using a busy waiting technique I'd need it both in my code and then in SRT. I was hoping I could only have to do it in SRT!

**Comment by maxlovic** [comment]
@oviano  You could use `SRTO_MAXBW` to limit the sending rate. This way you can add packets to the send buffer as soon as you have them, but they will be send not faster that at MAXBW.
Although this way you should set max bandwidth a bit higher to give some space for packet retransmission. And this set up will not work exactly how you like it to work.
A good use case though.

**Comment by oviano** [comment]
Right, thanks.

What would be the implication of making SRT just send immediately (so I guess hacking it so that the scheduled send time is always entertime_tk) and then doing the sleep delay in my own code also taking account of what I want to achieve with respect to scheduling the packets within a frame?

**Comment by ethouris** [comment]
I'd rather propose that you still submit packets to SRT with the same time gaps as the time gaps defined by the player, even though you'd end up with making the possible default source time effectively 5us later than the time declared as source time.

The rule is simple: the "source time" is the time when provision of the data "should happen". By specifying this time, even though it would be more-less the same time when you submit the data to SRT, you avoid this "more-less" to cause discrepancy on the receiver side.

**Comment by oviano** [comment]
> @oviano You could use `SRTO_MAXBW` to limit the sending rate. This way you can add packets to the send buffer as soon as you have them, but they will be send not faster that at MAXBW.
> Although this way you should set max bandwidth a bit higher to give some space for packet retransmission. And this set up will not work exactly how you like it to work.
> A good use case though.

Alternatively, twisting that around if I hack this line in LiveCCC...

m_dPktSndPeriod = 1000 * 1000.0 * (pktsize / m_llSndMaxBW);

...to read...

m_dPktSndPeriod = 0;

...then I get the instant sending I need and can control the sending rate from my application.

This is not quite the same as setting maxbw=0 (i.e. INFINITE) as the calculation above still resolves to around 12us or so for a packet size of 1500, which leads to either too much sleeping (if no busy waiting) or higher CPU (if busy waiting). If I just set the send period to zero as above it skips the whole sleep/busy wait entirely.

**Comment by ethouris** [comment]
I had some problem with having `m_dPktSndPeriod` set to zero, as somewhere there is some calculation done that uses this as a divisor - and you quickly end up with division by zero.

BTW. setting this to minimum value from upside usually doesn't change anything in the live mode, as your source will still send packets slower. If it gets to be faster, you should set MAXBW to a value higher than the default BW_INFINITE.

**Comment by oviano** [comment]
Thanks. I did check through as I considered the possibility of a /0 but I couldn't find one, I'll check again.

In terms of what it changes - it stops it doing *anything* at all in the sleepto loop. In the case of *not* using busy waiting then it eliminates the too-long sleep on Windows which would otherwise occur even for a small send period (granularity problem). If busy waiting is defined, then it obviously stops the busy wait and the associated CPU.

**Comment by oviano** [comment]
So to summarise, I propose adding to the API:

(srt.h)
SRT_API uint64_t srt_gettime();

(srt_c_api.cpp)
uint64_t srt_gettime()
{
	return CUDT::get_time();
}

(core.h, CUDT class)
static uint64_t get_time();

(core.cpp)
uint64_t CUDT::get_time()
{
	return CTimer::getTime();
}

...this then allows setting MSGCTRL.srctime to the same kind of time as used internally. This means that I have removed my application code that was delaying calling srt_send() and instead calling srt_sendmsg2() straightaway when I have some data but passing through a suitable srctime instead, based on srt_gettime() so that on reception in my player the packets appear at my intended time.
