### ISSUE TITLE
Q: SRTT_LIVE - does it actually or deprecated ?

### ISSUE THREAD

**Issue by m-garanin** [Haivision/srt#940]
I grepped  "SRTT_LIVE"  and not found any usage in examples 
It commented in recvlive.cpp . 
Can you please explain: does this flag mean or not?

**Comment by ethouris** [comment]
This is the default value for `SRTO_TRANSTYPE` option. That's why you will probably see the only value in use as `SRTT_FILE`.

**Comment by maxlovic** [comment]
Please also refer to the "Transmission modes" section of the [API.md](https://github.com/Haivision/srt/blob/master/docs/API.md#transmission-modes)
