### ISSUE TITLE
Remove reference wrappers

### ISSUE THREAD

**Issue by maxsharabayko** [Haivision/srt#945]
We have excessive usage of reference wrappers in several places.

There are two points of the agreement:
1.	Don’t add new reference wrappers.
2.	Get rid of the existing wrappers.

### Why don’t we need reference wrappers?

The purpose of reference wrappers is to wrap a reference and put it to some container like `std::vector`.

In SRT they are used as function arguments instead of a simple reference `&`.
For me this worsens the readability of code.

Furthermore, in most of the places additional variable is introduced to unwrap the wrapper.

Example:
```
int CUDT::sendmsg2(const char *data, int len, ref_t<SRT_MSGCTRL> r_mctrl)
{
    SRT_MSGCTRL &mctrl       = *r_mctrl;
```
Example 2.
```
EncryptionStatus CCryptoControl::encrypt(ref_t<CPacket> r_packet SRT_ATR_UNUSED)
{
    CPacket& packet = *r_packet;
```

**Comment by maxlovic** [comment]
Duplicates #943
