### ISSUE TITLE
Unable to send/receive data on different box.

### ISSUE THREAD

**Issue by aamirrad** [Haivision/srt#96]
I am running the stransmit application with the following commands for both server and client running on the same box and the transmit seems to be working.
./stransmit udp://239.153.13.16:1234 srt://127.0.0.1:1234/?mode=server
./stransmit srt://127.0.0.1:1234/?mode=client udp://239.235.13.2:1234

however, when I try to run the client and server on different box, the transmit of the data stops working.
./stransmit udp://239.153.13.16:1234 srt://239.212.212.212:1234/?mode=server
./stransmit srt://239.212.212.212:1234/?mode=client udp://239.235.13.2:1234

Can someone please help.

**Comment by heidabyr** [comment]
Hi, it looks like you are trying o use a MultiCast address for the SRT transmission? You should use the IP address of the server on the caller side, so it calls the server:

Server listens on one of its own network interfaces, in this example 1.2.3.4:
./stransmit udp://239.153.13.16:1234 srt://1.2.3.4:1234/?mode=server

Client calls out to the server IP and port:
./stransmit srt://1.2.3.4:1234/?mode=client udp://239.235.13.2:1234

- Marc

**Comment by ethouris** [comment]
And one more thing: if you want to **read** from the multicast UDP address, your application must first subscribe to the IGMP group. This is achieved by putting `@` character in front of the IP address.

**Comment by aamirrad** [comment]
Thanks. that worked.
So there is no any way to send the SRT output on a multicast and have the other side receive from that multicast? It is always one-to-one connection?

**Comment by heidabyr** [comment]
Yes, SRT is a point to point protocol.
