### ISSUE TITLE
[FR] Packet Filter build option

### ISSUE THREAD

**Issue by maxsharabayko** [Haivision/srt#968]
Certain appliances might not need packet filtering and FEC functionality.
Might be a good idea to provide a build option `ENABLE_PACKET_FILTER`, that will exclude or include FEC functionality.
This will also produce smaller size of the binary output when packet filter is disabled.

**Comment by ethouris** [comment]
Turning off the packet filtering functionality completely from the code is impossible. Even if you block those parts that are executed under a condition of having a filter, there are still more changes done to enable filter-processing. You can at best turn off the builtin FEC filter, but I think the size difference you gain out if it is rather negligible.

**Comment by maxsharabayko** [comment]
> Turning off the packet filtering functionality completely from the code is impossible.

Possible, but probably does not make sense in comparisson to the effort required. Closing as "won't implement".
