### ISSUE TITLE
Strange feedback bandwidth

### ISSUE THREAD

**Issue by m-garanin** [Haivision/srt#978]
I do SRT Streamer for Windows and during test sometimes 
I got very strange picture on Wifi Performance screen:  I got heavy feedback traffic. 
(of course I'm ensure not other apps use wifi, and do test few times).
I understand about control feedback traffic but why it's so much....

GOOD case (receiver side shows 2-3% loss):

![SRT_GOOD](https://user-images.githubusercontent.com/3765362/69717905-0a6f9f80-111e-11ea-8032-26fb2e96ed39.PNG)

BAD  case  (receiver  shows 50+% loss)

![SRT_BAD](https://user-images.githubusercontent.com/3765362/69717904-09d70900-111e-11ea-822b-ce55435dc468.PNG)

**Comment by m-garanin** [comment]
![Screenshot 2019-11-27 at 15 50 16](https://user-images.githubusercontent.com/3765362/69727221-26317080-1133-11ea-900c-5282e02e3145.png)

**Comment by maxlovic** [comment]
Wireshark capture can help. One NAK packet (loss report) takes at least 20 bytes ([overhead chart](https://maxlovic.github.io/srtcookbook/protocol/overhead/)). Still I agree it seems higher than you could expect.
Would you kindly do the network capture for the bad case?

**Comment by m-garanin** [comment]
ok, I will try do Wireshark capture. 
But now after few tests I can say:  the issue presents **only** when receiver is macOS-app (my srt lib build from head)  and sender is Win-app (use your srt lib build).

When sender and receiver are both Windows-app (and use same srt library build from you) - no issue.

**Comment by J-Rogmann** [comment]
Hello @m-garanin 
Were you able to get a wireshark capture, with that high rate of return traffic? This is really unexpected behaviour and I would like to take a look at it.
What parameters you used for that particular stream?

**Comment by mbakholdina** [comment]
Hi @m-garanin ! Do you have any updates on the @J-Rogmann questions from the previous comment?

**Comment by m-garanin** [comment]
sorry, I have not ability Wireshark analyse.
But I think I have new info.
I tested [iOS app ----srt--->SRT Server (Windows/macOs)]. 
So if I use Wifi (iOS app and Desktop in same Wifi) then I got heavy drops 20+%.
If I use LTE for iOS for send stream to same Desktop then I got perfect stream.

**Comment by ethouris** [comment]
To grab the traffic capture you only need tcpdump. Simply grab the traffic on the UDP port that is assigned to the listener address. Or simply whole traffic, if your devices do not use the network for more things than this transmission.

**Comment by mbakholdina** [comment]
Hi @m-garanin, please find the useful article [Using TShark & Wireshark to analyse SRT traffic](https://srtlab.github.io/srt-cookbook/how-to-articles/how-to-setup-wireshark-for-srt-traffic-analysis/) which will give you some tips on collecting Wireshark dump.

**Comment by J-Rogmann** [comment]
ticket can be closed. With new WiFi setup in 5GHz band this issue doesn't appear anymore.
