### ISSUE TITLE
how I can send VIP ("very important packet")

### ISSUE THREAD

**Issue by m-garanin** [Haivision/srt#998]
I have workflow [caller ------ srt(video feed) -----> server]
sometimes I want send feedback packet :    
[caller <----- your camera on/off air ---- server ] (and caller-app turn on/off green led).
This packet very important I want be sure - receiver got it.

So if I do simple "srt_send(VIP)" then my packet can be lost in theory, correct?  (I always see 2% loss on srt-feed) .
So:  what is way for be sure for transfer VIP ?

**Comment by maxlovic** [comment]
At the moment the only way to confirm the delivery of a packet is to deliver over a link with TL packet drop disabled (see `TLPKTDROP` in docs/API.ms).
Basically `SRTO_TRANSTYPE=FILE` and `SRTO_MESSAGEAPI=ON` provide the required operation mode. However, this requires another SRT connection. It can be established over the same UDP port.

Maybe a feature request for a special flag in SRT DATA packet, that does not allow to drop the packet, and ensures it is delivered.

**Comment by m-garanin** [comment]
thank you, I got it. 
And yes please add special flag "feauture request"  for this "feedback"-case:  interleave audio-feedback(NON-VIP, allow drops, live) and tally-signal (VIP).
